### ISSUE TITLE
SeqIO - parsing UniProt-XML throws error

### ISSUE THREAD

**Issue by hellingerbioinf** [biopython/biopython#1004]
## Error Description
Parsing UniProt-XML throws an error because apparently SeqIO cannot handle recently changed tags. `<begin status="unknown"/>` as well as `<end status="unknown"/>` appear to be the culprits.

### File:
[ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz](url)

### Code:
```python
#!/usr/bin/python

import sys
import gzip
from Bio import SeqIO

filename='uniprot_sprot.xml.gz'

sys.stderr.write("Reading %s..." % filename)
with gzip.open(filename) as infile:
  for entry in SeqIO.parse(infile, "uniprot-xml"):
    print entry.id
```

## Workaround
In the meantime it is possible to correct the faulty tags by sed-substitutions as a **temporary workaround**:
`zcat uniprot_sprot.xml.gz | sed 's/<begin status="unknown"\/>/<begin position="1"\/>/' | sed 's/<end status="unknown"\/>/<end position="1"\/>/' > uniprot_sprot.workaround.xml`

**Comment by hellingerbioinf** [comment]
Feature tags do not seem to be affected - only **begin** and **end** in comments.

**Comment by peterjc** [comment]
This looks like the issue raised and fixed in pull request #966 last month (after Biopython 1.68 was released).

Which version of Biopython are you using, and could you try installing Biopython from GitHub as that seems to work for me?

Do you think we should mention this explicitly in the ``NEWS`` file for Biopython 1.69?

**Comment by hellingerbioinf** [comment]
Yes, the issue raised in [#966](https://github.com/biopython/biopython/pull/966) seems to be exactly the same.

Our workgroup is running **Python 2.7.12** with **Biopython 1.68** in a multi-user environment, which is centrally administered. Our Admin actually uses **pip** for the installation, so we will have to wait until 1.69 is out and meanwhile fall back to correcting the tags.

Yes, probably a little reference in the news might be helpful.

Thanks a lot for your assistance!

**Comment by peterjc** [comment]
Added to the ``NEWS`` file. Closing issue.

Thanks for the feedback 👍
