### ISSUE TITLE
Use self.assertIn in our unit tests

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1006]
Until recently we supported Python 2.6, where the ``unittest`` library did not support the ``self.assertIn(search_term, thing_to_search)`` method meaning we used ``self.assertTrue(search_term in thing_to_search)`` instead, often with a message term.

I fixed a couple just now where there was a TODO comment: 0da38441dd3a220d62bd3edf09baf35dc2bd5c32

There are over 200 of these examples remaining, e.g.

```
$ cd Tests/
$ grep assertTrue *.py | grep " in "
common_BioSQL.py:        self.assertTrue("biosql-test" in server)
common_BioSQL.py:        self.assertTrue("biosql-test2" in server)
common_BioSQL.py:        self.assertTrue("biosql-test" in server)
...
```

Fixing these by hand would be extremely tedious, but with a little regular expression knowledge you can probably do this in one line of awk or perl etc. Or write a Python script to do it?

**Comment by souravsingh** [comment]
I would like to take a stab at the issue

**Comment by peterjc** [comment]
Great - if you can solve this using awk or a similar approach, it would be great if you could post your solution here too.
