### ISSUE TITLE
CEL files version 4 not supported

### ISSUE THREAD

**Issue by picrin** [biopython/biopython#1008]
biopython does not support CEL files version 4.

running the following code in python:

    from Bio.Affy.CelFile import *
    with open("Affy_v4.CEL") as c:
        record = read(c)
    print(record.intensities)

produces

    None

if `"Affy_v4.CEL"` is a path to an Affymetrix CEL file version 4.

I have written a parser for Affymetrix CEL files version 4 and made it available here: https://github.com/picrin/CELparser

I'd be happy to incorporate this code into biopython if this is decided to be desirable.

**Comment by peterjc** [comment]
Thank you for your offer :)

To me this looks like a very sensible addition to Biopython - it is a relatively small amount of code, and we already support for older versions of the format.

Note we would have to make sure this support Python 2.7 as well as Python 3.3 onwards (which from looking at your code shouldn't be too hard - we've got other binary parsers where we've solve most of the likely issues), and also include some functional tests.

I presume you have access to real data and could provide some sample data in this format to include for testing?

I don't think we have anyone looking after ``Bio.Affy`` module, so if you are interested in that responsibility as well, even better.

Are you happy to dual licence your contributions under both the _Biopython License Agreement_ *and* the _BSD 3-Clause License_? See #898.

**Comment by picrin** [comment]
> To me this looks like a very sensible addition to Biopython - it is a relatively small amount of code, and we already support for older versions of the format.

I also thought it was a sensible addition. Obviously I will have to make sure that my improvement does not introduce a regression, i.e. downstream code depending on Bio.Affy still works after my addition.

> Note we would have to make sure this support Python 2.7 as well as Python 3.3 onwards (which from looking at your code shouldn't be too hard - we've got other binary parsers where we've solve most of the likely issues), and also include some functional tests.

My code snippet already works both under python 2.7 and python 3.

> I presume you have access to real data and could provide some sample data in this format to include for testing?

I've been told that the data I'm working with can't be shared at the moment, but Affymetrix provides plenty of CEL version 4 data [on their website](http://www.affymetrix.com/support/technical/sample_data/exon_array_data.affx).

It is a different question if you *really* want this data in your git repository. A single analysis weights 60 Mb. Appropriate place for such big file would be github's LFS or [some other solution of this kind](http://stackoverflow.com/questions/540535/managing-large-binary-files-with-git/31390846#31390846)

> I don't think we have anyone looking after Bio.Affy module, so if you are interested in that responsibility as well, even better.

Let's start with one small change and we can see how it goes.

> Are you happy to dual licence your contributions under both the Biopython License Agreement and the BSD 3-Clause License? See #898.

Yes.

Do you have a Contrib.md outlining best practices for contributing to the project? Most importantly, how would you like to receive the change? On http://biopython.org/wiki/SourceCode it is suggested that contributors receive collaborator access. Would you not rather receive the change as a pull request?

I have signed up to biopython-dev mailing list.

**Comment by picrin** [comment]
This gives a rough idea of what the changes might look like. While still work in progress, it might give a general flavour of [what I'm doing](https://github.com/picrin/biopython/tree/affyV4)

I should be able to finish it off some time next week.

**Comment by picrin** [comment]
I have finished work relating to this issue & raised a pull request.

**Comment by peterjc** [comment]
Website hopefully a little clearer now: https://github.com/biopython/biopython.github.io/commit/ee5b1beb2342b1db8097942b0fe8539cd0651077

**Comment by picrin** [comment]
I've fixed linting issues and acknowledged issues.

**Comment by picrin** [comment]
I've fixed the remaining issues with the pull request, except for changing the naming convention of `read3` and `read4` methods.

I'm considering 2 options:

1. Break the convention of the module and use `read_v3` or similar
2. Keep the convention of the module and use `readV3`.

**Comment by peterjc** [comment]
(I replied to the local linting question on #1011, in essence install and run the command line tool ``pep8`` using the same setting we're using on TravisCI)

**Comment by peterjc** [comment]
See also #168
