### ISSUE TITLE
tests do not work on linux with the most recent master 

### ISSUE THREAD

**Issue by picrin** [biopython/biopython#1010]
4 tests never finish on linux:
    Tests/test_Entrez_online.py
    Tests/test_KEGG_online.py
    Tests/test_KGML_nographics.py
    Tests/test_NCBI_qblast.py

6 tests fail (stderr attached)

[failure.txt](https://github.com/biopython/biopython/files/614371/failure.txt)

stdout is:
    running test
    Python version: 2.7.11 (default, Sep  2 2016, 14:51:16) 
    [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
    Operating system: posix linux2

**Comment by peterjc** [comment]
I assume ``test_Affy`` is something you are working on?

At least some of your test failures suggest you didn't compile the C bits of Biopython before running the tests (you need to run ``python setup.py build`` first). e.g. ``test_QCPSuperimposer`` and ``_pwm``.

I know some of the TogoWS services seem to be down - I've not yet reported that to them. In general you can skip the network tests with:

```
python setup.py build
cd Tests
python run_tests.py --offline
```

**Comment by picrin** [comment]
Thanks, all the test cases pass.

**Comment by picrin** [comment]
I thought it would be a good idea to include this in the official README.md.

**Comment by peterjc** [comment]
Since this is working, I'm going to close this issue. See discussion on pull request #1024 about how best to clarify the documentation about compiling before testing.
