### ISSUE TITLE
Test suite leaving behind extra files

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1013]
This came up on pull request #983 where some stray files from the test suite were accidentally checked in. Ideally out test suite should not leave any stray files behind.

Where this is impractical to avoid, they should be added to ``.gitignore`` as in 2b0f33fd4bc775e812b17ad18a3ce5d291e72516 for:

```
Doc/examples/other_trees.nwk
```

We also use the ``.gitignore`` approach for graphical output from test files which ought to be manually checked occasionally, since we have not automated that.

For the Tutorial doctest system via ``Tests/test_Tutorial.py`` perhaps we need a mechanism for removing output files? The doctests are a particular problem because natural examples will produce files in the current directory (here using a temp file is an unwanted distraction). This leads to nasty workarounds like https://github.com/biopython/biopython/blob/biopython-168/Bio/SeqIO/SffIO.py#L229

However, in general the ``Tests/test_*.py`` scripts should clean up after themselves and/or use ``tempfile`` rather than writing output in the current directory. e.g. ``test_TreeConstruction.py`` and ``test_Consensus.py`` needed fixing - see da4ed3831fd3d9fc7cef6c8fdd2f07bc0e689842

Note before closing this issue, someone needs to audit this with a full test-suite run with all the optional dependencies - the command line tool wrappers often generate small test output files.

**Comment by peterjc** [comment]
OK, I've fixed the problems I knew about - help wanted to see what else needs cleaning up.

**Comment by peterjc** [comment]
With #1747 merged, another group of unwanted files from the test suite have been fixed.

Leaving this issue open pending a complete audit.

**Comment by jvfe** [comment]
Don't really know for sure because I can't run all tests locally, but from what I gather PR #2203 closes this issue, @peterjc

**Comment by peterjc** [comment]
Hopefully - I'm working from home and also don't have absolutely everything installed right now. Closing.
