### ISSUE TITLE
Add ungap method to the SeqRecord?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1017]
Originally filed by me on our old RedMine issue tracker as https://redmine.open-bio.org/issues/3060 back on 2010-04-21

> Biopython 1.53 added an ungap method to the Seq object.
> 
> This is a possible enhancement request to add a matching ungap method to the SeqRecord object, where the per-letter-annotation and features should be adjusted to match.
> 
> My motivating example is to take an ACE file loaded with SeqIO, remove the gaps, and output the contigs as FASTQ or QUAL files. This requires the per-letter-annotation to be sliced to match the ungapped sequence.
> 
> Likewise any features fully contained within ungapped regions should be retained and their co-ordinates shifted. I'm not sure if we should do anything about features spanning a gap - the simple option which I have implemented is they are lost. This is done via the existing SeqRecord slicing and addition code.
> 
> Patch to follow...
> 
> See also Bug 3054 for adding upper and lower methods to the SeqRecord, and the broader discussion on Bug 2351 about strings, Seq and SeqRecord objects.

First patch:

> Patch to Bio/SeqRecord.py to add ungap method
> 
> This includes a basic doctest, and some debug checks (assert statements) which could be removed after more testing.
> 
> Patch applied to this branch:
> http://github.com/peterjc/biopython/tree/seqrecord-rc

Next comment:

> I've been trying building SeqFeature objects for the reads in an ACE file,
> http://github.com/peterjc/biopython/tree/ace-reads
> 
> In this case when I call the SeqRecord ungap method, many of my read features
> are lost with the current implementation (because they included gaps). This
> also showed the ungap code to be quite slow for features. I'm going to have
> another look at this.

Second patch:

> I've been trying building SeqFeature objects for the reads in an ACE file,
> http://github.com/peterjc/biopython/tree/ace-reads
> 
> In this case when I call the SeqRecord ungap method, many of my read features
> are lost with the current implementation (because they included gaps). This
> also showed the ungap code to be quite slow for features. I'm going to have
> another look at this.
> 
> My new code handles SeqFeature ungapping so as to preserve all the features by adjusting their end points. This is also much faster:
> 
> http://github.com/peterjc/biopython/tree/ungap2

**Comment by Caiofcas** [comment]
Is this still an issue? Since the `ungap` method in `Seq` has been deprecated I don't know if this is still wanted.

**Comment by peterjc** [comment]
Good point, with the deprecation of the ``Seq`` object's ``.ungap`` there is no reason to add it to the ``SeqRecord``. Closing, thank you.
