### ISSUE TITLE
Entrez.parse fails on latest PubMed XML from NCBI Entrez efetch

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1027]
Reported on the mailing list:

http://mailman.open-bio.org/pipermail/biopython/2016-December/016043.html

Example based on our documentation, reduced test case:

``` python
from Bio import Entrez
Entrez.email = "Your.Name.Here@example.org"
handle = Entrez.efetch("pubmed", id="19304878,14630660", retmode="xml")
records = list(Entrez.parse(handle))
```

Excepted result is a list of length two, actual result is an exception from line 304 of ``Bio/Entrez/Parser.py``:

```
ValueError: The XML file does not represent a list. Please use Entrez.read instead of Entrez.parse
```

Note this is using a new DTD file, although manually adding that to Biopython under `Bio/Entrez/DTDs` makes no difference to this problem.

https://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_170101.dtd

**Comment by Boghog** [comment]
Thanks Peter for posting this!

**Comment by mdehoon** [comment]
The error message is correct. You should use Entrez.read.

**Comment by Boghog** [comment]
Then how does one parse the output?  Entrez.parse used to work, but no longer.  Apparently NCBI has made changes to their xml.

If one adds "['PubmedArticle']" to line 302 of /Bio/Entrez/Parse.py so that it reads:

records = self.stack[0]['PubmedArticle']

the error message is returned, but it mysteriously returns only the strings "PubmedArticle" and "PubmedBookArticle" and not the citation.  Any ideas?

**Comment by peterjc** [comment]
@mdehoon but using ``Entrez.parse`` used to work and our docstrings show this very example:

https://github.com/biopython/biopython/blob/589bc075ace24cb29bcd69c9789963df7febeb4d/Bio/Entrez/__init__.py#L80

If this is no longer possible, then this example needs updating - but my guess something needs fixing in the parser to cope with an NCBI change?

**Comment by MattDMo** [comment]
Has anyone been in contact with the Entrez dev team to see what the changes were?

**Comment by peterjc** [comment]
I have not. I'm on holiday otherwise I might have tried to investigate further. I would start by requesting a matching version of the example file ``Tests/Entrez/pubmed2.xml`` (two records) from the current Entrez Fetch, can compare the two with diff.

**Comment by peterjc** [comment]
On the mailing list @mdehoon wrote http://mailman.open-bio.org/pipermail/biopython/2016-December/016053.html

> ...
> There is only one difference between Entrez.parse and Entrez.read: Entrez.read parses the whole data at once, while Entrez.parse iterates through the data.There is no difference in the complexity of the data structure returned by Entrez.parse and Entrez.read: in both cases, the data structure is consistent with what NCBI specifies in the DTD referenced in the XML.Now, Entrez.parse only makes sense if the data structure returned by NCBI corresponds to a list in Python. If it doesn't, then iterating through the XML data makes no sense, and you should use Entrez.read instead.
>
> In this particular case, NCBI has changed the data structure such that Entrez.parse is not appropriate and you should use Entrez.read instead. This does not mean that Entrez.parse is broken.
>
> We do need to update the Biopython documentation though.

I'd like to know what exactly has changed, as it would be nice if we can continue to iterate over a list-list data structure.

**Comment by mdehoon** [comment]
@peterjc  

> If this is no longer possible, then this example needs updating - but my guess something needs fixing in the parser to cope with an NCBI change?

No changes are needed to the parser. The following works:
```python
>>> from Bio import Entrez
>>> Entrez.email = 'myemail@example.com'
>>> handle = Entrez.efetch("pubmed", id="19304878,14630660", retmode="xml")
>>> record = Entrez.read(handle)
>>> for article in record['PubmedArticle']:
...    print(article['MedlineCitation']['Article']['ArticleTitle'])
```

**Comment by peterjc** [comment]
Using Python 3,

``` python
>>> from Bio import Entrez
>>> Entrez.email = "p.j.a.cock@googlemail.com"
>>> with open("pubmed2a.xml", "w") as out_handle:
...     with Entrez.efetch("pubmed", id="11748933,11700088", retmode="xml") as net_handle:
...         out_handle.write(net_handle.read())
... 
15413
```

Then,

```
$ diff -w pubmed2.xml pubmed2a.xml
2c2
< <!DOCTYPE PubmedArticleSet PUBLIC "-//NLM//DTD PubMedArticle, 1st January 2008//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/pubmed_080101.dtd">
---
> <!DOCTYPE PubmedArticleSet PUBLIC "-//NLM//DTD PubMedArticle, 1st January 2017//EN" "https://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_170101.dtd">
5,6c5,6
<     <MedlineCitation Owner="NLM" Status="MEDLINE">
<         <PMID>11748933</PMID>
---
>     <MedlineCitation Status="MEDLINE" Owner="NLM">
>         <PMID Version="1">11748933</PMID>
44d43
<             <Affiliation>Dipartimento di Scienze Ambientali, Università degli Studi della Tuscia, 01100 Viterbo, Italy.</Affiliation>
49a49,51
>                     <AffiliationInfo>
>                         <Affiliation>Dipartimento di Scienze Ambientali, Università degli Studi della Tuscia, 01100 Viterbo, Italy.</Affiliation>
>                     </AffiliationInfo>
89,90c91,92
<                 <PublicationType>Journal Article</PublicationType>
<                 <PublicationType>Research Support, Non-U.S. Gov't</PublicationType>
---
>                 <PublicationType UI="D016428">Journal Article</PublicationType>
>                 <PublicationType UI="D013485">Research Support, Non-U.S. Gov't</PublicationType>
94c96
<             <Country>United States</Country>
---
>             <Country>Netherlands</Country>
96a99
>             <ISSNLinking>0011-2240</ISSNLinking>
101c104
<                 <DescriptorName MajorTopicYN="N">Animals</DescriptorName>
---
>                 <DescriptorName UI="D000818" MajorTopicYN="N">Animals</DescriptorName>
104,105c107,108
<                 <DescriptorName MajorTopicYN="N">Cell Membrane</DescriptorName>
<                 <QualifierName MajorTopicYN="N">ultrastructure</QualifierName>
---
>                 <DescriptorName UI="D002462" MajorTopicYN="N">Cell Membrane</DescriptorName>
>                 <QualifierName UI="Q000648" MajorTopicYN="N">ultrastructure</QualifierName>
108,109c111,112
<                 <DescriptorName MajorTopicYN="N">Cryopreservation</DescriptorName>
<                 <QualifierName MajorTopicYN="Y">methods</QualifierName>
---
>                 <DescriptorName UI="D015925" MajorTopicYN="N">Cryopreservation</DescriptorName>
>                 <QualifierName UI="Q000379" MajorTopicYN="Y">methods</QualifierName>
112c115
<                 <DescriptorName MajorTopicYN="N">Male</DescriptorName>
---
>                 <DescriptorName UI="D008297" MajorTopicYN="N">Male</DescriptorName>
115c118
<                 <DescriptorName MajorTopicYN="N">Microscopy, Electron</DescriptorName>
---
>                 <DescriptorName UI="D008854" MajorTopicYN="N">Microscopy, Electron</DescriptorName>
118c121
<                 <DescriptorName MajorTopicYN="N">Microscopy, Electron, Scanning</DescriptorName>
---
>                 <DescriptorName UI="D008855" MajorTopicYN="N">Microscopy, Electron, Scanning</DescriptorName>
121,122c124,125
<                 <DescriptorName MajorTopicYN="N">Nuclear Envelope</DescriptorName>
<                 <QualifierName MajorTopicYN="N">ultrastructure</QualifierName>
---
>                 <DescriptorName UI="D009685" MajorTopicYN="N">Nuclear Envelope</DescriptorName>
>                 <QualifierName UI="Q000648" MajorTopicYN="N">ultrastructure</QualifierName>
125,127c128,130
<                 <DescriptorName MajorTopicYN="N">Sea Bream</DescriptorName>
<                 <QualifierName MajorTopicYN="Y">anatomy &amp; histology</QualifierName>
<                 <QualifierName MajorTopicYN="N">physiology</QualifierName>
---
>                 <DescriptorName UI="D021541" MajorTopicYN="N">Sea Bream</DescriptorName>
>                 <QualifierName UI="Q000033" MajorTopicYN="Y">anatomy &amp; histology</QualifierName>
>                 <QualifierName UI="Q000502" MajorTopicYN="N">physiology</QualifierName>
130,132c133,135
<                 <DescriptorName MajorTopicYN="N">Semen Preservation</DescriptorName>
<                 <QualifierName MajorTopicYN="N">adverse effects</QualifierName>
<                 <QualifierName MajorTopicYN="Y">methods</QualifierName>
---
>                 <DescriptorName UI="D012662" MajorTopicYN="N">Semen Preservation</DescriptorName>
>                 <QualifierName UI="Q000009" MajorTopicYN="N">adverse effects</QualifierName>
>                 <QualifierName UI="Q000379" MajorTopicYN="Y">methods</QualifierName>
135c138
<                 <DescriptorName MajorTopicYN="Y">Sperm Motility</DescriptorName>
---
>                 <DescriptorName UI="D013081" MajorTopicYN="Y">Sperm Motility</DescriptorName>
138,140c141,143
<                 <DescriptorName MajorTopicYN="N">Spermatozoa</DescriptorName>
<                 <QualifierName MajorTopicYN="N">physiology</QualifierName>
<                 <QualifierName MajorTopicYN="Y">ultrastructure</QualifierName>
---
>                 <DescriptorName UI="D013094" MajorTopicYN="N">Spermatozoa</DescriptorName>
>                 <QualifierName UI="Q000502" MajorTopicYN="N">physiology</QualifierName>
>                 <QualifierName UI="Q000648" MajorTopicYN="Y">ultrastructure</QualifierName>
159a163,169
>             <PubMedPubDate PubStatus="entrez">
>                 <Year>2001</Year>
>                 <Month>12</Month>
>                 <Day>26</Day>
>                 <Hour>10</Hour>
>                 <Minute>0</Minute>
>             </PubMedPubDate>
172,173c182,183
<     <MedlineCitation Owner="NLM" Status="PubMed-not-MEDLINE">
<         <PMID>11700088</PMID>
---
>     <MedlineCitation Status="PubMed-not-MEDLINE" Owner="NLM">
>         <PMID Version="1">11700088</PMID>
211d220
<             <Affiliation>INFM and Department of Physics, University of L'Aquila, I-67100 L'Aquila, Italy.</Affiliation>
216a226,228
>                     <AffiliationInfo>
>                         <Affiliation>INFM and Department of Physics, University of L'Aquila, I-67100 L'Aquila, Italy.</Affiliation>
>                     </AffiliationInfo>
246c258
<                 <PublicationType>Journal Article</PublicationType>
---
>                 <PublicationType UI="D016428">Journal Article</PublicationType>
252a265
>             <ISSNLinking>1090-7807</ISSNLinking>
270a284,290
>             <PubMedPubDate PubStatus="entrez">
>                 <Year>2001</Year>
>                 <Month>11</Month>
>                 <Day>9</Day>
>                 <Hour>10</Hour>
>                 <Minute>0</Minute>
>             </PubMedPubDate>
281d300
< 
```

i.e. Some minor differences in attribute order, and extra attributes like UI, plus the tag ``<Affiliation>`` was replaced with ``<AffiliationInfo>``, and new tags ``<ISSNLinking>`` and ``<PubMedPubDate>``.

Interestingly if I take the old ``pubmed2.xml``  file and switch the DTD line to use the ``pubmed_170101.dtd`` one then we get the ``Entrez.parse`` problem. Note this would likely fail XML validation due to things like the affiliation tag change and new tags etc.

**Comment by mdehoon** [comment]
I have updated the tutorial documentation and the docstring. I believe we can close this issue now.

**Comment by mdehoon** [comment]
```
<!ELEMENT       PubmedArticleSet (PubmedArticle | PubmedBookArticle)+>
```
means that we either have multiple PubmedArticles, or we have multiple PubmedBookArticles, but in any case we have a list of items of the same kind. This is why we can treat it as a list in Python.

```
<!ELEMENT	PubmedArticleSet ((PubmedArticle | PubmedBookArticle)+, DeleteCitation?) >
```
means that we have multiple PubmedArticles, or multiple PubmedBookArticles, but additionally we may also have a DeleteCitation. Now we need to distinguish PubmedArticles (or PubmedBookArticles) from DeleteCitations, and therefore we need to use a dictionary in Python.

The parse() function only applies if the output is a list. With the new XML data returned by NCBI, this is no longer the case, and you should use read() instead.

**Comment by peterjc** [comment]
Thanks for the explanation @mdehoon.

Can you think of a use case (or know of a real example) where the NCBI would use a ``DeleteCitation`` here? It seems odd to me, and perhaps a mistake.

**Comment by apiljic** [comment]
In case it helps the discussion, I emailed info@ncbi.nlm.nih.gov (it was a few weeks ago) asking if they changed something on their end and got a reply only stating that: "PubMed XML structures do change, Updated DTD specs will be released along with the file structure changes, which is linked at the top of the efetch returned XML". So it seems that no other (non-standard) change deliberately took place. But now that more information is available, one could send another question and ask very specifically about "DeleteCitation" etc. When I emailed them, they were very friendly and replied immediately.

**Comment by Jhird** [comment]
Here is what I found out hoping that it helps.

BEFORE the 2017 update, one could parse PUBMED records using:

*from Bio import Entrez
Entrez.email = "Your.Name.Here@example.org"
handle = Entrez.efetch("pubmed", id="19304878,14630660", retmode="xml")
records = Entrez.parse(handle)*

That would make "records" a generator object from which individual records could be parsed. However, if you want your old scripts to work with the new 2017 update,  you can try using:

*from Bio import Entrez
Entrez.email = "Your.Name.Here@example.org"
handle = Entrez.efetch("pubmed", id="19304878,14630660", retmode="xml")
records = Entrez.read(handle)
records = records['PubmedArticle']
*

**Comment by peterjc** [comment]
Thanks @Jhird - I think that information was on the associated mailing list thread, but good to have it here. With the NCBI changes to the returned data, this is the current solution.

I have just emailed the NCBI EUtilities team (and CC'd Michiel), and that should let us close this issue one way or the other.

**Comment by peterjc** [comment]
My query has been passed to the NCBI Entrez Utilities developers...

**Comment by peterjc** [comment]
The reply from the NCBI is clear although not enlightening:

> I can confirm that the change was deliberate, but I have no other information available to me regarding specific changes other than what is stated in the DTD header.

Closing issue, unfortunately people using ``Bio.Entrez`` will as discussed above have to update their scripts due to the NCBI PubMed XML/DTD change.

**Comment by Gotojail** [comment]
> Reported on the mailing list:
> 
> http://mailman.open-bio.org/pipermail/biopython/2016-December/016043.html
> 
> Example based on our documentation, reduced test case:
> 
> ```python
> from Bio import Entrez
> Entrez.email = "Your.Name.Here@example.org"
> handle = Entrez.efetch("pubmed", id="19304878,14630660", retmode="xml")
> records = list(Entrez.parse(handle))
> ```
> 
> Excepted result is a list of length two, actual result is an exception from line 304 of `Bio/Entrez/Parser.py`:
> 
> ```
> ValueError: The XML file does not represent a list. Please use Entrez.read instead of Entrez.parse
> ```
> 
> Note this is using a new DTD file, although manually adding that to Biopython under `Bio/Entrez/DTDs` makes no difference to this problem.
> 
> https://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_170101.dtd

how could you?
