### ISSUE TITLE
Extra space inserted into multi-line /product qualifiers

### ISSUE THREAD

**Issue by spock** [biopython/biopython#1035]
**test1.gb**:
```
LOCUS       1                      17129 bp    DNA              UNK 01-JAN-1980
DEFINITION  
ACCESSION   1
VERSION     1
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
FEATURES             Location/Qualifiers
     CDS             14996..16366
                     /product="UDP-N-acetylmuramoyl-tripeptide--D-alanyl-D-
                     alanine ligase"
ORIGIN
//
```

**test2.gb** (file written using BioPython):
```
LOCUS       1                      17129 bp    DNA              UNK 01-JAN-1980
DEFINITION  
ACCESSION   1
VERSION     1
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
FEATURES             Location/Qualifiers
     CDS             14996..16366
                     /product="UDP-N-acetylmuramoyl-tripeptide--D-alanyl-D-alani
                     ne ligase"
ORIGIN
//
```

**test.py**:
```
#!/usr/bin/env python3
from Bio import __version__, SeqIO
print('Using BioPython {0}'.format(__version__))
for fname in ['test1.gb', 'test2.gb']:
    record = SeqIO.read(fname, format='genbank')
    print('{0}: {1}'.format(fname, record.features[0].qualifiers['product'][0]))
```

Output:
```
Using BioPython 1.68
test1.gb: UDP-N-acetylmuramoyl-tripeptide--D-alanyl-D- alanine ligase
test2.gb: UDP-N-acetylmuramoyl-tripeptide--D-alanyl-D-alani ne ligase
```

Extra space is added where there is a new line in the genbank file, after `D-` in test1 and after `alani` in test2.

- Is there a way to get multi-line /products without the extra space?
- Alternatively, should I pre-process /product qualifiers (by replacing some of the spaces with newlines, so as to fit into a certain width - e.g. using `textwrap`) before writing out genbank files using BioPython?

**Comment by OscarMaestre** [comment]
By reading the code and docs in Bio/GenBan/Scanner.py it seems that no, it's not possible to get /products without the extra space, at least not now. I think it could be implemented but some changes will be needed.

[http://biopython.org/DIST/docs/api/Bio.GenBank.Scanner.InsdcScanner-class.html#parse_feature](url) states

`Note that no whitespace is removed.`

**Comment by peterjc** [comment]
The GenBank/EMBL INSDC feature table fails to define how to wrap long lines like this were there is no space, nor how to treat line breaks on a hyphen (do you insert a space on parsing or not - sometimes is looks sensible, other times not as the hyphen gets used in many ways in annotation).

Also, Python's own textwrap library is unsuitable for this output use-case, which I regard as a bug http://bugs.python.org/issue28660

Right now the simplest solution is to pre-process any annotation like this to insert a space where you think best.

**Comment by spock** [comment]
I see, thank you for the information!
