### ISSUE TITLE
Possibly rounding error leads to test failure on arm64

### ISSUE THREAD

**Issue by tillea** [biopython/biopython#1038]
Hi,
please have a look at the [build log for arm64](https://buildd.debian.org/status/fetch.php?pkg=python-biopython&arch=arm64&ver=1.68%2Bdfsg-2&stamp=1484497717) of the Debian autobuilders.  It fails due to a test suite error
`AssertionError: 48.190612469753532 != 48.19061828483113 within 5 places`
which is possibly just a rounding error on this architecture and the test could/should be relaxed.
Kind regards, Andreas.

**Comment by peterjc** [comment]
Thanks Andreas. I would agree your diagnosis makes sense, excerpt from the log:

```
======================================================================
FAIL: test_WellRecord (test_phenotype_fit.TestPhenoMicro)
Test basic functionalities of WellRecord objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«BUILDDIR»/python-biopython-1.68+dfsg/.pybuild/pythonX.Y_2.7/build/Tests/test_phenotype_fit.py", line 54, in test_WellRecord
    self.assertAlmostEqual(w.slope, 48.190618284831132, places=5)
AssertionError: 48.190612469753532 != 48.19061828483113 within 5 places

----------------------------------------------------------------------
```

Do you know if this test machine was a Raspberry Pi? I did run the Biopython test suite on one over a year ago, but this phenotype code is relatively new.

@mgalardini is this something you could look at? Does just dropping to ``places=4`` look sensible?

**Comment by tillea** [comment]
Hi Peter,

On Tue, Jan 17, 2017 at 01:25:25PM -0800, Peter Cock wrote:
> Thanks Andreas. I would agree your diagnosis makes sense, excerpt from the log:
> 
> ```
> ======================================================================
> FAIL: test_WellRecord (test_phenotype_fit.TestPhenoMicro)
> Test basic functionalities of WellRecord objects
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/«BUILDDIR»/python-biopython-1.68+dfsg/.pybuild/pythonX.Y_2.7/build/Tests/test_phenotype_fit.py", line 54, in test_WellRecord
>     self.assertAlmostEqual(w.slope, 48.190618284831132, places=5)
> AssertionError: 48.190612469753532 != 48.19061828483113 within 5 places
> 
> ----------------------------------------------------------------------
> ```
> 
> Do you know if this test machine was a Raspberry Pi?

I do not really know but I think its not.  If this might help you fixing
the problem I could ask to be sure.

Kind regards

     Andreas.

-- 
http://fam-tille.de

**Comment by peterjc** [comment]
Ideally we'd reproduce the issue locally, and given a spare evening, I would be able to run the test suite on a Raspberry Pi. But my gut feeling is that isn't needed - so If @mgalardini agrees I think just relaxing the test precision is fine.

**Comment by tillea** [comment]
Hi,

On Tue, Jan 17, 2017 at 01:25:25PM -0800, Peter Cock wrote:
> @mgalardini is this something you could look at? Does just dropping to ``places=4`` look sensible?

I'd like to say that we are a bit in a hurry.  We have only three days
left to get the package into the next Debian stable release.  If you
send me a patch I could simply upload and see whether it works on the
autobuilders (whatever actual arm64 hardware this might be).

Kind regards

       Andreas.

-- 
http://fam-tille.de

**Comment by peterjc** [comment]
Does this work, or do any of the later comparisons also need relaxing?

```
$ git diff
diff --git a/Tests/test_phenotype_fit.py b/Tests/test_phenotype_fit.py
index a010976..4719469 100644
--- a/Tests/test_phenotype_fit.py
+++ b/Tests/test_phenotype_fit.py
@@ -51,7 +51,7 @@ class TestPhenoMicro(unittest.TestCase):
         self.assertEqual(w.model, 'gompertz')
         self.assertAlmostEqual(w.lag, 6.0425868725090357, places=5)
         self.assertAlmostEqual(w.plateau, 188.51404344898586, places=5)
-        self.assertAlmostEqual(w.slope, 48.190618284831132, places=5)
+        self.assertAlmostEqual(w.slope, 48.190618284831132, places=4)
         self.assertAlmostEqual(w.v, 0.10000000000000001, places=5)
         self.assertAlmostEqual(w.y0, 45.879770069807989, places=5)
         self.assertEqual(w.max, 313.0)
```

**Comment by tillea** [comment]
Hi Peter,

On Fri, Jan 20, 2017 at 07:32:32AM -0800, Peter Cock wrote:
> Does this work, or do any of the later comparisons also need relaxing?

Seems it worked nicely:

    https://buildd.debian.org/status/package.php?p=python-biopython

Status is green in all possible cases. :-)

Thanks a lot for the quick help

      Andreas.

-- 
http://fam-tille.de

**Comment by mgalardini** [comment]
Hi all,

really sorry I didn't notice it on time; relaxing the test is of course fine by me.

Marco

**Comment by tillea** [comment]
Hi,
On Mon, Jan 23, 2017 at 03:45:07AM -0800, Marco Galardini wrote:
> really sorry I didn't notice it on time; relaxing the test is of course fine by me.

thanks to Peter's answer the issue was solved - at least for the Debian
package.

Kind regards

    Andreas.

-- 
http://fam-tille.de

**Comment by peterjc** [comment]
Great - thanks for looking at this @mgalardini, and thanks again @tillea for reporting the issue.

 I've committed this fix to the master branch so it will be included in our next release.
