### ISSUE TITLE
Python 3.6 RNG bug and SinglePositionMutation

### ISSUE THREAD

**Issue by adalke** [biopython/biopython#1044]
There is bug in Python 3.6 under Windows where the RNG only uses the system clock and pid to initialize random.Random(). See http://bugs.python.org/issue29085 . The clock has a ~15 ms resolution, so the odds are high of that two Random() constructors in a row will get the same initial seed.

Biopython's Bio/GA/Mutation/Simple.py at https://github.com/biopython/biopython/blob/master/Bio/GA/Mutation/Simple.py#L28 contains the following:
```
class SinglePositionMutation(object):
    def __init__(self, mutation_rate=0.001):
        self._mutation_rate = mutation_rate
        self._mutation_rand = random.Random()
        self._switch_rand = random.Random()
        self._pos_rand = random.Random()
```
Odds are that under Windows/Python 3.6, these will have the same seed. This may cause an unexpected correlation between the outputs, though that's unlikely to have a noticeable effect.

One way to fix the issue is to use a single, shared RNG.
```
class SinglePositionMutation(object):
    def __init__(self, mutation_rate=0.001):
        self._mutation_rate = mutation_rate
        rng = random.Random()
        self._mutation_rand = rng
        self._switch_rand = rng
        self._pos_rand = rng
```
The results should be equally random, with less chance of having correlated seeds.

**Comment by peterjc** [comment]
The fix seems sensible, although I am hardly an expert on best practises for random number generators. Would you like to submit this change as a pull request?

If so, are you happy to dual licence your contributions under both the _Biopython License Agreement_ *and* the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS`` and ``CONTRIB`` files?

**Comment by adalke** [comment]
Git and github confuse me. My brain has 25 years of practice using SCCS/CSV/SVN/Mercurial and exchanging patches or working with a central private repo. I submit pull requests on github about once per year, and have to relearn the process each time.

Pull request is #1073 .

If you look at #898 you'll see I've already given permission. The answer is "yes", and I apologize again for not using the BSD 3-Clause license in the first place. ;)

Also, could you update my email in CONTRIB.rst from dalke@acm.org to dalke@dalkescientific.com ? Submitting *two* pull requests means I would need to figure out how to do branches in git, and I already failed to do it correctly with this RNG pull request. Sigh. I'll return to my stone knives and bearskins now.

**Comment by peterjc** [comment]
Thanks Andrew, I'll look at this shortly - don't have time this morning.

**Comment by peterjc** [comment]
CONTRIB updated. I should have recognised your GitHub username but as the profile doesn't list your name I didn't - otherwise I would have recalled the license discussion. Great to have your name on another Biopython release, thank you 👍

**Comment by adalke** [comment]
It's more a matter of "There's a github profile?" :)
