### ISSUE TITLE
AbiIO.py as a template for reading FSA files

### ISSUE THREAD

**Issue by njbernstein** [biopython/biopython#1062]
any thoughts about how to do this?

**Comment by peterjc** [comment]
What's an FSA file and why might the ABI parser be a good starting point?

**Comment by njbernstein** [comment]
An FSA file is a file format from applied biosystems genetic analyzer for fragment analysis that uses the ABIF (http://www6.appliedbiosystems.com/support/software_community/ABIF_File_Format.pdf
) like the ABI file format does. But I figured out how to do it. Have a good one
