### ISSUE TITLE
MafIO: Duplication of MAF blocks which span two exons?

### ISSUE THREAD

**Issue by TBradley27** [biopython/biopython#1083]
Hello,

I have had a problem trying to use biopython/Bio/AlignIO/MafIO.py recently

Version: Cloned from Github repository Feb 14 2017

In particular, I have been having problems using the 'get_spliced' method of the MafIndex class.

Here is my code:

```
import sys
from Bio import AlignIO
from Bio.AlignIO import MafIO

idx = AlignIO.MafIO.MafIndex("/path/chr1.mafindex" "/path/chr1.maf", "hg38.chr1" )

multiple_alignment = idx.get_spliced([11662625, 11662852], [11662731, 11662928], strand = 1)
```

NB: Chr1.maf and its corresponding index refers to the relevant MAF file from UCSC 100-way alignment:

http://hgdownload.cse.ucsc.edu/goldenPath/hg38/multiz100way/maf/

Running this scripts returns the following error message:

```
File "foo.py", line 15, in <module>
    strand = 1)
  File "/path/Bio/AlignIO/MafIO.py", line 538, in get_spliced
    (self._target_seqname, len(split_by_position[self._target_seqname]), total_rec_length))
    ValueError: Target seqname (hg38.chr1) has 372 records, expected 543
```

In order to debug, I amended the original MafIO.py file in order to print out the values of some variables - I printed `multiseq` for each `multiseq` in `fetched`.  I also printed `seqrec` for each `seqrec` in `multiseq` for the reference species only.

I noticed the following output which seemed to be particularly interesting:

```
multiseq: SingleLetterAlphabet() alignment with 12 rows and 188 columns
catctcatcttgaatgg--taatcctgggt---gtttagggaga...-tg hg38.chr1
catctcatcttgaatgg--taatcctgggt---gtttagggaga...-tg panTro4.chr1
catctcatcttgaatgg--taatcctggat---gtttagggaga...-tg gorGor3.chr1
catctcatcttgaatgg--taatcctgggt---gtttagggaga...-tg ponAbe2.chr1
catctcaccttgaatgg--taatcccgggt---gtttaggaaga...-tg nomLeu3.chr24
cacctcatcttgaacag--taatcctgggt---gtttagggaaa...--- rheMac3.chr1
cacctcatcttgaacgg--taatcctgggt---gtttagggaaa...--- macFas5.chr1
cacctCATCTTGAATGG--TAATCCTGGGT---GTTTAGGGaaa...--- papAnu2.chr1
cacctcatcttgaatgg--taatcctgggt---gtttagggaaa...g-- chlSab2.chr20
aattttaccttgaatgg--taattccaggt---gtttagggaga...-tg calJac3.chr7
gattttaccttgaatgg--taattccaggt---gtttaaggaga...-tg saiBol1.JH378185
--------------TGGGCTAGACCAGGGTCCAGTCTAGGTAGG...--- octDeg1.JH651628

ref_seqrec_ID: hg38.chr1
Name: hg38.chr1
Number of features: 0
/start=11662715
/srcSize=248956422
/strand=1
/size=171
Seq('catctcatcttgaatgg--taatcctgggt---gtttagggagagacctggtgg...-tg', SingleLetterAlphabet())

multiseq: SingleLetterAlphabet() alignment with 12 rows and 188 columns
catctcatcttgaatgg--taatcctgggt---gtttagggaga...-tg hg38.chr1
catctcatcttgaatgg--taatcctgggt---gtttagggaga...-tg panTro4.chr1
catctcatcttgaatgg--taatcctggat---gtttagggaga...-tg gorGor3.chr1
catctcatcttgaatgg--taatcctgggt---gtttagggaga...-tg ponAbe2.chr1
catctcaccttgaatgg--taatcccgggt---gtttaggaaga...-tg nomLeu3.chr24
cacctcatcttgaacag--taatcctgggt---gtttagggaaa...--- rheMac3.chr1
cacctcatcttgaacgg--taatcctgggt---gtttagggaaa...--- macFas5.chr1
cacctCATCTTGAATGG--TAATCCTGGGT---GTTTAGGGaaa...--- papAnu2.chr1
cacctcatcttgaatgg--taatcctgggt---gtttagggaaa...g-- chlSab2.chr20
aattttaccttgaatgg--taattccaggt---gtttagggaga...-tg calJac3.chr7
gattttaccttgaatgg--taattccaggt---gtttaaggaga...-tg saiBol1.JH378185
--------------TGGGCTAGACCAGGGTCCAGTCTAGGTAGG...--- octDeg1.JH651628

ref_seqrec_ID: hg38.chr1
Name: hg38.chr1
Number of features: 0
/start=11662715
/srcSize=248956422
/strand=1
/size=171
Seq('catctcatcttgaatgg--taatcctgggt---gtttagggagagacctggtgg...-tg', SingleLetterAlphabet())
```

So it seems that there is a duplicated entry for this particular MAF block. I also noticed that the size of the sequence record is reported as `171` - which is the same as the discrepancy between the expected and observed values seen in the error message i.e. `543` and `372`.

I also noticed that given the start position of the duplicated entry (`11662715`) and its size (`171`) - that this particular MAF block spans both exons/BED entries. 

Which perhaps may be the root cause of the error message.

I apologise in advance if I have made some mistake or this potential issue has already been raised - I checked the issues list and couldn't seem to find anything related to this.

**Comment by peterjc** [comment]
Thanks @TBradley27 - this is the first bug report against the new MAF code filed here.

Looking over https://github.com/biopython/biopython/commits/master/Bio/AlignIO/MafIO.py the ``MafIO.py`` code was last updated 22 Feb with https://github.com/biopython/biopython/commit/49e7da7b44c913143956e3662f4ada36937a3dc8 but that was a trivial white-space edit. Otherwise you're working with the latest version to have been committed to Biopython's master branch :)

There are a few more changes pending from @blaiseli on https://github.com/biopython/biopython/pull/504 which have not been merged yet.

@polyatail @adamnovak or @blaiseli - could you take a look at this problematic test case please?

**Comment by blaiseli** [comment]
@peterjc I'm currently trying to include a fix for this bug in my branch. The idea is to keep a record of start and stop positions already yielded in `MafIndex.search` and skip the blocks that have an already recorded (start, stop) pair. Maybe it would be more efficient to just perform this check on offset values.

**Comment by blaiseli** [comment]
@TBradley27 can you check whether the bug persists with my updated fork: <https://github.com/blaiseli/biopython/tree/alignio-maf> ?

**Comment by peterjc** [comment]
@TBradley27 are you comfortable cloning and checking out specific branches for testing?

I've included @blaiseli's proposed fix and test case in pull request #1086 (started from his work in #504 but excluding any changes to the end point treatment), so this is an alternative branch which could be tested https://github.com/peterjc/biopython/tree/mafio

**Comment by TBradley27** [comment]
@peterjc and @blaiseli - thank you very much for your quick responses.

Yes, I am happy to test the changes made to the forked repositories. I will hopefully have time to do this at some point today

**Comment by TBradley27** [comment]
I have now tested both of the branches mentioned in your previous comments.

First, I tested the code I posted in my first comment in this thread, on the following branch:

https://github.com/blaiseli/biopython/tree/alignio-maf

Which returned no error messages, and returned the following output when using `AlignIO.write` - with just the output shown for the reference species:

```
>hg38.chr1
TT-TACGGACATTGGATGAAGCCGaagcatttagaa----tggtgcctggcacacagttg
gtgcGt----gatat-ggttaagctttgtgtc-ccca-cccacatctcatcttgaatgga
cggtttccccggctccctcctgccgc------catg----tgaagaaggtcgttgcttcc
ccttcaccttccaccaccatgatt
```

Secondly, I tested the same code (see my first comment) on the following branch:

https://github.com/peterjc/biopython/tree/mafio

Which returned no error messages, and returned the following output when using `AlignIO.write` - with just the output shown for the reference species:

```
>hg38.chr1
TT-TACGGACATTGGATGAAGCCGaagcatttagaa----tggtgcctggcacacagttg
gtgcGt----gatat-ggttaagctttgtgtc-ccca-cccacatctcatcttgaatgga
cggtttccccggctccctcctgccgc------catg----tgaagaaggtcgttgcttcc
ccttcaccttccaccaccatgatt
```

As part of my project, I will be shortly fetching MAF alignments for every 3' UTR and CDS region (according to Ensembl annotations) in the human and mouse genomes. This will be a more extensive test of the latest commit.

**Comment by peterjc** [comment]
@TBradley27 thank you for your clear report, and testing the proposed fix from @blaiseli which I have now committed to the master (as part of pull request #1086). Please don't hesitate to reopen this issue if further testing reveals a problem - or indeed any new problems.
