### ISSUE TITLE
Missing module in PDBList

### ISSUE THREAD

**Issue by hmarlo** [biopython/biopython#1090]
There is a missing module in the PDBList which is used to write a warning to stderr using the module "sys", which is not imported (line 105). I'm forking the project and correcting the file.

**Comment by peterjc** [comment]
Well spotted. I wonder why ``flake8`` didn't spot that?

**Comment by hmarlo** [comment]
Thank you :) Maybe because flake 8 saw a import sys, but didn't notice that the range of that sys didn't include the scope of the write to stderr.

**Comment by peterjc** [comment]
That could explain it - even though that ``import sys`` was at the end of the file (as discussed on #1091) and not being executed.

**Comment by hmarlo** [comment]
@peterjc I close the issue.

**Comment by peterjc** [comment]
Yes, I should have closed this after merging #1091. Thank you.
