### ISSUE TITLE
 SearchIO parsing hmmer3-text records: allow for concatenated records

### ISSUE THREAD

**Issue by bachev** [biopython/biopython#1093]
Hi there,

I just stumbled across this problem while trying to speed up a couple of things by using GNU parallel for hmmscan: the current hmmer3-text parser does not handle cases where multiple outputs of hmmscan are concatenated together (as GNU parallel does).

I am implementing a workaround to clean up files prior to handing them over to the parser, but it would be nice for future users if this could be handled by SearchIO itself.

The fix should be quite trivial as in "if there's the [ok] line, but the file not empty and first character starts with a hash: restart parsing"

Best,
  Bastien

PS: I did not test this for other output formats of hmmscan. There too this *could* come in handy but much less probable to be used as more difficult to implement with GNU parallel

**Comment by peterjc** [comment]
I can certainly see the utility of this, provided it does not overly complicate the parser.

**Comment by bow** [comment]
Hi @bachev,

Thanks for opening this issue. I'll see what I can do. I hope it is as trivial as checking the line :).

**Comment by bow** [comment]
Hello @bachev,

After spending some time playing with this, I don't think I really like the idea of reworking the parser to support this I'm afraid.

The hmmer3-text format is actually quite poorly specified (there is no formal specification of it) and so it is subject to change on the HMMER maintainers. This is fine for them of course, but makes it difficult to have a parser that could work consistently across versions. 

The `[ok]` line addition is an example of this. This line only appeared in version 31b2, but not version 3.0 (when the parsers were initially written). While we could rely on this line for now, there is no guarantee that this will be the case for future versions as they may remove or alter the line.

This is not to say that having a parser that works for concatenated files are not useful of course. In fact, this is probably similar to parsing the output of `jackhmmer`, also in the HMMER suite, which is doing an iterative search (and this having an output close to concatenating multiple hmmer3-text output). Biopython does not currently provide a parser for this format (and there is no immediate plans to do so). The authors even [has this to say](http://manpages.ubuntu.com/manpages/trusty/man1/jackhmmer.1.html):

> The output format is designed to be human-readable,  but  is  often  so
       voluminous  that  reading  it is impractical, and parsing it is a pain.
       The --tblout and --domtblout options  save  output  in  simple  tabular
       formats  that  are  concise  and easier to parse.

So while I don't doubt the usefulness of having this feature, I'm just not sure if it's worth the maintenance effort to have this officially supported.
