### ISSUE TITLE
Improving doctest Bio/Graphics/GenomeDiagram/_FeatureSet.py

### ISSUE THREAD

**Issue by Gasta88** [biopython/biopython#1095]
Hi all, 

before editing and creating a PR for this script there are few things that I would like to discuss:

1) Testing on this script rely on a GenBank file which seems to be stored locally on the creator machine. I've found a copy of it and I would like to place it in the repo, but I'm not sure about the location. Maybe `Tests/Graphics`?

2) I'm relying on the doctest framework over the unittest because it seems in line with the previous testing that was implemented on the script. Any opinion of the contrary?

Thanks for the inputs.

**Comment by peterjc** [comment]
RE: self test in https://github.com/biopython/biopython/blob/biopython-168/Bio/Graphics/GenomeDiagram/_FeatureSet.py#L198

The basic functionality being tested here is already covered, e.g. https://github.com/biopython/biopython/blob/biopython-168/Tests/test_GenomeDiagram.py#L822

I'm reluctant to add another reasonably sized file to the repository (and thus the files distributed with Biopython) unnecessarily. ``NC_005213`` from *Nanoarchaeum equitans* is a nice test case in that is it a small genome and it has an example of a feature wrapping the origin.

I suggest we remove the self-test in ``_FeatureSet.py``, and consider constructing a simple genome diagram in code which include an origin-wrapping feature, drawn in both linear and circular mode (enhancement filed as #1096).

**Comment by Gasta88** [comment]
Thanks @peterjc.

I'll get my head around this issue then.

**Comment by peterjc** [comment]
I was not clear enough in my comment. As genomes go, NC_005213 is relatively small but I still DO NOT want to include it in the test suite.

Instead, we could recreate an origin spanning feature in code for the test.

**Comment by peterjc** [comment]
Closing, see #1096.
