### ISSUE TITLE
MUSCLE command line wrapper options

### ISSUE THREAD

**Issue by JoshuaMeyers** [biopython/biopython#1098]
The options available in the biopython wrapper for MUSCLE MSA do not correspond to those available in the command line version (for MUSCLE v3.8)

The most significant of these are the '-matrix' flag which allows users to set a scoring matrix (e.g. BLOSUM62) and '-gapextend' which defines the penalty for extending a gap. Both of these are not available in the biopython wrapper.

<br><br>

_This was mentioned on the mailing list:_
'''
[Issues when attempting to run MUSCLE through biopython with] a gapextend penalty. It seems that this Option was neglected in the command line wrapper.
The Option does exist in the MUSCLE docs: http://www.drive5.com/muscle/muscle_userguide3.8.html

records = [SeqRecord(full_ref_seq,id="ref"),SeqRecord(full_fit_seq,id="fit")]
muscle_cline = MuscleCommandline(clwstrict=True, matrix='blosum62', gapopen=-11.0, gapextend=-1.0, center=0.0)
child = subprocess.Popen(str(muscle_cline),
                         stdin=subprocess.PIPE,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE,
                         universal_newlines=True,
                         shell=(sys.platform!="win32"))
SeqIO.write(records, child.stdin, "fasta")
child.stdin.close()
align = AlignIO.read(child.stdout, format="clustal”)
**ValueError: Option name gapextend was not found.**

Upon inspecting the muscle_cline object, this kwarg is indeed absent (it exists in the analogous clustal wrapper).
print dir(muscle_cline)
[............... 'clw', 'clwout', 'clwstrict', 'clwstrictout', 'core', 'diaglength', 'diagmargin', 'diags', 'distance1', 'distance2', 'fasta', 'fastaout', '**gapopen**', 'group', 'html', 'htmlout', 'hydro', 'hydrofactor', 'in1', 'in2', 'input', 'le', 'log', 'loga', 'maxdiagbreak', 'maxhours', 'maxiters', 'maxtrees', 'minbestcolscore', 'minsmoothscore', 'msf'...........]
'''

**Comment by JoshuaMeyers** [comment]
Issue resolved: https://github.com/biopython/biopython/pull/1100

**Comment by peterjc** [comment]
I'd forgotten to close this after #1100 was merged, thanks!
