### ISSUE TITLE
Update Tutorial to use mmCIF in place of PDB format

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1102]
PDBx/mmCIF became the standard PDB archive format in 2014. The plain text PDB file format is now deprecated, so we should update the Biopython Tutorial to use the mmCIF parser instead.

http://mmcif.wwpdb.org/docs/faqs/pdbx-mmcif-faq-general.html

This should be fairly easy to fix, if you are familiar with the topic already.

**Comment by JoaoRodrigues** [comment]
We can highlight that we do have this feature indeed, but despite what
format is now default, many many people still use PDBs. Besides, we do no
have a mmCIF writer..

2017-03-17 7:18 GMT-07:00 Peter Cock <notifications@github.com>:

**Comment by peterjc** [comment]
True, adding an mmCIF writer would be nice. People are going to continue using PDB files for some time yet, so the tutorial transition could be more gradual - it should at least show parsing mmCIF and MMTF as early as possible?

**Comment by JoaoRodrigues** [comment]
Agreed. I'll have a look at that.

2017-03-19 15:48 GMT-07:00 Peter Cock <notifications@github.com>:

**Comment by souravsingh** [comment]
@peterjc Do we need to make the changes everywhere in the Tutorial sections where PDB parser is used?

**Comment by peterjc** [comment]
Not everywhere - as noted above, people will be using PDB for some time yet. In any case Joao says he'll look at this...

**Comment by JoaoRodrigues** [comment]
Hi @souravsingh, I was planning to have a look at it this weekend, but if you want to go ahead and add to the tutorial examples of the other two parsers, go for it. I need to have a look at the tutorial, but as @peterjc mentioned, we should try to introduce the mmCIF and MMTF parsers as soon as possible (not as an afterthought) to the user.

**Comment by deepaklorkhatri007** [comment]
@peterjc I can see that the present tutorial does somewhat covers a bit of mmCIF and MMTF. Is there anything I can do to improve the tutorial?

**Comment by peterjc** [comment]
@deepaklorkhatri007 I've hardly touched PDB files in years - I'm not well placed to review this chapter in any detail. However, a small change would be reordering to do mmCIF reading before PDB file reading, and mmCIF writing before PDB file writing? Also perhaps a very short paragraph at the chapter start about file formats?

**Comment by deepaklorkhatri007** [comment]
@peterjc I will work on these tasks for now and report here only.

| Sno        | Task           |
|-------------|-------------|
| 1 | mmCIF reading before PDB file reading |
| 2 | mmCIF writing before PDB file writing |
| 3 | a very short paragraph at the chapter start about file formats |
