### ISSUE TITLE
translate method for SeqRecord

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1103]
We have a ``.reverse_complement(...)`` method in the ``SeqRecord``, using the method of the same name on the ``Seq`` object.

It would be natural to do this for ``.translate(...)`` as well, with similar behaviour for the metadata. i.e. default to dropping it, but make it easy to explicitly retain it (e.g. ``.translate(..., id=True)`` to retain the nucleotide record's ``.id`` on the protein record.

This would have been useful in some recent training course materials.

**Comment by idoerg** [comment]
Some comments on translation:
1. Need to work with different codon tables. (E.g. UGA--> Trp in Mictochondria and some bacteria, if we don't already).
2. Should we  provide translational recoding for UGA for Selenocysteine., UAG for Pyrrolysine https://en.wikipedia.org/wiki/Selenocysteine
https://en.wikipedia.org/wiki/Pyrrolysine

or is that too idiosyncratic?

**Comment by peterjc** [comment]
Hi Iddo, the table option should be covered by the ``table`` argument as already implemented in the ``Seq`` object (usually an integer code or string for a table name, it can be a ``CodonTable`` object). The proposal here just extends that to the (annotated) ``SeqRecord`` object.

What did you have in mind for translational recoding? I've seen explicit annotation of this in GenBank records as part of a feature qualifiers.

**Comment by idoerg** [comment]
Probably option 2, maybe 1 as well:
1. Enable a reading from the genbank file (with a boolean _flag `trans_recode=False` for default)
2. Allow explicit translational recoding as an optional argument, e.g.
`.translate(...., recode=rc_list)`

Where `rc_list` has the following format:
`[(pos_1, AA1),...(pos_n,AAn)]`
The `pos_i` is the start position of the codon, `AAi` is the amino-acid.

**Comment by peterjc** [comment]
@idoerg could you expand on translational recoding over on new issue #1164 please? A specific example would be great.

This pull request is specially for extending the ``Seq`` object's ``.translate()`` to the ``SeqRecord`` object, and @idoerg's suggestion does raise an issue about this:

What happens when the ``Seq`` object's ``.translate()`` gains new options vs the argument order in the ``SeqRecord``? Rather than hard coded explicit named arguments as now, should we use a keyword argument dict and pass that to ``.translate()`` instead?

Regarding translational recording, the only place I've seen this in NCBI annotation is as part of features of a GenBank record as the `` /transl_except=...`` qualifier. That would belong to a Biopython ``SeqFeature`` object rather than the parent sequence ``SeqRecord``. The ``SeqFeature`` does have a ``some_feature.extract(...)`` method and perhaps building on that makes sense in place of ``some_feature.extract(...).translate(...)`` using the relevant annotation (e.g. codon start as well as translation exceptions)?
