### ISSUE TITLE
Prank_codon

### ISSUE THREAD

**Issue by foenpeng** [biopython/biopython#1111]
In the file Module Bio.Align.Applications._Prank.py,  Prank cannot recognize the codon argument.

_Option(["-codon", "codon"],

should be 

_Switch(["-codon", "codon"],

It is not supposed to manually input a codon model in prank. Instead, it is just a switch on/off

**Comment by peterjc** [comment]
Thanks for reporting this. Could you make this into a pull request? Its a tiny change so you've even be able to do it within GitHub in the browser (without using git at the command line at all).

**Comment by foenpeng** [comment]
Hi Peter, thanks! I've done it the way as you suggested.

**Comment by peterjc** [comment]
Closed via #1117, thank you.
