### ISSUE TITLE
how to convert atom object to structue object?

### ISSUE THREAD

**Issue by autodataming** [biopython/biopython#1121]
I have select some atom objects. Then I want to convert these atom objects to structure object and save it to pdb file as the following:
>>> io = PDBIO()
>>> io.set_structure(s)
>>> io.save('out.pdb')

I was confused that how to convert atom object to structue object.

**Comment by JoaoRodrigues** [comment]
This is a question better suited for the general user mailing list: http://biopython.org/wiki/Mailing_lists

In short, if you select a *few* atom objects and you want to save only those to a file, you should look into the Select class and how it is used together with PDBIO. There's a simple example in the [Tutorial](http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc154). You have to find a simple common feature between the atoms you want to save, or just make your own (add a new attribute dynamically).
