### ISSUE TITLE
Restriction Analysis: Strange behavior of AbaSI in CommOnly

### ISSUE THREAD

**Issue by paxelito** [biopython/biopython#1128]
Hi,
I obtained strange results from the restriction analysis based on CommOnly restriction batch for several enzymes, for example focusing on a simple search of AbaSI I find the following results 
```python
    seq = Seq('AAGGTCGGGCAGGA', IUPACAmbiguousDNA())
    rest.AbaSI.search(seq) -> [3, 4]
    rest.AbaSI.characteristic() -> (12, 9, None, None, 'C')
    rest.AbaSI.elucidate() -> CNNNNNNNNN_NN^N
```
The enzyme cuts forward at 3 and 4. If the "^" is placed 12 bases after the recognized sequence, how the first cut can be 3? 

Really thx

**Comment by peterjc** [comment]
Why do you say the enzyme cuts at 3 and 4?

(Also beware that due to a what I consider to be an unfortunate design choice, ``Bio.Restriction`` counts from one rather than zero like Python and most of Biopython)

**Comment by paxelito** [comment]
Hi,
in accordance with the documentation 
``` python
>>> ecoseq = my_seq + Seq(EcoRI.site, amb) + my_seq
>>> ecoseq
Seq('AAAAAAAAAAAAAAGAATTCAAAAAAAAAAAAAA', IUPACAmbiguousDNA())
>>> EcoRI.search(ecoseq)
[16]
 ```
> The position returned by the method search is the first base of the downstream segment produced by a restriction (i.e. the first base after the position where the enzyme will cut)

and

> A more detailled view of the restriction site can be produced using the elucidate() method. The ^ refers to the position of the cut in the sense strand of the sequence,  _ to the cut on the antisense or complementary strand. ^_ means blunt.

as in 
``` python
>>> EcoRI.elucidate()
'G^AATT_C'
```
thus, if I understand correctly, 
``` python
>>> AbaSI.elucidate()
'CNNNNNNNNN_NN^N'
```
means that the `AbaSI` enzyme cuts in the sense strand **12 bases after** the recognized site `C` as also documented in 
``` python
>>> AbaSI.characteristic()
(12, 9, None, None, 'C')
```
thus, looking at my sequence, if search() returns 3 it means that the recognized sequence should be 12 bases before that is **not possible**. 

Moreover, looking at this [AbaSI](https://www.neb.com/products/r0665-abasi) description 

>AbaSI is a DNA modification-dependent endonuclease and it is an EpiMark™ validated product. AbaSI recognizes 5-glucosylhydroxymethylcytosine (5ghmC) in double stranded DNA. It also recognizes 5-hydroxymethylcytocine (5hmC) but at a lower efficiency. It does not recognize DNA with 5-methylcytosin or un-modified cytosine

How can it identify a methylated sequence in a row string sequence input?  

Two important remarks:
1. I am not really interested in AbaSI activity, but it is present in the `CommOnly` restriction batch and it returns strange results. 
2. There are other enzymes with strange outputs, so I can remove them from a `custom` restriction batch based on `CommOnly`

nevertheless, it may be also a bad comprehension in the usage of the `Bio.Restriction` library on my side.
thank you for your precious work... 

Ale

**Comment by peterjc** [comment]
OK, there is definitely something odd here.

Unfortunately this module has no active maintainer and there are other open issues including #509 and your #1113.

Also we'd like to replace it - see eg #268

**Comment by MarkusPiotrowski** [comment]
What happens if you make your sequence longer? At the moment the sequence is too short to find the correct cutting site, it seems like it wraps over and starts from the beginning? 
Is this the same problem (cutting site outside the given sequence) for the other enzymes you mentioned?

**Comment by paxelito** [comment]
Thanks @MarkusPiotrowski. Hoping to do something useful I am preparing a short report where all the enzymes contained in Common batch are tested. I have also found problems in those enzymes cutting at the very end of the sequence. If you think that the report may be useful, I hope to finish it in the next few days. 
 
For example  GsaI does not work in the following test case 
```python
s = Seq('AAAACGGGGGGGCCCAGC', IUPACAmbiguousDNA())
print('\n{0}'.format(s))
print(GsaI.elucidate())
print(GsaI.search(s))
print(GsaI.characteristic())
print(GsaI.catalyse(s))

AAAACGGGGGGGCCCAGC
C_CCAG^C
[]
(5, -5, None, None, 'CCCAGC')
(Seq('AAAACGGGGGGGCCCAGC', IUPACAmbiguousDNA()),)
```
but if I add a base at the end 

```python
s = Seq('AAAAAGGGGGGGCCCAGCT', IUPACAmbiguousDNA())
print('\n{0}'.format(s))
print(GsaI.elucidate())
print(GsaI.search(s))
print(GsaI.characteristic())
print(GsaI.catalyse(s))

AAAAAGGGGGGGCCCAGCT
C_CCAG^C
[18]
(5, -5, None, None, 'CCCAGC')
(Seq('AAAAAGGGGGGGCCCAG', IUPACAmbiguousDNA()), Seq('CT', IUPACAmbiguousDNA()))
```

**Comment by MarkusPiotrowski** [comment]
@paxelito can you also test ```is_palindromic()``` in your script? My guess would be that the problematic enzymes are all non-palindromic.

**Comment by paxelito** [comment]
@MarkusPiotrowski ok, I will test it. I will update you in a few days.

**Comment by MarkusPiotrowski** [comment]
OK, two things:
1. AbaSI behaves as expected. The design in ```Restriction.py``` is that it will only report cuts _in the given sequence/strand_ although both strands are searched for recognition sites. 
  - So in your first example, although there are some recognition sites for AbaSI in the given sequence (=forward strand), the cuts would occur outside of the given strand.
  - However, there are also recognition sites on the reverse-complement strand, and this would result in cuts in the forward strand, with the returned result (as explained earlier)
   - If I supply the reverse-complement sequence, then there will be again recognition sites, but the cuttings would be outside of the given strand, thus the result is 0, although the enzyme would cut the other strand.
2. There was indeed a bug that cuts at the penultimate position were not reported. This is hopefully solved with #1195

**Comment by peterjc** [comment]
This should now be fixed on the master branch - I have merged #1195 from @MarkusPiotrowski 

@paxelito are you able to install Biopython from github and re-test?

**Comment by paxelito** [comment]
@peterjc thank you so much for your effort. I will do that in the weekend I hope.

**Comment by MarkusPiotrowski** [comment]
@paxelito In case you won't/can't install Biopython completely from scratch, it should work just to replace ``` Restriction.py```, e.g., display as raw file and copy/paste to Idle.

**Comment by paxelito** [comment]
Hi, finally I have found the time to test the new Restriction.py. As @MarkusPiotrowski suggested I just created my restriction.py by copying and pasting the new Restriction.py.
1. The first thing that I noticed is that CommOnly restriction batch is now composed of 895 enzymes (as AllEnzymes) instead of 622 as in the old one, is it right?
2. Some new enzyme as `None` cutting point

```python
------- Sen1898IV
(None, None, None, None, 'GATCAG')
Sequence: GATCAGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
found at 1
rec site GATCAG
valid rec site GATCAG
CutF: None
```
3. MspJI has a strange behavior. As for all the recognition sites having an ambiguous DNA recognition site, I created a non-ambiguous recognition fragment in the sequence by substituting the ambiguous code in the sequence with a random char from the following ambiguous dictionary

```python
IUPAC_AMB = {
    'A':(A,),
    'T':(T,),
    'G':(G,),
    'C':(C,),
    'R':(A,G,),
    'Y':(C,T,),
    'S':(G,C,),
    'W':(A,T,),
    'K':(G,T,),
    'M':(A,C,),
    'B':(C,G,T,),
    'D':(A,G,T,),
    'H':(A,C,T,),
    'V':(A,C,G,),
    'N':(A,C,G,T),
}
```
For example the recognition site `CNNR` of MspJI stands for 4X4X2 possible different recognition sites, but not all of them are recognized. Unfortunately currently I do not test all the possible permutations but only one randomly selected from the possible ones. In this particular case I realized that, although N stands for all the bases, the G bases are not recognized. Look for instance at the following example where MspJI should be recognized but it does not. 

```python
RESTRICTION ENZYME: MspJI
	Enzyme representation: CNNRNNNNNNNNN^NNNN_N
	(13, 13, None, None, 'CNNR')
	Position added 10	Sequence length: 54
	Original: TTTTTTTTTTCGGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
	Digested: TTTTTTTTTTCGGGTTTTTTTTT\/TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
```
4. the bug of the recognition sites at the very end of the sequence seems to be fixed.

Do you think now would it be the case to create an exhaustive test for all the ambiguous sequences?

**Comment by MarkusPiotrowski** [comment]
@paxelito 
1. Damn, this is a bug I introduced, sorry. Forgot that ```a = b``` with ```sets``` does not make a copy of ```b```, Need to make a copy of CommOnly...
2. That's a consequence of the bug. Sen18988IV is not commercially available and has no known cutting site.
3. The problem with MspJI does not seem to be 'N' or 'R' related, but the position seems to be critical. It works if the recognition site is directly at the start, but not if later:

```python
>>> from Bio.Restriction import *
>>> from Bio.Seq import Seq
>>> my_seq = Seq('CGGATTTTTTTTTTTTTTTTTTTTTTTTTTTTTT')
>>> MspJI.search(my_seq)
[14]
>>> my_seq = Seq('CGGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT')
>>> MspJI.search(my_seq)
[14]
>>> my_seq = Seq('TCGGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT')
>>> MspJI.search(my_seq)
[]
>>> my_seq = Seq('TCGGATTTTTTTTTTTTTTTTTTTTTTTTTTTTTT')
>>> MspJI.search (my_seq)
[]
```
This is probably/likely a bug, but I need to investigate. It's already in Biopython 1.68, so I'm not guilty here...

4. That's good.

**Comment by paxelito** [comment]
@MarkusPiotrowski i'm only happy to give my small contribute to this issue. Let me know when you fix it, do you think is it useful to prepare an exhaustive test for all the enzymes? At least the ones in CommOnly batch as soon as you fix it?

**Comment by paxelito** [comment]
Dear @MarkusPiotrowski do you know when the fixed Restriction.py will be officially released?

**Comment by peterjc** [comment]
It would be part of the next Biopython release, version 1.70, likely June 2017 as we'll be wanting it out before the annual Bioinformatics Open Source Conference (BOSC) in July.

**Comment by paxelito** [comment]
@peterjc that's cool!!! thx so much.

**Comment by peterjc** [comment]
@MarkusPiotrowski did you make a pull request for the ``CommOnly`` problem you noted above?

**Comment by MarkusPiotrowski** [comment]
Not yet, I'm working on ```test_Restriction.py``` to get the coverage of ```Restriction.py``` somewhere above 70% (hopefully). I think I'm through with it in a few days.
I have fixed the ```CommOnly``` problem and the other problem with non-palindromic enzymes (MspJI example from above). So I could do a separate PR only for ```Restriction.py```.

**Comment by MarkusPiotrowski** [comment]
@paxelito Another bugfix has been merged. If you like you can repeat your tests with the new version of ```Restriction.py```?

**Comment by paxelito** [comment]
@MarkusPiotrowski really apologize for the delay. I have tried the new version with my tests, it seems that the last version of Restriction.py works really well, really good work. 
I have a question, is there some way to recognize the strand where the enzyme recognize the sequence? For example in the following example: 
```python
BsmBI
(7, 5, None, None, 'CGTCTC')
elucidate: CGTCTCN^NNNN_N

### RECOGNIZE BsmBI IN 5'
Sequence: CGTCTCAAAAAAAAAAAAAAAAAA
First after cut: [8]
Original: CGTCTCAAAAAAAAAAAAAAAAAA
Digested: CGTCTCA\/AAAAAAAAAAAAAAAAA

### RECOGNIZE BsmBI IN 3'
Sequence: AAAAAAAAAAAAAAGAGACGTTTTTTTTTTTTT
First after cut: [10]
Original: AAAAAAAAAAAAAAGAGACGTTTTTTTTTTTTT
Digested: AAAAAAAAA\/AAAAAGAGACGTTTTTTTTTTTTT
```
is there some method to get the strand of the cut or I have to check it manually?

**Comment by MarkusPiotrowski** [comment]
As far as I can tell there is no implemented method which reports the strand on which the recognition sequence was recognized. You would have to do this manually e.g. searching both strands with a regular expression. The regular expression pattern of the enzyme can be inferred from it's ```compsite.pattern```:
```
>>> from Bio import Restriction as re
>>> print(re.BsmBI.compsite.pattern)
(?P<BsmBI>CGTCTC)|(?P<BsmBI_as>GAGACG)
```
You could then assign the patterns for two regular expression searches:
```
>>> forward_pattern, reverse_pattern = re.BsmBI.compsite.pattern.split('|')
```

**Comment by MarkusPiotrowski** [comment]
Everything seems to be resolved.
