### ISSUE TITLE
SeqIO not parsing gzipped genbank file

### ISSUE THREAD

**Issue by mojones** [biopython/biopython#1134]
Using BioPython 1.68, freshly installed using pip. 

Using this file from the NCBI FTP site:

    ftp://ftp.ncbi.nih.gov/genbank/gbinv1.seq.gz

and the example from the tutorial, I get no records found and hence zero bases:

```
>>>import gzip
>>>from Bio import SeqIO
>>>handle = gzip.open("gbinv1.seq.gz", "r")
>>>print(sum(len(r) for r in SeqIO.parse(handle, "gb")))
0
```

The same file works as expected if uncompressed. Is this maybe something to do with the fact that the gzipped handle returns  `bytes` objects rather than strings?

**Comment by peterjc** [comment]
Sorry, we've already updated the documentation read for the next release - the gzip defaults changed in Python 3 and you need to do:

```
handle = gzip.open("gbinv1.seq.gz", "rt")
```

**Comment by mojones** [comment]
Yep, that works perfectly. Many thanks.
