### ISSUE TITLE
Duplicated ID in HMM 3.0 results

### ISSUE THREAD

**Issue by frcamacho** [biopython/biopython#1135]
Hi there,
I ran hmmsearch and within the results I have duplicated IDs in the results. The duplicated IDs is caused because the model detected different sections of a sequence (query). Because of this issue when I run the following:
```
handle=SearchIO.parse("HMM-results.txt", 'hmmer3-text')
for record in handle:
      print record

```
I receive the following error: 

> ValueError: The ID or alternative IDs of Hit '13848_2_2' exists in this QueryResult

I have multiple files so editing files one by one will be too time consuming. Is there a way that I could edit the handle to change the duplicated ID? With the following code, I saved the duplicatedID to know which query to add a numeric prefix to the queryID. 

```
duplicatedID = ""
try:
    for record in handle:
            print record
except ValueError as e:
    strError = str(e)
    duplicatedID = strError. split("'")[1] 
```
Thanks for your time and input.

**Comment by bow** [comment]
Hello @frcamacho,

Hmm..having multiple hits of different parts of a sequence is an expected case of the parser. However, when that occurs, HMMER would output it as a single database record hit with multiple alignments. May I ask if you are sure that the database you are searching against do not have duplicate IDs? If you don't mind, I could also take a look at the file (feel free to send it to me personally if posting a link here is not something you prefer).

**Comment by frcamacho** [comment]
Hi @bow, 
I figured out the issue was due to the translation tool (transeq) cutting off the headers causing the duplication error. 
Thanks for your input!

**Comment by bow** [comment]
Good to hear + thanks for the update :). I'm closing this now then.

**Comment by jeremi1504** [comment]
Hi @frcamacho,
I have exactly the same problem and I'm also using transeq in one of the previous steps. Could you please describe in more detail how did you solve this problem? How exactly is the transeq cutting off the headers?

**Comment by frcamacho** [comment]
Hi @jeremi1504, 
I used transeq for the [algorithm](https://github.com/donia-lab/MetaBGC) I built in grad school here, I was using EMBOSS 6.6.0. 

```
def runTranSeq(fastaFile,frameCode,outputFile):
    print('Running transeq with {0}.'.format(fastaFile))
    cmd = "transeq " + fastaFile + " " + outputFile + " -frame="+ frameCode +" -table=0 -sformat pearson"
    print(cmd)
    subprocess.call(cmd, shell=True)
    print("Done Running transeq with:",fastaFile)
```
My fasta headers had '|' and when encountering the '|' character in an identifier, the parsing process in EMBOSS 6.6.0 is designed to extract specific information such as the database name, accession, and entry name. However, a bug in the 6.6.0 release caused unexpected behavior when using a two-field identifier separated by a pipe ('|') character. Identifiers with two fields separated by a colon (':') or three or more fields separated by pipes are unaffected by this bug.

If you are working with FASTA-formatted input sequences and wish to keep the identifiers exactly as they appear in the headers, you should explicitly specify the '**pearson**' format instead of relying on '**fasta**' or **automatic format detection**. The '**pearson**' format considers the identifier as the first non-whitespace token on the header line and does not attempt to parse structured identifiers. To achieve this, include the '**-sformat pearson'** option in your command-line. By doing so, your output will contain the expected identifiers, along with the additional '_1' frame suffix. Therefore the headers should not be duplicated anymore when you parse.
