### ISSUE TITLE
SearchIO.BlatIO assertion statements block parsing of blatx (protein query vs dnax database) PSL files

### ISSUE THREAD

**Issue by docmanny** [biopython/biopython#1136]
Hello all, 

While working on a program to automate BLAT searches, I stumbled across this error. In short, the mismatch between the query ranges and target ranges that are inherit in blatx searches are triggering the following AssertionError:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-743ae90aba50>", line 1, in <module>
    qresults = SearchIO.read('/home/manny/blatx_test.psl','blat-psl')
  File "/usr/lib64/python3.4/site-packages/Bio/SearchIO/__init__.py", line 357, in read
    first = next(generator)
  File "/usr/lib64/python3.4/site-packages/Bio/SearchIO/__init__.py", line 314, in parse
    for qresult in generator:
  File "/usr/lib64/python3.4/site-packages/Bio/SearchIO/BlatIO.py", line 401, in __iter__
    for qresult in self._parse_qresult():
  File "/usr/lib64/python3.4/site-packages/Bio/SearchIO/BlatIO.py", line 492, in _parse_qresult
    hsp = _create_hsp(prev_hid, prev_qid, prev)
  File "/usr/lib64/python3.4/site-packages/Bio/SearchIO/BlatIO.py", line 354, in _create_hsp
    assert hsp.hit_end == psl['tend']
AssertionError
```
This bug was replicated by myself using various versions of BLAT (v0.33, a few revisions of v0.34, and the recent v0.35), using various genomes from UCSC (Alligator, Human, and Mouse), and using different protein queries (CDN1B and Insulin in addition to UCHL3). All of the above combinations work if one uses nucleotide queries. 

To replicate this error, run a blat search using `blat [genome.2bit] [protein query] [output.psl] -q=prot -t=dnax -out=psl` to generate the required psl file. ([Here is one such file](https://github.com/biopython/biopython/files/903515/blatx_test.psl.txt), generated by blat-ing [this protein](https://www.ncbi.nlm.nih.gov/protein/48145827?report=fasta) against hg38 with the given command). Then, in python, run:

```
from Bio import SearchIO
qresults = SearchIo.read('blat_test.psl', 'blat-psl')
```

It seems like the issue comes up because of the inherit discrepancy between the range of the protein hit, and the range of the DNA target; a stopgap patch, then, might be to have an optional `dnax` parameter for blat-psl that, combined with an if-then statement, allows a bypass of the assertions in lines 351-354 of Bio.SearchIO.BlatIO. While it would be nice to have an alternative set of assertion tests in the case of blatx-derived PSL files, I can't think of any off the top of my head that wouldn't run into the same issues. 

Best, 
Juan Manuel Vazquez

**Comment by bow** [comment]
Hi @docmanny,

Thanks for reporting the bug and including a test case. I can confirm I could reproduce the bug with the latest master. There is indeed an expected difference of coordinates when doing blatx searches, but this was anticipated with some test cases (and this assert check was put in place to ensure my assumptions about the files were all correct ~ apparently this is not the case). I will take a look.

**Comment by bow** [comment]
@docmanny, I've just pushed a fix for this. There is one more thing I would like to ask: would you mind if we add your test case to Biopython's test suite? This is to prevent regression bugs in the future. If not, I would add it to the linked PR.

**Comment by docmanny** [comment]
Yeah go for it, feel free!

**Comment by bow** [comment]
Great. I'll include your test case to the PR, merge the PR, and then close this issue.

Thanks again for reporting and sharing the test case!

**Comment by docmanny** [comment]
@bow, I downloaded the latest master with the fix as of two days ago, and I tried it again. While the test case I gave you works, as well as a few others, files made by blatting the same query sequence as before against other UCSC genomes are giving me similar AssertionErrors. 
The gfServers were generally made using the command:
```gfServer start localhost [port] -canStop -trans -mask [2bit]```
And then the following commands were run to generate the attached list of files:
```
gfClient localhost 30001 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/AilMel1_CAG33136_1.psl -t=dnax -q=prot minIdentity=50 -out=psl
gfClient localhost 30002 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/BalAcu1_CAG33136_1.psl -t=dnax -q=prot minIdentity=50 -out=psl
gfClient localhost 30003 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/HetGla2_CAG33136_1.psl -t=dnax -q=prot minIdentity=50 -out=psl
gfClient localhost 30004 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/hg19_CAG33136_1.psl -t=dnax -q=prot minIdentity=50 -out=psl
gfClient localhost 30005 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/mm10_CAG33136_1.psl -t=dnax -q=prot minIdentity=50 -out=psl
gfClient localhost 30006 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/OrnAna2_CAG33136_1.psl -t=dnax -q=prot minIdentity=50 -out=psl
gfClient localhost 30007 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/PteVam1_CAG33136_1.psl -t=dnax -q=prot minIdentity=50 -out=psl

gfClient localhost 30001 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/AilMel1_CAG33136_1.pslx -t=dnax -q=prot minIdentity=50 -out=pslx
gfClient localhost 30002 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/BalAcu1_CAG33136_1.pslx -t=dnax -q=prot minIdentity=50 -out=pslx
gfClient localhost 30003 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/HetGla2_CAG33136_1.pslx -t=dnax -q=prot minIdentity=50 -out=pslx
gfClient localhost 30004 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/hg19_CAG33136_1.pslx -t=dnax -q=prot minIdentity=50 -out=pslx
gfClient localhost 30005 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/mm10_CAG33136_1.pslx -t=dnax -q=prot minIdentity=50 -out=pslx
gfClient localhost 30006 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/OrnAna2_CAG33136_1.pslx -t=dnax -q=prot minIdentity=50 -out=pslx
gfClient localhost 30007 / /home/manny/Scripts/Py/RecBlast/etc/UCHL3.faprt /home/manny/Scripts/Py/RecBlast/etc/PteVam1_CAG33136_1.pslx -t=dnax -q=prot minIdentity=50 -out=pslx
```
Notes: 
- AilMel1, hg19, and PteVam1 read without issues as both psl and pslx
- BalAcu1, HetGla2, mm10, OrnAna2 fail as both psl and pslx
- All of them can be read as blast-tab files using "-out=blast8"
- All failures are the same:
At BlatIO.py, line 354, in _create_hsp: assert hsp.hit_start == psl['tstart']

It seems like its just another change of the same type, but now for Tstart as opposed to Tend. As before, I've attached the files, and please feel free to use any of them for the test suite.




















[AilMel1_CAG33136_1.psl.txt](https://github.com/biopython/biopython/files/1005977/AilMel1_CAG33136_1.psl.txt)
[AilMel1_CAG33136_1.pslx.txt](https://github.com/biopython/biopython/files/1005975/AilMel1_CAG33136_1.pslx.txt)
[AilMel1_CAG33136_1.tab.txt](https://github.com/biopython/biopython/files/1005976/AilMel1_CAG33136_1.tab.txt)
[BalAcu1_CAG33136_1.psl.txt](https://github.com/biopython/biopython/files/1005979/BalAcu1_CAG33136_1.psl.txt)
[BalAcu1_CAG33136_1.pslx.txt](https://github.com/biopython/biopython/files/1005980/BalAcu1_CAG33136_1.pslx.txt)
[BalAcu1_CAG33136_1.tab.txt](https://github.com/biopython/biopython/files/1005981/BalAcu1_CAG33136_1.tab.txt)
[HetGla2_CAG33136_1.psl.txt](https://github.com/biopython/biopython/files/1005978/HetGla2_CAG33136_1.psl.txt)
[HetGla2_CAG33136_1.pslx.txt](https://github.com/biopython/biopython/files/1005982/HetGla2_CAG33136_1.pslx.txt)
[HetGla2_CAG33136_1.tab.txt](https://github.com/biopython/biopython/files/1005984/HetGla2_CAG33136_1.tab.txt)
[OrnAna2_CAG33136_1.psl.txt](https://github.com/biopython/biopython/files/1005983/OrnAna2_CAG33136_1.psl.txt)
[OrnAna2_CAG33136_1.pslx.txt](https://github.com/biopython/biopython/files/1005985/OrnAna2_CAG33136_1.pslx.txt)
[OrnAna2_CAG33136_1.tab.txt](https://github.com/biopython/biopython/files/1005986/OrnAna2_CAG33136_1.tab.txt)
[PteVam1_CAG33136_1.psl.txt](https://github.com/biopython/biopython/files/1005987/PteVam1_CAG33136_1.psl.txt)
[PteVam1_CAG33136_1.pslx.txt](https://github.com/biopython/biopython/files/1005989/PteVam1_CAG33136_1.pslx.txt)
[PteVam1_CAG33136_1.tab.txt](https://github.com/biopython/biopython/files/1005990/PteVam1_CAG33136_1.tab.txt)
[hg19_CAG33136_1.psl.txt](https://github.com/biopython/biopython/files/1005988/hg19_CAG33136_1.psl.txt)
[hg19_CAG33136_1.pslx.txt](https://github.com/biopython/biopython/files/1005993/hg19_CAG33136_1.pslx.txt)
[hg19_CAG33136_1.tab.txt](https://github.com/biopython/biopython/files/1005992/hg19_CAG33136_1.tab.txt)
[mm10_CAG33136_1.psl.txt](https://github.com/biopython/biopython/files/1005991/mm10_CAG33136_1.psl.txt)
[mm10_CAG33136_1.pslx.txt](https://github.com/biopython/biopython/files/1005994/mm10_CAG33136_1.pslx.txt)
[mm10_CAG33136_1.tab.txt](https://github.com/biopython/biopython/files/1005995/mm10_CAG33136_1.tab.txt)

**Comment by bow** [comment]
Hi @docmanny,

Thanks for reporting the issue with the complete test cases. The incorrect assumption last time was related to the nucleotide-amino acid coordinate conversion, I will check if I need to do more adjustments in other places.

**Comment by bow** [comment]
Right, so this indeed boils down to the same issue: not correctly specifying the dna-protein coordinate conversion. What I missed here was the case when the hit is on the negative strand. Correctly specifying the size multiplier there seems to have fixed the issue.

Thanks again for reporting (and having an even more complete test cases!). I added the `BalAcu1_CAG33136_1.psl.txt` and `BalAcu1_CAG33136_1.pslx.txt` files into Biopython's test suite and renamed them accordingly. The fix will be in `master` after I see all tests passing on our CI server.

**Comment by bow** [comment]
Ok, all tests seem to pass now and the fix is in `master`. Would you mind checking that this is the case?

**Comment by docmanny** [comment]
Hey @bow,
As always, thanks so much for the quick fix! I just tested the fix in the master branch and it works perfectly, not only for the aforementioned test cases but also when I ran other proteins. Thanks again!

**Comment by bow** [comment]
Good to hear :). I'm closing this issue now, then.
