### ISSUE TITLE
ptyp, text and other filters

### ISSUE THREAD

**Issue by nurykim** [biopython/biopython#1137]
Hi, this is Nury, learning to use Biopython

I am trying to obtain titles and abstracts from 'journal articles' (in all documents) and analyze their language

-----------------------------------------
My code goes as follows:

from Bio import Entrez

def search(query):
	Entrez.email = 'my@real.email' # I use my email here
	handle = Entrez.esearch(db = 'pubmed', term = query, ptyp = 'Journal Article', text = 'hasabstract', lang = 'English', retmax = '20', mindate = '1981/01/01', maxdate = '1981/02/01', datetype = 'pdat', sb = 'medline')
	results = Entrez.read(handle)
	return results

search('')
----------------------------------------

This gives me result of count = 86078, but the same search in pubmed gave me 32651 results

The search que in the browser was (without any query word): 
("1981/01/01"[PDAT] : "1981/02/01"[PDAT]) AND (Journal Article[ptyp] AND hasabstract[text] AND English[lang] AND medline[sb]) 

The difference seems to be resulted from 'filters' of browsers - some result from biopython appears in browser if I remove some filters

My questions are: 

1. Is there a method to add browser filters in biopython code? As 'ptyp' and 'text' did not show any error the 'esearch' has those keywords but not functioning well

2. Is there a method to add journal name as the keyword or filter? Like, I would like to analyze and compare the sentences in 'Journal of Biochemistry' and 'PNAS', what should I add in keywords?

Thank you in advance

Sincerely,

**Comment by peterjc** [comment]
Use the exact same the search term for ``Entrez.esearch`` as a long string,

```python
my_term = '("1981/01/01"[PDAT] : "1981/02/01"[PDAT]) AND (Journal Article[ptyp] AND hasabstract[text] AND English[lang] AND medline[sb])'
```

Note because the search term has double quote characters in it, I have used single quote characters to define the Python string start and end. You can alternatively escape the quotes but I find that harder to read.

See also https://news.open-bio.org/2009/06/21/ncbi-einfo-biopython/

**Comment by nurykim** [comment]
Thanks a lot! I'll try as you've said!
