### ISSUE TITLE
Alphabet error "alignment should be a *PROTEIN* alignment" with MultipleSeqAlignment of Proteins

### ISSUE THREAD

**Issue by universvm** [biopython/biopython#1151]
Basically my aim is to use `.get_dn_ds_matrix` on a group sequences. I parsed with SeqIO `(stored in "sequence" list)` and translated my sequences  `(stored in "protein" list)`. While I was following [this tutorial](https://github.com/biopython/biopython/blob/master/Doc/doc.rst) I managed to get my dnds matrix on an ungapped sequence. 

However when the sequence is gapped, although I specify `alphabet=Gapped(IUPAC.IUPACUnambiguousDNA())` in SeqIO, and I successfully translate the proteins with the alphabet `Gapped(ExtendedIUPACProtein()`, when I try to build the alignment:

`aln = MultipleSeqAlignment(protein)`
`codon_aln = codonalign.build(aln, sequence)`

I get the error:

`File "/usr/local/lib/python2.7/site-packages/Bio/codonalign/__init__.py", line 83, in build`    
`TypeError: Alphabet Error!
The input alignment should be a *PROTEIN* alignment`

I'm not sure exactly why it would work on ungapped sequences and not on gapped sequences. 

Could it be something wrong with my code or is it a bug?

Specs:
biopython==1.68
Python =2.7.12
OS = MacOS

**Comment by peterjc** [comment]
Next time please include your version of Biopython, Python, OS, and the full error message.

This is an oversight (small bug) in ``codonalign``, it does not consider fancy protein alphabets with gaps or stop codons (an old and overly complicated design in biopython):

https://github.com/biopython/biopython/blob/biopython-169/Bio/codonalign/__init__.py#L82

**Comment by peterjc** [comment]
I think I have a fix for this, but it would be useful to have a small test case...

**Comment by universvm** [comment]
Sorry for the format issues. I just fixed my post. 

I can send you 3 sequences I was working on. I added a "---" after the first ATG. I had to make a zip file since they do not accept fasta as a format.
[sequence.fasta.zip](https://github.com/biopython/biopython/files/921963/sequence.fasta.zip)

**Comment by peterjc** [comment]
Could you share your script too? If we use this to write a test case, are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

Also, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by universvm** [comment]
My file is extremely long at the moment, as I did all sorts of stuff. However if you are ok with it I could simplify it and send it to you. At the moment it includes:

- dN/dS calculation for a matrix, 
- N and S calculation for each sequence,
- Production of a dn_tree and a ds_tree,

I also worked on a matrix parser which takes elements in the matrix generated by Biopython and produces something like this:

<img width="343" alt="screenshot_2017-04-14 12 25 18" src="https://cloud.githubusercontent.com/assets/17524568/25042128/7f49a1e2-210d-11e7-9f64-fef7729dbcf5.png">

This is useful in case you want to produce a graphical representation.
Let me know if there's anything you'd prefer.

**Comment by peterjc** [comment]
Hmm. Hopefully the module's author can come up with a short test case then, I've asked on #1153.

**Comment by universvm** [comment]
I updated a simplified file for a test case, if you want you could use it as a test case.

**Comment by peterjc** [comment]
This should be fixed now.

@universvm are you comfortable getting Biopython from GitHub and installing it from source on your Mac? You can do this via pip if you installed Biopython that way...

Otherwise the simplest option may be to backup ``/usr/local/lib/python2.7/site-packages/Bio/codonalign/__init__.py`` and then edit it by hand to apply these three small changes:

https://github.com/biopython/biopython/pull/1153/commits/7eb697231e454dbd2d3d0f67c78747791c379ded

**Comment by universvm** [comment]
I updated biopython by hand since pip didn't seem to work. Everything is fixed! Thank you so much!

**Comment by peterjc** [comment]
You would have needed something like this to grab the latest code from GitHub via pip (rather than ``pip install --upgrade biopython`` which would just get the latest release on PyPI which does not have this fix yet),

```
pip install git+git://github.com/biopython/biopython.git
```

or,

```
pip install https://github.com/biopython/biopython/archive/master.tar.gz
```

(untested, based on a quick Google search)

Anyway, thanks for quickly trying this out and confirming the fix works for your example. 👍
