### ISSUE TITLE
Testing Bio/PDB/REsidueDepth.py, missing MSMS software

### ISSUE THREAD

**Issue by Gasta88** [biopython/biopython#1152]
Hi,

in the process of testing `Bio/PDB/ResidueDepth.py` I'm finding some problems.

I'm  using one of the PDB in the `Tests/PDB` folder. 
As mentioned in the `Bio/PDB/ResidueDepth.py`, a tool called MSMS is required (source: http://mgltools.scripps.edu/packages/MSMS).

I download and install the application for Windows. This is the result:

```
'\\homes\fgastaldello\Documents\Python Scripts'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'pdb_to_xyzr' is not recognized as an internal or external command,
operable program or batch file.
'\\homes\fgastaldello\Documents\Python Scripts'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'msms' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\fgastaldello\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "C:\Users\fgastaldello\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "//homes/fgastaldello/Documents/Python Scripts/ResDepth_minitest.py", line 8, in <module>
    rd = ResidueDepth(model, prot_file)
  File "C:\Users\fgastaldello\AppData\Local\Continuum\Anaconda3\lib\site-packages\Bio\PDB\ResidueDepth.py", line 144, in __init__
    surface = get_surface(pdb_file)
  File "C:\Users\fgastaldello\AppData\Local\Continuum\Anaconda3\lib\site-packages\Bio\PDB\ResidueDepth.py", line 90, in get_surface
    "Failed to generate surface file using command:\n%s" % make_surface
AssertionError: Failed to generate surface file using command:
msms -probe_radius 1.5 -if C:\Users\FGASTA~1\AppData\Local\Temp\tmpiz5raqw9 -of C:\Users\FGASTA~1\AppData\Local\Temp\tmppw80tauf > C:\Users\FGASTA~1\AppData\Local\Temp\tmpuj1lyj7s
```

Machine specs:
> Windows 7 Enterprise 64-bit
> 4GB RAM memory
> Processor i5 Intel

**Comment by peterjc** [comment]
How are you running ``ResidueDepth``?

Can you run ``pdb_to_xyzr`` directly yourself at the Windows command line?

Can you run ``msms`` directly yourself at the Windows command line?

**Comment by Gasta88** [comment]
I'm taking the self-test of `ResidueDepth` and modify it as such:
```python
from Bio.PDB import PDBParser, ResidueDepth

prot_file="//homes/fgastaldello/Desktop/GitHub/biopython/Tests/PDB/2XHE.pdb"
p = PDBParser()
s = p.get_structure("X", prot_file)
model = s[0]

rd = ResidueDepth(model, prot_file)

for item in rd:
    print(item)
```

From comand line I'm not able to run neither `msms` nor `pdb_to_xyzr`.

**Comment by peterjc** [comment]
OK, first you have to be able to run these tools from the command line.

Does it work with a full path like ``C:\Program Files\where you installed the file\msms.exe`` at the command line? If so, the simple fix is likely adding that folder to the ``$PATH``.

Also, given the warning ``UNC paths are not supported.`` try replacing:

```
prot_file = "//homes/fgastaldello/Desktop/GitHub/biopython/Tests/PDB/2XHE.pdb"
```

The tests will be run from the ``.../biopython/Tests`` folder, so try a relative path like:

```
prot_file = "PDB/2XHE.pdb"
```

and if that fails, try with Windows specific slashes using:

```
prot_file = os.path.join("PDB", "2XHE.pdb")
```

**Comment by Gasta88** [comment]
I've managed to make some progress with the Windows installation and reach the point of calling the method `get_surface`. After that, it failed.

I'll wait for @JoaoRodrigues to update the module and try again to see if I can progress further.

**Comment by Gasta88** [comment]
Installed MSMS on my Linux environment and I'm carry on some testing for the `Bio.PDB.ResidueDepth` module. A new PR will be open in the near future.

**Comment by peterjc** [comment]
See #1508
