### ISSUE TITLE
Customizing the BioSQL database schema.

### ISSUE THREAD

**Issue by robear22890** [biopython/biopython#1155]
I'd like to make some customizations to the BioSQL schema so that I can more efficiently access the data that I require.  I'm interested in a handful of genes.  I understand SQL, but I'm also very new to it so I have a lot to learn.  I'd like to add the following data to the schema in the **_biosqldb-sqlite.sql_** file:
[example_BioSQL_table.csv](https://github.com/robear22890/Vallender-Labs-Scripts/blob/master/archive/example_BioSQL_table.csv)

Here is a more complex example that I'd like to use:
[example_BioSQL_table2.csv](https://github.com/robear22890/Vallender-Labs-Scripts/blob/master/archive/example_BioSQL_table2.csv)

I think that I need to add the following tables:
### Gene Table
| P.K. id | Gene Name | Entrez ID | F.K. to gene | F.K. to tier | F.K. to accessions |
|---------|-----------|-----------|--------------|--------------|--------------------|
|         |           |           |              |              |                    |
|         |           |           |              |              |                    |

### Tier Table
| P.K. id | Tier Name | Tier Description |
|---------|-----------|------------------|
|         |           |                  |
|         |           |                  |

### Accession Table
| F.K. to my gene table (P.K.) | Gene Name | Organism_1 Name | Organism_2 |
|-----------------------|-----------|-----------------|------------|
|                       |           |                 |            |
|                       |           |                 |            |

This may not be the place to ask for this, but I wasn't sure where else to go with this issue.

**Comment by peterjc** [comment]
If this would be a generally useful extension to BioSQL, then see https://github.com/biosql/biosql

If you just want to add tables for local use, then you are free to modify your local copy of the schema - are you looking for advice on doing this from Python?

**Comment by robear22890** [comment]
Well I'd like to test out some ideas once I get some SQL under my belt.  However, I am interested in changing the .sql script for my needs in the long term.  In the short term I could definitely use some advice on using Python/BioPython to upload my own tables and data.  For instance is there anything that I should avoid?  And is there an easier way to do this/Is someone else already doing something similar?
Thanks for responding to my question @peterjc.

**Comment by peterjc** [comment]
The database back ends that Biopython's BioSQL code uses are fairly low level, and we've essentially implemented our our ``SeqRecord`` focused Object-relational mapping (ORM), with enough abstraction to handle different SQL back ends and adaptors (not just SQLite3).

Nowadays there are things like SQLAlchemy for this general problem, although using something like this with a pre-defined schema (like the BioSQL schema which is shared between Bio* projects) seems a little harder.

My point is following the Biopython BioSQL coding style may not be the best plan for learning modern Python and SQL best practise (but I'm not done much of this myself for several years now).

**Comment by robear22890** [comment]
Ok thanks.  I'll start learning SQLAlchemy and SQLite3 as well, and then I'll start making some changes.  Maybe I can do something worth pushing to biosql.  
Thanks for helping.

**Comment by peterjc** [comment]
OK. I'm going to close this issue for now. Good luck.
