### ISSUE TITLE
Faulty assertion in Tutorial::Entrez

### ISSUE THREAD

**Issue by jimmyodonnell** [biopython/biopython#1156]
#There is an assertion in the entrez chapter of the tutorial that requires that the total count of records  returned (`search_result["Count"]`) is equal to the length of the list of accession numbers (`search_result["IdList"]`). However, `search_result["IdList"]` is constrained by the `retmax` argument to `Entrez.esearch`, while `search_result["Count"]` is the total number of records found. Thus, in a valid case, `Count` can exceed the length of `IdList`.

This doesn't cause any errors, but could worry and confuse newcomers (like myself!).

[This issue references PR #1068 'remove assertion comparing Count and IdList'.]

**Comment by peterjc** [comment]
As per our discussion on #1068, it isn't a faulty assert - its emphasising that while you might expect the count to match the number of IDs it might not.

I agree that right now this is not very explicit/clear, but rather than just removing it (as in #1157) the tutorial could explain how the return max limit comes into play.

**Comment by jimmyodonnell** [comment]
Got it; I agree that an explanation would be great and I'm happy to add it. I started to do so, but felt it interrupted the flow of this section. I understand the intent of this section to be introducing the additional WebEnv and QueryKey elements of the search results. I think pointing out the potential for differences between the length of `IdList` and `Count` would be best introduced much earlier -- I was thinking it would fit in perfectly with the first search of GenBank circa line 190. How does that sound? Also, instead of using `assert()`, do you think `count == acc_list` would return a result that would make more sense to the target audience?

**Comment by peterjc** [comment]
If you think this fits better later on, you're probably right 👍

**Comment by jimmyodonnell** [comment]
Bueno -- I made these changes.
