### ISSUE TITLE
bppseqgen expected to ignore branch length from root to mrca?

### ISSUE THREAD

**Issue by psathyrella** [biopython/biopython#1159]
It appears that bppseqgen doesn't mutate according to the distance between root and mrca. For instance using a tree like:

`(t1:0.001,t2:0.001):0.1;`

results in two essentially unmutated sequences. Adding a dummy leaf `xxx` branched from root to this tree, on the other hand, results in the expected mutation rates:

`((t1:0.001,t2:0.001):0.1,xxx:0.101):0.0;`

This seems like unexpected behavior to me, but perhaps I'm missing something?

**Comment by peterjc** [comment]
What is bppseqgen?

**Comment by psathyrella** [comment]
oh my goodness, oops. Wrong repo, sorry.

**Comment by peterjc** [comment]
Ah - easily done. Thanks
