### ISSUE TITLE
Entrez.efetch could not get Genbank flat text recently

### ISSUE THREAD

**Issue by wpwupingwp** [biopython/biopython#1161]
```python
             Entrez.email = my_email
             handle = Entrez.read(Entrez.epost(db='nuccore',
                                               id=', '.join(to_down)))
              genome_content = Entrez.efetch(db='nuccore',
                                           webenv=handle['WebEnv'],
                                             query_key=handle['QueryKey'],
                                             retfragment_type='gb',
                                            retmode='text')
             with open(genbank_file, 'a') as output_file:        
                 output_file.write(genome_content.read())
```

This is my code. It works fine before to get Genbank flat text from given Accession id list. 
Today I found that efetch return strange result which Bio.SeqIO could not parse as genbank format:

>     Seq-entry ::= set {
> 
>     class nuc-prot ,
> 
>     descr {
> 
>       source {
> 
>       genome chloroplast ,
> 
>       origin natural ,
> 
>       org {
> 
>         taxname "Zygnema circumcarinatum" ,
> 
>         db {
> 
>           {
> 
>             db "taxon" ,
> 
>             tag
> 
>               id 35869 } } ,
> 
>         orgname {
> 
>           name
> 
>             binomial {
> 
>               genus "Zygnema" ,
> 
>               species "circumcarinatum" } ,
> 
>           lineage "Eukaryota; Viridiplantae; Streptophyta; Zygnemophyceae;
> 
>      Zygnematales; Zygnemataceae; Zygnema" ,
> 
>           gcode 1 ,
> 
>           mgcode 1 ,
> 
>           div "PLN" } } ,
> 
>       subtype {
> 
>         {
> 
>           subtype cell-line ,
> 
>           name "SAG 698-1a" } } } ,
> 
>     pub {
> 
>       pub {
> 
>         article {
> 
>           title {
> 
>             name "The complete chloroplast DNA sequences of the charophycean
> 
>       green algae Staurastrum and Zygnema reveal that the chloroplast genome
> 
>       underwent extensive changes during the evolution of the Zygnematales." } ,
> 
>           authors {
> 
>             names
> 
>               std {
> 
>                 {
> 
>                   name
> 
>                     name {
> 
>                       last "Turmel" ,
> 
>                       initials "M." } ,
> 
>                   affil
> 
>                     str "Departement de Biochimie et de Microbiologie,
> 
>      Universite Laval, Quebec, Quebec, G1K 7P4, Canada.
> 
>      monique.turmel@rsvs.ulaval.ca" } ,
> 
>                 {
> 
>                   name
> 
>                     name {
> 
>                       last "Otis" ,
> 
>                       initials "C." } } ,
> 
>                 {
> 
>                   name
> 
>                     name {
> 
>                       last "Lemieux" ,
> 
>                       initials "C." } } } } ,
> 

If I change **retmode** to "xml", Entrez.parse could handle it but I do not know how to generate files from it which Bio.SeqIO could handle with.
Does Entrez change its result format or my code is wrong? ( I guess not because it works fine from 2014)
Or is there any way to parse xml format genbank record by Bio.SeqIO?

Ping Wu

**Comment by peterjc** [comment]
That looks like JSON format.

It looks like you have a mistake in the argument name where you doing this:

``Entrez.efetch(..., retfragment_type='gb', retmode='text')``

try:

``Entrez.efetch(..., rettype='gb', retmode='text')``

**Comment by wpwupingwp** [comment]
!!!
Sorry for bothering. Fix it.  

Ping Wu

**Comment by peterjc** [comment]
No problem - it can be hard sometimes to spot a typo like this if you're not familiar with the API.

**Comment by peterjc** [comment]
Ideally the NCBI would catch this and return an error HTTP code. Sadly they don't do this with Entrez (IMHO, the NCBI error handling is the worst thing about NCBI Entrez API).

Conversely, we don't know the full range of valid arguments for ``rettype`` - and they might add a new one tomorrow. We could perhaps define a list of known formats (per database as per the NCBI documentation), and issue a warning if an unexpected one is used?

Likewise, we don't know the full range of possible argument names - again they might add a new one tomorrow.

**Comment by blaiseli** [comment]
A warning could be useful indeed. That said, I'm wondering what this format is and how I could parse it because it seems to contain useful information in my case: I'm fetching transcripts, some of which are predicted, and I want to know what it the genomic origin of the predicted transcript. The origin scaffold ID appears inside a comment in the genbank record, but this same information appears to exist in structured format in this data, inside a "ModelEvidence" section.

It seems to be [ASN.1](https://www.ncbi.nlm.nih.gov/Structure/asn1.html) format.

**Comment by peterjc** [comment]
The NCBI do still use ASN.1 internally for many things, but support for parsing this is nowhere near as widespread as XML.

Oftentimes playing around with the NCBI output you can find several routes to get the information you need - and some files are going to be much smaller than others which can be preferential.
