### ISSUE TITLE
Handling UnknownPosition

### ISSUE THREAD

**Issue by aaronk** [biopython/biopython#1165]
I'm working on a BioSQL database for SwissProt entries and it's balking at some of the UnknownPosition values that are being set by the SeqIO parser (I'm using BioPython 1.69).  I'm sure wading into the fuzzy location morass is not a fun prospect, but I'm wondering if this has been given some thought.  I'm happy to try to implement any reasonable suggestion. 

For reference, the specific error that comes up is in BioSQL/Loader.py line 912.  Uniprot record P97881 is an example:
    
      File "/n/home_rc/akitzmiller/.conda/envs/2.7.13/lib/python2.7/site-packages/biopython-1.69-py2.7-linux-x86_64.egg/BioSQL/Loader.py",  line 912, in _insert_location
          end = int(location.end)
      TypeError: int() argument must be a string or a number, not 'UnknownPosition'

**Comment by peterjc** [comment]
At first glance this looks like something missing from our BioSQL mappings - the ``UnknownPosition`` does not exist in EMBL/GenBank which is what BioSQL was designed for.

The tricky bit would likely be how best to represent this in BioSQL: https://github.com/biosql/biosql/issues/11

e.g. Does the relevant table allow us to use ``NULL`` for the start/end?

**Comment by aaronk** [comment]
I don't recall where I saw it, but there was some note somewhere that said the value could be null.

ajk

**Comment by peterjc** [comment]
You're right - there are comments in the schema about explicitly allowing NULL for the location table start/end.

Do you have enough information to have a go adding this to Biopython's BioSQL interface?

**Comment by aaronk** [comment]
Sure.

ajk

**Comment by aaronk** [comment]
Dealing with the UnknownPosition was not too hard.  It's the pydocstyle test that seems to be a problem :)

I haven't changed files like Bio/NaiveBayes.py, but I'm getting a bunch of errors when generating the pull request:

    style runtests: commands[5] | pydocstyle Bio/ BioSQL/ Tests/ Scripts/ Doc/
    Bio/NaiveBayes.py:42 in public class `NaiveBayes`:
            D406: Section name should end with a newline ('Attributes', not 'Attributes:')
    Bio/NaiveBayes.py:42 in public class `NaiveBayes`:
            D407: Missing dashed underline after section ('Attributes')
    Bio/NaiveBayes.py:59 in public function `calculate`:
            D406: Section name should end with a newline ('Returns', not 'Returns:')

Looks like other recent PRs have passed just fine.

ajk

**Comment by peterjc** [comment]
Thanks for the heads up. I was able to reproduce this - it looks like the new release pydocstyle v2.0.0 is stricter, v1.1.1 was fine.

**Comment by peterjc** [comment]
I've 'fixed' the pydocstyle problem cc2ad72f1f237b3ff779b151fdf529abba1f3459, and filed an issue about cleaning up the style issues - #1170
