### ISSUE TITLE
Turn Bio/PDB/Dice.py into an example script and/or test case

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1167]
Following discussion on #820, we propose to deprecate ``Bio.PDB.Dice`` - see pull request #1166

It would be nice to turn ``Bio/PDB/Dice.py`` into an example under ``Scripts/PDB/`` or a unit test under ``Tests/`` (if needed for test coverage).

**Comment by souravsingh** [comment]
Would it be good if we can use Dice.py both as example as well as a unit-test?

**Comment by peterjc** [comment]
Both would be nice.

For the unit-test you would off course have to pick some specific PDB file from ``Tests/PDB/`` as the input, and include some validation of the output. e.g. Write it to a temporary file, parse that to confirm the number of atoms, and then delete the temp file.

**Comment by Gasta88** [comment]
@souravsingh are you working on the unit-test?If not, I can help on this.

Will this testing be hosted inside the others in `Tests/test_PDB.py` or will it be by itself?

**Comment by souravsingh** [comment]
@Gasta88 I am working on it.

**Comment by peterjc** [comment]
I was thinking we might want to split up ``test_PDB.py`` as its getting quite long...

**Comment by peterjc** [comment]
I've reverted the deprecation in 3b7f121371e2a0f30177a7643acf9ac521996ffd
