### ISSUE TITLE
Bio.PDB sorting not tested and Python 2 only

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1189]
The ``cmp`` function is Python 2 only, sorting using a key function is the preferred idiom for Python 2 and 3.

``Bio/PDB/Chain.py`` class ``Chain`` uses ``cmp`` in never used private method ``._sort```, could remove this?

``Bio/PDB/Structure.py`` class ``Structure``, same.

``Bio/PDB/Model.py`` class ``Model``, same.

``Bio/PDB/Residue.py`` class ``Residue`` defines ``._sort`` and uses in public ``.sort`` but not tested.

Spotted via flake8 tests (installed and running under Python 3),

```
$ flake8 --config=/dev/null --select F821 Bio/PDB/
Bio/PDB/Chain.py:34:20: F821 undefined name 'cmp'
Bio/PDB/Chain.py:36:20: F821 undefined name 'cmp'
Bio/PDB/Chain.py:37:16: F821 undefined name 'cmp'
Bio/PDB/Model.py:52:16: F821 undefined name 'cmp'
Bio/PDB/Residue.py:52:20: F821 undefined name 'cmp'
Bio/PDB/Residue.py:62:20: F821 undefined name 'cmp'
Bio/PDB/Residue.py:67:16: F821 undefined name 'cmp'
Bio/PDB/Structure.py:36:16: F821 undefined name 'cmp'
```

**Comment by peterjc** [comment]
@etal @lennax @JoaoRodrigues etc - comments welcome on how best to solve this, thanks.

**Comment by JoaoRodrigues** [comment]
I'll have a look. Sorting should be simple for anything but Atom objects.

**Comment by peterjc** [comment]
I would guess we can delete/deprecate the ``._sort`` methods, and add ``.sort`` using ``key=...`` rather than the legacy ``cmp`` style sorting?

**Comment by JoaoRodrigues** [comment]
I guess so, but I need to have a look. Can't remember the exact
implementation and details..​

**Comment by peterjc** [comment]
@JoaoRodrigues are you likely to be able to look at this this week? If not do you mind if I try?

**Comment by JoaoRodrigues** [comment]
Hi Peter,

Go ahead, I've been swamped lately with several different projects needing
my attention and these issues were sort of left behind for now..​

Cheers,

João
