### ISSUE TITLE
Parser needs updating for MEME version 4.11.4

### ISSUE THREAD

**Issue by mrafante** [biopython/biopython#1193]
As the MEME was updated at Apr, 07, 2017, the Bio/motifs/meme.py lib to read the resultant file is not working.

**Comment by aralap** [comment]
Is someone working on this? I will adress it if not.

**Comment by peterjc** [comment]
I'm not aware of anyone working on it, so that would be great. See also #232

**Comment by peterjc** [comment]
And see also #793.

**Comment by j-andrews7** [comment]
@aralap Has this been addressed? Do we know what change caused the error? It'd be nice to retain backwards compatibility with previous versions if possible.

**Comment by aralap** [comment]
@j-andrews7 It has been adressed, and retains backwards compatibility (as far as i know) 
#1372 #1374

**Comment by j-andrews7** [comment]
@aralap thanks, good to know. @peterjc could this issue be closed to prevent further confusion?

**Comment by peterjc** [comment]
Thanks for the reminder, closed via #1372 and #1374.
