### ISSUE TITLE
PDB mmCIF parser labels water molecules as 'H_HOH', not 'W'

### ISSUE THREAD

**Issue by andrewguy** [biopython/biopython#1197]
The two parsers for PDB files should behave consistently, but currently the mmcCIF parser labels all waters as `'H_HOH'`, rather than `'W'`.

#1196 fixes this inconsistency, but wanted to raise this here as it will change the output from the mmCIF parser  - all water residues would now be accessed with the key `('W', ##, ' ')`, rather than `('HOH', ##, ' ')`. Note that this is the approach used by PDBParser.py, and could therefore be considered the standard approach.

**Comment by peterjc** [comment]
Good question: @JoaoRodrigues @lennax @etal etc, what do you think?

**Comment by peterjc** [comment]
You might as well comment on the pull request #1196...
