### ISSUE TITLE
Adopt flake8-docstrings to run pydocstyle via flake8

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1199]
Once it has been updated for pydocstyle v2.0.0, I propose we use ``flake8-docstrings`` to run the docstring (PEP257) checks via ``flake8`` instead of calling ``pydocstyle``.

Cross reference https://gitlab.com/pycqa/flake8-docstrings/issues/19

i.e. For both the TravisCI/Tox configuration and the proposed git pre-commit hook.

The advantage of this is we can get ride of our ``.pydocstyle`` configuration file and move those settings into ``.flake8`` and then just need to run a single tool for the style checks.

Cross reference #1170 and #493 and #883

**Comment by MarkusPiotrowski** [comment]
I adopted the fix mentioned in https://gitlab.com/nightmarebadger/flake8-docstrings/commit/8ffc68a821fd3b89641c10c3086d6672e04f5bf4 manually. These are just a few lines and it worked fine. Used ```flake8-docstring``` for the recent work on ```Restriction.py``` as pre-commit hook locally.

**Comment by peterjc** [comment]
That's good news. If we can get all the python code checks via ``flake8``, then a standard flake8 pre-commit git hook ought to be enough for Biopython.

Right now on #1188 I have an overly complicated script which does ``flake8`` and ``pydocstyle`` on changed Python files, plus ``rst-lint`` on changed RST files.

**Comment by peterjc** [comment]
flake8-docstrings v1.0.1 has been released now, testing now...

**Comment by peterjc** [comment]
Note right now the flake8 provided git pre-commit hook is unusable as it doesn't restrict itself to just Python files: https://gitlab.com/pycqa/flake8/issues/325
