### ISSUE TITLE
SwissProt : parse PE line, debug sequence version and propagate to record

### ISSUE THREAD

**Issue by FredericBGA** [biopython/biopython#1207]
In order to get an Uniprot fasta header (http://www.uniprot.org/help/fasta-headers), you need to retrieve Protein Existence value and sequence version as well.

The PE tag was not yet parsed.
The value of version seemed to be broken (always retrieved as 0).

Using the patch, you will be able to create PE and SV tags in this manner :

```
for record in SeqIO.parse(options.file, "swiss"):
    if (record.protein_existence):       
        protein_existence = " PE=" + record.protein_existence
    version = " SV=" + record.annotations['version']
```

I have parsed the whole Uniprot .dat files without any problem.

soory for the patch, but I failed to launch the "git push" command (http://biopython.org/wiki/GitUsage) from my private network.

Fred
[swissProt-parse-PE-and-debug-sequence-version.patch.txt](https://github.com/biopython/biopython/files/973314/swissProt-parse-PE-and-debug-sequence-version.patch.txt)

**Comment by peterjc** [comment]
It looks like you are adding a new attribute to the ``SeqRecord`` here:

```
--- a/Bio/SeqIO/SwissIO.py
+++ b/Bio/SeqIO/SwissIO.py
@@ -93,6 +93,7 @@ def SwissIterator(handle):
                                                in swiss_record.features],
                                      )
         record.description = swiss_record.description
+        record.protein_existence = swiss_record.protein_existence
         for cross_reference in swiss_record.cross_references:
             if len(cross_reference) < 2:
                 continue
```

Please instead add this to the ``.annotations`` dictionary, e.g.

```python
record.annotations["protein_existence"] = swiss_record.protein_existence
```

Regarding the git push failure, can you show us the exact error message and also the output for ``git remote -v`` (sometimes it is down to the URL used for cloning, https vs git, and your firewall)?

**Comment by FredericBGA** [comment]
Ok, I will modify in order to avoid the creation of a new attribute.

And regarding the push failure, I know that this is due to the firewall but it's not that simple to ask for a change in the current configuration.

**Comment by peterjc** [comment]
What I mean is I have found sometimes when e.g. ``git@github.com:peterjc/biopython.git`` does not work, ``https://github.com/peterjc/biopython.git`` might. Or the other way round.

**Comment by FredericBGA** [comment]
Here is the new patch.
[swissProt-parse-PE-and-debug-sequence-version.patch2.txt](https://github.com/biopython/biopython/files/973619/swissProt-parse-PE-and-debug-sequence-version.patch2.txt)

**Comment by peterjc** [comment]
I may have to create a pull request on your behalf (using your patches) to get the TravisCI tests run. I would ask you to include a unit test for this though, something in ``test_Uniprot.py`` I would think which confirms the field has been parsed.

Also, are you happy to dual licence your contributions under both the _Biopython License Agreement_ AND the _BSD 3-Clause License_? See #898.

And, are you happy to be thanked by name in the ``NEWS.rst`` and ``CONTRIB.rst`` files?

**Comment by FredericBGA** [comment]
ok, I will have a look to tests.
I agree for the licence and citation.

**Comment by FredericBGA** [comment]
here is the new version of the patch 

I have added test, cast version and protein existence to int.

I have change annotations version to sequence_version and entry_version in order to be clearer.
I have add a test because protein existence is not always present (old SP files)

[swissProt-parse-PE-and-debug-sequence-version.patch3.txt](https://github.com/biopython/biopython/files/976256/swissProt-parse-PE-and-debug-sequence-version.patch3.txt)

**Comment by FredericBGA** [comment]
ok, I manage to create a Pull Request (over SSH).
This topic can be closed.

**Comment by peterjc** [comment]
Cross reference pull request #1211 - thank you for sorting the firewall issue 👍

**Comment by peterjc** [comment]
Belatedly, would you agree to dual license your contributions as per #898? Thanks!
