### ISSUE TITLE
Bio.pairwise.align.* docstrings

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1210]
As flagged on Twitter by Bede Constantinides (@Bebe on GitHub), 
https://twitter.com/beconstant/status/860079532946202624

The main docstring describes e.g. ``localxx``,

```python
>>> from Bio import pairwise2
>>> help(pairwise2)
```

However, the alignment class lacks this key information:

```python
>>> from Bio import pairwise2
>>> help(pairwise2.align)
```
```
Help on align in module Bio.pairwise2 object:

class align(builtins.object)
 |  This class provides functions that do alignments.
 |  
 |  Methods defined here:
 |  
 |  __getattr__(self, attr)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  alignment_function = <class 'Bio.pairwise2.align.alignment_function'>
 |      This class is callable impersonates an alignment function.
 |      The constructor takes the name of the function.  This class
 |      will decode the name of the function to figure out how to
 |      interpret the parameters.
```

As do the methods,

```python
>>> from Bio import pairwise2
>>> help(pairwise2.align.localxx)
```
```
Help on alignment_function in module Bio.pairwise2 object:

localxx = class alignment_function(builtins.object)
 |  This class is callable impersonates an alignment function.
 |  The constructor takes the name of the function.  This class
 |  will decode the name of the function to figure out how to
 |  interpret the parameters.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args, **keywds)
 |      Call self as a function.
 |  
 |  __init__(self, name)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  decode(self, *args, **keywds)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  match2args = {'c': (['match_fn'], 'match_fn is a callback function tha...
 |  
 |  penalty2args = {'c': (['gap_A_fn', 'gap_B_fn'], 'gap_A_fn and gap_B_fn...
```

Initially we could perhaps move/copy key bits of the module docstring into the class docstring?

Adding docstrings to the class' methods like ``localxx`` look tricky given the current ``__getattr__`` based approach (modern Python likely offers a more elegant way to do that).

**Comment by roccomoretti** [comment]
I came here to post this.

Though I would argue that this counts as a "Bug" rather than an "Enhancement", as the current `help(pairwise2)` has the following to say near the bottom:

    To see a description of the parameters for a function, please look at
    the docstring for the function via the help function, e.g.
    type ``help(pairwise2.align.localds)`` at the Python prompt.

And `help(pairwise2.align.localds)` is distinctly unhelpful.

**Comment by peterjc** [comment]
Well spotted. If we can't easily add docstrings to the magic methods, we can at least tweak that text.

**Comment by MarkusPiotrowski** [comment]
There is an attempt to set the docstring correctly in ```pairwise2``` but it doesn't seem to work:

```python
# Set the doc string.
            doc = "%s(%s) -> alignments\n" % (
                self.__name__, ', '.join(self.param_names))
            if match_doc:
                doc += "\n%s\n" % match_doc
            if penalty_doc:
                doc += "\n%s\n" % penalty_doc
            doc += ("""\
\nalignments is a list of tuples (seqA, seqB, score, begin, end).
seqA and seqB are strings showing the alignment between the
sequences.  score is the score of the alignment.  begin and end
are indexes into seqA and seqB that indicate the where the
alignment occurs.
""")
            self.__doc__ = doc
```

```self.__doc__``` is obviously not used by ```help()```. Interestingly, you can print it:

```
>>> from Bio import pairwise2
>>> help(pairwise2.align.globalxx)
Help on alignment_function in module Bio.pairwise2 object:

globalxx = class alignment_function(__builtin__.object)
 |  This class is callable impersonates an alignment function.
 |  The constructor takes the name of the function.  This class
 |  will decode the name of the function to figure out how to
 |  interpret the parameters.
 |  
 |  Methods defined here:
 |  
...
 |  
 |  penalty2args = {'c': (['gap_A_fn', 'gap_B_fn'], 'gap_A_fn and gap_B_fn...

>>> print(pairwise2.align.globalxx.__doc__)
globalxx(sequenceA, sequenceB) -> alignments

alignments is a list of tuples (seqA, seqB, score, begin, end).
seqA and seqB are strings showing the alignment between the
sequences.  score is the score of the alignment.  begin and end
are indexes into seqA and seqB that indicate the where the
alignment occurs.
```

**Comment by peterjc** [comment]
Yeah, I think the problem is how the 'method' is defined at run time - likely something like https://github.com/biopython/biopython/blob/biopython-169/Tests/test_SeqIO_index.py#L666 would work better?

At least there the docstring exists via the help command:

```
>>> import test_SeqIO_index
>>> dir(test_SeqIO_index.IndexDictTests)
>>> help(test_SeqIO_index.IndexDictTests.test_swiss_SwissProt_sp010_keyf)
...
```

**Comment by MarkusPiotrowski** [comment]
I give up on this one. Posted a question to SO (http://stackoverflow.com/questions/43830759/help-doesnt-return-docstring-of-method-when-using-magical-getatrr), without getting a solution. 

As a workaround, we can rephrase the module's docstring part saying:

> To see a description of the parameters for a function, please look at
the docstring for the function via the help function, e.g.
type ``help(pairwise2.align.localds)`` at the Python prompt.

into 
> ...please print the docstring for the function by typing
 ``print(pairwise2.align.localds.__doc__)`` at the Python prompt.

And we may copy some parts from the module's docstring into the ```align``` and ```alignment_function``` classes. Their actual docstrings may be converted to comments.

**Comment by peterjc** [comment]
For the short term I would say expand the align class docstring to include some of the function name information and/or a pointer to the main module docstring.

Medium term it does look like we have to replace the ``__getattr__`` magic in order to add proper docstrings to the class methods.

**Comment by MarkusPiotrowski** [comment]
The problem is that parameters are encoded within the function names, so 16, sorry, 32 different functions are possible: ```globalxx```, ```globalxs```, ... ```localcc```. I guess that was the reason for using ```__getattr___``` in the first place. 
As suggested earlier by @mdehoon in #782 we should, in median term, made a new ```pairwise``` module, 
1.  with a different interface (e.g. two methods ```align_local``` and ```align_global``` where the parameters are passed to the methods)
2.  which accepts and returns alignment objects (and is possibly located within ```Bio.Align``)`
3.  with an additional functionality which allows to do pairwise alignments in linear space

**Comment by peterjc** [comment]
A new module with a clean API would seen a good long term solution.

**Comment by mdehoon** [comment]
I have some working code for pairwise alignments that I have been using for my own work. I'd be happy to share it if somebody wants to turn it into a new module for Biopython.

**Comment by MarkusPiotrowski** [comment]
@mdehoon Can I have a look at the code?
I think the functionality of the current ```pairwise2``` is OK, and speed and memory usage is also OK (when using the C module). Writing a C function from scratch is probably beyond my capabilities.

**Comment by mdehoon** [comment]
@MarkusPiotrowski 
Please have a look at
https://github.com/mdehoon/biopython/tree/aligner/Bio/Align

An example script is
```python
from Bio.Align import algorithms

aligner = algorithms.NeedlemanWunsch()
aligner.gap_open = -1
aligner.gap_extend = -1
aligner.end_gap_open = (-1, 0)
aligner.end_gap_extend = (-1, 0)
aligner.match = 0
aligner.mismatch = -1
# This is just some particular set of scoring parameters; they can be adjusted depending on the purpose.

A = "AAAAAAAGGGGGGAAAAAA"
B = "GGCGG"

alignments = aligner.align(A, B)

for alignment in alignments:
    print alignment[0]
    print alignment[1]
    print alignment[2]
```

which prints all alignments between the two sequences with the maximum alignment score:
```
AAAAAAAGGGG-GGAAAAAA
---------GGCGG------
-1.0
AAAAAAAGGGGGGAAAAAA
--------GGCGG------
-1.0
AAAAAAAGGG-GGGAAAAAA
--------GGCGG-------
-1.0
AAAAAAAGGGGGGAAAAAA
-------GGCGG-------
-1.0
AAAAAAAGG-GGGGAAAAAA
-------GGCGG--------
-1.0
```

I think the alignment scores can be further generalized a bit by replacing `end_gap_open`, `end_gap_extend` by `left_gap_open`, `left_gap_extend`, `right_gap_open`, `right_gap_extend`.

From a performance viewpoint (and probably also for ease of use), I do think that creating an aligner object and reusing it to do alignments is better than calling a function (in particular because of the number of scoring parameters).

Let me know if you need help with the C code.

**Comment by MarkusPiotrowski** [comment]
As the docstring issue is solved, we can close this one

**Comment by peterjc** [comment]
Thanks all.
