### ISSUE TITLE
Restriction Enzymes Type #enhancement

### ISSUE THREAD

**Issue by paxelito** [biopython/biopython#1226]
Hi, 

is there a way to get the relative restriction enzymes type (I, II, IIs, ..., V) from the Bio.Restriction package?

**Comment by peterjc** [comment]
Hmm, REBASE does have the types (at leave, I to IV but I don't see V):

http://rebase.neb.com/rebase/rebtypes.html

However, I don't see this information in the EMBOSS format downloads we use for Biopython http://rebase.neb.com/rebase/rebase.f37.html nor in the format used for BioPerl http://rebase.neb.com/rebase/rebase.f31.html

Indeed scanning http://rebase.neb.com/rebase/rebase.files.html I can see some lists for type II only, but I didn't see any obvious listing including the type.

You might have to ask the REBASE authors if they provide this information in a computer-readable format.

CC @MarkusPiotrowski as he may know.

**Comment by MarkusPiotrowski** [comment]
As said by @peterjc, the REBASE files we use don't have this information. There are some REBASE files which do have this information (e.g. http://rebase.neb.com/rebase/rebase.f19.html). So to get this information we would need to use a different file format from the beginning or in addition to the used files. Which would require a major re-write of ```ranacompyler.py``` the script that extracts the data from the REBASE files and writes it to ```Restriction_Dictionary.py```.

But what is the use-case for this information?
Of course you can use ```Restriction.py``` to fetch some general information about the enzyme (e.g. suppliers). And some of them may be of some importance in everydays cloning (again, e.g. supplier). However, enzyme type is mainly of academic interest. Most of them are type II (cuts at defined position in or close to a defined recognition sequence). The interesting subtypes (IIp = palindromic, IIs =shifted, cuts outside recognition sequence) are not given in the REBASE files.
