### ISSUE TITLE
Pairwise2 reversing character when given list input

### ISSUE THREAD

**Issue by andrewdholmes** [biopython/biopython#1233]
I was trying out pairwise2 list mode, tested by aligning three letter amino acid codes

```
from Bio import pairwise2
from Bio.pairwise2 import format_alignment

firseq = ['Gly','Gly','Leu','Asp','Gly','Glu','Gly','Leu','Asn','Glu','Val']
secseq = ['Val','Und','Glu','Asn','Gly','Asp','Leu','Gly','Glu','Gly','Asp','Leu','Gly','Glu','Gly','Asp','Leu','Gly','Glu','Gly','Asp','Leu','Gly','Glu','Gly','Asp','Leu','Gly']



alignments = pairwise2.align.localmx(firseq, secseq, 2, -1,gap_char = ['---'])
print(format_alignment(*alignments[0]))
```

What that gets is 

```
['---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---', 'y', 'l', 'G', '---', '---', 'y', 'l', 'G', '---', '---', '---', 'u', 'e', 'L', '---', '---', '---', 'p', 's', 'A', '---', 'y', 'l', 'G', 'u', 'l', 'G', 'y', 'l', 'G', '---', 'u', 'e', 'L', 'n', 's', 'A', '---', 'u', 'l', 'G', 'Val', '---', '---', '---']
    |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
['Val', 'Und', 'Glu', 'Asn', 'y', 'l', 'G', 'p', 's', 'A', 'u', 'e', 'L', 'y', 'l', 'G', 'u', 'l', 'G', 'y', 'l', 'G', 'p', 's', 'A', 'u', 'e', 'L', 'y', 'l', 'G', 'u', 'l', 'G', 'y', 'l', 'G', 'p', 's', 'A', 'u', 'e', 'L', 'y', 'l', 'G', 'u', 'l', 'G', 'y', 'l', 'G', 'p', 's', 'A', 'u', 'e', 'L', '---', 'y', 'l', 'G', 'u', 'l', 'G', 'Gly', 'Asp', 'Leu', 'Gly']
  Score=18

```
Where many of the 'characters' are split and reversed

    biopython version: 1.69
    Pyton version: 2.7.12
    OS: CentOS release 6.9

**Comment by MarkusPiotrowski** [comment]
@andrewdholmes Thank's for reporting this. Actually there is a problem with the list input. A similar problem was recently reported on [StackOverflow](https://stackoverflow.com/questions/43299822/how-to-align-lists-of-words-using-biopython-pairwise2/43339322).
Obviously I broke the list input during the last major update of ```pairwise2```. I'm working on it and have already found the problem (and have hopefully fixed it). 
If you want to test the fixed version, I can upload it to my GitHub.

**Comment by peterjc** [comment]
I believe this should be fixed on the master now after #1242 was merged.

**Comment by MarkusPiotrowski** [comment]
@andrewdholmes Do you want to give it a try? The bugfix is merged with the main branch, so you can download ```pairwise2.py``` (e.g. display as raw file and save in a text editor) and replace the 1.69 version for testing.

**Comment by andrewdholmes** [comment]
Oh, sorry, I gave it a try a bit ago and it's working great.  Thanks for
the fix.

Andrew Holmes

**Comment by peterjc** [comment]
Great - thanks for confirming the fix @andrewdholmes, and of course @MarkusPiotrowski for writing it. I'm closing this issue now.

**Comment by mdehoon** [comment]
@andrewdholmes 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
