### ISSUE TITLE
Bio.Phylo.draw_graphviz fail

### ISSUE THREAD

**Issue by wpwupingwp** [biopython/biopython#1247]
Python 3.6
Biopython 1.69
Debian stretch

```
 File "/home/ping/.local/lib/python3.6/site-packages/Bio/Phylo/_utils.py", line 152, in draw_graphviz
    posi = networkx.graphviz_layout(Gi, prog, args=args)
AttributeError: module 'networkx' has no attribute 'graphviz_layout'
```

Google it and someone said that graphviz_layout changed its location in networkx from
`networkx.graphviz_layout`
to
`networkx.drawing.nx_agraph.graphviz_layout`
See http://stackoverflow.com/questions/39411102/attributeerror-module-object-has-no-attribute-graphviz-layout-with-networkx

**Comment by peterjc** [comment]
What version of networkx do you have?

**Comment by wpwupingwp** [comment]
```
pip3 list|grep networkx
networkx                     1.11
```

**Comment by etal** [comment]
I'll see if I can find time to fix and test this.

Actually, I'd like to deprecate this function if there's not too much outcry. It was nice before the `draw` function was in place, but `draw_graphviz` is problematic in many ways (including but not limited to maintenance), and there are other packages better suited to the task now. The best long-term solution would be to implement radial tree plotting, available through either a new function `draw_radial` or another parameter in `draw`.

**Comment by peterjc** [comment]
That seems like a good cause for deprecating the function.

**Comment by etal** [comment]
Shall we add a DeprecationWarning or PendingDeprecationWarning before the upcoming release, then?

**Comment by peterjc** [comment]
I'd go for directly to the ``BiopythonDeprecationWarning`` here - you can ask on the mailing list first if you prefer.

http://biopython.org/wiki/Deprecation_policy

**Comment by rwst** [comment]
BTW I looked around a bit for tree rendering engines with Python API. The most sophisticated at the moment is the ETE toolkit. ETE-3.1.1 requires PyQt5 however, and right now I'm struggling with that installation.
