### ISSUE TITLE
`Bio.PDB.PDBIO.set_structure()` alters parent of chains, residues and atoms

### ISSUE THREAD

**Issue by StefansM** [biopython/biopython#1270]
Calling the `set_structure` method of the `Bio.PDB.PDBIO` class alters the parent of (non-`Structure`) entities in a non-obvious way. For example, this script:
```python
import Bio.PDB
pdbio = Bio.PDB.PDBIO()
parser = Bio.PDB.MMCIFParser()
structure = parser.get_structure("12as", "12as.cif")
for chain in structure[0]:
    old_id = chain.id
    chain.id = " "
    pdbio.set_structure(chain)
    chain.id = old_id
```
Gives this error from line 91 of `Bio/PDB/Entity.py`:
```
ValueError: Cannot change id from `B` to ` `. The id ` ` is already used for a sibling of this entity.
```
Removing the call to `set_structure` acts as I would expect: temporarily renaming the chain name, and then reverting it without problems.

When `set_structure` is called with an `Entity` other than a `Structure` object, it constructs a `Structure` and populates it with the entity using the `add` method, which calls `set_parent` on the entity. To me, this isn't very intuitive: I don't expect writing an object to have side effects that act on that object.

I think a good solution to this would be to call `copy()` in `set_structure` before `add`ing the entity to the new `Structure` object. That is, change `sb.structure.add(pdb_object)` to `sb.structure.add(pdb_object.copy())` in `Bio.PDB.PDBIO.set_structure`. I'm happy to make a pull request if people agree that this is an issue.

**Comment by JoaoRodrigues** [comment]
Indeed. Copying is the better way. I added this 'feature' to allow writing individual bits of Structure object (chains, residues), did not foresee this indeed. Thanks!

If you want to go on with the pull request, I'd be happy to review it.
