### ISSUE TITLE
Bio.KEGG.Enzyme assumes GENES keys are 3 characters

### ISSUE THREAD

**Issue by fsimkovic** [biopython/biopython#1275]
## Problem

    >>> list(Enzyme.parse(open("ec_2.3.1.237.txt")))
    [<Bio.KEGG.Enzyme.Record at 0x7f182a1e2ed0>]
    
    >>> list(Enzyme.parse(open("ec_2.3.1.246.txt")))
    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    <ipython-input-32-3263d682ee05> in <module>()
    ----> 1 list(Enzyme.parse(open("ec_2.3.1.246.txt")))
    
    /home/felix/anaconda/lib/python2.7/site-packages/Bio/KEGG/Enzyme/__init__.py in parse(handle)
        267                 record.genes.append(row)
        268             else:
    --> 269                 row = record.genes[-1]
        270                 key, values = row
        271                 for value in data.split():
    
    IndexError: list index out of range

The problem is caused in `line 263` in file `Bio/KEGG/Enzyme/__init__.py`, which assumes that all `GENES` keys are three characters long.

## Solution

Change line 264 in  `Bio/KEGG/Enzyme/__init__.py`

    262         elif keyword == "GENES       ":
    263             if data[3:5] == ': ':
    264                 key, values = data.split(":", 1)

to the following

    262         elif keyword == "GENES       ":
    263             if data[3:5] == ': ' or data[4:6] == ': ':
    264                 key, values = data.split(":", 1)

This is probably not the optimal solution but fixes the problem for now. 

## Working version

The test case **without** issues:

    >>> records = Enzyme.parse(open("ec_2.3.1.237.txt"))
    >>> record = list(records)[0]
    >>> print(record.genes)
    [('SEN', ['SACE_5532']), ('SAQ', ['Sare_4951']), ('ACTN', ['L083_3191'])]

The test case **with** issues:

    >>> records = Enzyme.parse(open("ec_2.3.1.246.txt"))
    >>> record = list(records)[0]
    >>> print(record.genes)
    [('SMAF', ['D781_2331']), ('XAL', ['XALC_1059']), ('XTN', ['FD63_09790']), ('MNR', ['ACZ75_13535']), ('NBR', ['O3I_032820']), ('SVE', ['SVEN_0493']), ('SRC', ['M271_00240', 'M271_09145']), ('SCW', ['TU94_04905', 'TU94_32245']), ('STRC', ['AA958_31865']), ('SLE', ['sle_03950', 'sle_58620']), ('KFL', ['Kfla_4132']), ('NDA', ['Ndas_1740']), ('FRA', ['Francci3_2458']), ('AOI', ['AORI_1502', 'AORI_5330']), ('AJA', ['AJAP_32005']), ('ALU', ['BB31_20660']), ('MPRO', ['BJP34_31700'])]

**Comment by peterjc** [comment]
Which version of Biopython are you using? You can check with:

```python
>>> import Bio
>>> print(Bio.__version__)
```

This should be fixed by https://github.com/biopython/biopython/commit/ede2ffd52c18daf78857778683c20990e3db99c6 from https://github.com/biopython/biopython/pull/722 which was included in Biopython 1.69

**Comment by fsimkovic** [comment]
Duh ... good spot! 
```python
In [65]: import Bio
In [66]: print(Bio.__version__)
1.66
```

**Comment by peterjc** [comment]
Great - please do let us know if you find any other issues after updating your system. Thanks!

**Comment by fsimkovic** [comment]
Maybe a slightly more future-proof version should be considered.

```python
import re
pattern = re.compile(":\s")
if pattern.search(data):
    key, value = pattern.split(data)
```
