### ISSUE TITLE
why I got a wrong file when using efetch to download a genbank file

### ISSUE THREAD

**Issue by zhqu1148980644** [biopython/biopython#1278]

**Comment by zhqu1148980644** [comment]
from Bio import Entrez
Entrez.email = "A.N.Other@example.com"
net_handle = Entrez.efetch(db="Nucleotide", id="NC_000019", rettype="gb", retmode="text")
out_handle = open("my_file.txt", "w")

for line in net_handle:
    out_handle.write(line)

out_handle.close()
net_handle.close()


result
txt file ends with 
                     /db_xref="taxon:9606"
                     /chromosome="19"
CONTIG      join(gap(10000),gap(50000),NT_011295.12:1..24388980,gap(50000),
            NT_187281.1:1..53672,gap(100),NT_187282.1:1..338504,gap(100),
            NT_187283.1:1..4434,gap(100),NT_187284.1:1..12699,gap(100),
            NT_187285.1:1..2282185,gap(50000),NT_011109.17:1..31366742,
            gap(10000))

no features

**Comment by zhqu1148980644** [comment]
I also tried to read it use SeqIO.read() function
result:
请输入您要下载的基因idNC_000019  
NC_000019.10 Homo sapiens chromosome 19, GRCh38.p7 Primary Assembly 1 [] <class 'list'>
geneNC_000019   has 0genesequence and 0cds  58617616
>>>

**Comment by wpwupingwp** [comment]
From website, it says
`
Due to the size of this record, annotated features are not shown by default.
`
I guess it's because of too large size.

If you really want to get the whole chromosome, you may change 'rettype=gb' to **'rettype=gbwithparts'**, which I not recommend, because I think NCBI FTP is a better choice for such large data.

**Comment by zhqu1148980644** [comment]
thanks

**Comment by zhqu1148980644** [comment]
by the way, how did you get that information,which websit?

**Comment by wpwupingwp** [comment]
The website is NCBI, just query the id.
In NCBI FTP, it is compressed so you could download the data faster.
If you only want this sequence, just use your web browser.
