### ISSUE TITLE
Entrez search returning incorrect results

### ISSUE THREAD

**Issue by abrialmeyer** [biopython/biopython#1282]
Hi! 
My team and I are creating an external database pulling genomic data from genbank using the biopython entrez interface tool. We have hit a problem with our query. When calling from a python script, this search “Squilla empusa”[Organism] AND “18S”[Title] NOT (mito* OR “whole genome”) returns 4 correct results, and 2 results for the 28S gene instead. We think this may be because the 'Title' field for some records (like this one which was incorrectly returned - AY210842) include both the words 18S and 28S, since it is the title of the paper rather than the title of the record. 

When we query genbank directly, with the same search terms, we don't have this issue. 

Does anyone have any idea what's going on? Any advice would help.

Thanks - Abby

**Comment by peterjc** [comment]
Please show the exact Python code you used (or better, a minimal example showing the problem), along with the OS and version of Python and Biopython:

```python
>>> import Bio
>>> print(Bio.__version__)
```

It can be helpful to look at the ``.url`` attribute of the network handle returned by the ``Bio.Entrez`` functions to look at exactly how it was constructed and compare this to the website.

**Comment by abrialmeyer** [comment]
Hi - thank you for your response! 
Sorry about not including all the relevant information, I will make sure to do so in the future. 
We are using Mac OS 10.11.6, Python version 2.7.12 and Biopython version 1.68.

How would be look at the `.url` of the handle? 

Below is the code - it's definitely not a minimal example. We are creating a SQL database as part of an internship project to house genetic and genomic data specific to the projects of a scientist. It is hard to test our code because it is required to run in off peak hours. I am working on testing with a smaller set of data now! 

`def nuclear_genes(email):
	import sqlite3 as sq
	import csv
	import time

	# to run this file, make sure it starts running during GenBank off-peak hours!
	time.sleep(14400)

	from Bio import Entrez, SeqIO
	Entrez.email = email

	conn = sq.connect('decapoda.db')
	c = conn.cursor()
	
	# genes that only have one name
	other_genes = ['18S', '28S']

	for x in c.execute('select species_name from Species_Info'):

		species = x[0]
		
		for name in other_genes:
			handle = Entrez.esearch(db='nucleotide', retmax=1000, term='"'+species+'"[Organism] AND "'+name+'"[Title] NOT (mito* OR "whole genome")')
			record = Entrez.read(handle)
			ids = record['IdList']
			out = open('Nuclear_Fastas/'+name+'.fasta', 'a')
			for i in ids:
				handle = Entrez.efetch(db="nucleotide", id=i, rettype = "gb", retmode= "text")
				record = SeqIO.parse(handle, "genbank")
				try:
					r = next(record)
					paren = r.annotations['source'].find('(')
					gb_species_name = r.annotations['source']
					if paren != -1:
						gb_species_name[:paren]
					if species == gb_species_name.rstrip():
						out.write('>'+species+' '+r.annotations['accessions'][0]+'\n'+str(r.seq)+'\n')
				except ValueError:
					pass
			out.close()

	conn.commit()
	conn.close()

nuclear_genes('gmarkov17@gmail.com')`

Thank you - Abby

**Comment by peterjc** [comment]
I would suggest adding this for logging purposes:

```python
handle = Entrez.esearch(db='nucleotide', retmax=1000, ...)
print(handle.url)
```

Just in case it makes a difference, it would also be worth trying to upgrade to Biopython 1.69 (the current latest release) before going any further.

**Comment by peterjc** [comment]
Closing issue due to lack of information.
