### ISSUE TITLE
Building compiled wheels for PyPI (Linux, Mac, Windows)

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1296]
After Biopython 1.70 is out (which with the move from ``distutils`` to ``setuptools`` already makes enough changes to our installation to make me nervous, see #1293), we should look at how to compile/build suitably portable Linux/Mac/Windows binaries as wheel files for upload to PyPI.

This will likely be heavily guided by how NumPy does it - in part as we need to be binary compatible with theirs.

Traditionally we have not offered 64-bit Windows installers because there we no official 64-bit NumPy installers. However, according to https://pypi.python.org/pypi/numpy/1.11.0 they have had 64-bit Windows wheels since NumPy 1.11.0, so we should be able to do this with wheels.

The hope would be ``pip install biopython --only-binary=biopython`` would work on any platform, or to put it another way ``pip install biopython`` will just work and not need a compiler (e.g. default Windows and Mac setups).

**Comment by peterjc** [comment]
Note we've been running ``python setup.py bdist_wheel`` as a TravisCI test check for a while now, but not doing anything with the output.

**Comment by souravsingh** [comment]
We can make use of the manylinux to build wheels for Linux- https://github.com/pypa/manylinux

For Mac, I think there is MacPython.

**Comment by peterjc** [comment]
Thanks for the ``manylinux`` link - yes, their Docker image seems like the official best practise for the Linux wheels.

Mac is harder as you have Apple Python vs Python.org Python to consider.

**Comment by taleinat** [comment]
@peterjc I can't see `python setup.py bdist_wheel` being run on AppVeyor yet, though.

**Comment by peterjc** [comment]
True, but AppVeyor runs everything in serial so already takes rather a long time to finish on pull requests etc.

I'm thinking baby steps for Biopython 1.70 (which has now shifted to using setuptools internally, see #1293) and trying building self-compiled wheels for Windows and uploading them to PyPI

**Comment by peterjc** [comment]
Here is how NumPy etc does their wheels:

https://github.com/MacPython/numpy-wheels

Background to the setup:

https://github.com/MacPython/wiki/wiki

https://github.com/matthew-brett/multibuild

**Comment by souravsingh** [comment]
@peterjc This projet could also be interesting- https://github.com/joerick/cibuildwheel

**Comment by peterjc** [comment]
That looks good too @souravsingh - but I think given NumPy is our major compile time dependency, joining the wider NumPy community's approach is worth trying first: http://mailman.open-bio.org/pipermail/biopython-dev/2017-July/021809.html

**Comment by peterjc** [comment]
This is in progress using the NumPy eco-system's approach (Mathhew Brett's multibuild):

https://github.com/biopython/biopython-wheels

**Comment by peterjc** [comment]
This worked, and the Biopython 1.70 wheels went up on PyPI some time back. Belated closing issue.

**Comment by peterjc** [comment]
Looks like I commented only, rather than closing this last year. Trying again...
