### ISSUE TITLE
Make _DistanceMatrix non-private

### ISSUE THREAD

**Issue by DamianSkrzypczak** [biopython/biopython#1304]
I belive that TreeConstruction/_DistanceMatrix could and should be public. 
Personally i had this issue when I tried make tree from my own distance matrix... 

Of course this is compatibility-breaking but there can always be some hook like simple var named _DistanceMatrix or subclass with deprecation warning

If there is any reason for _DistanceMatrix to keep underscore, please share it :D 
Maybe Im wrong and it's just my point of view.

**Comment by peterjc** [comment]
I have few worries about breaking backward compatibility of private methods (unless we have reason to believe the are widely used).

CC @lijax and @etal

**Comment by DamianSkrzypczak** [comment]
But can't this be done by adding some placeholder _DistanceMatrix = DistanceMatrix
and renaming private class into public one? This is easiest way.

Or maybe extending library by DistanceMatrix class which will inherent from _DistanceMatrix?
Just to show that this can be used by user, IMO because it should be provided to users .

**Comment by peterjc** [comment]
Sure, if you really wanted to preserve ``_DistanceMatrix`` as a backward compatible alias something like that should work. From my perspective it seems unnecessary here, but I neither wrote nor have used this part of Biopython and am leaving this to @lijax and @etal.

**Comment by etal** [comment]
I see no problem with making it public. Might as well use the _DistanceMatrix = DistanceMatrix placeholder, since the reason we're interested in making it public is that people have been using it directly.

**Comment by DamianSkrzypczak** [comment]
I suggest to create subclass of _DistanceMatrix and make some more comfortable methods, like for example constructor that can get normal matrix and cut it into lower triangular.

**Comment by peterjc** [comment]
Given we're happy to make it public as ``DistanceMatrix``, there is no reason to keep two different classes in the code - the alias seems a better plan than a subclass.

A pull request to further enhance the ``DistanceMatrix`` seems like a good idea.

**Comment by peterjc** [comment]
And the PEP8 check fixed in d080655fce8bc5987e4ff653f16c58d3dcd09c9d
