### ISSUE TITLE
error parsing cif files

### ISSUE THREAD

**Issue by aj26git** [biopython/biopython#1325]
Reading the pdb file 5uyk.cif fails with the log:

```
  File "/usr/lib/python2.7/dist-packages/Bio/PDB/MMCIFParser.py", line 61, in get_structure
    self._build_structure(structure_id)
  File "/usr/lib/python2.7/dist-packages/Bio/PDB/MMCIFParser.py", line 179, in _build_structure
    name, element=element)
  File "/usr/lib/python2.7/dist-packages/Bio/PDB/StructureBuilder.py", line 241, in init_atom
    residue.add(self.atom)
  File "/usr/lib/python2.7/dist-packages/Bio/PDB/Residue.py", line 80, in add
    "Atom %s defined twice in residue %s" % (atom_id, self))
Bio.PDB.PDBExceptions.PDBConstructionException: Atom P defined twice in residue <Residue C het=  resseq=17 icode= >
```

(*Peter: Updated to use triple-back-tick markup for the exception)

**Comment by peterjc** [comment]
Which version of Biopython are you using?

Does the equivalent PDB file work?

**Comment by jgreener64** [comment]
This appears to read in without an error using the Biopython master branch.

**Comment by aj26git** [comment]
Thanks for looking into this. Sorry for the delay. We are using biopython v 1.66, seems to fail for the associated pdb files as well..

**Comment by aj26git** [comment]
It worked with v 1.7. Many thanks.

**Comment by peterjc** [comment]
Thanks for checking with our current release (Biopython 1.70), good to hear this has been fixed already :)
