### ISSUE TITLE
Biopython structural integration with nglview

### ISSUE THREAD

**Issue by jgreener64** [biopython/biopython#1331]
Not sure if an issue is the best place for this, but just making people aware that I am working on a small addition to the cool nglview package to allow viewing of Biopython structural entities in Jupyter notebooks:

<img width="738" alt="screen shot 2017-07-20 at 17 00 33" src="https://user-images.githubusercontent.com/6620652/28428450-b7da9684-6d79-11e7-8e37-2cd60e082a29.png">

**Comment by peterjc** [comment]
That looks very nice. There has been talk of converting material to notebooks, but for now maybe add it to http://biopython.org/wiki/The_Biopython_Structural_Bioinformatics_FAQ ?

(It used to be a wiki, it is now written in Markdown using GitHub pages - there should be an edit link top right via GitHub)

**Comment by jgreener64** [comment]
Okay thanks, will wait for it to get sorted and released as part of nglview first.

**Comment by jgreener64** [comment]
This is now in a release of nglview, so I have made a PR to edit the wiki: https://github.com/biopython/biopython.github.io/pull/122.
