### ISSUE TITLE
QuantifiedCode is shutting down

### ISSUE THREAD

**Issue by souravsingh** [biopython/biopython#1338]
As mentioned in the blog post here- https://www.quantifiedcode.com/blog/quantifiedcode-shutdown, QuantifiedCode will shut down from July 22 onwards. 

For alternatives to QuantifiedCode, We can make use of [Scrutinizer](https://scrutinizer-ci.com/) or [Codacy](https://www.codacy.com/)

**Comment by peterjc** [comment]
It looks like QuantifiedCode is still alive (for now), but the 22 July deadline has passed.

https://scrutinizer-ci.com/pricing says *"What about open-source repositories? We do not charge for open-source repositories, you can add as many as you like."*

https://www.codacy.com/pricing is even clearer *"Open Source: Free"*

**Comment by peterjc** [comment]
Here are two non-trivial example Python projects using these tools:

* https://www.codacy.com/app/Weblate/weblate/issues
* https://scrutinizer-ci.com/g/pyload/pyload/issues

**Comment by souravsingh** [comment]
QuantifiedCode has now shut down officially(The link shows a 404). They point to a repository for hosting QuantifiedCode for your own project- https://github.com/quantifiedcode/quantifiedcode

**Comment by peterjc** [comment]
Is there anything left in our documentation which mentions QuantifiedCode? I've run a basic grep to check, and don't see anything other than a simple comment in one test to silence an unused variable warning:

```
$ grep -i quantified Tests/*.py
Tests/test_pairwise2.py:            x = 0  # fool QuantifiedCode, x is not used here
Tests/test_pairwise2.py:            x = 0  # fool QuantifiedCode, x is not used here
```
