### ISSUE TITLE
getting "AttributeError: 'NoneType' object has no attribute 'readline'" when reading Bio.SCOP.search()

### ISSUE THREAD

**Issue by jhutar** [biopython/biopython#1343]
I'm most probably using this incorrectly, but have not found much info on how to use it. Also this might be clearly issue on a server. Anyway, could somebody knowledgeable check these steps?

```
$ python
Python 2.7.13 (default, Jun 26 2017, 10:20:05) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio.SCOP
>>> aaa = Bio.SCOP.search(pdb='1TQN')
>>> bbb = aaa.info()
>>> bbb.readheaders()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/httplib.py", line 316, in readheaders
    line = self.fp.readline(_MAXLINE + 1)
AttributeError: 'NoneType' object has no attribute 'readline'
```

I'm using python2-biopython-1.68-3.fc26.x86_64 and python2-2.7.13-11.fc26.x86_64.

**Comment by peterjc** [comment]
The ``Bio.SCOP.search`` function returns a network handle, which seems to default to HTML which is probably not ideal. e.g.

```pycon
>>> from Bio import SCOP
>>> handle = SCOP.search(pdb='1TQN')
>>> print(handle.info())
Date: Thu, 27 Jul 2017 16:54:25 GMT
Server: Apache/2.2.15 (Scientific Linux)
Last-Modified: Wed, 03 Jun 2009 17:53:01 GMT
ETag: "64eaf-2f47-46b7554915940"
Accept-Ranges: bytes
Content-Length: 12103
Connection: close
Content-Type: text/html; charset=UTF-8
>>> print(handle.read())
<html><head><title>SCOP: Protein: Mammalian cytochrome P450 3a4 from Human (Homo sapiens) <a href="http://www.ncbi.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9606&lvl=0" class="taxid">[TaxId: 9606]</a></title></head>
<body bgcolor=silver>
...
```

Note that the handle's ``.info()`` returns an ``httplib.HTTPMessage`` instance, which is not something Biopython provides.

What are you trying to do here?

**Comment by jhutar** [comment]
Sorry for not responding earlier. Thank you for explaining the usage. I wanted to map <protein>-<chain> to superfamily. But I admit I might be using incorrect tool. For now I'm using CATH's data files. I do not know what server part can do - would it be possible to return some structured data instead of HTML?

**Comment by peterjc** [comment]
I think it might be worth asking on the Biopython mailing list - http://biopython.org/wiki/Mailing_lists - I am not familiar with SCOP or CATH personally.
