### ISSUE TITLE
SeqIO.index fails on empty ACCESSION lines in GenBank

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#1344]
When running `SeqIO.index` on a GenBank file that has an `ACCESSION` line without any content, `SeqIO.index` crashes with an `IndexError` like this:

```
Traceback (most recent call last):
  File "./check.py", line 6, in <module>
    rec = SeqIO.index(sys.argv[1], 'genbank')
  File "/home/kai/dev/libs/biopython/Bio/SeqIO/__init__.py", line 885, in index
    key_function, repr, "SeqRecord")
  File "/home/kai/dev/libs/biopython/Bio/File.py", line 294, in __init__
    for key, offset, length in offset_iter:
  File "/home/kai/dev/libs/biopython/Bio/SeqIO/_index.py", line 268, in __iter__
    key = line.rstrip().split()[1]
IndexError: list index out of range
```

The regular GenBank parser is handling these files just fine, it functionally reacts like there was no `ACCESSION` line.

**Comment by kblin** [comment]
Unfortunately, it looks like `SeqIO.index` is very insistent on not using the ID available in the `LOCUS` line, so the behaviour here differs. I'm a bit at a loss on how to fix this properly.
That said, we should at least trigger the same `ValueError` the code throws if there is no `ACCESSION` or `VERSION` line.

**Comment by peterjc** [comment]
It probably does not matter given the ``.rstrip()`` but can you share an example - is it just ``ACCESSION\n`` in these cases, or might there be trailing whitespace?

**Comment by peterjc** [comment]
Do your files have a ``VERSION`` line which would be used in preference to the (blank) ``ACCESSION`` line?

If neither is missing then from memory the parser would use the ``LOCUS`` line - but the indexer does not have that implemented.

**Comment by kblin** [comment]
In this particular case, the file has trailing whitespace, and no `VERSION` line. Let me reproduce with a similar file I can share.

**Comment by kblin** [comment]
This one has the same issue:
[empty_accession.gbk.txt](https://github.com/biopython/biopython/files/1180176/empty_accession.gbk.txt)

**Comment by peterjc** [comment]
Short term "fix" would be:

```
$ git diff
diff --git a/Bio/SeqIO/_index.py b/Bio/SeqIO/_index.py
index 952b4856f..6a1b2fdd5 100644
--- a/Bio/SeqIO/_index.py
+++ b/Bio/SeqIO/_index.py
@@ -265,7 +265,11 @@ class GenBankRandomAccess(SequentialSeqFileRandomAccess):
                     start_offset = end_offset
                     break
                 elif line.startswith(accession_marker):
-                    key = line.rstrip().split()[1]
+                    try:
+                        key = line.rstrip().split()[1]
+                    except ValueError:
+                        # Missing any accession
+                        pass
                 elif line.startswith(version_marker):
                     version_id = line.rstrip().split()[1]
                     if version_id.count(b".") == 1 and version_id.split(b".")[1].isdigit():
```

That should at least trigger ValueError ``Did not find ACCESSION/VERSION lines`` although there would actually be an incomplete ACCESSION line.

**Comment by peterjc** [comment]
The real fix is to implement the exact same ``LOCUS`` line fall back implemented by the GenBank parser.

(Given a clean slate for efficient indexing I would have used the ``LOCUS`` line entry as the record's ``.id`` but that was not what the parser did when I came to write the indexing)

**Comment by kblin** [comment]
You need to catch an `IndexError`, not a `ValueError`, though.

**Comment by kblin** [comment]
I'd have submitted a patch in that direction already, but I can't figure out where to put the unit test for that. I am confused by `test_SeqIO_index.py`.

**Comment by kblin** [comment]
That said, so far I relied on having another part of my code sanity checking the GenBank file via `parse()` prior to indexing it where this blew up, and I guess I need more defense in depth anyway.

**Comment by peterjc** [comment]
Good point on the exception, how about:

```
$ git diff
diff --git a/Bio/SeqIO/_index.py b/Bio/SeqIO/_index.py
index 952b4856f..7de4e5063 100644
--- a/Bio/SeqIO/_index.py
+++ b/Bio/SeqIO/_index.py
@@ -260,12 +260,16 @@ class GenBankRandomAccess(SequentialSeqFileRandomAccess):
                 if marker_re.match(line) or not line:
                     if not key:
                         raise ValueError(
-                            "Did not find ACCESSION/VERSION lines")
+                            "Did not find usable ACCESSION/VERSION lines")
                     yield _bytes_to_string(key), start_offset, length
                     start_offset = end_offset
                     break
                 elif line.startswith(accession_marker):
-                    key = line.rstrip().split()[1]
+                    try:
+                        key = line.rstrip().split()[1]
+                    except ValueError:
+                        # Missing any accession
+                        pass
                 elif line.startswith(version_marker):
                     version_id = line.rstrip().split()[1]
                     if version_id.count(b".") == 1 and version_id.split(b".")[1].isdigit():
```

Regarding ``test_SeqIO_index.py`` the first half is fairly traditional unittests (some wrapped for use when SQLite3 is missing), then there is a list for files and formats from which tests are generated dynamically.

Simple option add your new pathological GenBank file to this list:
https://github.com/biopython/biopython/blob/biopython-170/Tests/test_SeqIO_index.py#L611

**Comment by kblin** [comment]
How do I tell that test that I expect a ValueError then?

**Comment by peterjc** [comment]
Umm. Good point, I hadn't thought that though. Those main tests are for working files.

Right now it would have be a special case test method, something like:

```python
class Problems(unitest.TestCase):
    def test_genbank_no_acc_ver(self):
        filename = "..."
        self.assertRaises(ValueError, SeqIO.index, filename, "gb")
```

It would be better to fix the indexer for this case, which I guess is something for me to tackle if I can find a quite moment.

**Comment by peterjc** [comment]
Thanks for #1346 - clear exceptions here is a worthwhile step forward.
