### ISSUE TITLE
MMTF parser errors

### ISSUE THREAD

**Issue by jgreener64** [biopython/biopython#1345]
I tested the MMTF parser on the whole PDB and got 6 files that errored before the `PDBConstructionException` (i.e. controlled failure) stage.

I think this is an issue with the mmtf package and have raised it there: https://github.com/rcsb/mmtf-python/issues/28.

**Comment by peterjc** [comment]
Thanks - @abradle did the Biopython mapping on top of the ``mmtf`` package, so is there perfect person to look into this.

**Comment by abradle** [comment]
I'm gonna close this - because the underlying data issue is being investigated by https://github.com/biojava/biojava/issues/696 as seen in https://github.com/rcsb/mmtf-python/issues/28

**Comment by peterjc** [comment]
Thanks @abradle for those links. I'm OK with closing this Biopython issue since it sounds like the underlying data in those files is going to be curated and the MMTF files fixed.
