### ISSUE TITLE
Default `codon_table` for codonalign.CodonSeq should be `self.alphabet`

### ISSUE THREAD

**Issue by conchoecia** [biopython/biopython#1353]
Hi All,

I noticed something weird about the `codonalign.CodonSeq` object's `.translate()` function -- It uses the `default_codon_table` even if self.alphabet is something different, like mold an protozoan mitochondrial alphabet. To me it would make more sense if `codon_table=self.alphabet` instead of `codon_table=default_codon_table`. What do you all think?

``` 
def translate(self, codon_table=default_codon_table,
                  stop_symbol="*", rf_table=None, ungap_seq=True):
```

**Comment by conchoecia** [comment]
I also just noticed that there is documentation at [biopython/blob/master/Doc/doc.rst](biopython/blob/master/Doc/doc.rst) that states incorrectly how the `translate` function works.

> As you might imagine, CodonSeq is able to be translated into amino acid sequence based on the CodonAlphabet within it. In fact, CodonSeq does more than this.

**Comment by peterjc** [comment]
What do you think @zruan? 

P.S. This is slightly related to #1160

**Comment by zruan** [comment]
This is indeed very confusing and the document is not correct. But the `codon_alphabet` is different from `codon_table`. `codon_alphabet` only saves the possible three letter codons of the CodonSeq, but `codon_table` contains the mapping from codon to amino acid. Perhaps I can add the `self.codon_table` attribute to CodonSeq so that we can then translate from it?

**Comment by conchoecia** [comment]
Adding `self.codon_table` seems like a good option since there is information intrinsically linked in the `codon_table` that is useful to a `CodonSeq` object. I'd be interesting in contributing but will defer to you both since I'm very new to this module!

**Comment by peterjc** [comment]
The method definition is now:

```python
    def translate(
        self, codon_table=None, stop_symbol="*", rf_table=None, ungap_seq=True
    ):
        # ...
        if codon_table is None:
            codon_table = CodonTable.generic_by_id[1]
        # ...
        if rf_table is None:
            rf_table = self.rf_table
```

I am unclear if the original issue remains, or if we can close this?

**Comment by zruan** [comment]
Yes, I think this is no longer an issue now since we dropped the alphabet class.

**Comment by peterjc** [comment]
Closing, thank you.
