### ISSUE TITLE
Adding style test for Python 3 to Travis

### ISSUE THREAD

**Issue by junaruga** [biopython/biopython#1354]
Right now the style test is running for only default Python (2.7). Not for Python 3.

When I tried to run it on local for both Python 2.7 and 3.6.
3.6 was failed.

So, I want to add the style test on Python 3.6 in Travis CI.
Is it possible?
Because I am basically developing on Python 3.6.

```
$ /usr/local/python-2.7.13/bin/tox --version
2.7.0 imported from /usr/local/python-2.7.13/lib/python2.7/site-packages/tox/__init__.pyc
```

```
$ /usr/local/python-3.6.1/bin/tox --version
2.7.0 imported from /usr/local/python-3.6.1/lib/python3.6/site-packages/tox/__init__.py
```

```
$ /usr/local/python-2.7.13/bin/tox -c .travis-tox.ini -e style
...
  congratulations :)
```

```
$ /usr/local/python-3.6.1/bin/tox -c .travis-tox.ini -e style
Bio/PDB/Residue.py:55:20: F821 undefined name 'cmp'
Bio/PDB/Residue.py:65:20: F821 undefined name 'cmp'
Bio/PDB/Residue.py:70:16: F821 undefined name 'cmp'
Bio/PDB/Chain.py:35:20: F821 undefined name 'cmp'
Bio/PDB/Chain.py:37:20: F821 undefined name 'cmp'
Bio/PDB/Chain.py:38:16: F821 undefined name 'cmp'
Bio/PDB/Structure.py:36:16: F821 undefined name 'cmp'
Bio/PDB/Model.py:54:16: F821 undefined name 'cmp'
ERROR: InvocationError: '/usr/local/python-3.6.1/bin/flake8 Bio/'
```

**Comment by peterjc** [comment]
Good idea - This has just been solved by #1291 which by chance I was looking at again this afternoon (and just merged now, since the rebased branch tests passed while I had dinner).

(I should perhaps have logged an issue on the style checking aspect, rather than just a mental to do list)

**Comment by junaruga** [comment]
Oh that is coincidence. Thanks!

**Comment by junaruga** [comment]
I am fine for your mental todo list :)
