### ISSUE TITLE
mmCIF parsing failures due to line splitting

### ISSUE THREAD

**Issue by jgreener64** [biopython/biopython#1357]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

2.7.11 (default, Jun  1 2016, 15:51:35)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
CPython
Darwin-14.5.0-x86_64-i386-64bit
1.71.dev0

### Expected behaviour

Parsing mmCIF files 1mom, 1n5m, 1tsl, 1y59, 2a9w, 3b3p and 3dqt should work.

### Actual behaviour

These 7 files fail due to the way `shlex` parses quotes. `shlex.split("foo 'ba'ar' foo")` throws an error as the quote character in the middle is read as a close quote. The CIF syntax actually allows this (https://www.iucr.org/resources/cif/spec/version1.1/cifsyntax) and it occurs in places such as line 112 of 1n5m.cif:

```
6 non-polymer syn '2,2',2"-[1,2,3-BENZENE-TRIYLTRIS(OXY)]TRIS[N,N,N-TRIETHYLETHANAMINIUM]' 510.816   1   ?       ? ? ?
```

### Steps to reproduce

```python
from Bio.PDB.MMCIF2Dict import MMCIF2Dict
d = MMCIF2Dict("1n5m.cif")
```

I played around with the `shlex` whitespace options but could not immediately fix this issue. Instead I will make another PR shortly which proposes to replace `shlex` entirely.

**Comment by peterjc** [comment]
That's an interesting corner case - good job on tracking this down and coming up with a fix 👍
