### ISSUE TITLE
Meme parser fails on any version of meme above 4.11.4 (newest is currently 4.12.0)

### ISSUE THREAD

**Issue by hwalinga** [biopython/biopython#1372]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
CPython
Linux-3.19.0-32-generic-x86_64-with-debian-jessie-sid
1.70

### Expected behaviour

I expect Biopython's meme parser to run with the newest version of meme. In my case 4.12.0. 

### Actual behaviour

Biopython's meme parser will now always fail with any newer version of meme. 

### Steps to reproduce

Try to parse a meme.txt with the newest version of meme (version 4.12.0). (Altering the version number to 4.12.0 of a meme.txt produced by version 4.11.4 will likely produce the same results.)

meme.txt I used: https://pastebin.com/V2Mg2Kxi

Full Exception can be found here: https://pastebin.com/ntQsLhBJ (somehow the exception is not correctly displayed, because obviously `revcomp = 'revcomp' in record.command` did not raise the 'Unexpected end of stream'.

### Actual problem 

To add support for version 4.11.4 a check for `record.version == '4.11.4'` in line 36 of meme.py is inserted. Versions above 4.11.4 will therefore not be parsed, even if they would be parsed correctly if it had a different version number. 

### Proposed solution

I don't know if it is by design to let the program not parse output of newer versions to force a review of the code every time a newer version is issued. I would however at least continue the parsing with a warning. 

To check versions of 4.11.4 and above you can use:
```python
from distutils.version import StrictVersion
if StricVersion('4.11.4') <= StrictVersion(record.version) and ... 
```

**Comment by peterjc** [comment]
CC @aralap who worked on this on pull request #1266.

I tried tweaking this line of the code which checks for ``4.11.4`` but the parser still failed...

**Comment by aralap** [comment]
Will look into it.

**Comment by hwalinga** [comment]
@peterjc did you tried to change the file directly from the module? Because I did that as well first, but somehow the changes I make there were not applied. (I tested this with a print statement.)  (It did, however, alter the line which is shown in the error traceback.) I don't know the exact details of the working of pythons internals, but I thought it might be something similar to pycache. 
Maybe you have something similar. 
Anyway, I copied the code of the file into my working directory and from there I could confirm that that line of code was the culprit. 
Thanks for the quick response by the way.

**Comment by hwalinga** [comment]
@aralap I see that you already created change. However, I think it would still be better to raise a different exception than 'ValueError: unexpected end of stream' when a file from a not yet supported version of meme is parsed. What about something like this:
```python
from distutils.version import StrictVersion
...
supported = ['4.11.4', '4.12.0']
...
for line in handel:
    if line.startswith('MOTIF  1'):
        break
    if record.version in supported and line.startswith('MOTIF')
        break
    if StrictVersion(record.version) > StrictVersion(supported[-1]
        raise ValueError('Parser not yet supporting version %s' % record.version)
else:
    raise ValueError('Unexpected end of stream')

**Comment by aralap** [comment]
@hwalinga It's probably good to raise a different exception, but i dont know about importing StrictVersion.
Do you think something like this would work :

`def version_to_tuple(version):
    return tuple(map(int, (version.split("."))))
...
if  version_to_tuple(record.version) > version_to_tuple(supported[-1]):
        raise ValueError('Parser not yet supporting version %s' % record.version)
`

**Comment by hwalinga** [comment]
@aralap I took a closer look and using StrictVersion would be a mistake. Meme has also had version numbers on which it attached an underscore to its version number, for example 4.11.4_1 and then StrictVersion will fail. (You can take a look here for all previous versions http://meme-suite.org/doc/download.html?man_type=web)

But your function needs some adjustments as well then. Another thing that for example might be a problem is that version number might have an attachment with a word, like beta, so that int conversion fails. Luckily int conversion is not required at all, also tuple conversion is not required. 
So this might be better:
```python
def version_to_list(version)
    import re
    return re.split('\.|_', version)
```
I don't think it really matters if it will fail if the version format changes, it will then be unsupported anyway.

**Comment by aralap** [comment]
@hwalinga From what i see here in [MEME versions.](http://meme-suite.org/doc/download.html?man_type=web)
It seems as the version number has always been "x.x.x" format. There arent so many versions, so maybe just listing them like this could work to get the "Version not supported" exception. (Is not elegant, but will be easy to add future versions, even if the format changes)
```Python
supported = ["4.12.0","4.11.4","4.11.3","4.11.2","4.11.1","4.11.0","4.10.2","4.10.1","4.10.0","4.9.1","4.9.0","4.8.1",
"4.8.0","4.7.0","4.6.1","4.6.0","4.5.0","4.4.0","4.3.0","4.2.0","4.1.1","4.1.0","4.0.0","3.5.7","3.5.4","3.5.3"
,"3.5.2","3.5.1","3.5.0","3.0.14","3.0.13","3.0.10","3.0.9","3.0.8","3.0.6","3.0.5","3.0.4","3.0.3","3.0.2",
"2.3.0","2.2.2","2.2.1","2.2.0","2.1.0","2.0.0","1.4.3","1.4.0","1.3.0","1.2.0"]

**Comment by peterjc** [comment]
I think comparing the version as a tuple-of-ints is a good approach, as that has a well defined order for the comparison. Having a hard coded list of supported versions seems very fragile and will keep breaking on new releases.

Does the code actually work if you remove the version check completely? Is that an acceptable solution? Normally we'd only have a version check if there was a major change to the file format and we needed a large if-statement or similar.

**Comment by aralap** [comment]
It could work without a version check. I tested the change below on version 4.9.0, 4.11.4 and 4.12.0 and worked.  
```Python 
...
 record = Record()
    __read_version(record, handle)
    __read_datafile(record, handle)
    __read_alphabet(record, handle)
    __read_sequences(record, handle)
    __read_command(record, handle)
    for line in handle:
        if line.startswith('MOTIF '):
            break
    else:
        raise ValueError('Unexpected end of stream')
...

**Comment by peterjc** [comment]
Great - I see you've proposed that as pull request #1374 which I have now merged. Thank you both, this will be included in Biopython 1.71.

@hwalinga are you able to try installing Biopython from git, or making this change locally?

**Comment by hwalinga** [comment]
Certainly great. 

I use a locally changed file now. 

Nitpicking: comment on line 223 is now slightly off, since it still states to be applicable only for version 4.11.4

**Comment by aralap** [comment]
The comment is this :
```Python
def __read_motif_statistics(line):
    # Depending on the version of MEME, this line either like like
    #    MOTIF  1        width =  19  sites =   3  llr = 43  E-value = 6.9e-002
    # or like
    #    MOTIF  1 MEME    width =  19  sites =   3  llr = 43  E-value = 6.9e-002
    # or in v 4.11.4 onwards
    #    MOTIF ATTATAAAAAAA MEME-1	width =  12  sites =   5  llr = 43  E-value = 1.9e-003
    words = line.split()
    assert words[0] == 'MOTIF'
```
It's still applicable to version 4.12.0 as the line format they use is of the form:
```Python
# MOTIF TAAGAAATAAG MEME-1	width =  11  sites =   8  llr = 93  E-value = 4.4e-004
```
What do you think @hwalinga,  maybe changing the "onwards" for something else ? erasing the comment ?

**Comment by peterjc** [comment]
But version 4.12.0 is after 4.11.4, so isn't this fine as written?

**Comment by hwalinga** [comment]
@aralap Are you aware that 'onwards' was added by @peterjc after I commented that the comment was wrong?

It's now fine as it is written, because it is no longer a wrong comment. 'Onwards' also covers the situation correctly. However I think it is not yet a perfect comment. In my opinion it can be improved.

English is not my first language, but I suspect the first sentence of the comment is grammatically wrong. Two times like, no verb. 

Next to that it is slightly inconsistent. It states three different ways that the statistics line occurs, but only the last one is accompanied with a version number. Since the whole file does not (any more) check the version anywhere, stating version numbers in the comment is unnecessary information. I think you shouldn't include unnecessary information in a comment. 

Therefore in my opinion the comment can be improved to this:
```python
...
def __read_motif_statistics(line):
    # Depending on the version of MEME, this line is either like
    #    MOTIF  1        width =  19  sites =   3  llr = 43  E-value = 6.9e-002
    # or like
    #    MOTIF  1 MEME    width =  19  sites =   3  llr = 43  E-value = 6.9e-002
    # or like
    #    MOTIF ATTATAAAAAAA MEME-1	width =  12  sites =   5  llr = 43  E-value = 1.9e-003
    words = line.split()
...
```

**Comment by peterjc** [comment]
The version information is very useful for anyone trying to work on the parser - if you know more about when the first change happened let's add that.

**Comment by hwalinga** [comment]
I don't know, luckily github knows. Maybe include these links as well then:
Old version: https://github.com/aralap/biopython/blob/ec665e0010ad47b411740c1a50ff0a2c6dd9d25d/Tests/motifs/meme.out
First change first appeared in version 4.10.0 according to https://github.com/biopython/biopython/issues/461 :
https://gist.github.com/mgalardini/78cc9d918d3af6cccf22
Second change first appeared in version 4.11.4:
https://github.com/aralap/biopython/blob/ec665e0010ad47b411740c1a50ff0a2c6dd9d25d/Tests/motifs/meme_v_4_11_4.out

**Comment by hwalinga** [comment]
@peterjc and @aralap 
Can we include this information. And also maybe include  https://gist.github.com/mgalardini/78cc9d918d3af6cccf22 in a test case. This is version 4.10.0 through 4.11.4.

**Comment by peterjc** [comment]
That sounds sensible, please submit a pull request.
