### ISSUE TITLE
Cavener rules for exactly 50 % frequency in motifs

### ISSUE THREAD

**Issue by hwalinga** [biopython/biopython#1373]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
CPython
Linux-3.19.0-32-generic-x86_64-with-debian-jessie-sid
1.70

### Expected behaviour

I expect that when the frequency is exactly 50 %, the nucleotide will not be accepted as the consensus nucleotide. 

The Cavener rules stated in the article itselfs is the following:
*If the frequency of a single nucleotide at a specific position is greater than 50% and greater than twice the number of the second most frequent nucleotide it is assigned as the consensus nucleotide.*
**Cavener, Nucleic Acids Res. 15:1353-1361, 1987**

(So only when it is greater than.)

### Actual behaviour

Now when a frequency is equal to 50 percent it will accepted as the consensus nucleotide.

### Steps to reproduce

```python
from Bio import motifs
from Bio.Seq import Seq

instances = [Seq("A"), Seq("A"), Seq("G"), Seq("T")]
m = motifs.create(instances)
print(m.degenerate_consensus)
```

*prints A instead of the expected N*

### Context

I am using meme to find motifs and meme also shows you the ambiguous sequence of the motif it found. I discovered this was different from the output Biopython gave me. 

### Proposed solution

Remove the equal sings from line 234 from Bio.motifs.matrix.py

**Comment by peterjc** [comment]
@mdehoon and/or @barwil - could you look at this please?

**Comment by mdehoon** [comment]
Fixed, thanks!

**Comment by peterjc** [comment]
I see d25d8cb72e38557388e3efd769b737a4c17a8ed2 fixed this but a tutorial example needs updating:

https://travis-ci.org/biopython/biopython/builds/267847525

eg

```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biopython/biopython/Tests/test_Tutorial.py", line 256, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 1 Tutorial doctests failed: test_chapter_motifs_line_00028
----------------------------------------------------------------------
```

https://ci.appveyor.com/project/biopython/biopython/build/0.0.284

```
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\biopython\Tests\test_Tutorial.py", line 256, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 1 Tutorial doctests failed: test_chapter_motifs_line_00028
----------------------------------------------------------------------
```
