### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by smsaladi** [biopython/biopython#1377]
The [docs for Bio.Alphabet.Reduced](http://biopython.org/DIST/docs/api/Bio.Alphabet.Reduced-pysrc.html) suggest looking at the following website for examples of reduced alphabets:

http://viscose.ifg.uni-muenster.de/html/alphabets.html 

but isn't available anymore. The Wayback Machine's last working crawl is from 2007:

https://web.archive.org/web/20070303172013/http://viscose.ifg.uni-muenster.de/html/alphabets.html

I suggest updating the link in the docs to something that resolves properly. Some searching on my part doesn't find a currently hosted version of that page. I'm suggest linking to the old page through the wayback machine or, alternatively, putting citations for the papers on that page in the docs (but this seems considerably less helpful).

I can make a PR based on the discussion.  @idoerg , as the original author, other ideas?

**Comment by peterjc** [comment]
Using the archive.org URL sounds like an improvement, unless @idoerg can thing of a better page. I've never needed to use reduced alphabets some am unsure what to suggest.

**Comment by MarkusPiotrowski** [comment]
This has been solved in #1479, I found a valide and working version here: http://viscose.herokuapp.com/html/alphabets.html. So I'm closing this now.
