### ISSUE TITLE
ImportError: cannot import name Alphabet

### ISSUE THREAD

**Issue by rraadd88** [biopython/biopython#1396]
This error is very strange as I looked into github repo and found that `Alphabet` is very much present [latest biopython](https://github.com/biopython/biopython/tree/4d01a84f0aa8f91863075f7f0f074b4b69e53959/Bio). Not only that, I looked into the old biopython packages and found that `Alphabet` is even present in biopython's [1st release 16 yrs ago.](http://biopython.org/DIST/biopython-1.00a3.tar.gz).

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
>>> import sys; print(sys.version)
2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.11.0-26-generic-x86_64-with-debian-wheezy-sid
>>> import Bio; print(Bio.__version__)
1.70
```

### Expected behaviour

Import `Alphabet` without any error.

### Actual behaviour

Command:
```
from Bio import Alphabet
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Alphabet
```

### Steps to reproduce

Single command:
```
from Bio import Alphabet
```

Please let me know if any suggestions.

**Comment by peterjc** [comment]
This is very strange, this may help:

```
>>> import Bio; print(Bio.__file__)
```

That will tell you where Python is loading Biopython from on disk, and then you can ``ls`` that folder to see if the ``Alphabet/`` subfolder and ``Alphabet/__init__.py`` exists.

How was your Biopython installed?

Note I have heard people say it is best to avoid mixing ``pip install`` and ``conda install``, which comes up in the discussion on https://github.com/kc-lab/dms2dfe/issues/3#issuecomment-331746060 - but don't know why.

**Comment by peterjc** [comment]
Closing for lack of information.
