### ISSUE TITLE
SeqIO unexpected silent with inputting fasta as fastq

### ISSUE THREAD

**Issue by wdecoster** [biopython/biopython#1410]
Hi,

### Setup

Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
CPython
Linux-4.4.0-97-generic-x86_64-with-debian-stretch-sid
Biopython 1.70

### Expected behaviour

I use on Biopython SeqIO to parse fastq files in various scripts. A user used a fasta file as input, I expected an error or warning to be raised.

### Actual behaviour

No exception is raised, no warning posted. The script ends silently. Upon inspection the generator only contains the StopIteration, i.e. is empty.

### Steps to reproduce

It doesn't look like there is anything odd with the fasta file, so should be easy to reproduce.
```
for read in SeqIO.parse("file_which_is_secrectly_fasta_bamboozled.fastq", "fastq"):
    print(read.seq)
```
-------------

If that's expected behaviour of SeqIO.parse then I need to add some code to check if the input is valid, but I was surprised to see that SeqIO didn't catch this issue and silently returns an empty generator.

Cheers,
Wouter

**Comment by peterjc** [comment]
Right now I don't recall why, but this is a side effect of tolerating a header before the first sequence. The special case of a FASTA record does seem worth giving an error on...

(Likewise the FASTA parser allows a generic header before the first record, one real life use of this is in GFF where after the annotations you can have the FASTA sequence)

**Comment by wdecoster** [comment]
I just naively tested something more ridiculous:

```Python
>>> from Bio import SeqIO
>>> a = SeqIO.parse("Bamboozled-again-fastq-is-actually-vf.vcf", "fastq")
>>> next(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```
And the behaviour is pretty much the same.

I haven't digged too deep in the SeqIO code, but I believe this issue is coming from FastqGeneralIterator https://github.com/biopython/biopython/blob/master/Bio/SeqIO/QualityIO.py#L896 where the loop never encounters a '@' and therefore just finishes silently.

```
    # Skip any text before the first record (e.g. blank lines, comments?)
    while True:
        line = handle_readline()
        if not line:
            return  # Premature end of file, or just empty?
        if line[0] == "@":
            break
        if isinstance(line[0], int):
            raise ValueError("Is this handle in binary mode not text mode?")
```

I would argue that an empty generator is always unexpected - and at least a warning would make sense there. 

Would this be solved by adding an `else` clause to the for loop using the FastqGeneralIterator, for example here: https://github.com/biopython/biopython/blob/master/Bio/SeqIO/QualityIO.py#L1033

If this makes any sense I could look into this further and perhaps write a fix and open a PR - but would first like to get your opinion on this.

**Comment by peterjc** [comment]
Empty files are a real valid FASTQ corner use case (as are empty files for many of the sequence file formats we support).

We never touched on possible headers in current FASTQ usage in https://dx.doi.org/10.1093%2Fnar%2Fgkp1137 (other than a remark that this would have been a good way to declare the encoding), so it would probably be fine to remove this loop and insist the first line starts with ``@`` as is usual.

CC @cjfields from BioPerl for his thoughts.

**Comment by cjfields** [comment]
@wdecoster I agree w/ @peterjc: an empty FASTQ file is a real side effect i have encountered fairly often (e.g. trimming paired reads for microbiome data, where one orphan read file such as R2 is empty for some samples).  I have also encountered empty files with other formats such as on-the-fly NCBI queries to attempt retrieval of sequences, or filtering steps with FASTA.  So immediately failing with an empty file seems like a bad idea since one would have to build in exception handling in every downstream instance (e.g. script) to work around it.

However, failing or warning in the case of a *non-empty* file/stream and an empty generator does make some sense as a form of validation.  This should also work for cases like FASTA embedded in GFF, as the generator should be non-empty if it's capturing the sequence data.  If there is a consistent IO core (I believe this is the case for most Bio*) this could possibly be handled at that level across formats to be consistent.

**Comment by peterjc** [comment]
It sounds like we're in agreement for FASTQ that other that for non-empty files there should be an error or some sequences returned.

Note in some file formats like XML you would have a non-empty file even with zero sequences.

**Comment by peterjc** [comment]
@wdecoster are you willing and able to test #1411 ?

**Comment by wdecoster** [comment]
Absolutely, will do so tonight.

**Comment by cjfields** [comment]
@peterjc re: XML good point.

**Comment by wdecoster** [comment]
Hi Peter,

I hope I did this right:

```
git clone https://github.com/peterjc/biopython.git
git checkout remotes/origin/fastq_headers
pip install -e .
```

And the result is:

```python
>>> import Bio
>>> Bio.__version__
'1.71.dev0'
>>> from Bio import SeqIO
>>> list(SeqIO.parse("file_which_is_secrectly_fasta_bamboozled.fastq", "fastq"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wdecoster/temp/bamboozled/biopython/Bio/SeqIO/__init__.py", line 612, in parse
    for r in i:
  File "/home/wdecoster/temp/bamboozled/biopython/Bio/SeqIO/QualityIO.py", line 1029, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/wdecoster/temp/bamboozled/biopython/Bio/SeqIO/QualityIO.py", line 904, in FastqGeneralIterator
    "Records in Fastq files should start with '@' character")
ValueError: Records in Fastq files should start with '@' character
```

So it seems to work perfectly. Thanks!

I only wonder (without sufficient experience in handling/raising errors) if a ValueError is sufficiently specific. Would a FileFormatError or something similar be more descriptive and easier to catch unambiguously? I can imagine that catching a ValueError in a more complicated setup could be too generic if I only want to print a message to the user that the file is not a fastq file. What are your thoughts about this? I write scripts for other users since only a few months, so I don't know what's the best way to handle this.

Cheers,
Wouter

**Comment by peterjc** [comment]
We do have a ``BiopythonParserWarning`` but not currently a Biopython specific parser or file-format exception. As a separate enhancement, that might be worthwhile - it could subclass ``ValueError``?

**Comment by wdecoster** [comment]
Sounds okay - although I have to admit I don't completely understand :)

**Comment by peterjc** [comment]
Closed via #1411

**Comment by wdecoster** [comment]
Thanks a lot for the quick fix!

**Comment by peterjc** [comment]
Your fresh eyes helped, thanks - this oddity has been there for far too long :(

We should start thinking about the next release as well to get this and other recent work out.
