### ISSUE TITLE
mmCIF parser should pass both '?' and '.' as empty fields to StructureBuilder

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#1425]
The mmCIF documentation states:

>There are two special characters used as placeholders for mmCIF item values which for some reason cannot be explicitly assigned. The question mark (?) is used to mark an item value as missing. A period (.) may be used to identify that there is no appropriate value for the item or that a value has been intentionally omitted. 

The current mmCIF parser arbitrarily checks for '.' or '?' depending on the field when it should check for both and translate both as empty to `StructureBuilder`. The result is a structure with, for example, '.' in insertion codes or '?' in alt codes (when you write a PDB file this will be trouble).

**Comment by peterjc** [comment]
Fix applied, thanks.
