### ISSUE TITLE
ssl.CertificateError: hostname 'www.expasy.ch' doesn't match either of 'www.expasy.org', 'expasy.org', 'insights.expasy.org'

### ISSUE THREAD

**Issue by uiwjgensuali** [biopython/biopython#1427]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]
platform CPython Windows-10-10.0.17017-SP0
Bio 1.71.dev0

### Expected behaviour
running without ssl.CertificateError

### Actual behaviour
I'm learning biopython by the tutorial,  when  searching Swiss-Prot(10.5.2), there is a ssl.CertificateError.
I searched the issues, can't find the solution. 
```python
from Bio import ExPASy
handle = ExPASy.sprot_search_de("Orchid Chalcone Synthase")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\python_js\biopython\master\biopython-master\Bio\ExPASy\__init__.py", line 147, in sprot_search_de
    return _binary_to_string_handle(_urlopen(fullcgi))
  File "C:\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Anaconda3\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Anaconda3\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Anaconda3\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Anaconda3\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Anaconda3\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
...
File "C:\Anaconda3\lib\ssl.py", line 688, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "C:\Anaconda3\lib\ssl.py", line 321, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'www.expasy.ch' doesn't match either of 'www.expasy.org', 'expasy.org', 'insights.expasy.org'
```
### Steps to reproduce
```python
from Bio import ExPASy
import re
handle = ExPASy.sprot_search_de("Orchid Chalcone Synthase")
handle = ExPASy.sprot_search_ful("Orchid and {Chalcone Synthase}")
```

**Comment by peterjc** [comment]
Looks like a problem with the domain itself, try https://www.expasy.ch/ in your browser - Chrome complains. @jervenbolleman may know who to contact about that.

Separately it is highly likely that some of the URLs in ``Bio.ExPASy`` are considered legacy, and can likely be moved over to point a UniProt equivalent.

**Comment by JervenBolleman** [comment]
expasy.ch should not be used but expasy.org I will however take it up with the relevant team that the rewrite rules are not correct.

I think that anything UniProtKB or Swiss-Prot related should be on uniprot.org. However, expasy.org hosts many interesting resources and is not a deprecated service. It is actually a key entry point to all of the Swiss Institute of Bioinformatics tools.

**Comment by peterjc** [comment]
Thank you! So we should look to move REST calls against https://www.expasy.ch/ to https://www.expasy.org/ then?

**Comment by JervenBolleman** [comment]
@peterjc I think so see my broken pull request at https://github.com/biopython/biopython/pull/1428

**Comment by peterjc** [comment]
After today's commits 5d3dbb12bf02a6c9ac1cd269571f7feb93dbd5a7 and 240e5fb0ef1c242fbcf21e78318323686a8e900c there should not be any references to the ``expasy.ch`` domain left.
