### ISSUE TITLE
BWA test failure

### ISSUE THREAD

**Issue by pgarland** [biopython/biopython#1431]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.6.3 (default, Oct  3 2017, 21:16:13) 
[GCC 7.2.0]
>>> CPython
Linux-4.13.0-1-amd64-x86_64-with-debian-buster-sid
>>> 1.71.dev0

### Expected behaviour

BWA test succeeds and shows the output of running the BWA index command.

### Actual behaviour
```bash
(biopython-3.6) pgarland@rimbaud:~/Hacking/biopython/Tests$ python run_tests.py test_BWA_tool.py
Python version: 3.6.3 (default, Oct  3 2017, 21:16:13) 
[GCC 7.2.0]
Operating system: posix linux
test_BWA_tool ... FAIL
======================================================================
FAIL: test_index (test_BWA_tool.BwaTestCase)
Test for creating index files for the reference genome fasta file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pgarland/Hacking/biopython/Tests/test_BWA_tool.py", line 102, in test_index
    % (cmdline, stdout))
AssertionError: False is not true : FASTA indexing failed:
bwa index -a bwtsw BWA/human_g1k_v37_truncated.fasta
Stdout:

----------------------------------------------------------------------
Ran 1 test in 0.493 seconds

FAILED (failures = 1)
```

### Steps to reproduce

Running the biopython test suite.

**Comment by peterjc** [comment]
It would appear the test has caught a major behaviour change in BWA, which is worth knowing about. A little investigation would be needed, but assuming that to be the case and that BWA is well behaved, checking for a non-zero return makes sense. CC @saketkc (original wrapper author).

**Comment by peterjc** [comment]
Cross reference Debian issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880236

**Comment by saketkc** [comment]
Thank you @pgarland and @peterjc! It seems to break because of the change upstream:
https://github.com/lh3/bwa/commit/298284d754aa946b24a9d40d12cd911c57e8eacd
See #1437

**Comment by pgarland** [comment]
I tried the bwa banch from the repo of @saketkc and running the BWA_tool test now passes on my system.

**Comment by peterjc** [comment]
Good detective work @saketkc, that BWA commit explains the stderr/stdout change.
