### ISSUE TITLE
How to read HETATM line in pdb file?

### ISSUE THREAD

**Issue by qzlshy** [biopython/biopython#1433]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
Biopython 1.70
python 3.5.2
CPython
Linux-4.10.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
```

(*
from Bio.PDB.PDBParser import PDBParser
p = PDBParser()
s = p.get_structure("*.pdb")
 *)

### Expected behaviour

(*
I want to read the line begin with "HETATM" from pdb file. But the result only include the "ATOM" line.
*)

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

**Comment by JoaoRodrigues** [comment]
The `PDBParser` reads HETATM lines by default. If you have questions about the usage of the code, instead of opening an issue, write to the Biopython users mailing list (biopython@biopython.org). You'll get faster help there.
