### ISSUE TITLE
SeqIO.parse failing with anaconda3-4.0.0/lib/python3.5

### ISSUE THREAD

**Issue by michaldrori** [biopython/biopython#1454]
[55457.zip](https://github.com/biopython/biopython/files/1474598/55457.zip)
### Setup

I am reporting a problem with Biopython, Python 3.5, running on linux. When switching to python 3.3.0
there was no error:

```python
from Bio import SeqIO

sequences_path = 'XXXXXXX/GenBank/55457'
speciesSeqRecords = SeqIO.parse(sequences_path, "genbank")
write list(speciesSeqRecords)
for seq in list(speciesSeqRecords):
    print(seq.name)
    print(seq.description)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

```
  File "CheckBug.py", line 5, in <module>
    print( list(speciesSeqRecords))
  File "/share/apps/python/anaconda3-4.0.0/lib/python3.5/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/share/apps/python/anaconda3-4.0.0/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 478, in parse_records
    record = self.parse(handle, do_features)
  File "/share/apps/python/anaconda3-4.0.0/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 462, in parse
    if self.feed(handle, consumer, do_features):
  File "/share/apps/python/anaconda3-4.0.0/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 430, in feed
    self._feed_header_lines(consumer, self.parse_header())
  File "/share/apps/python/anaconda3-4.0.0/lib/python3.5/site-packages/Bio/GenBank/Scanner.py", line 1425, in _feed_header_lines
    structured_comment_key = re.search(r"([^#]+){0}$".format(STRUCTURED_COMMENT_START), data).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

### Expected behaviour

```
module load python/python-3.3.0
(compute-7-1:bioseq) /bioseq/data/results/oneTwoTree/1510735961> python CheckBug.py &
[1] 70721
(compute-7-1:bioseq) /bioseq/data/results/oneTwoTree/1510735961> [SeqRecord(seq=Seq('TGACATAAAATTAACAGAACTNNTGTATAGGAACTTAATAAACCTCAAGGATCT...AAG', IUPACAmbiguousDNA()), id='AB120563.1', name='AB120563', description='Groenlandia densa chloroplast DNA, trnT-trnL intergenic spacer, country:Switzerland: Zurich, Linth Muendung.', dbxrefs=[]), SeqRecord(seq=Seq('AAGTGCTGGATTTAAAGCTGGTGTTAAAGATTACAAATTGACTTATTATACTCC...CTT', IUPACAmbiguousDNA()), id='AB196954.1', name='AB196954', description='Groenlandia densa chloroplast rbcL gene for large subunit of ribulose 1,5-bisphosphate carboxylase/oxygenase, partial cds.', dbxrefs=[]), SeqRecord(seq=Seq('ACTTGATTAGATTGAGCCTTGGTATGGAAACCTACTAAGTGTTAACTTCCAAAT...AGG', IUPACAmbiguousDNA()), id='DQ786416.1', name='DQ786416', description='Groenlandia densa tRNA-Leu (trnL) gene and trnL-trnF intergenic spacer, partial sequence; chloroplast.', dbxrefs=[]), SeqRecord(seq=Seq('TTTTCTTCTTCGTCTTATTCCAAGAGTCACATCATCCGTTGGTGCATAGCTACG...ACC', IUPACAmbiguousDNA()), id='DQ786446.1', name='DQ786446', description='Groenlandia densa 5S ribosomal RNA nontranscribed spacer, partial sequence.', dbxrefs=[]), SeqRecord(seq=Seq('CGTAATGCTCACAATTTCCCTCTAGACCTAGCTGCTGTTGAAGCTCCATCTATA...CGG', IUPACAmbiguousDNA()), id='DQ786521.1', name='DQ786521', description='Groenlandia densa psbA gene, partial sequence; psbA-trnH intergenic spacer, complete sequence; trnH gene partial sequence; chloroplast.', dbxrefs=[]), SeqRecord(seq=Seq('TTGGATGAAGCAACGAATTCGTCTAGACTTTTGGTTGAGTCTATAAAACCACGA...AAA', IUPACAmbiguousDNA()), id='HQ456497.1', name='HQ456497', description='Groenlandia densa voucher Philbrick 4585 (WCSU) tRNA-Lys (trnK) gene, partial sequence; and maturase K (matK) gene, partial cds; chloroplast.', dbxrefs=[]), SeqRecord(seq=Seq('ACGTAAAGTTGCCAGAGTACGATTAACCTCTGGATTTGAAATCACTGCTTATAT...GTA', IUPACAmbiguousDNA()), id='HQ901387.1', name='HQ901387', description='Groenlandia densa ribosomal protein S12 (rps12) gene, partial cds; ribosomal protein S7 (rps7) and NADH dehydrogenase subunit B (ndhB) genes, com
```

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

*Copy the attached file to your loca dir and just replace the path 'XXXXXXX/GenBank/55457' with your path of the file. perform "module load python/anaconda3-4.0.0" and run the script.

Thanks

Michal

**Comment by peterjc** [comment]
Thanks for providing a test case.

What version of Biopython do you have? Running this in Python ought to tell us:

```python
import Bio; print(Bio.__version__)
```

**Comment by peterjc** [comment]
Note Biopython 1.69 was our last release to support Python 3.3

You test case as written will not work - the line ``write list(speciesSeqRecords)`` is invalid syntax.

Reduced test case which works for me on Apple macOS provided Python 2.7:

```
$ python -c "from Bio import SeqIO; print([r.id for r in SeqIO.parse('55457', 'genbank')])"
['AB120563.1', 'AB196954.1', 'DQ786416.1', 'DQ786446.1', 'DQ786521.1', 'HQ456497.1', 'HQ901387.1', 'HQ901413.1', 'HQ901440.1', 'HQ901467.1', 'HQ901494.1', 'HQ901521.1', 'HQ901546.1', 'HQ901571.1', 'JN891566.1', 'JN891567.1', 'JN893692.1', 'JN894619.1', 'JN896144.1']
```

And works on my self-compiled Python 3.6 on macOS etc:

```
$ python3 -c "from Bio import SeqIO; print([r.id for r in SeqIO.parse('55457', 'genbank')])"
['AB120563.1', 'AB196954.1', 'DQ786416.1', 'DQ786446.1', 'DQ786521.1', 'HQ456497.1', 'HQ901387.1', 'HQ901413.1', 'HQ901440.1', 'HQ901467.1', 'HQ901494.1', 'HQ901521.1', 'HQ901546.1', 'HQ901571.1', 'JN891566.1', 'JN891567.1', 'JN893692.1', 'JN894619.1', 'JN896144.1']
```

I've tried Biopython 1.65, 1.66, 1.67, 1.68, 1.69, 1.70 and current master branch under Python 3.6.0 on macOS and all of them worked.

I've tried Biopython 1.65, 1.66, 1.67, 1.68, 1.69, 1.70 and current master branch under Python 3.5.0 on 64-bit Linux and all of them worked.

(There have been some structured comment changes in the GenBank parser fairly recently, but this didn't make it to the NEWS file so I just checked several releases back)

This makes me wonder if this is in some way anaconda specific. Again which version of Biopython is breaking, and how did you install Biopython under Anaconda? Do you recall which package and conda channel was used?

**Comment by michaldrori** [comment]
Hi,

Thank you for responding :) my Biopython version is 1.68  working under the following system.

$ module load python/anaconda3-4.0.0
$ python
Python 3.5.3 |Anaconda custom (64-bit)| (default, Feb 22 2017, 21:13:27)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

The anaconda was forced by IT so I'm not sure how to answer your question. I can try and ask them if you think it can help solve this issue.

thanks
Michal

**Comment by peterjc** [comment]
Can you run this (long) command at the terminal please, and copy-paste the output?

```
$ python -c "import sys; print(sys.version); import Bio; print(Bio.__version__); from Bio import SeqIO; print([r.id for r in SeqIO.parse('55457', 'genbank')])"
```

It works for me using Python 3.5 (which is slightly older than your Python 3.5.3) on Linux:

```
$ python3.5 -c "import sys; print(sys.version); import Bio; print(Bio.__version__); from Bio import SeqIO; print([r.id for r in SeqIO.parse('55457', 'genbank')])"
3.5.0 (default, Sep 28 2015, 11:25:31) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
1.71.dev0
['AB120563.1', 'AB196954.1', 'DQ786416.1', 'DQ786446.1', 'DQ786521.1', 'HQ456497.1', 'HQ901387.1', 'HQ901413.1', 'HQ901440.1', 'HQ901467.1', 'HQ901494.1', 'HQ901521.1', 'HQ901546.1', 'HQ901571.1', 'JN891566.1', 'JN891567.1', 'JN893692.1', 'JN894619.1', 'JN896144.1']
```

Assuming that fails for you, I could try to get an Anaconda or at least conda version of Python setup to match yours.

**Comment by michaldrori** [comment]
Hi,

It seems that loading python/**anaconda3-5.0.0** solved the problem

Thanks,
Michal

**Comment by peterjc** [comment]
I remain puzzled about what was wrong, and if there is anything we need to fix within Biopython, but good news that it works for you now.

Unless you want to help explore this further, should we close this issue?

**Comment by stephy2985** [comment]
@peterjc 
I am having an issue running BLAST in Biopython. This is my code:

from Bio import SearchIO

result_handle = NCBIWWW.qblast("blastn", "nt", 153219)
with open("my_blast.xml", "w") as out_handle:
    out_handle.write(result_handle.read())

result_handle.close()

And then the main error I get is this:
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

I have a Mac and i am running python 3.6. The program is not in the applications folder but in the frameworks:
/Library/Frameworks/Python.framework/Versions/3.6/bin/

now I do not know (and i have tried many things) to update the certificates.
Could you help me?

Thanks in advance!!

**Comment by peterjc** [comment]
@stephy2985 that is a completely separate issue and is something to do with the SSL certificates on your machine (not specific to Biopython). If you are still stuck, please open a new issue about this.

**Comment by peterjc** [comment]
Closing as @michaldrori's original issue seems to be solved.
