### ISSUE TITLE
Warning users about their old pip installations

### ISSUE THREAD

**Issue by Cediddi** [biopython/biopython#1457]
This is not a bug but a proposal, thus ignoring the issue report template.

As a continuation of https://github.com/biopython/biopython/pull/130 I think if pip version is important for biopython, then it should give either an error for prehistoric pip versions or give a update error for old versions.

I tried installing biopython with 1.5.x, 6-7-8-9 and only 1.5 can't install biopython without numpy. All the newer versions can do. Only pip version 9.0.1 installs precompiled wheels by default and it's a great time reduction.

I think giving a sensible error for 1.5 and a warning for >1.5.6 (using pip's included mechanism) would be a good improvement.

I found out that pip's warning mechanism is not included in 1.5.6 but is included in next version, which is 6 and does work. Thus importing the mechanism can cause 3 outcomes;
- No output means we're up to date
- A warning, we're not up to date but still can install without a major issue
- An ImportError

This codeblock is a crude implementation.

```
try:
    from pip.utils.outdated import pip_version_check
    pip_version_check(None)  # you can actually send your pip session here
except ImportError:
    raise Exception("Your pip is prehistoric, please upgrade your pip")
```

AFAIK all python3 versions come with pip preinstalled, as well as 2.7 thus not having a pip shouldn't be a issue. But for users that install from source can have a problem here. Wheels can only be installed with pip. tar.gz and git clone are the main issues here.

**Comment by peterjc** [comment]
Looks like we didn't follow up on this - and now that we require Python 3.6 onwards, I think this can be closed.

Thank you @chebizarro for help with issue triage
