### ISSUE TITLE
Unable to output nexus file

### ISSUE THREAD

**Issue by thkuo** [biopython/biopython#1458]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Linux-4.4.0-98-generic-x86_64-with-debian-stretch-sid
1.70
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
Conversion of a fasta file (dna alignment) to a nexus file
### Actual behaviour
The file was successfully parsed, but the records couldn't be written in nexus format. The message was:
```ValueError: Need a DNA, RNA or Protein alphabet```
### Steps to reproduce
My sequences in ```test.aln``` are:
```
>seq1
AATTC
>seq2
AATTC
```
The script to convert the file was:
```
from Bio import AlignIO
f='test.aln'
out_f= 'test.nexus'

fh= open(f, 'r')
out_fh= open(out_f, 'w')
records= AlignIO.read(fh, 'fasta')
for rec in records:
AlignIO.write(records, out_fh, 'nexus')
fh.close()
out_fh.close()
```

**Comment by peterjc** [comment]
That is expected behaviour. When loading the FASTA file you need to tell Biopython this is DNA, try:

```
from Bio.Alphabet import generic_dna
```

and then use:

```
AlignIO.read(fh, 'fasta', alphabet, generic_dna)
```

Also you might prefer to use ``AlignIO.convert(...)`` instead of calling ``AlignIO.read(...)`` and ``AlignIO.write(...)`` here:

```python
from Bio.Alphabet import generic_dna
from Bio import AlignIO
f='test.aln'
out_f= 'test.nexus'
AlignIO.convert(f, 'fasta', out_f, 'nexus', generic_dna)
```

**Comment by thkuo** [comment]
It works perfectly. Many thanks!

**Comment by peterjc** [comment]
Excellent, thanks for confirming it worked. If you can suggest any specific change to our documentation to help others here, that would be great.

**Comment by thkuo** [comment]
Sorry for bothering again, but probably I found some behaviors that I didn't expect. Part of the sequence names in my fasta file were quoted after the conversion (ie. seq1-0 -> 'seq1-0'). These names, in my case, have non-word characters but without gaps. Do you think it should be fixed?

**Comment by peterjc** [comment]
Can you share the example input and output files? Or some of the text?

**Comment by thkuo** [comment]
The full alignment is large, so I am just showing part of it. 
The original fasta was:
```
>RefCln_W16407
atgaccttgaaatccgtaatcagcctgctggcgaccctgctgatcctgctggtcgccgtattcatcgggc
>RefEnv_MTB-1
atgaccttgaaatccgtaatcagcctgctggcgaccctgctgatcctgctggtcgccgtattcatcgggc
>CH2713
atgaccttgaaatccgtaatcagcctgctggcgaccctgctgatcctgttggtcgccgtattcatcgggc
```
The nexus output was:
```
#NEXUS
begin data;
        dimensions ntax=506 nchar=2155764;
        format datatype=dna missing=? gap=- interleave;
matrix
RefCln_W16407                  atgaccttgaaatccgtaatcagcctgctggcgaccctgctgatcctgctggtcgccgtattcatcgggc
'RefEnv_MTB-1'                 atgaccttgaaatccgtaatcagcctgctggcgaccctgctgatcctgctggtcgccgtattcatcgggc
CH2713                         atgaccttgaaatccgtaatcagcctgctggcgaccctgctgatcctgttggtcgccgtattcatcgggc

;
end;
```

**Comment by peterjc** [comment]
I believe this is deliberate - NEXUS has rules about putting quotes around names using special characters (like spaces), and I presume the minus sign triggered that.
