### ISSUE TITLE
Convert protein Seq to binary vector?

### ISSUE THREAD

**Issue by EmanIsmail** [biopython/biopython#1474]
How can I convert protein sequence 
"MASVKSSSSSSSSSFISLLLLILLVIVLQSQVIECQPQQSCTASLTGLNVCAPFLVPGSP"
to binary vector "01100001111011111110"
to be able work with it as numpy vector??

**Comment by JoaoRodrigues** [comment]
I guess you have to define what each letter means, then you can convert it
to its proper numerical representation. For example, charged residues = 1,
non-charged = 0.

Otherwise if you want to convert EACH letter to its binary representation
and concatenate the entire array: http://bfy.tw/FWTe

**Comment by peterjc** [comment]
You'd have to explain what exactly you had in mind for a binary encoding.

FYI, you can have fixed length string arrays in NumPy, e.g. one-character entries:

```python
>>> import numpy as np
>>> from Bio import AlignIO
>>> alignment = AlignIO.read("PF05371_seed.sth", "stockholm")
>>> align_array = np.array([list(rec) for rec in alignment], np.character)
>>> print("Array shape %i by %i" % align_array.shape)
Array shape 7 by 52
```

Example from http://biopython.org/DIST/docs/tutorial/Tutorial.html

You can also have NumPy arrays of Python strings of variable length.

**Comment by EmanIsmail** [comment]
Thanks a lot

**Comment by peterjc** [comment]
Can we close this issue, or do you have a more precise question?
