### ISSUE TITLE
Representation of restriction enzymes do not work in the IPython shell

### ISSUE THREAD

**Issue by BjornFJohansson** [biopython/biopython#1491]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

(bjorn36) bjorn@bjorn-ThinkPad-T450s:~/python_packages/biopython$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.10.0-42-generic-x86_64-with-debian-stretch-sid
>>> import Bio; print(Bio.__version__)
1.71.dev0
>>> 

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(bjorn36) bjorn@bjorn-ThinkPad-T450s:~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/Bio/Restriction$ ipython
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from Bio.Restriction import EcoRI

In [2]: repr(EcoRI)
Out[2]: 'EcoRI'

In [3]: EcoRI
Out[3]: EcoRI

In [4]:

### Actual behaviour

bjorn@bjorn-ThinkPad-T450s:~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/Bio/Restriction$ bjorn36
(bjorn36) bjorn@bjorn-ThinkPad-T450s:~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/Bio/Restriction$ ipython
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from Bio.Restriction import EcoRI

In [2]: repr(EcoRI)
Out[2]: 'EcoRI'

In [3]: EcoRI
Out[3]: ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    959             # lookup registered printer
    960             try:
--> 961                 printer = self.lookup(obj)
    962             except KeyError:
    963                 pass

~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/IPython/core/formatters.py in lookup(self, obj)
    393             return self.singleton_printers[obj_id]
    394         # then lookup by type
--> 395         return self.lookup_by_type(_get_type(obj))
    396 
    397     def lookup_by_type(self, typ):

~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/IPython/core/formatters.py in _get_type(obj)
    274 def _get_type(obj):
    275     """Return the type of an instance (old and new-style)"""
--> 276     return getattr(obj, '__class__', None) or type(obj)
    277 
    278 

~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/Bio/Restriction/Restriction.py in __len__(cls)
    342 
    343         length of the recognition site."""
--> 344         return cls.size
    345 
    346     def __hash__(cls):

AttributeError: type object 'RestrictionType' has no attribute 'size'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-cdf3fb855965> in <module>()
----> 1 EcoRI

~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/IPython/core/displayhook.py in __call__(self, result)
    255             self.start_displayhook()
    256             self.write_output_prompt()
--> 257             format_dict, md_dict = self.compute_format_data(result)
    258             self.update_user_ns(result)
    259             self.fill_exec_result(result)

~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    149 
    150         """
--> 151         return self.shell.display_formatter.format(result)
    152 
    153     # This can be set to True by the write_output_prompt method in a subclass

~/anaconda3/envs/bjorn36/lib/python3.6/site-packages/IPython/core/formatters.py in format(self, obj, include, exclude)
    148             return {}, {}
    149 
--> 150         format_dict, md_dict = self.mimebundle_formatter(obj, include=include, exclude=exclude)
    151 
    152         if format_dict or md_dict:

TypeError: 'NoneType' object is not iterable

In [4]: 

### Steps to reproduce

see above

**Comment by BjornFJohansson** [comment]
I wrote up some more details here:

https://gist.github.com/BjornFJohansson/7c5185a38e024dc684762da272b29481

**Comment by MarkusPiotrowski** [comment]
@BjornFJohansson There is actually a PR (#1486) on a related issue by @peterjc, also related to the ```len()```.
Can you try his "hack" if this solves the problem?

**Comment by peterjc** [comment]
I'm guessing this is a Python 3 specific bug, is it easy for you to try this under Ipython with Python 2?

**Comment by BjornFJohansson** [comment]
My initial test with Python 3.6 confirm that #1486 also solves the IPython problem I have. I will try Python 2.7 as well.

**Comment by BjornFJohansson** [comment]
#1486 also solves IPython problem in 2.7.

**Comment by peterjc** [comment]
Excellent news, thank you @BjornFJohansson - and @MarkusPiotrowski for spotting the connection.

**Comment by peterjc** [comment]
Hmm, this isn't as simple as I was hoping for:

```
$ python -c "import Bio; print(Bio.__version__); from Bio.Restriction import EcoRI; print(bool(EcoRI)); print(repr(EcoRI))"
1.71.dev0
True
EcoRI
$ python3.6 -c "import Bio; print(Bio.__version__); from Bio.Restriction import EcoRI; print(bool(EcoRI)); print(repr(EcoRI))"
1.71.dev0
True
EcoRI
```

i.e. Neither ``__repr__`` nor ``__bool__`` are breaking in C Python.

**Comment by peterjc** [comment]
Reading the stacktrace in https://gist.github.com/BjornFJohansson/7c5185a38e024dc684762da272b29481 it makes sense that the ``__len__`` change on #1486 would also work for IPython.

**Comment by BjornFJohansson** [comment]
@peterjc That is my experience as well. We probably do not need both #1486 and #1491. What I do not know is if #1491 also solve the sphinx problem even in the absence of #1486. If it does, I wonder if people would agree with me that #1491 is slightly less hackish since we add a __bool__ method instead of a try except in __len__. Although I would be satisfied with either.

**Comment by peterjc** [comment]
I agree that explicitly defining ``__bool__`` is more elegant and cleaner than my try/except hack in ``__len__``. Although I do wonder if there are any enzymes where the length is reported as zero, and thus the boolean value would be false? Seems unlikely.

However... it was at almost same time, so you may not have seen this: https://github.com/biopython/biopython/pull/1486#issuecomment-356990613

> Based on https://travis-ci.org/peterjc/biopython/jobs/327744275 adding the __bool__ definition > from #1492 does not solve the Sphinx problem.

**Comment by BjornFJohansson** [comment]
@peterjc I can not think of any situation where an enzyme should report False as the module only deals with enzymes with known recognition sequences... However, it is probably better to stick with #1486 and discard the #1491 since the former solves both problems.

**Comment by MarkusPiotrowski** [comment]
@BjornFJohansson Thank you for your efforts. I think it's consense that we should merge #1486 now (since it solves both problems) and close #1492.

**Comment by peterjc** [comment]
Agreed, thank you both for looking at this.
