### ISSUE TITLE
Translation of partial sequence in a different frame

### ISSUE THREAD

**Issue by ctSkennerton** [biopython/biopython#1507]
I've found that when translating a partial feature from a genbank file (https://www.ncbi.nlm.nih.gov/nuccore/938512178) with a `codon_start` tag the correct frame isn't used. Is there another way to translate a feature such that this information is taken into account?

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
CPython
Darwin-17.3.0-x86_64-i386-64bit
1.71.dev0
```

### Expected behaviour

```
VTLTDNVSDEGQLSYRIGAAGSTYYFQKQAGGLSSLVDASNNDWINFHPTPWTSAGGGYRGIPNVYANGIFHPGWTTGTSSIVSQGPLKIRVRSVTNNGLWESLWDFYPGYATNTIVKAGGTYWWLYEGTPGGSLDQNTDFMVRSDNRKTMLSVRTNDDIPTDEWVYFSDPNVNRSLFVSHHEDDSLIDEYHPMTDT
```

### Actual behaviour

```
GYTYR*CL**RAVKLSDRSSRQHLLLPETGRRFIESCGCIK**LDQFPSDSLDQCRRGIPRHSQCLC*WDFPSGLDNRYKQYSLTGTAKDQSKVSHK*WTMGKSLGLLSRICYKYHSKSRRHLLVALRRYSRRVVRSKYRFHGQI***EDHALCENK**YSHRRMGLFQ*SECESLPVRFAP*G*FIN**IPSDDGY
```

### Steps to reproduce

```python
with open("LKCM01000029.gb") as fp:
     for rec in SeqIO.parse(fp, "gb"):
        for feat in rec.features:
            if feat.type == 'CDS':
                print(feat.extract(rec.seq).translate(table=11))
```

**Comment by peterjc** [comment]
Personally I've never needed to do much with partial gene features, but have pondered this functionality as a sister method of the ``SeqFeature``'s existing ``extract`` method. i.e. Something to extract and translate the sequence using any ``codon_start`` and ``transl_table`` information from the qualifiers.

So currently nothing built in, you'd need to do something like this I'd guess:

```
default_table = 11
with open("LKCM01000029.gb") as fp:
     for rec in SeqIO.parse(fp, "gb"):
        for feat in rec.features:
            if feat.type == 'CDS':
                codon_start = int(feat.qualifiers.get("codon_start", [1])[0]) - 1
                codon_table = int(feat.qualifiers.get("transl_table", [default_table])[0])
                print(feat.extract(rec.seq)[codon_start:].translate(codon_table))
```

**Comment by ctSkennerton** [comment]
Thanks for the solution Peter. I made a pull #1509 as a possible way to add in a translate method for seqfeatures.
