### ISSUE TITLE
Is there any way to remove gaps and complete deletion from fasta file

### ISSUE THREAD

**Issue by raoasifraza11** [biopython/biopython#1511]
### Setup

I want to remove gaps "----" form align fasta file. I search from documentation but did't found any hlep. Can any one help me?

```python
import sys; print(sys.version)
2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-17.3.0-x86_64-i386-64bit

import Bio; print(Bio.__version__)
1.70
```

**Comment by peterjc** [comment]
The ``Seq`` object has an ``.ungap()`` method, which should help do what you want, e.g.

```python
from Bio import SeqIO
for record in SeqIO.parse("example.fasta", "fasta"):
    print("%s without gaps is %s" % (record.id, record.seq.ungap("-")))
```

If that is not enough, could you be more explicit about what you want to do? Can you give an example of the input file and desired output?

**Comment by janeetjovial** [comment]
Hello! I tried this method earlier but it only removes (-) from the input aligned file.  Actually i need to apply complete deletion method in which all the gaps and missing residues should be removed. So is there any way to remove residues(entries ) against gap (-) in aligned file?

**Comment by raoasifraza11** [comment]
@peterjc

**Comment by peterjc** [comment]
Ah! So what you want to do is manipulate the alignment as a matrix, and remove columns which have any gaps (or some other criteria?). The tutorial http://biopython.org/DIST/docs/tutorial/Tutorial.html touches on this 

> addition of alignment objects works by column. This lets you do this as a way to remove a block of columns:

```
>>> edited = alignment[:, :6] + alignment[:, 9:]
>>> print(edited)
SingleLetterAlphabet() alignment with 7 rows and 49 columns
AEPNAAATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIRLFKKFSSKA COATB_BPIKE/30-81
AEPNAAATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIKLFKKFVSRA Q9T0Q8_BPIKE/1-52
DGTSTAATEAMNSLKTQATDLIDQTWPVVTSVAVAGLAIRLFKKFSSKA COATB_BPI22/32-83
AEGDDPAKAAFNSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFTSKA COATB_BPM13/24-72
AEGDDPAKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFASKA COATB_BPZJ2/1-49
AEGDDPAKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFTSKA Q9T0Q9_BPFD/1-49
FAADDAAKAAFDSLTAQATEMSGYAWALVVLVVGATVGIKLFKKFVSRA COATB_BPIF1/22-73
```

Right now there is nothing built in, but I did wonder this a long time ago: http://mailman.open-bio.org/pipermail/biopython-dev/2010-June/016979.html

**Comment by raoasifraza11** [comment]
@peterjc Okay let me check it.

**Comment by janeetjovial** [comment]
Thanks @peterjc . This can be helpful i guess.

**Comment by raoasifraza11** [comment]
I am going to close this issue the above answer is not the solution which we want.

**Comment by Ramsha12-star** [comment]
@raoasifraza11 help me I also want to apply complete deletion on my alignment files.
