### ISSUE TITLE
UnknownSeq.ungap() ignores the passed gap character

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#1512]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
CPython
Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
1.71.dev0
0008a0d
```

I took the liberty of adding my git hash. :)

### Expected behaviour

`UnknownSeq.ungap()` passes on the gap character used to `Seq.ungap()` in https://github.com/biopython/biopython/blob/master/Bio/Seq.py#L1693

### Actual behaviour

Gap character is ignored.

### Steps to reproduce

Visual inspection of https://github.com/biopython/biopython/blob/master/Bio/Seq.py#L1693

**Comment by kblin** [comment]
I'll do a patch for this next week, just can't be bothered today.

**Comment by peterjc** [comment]
Opps. Good catch. The fix look easy (one word), but adding a unit test is slightly more work.

**Comment by kblin** [comment]
One week later than intended, but there we go. :)

**Comment by peterjc** [comment]
Thanks! I was wondering if I should do it if I got a lull in my day.
