### ISSUE TITLE
Include distout option in MAFFT wrapper

### ISSUE THREAD

**Issue by btski** [biopython/biopython#1521]
MAFFT provides distance scoring through the distout command which does not appear available via the command line wrapper. It seems it may have been done in the past (https://www.biostars.org/p/6732/), but I see no record on this GitHub page mentioning a distout feature. I am interested in an alignment scoring feature and will attempt to make modifications to the wrapper accordingly.

**Comment by btski** [comment]
Source code: https://github.com/biopython/biopython/blob/master/Bio/Align/Applications/_Mafft.py
Seems including the distout feature to the wrapper should be as simple as adding two lines of code:
_Switch(["--distout", "distout"],
              "Generates distance matrix as hat2 file. Default: off"),
However, I don't seem to be modifying the same file being called. I've tried following the file path given by error codes generated from Bio.Application. I've also used the inspect package (inspect.getfile(MafftCommandline)). Both lead to the same file location, but when I heavily modify the file/package, it remains fully functional when called via python.

**Comment by peterjc** [comment]
Yes, editing installed Python files is not recommended - although it can be done.

Your proposal makes sense if MAFFT has this option - but my version does not seem to:

```
$ mafft --version
v7.310 (2017/Mar/17)
[pc40583@gruffalo2 ~]$ mafft --help

------------------------------------------------------------------------------
  MAFFT v7.310 (2017/Mar/17)
  http://mafft.cbrc.jp/alignment/software/
  MBE 30:772-780 (2013), NAR 30:3059-3066 (2002)
------------------------------------------------------------------------------
High speed:
  % mafft in > out
  % mafft --retree 1 in > out (fast)

High accuracy (for <~200 sequences x <~2,000 aa/nt):
  % mafft --maxiterate 1000 --localpair  in > out (% linsi in > out is also ok)
  % mafft --maxiterate 1000 --genafpair  in > out (% einsi in > out)
  % mafft --maxiterate 1000 --globalpair in > out (% ginsi in > out)

If unsure which option to use:
  % mafft --auto in > out

--op # :         Gap opening penalty, default: 1.53
--ep # :         Offset (works like gap extension penalty), default: 0.0
--maxiterate # : Maximum number of iterative refinement, default: 0
--clustalout :   Output: clustal format, default: fasta
--reorder :      Outorder: aligned, default: input order
--quiet :        Do not report progress
--thread # :     Number of threads (if unsure, --thread -1)
```

That's only some of the options - https://mafft.cbrc.jp/alignment/software/manual/manual.html#lbAI lists more, but again I don't see a ``distout`` feature.

Right now https://www.biostars.org/p/6732/ is failing (Internal Server Error), so I'm not sure what it says.

**Comment by btski** [comment]
Sorry, here's an image of the biostars post:
<img width="879" alt="screen shot 2018-02-01 at 3 23 03 pm" src="https://user-images.githubusercontent.com/32686196/35704081-da78f864-0763-11e8-8a09-361819e3ee99.png">

The distout feature is in the source code but isn't documented (the biostars post seems to be the best existing documentation). I am currently using MAFFT v7.310 (2017/Mar/17). I will update documentation assuming Dr. Katoh (MAFFT author) wishes for distout to be supported.

**Comment by peterjc** [comment]
OK, assuming the MAFFT authors are happy for people to use ``--distout`` adding it to the Biopython wrapper is a good idea. Would you be able to submit a pull request doing this, and adding a brief test using the new argument and confirming the file is created?

**Comment by btski** [comment]
The developer's response in it's entirety:

> The --distout flag is just for my personal use and there is no document.  I think it's better and safer for you to use your code to assess the similarity or distance of sequences from a given alignment.  However, I think I can explain this option.  Please check if it'll be useful for your purpose or not:  
> 
> The --distout option outputs distances that are used for building a guide tree.  Note that the distances are computed *before* building an MSA, not computed *from* the MSA.  The distances are converted from pairwise scores with this equation,
> 
> Distance(i,j) = 1 - Score(i,j) / min( Score(i,i), Score(j,j) )
> 
> 
> as explained in our old paper, Katoh et al 2002.  Score() can be computed by various ways (without MSA).  In Katoh2002, Score(i,j) was the number of 6mers that are shared by sequences i and j.  If the --localpair flag is set, then Score(i,j) is the pairwise alignment score between sequences i and j.  The pairwise alignment is not always the same as the resulting MSA even if the number of the input sequences is two.

The distout setting is not what I expected but with appropriate documentation it could still be useful.

**Comment by peterjc** [comment]
It is interesting to see those details - I would have guess this was a distance matrix computed from the MSA. It seems that the author does not really intend it for general use, so we probably shouldn't advertise it by adding it to the Biopython wrapper.
