### ISSUE TITLE
ValidationError With Clinvar and rettype variation

### ISSUE THREAD

**Issue by rbutleriii** [biopython/biopython#1528]
### Setup
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609]
CPython
Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
Biopython 1.70

### Expected behaviour
```
result = Entrez.read(Entrez.efetch(db='clinvar', id='11,9', rettype='variation'))
```
should return an xml

### Actual behaviour
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rbutl/.local/lib/python3.5/site-packages/Bio/Entrez/__init__.py", line 453, in read
    record = handler.read(handle)
  File "/home/rbutl/.local/lib/python3.5/site-packages/Bio/Entrez/Parser.py", line 233, in read
    self.parser.ParseFile(handle)
  File "../Modules/pyexpat.c", line 414, in StartElement
  File "/home/rbutl/.local/lib/python3.5/site-packages/Bio/Entrez/Parser.py", line 368, in startElementHandler
    raise ValidationError(name)
Bio.Entrez.Parser.ValidationError: Failed to find tag 'ClinVarResult-Set' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.
```
### Steps to reproduce

I tried replacing my DTD folder with the latest github version in my ~/.local/lib/python3.5/site-packages/Bio/Entrez/DTDs, and also copied the efetch dtd from NCBI. neither helped. validate=False returns blank object, as 'ClinVarResult-Set' is at the top.

**Comment by peterjc** [comment]
Thanks for reporting this.

This kind of DTD XML validation problem is usually a (temporary) problem with the NCBI where the DTD file is out of sync, or sometimes the back end system for some of their databases simply do not have a defined DTD. In these cases, an non-DTD based XML parser is the best fall back, and Python comes with several (e.g. ``ElementTree``).

Sadly here the NCBI are simply not providing a DTD file:

```
>>> from Bio import Entrez
>>> with Entrez.efetch(db='clinvar', id='11,9', rettype='variation') as handle:
...     print(handle.url)
...     with open("clinvar_example.xml", "w") as tmp:
...         tmp.write(handle.read())
...
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&id=11%2C9&rettype=variation&tool=biopython
318214
```

Leaving off the tool and email arguments, the minimal NCBI Entrez URL is https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=clinvar&id=11%2C9&rettype=variation which we can put into various online XML validators, like https://validator.w3.org/

That said valid XML, but:

> Warning No DOCTYPE found! Checking XML syntax only.
>
> The DOCTYPE Declaration was not recognized or is missing. This probably means that the Formal Public Identifier contains a spelling error, or that the Declaration is not using correct syntax, or that your XML document is not using a DOCTYPE Declaration.
>
> Validation of the document has been skipped, and a simple check of the well-formedness of the XML syntax has been performed instead.
>
> Learn how to add a doctype to your document from our FAQ, or use the validator's option to validate your XML document against a specific Document Type

Looking at the XML file confirms this - there is no DTD file declared.

So, please contact the NCBI to ask if the ``clinvar`` XML should have declared a DTD file.

If not, or in the meantime, try a non-DTD based XML parser.

**Comment by rbutleriii** [comment]
My response from eutilities was somewhat uninformative:

> Hi,
>
>Thanks for writing to us.
>
>It is not clear how up-to-date this 3rd party tool is and why it references an outside site for the dtd.
>
>You may want to take a look at the dtd here:
>ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/ 
>
>Also check the xml and readme here:
>ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ 
>
>The full xml is updated monthly.
>
>Regards,

I did some browsing on the ftp, and the structure may have changed. They also appear to be using xsd to validate now. I am a bit in over my depth here, but if I put the clinvar .xsd in the Bio/Entrez/XSD folder, will it check there?

**Comment by peterjc** [comment]
There seem to be some confusion in the communications with the NCBI - there are no 3rd party tools involved in the key questions:

* Does the Clinvar XML have a DTD? If so, why doesn't the Entrez Clinvar XML refer to it?

It appears there is no DTD file (unlike most of the databases supported by Entrez with XML output).

* Does the Clinvar XML have an XSD? If so, why doesn't the Entrez Clinvar XML refer to it?

It appears there is an XSD on the FTP site mentioned ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/clinvar_public.xsd

However even the sample XML file on the FTP site does not itself reference the XSD:
ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/sample_xml/RCV000077146.xml

So, it looks like a duplicate of #805 where there is a bioproject XSD but the XML does not reference it. As per @mdehoon's comment there  https://github.com/biopython/biopython/issues/805#issuecomment-209180898 we may need to add an XSD option to the ``Entrez.parse(...)`` and ``Entrez.read(...)`` functions?

**Comment by rbutleriii** [comment]
The ClinVar development team lead got back to me on this and said they are looking into it, as they want it to work with biopython. So perhaps future versions of Clinvar will declare the xsd? No other updates since their response to me on Feb 16th.

**Comment by peterjc** [comment]
Hello @rbutleriii was there any follow up from the ClinVar team?

**Comment by rbutleriii** [comment]
@peterjc good question. I am still using ElementTree in my code for a non-DTD option. However, they entirely rebuilt the xml for `rettype='variation'` ==> `rettype='vcv'` .
```
>>> import Bio.Entrez as Entrez
>>> Entrez.email = 'A.N.Other@example.com'
>>> result = Entrez.read(Entrez.efetch(db='clinvar', id='11,9', rettype='vcv'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rbutleriii/miniconda3/envs/R-4.0/lib/python3.8/site-packages/Bio/Entrez/__init__.py", line 506, in read
    record = handler.read(handle)
  File "/home/rbutleriii/miniconda3/envs/R-4.0/lib/python3.8/site-packages/Bio/Entrez/Parser.py", line 325, in read
    self.parser.ParseFile(handle)
  File "/home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Modules/pyexpat.c", line 407, in StartElement
  File "/home/rbutleriii/miniconda3/envs/R-4.0/lib/python3.8/site-packages/Bio/Entrez/Parser.py", line 438, in handleMissingDocumentDefinition
    raise ValueError(
ValueError: As the XML data contained neither a Document Type Definition (DTD) nor an XML Schema, Bio.Entrez is unable to parse these data. We recommend using a generic XML parser from the Python standard library instead, for example ElementTree.
``` 
Still no. Continuing to store as batches and `clinvarresult = ET.fromstring(batch)`.
```
# Utilized for batch efetch/esummary from ncbi using history server.
def batch_ncbi(query_type, query_results, id_list, **kwargs):
    count = len(id_list)

    time.sleep(0.35)
    for start in range(0, count, g.efetch_batch):
        end = min(count, start + g.efetch_batch)
        logging.info("Going to download record {} to {}"
                     .format(start + 1, end))

        logging.debug('{} run with {}'
                      .format(query_type, dict(retstart=start, **kwargs)))
        fetch_handle = http_attempts(query_type,
                                     **dict(retstart=start, **kwargs))
        # Ideally Entrez.read would import as python object, and validate with
        # ClinVar, but ClinVar currently deoesn't declare DOCTYPE for 
        # validation in their xml header. They have .xsd for this purpose, but
        # Entrez.read can't use this w/o a declaration to validate. Something
        # of a security flaw, but hopefully NCBI is in control of their xml
        # and it is injection free (hopefully...). Ultimately, the best option
        # for now is to utilize ElementTree for parsing. >Revisit<
        # data = Entrez.read(fetch_handle)
        # fetch_handle.close()
        query_results.append(fetch_handle.read())
        fetch_handle.close()
    return
```

**Comment by peterjc** [comment]
Thanks for the update, disappointing news though it was. Shall we leave this issue open for now then?

**Comment by rbutleriii** [comment]
Well, it seems like it is resource dependent, i.e.
```
result = Entrez.read(Entrez.efetch(db='pubmed', id='19304878', retmode='xml'))
result = Entrez.read(Entrez.efetch(db='nucleotide', id='EU490707', retmode='xml'))
result = Entrez.read(Entrez.efetch(db='gene', id='2', retmode='xml'))
result = Entrez.read(Entrez.efetch(db='clinvar', id='7', retmode='xml')) # returns just the uid back
```
All work, but others give the same error. Still others I cannot even figure out what `rettype`s are available, as the E-utilities handbook is very out of date. But the xml issue does not seem like something they are going to solve universally, so maybe just close it. There are notes in the tutorial on how to work around it with ET.

**Comment by peterjc** [comment]
OK, thank you.
