### ISSUE TITLE
Questions: interproscan suport

### ISSUE THREAD

**Issue by azneto** [biopython/biopython#1536]
I have to parse a xml from Inteproscan and couldn't find a python module for that. 
Should I just deal with the XML directly or is it worth to implement a biopython module + the XML parser?
If the best option is to create the module, should it be independent, like Bio/Blast, or should it integrate Bio/SearchIO?

**Comment by peterjc** [comment]
I would think integration into ``Bio.SearchIO`` would be best, what do you think @bow ?

**Comment by bow** [comment]
It does sound like a fit for SearchIO. It's also nice that the InterproScan team [has put up a proper documentation on what we can expect from the output](https://github.com/ebi-pf-team/interproscan/wiki/OutputFormats).

> Should I just deal with the XML directly or is it worth to implement a biopython module + the XML parser?

I would say it depends on your use case. Plain XML parsing seems to be the simplest and quickest way to get whatever you need from the file. But if you're interested in contributing an `interproscan-xml` parser, I would be happy to give some pointers and help along the way. This would require more work, though it would surely help others who need to parse such a file as well.

**Comment by azneto** [comment]
We're already using blast-xml, therefore interpro-xml would be a really nice solution for handling interproscan files. I'll study your code and give it a try. @bow , do you mind if I write you directly to have your feedback on my fork and discuss the progress?

**Comment by bow** [comment]
@azneto Not at all. Feel free to ping me or write to me anytime.

**Comment by azneto** [comment]
The first draft is in my fork https://github.com/azneto/biopython
There's a test file in the Tests directory.

There are some issues we need address:

- go-ref and pathway-ref: I was planning to load them as hit._id_alt and hit._description_alt but it didn't work since they must be unique even between hits and it's common to find different hits with the same GO term. Should I add a xref data structure in SearchIO._model.hit.py?
- hit database: Whereas blast has the database info for the query_result, intepro has such information available for every hit (signature-library-release). I guess I should implement a 'target' data structure for hit.py, the same way query.py has.
- models: I'm planning to ignore them for now.

**Comment by bow** [comment]
Closing this issue since the proposed changes has been merged.
