### ISSUE TITLE
Seq.complement tries to complement protein sequences when no alphabet specified

### ISSUE THREAD

**Issue by chris-rands** [biopython/biopython#1538]
### Setup

I am reporting behaviour with Biopython version, Python version, and operating
system as follows:

```$ python
Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.11.5-1-ARCH-x86_64-with-arch
>>> import Bio; print(Bio.__version__)
1.69
```

### Expected behaviour

```
>>> from Bio.Seq import Seq
>>> Seq('M').complement()
ValueError: Proteins do not have complements!
```
This would be consistant with specifying the protein alphabet:

```
>>> Seq('M', IUPAC.protein).complement()
ValueError: Proteins do not have complements!
```

### Actual behaviour

```
>>> Seq('M').complement()
Seq('K', Alphabet())
```

### Thoughts

What happens here is that without specifying the alphabet, Biopython checks for `U` or `u` implying RNA else assumes DNA: https://github.com/biopython/biopython/blob/master/Bio/Seq.py#L854

A check could also be added for proteins, because a user could accidentally input amino acids to the `complement()` method and this would pass silently changing the sequence and potentially creating a bug. The only disadvantage of this suggestion I can see is the overhead of adding another check, this was considered worthwhile for DNA/RNA but is it worth it for proteins?

*Note this also impacts `reverse_complement()` since it is called by `complement()`. Further note, these methods apply to `Seq`, `UnknownSeq`, and `MutableSeq`.

**Note, while writing this I realised a similar point  applies for `Seq.transcribe` and `Seq.back_transcribe`, which both currently accept protein sequences without an alphabet. They will *mostly* return the protein unchanged, but `transcribe()` will change `T`(Threonine) to `U` (not a valid amino acid).

***Note, this could also apply for `Seq.translate` but I think the issue is less severe here because Biopython will raise `Bio.Data.CodonTable.TranslationError` for invalid codons, which are likely to occur for protein sequences of reasonable length. 

I would be happy to start working on a pull request if my suggestion is deemed suitable, but I will certainly wait for thoughts and discussion first, thank you

**Comment by peterjc** [comment]
It is by design that ``Seq(some_string)`` and the related classes when instantiated without giving an alphabet use a generic alphabet, and let you try to use any relevant methods. In this case by using the complement method you are implying this is a nucleotide sequence.

This is the expected behaviour for taking the complement of a an ambiguous nucleotide sequence ``M`` which under the IUPAC standard means ``A`` or ``C``, thus the complement is ``T`` or ``G`` which is encoded as ``K``.

However, there are some of letters in the (extended) protein alphabet which are not valid as nucleotides, e.g. ``E``,``F``, ``I``, ``J``, ``L``, ``O``, ``P``, ``Q``, and ``Z`` (list not double checked). You could make a case for adding a check for these and raising a ``ValueError``. Currently they are silently ignored:

```python
>>> from Bio.Seq import Seq
>>> print(Seq('E').complement())
E
```

**Comment by chris-rands** [comment]
Thanks Peter, sorry `M` was a bad example, I guess the full list would be:

```
>>> from Bio.Data import IUPACData
>>> unique_aa = set(IUPACData.extended_protein_letters).difference(IUPACData.ambiguous_dna_letters)
>>> sorted(unique_aa)
['E', 'F', 'I', 'J', 'L', 'O', 'P', 'Q', 'U', 'X', 'Z']
```

Then the check would be either:

```
if any(aa in self._data for aa in unique_aa):
    raise ValueError("Proteins do not have complements!")
```

Or perhaps:

```
if not unique_aa.isdisjoint(self._data):
    raise ValueError("Proteins do not have complements!")
```

The check could be modified to handle upper and lower case. Of course the checks will impact performance for the normal case where the user inputs valid DNA/RNA.

**Comment by peterjc** [comment]
I would exclude ``U`` (valid RNA nucleotide) and ``X`` (sometimes used as an alternative to ``N`` for an unknown nucleotide), but otherwise we agree on the list.

The worry is what this extra check does to performance (specifically of the main use case of a real complement operation, performance for the exception cases can be slower).

I wonder if it would be faster to modify how we use ``maketrans`` to map problem characters to markers, and check for the marker after doing the transformation. For example, map these probable amino acids to (say) ``'!'`` and then just check ``if '!' in result`` which I expect to be quicker than checking for the long list of amino acids?

It would be worth reviewing the existing checks and if they can be sped up...

**Comment by peterjc** [comment]
IUPAC doesn't define ``X`` as a nucleotide, so it should not be included in the IUPAC based ``ambiguous_dna_letters`` and ``ambiguous_rna_letters`` -  but we've seen ``X`` in the third party data from time to time so we should tolerate it in generic sequences.

**Comment by chris-rands** [comment]
Ok thanks, but does the same logic not apply for `IUPACData.ambiguous_dna_values` and the other dictionaries that include `X`? I guess removing `X` would break compatibility though for no good reason? Might be worth a comment/warning on the code noting the asymmetry between the `letters` strings and the dictionaries keys?

These dictionaries and strings seem unchanged from the first github commit on 1 May 2000, I don't know about the history prior to that:
https://github.com/biopython/biopython/blob/f726249141aa42afbfabab72157fe0f7d820b548/Bio/Data/IUPACData.py

**Comment by peterjc** [comment]
Probably best just adding a comment next to those lines about the ``X``, I fear changing this now would have subtle side effects in scripts round the world.

**Comment by chris-rands** [comment]
Ok, I can add a comment to the code about the `X` discrepancy when I make a pull request.

I've just done a benchmark of the different checks for `Seq.complement()`, I think the conclusion from this is that your logic of modifying `maketrans` and then doing `if '!' in result` is the best way to check for protein sequences because it has a rather small impact on performance for the normal DNA/RNA cases. Therefore, perhaps I can start working on a pull request to implement in a similar way as to in my script here in the pastebin?

My suggestion of using `any()` also performs fairly ok, but using `set.disjoint()` is really bad for speed for DNA or RNA.

I didn't find a way of speeding up the current check for RNA and mixed DNA/RNA. I've not put the timings here (since I'm not suggesting changing anything), but basically the current `if ('U' in seq or 'u' in seq) and ('T' in seq or 't' in seq):` logic, although naive, is pretty fast and adds little overhead compared to having no check from my tests. Using `any(nuc in dna_string for nuc in ['U', 'u'])` also doesn't change the speed.

Thoughts? It would be worth checking over my benchmark for any mistakes (quite posisble there are some). Otherwise, I know, it's not perfect since I'm only testing a single string for each case etc. but hopefully it is good enough. The timings for mixed DNA/RNA and for proteins are likely not accurate as the ipython warnings show, but the main purpose is looking at the 'normal' DNA and RNA use cases.

---

Here is a description of each function:
`biopy_complement`-- classical biopython implementation
`emulate_biopy_complement_1`-- re-creation of classical implementation to allow modification
`emulate_biopy_complement_2`-- modified classical implementation to see if speed up achieved (it wasn't)
`check_prot_complement_1`-- Chris's `any()` approach to check for proteins
`check_prot_complement_2`-- Chris's `set.disjoint()` approach to check for proteins
`check_prot_complement_3`-- Peter's `maketrans` modified `if '!' in result` to check for proteins

Here are the results from `timeit` in Ipython (Python 3.6.1; IPython 5.3.0):

For DNA:
```
Timing for seq dna and func biopy_complement
10000 loops, best of 3: 54.9 us per loop
Timing for seq dna and func emulate_biopy_complement_1
10000 loops, best of 3: 50.8 us per loop
Timing for seq dna and func emulate_biopy_complement_2
10000 loops, best of 3: 48.5 us per loop
Timing for seq dna and func check_prot_complement_1
10000 loops, best of 3: 72.7 us per loop
Timing for seq dna and func check_prot_complement_2
1000 loops, best of 3: 844 us per loop
Timing for seq dna and func check_prot_complement_3
10000 loops, best of 3: 51.6 us per loop
```

For RNA:
```
Timing for seq rna and func biopy_complement
10000 loops, best of 3: 49.6 us per loop
Timing for seq rna and func emulate_biopy_complement_1
10000 loops, best of 3: 46 us per loop
Timing for seq rna and func emulate_biopy_complement_2
10000 loops, best of 3: 49.3 us per loop
Timing for seq rna and func check_prot_complement_1
10000 loops, best of 3: 75.8 us per loop
Timing for seq rna and func check_prot_complement_2
1000 loops, best of 3: 720 us per loop
Timing for seq rna and func check_prot_complement_3
10000 loops, best of 3: 50.2 us per loop
```

For mixed RNA and DNA:
```
Timing for seq mixed_dna_rna and func biopy_complement
100000 loops, best of 3: 4.07 us per loop
Timing for seq mixed_dna_rna and func emulate_biopy_complement_1
The slowest run took 5.61 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.27 us per loop
Timing for seq mixed_dna_rna and func emulate_biopy_complement_2
The slowest run took 5.59 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.25 us per loop
Timing for seq mixed_dna_rna and func check_prot_complement_1
10000 loops, best of 3: 25.1 us per loop
Timing for seq mixed_dna_rna and func check_prot_complement_2
1000 loops, best of 3: 728 us per loop
Timing for seq mixed_dna_rna and func check_prot_complement_3
The slowest run took 7.04 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.26 us per loop
```

For protein:
```
Timing for seq prot and func biopy_complement
100000 loops, best of 3: 12.6 us per loop
Timing for seq prot and func emulate_biopy_complement_1
100000 loops, best of 3: 10.9 us per loop
Timing for seq prot and func emulate_biopy_complement_2
100000 loops, best of 3: 10.3 us per loop
Timing for seq prot and func check_prot_complement_1
The slowest run took 5.04 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 2.16 us per loop
Timing for seq prot and func check_prot_complement_2
The slowest run took 10.79 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 816 ns per loop
Timing for seq prot and func check_prot_complement_3
100000 loops, best of 3: 13.1 us per loop
```

Here is the full code on pastebin:
https://pastebin.com/ub5NNW3N

**Comment by peterjc** [comment]
With the removal of ``Bio.Alphabet`` for Biopython 1.78 this is in a sense solved.

However, there is still the possibility of adding sanity tests on complementing letters which are not IUPAC ambiguity codes. e.g. ``E``,``F``, ``I``, ``J``, ``L``, ``O``, ``P``, ``Q``, and ``Z``(in either case) might justify raising a ``ValueError``. Currently they are still silently ignored:

```python
>>> from Bio.Seq import Seq
>>> print(Seq('E').complement())
E
```

See also discussion on #2977, where we also touched on punctation (not just ``-`` for gaps but various other symbols might be present). i.e. Should this be an allow list, or an exclude list.
