### ISSUE TITLE
Bug in AlignIO.write with phylip relaxed and phylip interleaved format and 50 character sequences

### ISSUE THREAD

**Issue by matthew-fogel** [biopython/biopython#1556]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

>>> import sys; print(sys.version)
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
>>> import Bio; print(Bio.__version__)
1.70

### Expected behaviour
When reading a fasta file with sequences that are all 50 positions (characters) long using AlignIO.read and writing this data in a file in PHYLIP relaxed or interleaved format using AlignIO.write, there should be no empty lines between each PHYLIP record.

### Actual behaviour

When reading a fasta file with sequences all 50 positions (characters) long and writing this data in a file in PHYLIP relaxed or interleaved format, empty lines are outputted after each PHYLIP record. The number of empty lines outputted after each record is equal to the number of sequences in that record plus one (for the header line).

### Steps to reproduce

1. Create a fasta file where each sequence is 50 characters long (with any number of sequences).
2. alignment = AlignIO.read(inputLocation, 'fasta')
3. Bootstrap this input using the bootstrap function from Bio.Phylo.Consensus:
    bootstrappedData = bootstrap(alignment, any_num_greater_than_one)
4. Take the bootstrapped input and use it as a parameter in the following function:
    AlignIO.write(bootstrappedData, outputLocation, 'phylip-relaxed')
OR
    AlignIO.write(bootstrappedData, outputLocation, 'phylip')

**Comment by peterjc** [comment]
Self contained example:

```python
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import MultipleSeqAlignment
a = MultipleSeqAlignment([SeqRecord(Seq("A"*50), id="Alpha"),
                          SeqRecord(Seq("T"*50), id="Tango"),
                          SeqRecord(Seq("C"*50), id="Charlie")])
print(a.format("stockholm"))
```

**Comment by peterjc** [comment]
Currently testing a fix,

```diff
$ git diff
diff --git a/Bio/AlignIO/PhylipIO.py b/Bio/AlignIO/PhylipIO.py
index 92504ba44..445d37a28 100644
--- a/Bio/AlignIO/PhylipIO.py
+++ b/Bio/AlignIO/PhylipIO.py
@@ -145,7 +145,7 @@ class PhylipWriter(SequentialAlignmentWriter):
                         break
                 handle.write("\n")
             block += 1
-            if block * 50 > length_of_seqs:
+            if block * 50 >= length_of_seqs:
                 break
             handle.write("\n")
```

**Comment by peterjc** [comment]
Fix applied. Thanks for reporting this.

**Comment by matthew-fogel** [comment]
You're welcome, thanks for applying the fix!
