### ISSUE TITLE
PDBParser, FastMMCIFParser do not support Python 3 byte file objects

### ISSUE THREAD

**Issue by schaarj** [biopython/biopython#1558]
### Setup

I am reporting a problem with Biopython version 1.70, Python version 3.6.4 , and operating
system Darwin-17.4.0-x86_64-i386-64bit as follows:

3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-17.4.0-x86_64-i386-64bit
1.70

### Expected behaviour

Biopython  (PDBParser and FastMMCIFParser) should parse file objects into a structure object but fails when the file object contains a byte stream. This worked fine in Python2 but breaks in Python3.
While we acknowledge that the urllib approach can be circumvented by using PDBList with the PDB ID,
we also use FileStorage objects from a webserver that show the same behaviour and would appreciate if Biopython could be adapted to also work with those again in Python 3.

### Steps to reproduce

```python
from urllib.request import Request, urlopen, HTTPError
from Bio.PDB import PDBParser, FastMMCIFParser

req = Request('http://www.ebi.ac.uk/pdbe/entry-files/download/1u19_updated.cif')
parser = FastMMCIFParser(QUIET=1)
parser.get_structure(structure_id='test', filename=urlopen(req))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/joerg/miniconda3/envs/prodigy/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 263, in get_structure
    self._build_structure(structure_id, handle)
  File "/Users/joerg/miniconda3/envs/prodigy/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 276, in _build_structure
    if line.startswith('_atom_site.'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by peterjc** [comment]
The parser evidently expects a string based handle, and you are giving it a binary bytes based handle. This is a fundamental distinction under Python 3, where the ``io.TextIOWrapper`` object is provided to allow you to turn a bytes handle into a string handle.

Internally Biopython uses the private ``Bio._py3k._binary_to_string_handle`` function in this context.

i.e. I think this is a documentation issue rather than a bug. Anyway, did that help?

**Comment by schaarj** [comment]
Thank you, I was aware of the issue but not that there is a function to deal with that. Thanks' for your help. I assume there are no plans to add checks for this to the parsers? In this case we'll just use the wrapper function prior to calling the parser.

**Comment by peterjc** [comment]
Thanks. I don't think we'd want to go down the route of making all the Biopython text parsers automatically accept a binary handle. There are too many nasty corner cases with encodings.

(We know this from the choice to try and to this for some of the network APIs to continue to return strings, which is still causing problems).

Is there anything in the current documentation you think could be clarified on this issue, or can we close the issue?

**Comment by schaarj** [comment]
Indeed this is probably not broadly applicable to add a check for that. In terms of documentation maybe adding a comment in the doc string of the`get_structure` function pointing to the `_binary_to_string_handle` might help. Otherwise people might also now find this thread when encountering the issue.
Either way, Thank you again for you help!

**Comment by peterjc** [comment]
We don't really intend ``Bio._py3k`` or function ``_binary_to_string_handle`` for general use - the leading underscore is a convention for private in Python.

Perhaps the ``get_structure`` docstring needs a little clarification... thanks!

**Comment by schaarj** [comment]
I was indeed wondering wether usage of a private function is the way to go, but what would be the best practice in this case? Duplicate the private function in our code or call it nevertheless and test wether it still exists/works as expected in future Biopython versions?

**Comment by peterjc** [comment]
The Biopython private function has some nasty hacks for early versions of Python 3, but is now fairly simple.

If you are just targeting Python 3 onwards, I would just import and use the standard library ``io`` code, and set the encoding as appropriate for your use case. If you still need to support Python 2, then I would make it conditional.
