### ISSUE TITLE
eLink using the history server errors over 1000 UIDs

### ISSUE THREAD

**Issue by rbutleriii** [biopython/biopython#1559]
### Setup
Python 2.7.12 ; GCC 5.4.0 20160609 ; Cpython
Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
Biopython 1.70

### Issue
I am using biopython to take an rsID list, convert to matching VariationIDs in ClinVar and then fetch those ClinVar xml files. This is essentially an ePost>eLink>eFetch, but given I want to do this with large lists, I am using the history server for the whole process. Roughly speaking, it goes:

ePost a list of UIDs from dbSNP (rsIDs), return the webenv1 and query_key1. 
(args: db='snp', id=",".join(rsid_list))

eLink to associated UIDs in ClinVar (VariationIDs), keeping this new list entirely on the history server with "cmd=neighbor_history". Return webenv2 and query_key2
(args: db='clinvar', dbfrom='snp', linkname='snp_clinvar', cmd='neighbor_history', webenv=webenv1, query_key=query_key1)

eFetch from ClinVar in batches, 
(args: db='clinvar', rettype='variation', retmax=4500, retstart=sliding_value, retwebenv=webenv2 query_key=query_key2)

Now, this works perfectly if I use a batch of 1000 or less rsids. However at 1001 and beyond, I get an error when I try to run the elink command. It ePosts fine and gives me my webenv1 and key1, but when I try to elink, I get 'Empty history ID list - nothing todo'. It does not return webenv2 or query_key2

Curiously, if I ePost 50,000 UIDs straight from ClinVar, eFetch has no problem getting batches with the webenv and query_key. 

Below is are the two functions that relate, with get_ncbi_xml receiving a list type (rsid or vid), a list of NCBI UIDs, and an empty list passed from the function above to be filled. post_ncbi handles the epost or elink setup, returning webenv and query_key:

```python
# getting xml variation files for query_results list, 
def get_ncbi_xml(file_type, id_list, query_results):
    logging.debug('{} list -> {}'.format(file_type, id_list))
    start = timing_tool()
    staging_list = []
    id_list = list(filter(None, id_list)) # costs ~ 6 sec per 50k list

    if file_type == 'rsid':
        webenv2, query_key2 = post_ncbi(file_type, 'epost', db='snp',
                                        id=",".join(id_list))
        webenv1, query_key1 = post_ncbi(file_type, 'elink', db='clinvar',
                                        webenv=webenv2, query_key=query_key2,
                                        dbfrom='snp', linkname='snp_clinvar',
                                        cmd='neighbor_history')
    elif file_type == 'vid':
        webenv1, query_key1 = post_ncbi(file_type, 'epost', db='clinvar',
                                        id=",".join(id_list))
    else:
        logging.fatal('Error: Incorrect file_type argument in get_rsid_xml ->'
                      ' {}'.format(file_type))

    batch_ncbi('efetch', staging_list, id_list, db='clinvar',
               rettype='variation', retmax=g.batch_size, webenv=webenv1,
               query_key=query_key1)
    [query_results.append(batch) for batch in staging_list] 
    stop = timing_tool()
    logging.debug('Download time: {} min, Batches run -> {}'
                  .format(((stop-start)/60), len(query_results)))
    return

# epost or elink list to e-utilities history server for target db. 
def post_ncbi(file_type, query_type, **kwargs):
    logging.debug('{} to ncbi using kwargs: {}'.format(query_type, kwargs))
    handle = getattr(Entrez, query_type)(**kwargs)
    query = Entrez.read(handle)
    logging.debug(query)
    handle.close()

    if file_type == 'rsid' and query_type == 'elink':
        webenv = query[0]['WebEnv']
        query_key = query[0]['LinkSetDbHistory'][0]['QueryKey']
    else:    
        webenv = query['WebEnv']
        query_key = query['QueryKey']

    logging.debug('returned webenv: {} and query key: {}'
                  .format(webenv, query_key))
    return webenv, query_key
```

**Comment by peterjc** [comment]
You may need to take this direct to the NCBI via the Entrez Utils email address...

**Comment by rbutleriii** [comment]
I asked the E-utils people, and they confirmed the phenomenon. Theoretically ePost->eLink is supposed to be able to handle batches of up to 5000, but it returns an empty neighbor list above 1000. Regardless, eLink will not work with larger lists, as it doesn't support retstart and retmax for batch retrieval. So, batches must happen locally, and be sent to ePost 1000 at a time for the ePost->eLink function to work.

**Comment by peterjc** [comment]
I wonder if they have documented this 1000 limit? Oh well, thanks for the information.

**Comment by rbutleriii** [comment]
The eLink documentation says 5000 for snp_clinvar elink results:
https://eutils.ncbi.nlm.nih.gov/entrez/query/static/entrezlinks.html
In this case, they confirmed it appears to be a bug, though I am unsure if that is unique to the snp_clinvar link, or if other elinks have that issue. it does seem to happen whether I use the "cmd=neighbor_history" option or download the elink directly. Both result in an empty link set.
