### ISSUE TITLE
SearchIO hmmer2-text parser incorrectly handles "end of sequence" marker if that is in a line break

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#1564]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
CPython
Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
1.71.dev0
git revision: eeaa270
```

### Expected behaviour

Parsing the hmmpfam input using `Bio.SearchIO.parse(file, 'hmmer2-text')` works.

### Actual behaviour

Parsing the hmmpfam input causes a `ValueError`:

```
Traceback (most recent call last):
  File "/home/kai/dev/libs/biopython/Tests/test_SearchIO_hmmer2_text.py", line 221, in test_hmmpfam_23_break_in_end_of_seq
    res = next(results)
  File "/home/kai/dev/libs/biopython/build/lib.linux-x86_64-3.5/Bio/SearchIO/__init__.py", line 314, in parse
    for qresult in generator:
  File "/home/kai/dev/libs/biopython/build/lib.linux-x86_64-3.5/Bio/SearchIO/HmmerIO/hmmer2_text.py", line 45, in __iter__
    for qresult in self.parse_qresult():
  File "/home/kai/dev/libs/biopython/build/lib.linux-x86_64-3.5/Bio/SearchIO/HmmerIO/hmmer2_text.py", line 126, in parse_qresult
    self.parse_hsp_alignments()
  File "/home/kai/dev/libs/biopython/build/lib.linux-x86_64-3.5/Bio/SearchIO/HmmerIO/hmmer2_text.py", line 298, in parse_hsp_alignments
    frag.query = otherseq
  File "/home/kai/dev/libs/biopython/build/lib.linux-x86_64-3.5/Bio/SearchIO/_model/hsp.py", line 849, in _query_set
    self._query = self._set_seq(value, 'query')
  File "/home/kai/dev/libs/biopython/build/lib.linux-x86_64-3.5/Bio/SearchIO/_model/hsp.py", line 817, in _set_seq
    len(seq), seq_type))
ValueError: Sequence lengths do not match. Expected: 297 (hit); found: 296 (query).
```

### Steps to reproduce

[line_parsing_break.txt](https://github.com/biopython/biopython/files/1810253/line_parsing_break.txt)

Using the above input file, run:
```python
from Bio import SearchIO
results = SearchIO.parse('line_parsing_break.txt', 'hmmer2-text')
res = next(results)
```

**Comment by kblin** [comment]
Oh, I just realised that I forgot to mention that the bug is because the removal of the end marker fails because it's in a line break, so one line has `<-` and the next line has the `*`.

Fixing this is not entirely trivial, because we rely on having the correct sequence length for building up the consensus sequence.

**Comment by kblin** [comment]
Ah, an additional problem is that in the way this one breaks, the logic in https://github.com/biopython/biopython/blob/master/Bio/SearchIO/HmmerIO/hmmer2_text.py#L262 for start marker detection triggers twice, causing the `*` of the end marker to be skipped.

**Comment by kblin** [comment]
And if I fix that, the way we parse the `otherseq` takes the trailing `-` for a gap in the sequence, instead of ignoring it as the "end coordinate".

**Comment by peterjc** [comment]
I assume there is nothing special about this query sequence and the ``PKSI-KS_N.hmm2`` model? Just bad luck with the end of the alignment falling on a line break?

Parsing your example does sound tricky...

```
hmmpfam - search one or more sequences against HMM database
HMMER 2.3.2 (Oct 2003)
Copyright (C) 1992-2003 HHMI/Washington University School of Medicine
Freely distributed under the GNU General Public License (GPL)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
HMM file:                 antismash/modules/active_site_finder/data/PKSI-KS_N.hmm2
Sequence file:            -
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query sequence: 0
Accession:      [none]
Description:    [none]

Scores for sequence family classification (score includes all domains):
Model    Description                                    Score    E-value  N 
-------- -----------                                    -----    ------- ---
PKSI-KS                                                 211.2    2.7e-64   1

Parsed for domains:
Model    Domain  seq-f seq-t    hmm-f hmm-t      score  E-value
-------- ------- ----- -----    ----- -----      -----  -------
PKSI-KS    1/1       1   275 [.     1   264 []   211.2  2.7e-64

Alignments of top-scoring domains:
PKSI-KS: domain 1 of 1, from 1 to 275: score 211.2, E = 2.7e-64
                   *->epIAIVGmacRFPGgAdspeaFWelLleGrdaisevPadRwdadafy
                        +A+VG +   PG A++++ +W+    Grd+i+evPa+Rw ++++y
           0     1    --VAVVGVGALVPG-ATDAAGYWRVVTGGRDLITEVPASRWRVEDHY 44   

                   dPdgerpGktytrwGgFLddvdlFDAaFFgISPrEAeaMDPQQRLLLEva
                   dPd+++p+kty+r+G+FL++  +FD+   g++P+   a+D  Q L+L+va
           0    45 DPDPAAPDKTYARRGAFLPE-VDFDPMAYGVPPANLPATDTSQLLALMVA 93   

                   wEALEdAGippeslrGArhgerlgsrtGVFvGasssDYgdllplrdapdd
                    + L dAG + + +           rtGV  Ga+  + +  +        
           0    94 DQVLRDAGGT-SGIDR--------DRTGVVLGAAALELLPHM-YG----- 128  

                   pedidaya...............................atGtarsilAN
                   + + +a+  + ++++ ++ + +   ++   + ++ ++++ +G   +++A+
           0   129 RSQRPAWLaglresgldeakaqavcdriaarfepwrestFPGLLGNVVAG 178  

                   RiSYffdLrGPSltVDTACSSSLVAlHlACqsLrlsGEcdmAlaGGVNLi
                   Ri+  fdL+G   t D+AC+SSL+Al  A+  L   + +d+ + GGV   
           0   179 RIANRFDLHGVNHTTDAACASSLAALSTAVGELS-LHRADLVISGGVDTG 227  

                   lsPdmfialsklgmLSPdGrCktFDarADGYvRGEGvGvVvLKRLsDA<-
                    + +mf+++sk  +LSP G C++F ++ADG+  GE+v++  LKRLsDA  
           0   228 NDIGMFLCFSKTPALSPSGDCRPFAEAADGTMLGEAVVMYALKRLSDA   275  

                   *
                    
           0     -   -    

//
```

**Comment by kblin** [comment]
Yeah, it's just the line break in the <-* marker.

**Comment by kblin** [comment]
But the `-   -` for the `otherseq` is where I'm stuck currently.
I've moved the "remove the `<-*` marker logic outside of the loop so I could work on the full sequence, and fixed the `*->` marker detection to stop eating my trailing `*`.

**Comment by kblin** [comment]
I have a hackish fix, but I don't really like it. I'll send a PR so we can hopefully find a better solution.

**Comment by peterjc** [comment]
Can you tweak the example (e.g. add/remove a few residues) so that ``<-*`` gets split as ``<`` and ``-*`` as well as how it is split in the original issue ``<-`` and ``*`` on its own line? It seems worth testing that corner case as well.

**Comment by kblin** [comment]
I'll give that a shot, yes. But I think the fix I proposed should handle both.

**Comment by kblin** [comment]
This is a bit tricky to get from the actual tool, as the full profile matches. But for a fake match I just added manually to test this works.

**Comment by kblin** [comment]
Updated the PR with my artificial test case.

**Comment by bow** [comment]
@kblin, thanks for the report + fix! This looks good to me, I was going to suggest adding arbitrary breaks for the end marker, but I see this is already covered :+1:.

If there are no further comments/objections, I'll merge this today no sooner than 16.00 CET.

**Comment by bow** [comment]
Closing this issue since #1565 is merged.
