### ISSUE TITLE
Error in biopython parsing genbank info

### ISSUE THREAD

**Issue by balathl** [biopython/biopython#1568]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

```
$ python
Python 2.7.13 (default, Mar  9 2017, 09:27:58)
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
2.7.13 (default, Mar  9 2017, 09:27:58)
[GCC 5.4.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-2.6.32-642.15.1.el6.x86_64-x86_64-with-centos-6.9-Final
>>> import Bio; print(Bio.__version__)
1.70
```

### Expected behaviour

getting the output of isolation source information

```
Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
```

### Actual behaviour

```
Loading application python-2.7.13 environment with needed modules
Activating virtualenv from /homeappl/home/bjam/appl_taito/.my_py_venv_2.7.13/bin/activate
/appl/opt/lmod/lmod/init/bash: line 52: deactivate: command not found
Traceback (most recent call last):
  File "try_xml_isolation_source_NA_test.py", line 13, in <module>
    xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 180, in efetch
    return _open(cgi, variables, post=post)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 527, in _open
    handle = _urlopen(cgi)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 97] Address family not supported by protocol>
```

### Steps to reproduce

```
$ cat try_xml_isolation_source_NA_test.py
#!usr/bin/python
import sys
import Bio
import time
import xml.etree.ElementTree
from Bio import Entrez
from urllib2 import HTTPError
Entrez.email = "balamuralikrish@gmail.com"
test = open(sys.argv[1],"r")
for i in test:
#   print i
   try:
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   except HTTPError:
      time.sleep(60)
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   for record in Entrez.read(xml):
      gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
      for qualifier in gb_quals:
         if qualifier["GBQualifier_name"] == "isolation_source":
            print qualifier["GBQualifier_value"]
            break
      else:
         print "NA"
      time.sleep(15)
xml.close()

$ cat array.job.1-100.sh
#!/bin/bash -l
#SBATCH -J array_job
#SBATCH -o array_job_out_%A_%a.txt
#SBATCH -e array_job_err_%A_%a.txt
#SBATCH -t 02:00:00
#SBATCH --mem-per-cpu=4000
#SBATCH --array=1-100
#SBATCH -n 1
#SBATCH -p serial
cd /wrk/bjam/HNO/new_run_parsing_split100/4000to7033
module load biopython-env/2.7.13
python try_xml_isolation_source_NA_test.py piece_"$SLURM_ARRAY_TASK_ID" > gb.list.parse.results.isolation_source_"$SLURM_ARRAY_TASK_ID".txt

Running as array jobs as:

sbatch array.job.1-100.sh
```

most of the jobs giving this error and some suceed though. I wanted to get output for all jobs in order to avoid picking failed jobs and rerun. I like to know the reason why this error comes from Biopython so that i can improve the code.

Any help is appreciated!

Thanks in advance.

Bala

**Comment by peterjc** [comment]
I've never seen ``Address family not supported by protocol`` with Entrez before, a quick Google suggest something on your network's setting with IPv6 might be important.

Anyway, catching the exception (``urllib2.URLError`` is presumably a subclass of ``urllib2.HTTPError``) seems the most sensible action here. You could go further and have a retry loop (say 3 attempts)?

**Comment by balathl** [comment]
I am working on CSC Taito environment which is a computing cluster. I will ask the admin to check the Network setting.

Do you mean looping exception block three times as below??

try:
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   except HTTPError:
      time.sleep(60)
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   except HTTPError:
      time.sleep(60)
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   except HTTPError:
      time.sleep(60)
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")

Thanks for your reply!

Bala

**Comment by peterjc** [comment]
I meat using a ``try/except`` inside a ``for`` loop. e.g. http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec:entrez-webenv in the Tutorial

**Comment by balathl** [comment]
Hi,

Following the implementation, i also got a different error. so, i will post it in the same thread here:

python try_xml_isolation_source_NA.py piece_1 > gb.list.parse.results.isolation_source_1.txt
Traceback (most recent call last):
  File "try_xml_isolation_source_NA.py", line 26, in <module>
    xml.close()
AttributeError: 'module' object has no attribute 'close'


#####cat try_xml_isolation_source_NA.py#####
#!usr/bin/python
import sys
import Bio
import time
import xml.etree.ElementTree
from Bio import Entrez
from urllib2 import HTTPError
Entrez.email = "balamuralikrish@gmail.com"
batch_size = 3
test = open(sys.argv[1],"r")
for i in test:
   try:	
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   except HTTPError:
      time.sleep(15)
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   for record in Entrez.read(xml):
      gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
      for qualifier in gb_quals:
         if qualifier["GBQualifier_name"] == "isolation_source":
            print qualifier["GBQualifier_value"]
            break
      else:
         print "NA"
      time.sleep(1)         
xml.close()
#################
##### cat piece_1 ####
HG421326
HG421327
HG421328
HG421329
HG421334
HG421335
HG421336
HG421337
HG421338
HG421345
HG421348
HG421349
HG421351
HG421352
HG421353
HG421359
HG421366
HG421370
HG421375
HG421377
HG421379
HG421380
HG421382
HG421387
HG421389
HG421390
HG421393
HG421399
HG421406
HG423398
HG423434
HG424426
HG424633
HG425472
HG425484
HG425489
HG425491
HG425496
HG425502
HG425504
HG425509
HG425515
HG425526
HG425551
HG428642
HG428643
HG428644
HG428646
HG428647
HG428648
HG428649
HG428650
HG428651
HG428652
HG428653
HG428657
HG428659
HG428660
HG428662
HG428663
HG428664
HG428666
HG428670
HG428671
HG428672
HG428673
HG428674
HG428676
HG428677
HG428754
HG428755
HG514499
HG515399
HG515539
HG518322
HG518323
HG529983
HG529984
HG529985
HG529989
HG529995
HG529998
HG530068
HG530069
HG530133
HG530134
HG530135
HG530273
HG530280
HG530283
HG530286
HG530287
HG530671
HG530672
HG530674
HG530675
HG530676
HG530678
HG531858
HG531910
HG670306

Hope you can reproduce the error! The environment and versions were same in the previous discussion.

Any help is appreciated!

Bala

**Comment by peterjc** [comment]
As written, the line ``xml.close()`` should be indented to be part of the for loop. That might explain the error, as there is also an XML module imported...

**Comment by balathl** [comment]
Hi,

Thanks for the comment! It does silent the error and run was finished. But the output looks empty. I am wondering why...

$ python try_xml_isolation_source_NA_indented.py piece_1 > gb.list.parse.results.isolation_source_1.txt
(.my_py_venv_2.7.13) [bjam@c308 new_run_parsing_split100]$ wc -l gb.list.parse.results.isolation_source_1.txt
0 gb.list.parse.results.isolation_source_1.txt
(.my_py_venv_2.7.13) [bjam@c308 new_run_parsing_split100]$ cat try_xml_isolation_source_NA_indented.py
#!usr/bin/python
import sys
import Bio
import time
import xml.etree.ElementTree
from Bio import Entrez
from urllib2 import HTTPError
Entrez.email = "balamuralikrish@gmail.com"
batch_size = 3
test = open(sys.argv[1],"r")
for i in test:
   try:	
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   except HTTPError:
      time.sleep(15)
      xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   for record in Entrez.read(xml):
      gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
      for qualifier in gb_quals:
         if qualifier["GBQualifier_name"] == "isolation_source":
            print qualifier["GBQualifier_value"]
            break
      else:
         print "NA"
      time.sleep(1)         
      xml.close()


I am sorry if this is very obvious. Hope you can still help what was the problem.

Bala

**Comment by peterjc** [comment]
I am far more familiar with parsing the nucleotide records in the plain text GenBank format using ``Bio.SeqIO``, so using https://www.ncbi.nlm.nih.gov/nuccore/HG421326 as an example the information you want is in the source feature (usually there is only one source feature, and they are the first features in the table):

```
FEATURES             Location/Qualifiers
     source          1..909
                     /organism="uncultured bacterium"
                     /mol_type="genomic DNA"
                     /isolation_source="copper contaminated riparian soil"
                     /db_xref="taxon:77133"
                     /clone="Cu-nanoparticle_7 microcosm enrichment clone
                     3fb-IIIA5"
                     /environmental_sample
```

Using this approach:

```python
from Bio import SeqIO
from Bio import Entrez

def isolation_source_for_acc(accession):
    # TODO - Cache the file locally rather than downloading it each time?
    with Entrez.efetch(db="nucleotide", id=accession, rettype="gb", retmode="text") as handle:
        record = SeqIO.read(handle, "genbank")
    for feature in record.features:
        if feature.type == "source" and "isolation_source" in feature.qualifiers:
            return feature.qualifiers["isolation_source"][0]
    return "NA"

print(isolation_source_for_acc("HG421326"))
```

**Comment by peterjc** [comment]
However, your XML approach should work fine too - this works for example:

```python
def isolation_source_for_acc(accession):
    with Entrez.efetch(db="nucleotide", id=accession, rettype="gb", retmode="xml") as handle:
        for record in Entrez.read(xml):
            gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
            for qualifier in gb_quals:
                if qualifier["GBQualifier_name"] == "isolation_source":
                    return qualifier["GBQualifier_value"]
    return "NA"
```

**Comment by peterjc** [comment]
I suspect something is wrong with your input data, this works too - based heavily on your scripts:

```
#!usr/bin/python
from __future__ import print_function
import sys
import Bio
import time
import xml.etree.ElementTree
from Bio import Entrez
from urllib2 import HTTPError
Entrez.email = "balamuralikrish@gmail.com"
batch_size = 3
for i in sys.argv[1:]:
   try:
       xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   except HTTPError:
       time.sleep(15)
       xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
   for record in Entrez.read(xml):
       gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
       for qualifier in gb_quals:
           if qualifier["GBQualifier_name"] == "isolation_source":
               print(i, qualifier["GBQualifier_value"])
               break
       else:
           print(i, "NA")
       time.sleep(1)         
   xml.close()
```

Note the ``xml.close()`` should be indented one level only!

Used as follows under Python 2:

```
$ python try_xml_isolation_source_NA_indented.py HG421326 HG530069
HG421326 copper contaminated riparian soil
HG530069 NA
```

**Comment by balathl** [comment]
Thanks Peter! I will closely check my input files as well.

Bala

**Comment by peterjc** [comment]
You must be very close - hopefully you can figure it out from here.

**Comment by balathl** [comment]
I found difficulty with genbank ids (for example, this one "HG670306") which has long display due to huge sequence record.

The error that i get is below:

Traceback (most recent call last):
  File "new_script.py", line 18, in <module>
    for record in Entrez.read(xml):
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 453, in read
    record = handler.read(handle)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 233, in read
    self.parser.ParseFile(handle)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/httplib.py", line 642, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/appl/opt/python/2.7.13-gcc540-shared/lib/python2.7/httplib.py", line 690, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(0 bytes read, 1126 more expected)


Is there anything i can do to still get the results?

The code that i used is:

    #!usr/bin/python
    from __future__ import print_function
    import sys
    import Bio
    import time
    import xml.etree.ElementTree
    from Bio import Entrez
    from urllib2 import HTTPError
    Entrez.email = "balamuralikrish@gmail.com"
    batch_size = 3
    test = open(sys.argv[1],"r")
    for i in test:
       try:
           xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
       except HTTPError:
           time.sleep(20)
           xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml")
       for record in Entrez.read(xml):
           gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
           for qualifier in gb_quals:
               if qualifier["GBQualifier_name"] == "isolation_source":
                   print(qualifier["GBQualifier_value"])
                   break
           else:
               print("NA")
           time.sleep(3)         
       xml.close()

**Comment by peterjc** [comment]
The nature of NCBI Entrez is this is an online API, and there will be network issues. Personally I would fetch the full data inside the try/except repeat structure, save the complete XML file to disk for reuse, and then parse the file. This will also make repeating your analysis trivially fast as it won't need to go online again.

**Comment by balathl** [comment]
Isnt it Entrez.efetch() fetch the full record and save it in xml in the above code inside the Try/except repeat block?? In My understanding, the steps You mentioned is What I Did. Please correct me If I am wrong.

Bala

**Comment by peterjc** [comment]
Ah, there is a subtly here about how handles work. In ``xml = Entrez.efetch(...)`` or the standard ``open(...)`` function all you do is open the handle. The data gets read in via the ``xml.read()`` method or similar (in this case done by the ``Entrez.read(xml)``` function. The handle is being closed here by ``xml.close()`` at the end of each loop.

Something like this reads all the data inside the try/except, and then turns the big string of XML data back into a handle using ``StringIO`` (as written this is Python 2 only):

```
#!usr/bin/env python
from __future__ import print_function
import sys
import Bio
import time
import xml.etree.ElementTree
from StringIO import StringIO  # Python 2
from Bio import Entrez
from urllib2 import HTTPError  # Python 2

Entrez.email = "balamuralikrish@gmail.com"
batch_size = 3
for i in sys.argv[1:]:
   try:
       xml_data = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml").read()
   except HTTPError:
       time.sleep(15)
       xml_data = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml").read()
   for record in Entrez.read(StringIO(xml_data)):
       gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
       for qualifier in gb_quals:
           if qualifier["GBQualifier_name"] == "isolation_source":
               print(i, qualifier["GBQualifier_value"])
               break
       else:
           print(i, "NA")
       time.sleep(1) 
```

**Comment by balathl** [comment]
I tried the solution and it did not solve the problem of getting stuck at "HG670306". The code got stuck when it reaches this specific id.

    #!usr/bin/python
    from __future__ import print_function
    import sys
    import Bio
    import time
    import xml.etree.ElementTree
    from Bio import Entrez
    from urllib2 import HTTPError
    from StringIO import StringIO
    Entrez.email = "balamuralikrish@gmail.com"
    batch_size = 3
    test = open(sys.argv[1],"r")
    for i in test:
       try:
           xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml").read()
       except HTTPError:
           time.sleep(20)
           xml = Entrez.efetch(db="nucleotide", id=i, rettype="gb", retmode="xml").read()
       for record in Entrez.read(StringIO(xml)):
           gb_quals = record["GBSeq_feature-table"][0]["GBFeature_quals"]
           for qualifier in gb_quals:
               if qualifier["GBQualifier_name"] == "isolation_source":
                   print(qualifier["GBQualifier_value"])
                   break
           else:
               print("NA")
           time.sleep(3)

Although this is not making the error "httplib.IncompleteRead: IncompleteRead(0 bytes read, 1126 more expected)", but causing another problem of not coming out of the run with not output for that specific id. Other ids output were fine.

I think the solution did not able to address the problem for "HG670306". Hope there might be some solution.

Bala

**Comment by peterjc** [comment]
Do you mean the code seems to get stuck for HG670306? No error, not output, waiting for network? Probably it would have given a time out exception eventually. This record worked for me just now.

What time of day are you running this? During USA office hours the service is much busier and that is best avoided if possible.

**Comment by balathl** [comment]
Ok! That might be the reason and I will try in non-USA working hours. Yes, the id waiting for network for more than many hours and I thought there is some problem.

Thanks for your support!

Bala

**Comment by peterjc** [comment]
I think/hope everything is OK for now, and on that basis am closing this issue.
