### ISSUE TITLE
Support mmCIF input in SeqIO

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1573]
As documented on http://biopython.org/wiki/SeqIO within ``Bio.SeqIO`` we support input formats ``pdb-atom`` and ``pdb-seqres`` using ``Bio.PDB`` to pull protein sequences out of structure files.

Can we do the same with mmCIF files which are replacing the old PDB plain text format?

**Comment by StefansM** [comment]
If nobody is working on this, I'm happy to give it a go. It'll get put on my to-do FIFO, so it might take a little while.

**Comment by peterjc** [comment]
Sure - and if anyone else is interested, please get in touch in case first to avoid duplication of effort.

**Comment by peterjc** [comment]
This is now implemented via #1635, it just needs a minor update to the webpage to say this will be in Biopython 1.73 and we can close this issue:

https://github.com/biopython/biopython.github.io/blob/master/wiki/SeqIO.md

**Comment by jvfe** [comment]
I believe this can be closed, @peterjc

**Comment by peterjc** [comment]
Yes, well spotted. Thanks.
