### ISSUE TITLE
Bug in Bio.pairwise2.align.localxx when sequences are given with list of strings with more than 1 character

### ISSUE THREAD

**Issue by bougui505** [biopython/biopython#1574]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118]
CPython
Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
1.68
```

### Expected behaviour

The  Bio.pairwise2.align.localdd when sequences are given with list of strings with more than 1 character should return a correct alignment like:

Minimum example:

```
from Bio import pairwise2
seq1 = [str(e) for e in range(20)]
seq2 = [str(e) for e in range(10, 30)]
print pairwise2.align.localxx(seq1, seq2, gap_char=['-'])
```

should return but DO NOT:

`[(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29'], 10.0, 10, 30)]`

### Actual behaviour

The actual code below

```
from Bio import pairwise2
seq1 = [str(e) for e in range(20)]
seq2 = [str(e) for e in range(10, 30)]
print pairwise2.align.localxx(seq1, seq2, gap_char=['-'])
```
returns:

`[(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '1', '1', '2', '1', '3', '1', '4', '1', '5', '1', '6', '1', '7', '1', '8', '1', '9', '1', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '0', '1', '1', '1', '2', '1', '3', '1', '4', '1', '5', '1', '6', '1', '7', '1', '8', '1', '9', '1', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29'], 10.0, 10, 30)]`

### Steps to reproduce

Minimum example:

```
from Bio import pairwise2
seq1 = [str(e) for e in range(20)]
seq2 = [str(e) for e in range(10, 30)]
print pairwise2.align.localxx(seq1, seq2, gap_char=['-'])
```

**Comment by bougui505** [comment]
Same in Biopython 1.70

**Comment by MarkusPiotrowski** [comment]
@bougui505 Is there any chance to test this with Biopython 1.67? There was a major re-write of the module in 1.68 and I'm curious if this bug was there before.

**Comment by bougui505** [comment]
@MarkusPiotrowski It works with Biopython 1.67.
```python
import Bio
Bio.__version__
```
```
'1.67'
```
```python
from Bio import pairwise2
seq1 = [str(e) for e in range(20)]
seq2 = [str(e) for e in range(10, 30)]
print pairwise2.align.localxx(seq1, seq2, gap_char=['-'])
```
```
[(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29'], 10.0, 10, 20)]
```

**Comment by MarkusPiotrowski** [comment]
@bougui505 Thank you.

I'm sorry, but while I can reproduce the error in ```Biopython 1.68``` (and I can recall that I did something wrong in this version regarding list input) it works fine for me in ```1.70```:

```python
import Bio
from Bio import pairwise2

print(Bio.__version__)

seq1 = [str(e) for e in range(20)]
seq2 = [str(e) for e in range(10, 30)]
print pairwise2.align.localxx(seq1, seq2, gap_char=['-'])
```
gives

```python
1.70
[(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29'], 10.0, 10, 20)]
>>> 
```

**Comment by bougui505** [comment]
@MarkusPiotrowski Sorry Markus, my fault for version 1.70, I should have been mistaken with the virtualenv I created for the tests. So the biopython package from Debian (version 1.68) is buggy. Thanks for your help.

**Comment by MarkusPiotrowski** [comment]
OK, thank you. So I'm going to close this now.

**Comment by mdehoon** [comment]
@bougui505 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
