### ISSUE TITLE
DSSP support for mmCIF, perhaps not completely resolved?

### ISSUE THREAD

**Issue by bwllc** [biopython/biopython#1581]
Relevant link from 2015: https://github.com/biopython/biopython/issues/459

I am reporting a problem with Biopython version, Python version, and operating system as follows:

3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
CPython
Linux-4.13.0-37-generic-x86_64-with-Ubuntu-17.10-artful
1.70

It is expected that Bio.PDB.DSSP supports the processing of all mmCIF files from the Protein Data Bank.

I have tried two files thus far, which were retrieved directly from the Protein Data Bank.  One file succeeded, but another failed.  The two files are attached.  Github is making me add a .txt extension to the files in order to upload them.  Please remove the .txt extension before trying my test below.

Here's a minimal example of the success, and the failure.  Bio.PDB.DSSP is looking for a Chain named "A" in the second file, despite the fact that only a Chain named "E" exists.

```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from Bio.PDB.MMCIFParser import MMCIFParser
>>> from Bio.PDB import DSSP
>>> parser = MMCIFParser()
>>> 
>>> path = "1a6l.cif"
>>> structure = parser.get_structure("tmp", path)
>>> model = list(structure.get_models())
>>> chain = list(model[0].get_chains())
>>> structure, model, chain
(<Structure id=tmp>, [<Model id=0>], [<Chain id=A>])
>>> output = DSSP(model[0], path) 
>>> 
>>> path = "1a7g.cif"
>>> structure = parser.get_structure("tmp", path)
>>> model = list(structure.get_models())
>>> chain = list(model[0].get_chains())
>>> structure, model, chain
(<Structure id=tmp>, [<Model id=0>], [<Chain id=E>])
>>> output = DSSP(model[0], path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/Bio/PDB/DSSP.py", line 381, in __init__
    chain = model[chain_id]
  File "/usr/lib/python3/dist-packages/Bio/PDB/Entity.py", line 40, in __getitem__
    return self.child_dict[id]
KeyError: 'A'

[1a6l.cif.txt](https://github.com/biopython/biopython/files/1846561/1a6l.cif.txt)
[1a7g.cif.txt](https://github.com/biopython/biopython/files/1846562/1a7g.cif.txt)

```

**Comment by bwllc** [comment]
Followup: I attempted to process an additional 100 or so mmCIF files.  Most were successfully handled by DSSP.  I have obtained two more examples of files which generate DSSP KeyErrors as shown for 1a7g.cif, above.  In both cases, the Structures contain single Models, which in turn contain single Chains, but as before, these Chains are not named "A".  I am appending these two files to the discussion below.

[1f6l.cif.txt](https://github.com/biopython/biopython/files/1846686/1f6l.cif.txt)
[1wwb.cif.txt](https://github.com/biopython/biopython/files/1846689/1wwb.cif.txt)

**Comment by JoaoRodrigues** [comment]
Hi there,

This is because of a mismatch between PDB and mmCIF chain identifiers. Could you try updating to the latest github version of Biopython? We changed the behaviour of the mmCIF parser a while back (see issue #779) to address this exact issue.

**Comment by bwllc** [comment]
Thank you for your reply, JoaoRodrigues!  You work for Michael Levitt?  Ask him whether he remembers John Ladasky, and please say hello for me.

The Ubuntu 17.10 repository handed me Biopython 1.70.  As you suggested, I downloaded and installed the ZIP file which is available on GitHub.  My `Bio.__version__ `now reads `1.71.dev0`.  Unfortunately, I still get the same KeyError when I attempt to process `1a6l.cif`.

**Comment by peterjc** [comment]
Thanks - ``1.71.dev0`` means a pre-release of what will one day be Biopython 1.71, so you did manage to install a recent copy of Biopython from github.

Hmm. So the problem is still there. But on the bright side, you have provided a test case 👍

**Comment by jgreener64** [comment]
So it seems DSSP uses the `label_asym_id` field to define the chain in the output. Since https://github.com/biopython/biopython/issues/779, Bio.PDB has used the `auth_asym_id` to give better correspondence between PDB and mmCIF files. I think that is the issue here.

There could be a workaround given that the function is given the mmCIF filename: determine if mmCIF is being used, if so read in the `MMCIFDict`, read in the DSSP dict as usual, convert from `label_asym_id` to `auth_asym_id` using the `MMCIFDict`, proceed as usual.

**Comment by jgreener64** [comment]
See the linked PR for a possible fix.
