### ISSUE TITLE
suggestion: SearchIO.parse directly get column header from "outfmt 7" blast-tab rather than ask user to provide

### ISSUE THREAD

**Issue by wpwupingwp** [biopython/biopython#1591]
### Setup
Python: 3.6.5rc1 (default, Mar 14 2018, 06:54:23) \n[GCC 7.3.0]
Platform: Linux-4.9.0-3-amd64-x86_64-with-debian-buster-sid
Biopython: 1.70

### Expected behaviour
According to the document of Bio.SearchIO,
`
Note that the 'fields' keyword argument will be ignored if the parsed file is commented. Commented files have their column ordering stated explicitly in the file, so there is no need to specify it again in SearchIO.
`
My understand is, if I use 
`'-outfmt "7  qseqid sseqid nident mismatch score qstart qend sstart send"' `
in blastn, which generated comment line in tab file, then I can directly use 
`SearchIO.parse(tab_file, 'blast-tab')`
But it still use "std" fields to parse my blast-tab  file,  so I got AssertionError:

> AssertionError: Expected 12 columns, found: 9

My question is, what is "commented" file according to the documents?

### Steps to reproduce
python  file:

```
#!/usr/bin/python3

from Bio import SearchIO

fmt = 'qseqid sseqid nident mismatch score qstart qend sstart send'
print('with fields')
a = SearchIO.parse('wrong.tab', 'blast-tab', fields=fmt)
print(list(a))
print()
print('without fields')
b = SearchIO.parse('wrong.tab', 'blast-tab')
print(list(b))
```
tab file:
```
# BLASTN 2.7.1+
# Query: AvgMidLocation(0)-Tm(48.84)-Coverage(0.00%)-SumBitScore(0)-Start(994)-End(1013)
# Database: /tmp/tmpyurpxrp1
# Fields: query id, subject id, identical, mismatches, score, q. start, q. end, s. start, s. end
# 2 hits found
a	b	20	0	40	1	20	486	505
c	d	20	0	40	1	20	477	496
```

**Comment by wpwupingwp** [comment]
In https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py,
```
272            if 'BLAST' in self.line and 'processed' not in self.line:
273                program_line = self.line[len(' #'):].split(' ')
```
I think "len(' #')" may be a typo of "len('# ')", although  they have same effect in here :)

**Comment by peterjc** [comment]
This means ``-outfmt 7`` as per the NCBI command line help, e.g. from a slightly old copy of ``blastn``:

```
 *** Formatting options
 -outfmt <String>
   alignment view options:
     0 = pairwise,
     1 = query-anchored showing identities,
     2 = query-anchored no identities,
     3 = flat query-anchored, show identities,
     4 = flat query-anchored, no identities,
     5 = XML Blast output,
     6 = tabular,
     7 = tabular with comment lines,
     8 = Text ASN.1,
     9 = Binary ASN.1,
    10 = Comma-separated values,
    11 = BLAST archive format (ASN.1) 
    12 = JSON Seqalign output
```

**Comment by wpwupingwp** [comment]
But here it cannot correctly parse a commented blast tab without providing "fields"

**Comment by peterjc** [comment]
That does look like a bug - unless meant just ``-outfmt 7`` with the standard 12 columns?

Note that columns 1 and 2 have changed slightly in recent BLAST+ releases.

**Comment by bow** [comment]
@wpwupingwp Aha, good catch on `self.line[len(' #'):]`. The correct one is indeed `self.line[len('# '):]`, but it works either way since we are not using the string per se, but rather its length.

As for your error, the standard `blast-tab` format for commented files expects [12 columns](https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py#L133), which is what you would get when you do `-outfmt 7` without specifying any columns explicitly. These columns, as you can see, is the different from the ones you defined in `fmt`. And so, in this case, the parser is behaving as expected. It only accepts the file when you supply the fields.

The 12 columns selection was based on BLAST version 2.2.26+, which may be different in recent BLAST version, as @peterjc mentioned.

**Comment by wpwupingwp** [comment]
I found
```
307    def _parse_fields_line(self):
308        """Return column short names line from 'Fields' comment line (PRIVATE)."""
309       raw_field_str = self.line[len('# Fields: '):]
310       long_fields = raw_field_str.split(', ')
311       fields = [_LONG_SHORT_MAP[long_name] for long_name in long_fields]
312       return self._prep_fields(fields)
```
in https://github.com/biopython/biopython/blob/master/Bio/SearchIO/BlastIO/blast_tab.py
Since it already get field info from blast-tab file, as a suggestion, parser could directly use this rather than ask user to provide it.

**Comment by peterjc** [comment]
I agree - it would be ideal if with commented tsv, SearchIO could infer the columns from the provided headers. Shall we retitle this issue to focus on that as an enhancement?

Note we'd have to map the "human readable" column names to the column names as used in the command line API, i.e.

```
# Fields: query acc.ver, subject acc.ver, % identity, alignment length, mismatches, gap opens, q. start, q. end, s. start, s. end, evalue, bit score
```

becomes:

```
qaccver saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore
```

This would then cope with the three variants thus far on which 12 columns are used by default.

**Comment by bow** [comment]
@wpwupingwp Indeed, I should also add to my previous comment that you can (and I think probably should) specify `comments=True` when parsing tabular commented fields. The parser does indeed already try to pull the existing field names when it knows that its parsing a commented tabular file.

**Comment by bow** [comment]
@wpwupingwp Any further comments on this? As I mentioned earlier:

> The parser does indeed already try to pull the existing field names when it knows that its parsing a commented tabular file.

Does specifying `comments=True` solve your issue?

**Comment by wpwupingwp** [comment]
Yes

**Comment by bow** [comment]
Great. Ok, then I'm closing this issue.
