### ISSUE TITLE
Fill in missing licence headers in Python files

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1609]
This is a spin out from #898 (dual licensing our code base) where I wrote the following script to try to classify our Python code as using the old licence or the new dual licensing terms:

```python
import sys
import os

# One space or two after a full stop? Or avoid this argument with a line break!

old = """# This code is part of the Biopython distribution and governed by its
# license.  Please see the LICENSE file that should have been included
# as part of this package.
"""

old2 = """# This code is part of the Biopython distribution and governed by its
# license. Please see the LICENSE file that should have been included
# as part of this package.
"""

old3 = """# All rights reserved.  This code is part of the Biopython
# distribution and governed by its license.
# Please see the LICENSE file that should have been included as part
# of this package.
"""

new = """# This file is part of the Biopython distribution and governed by your
# choice of the "Biopython License Agreement" or the "BSD 3-Clause License".
# Please see the LICENSE file that should have been included as part of this
# package.
"""

count_total = 0
count_old = 0
count_new = 0

def count(filename):
    global count_total, count_old, count_new
    count_total += 1
    with open(filename) as in_handle:
        text = in_handle.read(1000)
        if old in text or old2 in text or old3 in text:
            count_old += 1
            assert new not in text
            #print("OLD - %s" % filename)
        elif new in text:
            count_new += 1
            #print("New - %s" % filename)
        else:
            print("??? - %s" % filename)

for path in sys.argv[1:]:
    print("Walking %s" % path)
    for (dirpath, dirnames, filenames) in os.walk(path):
        for f in filenames:
            if f.endswith(".py"):
                count(os.path.join(dirpath, f))
print("%i old, %i new, %i other, %i in total"
      % (count_old,
         count_new,
         count_total - count_old - count_new,
         count_total))
```

e.g.

```
$ python count_license.py Bio BioSQL
Walking Bio
??? - Bio/codonalign/chisq.py
??? - Bio/GA/Crossover/__init__.py
??? - Bio/GA/Mutation/__init__.py
??? - Bio/GA/Repair/__init__.py
??? - Bio/GA/Selection/__init__.py
??? - Bio/Graphics/KGML_vis.py
??? - Bio/Pathway/Rep/__init__.py
??? - Bio/PDB/parse_pdb_header.py
??? - Bio/PDB/PDBList.py
??? - Bio/PDB/Vector.py
??? - Bio/SearchIO/InterproscanIO/__init__.py
??? - Bio/SeqIO/SeqXmlIO.py
??? - Bio/Sequencing/Applications/_samtools.py
??? - Bio/SeqUtils/CodonUsageIndices.py
??? - Bio/SeqUtils/IsoelectricPoint.py
??? - Bio/SeqUtils/ProtParam.py
??? - Bio/SeqUtils/ProtParamData.py
Walking BioSQL
285 old, 39 new, 17 other, 341 in total
```

and

```
$ python count_license.py Tests/
Walking Tests/
??? - Tests/requires_internet.py
??? - Tests/requires_wise.py
??? - Tests/test_Affy.py
??? - Tests/test_GACrossover.py
??? - Tests/test_GAMutation.py
??? - Tests/test_GAOrganism.py
??? - Tests/test_GAQueens.py
??? - Tests/test_GARepair.py
??? - Tests/test_HMMCasino.py
??? - Tests/test_HMMGeneral.py
??? - Tests/test_NaiveBayes.py
??? - Tests/test_SearchIO_interproscan_xml.py
??? - Tests/test_translate.py
187 old, 11 new, 13 other, 211 in total
```

All these unclassified entries would need reviewing as part of moving to a dual license for the entire codebase (#898). In most cases, inserting the standard license text would suffice:

```
# This code is part of the Biopython distribution and governed by its
# license.  Please see the LICENSE file that should have been included
# as part of this package.
```

Likewise we should check our C files too.

**Comment by peterjc** [comment]
Commit 0cd176056d077bf18fc91445e9172b904c31c96a handled another special case where there had been a rename in the file history.

**Comment by peterjc** [comment]
For interest sake, Biopython 1.72 will be the biggest step forward in our dual licensing effort thus far:

```
$ git checkout master && python count_license.py Bio BioSQL
...
269 old, 57 new, 15 other, 341 in total
$ git checkout biopython-171 && python count_license.py Bio BioSQL
...
309 old, 7 new, 26 other, 342 in total
$ git checkout biopython-170 && python count_license.py Bio BioSQL
...
305 old, 6 new, 27 other, 338 in total
$ git checkout biopython-169 && python count_license.py Bio BioSQL
...
312 old, 5 new, 31 other, 348 in total
$ git checkout biopython-168 && python count_license.py Bio BioSQL
...
316 old, 0 new, 32 other, 348 in total
```

Leaving this open to deal with the 15 Python scripts where the license was not automatically determined (some will be trivial white space differences, others are more interesting).

**Comment by Amrithasuresh** [comment]
@peterjc  Shall I do this? Do I need to add the mentioned license message to the mentioned files?

Thank you

**Comment by peterjc** [comment]
These files need examining one by one to see if there is anything special about the original contribution and/or licensing, and if not, add our (old) standard wording:

```python
# This code is part of the Biopython distribution and governed by its
# license.  Please see the LICENSE file that should have been included
# as part of this package.
```

We would also ideally credit the original author with a copyright line, again following our typical layout.

**Comment by Amrithasuresh** [comment]
@peterjc I have few queries here

For example the code has following lines at the start in this [file](https://github.com/biopython/biopython/blob/master/Bio/Affy/CelFile.py)


```
# Copyright 2004 by Harry Zuzan. All rights reserved.
# Copyright 2016 by Adam Kurkiewicz. All rights reserved.
# This code is part of the Biopython distribution and governed by its
# license.  Please see the LICENSE file that should have been included
# as part of this package.
```

However, in this [file](https://github.com/biopython/biopython/blob/master/Bio/codonalign/chisq.py) the start lines are 

``` Python implementation of chisqprob, to avoid SciPy dependency.
Adapted from SciPy: scipy/special/cephes/{chdtr,igam}.


import math

# Cephes Math Library Release 2.0:  April, 1987
# Copyright 1985, 1987 by Stephen L. Moshier
# Direct inquiries to 30 Frost Street, Cambridge, MA 02140
MACHEP = 0.0000001     # the machine roundoff error / tolerance
BIG = 4.503599627370496e15
BIGINV = 2.22044604925031308085e-16

```

Where to write the standard license wording? Is it start of the file?  and is there a standard procedure/files to follow

Thank you!

**Comment by peterjc** [comment]
``Bio/Affy/CelFile.py`` looks fine as it is, copyright line(s) then the license text as comments before anything else (other than perhaps a hash-bang line as the very first line, but that is unusual).

``Bio/codonalign/chisq.py`` is a potential problem, already logged as #1610.

**Comment by svalqui** [comment]
I'll have a look at the license in the test files,
Cheers,

**Comment by peterjc** [comment]
@svalqui the ``Tests/`` folder is a special case - it would probably be better to review ``Tests/test_XXX.py`` as part of reviewing the appropriate ``Bio/XXX/*.py`` code.

**Comment by peterjc** [comment]
@svalqui Update: Sorry, mixing up issues in my head. For adding missing license headers, sure, you should be fine working on the test files. I was thinking about dual licensing the files, which is more complicate.

**Comment by peterjc** [comment]
We were down to file files now where the license is unclear:

* ``Bio/codonalign/chisq.py`` - see #1610
* ``Bio/PDB/parse_pdb_header.py`` - done in dffc896dbf9939bf42cc1753e6e0e47cf19abe09
* ``Bio/SeqUtils/CodonUsageIndices.py`` - done in 67c4e4e18e79397b42bc27c00d0382989997b055
* ``Bio/SeqUtils/IsoelectricPoint.py`` -  done in 67c4e4e18e79397b42bc27c00d0382989997b055
* ``Bio/SeqUtils/ProtParam.py`` -  done in 67c4e4e18e79397b42bc27c00d0382989997b055

Closing issue - thank you everyone.
