### ISSUE TITLE
Biopython Alignment using Muscle or ClustalW without file input

### ISSUE THREAD

**Issue by Grendel26** [biopython/biopython#1618]
Hi.
I'm actually building a script in python3 to calculate divergence between several paired sequences. So, I need firt to make an alignment between 2 proteines sequences and then make a codon alignment with 2 dna sequences. To make my first alignment (between 2 proteines sequences), I'm actually using:
```
alns = pairwise2.align.globalds(prot1 ,prot2, matrix, gap_open, gap_extend)
```
But I need something more sofisticated such ClustalW or MUSCLE algorithmes. The problem is that my script is built in the way that I ask 4 sequences files: 2 of dna and 2 of amino acides.

Then I convert my sequences in string. But ClustalW and MUSCLE ask to give a file with those sequences unaligned. Is there a way to give the sequences like that:
```
muscle_cline = MuscleCommandline(muscle_exe, prot1 , prot2, out=out_file)
instead of the input file (unaligned sequences file):
muscle_cline = MuscleCommandline(muscle_exe, input=in_file, out=out_file)
```
or like that:
```
clustalw_cline = ClustalwCommandline("clustalw2", prot1, prot2)
instead of that:
clustalw_cline = ClustalwCommandline("clustalw2", infile=in_file)
```
Because I do not want to creat a file with my sequence unaligned for each of my sequences (around 450)...

Thanks you very much.

**Comment by peterjc** [comment]
The simplest solution here for passing the unaligned sequences to a command line tool like clustalw or muscle is to write a (temporary) FASTA file.

However, by default it you do not tell Muscle a filename, it will expect to read FASTA input from ``stdin``. Normally this is passed to the tool at the command line by Unix redirection or a pipe. You can do this within Python using the ``subprocess`` module.

See the example "MUSCLE using stdin and stdout" in the Tutorial,
http://biopython.org/DIST/docs/tutorial/Tutorial.html
http://biopython.org/DIST/docs/tutorial/Tutorial.pdf

However, when things don't work, this is much harder to explore. The file solution is simpler as you have the input data on disk so can try running the alignment by hand at the command line to figure out what is breaking.

**Comment by Grendel26** [comment]
Ok thank you.
