### ISSUE TITLE
problem in using AlignIO

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1620]
i'm new in python and i have met a problem while running AlignIO with simple file, what happens here is while trying to test the alignment of amino acid sequance it give me an errore in the source code of the module AlignIO itself

I am reporting a problem with biopython-1.71, Python version 3.6.5, and operating
system Ubuntu (bio-linux)  as follows:

```python
from Bio import AlignIO
alignment = AlignIO.read("PF05371_seed.sth", "stockholm")
print(alignment)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

```
SingleLetterAlphabet() alignment with 7 rows and 52 columns
AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIRL...SKA COATB_BPIKE/30-81
AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIKL...SRA Q9T0Q8_BPIKE/1-52
DGTSTATSYATEAMNSLKTQATDLIDQTWPVVTSVAVAGLAIRL...SKA COATB_BPI22/32-83
AEGDDP---AKAAFNSLQASATEYIGYAWAMVVVIVGATIGIKL...SKA COATB_BPM13/24-72
AEGDDP---AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKL...SKA COATB_BPZJ2/1-49
AEGDDP---AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKL...SKA Q9T0Q9_BPFD/1-49
FAADDATSQAKAAFDSLTAQATEMSGYAWALVVLVVGATVGIKL...SRA COATB_BPIF1/22-73
```

### Actual behaviour

Running: /home/peter/Desktop/try.py (Thu Apr 19 02:45:59 2018)

```
Traceback (most recent call last):
  File "/home/peter/Desktop/try.py", line 2, in <module>
    alignment = AlignIO.read("PF05371_seed.sth", "stockholm")
  File "/usr/lib/python2.7/dist-packages/Bio/AlignIO/__init__.py", line 423, in read

    first = next(iterator)
  File "/usr/lib/python2.7/dist-packages/Bio/AlignIO/__init__.py", line 370, in parse

    for a in i:
  File "/usr/lib/python2.7/dist-packages/Bio/AlignIO/StockholmIO.py", line 325, in __next__

    raise ValueError("Did not find STOCKHOLM header")
ValueError: Did not find STOCKHOLM header
```

### Steps to reproduce

1- downloaded the file of sequances in correct directory
2- copy the source code from tutorial of biopython and paste it in IDE (spyder)
3- running
4- get this errores

**Comment by peterjc** [comment]
In step 1, where did you download the file from? i.e. the URL please. I suspect you do not have a Stockholm format file. We can confirm this at the command line with something like ``head PF05371_seed.sth``

**Comment by peterhabib** [comment]
Peterjc

the file is downloaded from the database it self just like as it described in the biopython tutorial

**Comment by peterhabib** [comment]
here is the file 

# STOCKHOLM 1.0
#=GS COATB_BPIKE/30-81
#=GS COATB_BPIKE/30-81
#=GS Q9T0Q8_BPIKE/1-52
#=GS COATB_BPI22/32-83
#=GS COATB_BPM13/24-72
#=GS COATB_BPM13/24-72
#=GS COATB_BPM13/24-72
#=GS COATB_BPZJ2/1-49
#=GS Q9T0Q9_BPFD/1-49
#=GS Q9T0Q9_BPFD/1-49
#=GS COATB_BPIF1/22-73
#=GS COATB_BPIF1/22-73
COATB_BPIKE/30-81
#=GR COATB_BPIKE/30-81
Q9T0Q8_BPIKE/1-52
COATB_BPI22/32-83
COATB_BPM13/24-72
#=GR COATB_BPM13/24-72
COATB_BPZJ2/1-49
Q9T0Q9_BPFD/1-49
#=GR Q9T0Q9_BPFD/1-49
COATB_BPIF1/22-73
#=GR COATB_BPIF1/22-73
#=GC SS_cons
#=GC seq_cons
//
AC
DR
AC
AC
AC
DR
DR
AC
AC
DR
AC
DR
SS
SS
SS
SS
P03620.1
PDB; 1ifl ; 1-52;
Q9T0Q8.1
P15416.1
P69541.1
PDB; 2cpb ; 1-49;
PDB; 2cps ; 1-49;
P03618.1
Q9T0Q9.1
PDB; 1nh4 A; 1-49;
P03619.2
PDB; 1ifk ; 1-50;
AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIRLFKKFSSKA
-HHHHHHHHHHHHHH--HHHHHHHH--HHHHHHHHHHHHHHHHHHHHH----
AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIKLFKKFVSRA
DGTSTATSYATEAMNSLKTQATDLIDQTWPVVTSVAVAGLAIRLFKKFSSKA
AEGDDP...AKAAFNSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFTSKA
---S-T...CHCHHHHCCCCTCCCTTCHHHHHHHHHHHHHHHHHHHHCTT--
AEGDDP...AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFASKA
AEGDDP...AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFTSKA
------...-HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH--
FAADDATSQAKAAFDSLTAQATEMSGYAWALVVLVVGATVGIKLFKKFVSRA
XX-HHHH--HHHHHH--HHHHHHH--HHHHHHHHHHHHHHHHHHHHHHH---
XHHHHHHHHHHHHHHHCHHHHHHHHCHHHHHHHHHHHHHHHHHHHHHHHC--
AEssss...AptAhDSLpspAT-hIu.sWshVsslVsAsluIKLFKKFsSKA

**Comment by peterjc** [comment]
Something strange seems to have happended to your download, I got:

```
$ cat PF05371_seed.txt 
# STOCKHOLM 1.0
#=GS Q9T0Q9_BPFD/1-49    AC Q9T0Q9.1
#=GS Q9T0Q9_BPFD/1-49    DR PDB; 1NH4 A; 6-49;
#=GS J7I0P6_BPM13/24-72  AC J7I0P6.1
#=GS CAPSD_BPZJ2/1-49    AC P03618.1
#=GS CAPSD_BPIF1/22-73   AC P03619.2
#=GS CAPSD_BPIF1/22-73   DR PDB; 1IFK A; 1-50;
#=GS Q9T0Q8_BPIKE/1-52   AC Q9T0Q8.1
#=GS CAPSD_BPI22/32-83   AC P15416.1
#=GS CAPSD_BPIKE/30-81   AC P03620.1
#=GS CAPSD_BPIKE/30-81   DR PDB; 1IFL A; 1-52;
Q9T0Q9_BPFD/1-49               AEGDDP...AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFTSKA
#=GR Q9T0Q9_BPFD/1-49    SS    XXXXX-...-HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH--
J7I0P6_BPM13/24-72             AEGDDP...AKAAFNSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFTSKA
CAPSD_BPZJ2/1-49               AEGDDP...AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKLFKKFASKA
CAPSD_BPIF1/22-73              FAADDATSQAKAAFDSLTAQATEMSGYAWALVVLVVGATVGIKLFKKFVSRA
#=GR CAPSD_BPIF1/22-73   SS    XX-HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
Q9T0Q8_BPIKE/1-52              AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIKLFKKFVSRA
CAPSD_BPI22/32-83              DGTSTATSYATEAMNSLKTQATDLIDQTWPVVTSVAVAGLAIRLFKKFSSKA
CAPSD_BPIKE/30-81              AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIRLFKKFSSKA
#=GR CAPSD_BPIKE/30-81   SS    -HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
#=GC SS_cons                   -HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
#=GC seq_cons                  AEssss...AptAhDSLpspAT-hIu.sWshVsslVsAsluIKLFKKFsSKA
//
```

This works fine:

```
$ python -c "from Bio import AlignIO; print(AlignIO.read('PF05371_seed.txt', 'stockholm'))"
SingleLetterAlphabet() alignment with 7 rows and 52 columns
AEGDDP---AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKL...SKA Q9T0Q9_BPFD/1-49
AEGDDP---AKAAFNSLQASATEYIGYAWAMVVVIVGATIGIKL...SKA J7I0P6_BPM13/24-72
AEGDDP---AKAAFDSLQASATEYIGYAWAMVVVIVGATIGIKL...SKA CAPSD_BPZJ2/1-49
FAADDATSQAKAAFDSLTAQATEMSGYAWALVVLVVGATVGIKL...SRA CAPSD_BPIF1/22-73
AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIKL...SRA Q9T0Q8_BPIKE/1-52
DGTSTATSYATEAMNSLKTQATDLIDQTWPVVTSVAVAGLAIRL...SKA CAPSD_BPI22/32-83
AEPNAATNYATEAMDSLKTQAIDLISQTWPVVTTVVVAGLVIRL...SKA CAPSD_BPIKE/30-81
```

**Comment by peterhabib** [comment]
i took your file above and saved it in file, i run the code again and i have nothing.

however, thank you for your effort :) .

**Comment by peterhabib** [comment]
wooow !! i did it finally

i saved the stockholm file above that you provided and placed it the the correct directory, it works finally after trying for 2 weeks. thank you very much :hearts:

**Comment by peterjc** [comment]
It is strange that something happened with your download. If it happens again (e.g. on other PFAM families, it might be worth contacting the xfam.org website team to try to solve this properly). Please feel free to re-open this issue later on.

Anyway, glad to know you've got this particular example working now. Closing issue.

**Comment by asmaamohamedreda** [comment]
When you download the sequence Alignment... you have tho choose from format options "Stockholm"
