### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1646]
getting (NameError: free variable 'program' referenced before assignment in enclosing scope) while trying to run the code below

I am reporting a problem with biopython-1.71, Python version 3.6.5, and operating
system Ubuntu (bio-linux) as follows:

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

class ButtonWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="Button Demo")
        self.set_border_width(10)

        hbox = Gtk.Box(spacing=6)
        self.add(hbox)

        button = Gtk.Button.new_with_label("Click Me")
        button.connect("clicked", self.on_click_me_clicked)
        hbox.pack_start(button, True, True, 0)

        button = Gtk.Button.new_with_mnemonic("_Open")
        button.connect("clicked", self.on_open_clicked)
        hbox.pack_start(button, True, True, 0)

        button = Gtk.Button.new_with_mnemonic("_Close")
        button.connect("clicked", self.on_close_clicked)
        hbox.pack_start(button, True, True, 0)

    def on_click_me_clicked(self, button):
        class program(Gtk.Widget):

            def __init__(self):
                Gtk.Widget.__init__(self, title="window")
                self.set_border_width(50)
                hbox = Gtk.Box(spacing=60)
                self.add(hbox)

                button = Gtk.Button.new_with_label("peto")
                button.connect("clicked", self.on_me_clicked)
                hbox.pack_start(button, True, True, 0)

                def on_me_clicked(self, button):
                    print("woooooooooooooooow")

            win = program()
            win.connect("destroy", Gtk.main_quit)
            win.show_all()
            Gtk.main()



    def on_open_clicked(self, button):
        print("\"Open\" button was clicked")

    def on_close_clicked(self, button):
        print("Closing application")
        Gtk.main_quit()

win = ButtonWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
```

*Peter: Added there triple back-tick markup to show this as Python code*

### Expected behaviour

to open window with three buttons one of them which is "click me" should open new window once i clicks it

### Actual behaviour

```
Traceback (most recent call last):
  File "/home/peter/m.py", line 27, in on_click_me_clicked

    class program(Gtk.Widget):
  File "/home/peter/m.py", line 42, in program
    win = program()
NameError: free variable 'program' referenced before assignment in enclosing scope
```

### Steps to reproduce

1-construction of window
2-adding the buttons
3- connect the clicking of "click me" button with opening new window

Note: i copied the original code from "gtk+ tutorial" and modified it to open window from another window

**Comment by peterjc** [comment]
There is something wrong with the indentation, these lines look out of place:

```python
            win = program()
            win.connect("destroy", Gtk.main_quit)
            win.show_all()
            Gtk.main()
```

Currently you have them inside the class definition for ``program``, which is odd - and explains where they can't use the class (out of scope).

In fact, having the class definition for ``program`` inside the method ``on_click_me_clicked`` is also strange.

Without the URL linking to the original tutorial you started from, it is hard to give you more guidance.

Anyway, this is nothing to do with Biopython, so I'm going to close this issue and suggest you try asking elsewhere - either a GTK+ site or somewhere like https://stackoverflow.com
