### ISSUE TITLE
SearchIO tutorial uses single quotes which break in PDF

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1647]
i'm try to use (The SearchIO object model) to search for unknown sequence using biopython code example in tutorial, it gives me error. 

I am reporting a problem with Biopython version, Python version, and operating
system as follows: biopython-1.71, Python version 3.6.5, and operating
system Ubuntu (bio-linux) as follows:

```
from Bio import SearchIO
blast_qresult = SearchIO.read(’my_blast.xml’, ’blast-xml’)
print(blast_qresult)
```

### Expected behaviour
```
Program: blastn (2.2.27+)
Query: 42291 (61)
mystery_seq
Target: refseq_rna
Hits: ---- -----
# # HSP
---- -----
----------------------------------------------------------
ID + description
----------------------------------------------------------
gi|262205317|ref|NR_030195.1| Homo sapiens microRNA 52...
gi|301171311|ref|NR_035856.1| Pan troglodytes microRNA...
gi|270133242|ref|NR_032573.1| Macaca mulatta microRNA ...
gi|301171322|ref|NR_035857.1| Pan troglodytes microRNA...
gi|301171267|ref|NR_035851.1| Pan troglodytes microRNA...
gi|262205330|ref|NR_030198.1| Homo sapiens microRNA 52...
gi|262205302|ref|NR_030191.1| Homo sapiens microRNA 51...
gi|301171259|ref|NR_035850.1| Pan troglodytes microRNA...
gi|262205451|ref|NR_030222.1| Homo sapiens microRNA 51...
gi|301171447|ref|NR_035871.1| Pan troglodytes microRNA...
gi|301171276|ref|NR_035852.1| Pan troglodytes microRNA...
gi|262205290|ref|NR_030188.1| Homo sapiens microRNA 51...
gi|301171354|ref|NR_035860.1| Pan troglodytes microRNA...
gi|262205281|ref|NR_030186.1| Homo sapiens microRNA 52...
gi|262205298|ref|NR_030190.1| Homo sapiens microRNA 52...
gi|301171394|ref|NR_035865.1| Pan troglodytes microRNA...
gi|262205429|ref|NR_030218.1| Homo sapiens microRNA 51...
gi|262205423|ref|NR_030217.1| Homo sapiens microRNA 52...
gi|301171401|ref|NR_035866.1| Pan troglodytes microRNA...
gi|270133247|ref|NR_032574.1| Macaca mulatta microRNA ...
gi|262205309|ref|NR_030193.1| Homo sapiens microRNA 52...
gi|270132717|ref|NR_032716.1| Macaca mulatta microRNA ...
gi|301171437|ref|NR_035870.1| Pan troglodytes microRNA...
gi|270133306|ref|NR_032587.1| Macaca mulatta microRNA ...
gi|301171428|ref|NR_035869.1| Pan troglodytes microRNA...
gi|301171211|ref|NR_035845.1| Pan troglodytes microRNA...
gi|301171153|ref|NR_035838.1| Pan troglodytes microRNA...
gi|301171146|ref|NR_035837.1| Pan troglodytes microRNA...
gi|270133254|ref|NR_032575.1| Macaca mulatta microRNA ...
gi|262205445|ref|NR_030221.1| Homo sapiens microRNA 51...
gi|356517317|ref|XM_003527287.1|
gi|297814701|ref|XM_002875188.1|
gi|397513516|ref|XM_003827011.1|
PREDICTED: Glycine ma...
Arabidopsis lyrata su...
PREDICTED: Pan panisc...
```
### Actual behaviour
```
SyntaxError: Non-ASCII character '\xe2' in file /home/peter/alignment.py on line 23, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
### Steps to reproduce

1-create file contain the sequence of interest according to the biopython tutorial 
name of file: my_blast.xml
content of file: >mystery_seq
               CCCTCTACAGGGAAGCGCTTTCTGTTGTCTGAAAGAAAAGAAAGTGCTTCCTTTTAGAGGG
note: i know that there is somthing wrong in the file but i don't know where

2-copying the code from tutorial
3- run the code 
4- getting the error

**Comment by peterhabib** [comment]
i copied it from biopython tutorial chapter 8.1.1

**Comment by peterhabib** [comment]
8.1.1
QueryResult
The QueryResult object represents a single search query and contains zero or more Hit objects. Let’s see
what it looks like using the BLAST file we have:
>>> from Bio import SearchIO
>>> blast_qresult = SearchIO.read(’my_blast.xml’, ’blast-xml’)
>>> print(blast_qresult)
Program: blastn (2.2.27+)
Query: 42291 (61)
108mystery_seq
Target: refseq_rna
Hits: ---- -----
# # HSP
---- -----
0
1
1
1
2
1
3
2
4
1
5
2
6
1
7
1
8
1
9
2
10
1
11
1
12
1
13
1
14
2
15
1
16
1
17
1
18
1
19
1
20
1
21
2
22
2
23
2
24
2
25
1
26
2
27
2
28
2
29
2
~~~
97
1
98
1
99
1
----------------------------------------------------------
ID + description
----------------------------------------------------------
gi|262205317|ref|NR_030195.1| Homo sapiens microRNA 52...
gi|301171311|ref|NR_035856.1| Pan troglodytes microRNA...
gi|270133242|ref|NR_032573.1| Macaca mulatta microRNA ...
gi|301171322|ref|NR_035857.1| Pan troglodytes microRNA...
gi|301171267|ref|NR_035851.1| Pan troglodytes microRNA...
gi|262205330|ref|NR_030198.1| Homo sapiens microRNA 52...
gi|262205302|ref|NR_030191.1| Homo sapiens microRNA 51...
gi|301171259|ref|NR_035850.1| Pan troglodytes microRNA...
gi|262205451|ref|NR_030222.1| Homo sapiens microRNA 51...
gi|301171447|ref|NR_035871.1| Pan troglodytes microRNA...
gi|301171276|ref|NR_035852.1| Pan troglodytes microRNA...
gi|262205290|ref|NR_030188.1| Homo sapiens microRNA 51...
gi|301171354|ref|NR_035860.1| Pan troglodytes microRNA...
gi|262205281|ref|NR_030186.1| Homo sapiens microRNA 52...
gi|262205298|ref|NR_030190.1| Homo sapiens microRNA 52...
gi|301171394|ref|NR_035865.1| Pan troglodytes microRNA...
gi|262205429|ref|NR_030218.1| Homo sapiens microRNA 51...
gi|262205423|ref|NR_030217.1| Homo sapiens microRNA 52...
gi|301171401|ref|NR_035866.1| Pan troglodytes microRNA...
gi|270133247|ref|NR_032574.1| Macaca mulatta microRNA ...
gi|262205309|ref|NR_030193.1| Homo sapiens microRNA 52...
gi|270132717|ref|NR_032716.1| Macaca mulatta microRNA ...
gi|301171437|ref|NR_035870.1| Pan troglodytes microRNA...
gi|270133306|ref|NR_032587.1| Macaca mulatta microRNA ...
gi|301171428|ref|NR_035869.1| Pan troglodytes microRNA...
gi|301171211|ref|NR_035845.1| Pan troglodytes microRNA...
gi|301171153|ref|NR_035838.1| Pan troglodytes microRNA...
gi|301171146|ref|NR_035837.1| Pan troglodytes microRNA...
gi|270133254|ref|NR_032575.1| Macaca mulatta microRNA ...
gi|262205445|ref|NR_030221.1| Homo sapiens microRNA 51...
gi|356517317|ref|XM_003527287.1|
gi|297814701|ref|XM_002875188.1|
gi|397513516|ref|XM_003827011.1|
PREDICTED: Glycine ma...
Arabidopsis lyrata su...
PREDICTED: Pan panisc...
We’ve just begun to scratch the surface of the object model, but you can see that there’s already some
useful information. By invoking print on the QueryResult object, you can see:
• The program name and version (blastn version 2.2.27+)
• The query ID, description, and its sequence length (ID is 42291, description is ‘mystery seq’, and it is
61 nucleotides long)
• The target database to search against (refseq rna)
• A quick overview of the resulting hits. For our query sequence, there are 100 potential hits (numbered
0–99 in the table). For each hit, we can also see how many HSPs it contains, its ID, and a snippet of
its description. Notice here that Bio.SearchIO truncates the hit table overview, by showing only hits
numbered 0–29, and then 97–99.

**Comment by MarkusPiotrowski** [comment]
@peterhabib OK, I thought you have a script, since your error message said that the error is in line 23 of a script ```alignment.py```

Still, I think that this may be a wrongly converted ```'```.

1. Did you type the offending line or copy&paste it from the manual?
2. If you copy&pasted it, 
   - from the html version or the pdf version?
   - try typing the offending line
3. Was this the most recent version of the tutorial? The actual tutorial looks a little bit different. Also, I think we had small issues with quotation marks vs. apostrophe in the manual.

**Comment by peterjc** [comment]
Python lets you either either single quotes or double quotes:

```python
from Bio import SearchIO
blast_qresult = SearchIO.read('my_blast.xml', 'blast-xml')
print(blast_qresult)
```

or:

```python
from Bio import SearchIO
blast_qresult = SearchIO.read("my_blast.xml", "blast-xml")
print(blast_qresult)
```

The PDF tutorial (which is written with a system called LaTeX) deliberately uses double quotes to avoid this problem, as in the PDF output single quotes get turned into these pretty characters which do not copy-and-paste nicely:

```python
from Bio import SearchIO
blast_qresult = SearchIO.read(’my_blast.xml’, ’blast-xml’)  # BAD
print(blast_qresult)
```

It looks like the SearchIO chapter (which is relatively new) needs to be updated to use double quotes.

You will find this problem occurs in other contexts - another common issue is copy-and-paste of command line instructions where the minus sign has been replaced by a special hyphen character.

**Comment by bow** [comment]
Thanks for reporting, @peterhabib. As @MarkusPiotrowski and @peterjc mentioned, looks like this is indeed caused by an unexpected quote character in the PDF. I have replaced them with proper double quotes [here](https://github.com/biopython/biopython/pull/1648). This should fix your issue.

**Comment by peterhabib** [comment]
Okay i changed the quotes and it still give me this:

/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py:213: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)

Traceback (most recent call last):
  File "/home/peter/a.py", line 2, in <module>
    blast_qresult = SearchIO.read('my_blast.xml', 'blast-xml')
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py", line 359, in read

    first = next(generator)
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py", line 314, in parse
    generator = iterator(source_file, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 190, in __init__
    self._meta, self._fallback = self._parse_preamble()
  File "/usr/lib/python2.7/dist-packages/Bio/SearchIO/BlastIO/blast_xml.py", line 204, in _parse_preamble
    for event, elem in self.xml_iter:
  File "<string>", line 91, in next
cElementTree.ParseError: syntax error: line 1, column 0

**Comment by peterjc** [comment]
An XML syntax error at line 1, column 0 - that sounds like the very start of the file. Is it really an XML file you are trying to load?

**Comment by peterjc** [comment]
It should start like this,

```xml
<?xml version="1.0"?>
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
```

e.g. https://github.com/biopython/biopython/blob/biopython-171/Tests/Blast/xml_2226_tblastx_004.xml

**Comment by peterhabib** [comment]
you right, the format was incorrect. but if i want to search for sequence against the nucleotide database how should i write this sequence in xml file ?

**Comment by MarkusPiotrowski** [comment]
@peterhabib You are dealing with the wrong module, and possibly you haven't properly understood what you need to do. ```SearchIO``` is for dealing with the __output__ of a search. So in you example, ```my_blast.xml``` is __not__ the query sequence, but already the the output of some search machine, e.g. ```BLAST```.
In the example of the tutorial, there is a link to such an example xml file (https://github.com/biopython/biopython/blob/master/Doc/examples/my_blast.xml).

What you obviously want to do, is the search itself. This is described in Chapter 7 of the tutorial. Please read this carefully. 

If you still have problems, please post your script (a minimal version which reproduces your problem) and also your files you are using.

**Comment by peterhabib** [comment]
Thanks You very much for your Efforts.
