### ISSUE TITLE
EMBOSS pair format with full line insertion handled incorrectly by EmbossIO.py

### ISSUE THREAD

**Issue by pamelarussell** [biopython/biopython#1652]
### Setup

I am reporting a problem with Biopython version 1.71, Python version 3.6, and operating
system Mac OS High Sierra as follows. I have run a pairwise sequence alignment using [EMBOSS stretcher](https://www.ebi.ac.uk/Tools/psa/emboss_stretcher/nucleotide.html) and am attempting to parse the output (in "pair" format) with EmbossIO. There is a line in the alignment file that contains no letters, and the start coordinate of the line is 1 +  the end coordinate of the line. This case falls through the current flow of nested `if` statements in `EmbossIO.py`, which seems to be assuming that when there are no letters on a line, the reported start and end coordinates for the line will be equal.

```python
from Bio import AlignIO
file = "<Output file from EMBOSS Stretcher>"
alignment = AlignIO.read(open(file), "emboss")
```

### Expected behaviour

Complete silently

### Actual behaviour

```
Traceback (most recent call last):
  File "/Users/Pamela/Dropbox/git/align-utils/test.py", line 4, in <module>
    alignment = AlignIO.read(open(file), "emboss")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/AlignIO/__init__.py", line 429, in read
    first = next(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/AlignIO/__init__.py", line 376, in parse
    for a in i:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Bio/AlignIO/EmbossIO.py", line 165, in __next__
    assert seq.replace("-", "") != "", repr(line)
AssertionError: 'mm10_chrX_505  27261 --------------------------------------------------  27260\n'
```
### Steps to reproduce

The EMBOSS Stretcher file exists [here](https://www.ebi.ac.uk/Tools/services/rest/emboss_stretcher/result/emboss_stretcher-I20180514-174246-0545-50555559-p2m/aln) for the next 7 days. The problem is caused by the line `mm10_chrX_505  27261 --------------------------------------------------  27260`

**Comment by peterjc** [comment]
Could you add your example (or a smaller similar example) as a test case please?

 i.e. check in the file under ``Tests/Emboss/`` and at a minimum add it to the list in ``Tests/test_AlignIO.py`` (then run ``python run_tests.py -g test_AlignIO.py`` to update the output in ``Tests/output/test_AlignIO`` since this is one of our legacy print-and-compare tests).

There is a chapter in the tutorial giving more background on our test framework - the newer tests use ``unittest`` from the Python standard library.

**Comment by peterjc** [comment]
Belatedly closing this issue thanks to your work on pull request #1653
