### ISSUE TITLE
Nucleotide dot plots issue

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1661]
while trying to run the following code as it declared in Biopython tutorial it give me error that there is invalid syntex

I am reporting a problem with biopython-1.71, Python version 3.4, and operating
system Ubuntu (bio-linux)

from Bio import SeqIO
with open("ls_orchid.fasta") as in_handle:
    record_iterator = SeqIO.parse(in_handle, "fasta")
    rec_one = next(record_iterator)
    rec_two = next(record_iterator)
window = 7
seq_one = str(rec_one.seq).upper()
seq_two = str(rec_two.seq).upper()
data = [[(seq_one[i:i+window] <> seq_two[j:j+window])
for j in range(len(seq_one)-window)]
for i in range(len(seq_two)-window)]
import pylab
pylab.gray()
pylab.imshow(data)
pylab.xlabel("%s (length %i bp)" % (rec_one.id, len(rec_one)))
pylab.ylabel("%s (length %i bp)" % (rec_two.id, len(rec_two)))
pylab.title("Dot plot using window size %i\n(allowing no mis-matches)" % window)
pylab.show()

(*Please copy and run the above in your Python, and copy-and-paste the output*)

the output png picture that illustrate the blotting 

(*Please fill this in*)

File "/media/peter/14A08922A0890C04/Peter/seq/blotting.py", line 9
    data = [[(seq_one[i:i+window] <> seq_two[j:j+window])
                                   ^
SyntaxError: invalid syntax

##steps

1-download ls_orchid.fasta record and save it in correct directory
2- copy and run the code

**Comment by peterjc** [comment]
I think we need to update this line which is fine under Python 2:

```python
data = [[(seq_one[i:i+window] <> seq_two[j:j+window])
```

to read as follows in order to work on Python 3:

```python
data = [[(seq_one[i:i+window] != seq_two[j:j+window])
```

Does that fix it?

**Comment by peterhabib** [comment]
Yes it works ! Thank you

**Comment by peterjc** [comment]
Thank you for confirming, that will be fixed in the tutorial for the next release of Biopython.
