### ISSUE TITLE
drawing annotated Chromosome

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1662]
while trying to draw Annotated Chromosomes as it described in biopython tutorial it gives me the simple one without annotation with labels
 
I  am reporting a problem with biopython-1.71, Python version 3.4, and operating
system Ubuntu (bio-linux)

```python
from reportlab.lib.units import cm
from Bio import SeqIO
from Bio.Graphics import BasicChromosome

entries = [("Chr I", "NC_003070.gbk"),
           ("Chr II", "NC_003071.gbk"),
           ("Chr III", "NC_003074.gbk"),
           ("Chr IV", "NC_003075.gbk"),
           ("Chr V", "NC_003076.gbk")]

max_len = 30432563 #Could compute this
telomere_length = 1000000 #For illustration

chr_diagram = BasicChromosome.Organism()
chr_diagram.page_size = (29.7*cm, 21*cm) #A4 landscape

for index, (name, filename) in enumerate(entries):
    record = SeqIO.read(filename,"genbank")
    length = len(record)
    features = [f for f in record.features if f.type=="tRNA"]
    #Record an Artemis style integer color in the feature's qualifiers,
    #1 = Black, 2 = Red, 3 = Green, 4 = blue, 5 =cyan, 6 = purple
    for f in features: f.qualifiers["color"] = [index+2]

    cur_chromosome = BasicChromosome.Chromosome(name)
    #Set the scale to the MAXIMUM length plus the two telomeres in bp,
    #want the same scale used on all five chromosomes so they can be
    #compared to each other
    cur_chromosome.scale_num = max_len + 2 * telomere_length

    #Add an opening telomere
    start = BasicChromosome.TelomereSegment()
    start.scale = telomere_length
    cur_chromosome.add(start)

    #Add a body - again using bp as the scale length here.
    body = BasicChromosome.AnnotatedChromosomeSegment(length, features)
    body.scale = length
    cur_chromosome.add(body)

    #Add a closing telomere
    end = BasicChromosome.TelomereSegment(inverted=True)
    end.scale = telomere_length
    cur_chromosome.add(end)

    #This chromosome is done
    chr_diagram.add(cur_chromosome)

chr_diagram.draw("tRNA_chrom.pdf", "Arabidopsis thaliana")
```

(*Peter: Updated to add triple back-tick formatting*)

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
PDF containing picture of simple chromosome as in figure 17.13  in chapter 17 of biopython tutorial

### Actual behaviour

PDF containing picture of simple chromosome as in figure 17.12  in chapter 17 of biopython tutorial

### Steps to reproduce

1- download chromosomes
2-copy the code from the tutorial
3-run the code

**Comment by peterjc** [comment]
Strange, it looks like the example is missing a loop adding the tRNA features...

**Comment by peterjc** [comment]
See also:

https://news.open-bio.org/2011/10/28/chromosome-diagrams-in-biopython/

And the code for the paper mentioned is here:

https://github.com/peterjc/pico_galaxy/tree/master/tools/chromosome_diagram

**Comment by peterjc** [comment]
Where did you get the GenBank files from? The FTP link in the tutorial seems to have changed, ftp://ftp.ncbi.nlm.nih.gov/genomes/Arabidopsis_thaliana

This should now be ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_refseq/Arabidopsis_thaliana/ which lists the GenBank files as last modified in 2011, and these are the MD5 checksums I got (use ``md5sum`` on Linux):

```
$ md5 NC_*.gbk
MD5 (NC_003070.gbk) = dbc6066292506e459bebb914d760c5ab
MD5 (NC_003071.gbk) = 3d9d1baa0267fb61ba6466888b690e9d
MD5 (NC_003074.gbk) = 9acb8735a96b4c0b5a277ab259d310eb
MD5 (NC_003075.gbk) = d50268709aa45f157746ce15c7b48d55
MD5 (NC_003076.gbk) = 2bd9a470127a6a8053501024bbbc1ec5
```

The example worked for me. My guess is there is a problem with your GenBank files (e.g. you have summary files only via the website or something like that).

**Comment by peterhabib** [comment]
it works. the error was in the GeneBank files that i downloaded from NCBI as summary genebank file not from FTP . thank you very much.

**Comment by peterjc** [comment]
Great - I've updated the FTP link ready for the next release, so will close this issue now. Thank you!
