### ISSUE TITLE
question about how to align to DNA sequences and get the start-end position

### ISSUE THREAD

**Issue by lpantano** [biopython/biopython#1699]
### Setup

HI, this is not an issue, more a question how to get the results I want doing it right.

I want to know:

1.what is the right matrix to use for DNA pairwise alignment.
2.Can I get the position of the long sequence where the small sequence start?

maybe it is not possible, just want to check it out with you first.

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)

2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
CPython
Darwin-17.4.0-x86_64-i386-64bit
1.71
```

### Expected behaviour

```
from Bio import pairwise2
from Bio.Seq import Seq
import operator
pairwise2.align.globalds("TCAGTCAGACTGACTAGTAG","GCATCAGCATCGACACTCAGTCAGACTGACTAGTAGGAGAGGCACGAGCTCA",matlist.ident, -3, -1)

[('----------------TCAGTCAGACTGACTAGTAG----------------',
  'GCATCAGCATCGACACTCAGTCAGACTGACTAGTAGGAGAGGCACGAGCTCA',
  84.0,
  12,
  36)]
```

### Actual behaviour

```
from Bio import pairwise2
from Bio.Seq import Seq
import operator
pairwise2.align.globalds("TCAGTCAGACTGACTAGTAG","GCATCAGCATCGACACTCAGTCAGACTGACTAGTAGGAGAGGCACGAGCTCA",matlist.ident, -3, -1)

[('----------------TCAGTCAGACTGACTAGTAG----------------',
  'GCATCAGCATCGACACTCAGTCAGACTGACTAGTAGGAGAGGCACGAGCTCA',
  84.0,
  0,
  52)]
```

really appreciate the time for this, sorry if it is a stupid question.

cheers

**Comment by mdehoon** [comment]
In the "Expected behaviour", what does the 12 and 36 correspond to?

**Comment by lpantano** [comment]
Sorry, not clear enough. I want to know the position where the shorter sequence start in the larger sequence (and end). Something like when you do a bla(s)t, that you have query start, query end, target start, target end. 

I hope is better know, let me know!

**Comment by mdehoon** [comment]
You could use the new pairwise aligner (which is in Biopython 1.72):
```
>>> from Bio import Align
>>> aligner = Align.PairwiseAligner()
>>> aligner.open_gap_score = -3
>>> aligner.extend_gap_score = -1
>>> alignments = aligner.align("TCAGTCAGACTGACTAGTAG", "GCATCAGCATCGACACTCAGTCAGACTGACTAGTAGGAGAGGCACGAGCTCA")
>>> alignment = alignments[0]
>>> print(alignment)
----------------TCAGTCAGACTGACTAGTAG----------------
                ||||||||||||||||||||                
GCATCAGCATCGACACTCAGTCAGACTGACTAGTAGGAGAGGCACGAGCTCA

>>> alignment.path
((0, 0), (0, 16), (20, 36), (20, 52))
```

The path is the path through the traceback matrix used by the pairwise aligner, and gives the start and end position of each block:

- Start at the origin (0,0)
- Advance 16 characters in the second sequence only to reach (0, 16); this tells you the starting position is 16;
- Advance 20 characters in both sequences to reach (20, 36); this tells you the ending position is 36, as you have reached the end of the first sequence;
- Advance 16 characters in the second sequence only to reach (20,52)

Note that this pairwise aligner is very flexible in terms of the gap penalties; see the documentation for more information.

**Comment by MarkusPiotrowski** [comment]
@lpantano You are using a global algorithm (```.globalds```) and by definition global alignments always start at the first position. If you would use a local alignment, in your example, you would get the desired output.

**Comment by lpantano** [comment]
Thanks so much, I was sure I wasn't using right the functions!
