### ISSUE TITLE
SeqIO module

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1704]
when running the following module to extract sequence from fasta file it gives me part of sequence not the whole sequence as in the original fasta file, why it skip the rest of sequence after 54 character and add three dots (...) and then add the last three letters? what should i do to make all sequence is visible ?

I am reporting a problem with biopython-1.71, Python version 3.4, and operating
system Ubuntu (bio-linux)

from Bio import SeqIO
for seq_record in SeqIO.parse("oneseq.fasta", "fasta"):
    file = "\n\nSequence is:%s" % repr(seq_record.seq)
    print(file)

### Expected behaviour

Seq('TATACATTAAAGGAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAAAAAAATGAATCTAAATTATAGGATTCCACTATGTAAGGTCTTTGAATCATATCATAAAAGACAATGTAATAAAGCATGAATACAGATTCACACATAATTATCTGATATGAATCTATTCATAGAAAAAAGAAAAAAGTAAGAGCCTCCGGCCAAG
ACTAAGAGGGTTGGCTCAAGAACAAAGTTCATTAAGAGCTCCATTGTAGAATTCAGACCTAATCATTAT
CAAGAAGCGATGGGAACGATGTAATCCATGAATACAGAAGATTCAATTGAAAAAGATCCTATGNTCAG
GAAGGATGGCGGAACGAACCAGAGACCAATTCATCTATTCTGAAAAGTGATAAACTAATCCTATAAAACTAAAATAGATATTGAAAGAGTAAATATTCGCCCGCGAAAATTCCTTTTTTATTAAATTGCTCATATTTTT
TTTAGCAATGCAATCTAATAAAATATATCTATACAAAAAAACATAGACAAACTATATATATATATATATA
TAATATATTTCAAATTCCCTTATATATCCAAATATAAAAATATCTAATAAATTAGATGAATATCAAAGAA
TCTATTGATTTAGTGTATTATTAAATGTATATATTAATTCAATATTATTATTCTATTCATTTTTATTCAT
TTTCAAATTTATAATATATTAATCTATATATTAATTTAGAATTCTATTCTAATTCGAATTCAATTTTTAA
ATATTCATATTCAATTAAAATTGAAATTTTTTCATTCGCGAGGAGCCGGATGAGAAGAAACTCTCATGTCCGGTTCTGTAGTAGAGATGGAATTAAGAAAAAACCATCAACTATAACCCCAAAAGAACCAGA', SingleLetterAlphabet())

### Actual behaviour

Sequence is:Seq('TATACATTAAAGGAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAAAAAA...AGA', SingleLetterAlphabet())

**Comment by peterjc** [comment]
Do not use ``repr(...)`` which deliberately gives a truncated representation for use at the interactive terminal. You can use ``str(...)`` or in this case leave it out:

```python
from Bio import SeqIO
for seq_record in SeqIO.parse("oneseq.fasta", "fasta"):
text = "\n\nSequence is:%s" % seq_record.seq
print(text)
```

Also style wise, avoid ``file`` as a variable name - it is the name of a built in function.
