### ISSUE TITLE
Interfacing with "Phylogenetic Analysis by Maximum Likelihood" (PAML) package.

### ISSUE THREAD

**Issue by idolawoye** [biopython/biopython#1705]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
CPython
Windows-10-10.0.16299-SP0
1.70
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

It is supposed to produce an output file and generate the maximum likelihood phylogenetic analysis but I keep getting the error shown below

### Actual behaviour
```
>>> from Bio.Phylo.PAML import codeml 
>>> cml = codeml.Codeml()
>>> cml.alignment = "reference_dna2_Copy.phy"
>>> cml.tree = "reference_dna2_Copy.newick"
>>> cml.out_file = "outfile.txt"
>>> cml.run()
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    cml.run()
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\Phylo\PAML\codeml.py", line 183, in run
    Paml.run(self, ctl_file, verbose, command)
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\Phylo\PAML\_paml.py", line 119, in run
    result_code = subprocess.call([command, ctl_file], stdout=dn, stderr=dn)
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
### Steps to reproduce

(*Please fill this in *)

**Comment by peterjc** [comment]
Is codeml installed on your Windows machine?

Where is it installed?

Is it on the PATH? i.e. Can you run ``codeml`` at the terminal, or do you need to give the full path? If a full path is needed, you must tell Python this by doing:

```python
cml.run(command=full_path_tocodeml)
```

**Comment by idolawoye** [comment]
Yes codeml is installed on my PC and I have just added it to the path, now this is what I keep getting:
```
>>> from Bio.Phylo.PAML import codeml
>>> cml = codeml.Codeml()
>>> cml.alignment = r"C:\Users\Idowu\Downloads\paml\ref.phy"
>>> cml.tree = r"C:\Users\Idowu\Downloads\paml\ref.newick"
>>> cml.out_file = r"C:\Users\Idowu\Downloads\paml\results.txt"
>>> cml.working_dir = r"C:\Users\Idowu\Downloads\paml"
>>> cml.run()
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    cml.run()
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\Phylo\PAML\codeml.py", line 185, in run
    results = read(self.out_file)
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\Phylo\PAML\codeml.py", line 205, in read
    raise ValueError("Invalid results file")
ValueError: Invalid results file
```
Any idea why it says ```invalid results file``` even after changing it to an ```.out``` format.

**Comment by peterjc** [comment]
That's good progress. My guess is that the version of PAML is slightly different, and the Biopython code needs updating to understand the output.

Can you tell us the version of PAML or codeml installed?

Can you share the contents of the ``C:\Users\Idowu\Downloads\paml\results.txt`` file?

**Comment by idolawoye** [comment]
I have version 4.9 of PAML installed.

The result.txt file is empty, there is nothing in it.

**Comment by peterjc** [comment]
@brandoninvergo could you look at this?

**Comment by brandoninvergo** [comment]
It looks to me like codeml is failing.  Have you tried running it on these input files outside of Python? Is it giving any errors?  Alternatively, do `cml.run(verbose=True)`, which should give some clues.

**Comment by brandoninvergo** [comment]
@peterjc perhaps we can add the following to `Bio/Phylo/codeml.py` at line 197:

    if not lines:
        raise ValueError("Empty results file.  Pass 'verbose=True' to Codeml.run() to verify that CODEML exits successfully.")

...or something like that.  It would be a bit more descriptive and would help point people in the right direction.

**Comment by peterjc** [comment]
I don't know PAML well enough to guess how often it might happen, but was going to suggest checking for an empty results file specifically. Could you put that in a pull request (easily done via the GitHub in browser editor for a tiny change like this)?

**Comment by brandoninvergo** [comment]
If the user hasn't tried running the program on their input files outside of Python beforehand and they're not used to CODEML's ...ehm...eccentricities, I'm afraid it might be fairly common.  I'm also not 100% sure that CODEML will exit with a non-zero code in all cases, so depending on exit codes won't catch everything.

**Comment by idolawoye** [comment]
@brandoninvergo I ran ```cml.run(verbose=True)``` and here is the outcome:
```
>>> cml.run(verbose = True)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    cml.run(verbose = True)
TypeError: run() missing 1 required positional argument: 'self'
```
Also when I ran codeml outside python i.e using the PalmX-CodeML.exe program I got something different:
```
C:\Users\Idowu\Downloads\pamlX\bin\codeml.exe   running...


AAML in paml version 4.9h, March 2018
ns = 6  	ls = 39
Reading sequences, sequential format..
Reading seq # 1: Archaeopt CGATGCTTAC CGCCGATGCT       

Error in sequence data file: O at 7 seq 1.
Make sure to separate the sequence from its name by 2 or more spaces.

C:\Users\Idowu\Downloads\pamlX\bin\codeml.exe   finished
```
However, I have looked at the alignment files and the format are just fine as I have also used them to test other tree construction scripts.

**Comment by brandoninvergo** [comment]
> @brandoninvergo I ran cml.run(verbose=True) and here is the outcome:
> 
> >>> cml.run(verbose = True)
> Traceback (most recent call last):
>   File "<pyshell#8>", line 1, in <module>
>     cml.run(verbose = True)
> TypeError: run() missing 1 required positional argument: 'self'

Hmm...that's not supposed to happen.  Can you show all the steps you took?   It should be something like:

    cml = codeml.Codeml()
    <set up cml instance>
    cml.run(verbose=True)

Based on the error it looks like maybe you forgot the `()` after `Codeml`...?

> Also when I ran codeml outside python i.e using the PalmX-CodeML.exe program I got something different:
> 
> C:\Users\Idowu\Downloads\pamlX\bin\codeml.exe   running...
> 
> 
> AAML in paml version 4.9h, March 2018
> ns = 6  	ls = 39
> Reading sequences, sequential format..
> Reading seq # 1: Archaeopt CGATGCTTAC CGCCGATGCT       
> 
> Error in sequence data file: O at 7 seq 1.
> Make sure to separate the sequence from its name by 2 or more spaces.
> 
> C:\Users\Idowu\Downloads\pamlX\bin\codeml.exe   finished
> 
> However, I have looked at the alignment files and the format are just fine as I have also used them to test other tree construction scripts.

This is the real problem: CODEML is not creating a results file because it does not successfully run.  This isn't the appropriate place for support for running CODEML, but the best advice I can give is to do what it suggests and check that there are two spaces between the species name and the start of the sequence.  Also note that it says "Reading sequences, sequential format", which implies that it thinks your alignment is in the sequential Phylip format.  If it is interleaved Phylip, you have to put an "I" after the sequence length in the first line of the file (the header has number of sequences and sequence length, e.g. "7 300", which should be changed to "7 300I", I think).

**Comment by brandoninvergo** [comment]
Oh also, now that I look at it, it says "AAML", implying that it thinks it should be finding amino acids, when alignment clearly contains nucleic acids.  Double-check your settings (again, this isn't the correct place to provide CODEML support, so if you have trouble with this, I'll have to refer you to https://groups.google.com/d/forum/pamlsoftware.

**Comment by idolawoye** [comment]
Sorry about the``` Codeml()``` omission. I amended it but still the same outcome:
```
>>> from Bio.Phylo.PAML import codeml
>>> cml = codeml.Codeml()
>>> cml.alignment = r"C:\Users\Idowu\Downloads\paml\ref.phy"
>>> cml.tree = r"C:\Users\Idowu\Downloads\paml\ref.newick"
>>> cml.working_dir = r"C:\Users\Idowu\Downloads\paml"
>>> cml.out_file = r"C:\Users\Idowu\Downloads\paml\result.out"
>>> cml.run(verbose = True)
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    cml.run(verbose = True)
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\Phylo\PAML\codeml.py", line 184, in run
    results = read(self.out_file)
  File "C:\Users\Idowu\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\Phylo\PAML\codeml.py", line 204, in read
    raise ValueError("Invalid results file")
ValueError: Invalid results file
```

**Comment by peterjc** [comment]
At this point there does not seem to be a Biopython problem - rather something is wrong in your instructions to PAML's codeml tool.

Brandon has kindly suggested some things to check, but if you need help beyond that please try https://groups.google.com/d/forum/pamlsoftware

Anyway, thank you for reporting this here - thanks to this our next release will have a slightly clearer error message when the results file is empty - see #1709 .
