### ISSUE TITLE
While reading data for 29923177, we are getting incomplete abstractText

### ISSUE THREAD

**Issue by shivanand-cellworks** [biopython/biopython#1706]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

```
>>> import sys; print(sys.version)
3.5.1 (default, Apr  3 2018, 20:50:46) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-514.el7.centos.plus.i686-i686-with-centos-7.5.1804-AltArch
>>> import Bio; print(Bio.__version__)
```

### Expected behaviour
Should return full abstractText.

### Actual behaviour

Getting incomplete abstract for above mentioned PMID

### Steps to reproduce
Kindly fetch data for PMID  : 29923177

**Comment by peterjc** [comment]
I would guess you are trying to use ``Bio.Entrez`` in some way? Please fill in the steps to reproduce - probably four or five lines of Python code - along with the actual and expected output here.

**Comment by shivanand-cellworks** [comment]
Thank you for the quick reply. Below should be the code


'''
Sample Example to read Abstract
Author : Shivanand
'''
from Bio import Entrez
Entrez.email = 'shivgonda.birajdar@cellworksgroup.com'  # default 
developer's email as suggested by NCBI.
handle = Entrez.efetch(db='pubmed', retmode='xml', id=29923177)
xml_data = Entrez.read(handle)
print(xml_data['PubmedArticle'][0]['MedlineCitation']['Article']['Abstract']['AbstractText'])

Regards
Shivanand ...

**Comment by mdehoon** [comment]
Please try with Biopython 1.72 - I believe this bug has been fixed there.

**Comment by peterjc** [comment]
I agree, I think this is due to ``<sup>`` HTML tags in the abstract, a relatively recent NCBI change - see #1539

**Comment by swamyr** [comment]
Yes. It has fixed. Thank you all for your prompt reply and support.

**Comment by shivanand-cellworks** [comment]
Yes. It has fixed. Thank you all for your prompt reply and support.
