### ISSUE TITLE
Rate limit calls to NCBIWWW.qblast function

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1715]
We simplified the delay code in ``NCBIWWW`` for Biopython 1.72,

https://github.com/biopython/biopython/blob/biopython-172/Bio/Blast/NCBIWWW.py#L162

However, this does not currently impose a delay check between calls to the ``qblast`` function, and it should.

The simplest way to do this would be to store previous call time at function level as implemented in our Entrez and TogoWS code - see https://github.com/biopython/biopython/blob/biopython-172/Bio/Entrez/__init__.py#L538 and https://github.com/biopython/biopython/blob/biopython-172/Bio/TogoWS/__init__.py#L351

**Comment by Amrithasuresh** [comment]
@peterjc Is this issue still available? I would like to do this.

Do I need to add previous call time at qblast function  "_open.previous = 0" in the script?

**Comment by peterjc** [comment]
Earlier it looked like @yangwu91 was trying to do the delays as part of other work on #1732, but I don't think I was able to explain what I meant.

So yes @Amrithasuresh, please have a go at recording the time stamps via ``_open.previous = ...`` in BLAST, following the examples in Entrez and TogoWS.

**Comment by Amrithasuresh** [comment]
@peterjc I am trying to mimic the examples. Is it something like this? But the tests are failing it says 

> Bio/Blast/NCBIWWW.py:175:5: F821 undefined name '_open'

If you have time can you point some hints. I am also reading the help/doc.

`    delay = 20  # seconds
    current = time.time()
    _open.previous = 0
    while True:
        wait = _open.previous + delay - current
        if wait > 0:
            time.sleep(wait)
            _open.previous = current + wait
        else:
            _open.previous = current
        if delay < 60:
            # Wasn't a quick return, must wait at least a minute
            delay = 60`

**Comment by peterjc** [comment]
In TogoWS and Entrez, there is a locally defined private function ``_open`` and we've recorded the last used time as an attribute of that function. e.g.

Function definition:
https://github.com/biopython/biopython/blob/biopython-172/Bio/Entrez/__init__.py#L494

Creating the attribute immediately after function definition:
https://github.com/biopython/biopython/blob/biopython-172/Bio/Entrez/__init__.py#L538

In this case, we don't have an ``_open`` function, rather it is called ``qblast`` instead.

**Comment by Amrithasuresh** [comment]
@peterjc Let me if this ok.

**Comment by peterjc** [comment]
Closed via #1807
