### ISSUE TITLE
Deprecate ParseBlastTable?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1721]
This bit of code ``Bio/Blast/ParseBlastTable.py`` has no unit tests, and has had only maintaince updates (e.g. style changes) since @idoerg wrote it in 2003. It targets a niche part of the BLAST suite output:

> A parser for the NCBI blastpgp version 2.2.5 output format.
>
> Currently only supports the '-m 9' option, (table w/ annotations).
> Returns a BlastTableRec instance

Cross reference https://redmine.open-bio.org/issues/2319 filed by  Xizeng Mao on 2007-06-13,

> Bio/Blast/ParseBlastTable.py in BioPython 1.4.3 only supports BLASTP (-m 9)), but can't get any record when parsing the output from BLASTX (-m 9), cause ParseBlastTable.py always checks if the keyword 'BLASTP' exists in output file. This patch adds support for BLASTX besides BLASTP

```diff
38c38
< reader_keywords = {'BLASTP': 'version',
---
> reader_keywords = {'BLAST': 'version',
48c48
<       while inline and inline.find('BLASTP') == -1:
---
>       while inline and inline.find('BLAST') == -1:
102,103d101
<       
< 
```

To which @mdehoon replied:

> Whereas the patch seems to be correct, I am not sure if the code in Bio/Blast/ParseBlastTable.py is still relevant. The current Biopython tests for blastpgp output use the Bio/Blast/NCBIStandalone parser, which itself is superseded by the XML parser in Bio/Blast/NCBIXML.py. When I tried, the parser in Bio/Blast/ParseBlastTable failed to parse the blastpgp output in the Biopython tests.
>
> Can you use blastpgp with "-m 7" to get XML output, and use the XML parser? If the XML parser works fine for you, I'll ask on the mailing list if Bio/Blast/ParseBlastTable.py can be deprecated.

**Comment by peterjc** [comment]
See also discussion on https://redmine.open-bio.org/issues/2929 filed by Miguel, on 2009-10-15

> With the problems encountered while parsing plain text output from blastpgp, perhaps an answer would be to use the XML output of this program. The XML output seems to have evolved in recent versions of blastpgp and now all the info gets in a single proper XML file (not several concatenated files) and, in principle, it would seem that all the information in the plain text format can also be found in the XML one.
>
> I will attach an XML output for a PSI-Blast search that converges after 3 passes.
>
> blast.xml - XML output from a converged run of blastpgp (59.2 KB)

We may not be capturing everything in the blastpgp XML, but it seems a good replacement for the text output table.

**Comment by mdehoon** [comment]
Deprecated in  #4070 .
