### ISSUE TITLE
Save the output of Alignment

### ISSUE THREAD

**Issue by peterhabib** [biopython/biopython#1729]
i trying to save the output of alignment in fasta file but still have problem with that

I am reporting a problem with biopython-1.71, Python version 3.4, and operating
system Ubuntu (bio-linux)

from Bio import pairwise2
from Bio.pairwise2 import format_alignment
from Bio import AlignIO
from Bio import SeqIO
alignments = pairwise2.align.globalxx("ACCCGTAAGCTACGGTCAGT", "ACTCGATACGGTCTGACG")
print(format_alignment(*alignments[0]))
alignments = format_alignment(*alignments[0])
with open("example.faa", "w") as handle:
    count = SeqIO.write(alignments, handle, "fasta")

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

save the alignment like the following in file: 
ACC-CGTAAGCTACGGTC--A-GT
| | ||  |  |||||||  | | 
A-CTCG--A--TACGGTCTGACG-
  Score=14

### Actual behaviour

/usr/bin/python3.4 /home/peter/44.py
ACC-CGTAAGCTACGGTC--A-GT
| | ||  |  |||||||  | | 
A-CTCG--A--TACGGTCTGACG-
  Score=14

Traceback (most recent call last):
  File "/home/peter/44.py", line 9, in <module>
    count = SeqIO.write(alignments, handle, "fasta")
  File "/usr/local/lib/python3.4/dist-packages/Bio/SeqIO/__init__.py", line 497, in write
    count = writer_class(fp).write_file(sequences)
  File "/usr/local/lib/python3.4/dist-packages/Bio/SeqIO/Interfaces.py", line 215, in write_file
    count = self.write_records(records)
  File "/usr/local/lib/python3.4/dist-packages/Bio/SeqIO/Interfaces.py", line 200, in write_records
    self.write_record(record)
  File "/usr/local/lib/python3.4/dist-packages/Bio/SeqIO/FastaIO.py", line 273, in write_record
    id = self.clean(record.id)
AttributeError: 'str' object has no attribute 'id'

**Comment by peterjc** [comment]
The ``pairwise2`` module does not make ``SeqRecord`` objects - you need to do that, which means giving your sequences identifiers. This seems like a good thing to add to our documentation.

Also, with Biopython 1.72 (latest release) there is a newer alternative alignment tool under ``Bio.Align``, you might want to look at that (the tutorial was updated).

**Comment by peterhabib** [comment]
when i use the normal code to save which is this:
file = open('Alignment.txt', 'w')
file.write(alignments)
file.close()

the alignment in file is disrupted and overlapped (please, find the attached result file for more clarification)
[Alignment.txt](https://github.com/biopython/biopython/files/2175934/Alignment.txt)

**Comment by peterjc** [comment]
That output is not intended to be viewed with line wrapping. It is not actually very helpful once the alignment is longer than a screen width.

**Comment by MarkusPiotrowski** [comment]
It also depends on your text editor (e.g. how it handles line wrapping). In Notepad ++ it looks OK

**Comment by peterjc** [comment]
You could probably just do something like this, untested, working with the raw strings:

```python
for align1, align2, score, begin, end:
    filename = "generate_name_here.fasta"
    with open(filename, "w" as handle:
        handle.write(">A\n%s\nB\n%s\n" % (align1, align2)
```

Ideally you can give the two sequence better names than A and B.

**Comment by peterhabib** [comment]
@peterjc  

can you give me working Example using your code?
for align1, align2, score, begin, end in alignments:
    filename = "generate_name_here.fasta"
    with open(filename, "w" as handle:
        handle.write(">A\n%s\nB\n%s\n" % (align1, align2)

**Comment by peterjc** [comment]
I had a few typos in the snippet above, this has been tested:

```python
from Bio import pairwise2
from Bio.pairwise2 import format_alignment
from Bio import AlignIO
from Bio import SeqIO

alignments = pairwise2.align.globalxx("ACCCGTAAGCTACGGTCAGT", "ACTCGATACGGTCTGACG")

for index, (align1, align2, score, begin, end) in enumerate(alignments):
    filename = "alignment_%i.fasta" % index
    with open(filename, "w") as handle:
        handle.write(">A\n%s\n>B\n%s\n" % (align1, align2))
print("Done")
```

**Comment by peterhabib** [comment]
Wow! Thank you Very much

**Comment by peterjc** [comment]
Great - can you see a good place to add an example like this to the current tutorial?

(Note the pairwise alignment section changed quite a bit with Biopython 1.72's release)

Otherwise I think we can close this issue. Thanks!

**Comment by peterhabib** [comment]
i think you should add it at the end of multiple sequence alignment chapter to describe how dealing with outpout of alignment in another way other than AlignIO.Write()

**Comment by michaelsilverstein** [comment]
For a quick visualization of large alignments, I found it helpful to "chunk" up the alignment into segments of size `n`. This is kind of trivial for such a short alignment, but I found helpful for alignments of hundreds of base pairs:

```python
# Perform alignment
aln = pairwise2.align.globalxx("ACCCGTAAGCTACGGTCAGT", "ACTCGATACGGTCTGACG")
# Get sequences
a, b = aln[:2]
# Choose a chunk size
n = 100
# Chunk each sequence according to size
chunked = [[a[i: i+n], b[i: i+n]] for i in range(0, len(a), n)]
# Asses matches for each chunk
matches = [''.join(['|' if chunk[0][i]==chunk[1][i] else ' ' for i in range(len(chunk[0]))]) for chunk in chunked[:]]
# Print
for c, m, i in zip(chunked, matches, range(len(chunked))):
    txt = '%s to %s' % (i*n+1, i*n+n)
    print(txt)
    print(c[0])
    print(m)
    print(c[1])
    print()
```
Output:
```
1 to 10
ACC-CGTAAG
| | ||  | 
A-CTCG--A-

11 to 20
CTACGGTC--
 |||||||  
-TACGGTCTG

21 to 30
A-GT
| | 
ACG-
```

**Comment by JHANSI-G** [comment]
@Michaelsilverstein

I have tried your code. I really like the idea of chunking the alignment as my sequences are 2000bp long, alignment is disrupted when i view it on text editor.

But the output of the code came as

1 to 5
('ACC-CGTAAGCTACGGTC--A-GT', 'A-CTCG--A--TAC--TCTGACG-', 12.0, 0, 24)
| |||
('ACC-CGTAAGCTACGGTC--A-GT', 'AC-TCG--A--TAC--TCTGACG-', 12.0, 0, 24) 

I request you to kindly help me fix this code!

**Comment by MarkusPiotrowski** [comment]
@JHANSI-G Please try:
```python
# Get sequences
a, b = aln[0][:2]
```

`pairwise2` returns a list of alignments, so before chunking the aligned sequences, you need to select which alignment. In global alignments there will always be at least one alignment, so it's safe to check for the first (`aln[0]`).

**Comment by JHANSI-G** [comment]
@MarkusPiotrowski

Wow!! it worked. Thank you so much
