### ISSUE TITLE
Addition of a `Seq.join()` method

### ISSUE THREAD

**Issue by widdowquinn** [biopython/biopython#1731]
### Setup

I would like to be able to use the string-like concatenation/addition behaviour of `Seq` objects in the same way as using `'some_string'.join()`, but this behaviour is not currently available.

### Expected behaviour

```python
spacer = Seq('NNNNN')
seqlist = list(SeqIO.parse('myfile.fasta', 'fasta'))
concatenated = spacer.join(seqlist)
```

### Actual behaviour

Not implemented.

I appreciate that this is a minefield for resolving alphabets…

**Comment by widdowquinn** [comment]
Yeah, sorry about the mix-up of classes with `SeqIO.parse()` there… ;)

**Comment by kaskales** [comment]
@peterjc I see this issue is still open. Is it ok if I give it a shot as well?

**Comment by peterjc** [comment]
@kaskales did you have any thoughts on examples like ``Seq("").join(some_dna_seqs)`` vs ``Seq("", some_generic_alphabet).join(some_dna_seqs)`` where in some senses the default/generic alphabet of the empty sequence space is not important for the combined sequence (which in this example might be expected to be DNA from the alphabet attributes set in ``some_dna_seqs``)

**Comment by peterjc** [comment]
Yes, I'm talking about the special case where the spacer is a zero length sequence.

**Comment by peterjc** [comment]
Applied as e856cd3d1896814ed3f83b73391098d539e4ff8c from #1746. Thank you all.
