### ISSUE TITLE
Automatically fix bad origin wrapping locations in GenBank/EMBL?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1745]
Given a circular plasmid of say 7000bp, some tools producing GenBank format files are known to represent origin spanning locations as ``6800..100`` rather than the expected more explicit notation ``join(6800..7000,1..100)`` as used by the NCBI GenBank files. Likewise for reverse complement strand origin wrapping.

* Biopython up to 1.70 would parse locations like ``6800..100`` without error or warning, but create inconsistent location objects (e.g. ``len(...)`` would fail).
* Biopython 1.71 would error when parsing these locations due to #1497 which enforces the location object model expectation that start <= end.
* Biopython 1.72 would give a warning when parsing these locations, and leave the problem feature(s) with a location of ``None`` (see pull request #1657). This followed discussion on issues #1608 and other duplicate reports stemming from the same changes.

The complete failure to parse these invalid files in Biopython 1.71 was an unfortunate regression. I believe that the behaviour in Biopython 1.72 is reasonable and consistent with other problematic parsing issues where we do something reasonable and give a warning.

This issue is about if we should go further and recognise these invalid origin wrapping features as a special case, giving a warning, but then automatically upgrade the invalid locations to the presumed intended meaning using as if an explicit join had been used.

Although this has only been reported with GenBank format, EMBL flat files share the same INSDC table format, so the same issue likely applies there too.

Referring to the Zen of Python, https://www.python.org/dev/peps/pep-0020/

> *Special cases aren't special enough to break the rules.*
> *Although practicality beats purity.*
> *Errors should never pass silently.*

There is a case for practicality here - provided the problematic location usage is really widespread. @Zulko is unlikely to be alone in finding this a problem.

**Comment by nimne** [comment]
I think that it is reasonable to throw a warning, then try to fix it. I've done my best to [implement this](https://github.com/biopython/biopython/compare/master...nimne:Origin_wrapping), and it seems like it works well. Are there any unusual situations where a notation like `6800..100` would be ambiguous, or cases where an origin wrap would have anything except the two positions? It seems like the intention is clear enough that an automatic fix should be okay.

Implicitly fixing the poorly formatted origin wrapping should probably only occur when the genome is explicitly defined as circular, although this doesn't address the recent comment in #1608 where the topology is undefined and there is a feature spanning the presumed origin. 

With features that span the origin, finding the start and stop location on something like `6800..100` results in odd behavior, where the start is 100, and the end is 6800, but that is a bigger problem than fixing the formatting.

**Comment by peterjc** [comment]
@nimne If you want to submit a pull request for this, that'd be great. Your basic approach is what I had in mind (including checking the reference was declared as circular).

Note that I think you need to be careful about the order of the two child locations depending on the strand. The best check for this would be verifying the sequence the ``.extract()`` method pulls out is correct (e.g. for an origin spanning feature check the translation).

**Comment by peterjc** [comment]
I've merged the pull request from @nimne which implements this. So, continuing the bullet points:

* Biopython up to 1.70 would parse locations like ``6800..100`` without error or warning, but create inconsistent location objects (e.g. ``len(...)`` would fail).
* Biopython 1.71 would error when parsing these locations due to #1497 which enforces the location object model expectation that start <= end.
* Biopython 1.72 would give a warning when parsing these locations, and leave the problem feature(s) with a location of ``None`` (see pull request #1657). This followed discussion on issues #1608 and other duplicate reports stemming from the same changes.
* Biopython 1.73 will, providing the reference is labelled as circular, give a warning and treat the location as if it was a join spanning the origin. If the reference is not labelled as circular you get a warning and a location of ``None``.

Thank you everyone for your input.
