### ISSUE TITLE
What is return params for Gompertz function?

### ISSUE THREAD

**Issue by jianlianggao** [biopython/biopython#1751]
Hi Bjorn,

I am trying to use your Python code to fit my data with Gompertz function. I want to plot the fitting results, but I am not sure your fit function return Gompertz parameters in the order of (A, u, d, v, y0). When I assumed they were in the order of (A, u, d, v, y0), I got an almost horizontal line rather than a growth curve. Looking for your advise please. Many thanks,

BW,
Jianliang

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
CPython
Windows-10-10.0.17134

I don't use the whole "Bio" package. I only copied the gompertz and dependant functions for my use.
### Expected behaviour

(*Please fill this in*)
a curved fitting line.
### Actual behaviour
a flat line.
[sample_data_.zip](https://github.com/biopython/biopython/files/2280544/sample_data_.zip)

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce
I set the maxfev to 6000 in the function of curve_fit. The data I used were from male, x= age, y= volume_gm/volume_brain.

(*Please fill this in *)

**Comment by peterjc** [comment]
Are you asking about the Gompertz  function in ``Bio/phenotype/pm_fitting.py``?

You have not filling in an example of the code you are using, which is very helpful for understanding a bug report.

CC @mgalardini

**Comment by peterjc** [comment]
Also you have not copy-and-pasted the version information we ask for, which is again very important for understanding bug reports.

**Comment by jianlianggao** [comment]
Hi Marco,

Thank you very much for this. I played with the initial of p0 and when I used 1.2 and 0.1 rather than 4.0 and 0.1, I got  nice gompertz fitting using the fit function in Biopython, same as the red line in your plot.

Best wishes,
Jianliang
