### ISSUE TITLE
bwa mem support for Bio::Sequencing::Applications::_bwa 

### ISSUE THREAD

**Issue by JohnMCMa** [biopython/biopython#1756]
This is more of an Enhancement request.

As most of us know bwa has implemented the mem mode for quite a while. However, while Biopython has wrappers for bwa aln, samse, sampe and samsw, there is no wrapper for the mem alignment, which is frequently used. I think a wrapper for bwa mem is urgently needed.

**Comment by peterjc** [comment]
True - @saketkc as the original wrapper author, do you want to do this, or would you be happy for someone else to volunteer?

**Comment by VishwanathRavula** [comment]
Apologies for hijacking this platform for knowing something trivial.I am very much interested in contributing to OBF organisation, but don't from which project to start with.I am interested in this organisation regardless of technology. Could someone help me out.

**Comment by peterjc** [comment]
@VishwanathRavula If you want to contribute to one of the Bio* projects, look at their mailing lists and GitHub trackers. Biopython has labeled some of its issues as suitable for first-time contributors for example, see also our CONTRIBUTING file - https://github.com/biopython/biopython/blob/master/CONTRIBUTING.rst

Outside of that, you might be able to help with the OBF's annual meeting BOSC https://www.open-bio.org/wiki/BOSC - or perhaps the newsletter - see https://github.com/OBF/newsletter

However, commenting on issue with a completely unrelated question is not a good idea. Please do not do that - you are interrupting this discussion which was meant to be about the BWA wrapper in Biopython.

[I'm going to hide your question and my reply in a moment; you'll have got this by email though]

**Comment by saketkc** [comment]
Hi @peterjc, I will not have the bandwidth to do this for the next couple of months or so. Happy to review a PR though. @VishwanathRavula would you be interested? The relevant file is [here]( https://github.com/biopython/biopython/blob/master/Bio/Sequencing/Applications/_bwa.py) 
and the relevant manual page is [here](http://bio-bwa.sourceforge.net/bwa.shtml)

**Comment by peterjc** [comment]
Or @JohnMCMa? You actually want to use bwa-mem so would be in a better position to update the wrapper and test it for real.

**Comment by JohnMCMa** [comment]
Hi @peterjc, maybe I should try this out a bit.

**Comment by JohnMCMa** [comment]
I have written the code for it, but I'll test the code and study `CONTRIBUTING.rst` and make sure I have checked all boxes before I make a pull request.

**Comment by peterjc** [comment]
OK - if you can run the style checks locally that will make the pull request go more smoothly. Thanks!

**Comment by JohnMCMa** [comment]
You are welcome.

**Comment by JohnMCMa** [comment]
Since pull request #1790 is merged, I'm closing this as resolved.
