### ISSUE TITLE
docs - tutorial - blast - UML diagram out of date

### ISSUE THREAD

**Issue by notestaff** [biopython/biopython#1765]
@peterjc the UML diagram at https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_blast.tex#L445
is out of date; a number of fields are missing.

**Comment by peterjc** [comment]
Yes. Quoting the link you linked to:

> Here are my attempts at UML class diagrams for the \verb|Blast| and \verb|PSIBlast| record classes. If you are good at UML and see mistakes/improvements that can be made, please let me know. The Blast class diagram is shown in Figure~\ref{fig:blastrecord}.

This was written by @chapmanb in https://github.com/biopython/biopython/commit/4f535baa8e768ac6b90aeace1641f4fe539a6995 back in 2000, and sadly no one has stepped up to update the UML diagrams.

Can you help?

Quoting from the original header of the combined tutorial

```
% You will also need the pictures included in the document, which are
% UMLish diagrams created by Dia
% (http://www.lysator.liu.se/~alla/dia/dia.html).
% These diagrams are available from Biopython CVS in the original dia
% format, which you can easily save as .png format using Dia itself.
% They are also checked in as the png files, so if you make
% modifications to the original dia files, the png files should also be
```

The source files still exist, see https://github.com/biopython/biopython/tree/master/Doc/images

The tool Dia still exists, https://wiki.gnome.org/Apps/Dia/ last release in 2011.

It might be simpler to recreate them in some more modern software?

**Comment by svalqui** [comment]
I'll have a look at this.

**Comment by peterjc** [comment]
CLose
