### ISSUE TITLE
test_PopGen_GenePop_EasyController fails

### ISSUE THREAD

**Issue by nimne** [biopython/biopython#1777]
### Setup
`./Tests/run_tests.py test_PopGen_GenePop_EasyController` fails

Biopython versions tested: 1.72, 1.73dev0
Python versions: 2.7.15, 3.6.6, 3.7.0
Operating system: MacOS and Debian
Genepop versions tested: 4.7.0

### Expected behaviour

```
python ./Tests/run_tests.py test_PopGen_GenePop_EasyController
Python version: 2.7.15 (default, Jul 23 2018, 21:27:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
Operating system: posix darwin
test_PopGen_GenePop_EasyController ... ok
```

### Actual behaviour
```
python ./Tests/run_tests.py test_PopGen_GenePop_EasyController
Python version: 2.7.15 (default, Jul 23 2018, 21:27:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
Operating system: posix darwin
test_PopGen_GenePop_EasyController ... FAIL
======================================================================
ERROR: test_hwe_excess (test_PopGen_GenePop_EasyController.AppTest)
Test Hardy-Weinberg Equilibrium.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nick/git/biopython/Tests/test_PopGen_GenePop_EasyController.py", line 96, in test_hwe_excess
    hwe_excess = self.ctrl.test_hw_pop(0, "excess")
  File "/Users/nick/git/biopython/build/lib.macosx-10.13-x86_64-2.7/Bio/PopGen/GenePop/EasyController.py", line 43, in test_hw_pop
    return next(hw_res)
  File "/Users/nick/git/biopython/build/lib.macosx-10.13-x86_64-2.7/Bio/PopGen/GenePop/Controller.py", line 165, in next
    return self.__next__()
  File "/Users/nick/git/biopython/build/lib.macosx-10.13-x86_64-2.7/Bio/PopGen/GenePop/Controller.py", line 160, in __next__
    return self.func(self)
  File "/Users/nick/git/biopython/build/lib.macosx-10.13-x86_64-2.7/Bio/PopGen/GenePop/Controller.py", line 264, in hw_func
    return _hw_func(self.stream, False)
  File "/Users/nick/git/biopython/build/lib.macosx-10.13-x86_64-2.7/Bio/PopGen/GenePop/Controller.py", line 132, in _hw_func
    raise StopIteration
StopIteration

----------------------------------------------------------------------
Ran 1 test in 1.495 seconds

FAILED (failures = 1)
```

### Steps to reproduce

Install GenePop v4.7 from: http://kimura.univ-montp2.fr/~rousset/Genepop.htm
Run test_PopGen_GenePop_EasyController (or the biopython test suite)

### Probable cause

The `_hw_func` function is called in  `Bio/PopGen/GenePop/Controller.py` . This appears to parse through the GenePop output and looks for the lines that start with `Pop :`.

It looks like there is an extra space before `Pop :` in the function. Deleting the space lets the test pass, working branch [here](https://github.com/biopython/biopython/compare/master...nimne:fix_GenePop_test).
```python
def _hw_func(stream, is_locus, has_fisher=False):
    line = stream.readline()
    if is_locus:
        hook = "Locus "
    else:
        hook = " Pop : "
    while line != "":
        if line.startswith(hook):
```

The output that is parsed looks something like this (extra line-breaks removed for this example):
```
Genepop 4.7.0: Hardy-Weinberg test
...
==========================================
     Results by population
==========================================

Pop : Ind31
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
Locus1      0.4955    -     -0.1600 -0.1623      5 matrices
Locus2      0.6844    -     -0.1111 -0.1127      4 matrices
Locus3      0.9956    -      0.3919  0.4009     12 matrices
...
```
I am unable to find other versions of GenePop to test. It's not clear to me if this is a change in GenePop, or an error in the code. The GenePop changelog doesn't provide any clarity. I'm not a regular user of GenePop, so additional clarity from regular users would be helpful!

**Comment by peterjc** [comment]
I still have GenePop 4.6 installed locally on macOS, and ``test_PopGen_GenePop_EasyController.py`` passes. Unfortunately I don't seem to have the source code anymore.

It is frustrating that the authors only seem to host the latest v4.x release (i.e. they replaced v4.6 with v4.7). If need be we could try emailing them about keeping the older releases available for historical back-ward compatibility.

However, this does support your guess that it is a minor change to the tool's output - and it ought to be possible to tweak our parser to cope with either variants. If you want to make a pull request doing this, I can test it with GenePop 4.6 to confirm that still works.

CC @tiagoantao

**Comment by tiagoantao** [comment]
I will have a look at this tomorrow. Not in front of the computer today

**Comment by tiagoantao** [comment]
Thanks @nimne
