### ISSUE TITLE
Adding makeblastdb to the BLAST wrappers

### ISSUE THREAD

**Issue by nimne** [biopython/biopython#1788]
I'd like to work on adding `makeblastdb` to the BLAST command wrappers. This is to address a comment in #1463 as well as my own needs. As far as I'm aware, I haven't seen anyone else working on this!

Opening this issue as a discussion location separate from #1463

**Comment by peterjc** [comment]
Sounds sensible, thank you for working on this.

**Comment by peterjc** [comment]
Closed via #1800
