### ISSUE TITLE
Dead references in the Tutorial

### ISSUE THREAD

**Issue by sars1492** [biopython/biopython#1826]
DISCUSSION

The Tutorial contains several dead references to external sites. I have tried to google them out, but I struggled to find an actual working website of any of these projects.

The main point of this discussion is whether or not these references should be removed from the Tutorial or replaced by other references.

The list of the dead references I have found:

- [x] http://www.chem.qmw.ac.uk/iupac/ in the [chapter_seq_objects.tex](https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_seq_objects.tex) should contain details about IUPAC alphabets. I have proposed to replace the link with https://www.bioinformatics.org/sms/iupac.html instead (see Pull Request #1825).

- [x] http://pfam.sanger.ac.uk/family?acc=PF05371 in the [chapter_seqio.tex](https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_seqio.tex). The Sanger apparently no longer provides any Web interface for PFAM. I have no idea how did the deprecated interface look like and whether the [PFAM website](https://pfam.xfam.org/) provides a Web interface covering all its functionality.

- [x] http://blast.wustl.edu/ in the [chapter_blast.tex](https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_blast.tex) should be Washington University BLAST (WU-BLAST) website. The most recent reference to any WU-BLAST site given by the Google search results is ten years old. It seems that the WU-BLAST is obsolete for a long time.

- [ ] http://www.expasy.org/cgi-bin/sprot-search-de and http://www.expasy.org/cgi-bin/sprot-search-ful  in the [chapter_uniprot.tex](https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_uniprot.tex)  should contain details about search fields in *Swiss-Prot* but they have been moved to other location on the [UniProt](https://www.uniprot.org/) website. I think we should reference corresponding pages on the UniProt website; however, I have no idea whether the UniProt website contains such pages, and if it does, where to find them.

- [ ] http://www.columba-db.de/ in the [chapter_pdb.tex](https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_pdb.tex) does no longer provide annotated protein structures. I have no idea whether this database still works. If not, we should remove it from the Tutorial.

- [x] http://pazar.info in the [chapter_pdb.tex](https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_pdb.tex)  is not available. The [Sourceforge](https://sourceforge.net/projects/pazar/) page still works, but it does not contain many details about the project. The only external reference on the Sourceforge page is http://pazar.info that is known to be dead.

**Comment by peterjc** [comment]
The first one is easy, http://www.sbcs.qmul.ac.uk/iupac/ - see https://github.com/biopython/biopython/pull/1825#discussion_r223282531

**Comment by peterjc** [comment]
Regarding PAZAR, you had a typo - this is in the motifs chapter, https://github.com/biopython/biopython/blob/biopython-172/Doc/Tutorial/chapter_motifs.tex#L206 and is/was used in JASPAR. Over to @mdehoon for that one.

**Comment by peterjc** [comment]
The WU BLAST link and text still seem fine to me,

```
You may also come across \href{http://blast.wustl.edu/}{Washington University BLAST}
(WU-BLAST), and its successor, \href{http://blast.advbiocomp.com}{Advanced Biocomputing
BLAST} (AB-BLAST, released in 2009, not free/open source).
```

https://github.com/biopython/biopython/blob/biopython-172/Doc/Tutorial/chapter_blast.tex#L251

(Although as per #1825 we can use HTTPS now)

**Comment by peterjc** [comment]
The PFAM example should I think now point at http://pfam.xfam.org/family/PF05371 - if you agree could you include this in #1825 please?

**Comment by peterjc** [comment]
For http://www.expasy.org/cgi-bin/sprot-search-de and http://www.expasy.org/cgi-bin/sprot-search-ful see #253, which I'd forgotten about.

**Comment by sars1492** [comment]
> The WU BLAST link and text still seem fine to me,
> 
> ```
> You may also come across \href{http://blast.wustl.edu/}{Washington University BLAST}
> (WU-BLAST), and its successor, \href{http://blast.advbiocomp.com}{Advanced Biocomputing
> BLAST} (AB-BLAST, released in 2009, not free/open source).
> ```
> 
> https://github.com/biopython/biopython/blob/biopython-172/Doc/Tutorial/chapter_blast.tex#L251
> 
> (Although as per #1825 we can use HTTPS now)

OK
WU-BLAST webpage does not have HTTPS. We should leave HTTP.

**Comment by peterjc** [comment]
I think a pull request removing the reference to http://www.columba-db.de/  would make sense.

**Comment by chebizarro** [comment]
With the deprecation of `sprot_search_ful` (#253) and the removal of `http://www.columba-db.de/` (#3103) can we consider this issue resolved?

**Comment by peterjc** [comment]
BCC2020 CoFest Bug triage - thank you, closing.
