### ISSUE TITLE
Fastq parser: retrive original quality string in addition to Phred Scores

### ISSUE THREAD

**Issue by romagnolid** [biopython/biopython#1828]
To my knowledge the only way to retrive the orginal string is to split the representation of the record.
```python
>>> print(record.format("fastq")).split()[4])
GGGGGIIIIGGAGG<GGG.<GA.<GGGGGA..<..<<GGGIA<GAAGGIGGGAGGGGIIAAG#####
```
Personally I think it would be better if each record had a `record.quality` property.
Something like this:
```python
>>> print(record.quality)
GGGGGIIIIGGAGG<GGG.<GA.<GGGGGA..<..<<GGGIA<GAAGGIGGGAGGGGIIAAG#####
```

**Comment by peterjc** [comment]
If you are using FASTQ files via ``Bio.SeqIO`` you get ``SeqRecord`` objects where the quality string has been decoded into integer values, accessible as ``record.letter_annotations["phred_quality"]``. This object model tries to be file format neutral, and as such adding a ``.quality`` attribute would be too narrow in scope.

If you actually want the (original) FASTQ ASCII string, don't use the high level ``Bio.SeqIO`` API, instead use ``from Bio.SeqIO.QualityIO import FastqGeneralIterator`` and work with a tuple of strings (the title line, sequence, and quality string). See e.g.

https://news.open-bio.org/2009/09/25/biopython-fast-fastq/
http://biopython.org/DIST/docs/api/Bio.SeqIO.QualityIO-module.html#FastqGeneralIterator
https://github.com/biopython/biopython/blob/biopython-172/Bio/SeqIO/QualityIO.py#L800

This alternative is covered in the Tutorial too:

http://biopython.org/DIST/docs/tutorial/Tutorial.html

Do you see anything in the documentation we could improve this?

**Comment by romagnolid** [comment]
I realized I missed this line from the tutorial http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc68
_If you don’t need the quality scores turned into integers, or can work with them as ASCII strings [...]_

The only minor improvement in the documentation I could think of is to highlight that the quality string is present  in the tuple produced by `FastqGeneralIterator` but I'm just nitpicking.
Thank you for the clarification.
