### ISSUE TITLE
Improve documentation of Bio.codonalign.build() function

### ISSUE THREAD

**Issue by vanya-antonov** [biopython/biopython#1840]
I am new to the github and this is my first post, so I am sorry if it is not very appropriate..

Anyway, I was thinking to use Biopython to create a nucleotide alignment based on a protein alignment, i.e. to do what was asked on Biostars a while ago: https://www.biostars.org/p/89741/

Apparently, this Biopython function was developed to help with similar tasks. However, the example from this function documentation may be a bit confusing because the final nucleotide alignment has a single gap while I would only expect triple-gaps in a codon alignment:
```
>>> print(codon_aln)
    CodonAlphabet(Standard) CodonAlignment with 2 rows and 69 columns (23 codons)
    TCAGGGACTGCGAGAACCAAGCTACTGCTGCTGCTGGCTGCGCTCTGCGCCGCAGGT...GAG pro1
    TCAGGGACTTCGAGAACCAAGCG-CTCCTGCTGCTGGCTGCGCTCGGCGCCGCAGGT...GAG pro2
```

I think that the original idea of this example was to demonstrate that the function is able to handle frameshifts caused by single nucleotide insertions. At the same time this may not be the most important feature of the function and an example that converts a single gap from a protein alignment into triple gaps in the nucleotide one may be more informative.

**Comment by peterjc** [comment]
Which bit of the Biopython documentation specifically are you referring to?

**Comment by vanya-antonov** [comment]
Hello Peter,
I am talking about this part from the "biopython/Bio/codonalign/__init__.py" file:
https://github.com/biopython/biopython/blob/868b63d1af71650d247d70ba5ea4f82f6c732c61/Bio/codonalign/__init__.py#L33-L64

**Comment by peterjc** [comment]
Could you contribute a more typical example to insert above this one?

**Comment by vanya-antonov** [comment]
BTW, there is also a typo in the documentation. The second argument of the function is `nucl_seqs`, however in the documentation it is called `nucl_align`:
https://github.com/biopython/biopython/blob/868b63d1af71650d247d70ba5ea4f82f6c732c61/Bio/codonalign/__init__.py#L37

I believe `nucl_align` should be changed `nucl_seqs` in documentation.

**Comment by peterjc** [comment]
That sounds good - do you fancy turning this into a pull request? You can do it all from the GitHub website if you like (without running git at the command line).
