### ISSUE TITLE
premature end in GenBank

### ISSUE THREAD

**Issue by hmkim** [biopython/biopython#1846]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-18.2.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.72
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Parsing sucessfully 

### Actual behaviour

$ time python ../oligo-designer/test/brandon/validat_gb.py

<img width="806" alt="2018-11-10 10 25 29" src="https://user-images.githubusercontent.com/4966343/48301851-8f017700-e537-11e8-92e3-25a16552ebff.png">

### Steps to reproduce

When I tried to genbank from NCBI using API, I had some premature record in genbank.
so, I want to check and pass the record in genbank file.

How can I handle this problem ?

**Comment by peterjc** [comment]
It appears the parser is correct, the record ends part way though the CDS feature's translation with the start if what looks like an NCBI XML page (possibly an error message). i.e. It should fail validation, and you got a ValueError = Good.

Can you confirm this by looking at the raw GenBank file in a text editor or similar?

**Comment by hmkim** [comment]
@peterjc  I know it. but I want to pass for this entry. 
becuase..
Sometimes, when I download the genbank from NCBi using API, some record had  premature end. 
so, I want to pass for premature entry.  (like try.. except in Python)
Could you suggest the code  related to this issue ?

**Comment by peterjc** [comment]
You can see how Kai Blin uses Biopython to do a basic validation of GenBank or FASTA files downloaded from the NCBI here.

https://github.com/kblin/ncbi-acc-download/blob/master/ncbi_acc_download/validate.py

As you suggest, he uses a try/except catching ValueError (like your example) or AssertError (see also #933, we should replace those with ValueError or similar).

Note he checks the parser finds at least one record - as the parsers treat an empty file as valid in FASTA or GenBank format. If you know the expected record identifier, you could check that matches too.

**Comment by hmkim** [comment]
Thank you for suggestion!
I'll try to solving issue based on your suggestion.
