### ISSUE TITLE
[Discussion] generate_random_dna.py script

### ISSUE THREAD

**Issue by vanya-antonov** [biopython/biopython#1874]
Hello,

I know this has been asked before ( https://lists.open-bio.org/pipermail/biopython/2004-June/002140.html ), but I have a simple script that generates random DNA sequences with specific GC content:
https://github.com/vanya-antonov/ivanya_python/blob/master/scripts/baseutil/bio/generate_random_dna.py

Do you think it may be useful to the Biopython users? If so, I will be happy to donate it to the project.

BTW, I have written tests for this script as well:
https://github.com/vanya-antonov/ivanya_python/blob/master/scripts/baseutil/bio/test_generate_random_dna.py

**Comment by peterjc** [comment]
The core code here is actually very simple - most of your work is wrapping this up into a usable command line script. However, Biopython doesn't currently ship a set of scripts for command line use - other people have made packages to do so (e.g. expose the file converting abilities of ``Bio.SeqIO`` as a script). So unfortunately, my feeling is no, this would not be relevant contribution. You are welcome to suggest this on the mailing list which might generate more discussion?

What might be more interesting is functions to generate  random sequences with properties beyond single letter composition, for example also considering dimers, trimers etc. This might fit in with codon usage - for which there is already some code in Biopython?

**Comment by peterjc** [comment]
I should clarify that while we do have things in the folder ``Scripts/`` these are more like examples or for internal use - and are not added to the ``$PATH`` as part of a standard installation of Biopython.

**Comment by vanya-antonov** [comment]
Indeed, the `Scripts/` folder is what got me confused:) Thanks for the quick answer, Peter!
