### ISSUE TITLE
PDBList does not have the option to retrieve the 'biological assembly file'

### ISSUE THREAD

**Issue by jasiozaucha** [biopython/biopython#1875]
PDBList does not have the option to retrieve the 'biological assembly file'.

The file_format="bundle" option usually returns 
"Desired structure doesn't exists"

Can anyone explain how to overcome this?
As an example, try downloading the 'biological assembly file' for PDB '2exs'. At the moment I can only achieve this by using the PDB website.

**Comment by nimne** [comment]
Best as I can tell, PDB only has the 'bundle' files for structures that are too big to be represented in the PDBx/mmCIF file format, see [documentation here](http://www.wwpdb.org/documentation/file-formats-and-the-pdb). I'm able to find a bundle for [4UG0](https://www.rcsb.org/structure/4ug0) but not [2exs](https://www.rcsb.org/structure/2exs).

I think that the 'biological assembly file' is something different from the 'bundle'. From what I can tell, these are in the ftp site [here](http://ftp.wwpdb.org/pub/pdb/data/biounit/).

This feature doesn't seem too hard to add, I think there would just need to be small tweaks to the `retrieve_pdb_file`, `download_pdb_files`, and `download_entire_pdb` functions.

However, I don't frequently use PDB myself - so I'm not sure what the best name for this format should be (`biounit`?) or if it makes sense to add to this code. Anyone have any feedback?

**Comment by peterjc** [comment]
@dadoskawina or @jgreener64 might have some advice here?

**Comment by SimonKitSangChu** [comment]
I second the idea to add an option to download biological assemblies. Is the functionality added already?

**Comment by jadolfbr** [comment]
Agreed, this would be very nice indeed.

**Comment by JoaoRodrigues** [comment]
Just a note that mmCIF assemblies will be available from March 2022 onwards, so this will simplify this issue quite a bit: https://pdbj.org/news/Assembly_files_mmCIF_format
