### ISSUE TITLE
Are you planning on developing Assembly and Genome db support for efetch?

### ISSUE THREAD

**Issue by vinisalazar** [biopython/biopython#1876]
Hi,

I have a bunch of Genbank Assembly accession numbers, such as:

GCA_000760295.1
GCA_000759885.1
GCA_000158595.1
GCA_000011385.1
GCA_000757845.1
GCA_000009725.1
GCA_000760035.1
GCA_000317555.1
GCA_000012505.1
GCA_000332255.1

and about 600 more. I want to download the FASTA file for each of those identifiers.

But, I have noticed there is no support for downloading files from the Genome or the Assembly database. Esearch does work; I can get an UID from each of these accessions, but can't use that UID to download a fasta file of the version. I have seen that the assembly files can be downloaded from the NCBI ftp files with that accession IDs, but I can't do that programmatically. Any thoughts on how I can proceed?

Thanks.
V

**Comment by peterjc** [comment]
We (Biopython) are not able to add anything to efetch - that's in the hands of the NCBI. If you can see a logical addition to Biopython in this area though, it would be interesting to hear more details about your idea.

If you are looking for practical help, I would suggest you try https://github.com/kblin/ncbi-genome-download

**Comment by vinisalazar** [comment]
Hi @peterjc,

Thanks for the reply. That makes sense. I'll look into the repo you linked, it seems helpful.

Bw,
Vini
