### ISSUE TITLE
BSD Dual Licensing Bio/Blast/NCBIXML.py

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1878]
Sub-issue of #898, have not yet heard back from my emails to Bertrand Frottier as the original author of ``Bio/Blast/NCBIXML.py`` about dual licensing their contributions to Biopython.

**Comment by peterjc** [comment]
I've tried again via a Google address...

**Comment by peterjc** [comment]
No success with the Google email address.

His website http://bertrand.frottier.free.fr/ as listed on http://www.bioinformatics.org/people/list.php is blank.

**Comment by cbrueffer** [comment]
He appears to be on Linkedin, have you tried that?

**Comment by peterjc** [comment]
No - do you have an account on there?

**Comment by cbrueffer** [comment]
Yes, I'll give it a try.

**Comment by peterjc** [comment]
Thanks Christian - https://mailman.open-bio.org/pipermail/biopython/2019-August/016662.html - thanks Bertrand 👍

**Comment by peterjc** [comment]
Forgot to close this back in August.
