### ISSUE TITLE
BSD Dual Licensing Bio/Blast/NCBIWWW.py

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#1879]
Spin out from #898, based on the commit authors for ``Bio/Blast/NCBIWWW.py`` we have all their consent - but there are a few commits credited to people without commit rights (very common while Biopython was on CVS) where we do not yet have permission to dual license.

--

We've not been able to get in touch with Chris Wroe by email regarding this Feb 2004 contribution:

https://github.com/biopython/biopython/commit/8303c1c1e79d9f7e18a1842d8da67d569776a279

In any case, that code was later deprecated and removed in 2007:

https://github.com/biopython/biopython/commit/20855c501cd51151e900af0e49df4c0554326698

--

Still need to review this from Chang Soon Ong in July 2007:

https://github.com/biopython/biopython/commit/6dccf25c8bca1b5c87b24f559e6d8f9abd43547b

--

And this from Sjoerd de Vries in 2005,

https://github.com/biopython/biopython/commit/913c880c46f5b6eee2c05f3c1a1ea32691cba29b

**Comment by peterjc** [comment]
@mdehoon you committed the patch from Chang Soon Ong https://github.com/biopython/biopython/commit/6dccf25c8bca1b5c87b24f559e6d8f9abd43547b - do you have contact details for them to ask about re-licensing? Thanks.

**Comment by peterjc** [comment]
The original email address for Sjoerd de Vries does not work, and it is relatively common name, but I have emailed a likely candidate working at INSERM in France.

**Comment by peterjc** [comment]
It was the right person, and they kindly agreed:

**Comment by peterjc** [comment]
I believe that the only contribution now holding back dual licensing ``Bio/Blast/NCBIWWW.py`` is the changes in commit 6dccf25 from Chang Soon Ong, which while quite a few lines, is conceptually a simple translation of the BLAST documentation cited:

https://web.archive.org/web/20070701014147/http://www.ncbi.nlm.nih.gov/BLAST/Doc/node5.html

@mdehoon do you still have their contact details, as that would be the simplest way to proceed.

**Comment by mdehoon** [comment]
@peterjc  There is a Cheng Soon Ong chengsoon.ong@tuebingen.mpg.de, in the list of contributors in biopython release 1.44 from 2007.

**Comment by mdehoon** [comment]
@peterjc  This could be him: http://www.ong-home.my/

**Comment by chengsoonong** [comment]
> @peterjc There is a Cheng Soon Ong `chengsoon.ong@....de`, in the list of contributors in biopython release 1.44 from 2007.
> 
> [Edited to obscure email address]

Dear @peterjc, this is the right person who contributed that [very minor translation](https://github.com/biopython/biopython/commit/6dccf25c8bca1b5c87b24f559e6d8f9abd43547b). I'm agree to the BSD Dual License.

I am incredibly impressed at the lengths you have gone through to find me.

**Comment by peterjc** [comment]
Thank you @chengsoonong - I will prepare a pull request to dual license this file now :)

**Comment by peterjc** [comment]
Closed by #2106 - thank you everyone!
