### ISSUE TITLE
Bio.PDB.MMCIFParser.MMCIFParser exception

### ISSUE THREAD

**Issue by Minys233** [biopython/biopython#1884]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)

3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:20:05) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
CPython
Darwin-18.2.0-x86_64-i386-64bit
1.73
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

`Bio.PDB.MMCIFParser.MMCIFParser.get_structure()` parses structure `3HR6` normally.

### Actual behaviour

It will try to parse a string which representing a float number in a char to char manner, thus throw exception: `ValueError: could not convert string to float: '-'`.

### Steps to reproduce

First, download the mmCIF structure of `3HR6` from RCSB PDB: https://www.rcsb.org/structure/3HR6
Then write the following script and run
```python
from Bio.PDB.MMCIFParser import MMCIFParser
model = MMCIFParser().get_structure("", "path/to/3HR6/mmCIF")
```
Then you got this exception:
```python
Traceback (most recent call last):
  File "/Users/minys/Downloads/test/test.py", line 2, in <module>
    model = MMCIFParser().get_structure("", "test/3hr6.cif")
  File "/Users/minys/anaconda3/envs/pymol/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 64, in get_structure
    self._build_structure(structure_id)
  File "/Users/minys/anaconda3/envs/pymol/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 202, in _build_structure
    mapped_anisou = [float(_) for _ in u ]
  File "/Users/minys/anaconda3/envs/pymol/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 202, in <listcomp>
    mapped_anisou = [float(_) for _ in u ]
ValueError: could not convert string to float: '-'
```
This exception results from the following code from `Bio/PDB/MMCIFParser.py`:

```python
if aniso_flag == 1 and i < len(aniso_u11):
    u = (aniso_u11[i], aniso_u12[i], aniso_u13[i],
         aniso_u22[i], aniso_u23[i], aniso_u33[i])
    mapped_anisou = [float(_) for _ in u]
    anisou_array = numpy.array(mapped_anisou, 'f')
    structure_builder.set_anisou(anisou_array)
```
Variables like `aniso_u11` are the raw strings come from `_atom_site_anisotrop.U[a][b]` (a, b = 1, 2, 3) item of mmCIF file. Then, the code tries to iterating over every character of six strings like '0.1234', '-0.2345' or '-0.0012'. Finally, `ValueError` exception are thrown. The documentation says that this step is to set anisotropic B factor for certain atom through structure_builder.

Because I'm not a biologist and honestly, I'm not quite clear what does this mean and why this circumstance will happen. But it is quite strange and will throw exception.

[Data Item Description of _atom_site_anisotrop](http://mmcif.wwpdb.org/dictionaries/mmcif_mdb.dic/Categories/atom_site_anisotrop.html)

**Comment by Minys233** [comment]
After testing whole data on PDB (12/28/2018), I collected the whole list of proteins which could make `MMCIFParser` throw same exception:
```python
1e83	1e84	1e85	1e86
1ejg	1gv8	1gvc	1ihh
1kw3	1kw6	1pee	1r0f
1r0g	1r0h	1r0i	1r0j
1rky	1xc8	2ah7	2cg1
2eb8	2zaw	2zax	3a91
3bwf	3c58	3cjk	3dbu
3dcw	3e78	3fxz	3hhy
3hr6	3i15	3igp	3lzy
3m1q	3m3d	3nd4	3qng
3ta5	3u45	3u47	4dp1
4dp4	4dp6	4k7m	4u5t
4udf	5d7z	5gx5	5ilr
5o61	5wxb	6gob	6goh
```
All cases above will make `MMCIFParser` throw `ValueError` because of the reason stated above.

**Comment by jgreener64** [comment]
I think this was introduced by https://github.com/biopython/biopython/commit/c04ecd81509cb8f3563e7d09ac03c6bd8d8d009a#diff-cf792422691c3383d148ddd366857178.

I can have a look at fixing this. Thanks for the clear error report.

**Comment by OscarMaestre** [comment]
The parsing problem can be solved replacing line

`if aniso_flag == 1 and i < len(aniso_u11) :`

with

`if aniso_flag == 1 and i < len(aniso_u11) and isinstance(aniso_u11, list):`

I would provide a patch but I don't know how the calculation works

**Comment by jgreener64** [comment]
This would remove the loud error, but it would prevent assigning a single aniso value in a mmCIF file.

**Comment by OscarMaestre** [comment]
Maybe check if aniso value is a list or a string and do the calculations differently?

**Comment by jgreener64** [comment]
#2186 would fix this.

**Comment by jgreener64** [comment]
I think this can be closed now as #2186 is merged.

**Comment by peterjc** [comment]
Thanks. There is a magic comment pattern which triggers GitHub to close issues when a pull request is merged... we're not seeing that though. I wonder if the pull request template can be tweaked to help?

**Comment by jgreener64** [comment]
I think changing "addresses issue" to "closes" or "fixes" would do it, though it's not always a case that a PR addressing an issue would wish to close the issue on merge.

**Comment by peterjc** [comment]
You're right, having the default template wording always trigger the auto-close might not be ideal. But would it be better than the current situation? Maybe best discussed on a new issue... thanks!
