### ISSUE TITLE
SeqFeature.translate ignores CDS type

### ISSUE THREAD

**Issue by rwst** [biopython/biopython#1896]
This is master with Python3. The doctest of `SeqFeature.translate` follows:
```
        >>> seq = Seq("GGTTACACTTACCGATAATGTCTCTGATGA", generic_dna)
        >>> f = SeqFeature(FeatureLocation(0, 30), type="CDS")
        >>> f.qualifiers['transl_table'] = [11]
        >>> f.translate(seq)
```
 I would expect that giving a type of `CDS` make the translation behave as if I would have said:
```
In [10]: Seq('GGTTACACTTACCGATAATGTCTCTGATGA'[0:30], generic_dna).translate(table=11, cds=True)
---------------------------------------------------------------------------
TranslationError                          Traceback (most recent call last)
<ipython-input-10-08236f76b040> in <module>()
----> 1 Seq('GGTTACACTTACCGATAATGTCTCTGATGA').translate(table=11, to_stop=False, cds=True, gap=None)

/usr/lib64/python3.7/site-packages/Bio/Seq.py in translate(self, table, stop_symbol, to_stop, cds, gap)
   1183 
   1184         protein = _translate_str(str(self), codon_table, stop_symbol, to_stop,
-> 1185                                  cds, gap=gap)
   1186 
   1187         if gap and gap in protein:

/usr/lib64/python3.7/site-packages/Bio/Seq.py in _translate_str(sequence, table, stop_symbol, to_stop, cds, pos_stop, gap)
   2592         if str(sequence[:3]).upper() not in table.start_codons:
   2593             raise CodonTable.TranslationError(
-> 2594                 "First codon '{0}' is not a start codon".format(sequence[:3]))
   2595         if n % 3 != 0:
   2596             raise CodonTable.TranslationError(

TranslationError: First codon 'GGT' is not a start codon
```
But the output is:
```
Seq('GYTYR*CL**', HasStopCodon(ExtendedIUPACProtein(), '*'))
```
Reason is that the `type` property of `SeqFeature` is ignored in `SeqFeature.translate()` and a default `cds` parameter of `False` is used.

I'd like to do a PR where the translation uses cds=`True` if the feature type is `CDS` and the parameter is not explicitly set to `False`. Doctests change accordingly.

**Comment by peterjc** [comment]
I thought we had something related as an existing issue, on using more of the NCBI style annotation typically stored in the ``SeqFeature`` object's ``.qualifiers`` annotation dictionary, but I could only find:

* NCBI Genetic Code Tables 27 to 31 + ambiguous codons #1224
* translational recoding for UGA for Selenocysteine, UAG for Pyrrolysine, etc #1164

--

Your idea seems very sensible.

I would suggest changing the default to ``cds=None`` meaning it would use ``cds = (self.type == "CDS")`` while allowing the user to provide ``True`` or ``False`` for direct control.

I'd be happy to see a pull request along these lines, and your short example would make a good functional test.

**Comment by peterjc** [comment]
Ah, thanks. Sometimes I get the magic comment right in the comment for a squash merge, and GitHub closes the relevant issue for me.
