### ISSUE TITLE
QualityIO Sequence and quality captions differ

### ISSUE THREAD

**Issue by jfallmann** [biopython/biopython#1898]
I am reporting a problem with Biopython 1.72 , Python 3.7.1 on Fedora 29
When reading in FASTQ files with SeqIO with differing lines 1 (header) and 3 (optional) we get the above error message. We use Biopython to post-process unmapped reads from metagenomics mapping and tend to use line three to add information about runs and metagenomes used, which seems to be a topic of controversial opinions, however, I fail to understand why 
https://github.com/biopython/biopython/blob/e41e53e6c5caab0cbd1390b97cb02c7549384b1e/Bio/SeqIO/QualityIO.py#L916-L920
is so strict about this. Is this really necessary? And if yes is there a way to circumvent this?
Thanks for any help, highly appreciated

**Comment by peterjc** [comment]
Because we wrote the "spec" http://dx.doi.org/10.1093/nar/gkp1137 ;)

Practically speaking, do you want access to the plus line information, or would downgrading to a warning be enough?

**Comment by peterjc** [comment]
If this is urgent, just comment out that if statement, or to reduce the exception to a warning, replace:

```python
raise ValueError("Sequence and quality captions differ.")
```

with:

```python
warnings.warn("Sequence and quality captions differ.", BiopythonParserWarning)
```

In terms of integrating this into Biopython, it might make sense as part of #1812 / #1864 where we're looking at a revised faster FASTQ parser which assumes four lines (it would not support line wrapping, which is almost never used).

**Comment by jfallmann** [comment]
@peterjc Thanks for forwarding this to the revised FASTQ parser issues, if somebody takes this up it would be great. In the meantime I'll just edit locally. Feel free to close this issue anytime
