### ISSUE TITLE
fix untested doctests

### ISSUE THREAD

**Issue by rwst** [biopython/biopython#1902]
The following modules are not tested because of failing doctests:

- [x] `Bio.AlignIO.MauveIO`
- [x] `Bio.Cluster`
- [x] `Bio.Data.CodonTable`
- [x] `Bio.ExPASy`
- [x] `Bio.ExPASy.cellosaurus`
- [x] `Bio.File`
- [x] `Bio.Medline`
- [x] `Bio.motifs.jaspar.db`
- [x] `Bio.motifs.mast`
- [x] `Bio.motifs.meme`
- [x] `Bio.motifs.minimal`
- [ ] `Bio.PDB`
- [ ] `Bio.PDB.AbstractPropertyMap`
- [x] `Bio.PDB.Atom`
- [x] `Bio.PDB.DSSP`
- [x] `Bio.PDB.Entity`
- [x] `Bio.PDB.FragmentMapper`
- [x] `Bio.PDB.mmcifio`
- [x] `Bio.PDB.PDBIO`
- [x] `Bio.PDB.ResidueDepth`
- [x] `Bio.PDB.vectors`
- [x] `Bio.phenotype`
- [x] `Bio.phenotype.parse`
- [x] `Bio.phenotype.phen_micro`
- [x] `Bio.Phylo.Applications._Fasttree`
- [x] `Bio.Phylo._io`
- [x] `Bio.Phylo.TreeConstruction`
- [x] `Bio.Phylo._utils`
- [x] `Bio.Restriction`
- [x] `Bio.Restriction.PrintFormat`
- [x] `Bio.Restriction.Restriction`
- [x] `Bio.SearchIO.ExonerateIO._base`
- [x] `BioSQL.BioSeqDatabase`
- [x] `Bio.SubsMat`
- [x] `Bio.SubsMat.FreqTable`
- [x] `Bio.TogoWS`

**Comment by peterjc** [comment]
Cross reference #1901 to test more doctests in ``run_tests.py``.

**Comment by peterjc** [comment]
This looks like a good idea for new-comers. If you want to work on this, you'd need to update ``Tests/run_tests.py`` to add one of the problem modules like ``Bio.SubsMat`` to the ``DOCTEST_MODULES`` list - and then:

```
python3 setup.py install
cd Tests
python3 run_tests.py doctest
```

And then edit ``Bio/SubsMat/__init__.py`` to try to fix the doctest, and repeat.

Some of the examples might be intended to work as doctests, but might just need a file path adjusted or a missing import added.

Others would have been written as incomplete illustrative examples, which may not be practical to turn into self contained doctests.

**Comment by pcapel** [comment]
Is it preferred to fix a single module at a time or is it ok to group a few modules together in one merge request?

**Comment by peterjc** [comment]
@pcapel one top level folder per pull request is probably best here (e.g. Bio/PDB/, or Bio/motifs/), in part as they will tend to have different maintainers so that simplifies reviewing changes.

**Comment by kaskales** [comment]
Hello, about fixing the doctest for Bio.motifs.jaspar.db, it seems that the doctest uses an example database host, user, and password. If I'm correctly understanding this, it doesn't seem like this doctest will ever pass since everyone has their database configured differently.

**Comment by peterjc** [comment]
In cases like that, we either exclude the whole file from running doctests (not ideal), or for that example don't write it as a doctest but an RST literal block (i.e. indented code, but no ``>>>`` lines).

**Comment by peterjc** [comment]
Note that some of the modules on this list are simply missing any doctests at all, e.g. ``Bio.Restriction`` as noted by @MarkusPiotrowski https://github.com/biopython/biopython/commit/4a9dcbcf97e46ce284780cb2dd0960cb3cc2f8c7#commitcomment-32819770

**Comment by MarkusPiotrowski** [comment]
Sorry, I was wrong, actually they have doctests. I thougth that doctests are only self-running doctests (those modules with ```if __name__ = "__main__"...run_doctest()```). 

So, I'm taking care for the ```Restriction``` module.

**Comment by peterjc** [comment]
Great - it looks like they need some missing imports added, and blank lines where the expected output otherwise merges into the text - e.g.

https://github.com/biopython/biopython/blob/master/Bio/Restriction/Restriction.py#L286

```python
        """Override '/' operator to use as search method.

        >>> from Bio.Restriction import EcoRI
        >>> EcoRI/Seq('GAATTC')
        [2]
        Returns RE.search(other).
        """
```

to:

```python
        """Override '/' operator to use as search method.

        >>> from Bio.Seq import Seq
        >>> from Bio.Restriction import EcoRI
        >>> EcoRI / Seq('GAATTC')
        [2]

        Returns RE.search(other).
        """
```

**Comment by kritikadusad** [comment]
Hi there! I am new to contributing to open source projects. Please bear with me...
I am working on fixing the Bio.PDB.AbstractPropertyMap doctest. I want to make an AbstractPropertyMap object to fix the test. Trying to figure out where the property_dict, property_keys, property_list can be obtained to make the object.

**Comment by kaskales** [comment]
@kritikadusad I've never used the AbstractPropertyMap class myself, but if you take a took at the ResidueDepth class you can see that it creates a AbstractPropertyMap with the three attributes you need. If you have the test for it running, test_PDB_ResidueDepth.py, you could edit it to try and print the ResidueDepth objects contents maybe?

**Comment by svalqui** [comment]
I'll work on Bio.TogoWS

**Comment by MarkusPiotrowski** [comment]
@svalqui You cannot separate doctests and docstrings, a doctest is usually part of a docstring. 


This one  is a little bit difficult: It's accessing an online resource and the output can change from day to day, so it's impossible to show the output in the doctest.


Although in this case an import of TogoWS is not neccessary for running the doctest, it would be nice to have a self-contained example. Because it's part of the docstring, it will be shown in the documentation.

A possible solution could look like this:
```
>>> from Bio import TogoWS
>>> for id in TogoWS.search_iter("pubmed", "lung+cancer+drug", limit=10):
...     print("PubMed ID: %s" %id) # maybe fetch data with entry?
...
PubMed ID: ...
PubMed ID: ...
```

**Comment by svalqui** [comment]
@MarkusPiotrowski , Ok, Thank you, I'll work on Bio.TogoWS.

**Comment by svalqui** [comment]
I'll work on Bio.SubsMat.FreqTable

**Comment by svalqui** [comment]
I'll work on Bio.SearchIO.ExonerateIO._base

**Comment by svalqui** [comment]
I'll Work on Bio.Phylo.

**Comment by svalqui** [comment]
I'll work on Bio.phenotype

**Comment by svalqui** [comment]
I'll work on Bio.PDB.

**Comment by Andrey-Raspopov** [comment]
Hello! I'm looking into BioSQL.BioSeqDatabase and besides the simple import error there is a bigger concern. The existing doctest assumes that user not only has some DB software installed, but:
1) It has 'root' user
2) Without a password
3) This user has access to the existing 'minidb' database

Since we can't guarantee these, my only solution to this could be moving the doctest to the commentary block. Does that seem good?

**Comment by MarkusPiotrowski** [comment]
You can/should make it into a literal block. To do this you end the paragraph before with two colons (`::`) and remove the `>>>` from the code block. In this way it is rendered similar to a code block, but it is not run as doctest.

**Comment by dizak** [comment]
I have done ```Bio/phenotype/phen_micro``` and created pr #2235 I have tested it on TravisCI so it required changes to ```.travis-tox.ini```. Since the test passed (except for Python3.8 for which ```numpy``` installation fails) I guess I should revert the changes in this file?

**Comment by peterjc** [comment]
Updated the check boxes, just two left:

```
# Following modules have historic failures. If you fix one of these
# please remove here!
EXCLUDE_DOCTEST_MODULES = [
    "Bio.PDB",
    "Bio.PDB.AbstractPropertyMap",
]
```

https://github.com/biopython/biopython/blob/master/Tests/run_tests.py#L78

**Comment by farAtGitHub** [comment]
I created https://github.com/biopython/biopython/pull/2482 trying to fix Bio.PDB.AbstractPropertyMap. Hope it's not to far off.

**Comment by farAtGitHub** [comment]
I stumbled over biopython/Doc/Tutorial/chapter_testing.tex which also contains EXCLUDE_DOCTEST_MODULES (see below). Does that file need any attention as well?

```
# Following modules have historic failures. If you fix one of these
# please remove here!
EXCLUDE_DOCTEST_MODULES = [
    "Bio.PDB",
    "Bio.PDB.AbstractPropertyMap",
    "Bio.Phylo.Applications._Fasttree",
    "Bio.Phylo._io",
    "Bio.Phylo.TreeConstruction",
    "Bio.Phylo._utils",
]
```

**Comment by peterjc** [comment]
Since ``EXCLUDE_DOCTEST_MODULES`` is now empty, we could perhaps remove it including the code implementing, and this documentation describing it.

Any comments @mdehoon?  As I recall, problematic doctests have either been different versions of Python, or cross platform issues - although in that case the test itself can usually be tweaked (e.g. reduce number of significant figures). e.g. there was a 32 vs 64 bit issue recently.

**Comment by mdehoon** [comment]
Yes let's remove it

**Comment by peterjc** [comment]
Belatedly closing.

We still use ``EXCLUDE_DOCTEST_MODULES`` for things like ignoring online doctests in offline mode.
