### ISSUE TITLE
exclude rather than include doctests in "run_tests.py doctest"

### ISSUE THREAD

**Issue by rwst** [biopython/biopython#1904]
The testing code in `Tests/run_tests.py` that does doctests relies on people updating the list of modules to test.
@peterjc in https://github.com/biopython/biopython/pull/1901#issuecomment-456022268_:
> Perhaps rather a positive list like this, we can switch to testing them all by default and listing modules to exclude from doctests.

A solution would be to call `pkgutil.iter_modules` recursively to get all modules, then exclude all which should not be tested. This way the resulting list may contain modules without doctests, only discovered when later parsing the file and running the test. However determining if a file contains a test requires parsing anyway, so there is no performance gain in excluding files without doctest right at the start.

**Comment by peterjc** [comment]
Retitled to avoid the loaded term blacklist.

**Comment by peterjc** [comment]
It might be possible to query our ``setup.py`` which has the definitive list of packages - although separately we should be able to move away from that in favour of ``from setuptools import find_packages`` (which wasn't available in the early years of Biopython, and only relatively recently have we required ``setuptools`` as a dependency).

**Comment by rwst** [comment]
> ... in favour of `from setuptools import find_packages`

I'll use this, thanks.

**Comment by rwst** [comment]
Actually there are appveyor failures if a file has no docstring at all. I consider it a feature and will open a ticket with those files when I can figure out how to reproduce it.

**Comment by peterjc** [comment]
Maybe open the issue now (or add the appveyor links and log excerpts here) without waiting to figure out how to reproduce it locally?

**Comment by peterjc** [comment]
Closing this issue now that #1906 has been merged.
