### ISSUE TITLE
Outdated seqtype parameter values in Bio.Align.Applications.MuscleCommandline

### ISSUE THREAD

**Issue by biostu24** [biopython/biopython#1911]
### Description of issue 

I have found an issue where valid MUSCLE seqtype parameters values cannot be passed using MuscleCommandline(seqtype=XXX). This appears to be due to a change in MUSCLE parameter values that have not been updated in Biopython. 

The flag for nucleotide sequence in MUSCLE used to be ```-seqtype nucleo``` but ```nucelo``` has been changed to either ```rna``` or ```dna``` and ```nucleo``` is no longer valid. Normally sequence type is determined automatically (defualt: ```-seqtype auto```) and does not need to be specified, however, I am working on a project where explicitly passing the sequence type is necessary.

I'm not sure when exactly from nucleo was changed to rna/dna, however it does appears to be recent. The version 3.8 user guide (http://www.drive5.com/muscle/muscle_userguide3.8.pdf) uses the old nucleo value, while the current command line reference (https://www.drive5.com/muscle/manual/valueopts.html) uses the new rna/dna values.

### System info
Python version: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
Python implementation: CPython
OS: Windows-10-10.0.17134-SP0
Biopython version: 1.73
MUSCLE version: 3.8.31 for Windows (32/64 bit)

### Code examples
The following example in python should should be valid but raises and error:
```
from Bio.Align.Applications import MuscleCommandline

# Paths
muscle_path = 'MUSCLE\\muscle3.8.31_i86win32.exe'
fasta_in = 'sequences.fasta'
fasta_out = 'output.fasta'

# Alignment
muscle_cline=MuscleCommandline(muscle_path, input=fasta_in, out=fasta_out, seqtype = 'dna')
muscle_cline()
```
Error: ```ValueError: Invalid parameter value 'dna' for parameter seqtype```

Changing seqtype to the now obsolete 'nucleo' is valid in MuscleCommandline:
```
...
muscle_cline=MuscleCommandline(muscle_path, input=fasta_in, out=fasta_out, seqtype = 'nucleo')
...
```
But this results in a MUSCLE error:
```
Bio.Application.ApplicationError: Non-zero return code 2 from 'MUSCLE\\muscle3.8.31_i86win32.exe -in sequences.fasta -out output.fasta -seqtype nucleo', 
message '*** ERROR ***  Invalid parameter -SeqType nucleo'
```

However running MUSCLE directly  from the command line is fine with '-seqtype dna':
```
~\MUSCLE\muscle3.8.31_i86win32.exe -in sequences.fasta -out output.fasta -seqtype dna
```

### Suggested fix
The allowed parameter values for ```seqtype``` in ```MuscleCommandline()``` should be updated to allow ```'rna'``` and ```'dna'```. It would probably be a good idea to keep ```'nucleo'``` as a valid parameter to support older implementations of MUSCLE.

**Comment by peterjc** [comment]
That seems clear, the source for this is here:

https://github.com/biopython/biopython/blob/master/Bio/Align/Applications/_Muscle.py

Specifically, this line looks like it needs expanding:

```python
SEQUENCE_TYPES = ["protein", "nucleo", "auto"]
```

From your description, it should be:

```python
SEQUENCE_TYPES = ["protein", "rna", "dna", "auto"]
```

Or, if anyone still wants to use older versions of MUSCLE as well something like this:

```python
SEQUENCE_TYPES = ["protein", "rna", "dna", "nucleo", "auto"]
```

Would you like to submit this change as a pull request? You could do it entirely within GitHub as they let you edit files within the browser.
