### ISSUE TITLE
Conversion of Seq to MutableSeq causes failure of methods

### ISSUE THREAD

**Issue by chris-rands** [biopython/biopython#1918]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
>>> import sys; print(sys.version)
3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.19.4-arch1-1-ARCH-x86_64-with-arch
>>> import Bio; print(Bio.__version__)
1.74.dev0
```

### Expected and Actual behaviour

This works as expected...
```
>>> from Bio.Seq import Seq, MutableSeq
>>> s = MutableSeq('A')
>>> s[0] = 'T'
>>> s
MutableSeq('T')
```

I would expect this to work the same way, but instead it raises an exception...
```
>>> s1 = MutableSeq(Seq('A'))
>>> s1[0] = 'T'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/python3.7/site-packages/Bio/Seq.py", line 2037, in __setitem__
    self.data[index] = value
TypeError: 'Seq' object does not support item assignment
```

Note `type(s1)` still returns `<class 'Bio.Seq.MutableSeq'>`, but apparently the underlying `Seq` type methods are being invoked.

Assuming we are agreed that this is a bug, I can look at a PR fix when I have time, I guess the relevant place is here(?):
https://github.com/biopython/biopython/blob/master/Bio/Seq.py#L1861

Note I was alerted to this by a SO question:
https://stackoverflow.com/questions/54482944/replacing-all-of-instances-of-a-letter-in-a-column-of-a-fasta-alignment-file/

**Comment by peterjc** [comment]
In this setting I would expect you to use ``s1 = MutableSeq('A')`` or if you have a ``Seq`` object already, something long these lines: ``s1 = Seq('A').tomutable()``

I initially thought trying ``s1 = MutableSeq(Seq('A'))`` ought to raise an error - although it would be easy enough to support this directly as it is not unreasonable behaviour. Would you like to make a pull request doing either?

**Comment by peterjc** [comment]
P.S. Yes, that's exactly where a change would be needed.
