### ISSUE TITLE
No request-limit for Entrez with api-key cause data loss

### ISSUE THREAD

**Issue by danilotat** [biopython/biopython#1924]
### Setup

3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
CPython
Windows-10-10.0.17134-SP0
1.72

### Actual behaviour

Entrez api key also have the limit of 10 request/s : while submitting a query to ncbi, Entrez will just visualize the first 20 permitted files, and goes forward without displaying something. 

### Steps to reproduce

```
Entrez.email = "some@mail"
Entrez.api_key = "key"
search_term = "Bifidobacterium[organism] AND complete+genome[title]"
handle = Entrez.esearch(db="nucleotide", term=search_term)
genome_ids = Entrez.read(handle)['IdList']
print(genome_ids)

OUTPUT: 
`['1543111869', '1537796250', '1528551725', '1528465589', '1527174113', '1526297721', '1520138637', '1519108531', '1495549021', '1494638545', '1486629960', '1483584181', '1478165911', '1468414822', '1468377629', '1464571395', '1464343718', '1449875798', '1449857327', '1447649969']`
```

**Comment by peterjc** [comment]
Is it just the NCBI applying a default limit of 20? I think you should set ``retmax`` explicitly when you call ``esearch`` if you want more than that.

**Comment by danilotat** [comment]
How could be implemented the `retmax `inside my code? Reading from documentation 

>  Increasing retmax allows more of the retrieved UIDs to be included in the XML output, up to a maximum of 100,000 records

But I don't know actually how many records I will get using this `Bifidobacterium` query.

**Comment by peterjc** [comment]
Try it in code, and in the NCBI web-browser.

```python
handle = Entrez.esearch(db="nucleotide", term=search_term, retmax=100)
...
```

**Comment by danilotat** [comment]
Solved, many thanks.

**Comment by peterjc** [comment]
Glad we could help.
