### ISSUE TITLE
efetch to Pubmed API failing in for loop

### ISSUE THREAD

**Issue by sehjk** [biopython/biopython#1939]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-17.7.0-x86_64-i386-64bit
1.72

### Expected behaviour

```python
def search(query):
    Entrez.email = 'email@stanford.edu'
    handle = Entrez.esearch(db='pubmed', 
                            retmax='80',
                            retmode='xml', 
                            term=query)
    results = Entrez.read(handle)
    return results

def fetch_details(idl):
    if(type(idl) == list):
        ids = ','.join(idl)
    else:
        ids = idl
    print(ids)
    Entrez.email = 'email@stanford.edu'
    handle = Entrez.efetch(db='pubmed',
                           retmode='xml',
                           id=ids)
    results = Entrez.read(handle)
    return results


results = search('stanford[ad]Environment+and+Public+Health[mh]')
id_list = results['IdList']
authors = []
paper_auths = {}

id_list_split = np.array_split(id_list, 2)
    for mini_list in id_list_split:
        papers = fetch_details(list(mini_list))
        for i, paper in enumerate(papers['PubmedArticle']):
            pmid = str(paper['MedlineCitation']['PMID'])
            #print(pmid)
            if pmid not in paper_auths:
                paper_auths[pmid] = []
            author_list = paper['MedlineCitation']['Article']['AuthorList']
            for author in author_list:
                if author['AffiliationInfo']:
                    affiliation = author['AffiliationInfo'][0]['Affiliation']
                    identifier = author['Identifier']
                    lastname = author['LastName']
                    firstname = author['ForeName']
                    initials = author['Initials']
                    if re.match(r'.*\bstanford.*', affiliation, re.IGNORECASE):
                        authors.append([firstname + " " + lastname, affiliation])
                        paper_auths[pmid].append([firstname + " " + lastname, affiliation])
        time.sleep(5)`
```

Currently, my search function returns 80 PMIDs and I split these into a list of 40 each since single pulls of more than 50 ids was not working. The first 40 are successfully pulled but the second 40 gives me the error: "NotImplementedError: The Bio.Entrez parser cannot handle XML data that make use of XML namespaces".

I've tried several ways to debug
1. Tried putting the system to sleep between iterations of the for loop (up to 20 seconds) -- still fails on 2nd go around. 
2. I've tried pulling just the second batch to check if there is some error with those PMIDs -- they work fine when pulled separately, but not when pulled with the others. 
3. I've tried feeding id's singularly to the fetch function -- this also fails after some number of PMIDs. I'm not sure what to do. 

I'd appreciate your help in debugging this.

**Comment by mdehoon** [comment]
Works for me, using the latest source code of Biopython in github.

**Comment by sehjk** [comment]
@mdehoon the same code I pasted? Amazing... hm, not sure why it is not working for me then.

**Comment by sehjk** [comment]
Resolved.

I updated to the latest biopython package 1.73 and the code is working. Thank you for checking on your end.
