### ISSUE TITLE
Test precision failure on Ubuntu autopkgtests with glibc 2.29

### ISSUE THREAD

**Issue by rikmills** [biopython/biopython#1945]
We are seeing the following failure only on ppc64el architecture when the tests for 1.73 are run against new glib 2.29 on Ubuntu autopkgtests.

http://autopkgtest.ubuntu.com/packages/p/python-biopython/disco/ppc64el 

FAIL: test_WellRecord (test_phenotype_fit.TestPhenoMicro)
Test basic functionalities of WellRecord objects
Traceback (most recent call last):
  File "/tmp/autopkgtest.6H8J2c/autopkgtest_tmp/Tests/test_phenotype_fit.py", line 55, in test_WellRecord
    self.assertAlmostEqual(w.plateau, 188.51404344898586, places=5)
AssertionError: 188.51403793245183 != 188.51404344898586 within 5 places

I wonder it it would be acceptable to fix this by reducing the required precision here, similar to what was done for #1038?

Thank you.

**Comment by peterjc** [comment]
A similar fix seems appropriate and would be welcome - are you happy to make a pull request?

Perhaps we should drop all of these comparisons from 5 places to 4?

CC @mgalardini

**Comment by mgalardini** [comment]
Hi both,

I am of course very happy to drop the precision to 4 places instead of 5. I'm also happy to do the PR, just let me know.

Best,
Marco

**Comment by peterjc** [comment]
Thanks @mr-c, we've not been testing the other architectures regularly so I can see how this languished.
