### ISSUE TITLE
conda-forge: Biopython 1.73 for Win32?

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython#1954]
I wanted to update my Biopython to version 1.73 in my Anaconda environment using the conda-forge channel. 
Anaconda's standard channel is on Biopython 1.72 (as usual lagging behind), but while the conda-forge channel is on Biopython 1.73 for all the other OSs, it's still on 1.71 for Win32 (https://anaconda.org/conda-forge/biopython). 

Anyone around here who's participating in conda-forge?

**Comment by peterjc** [comment]
Me and @souravsingh, see https://github.com/conda-forge/biopython-feedstock

I hadn't noticed but it does look like Conda Forge dropped win32 a long time ago:

https://github.com/conda-forge/biopython-feedstock/commit/14138c8c52545f96d6f283ba2afd8e14ac015804#diff-11c909939117928998b102a1fff7d363

Looking here, there seems to be some tag needed to explicitly keep win-32 builds alive?

https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl

**Comment by MarkusPiotrowski** [comment]
Here's the issue about dropping Win32 support: https://github.com/conda-forge/staged-recipes/issues/5640 . I'm not sure if it is still possible to force a win32 build, I would guess no.

I wonder if it's worth to investigate further. I have a small laptop with Win32 and I for sure there are more around. However, I was able to upgrade my Biopython version in my conda environment using ```pip```. Some people don't like mixing ```conda``` and ```pip``` but in my hands it did work nicely.

**Comment by peterjc** [comment]
I had read that mixing pip and conda is not advised, so avoid it myself. In this case, pip seems like a practical way forward (rather than waiting for the default conda channel to catch up).

Note that the BioConda channel currently does not support Windows at all, so that does not offer an alternative. This was why we focused on conda-forge instead.

Shall we close this as there looks to be no easy way to offer win32 conda packages?

**Comment by cbrueffer** [comment]
FYI, the latest conda versions (>4.6.0) are supposed to interoperate with pip a lot better. See https://github.com/conda/conda/blob/master/CHANGELOG.md

**Comment by MarkusPiotrowski** [comment]
The better ```pip```/```conda``` interoperability is also described here: https://www.anaconda.com/conda-4-6-release/

Closing.
