### ISSUE TITLE
Bio.Motifs throws KeyError 'd'

### ISSUE THREAD

**Issue by SYSUMSD** [biopython/biopython#1978]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
CPython
Windows-10-10.0.17134-SP0

### Expected behaviour
I'm using Biopython to process some NGS data. 
But a 'd' arise during process. My reads has no 'd' in their content.

### Actual behaviour

Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\motifs\__init__.py", line 23, in create
    return Motif(instances=instances, alphabet=alphabet)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\motifs\__init__.py", line 244, in __init__
    counts = self.instances.count()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\motifs\__init__.py", line 199, in count
    counts[letter][position] += 1
KeyError: 'd'

### Steps to reproduce
from Bio import motifs
import pandas as pd
from Bio.Alphabet import IUPAC
seqs2 ={'a': 'GGCACTG', 'b': 'GGCACTG'}
frame = pd.DataFrame({'Spacer': seqs2.values()}, index=seqs2.keys())
Motif = motifs.create(frame.Spacer.values, alphabet=IUPAC.IUPACAmbiguousDNA())

**Comment by MarkusPiotrowski** [comment]
For me this works just fine on Python 2.7.14 with Biopython 1.73:

```python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from Bio import motifs
>>> from Bio.Alphabet import IUPAC
>>> Motif = motifs.create(['GGCACTG', 'GGCACTG'], alphabet=IUPAC.IUPACAmbiguousDNA())
>>> print(Motif)
GGCACTG
GGCACTG
```
Are you sure that your Pandas frame contains what you think?
Which Biopython version are you using?

**Comment by SYSUMSD** [comment]
> For me this works just fine on Python 2.7.14 with Biopython 1.73:
> 
> ```python
> Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
> Type "copyright", "credits" or "license()" for more information.
> >>> from Bio import motifs
> >>> from Bio.Alphabet import IUPAC
> >>> Motif = motifs.create(['GGCACTG', 'GGCACTG'], alphabet=IUPAC.IUPACAmbiguousDNA())
> >>> print(Motif)
> GGCACTG
> GGCACTG
> ```
> 
> Are you sure that your Pandas frame contains what you think?
> Which Biopython version are you using?

my Biopython version is 1.73.
As you say, pandas frame object seems strange in my code:
`seqs2 ={'a': 'GTCACTG', 'b': 'GGCACTG'} `
`frame = pd.DataFrame({'Spacer': seqs2.values()}, index=seqs2.keys())`
`frame`
              Spacer
a  (GGCACTG, GGCACTG)
b  (GGCACTG, GGCACTG)

These dataframe structrue is different from the example about motifs.create in 

> http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc221

I think the problem is in `pd.DataFrame({'Spacer': seqs2.values()}, index=seqs2.keys())`
Can the element after 'Spacer': '  be **dict_values**?

**Comment by MarkusPiotrowski** [comment]
Sorry, I don't have any knowledge about Pandas. Do you really need it here? If your sequence reads are in a dictionary, as you have shown, you can simply convert the values into a list with ```.values()```
Note: In Python 3 you may need to use ```list(seqs2.values()``` instead of just ```seqs2.values()```.

```python
>>> from Bio import motifs
>>> from Bio.Alphabet import IUPAC
>>> seqs2 ={'a': 'GGCACTG', 'b': 'GGCACTG'}
>>> Motif = motifs.create(seqs2.values(), alphabet=IUPAC.IUPACAmbiguousDNA())
>>> print(Motif)
GGCACTG
GGCACTG

**Comment by SYSUMSD** [comment]
> Sorry, I don't have any knowledge about Pandas. Do you really need it here? If your sequence reads are in a dictionary, as you have shown, you can simply convert the values into a list with `.values()`
> Note: In Python 3 you may need to use `list(seqs2.values()` instead of just `seqs2.values()`.
> 
> ```python
> >>> from Bio import motifs
> >>> from Bio.Alphabet import IUPAC
> >>> seqs2 ={'a': 'GGCACTG', 'b': 'GGCACTG'}
> >>> Motif = motifs.create(seqs2.values(), alphabet=IUPAC.IUPACAmbiguousDNA())
> >>> print(Motif)
> GGCACTG
> GGCACTG
> ```

Thanks! 
I rewrite these code .
Now the code can run as I wish.

**Comment by MarkusPiotrowski** [comment]
Fine!

Closing this now.
