### ISSUE TITLE
Add vcf snp comparing modules to biopython

### ISSUE THREAD

**Issue by TSL-RamKrishna** [biopython/biopython#2004]
I have been developing a tool for quick snp filtering from multiple vcf files and then comparing the snps from multiple vcf files to output the snps that are common or unique to each vc file.
The github link to the tool is: 
https://github.com/TeamMacLean/snpFC

I have followed PEP8 style format in the scripts. Documentation have been added.
I appreciated any help in adding the modules to biopython.

**Comment by peterjc** [comment]
It looks like a nice standalone tool for Python 3 using ``pyvcf`` (and nothing from Biopython).

Currently Biopython has relatively few command line scripts, and those that we do have are not first-class citizens added to the ``$PATH`` during installation. Our focus has been much more on library code for people to write scripts calling Biopython functions and classes.

(The fact that your code likely doesn't work on Python 2.7 without more work is really only a short term issue - Biopython is aiming to drop Python 2 support in 2020)

In all, I don't see this as a good fit - but you would be welcome to submit a pull request adding it to this listing on our website: https://biopython.org/wiki/Scriptcentral
