### ISSUE TITLE
Bio Module not found in python 3.6

### ISSUE THREAD

**Issue by Nelson-Gon** [biopython/biopython#2034]
### Setup
```
3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) 
CPython
Windows-10-10.0.17134-SP0
```
This fails:
```
import Bio; print(Bio.__version__)
```
>ModuleNotFoundError: No module named 'Bio'

I installed via:
```
pip install Biopython
pip3 install Biopython
```
I only received `BioSQL`, is `Bio` not available for python 3.6?

**Comment by peterjc** [comment]
This is strange, perhaps you have more than one copy of Python installed... but you say ``import BioSQL`` worked? Could you copy-and-paste the full output from the various commands - including the long filenames in any error messages.

**Comment by Nelson-Gon** [comment]
Full output:
```
import sys; print(sys.version)
3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Windows-10-10.0.17134-SP0
````

````
import Bio; print(Bio.__version__)
 File "<input>", line 1, in <module>
  File "E:\PyCharm Community Edition 2018.3.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'Bio'
````

**Comment by peterjc** [comment]
Can you try this within your Python 3:

```python
import sys; print(sys.path)
```

That will list all the folders Python looks in when you do an import.

If you (re)run ``pip3 install biopython``, it will say where it found or put the files.

**Comment by peterjc** [comment]
Did you work out what had gone wrong?

**Comment by Nelson-Gon** [comment]
Yes, I have two python versions on two different folders. That was the issue(I haven't tried fixing it yet but I think it will fix it so I closed the issue.)

**Comment by peterjc** [comment]
Thanks for the clarification. Good luck with the next steps of your project.
