### ISSUE TITLE
E731 (don't assign lamda...) in Bio.SearchIO.BlastIO.blast_tab

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython#2043]
Dear @bow I'm looking on some style issues, in this case ["don't assign a lambda expression, use a def"](https://lintlyci.github.io/Flake8Rules/rules/E731.html).

I stumbled upon this line in `Bio.SearchIO.BlastIO.blast_tab`: 
https://github.com/biopython/biopython/blob/3d235ad8dcc89c3d934cc7e3e33b52fb992c1798/Bio/SearchIO/BlastIO/blast_tab.py#L192

Shouldn't this be `func2 = ...`?

Regarding the lambdas: You make heavy use of lambdas in: https://github.com/biopython/biopython/blob/3d235ad8dcc89c3d934cc7e3e33b52fb992c1798/Bio/SearchIO/BlastIO/blast_tab.py#L159

but it seems that you use `func` and `func2` only once for one calculation each,
https://github.com/biopython/biopython/blob/3d235ad8dcc89c3d934cc7e3e33b52fb992c1798/Bio/SearchIO/BlastIO/blast_tab.py#L185
https://github.com/biopython/biopython/blob/3d235ad8dcc89c3d934cc7e3e33b52fb992c1798/Bio/SearchIO/BlastIO/blast_tab.py#L200
 so instead assigning several different lambdas to `func`/`func2` can't you simply calculate the `value`'s in place?

**Comment by bow** [comment]
Hi @MarkusPiotrowski ,

Good catch. It seems like it should be `func2` indeed and looking back, there is a better way to do this than using lambdas. I'll open a PR soon.

**Comment by MarkusPiotrowski** [comment]
Solved via PR #2047. Closing now.
