### ISSUE TITLE
ADJUSTED_FOR_SHORT_QUERY

### ISSUE THREAD

**Issue by KristaJ** [biopython/biopython#2049]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
CPython
Darwin-17.7.0-x86_64-i386-64bit
1.70

### Expected behaviour

I am running a search for a peptide sequence using blastp on the PDB database. I would like to set the parameter to adjust for short queries, but that parameter is not available.  As a result, the output returned by the python query does not match the output produced by the website when that parameter is activated

### Steps to reproduce

result_handle=NCBIWWW.qblast('blastp', 'pdb_v5', 'QRFSQPTFKLPQGRLTLSRKF')

run above query and notice that no results are returned with the is query, while a large number or results are returned when run with the Adjust for short query parameter set to on (located in algorithm parameters section) in the website.

**Comment by peterjc** [comment]
Have you seen any NCBI documentation on their QBLAST API indicating if it supports this, and how to do this? Or are you willing and able to try investigating this on your own?

**Comment by KristaJ** [comment]
I haven't seen any documentation, but by looking at the service calls I've
been able to include the parameter into the call used by the qblast method.

**Comment by MarkusPiotrowski** [comment]
According to https://ncbi.github.io/blast-cloud/dev/api.html the `task` option, which would allow to specify `blastp-short` is *not* available in the common URL API. 
You'd need to pass the respecive parameters to simulate the ``short`` task (I think that's what you meant with your last comment), for `blastp-short` these are `expect=200000`, `matrix_name='PAM30'` and `word_size=2`.

**Comment by MarkusPiotrowski** [comment]
@KristaJ Can you explain a little bit, what you meant with your [comment](https://github.com/biopython/biopython/issues/2049#issuecomment-489465091) from above?
Did you get it working? And if, what have you done? How did you implement the parameter in the qblast call?

**Comment by KristaJ** [comment]
Sorry for the delay. Things have been hectic at work. 

I thought that I was able to include the parameter to optimize for short sequences, but it seemed intermittently functional. Can you please let me know where you found the parameters for the optimization. I looked for a reference but I couldn’t seem to find anything. 

Thanks,
Krista

**Comment by MarkusPiotrowski** [comment]
If you run a BLAST search manually on the Blast webpage with short sequences, on the result page you can either open "Search Summary" to see the parameters in use or go back with "Edit and resubmit" and look at the changes in the "Algorithm Parameters". The changed parameters are colored in yellow.

Actually, I found the the correct keyword for short searches, it is `SHORT_QUERY_ADJUST`. It works fine for `blastp` but it is obiously wrongly implemented for `blastn`, because there it gives an error. I will submit a pull request soon, which will allow to use this parameter with `Bio.Blast.NCBIWWW`.

**Comment by KristaJ** [comment]
I had added the SHORT_QUERY_ADJUST PARAMETER but it seemed to get hung up from time to time. I’m not sure it that was due to the added parameter or something else. 

But if it can be added that would be great. Thanks!

**Comment by MarkusPiotrowski** [comment]
This searches can take a long time and NCBI will penalize you, when you are using their services to often in a short time. 
I set up a test module for `Bio.Blast.NCBIWWW` yesterday, and after some tests, delay times became very long (I fall asleep when the last test run with 4 short searches took more than 50 minutes).

**Comment by KristaJ** [comment]
hmmm...thanks for the insight.  I may need to think of a different way
around this.

thanks again
-Krista
