### ISSUE TITLE
Duplicate files in Tests/Motif and Tests/motifs

### ISSUE THREAD

**Issue by victorlin** [biopython/biopython#2057]
The files in Test/motifs seem to be a copy of those in Test/Motif plus some more. Has the Motif directory been deprecated since renaming Bio.Motif to Bio.motifs?

**Comment by peterjc** [comment]
That is likely what happened, probably ``Tests/Motif`` can be removed (after moving any still in use files under ``Tests/motifs``)? Do you agree @mdehoon?

**Comment by mdehoon** [comment]
@peterjc , @victorlin  Yes I think `Tests/Motif` can be removed.

**Comment by peterjc** [comment]
@victorlin would you like to try doing this as a pull request?
