### ISSUE TITLE
Failed to find tag 'mtr' in the DTD by pmid=30971865

### ISSUE THREAD

**Issue by 6syun9** [biopython/biopython#2077]
### Setup

```
3.6.8 (default, Apr  9 2019, 17:16:47)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
CPython
Darwin-17.7.0-x86_64-i386-64bit
1.73
```

### Expected behaviour

We should return paper info from efetch API.
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=30971865

### Actual behaviour

Exception
```
ValidationError: Failed to find tag 'mtr' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.
```

### Steps to reproduce

```
from Bio import Entrez
print(Entrez.read(Entrez.efetch(db="pubmed", id='30971865', retmode='xml')))
```

This paper is `quite special`. I can not judge whether we should cope. But I reported once.

**Comment by peterjc** [comment]
Did you try parsing with ``validate=False`` as suggested, and did it work?

**Comment by 6syun9** [comment]
@peterjc Hi. Yes, I did.
```
Entrez.read(Entrez.efetch(db="pubmed", id='30971865', retmode='xml'), validate=False)
```
result:
```
TypeError: startElementHandler() takes 3 positional arguments but 4 were given
```
I think this error is "when the XML is broken".

**Comment by mdehoon** [comment]
Works for me with the current Biopython source code in master.

**Comment by 6syun9** [comment]
@mdehoon Thanks. I confirmationed works for me with the code in master too.
