### ISSUE TITLE
Removing Doc/biopdb_faq.lyx

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2094]
I've just noticed we have two copies of the PDB FAQ under version control, files ``Doc/biopdb_faq.lyx``  and ``Doc/biopdb_faq.txt``, which the original author Thomas would update together.

Having done a little background reading, my understanding ``Doc/biopdb_faq.lyx`` was the source (edited in the Lyx graphical tool), which was exported to LaTeX as ``Doc/biopdb_faq.txt`` (also under version control), which via the ``Makefile`` and ``pdflatex`` gets turned into PDF.

Looking at the history since 2007 people (starting with me) have been editing ``Doc/biopdb_faq.tex`` directly, so ``Doc/biopdb_faq.lyx `` is now out of date.

There have been relatively few changes, so we _could_ manually update ``Doc/biopdb_faq.lyx`` to get things back in sync.

However, given Lyx is yet another dependency, and we're talking about moving away from LaTeX itself (see #907), I think ``Doc/biopdb_faq.lyx`` can probably just be deleted.

**Comment by peterjc** [comment]
@JoaoRodrigues @etal @lennax @jgreener64 Any comments on this bit of the PDB documentation?

**Comment by jgreener64** [comment]
If it doesn't disrupt things I would lean towards deleting `Doc/biopdb_faq.lyx`. When I have to remember to update two things together I usually forget.

**Comment by peterjc** [comment]
Exactly the mistake I made in 2007, when the two files first went out of sync. If Thomas was still active and wanted to continue to use Lyx, things would be different.

**Comment by lennax** [comment]
Sorry for late comment - I agree that if no one is actively using Lyx, it makes sense to delete the out-of-date lyx file.

**Comment by peterjc** [comment]
Done in 3c59219ccc4260f4f9107f48abec82672aa3c529, thank you both for looking at this
