### ISSUE TITLE
[ENTREZ] Some accession numbers won't return FASTA data

### ISSUE THREAD

**Issue by vinisalazar** [biopython/biopython#2123]
### Setup
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0]
import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.18.0-20-generic-x86_64-with-debian-buster-sid
import Bio; print(Bio.__version__)
1.73
```

Hi, I'm trying to download a bunch of .fasta and .gbk records using `Entrez.efetch`. However, I have noticed that some of my UIDs return both fasta and genbank data, but some only return genbank data. For example:

```
net_handle = Entrez.efetch(db="nucleotide", id="NC_018645", rettype="fasta", retmode="text")  # This returns proper FASTA characters when I run net_handle.read()

net_handle = Entrez.efetch(db="nucleotide", id="NZ_AGNZ00000000", rettype="fasta", retmode="text")  # This only returns '\n' when I run net_handle.read()
```

I'm puzzled to why this is happening. Do the "NZ" and "NC" files come from different databases? I have a whole bunch of records I need to download (more than 10k) and I can't afford looking through all of them. When I ran tests on a small dataset, everything worked, but then again all accession numbers started with "NC".

Thank you for any assistance you can provide.
V

### Expected behaviour

Both accession numbers should return FASTA file.

### Actual behaviour

Accession numbers that start with "NZ" don't return any FASTA data.

### Steps to reproduce

```
# Run the following
from Bio import Entrez
net_handle = Entrez.efetch(db="nucleotide", id="NZ_AGNZ00000000", rettype="fasta", retmode="text")
net_handle.read()
```

**Comment by peterjc** [comment]
Yes, the accession prefix does I think reflect a different category in the NCBI databases.

In this case,

> Streptococcus pneumoniae GA47281, whole genome shotgun sequencing project
> NCBI Reference Sequence: NZ_AGNZ00000000.1
> This entry is the master record for a whole genome shotgun sequencing project and contains no sequence data.

https://www.ncbi.nlm.nih.gov/nuccore/NZ_AGNZ00000000

Note the default GenBank output here has not actual sequence, it just ends with instructions for what the record points at:

```
WGS         AGNZ01000001-AGNZ01000016
WGS_SCAFLD  NZ_AGNZ01000001-NZ_AGNZ01000016
//
```

Beyond that, you will need to ask the NCBI (try the Entrez help email address), and please comment here with any resolution. Or can we close this?

Depending on you actual goal here, https://github.com/kblin/ncbi-genome-download might be useful.

**Comment by vinisalazar** [comment]
Hi @peterjc , thank you for the prompt reply.

I considered using @kblin 's package but was trying to avoid (more) external dependencies in my project.

Would you mind leaving the issue open for now? Next week I'll be able to work and this and hopefully can post my solution to help other folks.

Sincerely,
V

**Comment by vinisalazar** [comment]
The only alternative I found was to extract Assembly identifiers from the Genbank records and then using ncbi-genome-download. Even then, some GenBank records didn't have these identifiers so I had to manually go after the genome.

**Comment by kblin** [comment]
@vinisalazar Another option is to grab the GenBank records, and then recursively grab the sub-records if the record you got was a WGS master record. I happen to have a library for that as well: https://github.com/kblin/ncbi-acc-download/ because I also was running into this a lot.

You can run this one as both a command line tool and a library. https://github.com/kblin/ncbi-acc-download/blob/master/ncbi_acc_download/wgs.py has the logic around WGS record download. Feel free to just reuse the strategy in your code if adding an extra dependency is a problem.

**Comment by vinisalazar** [comment]
@kblin thank you for your suggestions. Your work is very much appreciated. Would be great to see these contributions being somehow incorporated into Biopython's Entrez.
