### ISSUE TITLE
Unexpected output of pairwise2 localms

### ISSUE THREAD

**Issue by juheon** [biopython/biopython#2136]
### Setup

I am reporting a problem with Biopython version: 1.73, Python version, and operating
system as follows: 

```
Python 3.5.4 |Anaconda custom (64-bit)| (default, Nov 20 2017, 18:44:38)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.5.4 |Anaconda custom (64-bit)| (default, Nov 20 2017, 18:44:38)
[GCC 7.2.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.19.0-61-generic-x86_64-with-debian-stretch-sid
>>> import Bio; print(Bio.__version__)
1.73
```

### Expected behaviour

```
GCCATTAAAAGCATTGTCCATAAAAAAAAAAAAAAAAAAA-
                     |||||||||||||||||||
---------------------AAAAAAAAAAAAAAAAAAAA
    score=33

...(18 cases with the same score but with different gap locations)...
GCCATTAAAAGCATTGTCCAT-AAAAAAAAAAAAAAAAAAA
                      |||||||||||||||||||
---------------------AAAAAAAAAAAAAAAAAAAA
    score=33
```

### Actual behaviour
According to the https://biopython.org/DIST/docs/api/Bio.pairwise2-module.html, "Since Biopython 1.71 identical matches are shown with a pipe character, mismatches as a dot, and gaps as a space."
In the first result, the 21st base of sequence A is 'T' and the corresponding base of sequence B is 'A'. Since there is neither pipe nor dot character, the 21tst base seems to regarded as the gap. In that case, I think the score should be 33 (=2*19-5). However, the score is 38.
If the 21st base is a mismatch, the score should be 37 (=2*19-1). 
The unexpected behavior of the second result is basically the same as the first result. 
```
GCCATTAAAAGCATTGTCCATAAAAAAAAAAAAAAAAAAA
                     |||||||||||||||||||
--------------------AAAAAAAAAAAAAAAAAAAA
  Score=38

GCCATTAAAAGCATTGTCCATAAAAAAAAAAAAAAAAAAA-
                     |||||||||||||||||||
---------------------AAAAAAAAAAAAAAAAAAAA
  Score=38
```

### Steps to reproduce

```
from Bio import pairwise2
from Bio.pairwise2 import format_alignment
from Bio.Seq import Seq
x=pairwise2.align.localms( "GCCATTAAAAGCATTGTCCATAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAA", 2, -1, -5, -1 );
for i in x:
        print( format_alignment(*i))
```

**Comment by MarkusPiotrowski** [comment]
@juheon This is a **local** alignment, therefore leading or trailing gaps or mismatches are not counted (note: A local alignment will *always* start with a positive score!).
You have 19 matching A's with a match score of 2, makes a total score of 38.
This will become clearer with the next Biopython version (1.74), where this alignment would be printed as:
```python
>>> from Bio import pairwise2
>>> from Bio.pairwise2 import format_alignment
>>> x = pairwise2.align.localms(
	"GCCATTAAAAGCATTGTCCATAAAAAAAAAAAAAAAAAAA",
	"AAAAAAAAAAAAAAAAAAAA", 2, -1, -5, -1 )
>>> for i in x:
	print(format_alignment(*i))

	
22 AAAAAAAAAAAAAAAAAAA
   |||||||||||||||||||
 2 AAAAAAAAAAAAAAAAAAA
  Score=38

22 AAAAAAAAAAAAAAAAAAA
   |||||||||||||||||||
 1 AAAAAAAAAAAAAAAAAAA
  Score=38

>>> 
```

**Comment by juheon** [comment]
Thank you a lot. I missed the description of 'format_alignment'. I personally prefer to see the sequences of non-aligned parts of sequences. I am using the local alignment to trim polyA tail and I can tell whether my trimming is correct or not based on the non-aligned parts of sequences. 
I think the argument such as bShowOnlyAlignedPart in "format_alignment" could be useful for people like me.

**Comment by MarkusPiotrowski** [comment]
Re-opened. Having the option to show the whole local alignment including the non-aligned parts seems sensible.

**Comment by MarkusPiotrowski** [comment]
`format_alignment` has now a keyword parameter `full_sequences` which can be set to `True` to restore the 'old' output format (showing the whole sequences including the non-aligned parts)

**Comment by mdehoon** [comment]
@juheon 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
