### ISSUE TITLE
How to calculate the protein complex interface

### ISSUE THREAD

**Issue by hongzhonglu** [biopython/biopython#2163]
Hi all, do you know how to calculate the interface between protein and protein in a complex?

**Comment by jgreener64** [comment]
You mean you want to know which residues/atoms are part of the interface?

To get the residues where the C-alpha distance to the other chain is less than 8 Angstroms you can do:
```python
from Bio.PDB import PDBParser

p = PDBParser()
s = p.get_structure("", "4HHB.pdb")
chain_A = s[0]["A"]
chain_B = s[0]["B"]

for res_A in chain_A:
    for res_B in chain_B:
        try:
            dist = res_A["CA"] - res_B["CA"]
        except KeyError:
            # Skip non-standard residues and any with missing C-alpha
            pass
        if dist < 8.0:
            print(res_A, "contacts", res_B)
```
Change the PDB file, chain IDs, contact distance and contacting atoms as appropriate.

**Comment by hongzhonglu** [comment]
@jgreener64 Great thanks for your help! I find there are function in biopython to do it. But I found it can't work now in the biopython version 1.73:
from Bio.PDB import InterfaceBuilder

parser = PDBParser()
structure = parser.get_structure('test', '/home/directory/of/your/PDB/test.pdb')

**Comment by jgreener64** [comment]
`InterfaceBuilder` doesn't seem to be in the current Biopython version, where have you found reference to it?

**Comment by peterjc** [comment]
I suspect this is a reference to the GSoC 2011 work by @mtrellet here, mentored by @etal & @JoaoRodrigues:
https://github.com/mtrellet/biopython/tree/interface_analysis
https://biopython.org/wiki/GSoC2011_mtrellet

I don't recall this got to the point of a pull request to be merged into Biopython's master branch?

**Comment by mtrellet** [comment]
As far as I know and remember this project was unfortunately not mature enough to make it to the master branch.
@hongzhonglu Could it be that you are/were using a fork of the main biopython project?

**Comment by hongzhonglu** [comment]
@mtrellet  Yes. I am using the fork of the main biopython project.
