### ISSUE TITLE
struct.error unpack requires a buffer of 10 bytes

### ISSUE THREAD

**Issue by liugaocn** [biopython/biopython#2173]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-10-10.0.17763-SP0
1.73t*)

### Expected behaviour

(*I was trying to use Affy.Cel. It should read properly.*)

### Actual behaviour

(*intensity, stdevs, npix = structa.unpack(binaryFragment)
struct.error: unpack requires a buffer of 10 bytesl*)

### Steps to reproduce

(*If you mean how many times i tried. Lots. *)

**Comment by peterjc** [comment]
By steps to reproduce, we mean we want you to write something like:

1. Download this sample data file from URL ...
2. Run the following short self contained bit of Python code: ...
3. I get the following exception (not just the final line ``struct.error: unpack requires a buffer of 10 bytes``, the whole thing with filenames and line numbers): ...
4. I expected the script to do ... instead.

**Comment by liugaocn** [comment]
Thanks. 

**from Bio.Affy import CelFile
with open("Affy/affy_v4_example.CEL", "rb") as handle:
         c = CelFile.read(handle)
print(c.version)**

print(c.version)  throws struct.error

**Comment by peterjc** [comment]
Thank you. That worked for me on macOS with Python 3.6.4, we probably need to test this on windows.

One possibility is that the CEL file has been corrupted with Unix vs WIndows new lines (even though it is meant to be a binary file). How big is your file and/or what's the MD5 checksum? I see it as 1079 bytes, MD5 checksum ``1f8ffd17bcd2134f93891cc297ae2881``.

Peter

**Comment by MarkusPiotrowski** [comment]
Works for me with Python 2.7.16 on Windows 7 and also with Python 3.7.3 on Windows 10 (using our dev branch):
```bash
F:\git_32bit\biopython>python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio.Affy import CelFile
Bio\__init__.py:128: BiopythonWarning: You may be importing Biopython from insid
e the source tree. This is bad practice and might lead to downstream issues. In
particular, you might encounter ImportErrors due to missing compiled C extension
s. We recommend that you try running your code from outside the source tree. If
you are outside the source tree then you have a setup.py file in an unexpected d
irectory: .
  format(_parent_dir), BiopythonWarning)
>>> with open("tests/affy/affy_v4_example.CEL", "rb") as handle:
...     c = CelFile.read(handle)
...
>>> print(c.version)
4
>>>
```

**Comment by liugaocn** [comment]
I just re-ran with the example v4 cel file. And it worked, so maybe it was because I didn't save it before I ran. But anyhow, I still cannot open my own cel files. I  tried several different cel files. All attempts failed.
I downloaded my cel files from pubmed (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE128955).
when I try to print c.version, it gives me "None". 
**from Bio.Affy import CelFile
with open("GSM3688968_WM793TR_CTRL_1.CEL", "rb") as handle:
	c = CelFile.read(handle)
	print(c.version)
	print(c)**
Output as:
**None
<Bio.Affy.CelFile.Record object at 0x000001B403F10C50>**
Besides, this old page also states the same problem.

**Comment by liugaocn** [comment]
> 
> 
> Thank you. That worked for me on macOS with Python 3.6.4, we probably need to test this on windows.
> 
> One possibility is that the CEL file has been corrupted with Unix vs WIndows new lines (even though it is meant to be a binary file). How big is your file and/or what's the MD5 checksum? I see it as 1079 bytes, MD5 checksum `1f8ffd17bcd2134f93891cc297ae2881`.
> 
> Peter
I tried with different size of files. 
It seems like some kinda memory error. But I have 12GB of memory.

**Comment by liugaocn** [comment]
**updates**
I just tried to specifically use read_v4:
```from Bio.Affy import CelFile
with open("GSM1924571_L80NSC1.CEL", "rb") as handle:
    c = CelFile.read_v4(handle)
print(c.version)```

And then I get:
...line 3, in <module>
    c = CelFile.read_v4(handle)
  File "C:\Users\Gao\AppData\Local\Programs\Python\Python37\lib\site-packages\Bio\Affy\CelFile.py", line 192, in read_v4
    raise ParserError("You are trying to parse CEL file version 4. This"
Bio.Affy.CelFile.ParserError: You are trying to parse CEL file version 4. This file violates the structure expected from CEL file version 4

What should I do?

**Comment by peterjc** [comment]
Can you share an example file with this problem?

Do you know anything about how the problematic files were created? What version of the CEL format are they meant to be?

**Comment by liugaocn** [comment]
[GSM3688968_WM793TR_CTRL_1.zip](https://github.com/biopython/biopython/files/3408855/GSM3688968_WM793TR_CTRL_1.zip)
Thank you for checking this out. This is one of my CEL files I want to open with biopython.

**Comment by MarkusPiotrowski** [comment]
@liugaocn When you open one of these files in a text editor you will see that the format is totally different from the format of the two demo CEL files in our test folder.
[Reading here](https://www.affymetrix.com/support/developer/powertools/changelog/gcos-agcc/cel.html#calvin) it seems that your files are in the **Command Console Format** which seems to be not supported by Biopython's CEL parser.

**Comment by MarkusPiotrowski** [comment]
Of course, this should throw an exception. @picrin?

**Comment by picrin** [comment]
Hi Markus, AFAIR the only two formats we support are version 3 format and version 4 format. "Command Console Format" is not supported. And agreed, ideally we would detect the format and throw an exception.

**Comment by MarkusPiotrowski** [comment]
Reopening, since the principal problem hasn't been solved.

@picrin: Do you want to give it a try?

**Comment by picrin** [comment]
Sorry guys, I'm entirely in a PhD-writeup mode, unable to divert much of my focus away ATM. Could do a code review?

**Comment by peterjc** [comment]
@liugaocn do you fancy trying this as your first Biopython contribution? Adding a try/except and raising a ``ValueError`` with a message about not being in the expected format?

**Comment by liugaocn** [comment]
Hahah. I don't know much about this format yet. It would be difficult for me to add support for this format. 
This .cel format seems to be popular on pubmed.

**Comment by peterjc** [comment]
Adding a new format would be an impressive first contribution - but I meant just graceful error handling when trying to parse the wrong file format instead of the ``struct.error: unpack requires a buffer of 10 bytes`` exception.
