### ISSUE TITLE
multiline text in GenBank structured comments are not parsed correctly

### ISSUE THREAD

**Issue by vkkodali** [biopython/biopython#2177]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.0.0-20-generic-x86_64-with-Ubuntu-19.04-disco
>>> import Bio; print(Bio.__version__)
1.73
```
When parsing a GenBank flat file with structured comment that has multiline annotations as shown below, only the information in the first line is captured. The following example uses the following flatfile: https://www.ncbi.nlm.nih.gov/nuccore/NM_000017
```
            ##RefSeq-Attributes-START##
            gene product(s) localized to mito. :: reported by MitoCarta
            MANE Ensembl match                 :: ENST00000242592.9/
                                                  ENSP00000242592.4
            RefSeq Select criteria             :: based on conservation,
                                                  expression, longest protein
            ##RefSeq-Attributes-END##
```
With this flatfile saved as `temp.gb`, I run the following code: 
```python
>>> with open('temp.gb', 'r') as f:
...     hdl = SeqIO.parse(f, 'genbank')
...     for rec in hdl:
...             print(rec.annotations['structured_comment']['RefSeq-Attributes'])
... 
OrderedDict([('gene product(s) localized to mito.', 'reported by MitoCarta'), ('MANE Ensembl match', 'ENST00000242592.9/'), ('RefSeq Select criteria', 'based on conservation,')])
```
### Expected behaviour
The value for the key `MANE Ensembl match` should be `ENST00000242592.9/ENSP00000242592.4`
### Actual behaviour
Only the accession in the first line is returned; `ENSP00000242592.4` is lost

**Comment by peterjc** [comment]
Could you re-test with Biopython 1.74 (although looking at the code I don't think this has changed recently)?

**Comment by vkkodali** [comment]
I see the same issue with Biopython 1.74
```python
>>> import Bio; print(Bio.__version__)
1.74
>>> from Bio import SeqIO
>>> with open('temp.gb', 'r') as f:
...     hdl = SeqIO.parse(f, 'genbank')
...     for rec in hdl:
...             print(rec.annotations['structured_comment']['RefSeq-Attributes'])
...
OrderedDict([('gene product(s) localized to mito.', 'reported by MitoCarta'), ('MANE Ensembl match', 'ENST00000242592.9/'), ('RefSeq Select criteria', 'based on conservation,')])
```

**Comment by peterjc** [comment]
@vkkodali would the proposed behaviour on #2355 cover your needs?

**Comment by vkkodali** [comment]
> @vkkodali would the proposed behaviour on #2355 cover your needs?
Yes. I don't know how to test it though.

**Comment by matteougolotti** [comment]
Hi @vkkodali 

You can test it like this

Prerequisites
---
- Install virtualenv (https://virtualenv.pypa.io/en/latest/)
``` bash
python -m pip install --user virtualenv
```

Setup a testing environment
---
- Prepare a clean directory
``` bash
mkdir biopython_issue_2177_test
cd biopython_issue_2177_test
```

- Setup a Python virtual environemnt to work in
``` bash
python -m virtualenv -p python venv
source venv/bin/activate
```

- Clone the Biopython repository from my fork
``` bash
git clone https://github.com/matteougolotti/biopython.git
cd biopython
```

- Checkout the branch which includes the new changes
``` bash
git checkout issue-2177
```

- Build and install from source
``` bash
python setup.py build
python setup.py install
```

- Exit the source tree
``` bash
cd ..
```

Test
---
- Now you can open a Python shell and test as with the code snippet you provided. While you stay in the Python virtual environment you will be importing the patched version of Biopython.

- After your test you can deactivate the Python virtual environment
``` bash
deactivate
```

Let me know if you have any issue ;)

**Comment by vkkodali** [comment]
Thank you @peterjc  for such detailed instructions. 
Yes, the fix from #2355 covers this issue as well. There is one minor correction needed. When concatenating the text from two lines, there should be single space character introduced. Take, for example, [NM_001376916](www.ncbi.nlm.nih.gov/nuccore/NM_001376916.1) which has the following: 
```
            ##RefSeq-Attributes-START##
            RefSeq Select criteria :: based on manual assertion, longest
                                      protein
            ##RefSeq-Attributes-END##
```
After parsing the dictionary has the following: 
```
OrderedDict([('RefSeq Select criteria', 'based on manual assertion, longestprotein')])
```
Note, it should be `longest protein` and not `longestprotein`. 
Another example, NM_003173:
```
OrderedDict([('Transcript exon combination', 'SRR1803616.168319.1,SRR1803612.15459.1 [ECO:0000332]'), ('RNAseq introns', 'single sample supports all intronsSAMEA1965299, SAMEA1966682[ECO:0000348]')])
```
Note, there should be a space between `introns` and `SAMEA1965299`.

**Comment by matteougolotti** [comment]
@vkkodali indeed, thanks for pointing this out, I will modify my patch to introduce an additional whitespace after each newline.

**Comment by matteougolotti** [comment]
Ok @vkkodali , now a single white space should be added before any new line. Would you mind testing again ?

**Comment by vkkodali** [comment]
Thank you @matteougolotti this looks good. I think you can declare victory!

**Comment by peterjc** [comment]
This was very useful feedback @vkkodali - I've merged the updated pull request from @matteougolotti - thank you both!
