### ISSUE TITLE
Parser Warnings not being reported

### ISSUE THREAD

**Issue by TBWarrington** [biopython/biopython#2183]
### Setup

I am reporting a problem with Biopython version: 1.74, Python version: 3.6.4, and operating
system: Ubuntu (Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic). Problem also in Biopython version 1.73, Python version 3.7.3 on Windows 10 (Windows-10-10.0.17763-SP0).

### Expected behaviour

Parser Warning warns when it can't parse a feature location when importing genbank files. Works on single genbank files or small multipart files.

### Actual behaviour

Seems to miss some warnings on longer files.

### Steps to reproduce

run attached script:
python3 convert_nonstandard_gb.py -f benchling_export.gb

I have a script to split and repair some improperly formatted genbank files. Since the parser warnings include the improperly formatted text I am using them to identify the and correct the text. Unfortunately, it appears that in longer multipart files the warnings aren't always reported. 

Please feel free to suggest alternative solutions to my problem. Using the warnings was convenient but there may be better ways to accomplish my task.

[convert_nonstandard_gb.zip](https://github.com/biopython/biopython/files/3428731/convert_nonstandard_gb.zip)

**Comment by peterjc** [comment]
My guess would be Python's default warning filters suppress duplicate
warnings with the exact same message, and I don't think you are preventing
that.

I would probably write this with the ``warnings`` module used to catch the
warnings by class, see:

https://docs.python.org/3/library/warnings.html#warnings.catch_warnings

I thought we had an example doing something like this in the Tutorial but I
don't see it.

https://docs.python.org/3/library/warnings.html

>

**Comment by TBWarrington** [comment]
Yep, that's exactly what was happening. Added this to my script:
warnings.simplefilter('always', Warning)

Works fine now. Thanks!
