### ISSUE TITLE
Bio.pairwise2.align.localds now inconsistently adds labels for some alignments

### ISSUE THREAD

**Issue by cariaso** [biopython/biopython#2216]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```2.7.16 (default, Jul 19 2019, 22:59:28)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
CPython
Linux-4.14.77-70.59.amzn1.x86_64-x86_64-with-glibc2.2.5
1.74
```

in comparison to 1.73

### Expected behaviour

consistency between 1.73 and 1.74

### Actual behaviour

localds alignments sometimes include numeric positions

### Steps to reproduce

```
import Bio.pairwise2
import Bio.SubsMat.MatrixInfo


if __name__ == '__main__':

    gap_open_penalty = -3
    gap_extend_penalty = -1

    seq1 = 'ATCGATCG'
    seq2 = seq1[1:]


    alignment = Bio.pairwise2.align.localds(seq1,
                                            seq1,
                                            Bio.SubsMat.MatrixInfo.blosum62,
                                            gap_open_penalty,
                                            gap_extend_penalty)
    ready = Bio.pairwise2.format_alignment(*alignment[0])
    print(ready)


    alignment = Bio.pairwise2.align.localds(seq1,
                                            seq2,
                                            Bio.SubsMat.MatrixInfo.blosum62,
                                            gap_open_penalty,
                                            gap_extend_penalty)
    ready = Bio.pairwise2.format_alignment(*alignment[0])
    print(ready)
```

```
$ pip install 'biopython==1.73' --user
Successfully installed biopython-1.73
$ python fail1.py
ATCGATCG
||||||||
ATCGATCG
  Score=48

ATCGATCG
 |||||||
-TCGATCG
  Score=44

$ pip install 'biopython==1.74' --user
Successfully installed biopython-1.74
$ python fail1.py
ATCGATCG
||||||||
ATCGATCG
  Score=48

2 TCGATCG
  |||||||
1 TCGATCG
  Score=44
```

specifically the inconsistent presence of ' 2 ' (and the similar formatting) on the lower rows is problematic. It makes downstream parsing difficult, and deviates from the behavior of earlier versions.

**Comment by peterjc** [comment]
You are not expected to parse the output from ``Bio.pairwise2.format_alignment()`` - What are you trying to do? It would be better to access the values directly.

I think the "inconsistency" is the following behaviour:

> Also, in local alignments, if the alignment does not include the whole sequences, now only the aligned part is shown, together with the start positions of the aligned subsequences. The start positions are 1-based; so start position n is the n-th base/amino acid in the *un-aligned* sequence.

https://github.com/biopython/biopython/blob/biopython-174/Bio/pairwise2.py#L1102

**Comment by cariaso** [comment]
```
        ready = format_alignment(*alignment)
        top, mid, bot, score, extra = ready.split('\n')
vs
        top, bot, score = alignment[:3]
```
but what is the equivalent for computing mid?

**Comment by peterjc** [comment]
The exact content has changed over the years, I would suggest writing your own function doing what do want it to be? e.g.

```python
def match_string(a, b, gap="-", match="|", diff="."):
    """Match string for two letters."""
    if a == b:
        return match
    elif a == gap or b == gap:
        return gap
    else:
        return diff

top = "AT-GATCG"
bot = "ATCGATCA"
mid = "".join(match_string(a, b) for (a, b) in zip(top, bot))

print(top + "\n" + mid + "\n" + bot)
```

Gives:

```
AT-GATCG
||-||||.
ATCGATCA
```

**Comment by cariaso** [comment]
I can, and probably will. but given the need for a 'roll your own'. I doubt I'm the only one who's done this, and the change in behavior is probably silently biting a lot of other codes.

**Comment by peterjc** [comment]
I think the real problem was the temptation to parse "pretty output" intended for humans, rather than the module exposing the match string as a method or attribute or something. That could still be added?

The changes in Biopython 1.71 and 1.74 were both in the ``NEWS.rst`` file. The pull requests for those changes:
- https://github.com/biopython/biopython/pull/1352
- https://github.com/biopython/biopython/pull/1505

See also the new pairwise sequence aligner in ``Bio.Align`` added in Biopython 1.72, intended as an alternative to ``Bio.pairwise2`` (better performant in many cases).

**Comment by MarkusPiotrowski** [comment]
Re-opening, until #2143 is merged.

Sorry, I was on holidays. 

Actually there is a pull request which allows to set the old behaviour (PR #2143), but it seems, unfortuntately, that we forgot to merge it before releasing Biopython 1.74.

**Comment by MarkusPiotrowski** [comment]
`format_alignment` has now a keyword parameter `full_sequences` which can be set to `True` to restore the 'old' output format (showing the whole sequences including the non-aligned parts).
