### ISSUE TITLE
Proposal: pairwise2.align return type

### ISSUE THREAD

**Issue by mobiusklein** [biopython/biopython#2221]
The return value of `Bio.pairwise2.align` functions is a `tuple` of values whose index labels can only be inferred from reading the (thorough) documentation. This tuple is convenient to pass among functions but is hard for a human to read, especially if the sequence length exceeds the width of the display area.

This proposal suggests replacing the returned tuple with a `namedtuple` based class:
```python
class Alignment(namedtuple("Alignement", ("sequence1", "sequence2", "score", "begin", "end"))):
    __slots__ = []
    
    def render(self, **kwargs):
        return format_alignment(*self, **kwargs)

    def __repr__(self):
        return self.render()
```
Because this is still a `tuple`, it should support all of the previous behavior while providing more convenient interface.

I've got a rough refactoring of `format_alignment` to make it wrap over multiple lines, but it doesn't yet include PR #2143's changes. 

Is there anything else this `Alignment` class should be able to do?

**Comment by peterjc** [comment]
Using a ``namedtuple`` seems a low risk improvement, but I will defer to @MarkusPiotrowski and @mdehoon for pairwise changes.

**Comment by mdehoon** [comment]
I am against adding one more `Alignment` class to Biopython (there is already a `MultipleSeqAlignment` and a `PairwiseAlignment` class in `Bio.Align`). Could you use the pairwise aligner in `Bio.Align` as a replacement for `Bio.pairwise2`? Then the alignment will be returned as an object.

**Comment by mobiusklein** [comment]
That does appear to be faster, though it also seems to produce an improbable number of optimal alignments:
```python
from Bio import Align
from Bio.SubsMat.MatrixInfo import blosum62

pw = Align.PairwiseAligner()
pw.substitution_matrix = blosum62

b = pw.align(
'MSLEQRSLHCKPEEALEAQQEALGLVCVQAATSSSSPLVLGTLEEVPTAGSTDPPQSPQGASAFPTTINFTRQRQPSEGSSSREEEGPSTSCILESLFRAVITKKVADLVGFLLLKYRAREPVTKAEMLESVIKNYKHCFPEIFGKASESLQLVFGIDVKEADPTGHSYVLVTCLGLSYDGLLGDNQIMPKTGFLIIVLVMIAMEGGHAPEEEIWEELSVMEVYDGREHSAYGEPRKLLTQDLVQEKYLEYRQVPDSDPARYEFLWGPRALAETSYVKVLEYVIKVSARVRFFFPSLREAALREEEEGV', 
'MPLEQRSQHCKPEEGLEARGEALGLVGAQAPATEEQEAASSSSTLVEVTLGEVPAAESPDPPQSPQGASSLPTTMNYPLWSQSYEDSSNQEEEGPSTFPDLESEFQAALSRKVAKLVHFLLLKYRAREPVTKAEMLGSVVGNWQYFFPVIFSKASDSLQLVFGIELMEVDPIGHVYIFATCLGLSYDGLLGDNQIMPKTGFLIIILAIIAKEGDCAPEEKIWEELSVLEVFEGREDSIFGDPKKLLTQYFVQENYLEYRQVPGSDPACYEFLWGPRALIETSYVKVLHHMVKISGGPRISYPLLHEWALREGEE')
len(b)
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-611-97d8916a185b> in <module>()
----> 1 len(b)

C:\...\AppData\Local\Continuum\anaconda2\lib\site-packages\Bio\Align\__init__.pyc in __len__(self)
   1176 
   1177     def __len__(self):
-> 1178         return len(self.paths)
   1179 
   1180     def __getitem__(self, index):

OverflowError: number of optimal alignments is larger than 9223372036854775807
```
Is `pairwise2` deprecated?

Is there any will to include a version of the aligner from:
>        Zhao, Mengyao, Wan-Ping Lee, Erik P. Garrison, & Gabor T.
>        Marth. "SSW Library: An SIMD Smith-Waterman C/C++ Library for
>        Applications". PLOS ONE (2013). Web. 11 July 2014.
>        http://www.plosone.org/article/info:doi/10.1371/journal.pone.0082138

**Comment by mdehoon** [comment]
@mobiusklein 
> though it also seems to produce an improbable number of optimal alignments:

Why do you think it is improbable?

**Comment by mobiusklein** [comment]
I didn't expect it to produce that many optimal solutions. Then again, the total number of ways that those two sequences could be compared exceeds 309 ** 315, which is much larger than what `Py_ssize_t` could hold.

**Comment by mdehoon** [comment]
@mobiusklein  See section 6.5.2.8 in the Biopython documentation for more information.

**Comment by peterjc** [comment]
Currently ``Bio.pairwise2`` is not deprecated, but that is a possibility if the new aligner code proves itself (added a year ago in Biopython 1.72).

How easy would it be just to change the return value of the ``Bio.pairwise2.align`` functions from ``tuple`` to ``namedtuple`` (given there is a Python and a C implementation)?

(That seems to me to be a minimal change from the user perspective, but a usability improvement)

**Comment by mobiusklein** [comment]
Thank you for the reference. I suppose it's a mismatch between my expectation that if `__len__` is implemented, it will return a useful value, and the complexity of sequence alignment. For simpler sequence comparisons, `__len__` would produce a useful value, and if the query for total number of optimal alignments weren't passing through `__len__` it would be possible to return a `PyInt/Long` which an take on arbitrarily large integer values.

This proposal would have just added an extra loop at [master/Bio/pairwise2.py#L498](https://github.com/biopython/biopython/blob/master/Bio/pairwise2.py#L498) to convert the list of tuples into a list of the new `namedtuple` based type. The change would be far removed from the relevant C code.

**Comment by mdehoon** [comment]
> For simpler sequence comparisons, __len__ would produce a useful value, and if the query for total number of optimal alignments weren't passing through __len__ it would be possible to return a PyInt/Long which an take on arbitrarily large integer values.

In principle yes, but that would have to be implemented in the C code, and supporting arbitrarily large integer values in C code is not trivial. Additionally, if the number of alignments is huge, then the actual number doesn't really matter (iterating over them would take forever), so you may as well raise an `OverflowError`.

**Comment by MarkusPiotrowski** [comment]
@mobiusklein The original issue has been solved with #2603 (`pairwise2` now returns the alignments as namedtuples).
OK to close?

**Comment by mobiusklein** [comment]
Yes, okay to close. Thank you for the discussion.

**Comment by mdehoon** [comment]
@mobiusklein 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
