### ISSUE TITLE
Implement support for parsing PQR files

### ISSUE THREAD

**Issue by zisikons** [biopython/biopython#2226]
### Description:
The [PQR](https://sites.google.com/a/poissonboltzmann.org/software/file-formats/biomolecular-structurw/pqr) is a format that is very similar to the [PDB](https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html) format,  where the *beta factor* and *occupancy* fields have been replaced with *charge* and *radius*. Although this format is not as popular as the PDB format, several computational biology programs and researchers use it. 

Since we (me and @artbendandi ) extensively use the PQR format in our research, based on the [existing PDB parser](https://github.com/biopython/biopython/tree/master/Bio/PDB) we have implemented (a beta version) I/O support for PQR files, which we now want to contribute to the Biopython project.

### Sample PQR File:
In most cases, one can directly derive the PQR file from an existing PDB file by using the appropriate software (you can find an online service for doing so [here](http://nbcr-222.ucsd.edu/pdb2pqr_2.1.1/)) . For instance, after downloading the .pdb file for [Taurine](http://www.rcsb.org/structure/6EDH), one can use the aforementioned link to convert it to a .pqr file. I am attaching both the .pqr and .pdb files for comparison (and later, testing): [6edh.zip](https://github.com/biopython/biopython/files/3530449/6edh.zip)

### Purpose of this ticket:
In this issue, we would like to discuss some implementation details, before we submit the final version of our code. In particular:

- since our parser is heavily based upon the implementation of the PDB parser, we are considering developing a separate PQR I/O module that inherits most of its functionality from the existing code versus directly modifying the existing implementation ( i.e. adding a flag to differentiate PDB from PQR files). Take note that we only modified `Atom.py`, `StructureBuilder.py`, `PDBParser.py` and `PQRIO.py`. 

- if you examine the generated .pqr file, you can see that the header consists only of autogenerated remarks. Therefore we decided to use the [existing header parser](https://github.com/biopython/biopython/blob/master/Bio/PDB/parse_pdb_header.py) for .pdb files. Do you think this could lead to a problem?

Thank you for your time. We look forward to your suggestions.
@joaorodrigues @lennax  @jgreener64

**Comment by peterjc** [comment]
I was emailed privately about this beforehand, and suggested those three names as people familiar with the PDB code and worth consulting.

**Comment by jgreener64** [comment]
Sounds like a good idea to have something like this in Biopython. Having a quick look at the file format, and based on what you say, it seems to differ principally in two places: the charge/radius fields replacing bfac/occupancy and a different header. So the implementation is probably best kept as close as possible to the existing PDB parser, which it sounds like you have done. Reducing code duplication would be important as it makes it easier to maintain down the line.

Using the structure of the existing header parser sounds fine, but I would consider defining a different version of the `_parse_pdb_header_list` function for pqr files unless you can unambiguously assign things to the pqr header. For example, the pqr files have lines like:

```
REMARK   5 Warning: O in HOH A 562 skipped when optimizing O in HOH A 538
``` 

but the [PDB docs](https://www.wwpdb.org/documentation/file-format-content/format33/remarks1.html) say that remark 5 is for describing why a structure was obsoleted, so there may theoretically be some conflict.

I'm happy to look at a pull request when it's ready.

**Comment by artbendandi** [comment]
Regarding the header parser, according to the Bio.PDB documentation, the only accessible information on PDB file headers, as entries of a dictionary, are: name, head, deposition_date, release_date, structure_method, resolution, structure_reference, journal_reference, author and compound.

The remark types present in PQR files do not  contain these keywords and would be ignored by the already present header parser. For this reason, we believe that there shouldn’t be any conflict when it comes to REMARK type differences between PQR and PDB files. Furthermore, PQR file REMARK types are much more loosely defined than in the case of PDB files, and, to our knowledge, there is no documentation on headers of PQR files. Finally, by observation of PQR files, we see that the same REMARK type can be formatted differently, making data mining difficult, as there is no single format per REMARK type for the parser to identify, as is done with some REMARK types by the PDB header parser (for example in Bio/PDB/parse_pdb_header.py lines 296-318).

**Comment by jgreener64** [comment]
Ah I see, you are using the existing function without adding to it. That sounds sensible given what you have said, as it is conceivable that PQR files would have some of the PDB header information. And if they don't then nothing will get read in, which is fine.

**Comment by artbendandi** [comment]
We finished working on this issue, run the relevant tests, and we address it [this pull request](https://github.com/biopython/biopython/pull/2338)
We are available for any additional changes. Feedback is welcome.
