### ISSUE TITLE
ModuleNotFoundError: No module named 'Bio'

### ISSUE THREAD

**Issue by alissawilliams** [biopython/biopython#2238]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
(base) Alissas-MacBook-Pro:bin alissawilliams$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-18.6.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Bio'

### Expected behaviour, Actual behaviour, Steps to reproduce

I recently got a new computer (mac), and installed Python via Anaconda. I was able to use biopython no problem yesterday with the import statement:
`    from Bio import SeqIO
`
However, today I was trying to use a function in the package Phylo. At first I didn't realize it was part of biopython, so I tried:
`    import phylo
`
When that didn't work, I tried to install it:
`    python -m pip install phylo
`
which of course didn't work. The output of that command was:
```
    Collecting phylo
      ERROR: Could not find a version that satisfies the requirement phylo (from versions: none)
    ERROR: No matching distribution found for phylo
```

I then went back into a Python shell and typed:
`    import Bio
`
which gave me the error:
`    ModuleNotFoundError: No module named 'Bio'
`
Thus, I tried to install biopython using:
`    python -m pip install Bio
`
After that, I still got the "No module called 'Bio'" error in the Python shell. I have since tried to install/reinstall biopython in a bunch of different ways, to no avail. Here's what I've tried:

```
    python -m pip install biopython
    pip install biopython
    pip install biopython --upgrade
    pip3 install biopython 
    pip install biopython --user
```
Except in the case of the pip3 command, which didn't work at all, every installation said it was successful. And yet I STILL can't import Bio. I also can't import it as biopython. The statement:
`    import bio
`
did work, but none of the needed packages are included.

**Comment by alissawilliams** [comment]
In the directory:
/Users/alissawilliams/anaconda3/lib/python3.7/site-packages/

all of these are listed:
bio
bio-0.1.0.dist-info
biopython-1.74.dist-info

in case that's any help.

**Comment by MarkusPiotrowski** [comment]
Have you 'activated' your environment via:
```
> conda activate
```

? When I start Python via the command line, without activating an environment, I got the following message:
``` bash
C:\WINDOWS\system32>python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Bio
>>
```

Now:
```bash
>>> exit()

C:\WINDOWS\system32>conda activate

(base) C:\WINDOWS\system32>python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:49:40) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> Bio.__version__
'1.74'
>>>
```

I also wonder that `import bio` (with lowercase b) works in your case. This may indicate that you have another package installed. Have you tried (after `import bio`) to do `bio.__version__` and `help(bio)`?

**Comment by MarkusPiotrowski** [comment]
BTW, if you use Anaconda you should use it's conda package manager for installing packages:
```
> conda install biopython
```

Although I haven't experienced problems when using `pip` in Anaconda installations, others have.

**Comment by alissawilliams** [comment]
I tried the conda activate command and it still doesn't work. I also tried the conda install command, also to no avail. :( 

As for the two commands you mention:
bio.__version__
`'1.74'`
help(bio)
```
Help on package bio:

NAME
    bio - Collection of modules for dealing with biological data in Python.

DESCRIPTION
    The Biopython Project is an international association of developers
    of freely available Python tools for computational molecular biology.
    
    http://biopython.org

PACKAGE CONTENTS
    Affy (package)
    Align (package)
    AlignIO (package)
    Alphabet (package)
    Application (package)
    Blast (package)
    CAPS (package)
    Cluster (package)
    Compass (package)
    Crystal (package)
    Data (package)
```
In my site-packages directory, I have three things with "bio" in the name:
bio
bio-0.1.0.dist-info
biopython-1.74.dist-info

Do you think that me starting with the command
`python -m pip install Bio`
somehow overwrote biopython? I don't know what bio-0.1.0 is.

Thanks,
Alissa

**Comment by alissawilliams** [comment]
Update: I fixed the issue! 

I ended up uninstalling biopython, and also deleted any file in site-packages with the name "biosomething." I then reinstalled with the conda command:
`conda install -c anaconda biopython`

I am now able to use the import Bio command. Thanks for your help! 
Alissa

**Comment by MarkusPiotrowski** [comment]
Strange, so somehow your Biopython package name was renamed to `bio` (lowercase b)... I could have spotted this earlier since the folder in `site-packages` should be `Bio`. Possibly due to the installation of a package called `bio`, as you suggested (which is very likely this one: https://pypi.org/project/bio/)

Thank you for the update. Luckily, you got it running now.

Closing
