### ISSUE TITLE
BSD dual licensing Bio/PDB/Entity.py

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2241]
Sub-issue of #898, original author Thomas Hamelryck and all the committers since to ``Bio/PDB/Entity.py`` as tracked with version control have agreed.

However, looking at the logs I found a further contributor, Klaus Kopec for b1fe143df162ed1eae881611864ffe1ebaac39ac in 2009 via our old RedMine issue tracker. His old tuebingen.mpg.de email address no longer works.

This might be him https://www.linkedin.com/in/klauskopec - @cbrueffer could you try contact via LinkedIn please?

**Comment by cbrueffer** [comment]
I've send him a message.

**Comment by klauskopec** [comment]
Hey Peter, Christian,

Funny to be contacted for this after so many years, it was a nice blast from my researcher life past!

Obviously, I'm herewith giving you my consent to any license change you need to do for biopython. Further I waive any rights I might have around my contribution to biopython and donate it back to the biopython project or whomever else might be legally entitled to make decisions about this contribution of mine in the future.

Please let me know if you need anything else from me to proceed with your plans!

**Comment by peterjc** [comment]
Thank you Klaus - we're not currently setup with a legal entity to hold any copyrights, but it has been suggested. That is all we need for now, much appreciated.

**Comment by peterjc** [comment]
Included on pull request #2242
