### ISSUE TITLE
Dual licensing Bio.Nexus

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2246]
Sub-issue of #898, we have not yet heard from the original (co)author of ``Bio.Nexus``, Frank Kauff (CVS username fkauff, joined GitHub as @frankkl) about moving to the 3-clause BSD license.

@cymon - do you have his current contact information?

**Comment by frankkl** [comment]
Hi there, I'm here :-)

I totally agree to the move.


Cheers,

Frank


Am 30.08.2019 um 18:14 schrieb Peter Cock:

**Comment by peterjc** [comment]
Excellent, thank you Frank.

**Comment by peterjc** [comment]
Belatedly closing this issue via #2250
