### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'status'

### ISSUE THREAD

**Issue by rafaeltiveron** [biopython/biopython#2257]
Testing Entrez as follow, not obtaining server response? Server time out?

`handle = Entrez.esummary(db="pubmed", id="19304878,14630660", retmode="xml")`

```
handle = Entrez.einfo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\Bio\Entrez\__init__.py", line 298, in einfo
    return _open(cgi, variables)
  File "C:\Python27\lib\site-packages\Bio\Entrez\__init__.py", line 564, in _open
    and exception.status // 100 == 4:
AttributeError: 'HTTPError' object has no attribute 'status'
```
Ref: https://biopython.org/DIST/docs/api/Bio.Entrez-module.html

**Comment by rafaeltiveron** [comment]
Yes, it was outstage.

**Comment by peterjc** [comment]
Outstage?

**Comment by rafaeltiveron** [comment]
Outage rsrsrsrsr
Sorry

**Comment by peterjc** [comment]
Ah - I was unable to connect to Entrez either earlier today.

That aside, the attribute error suggests a problem in our error handling code - but it could be tricky to diagnose without a reproducible test case. Any thoughts @mdehoon?

**Comment by rafaeltiveron** [comment]
Connection returned
