### ISSUE TITLE
Bio.SeqIO fails to parse GenBank transcriptome shotgun assembly records

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#2268]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
>>> import sys; print(sys.version)
3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import Bio; print(Bio.__version__)
1.74
>>> 
```

### Expected behaviour

Loading a transcriptome shotgun assembly record should work, similar to how we can load WGS records.

### Actual behaviour

```
$ curl "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?tool=ncbi-acc-download&retmode=text&id=GHGH00000000.1&db=nucleotide&rettype=gbwithparts" > broken.gbk

$ python -c 'from Bio import SeqIO; recs = list(SeqIO.parse("broken.gbk", "genbank"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kai/.virtualenvs/nad3/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 661, in parse
    for r in i:
  File "/home/kai/.virtualenvs/nad3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py", line 493, in parse_records
    record = self.parse(handle, do_features)
  File "/home/kai/.virtualenvs/nad3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py", line 477, in parse
    if self.feed(handle, consumer, do_features):
  File "/home/kai/.virtualenvs/nad3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py", line 449, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/home/kai/.virtualenvs/nad3/lib/python3.6/site-packages/Bio/GenBank/Scanner.py", line 175, in parse_features
    raise ValueError("Premature end of features table, marker '//' found")
ValueError: Premature end of features table, marker '//' found
```

### Steps to reproduce

See a reproducer above.

**Comment by peterjc** [comment]
How does #2269 look?

What are your thoughts on how the record count (``rc`` in ``LOCUS`` line) is currently treated in TSA and WGS files? See also 82a410fedccc67c4ab01eb76b0d91e6d14edd29b

**Comment by kblin** [comment]
For my use case I don't care about the record count, but I do need to generate the actual IDs of the records. I'm using a [helper class](https://github.com/kblin/ncbi-acc-download/blob/master/ncbi_acc_download/wgs.py#L43) to handle this in `ncbi-acc-download --recursive`. I'm happy to contribute this upstream if that's a feature you'd like in Biopython.

**Comment by peterjc** [comment]
You mean expand a range like this:

```
TSA         GHGH01000001-GHGH01126539
```

to the many thousands of individual entries? Might be useful as a generator/iterator style function - useful in other contexts too. Not sure immediately where best to place that... maybe ``Bio.GenBank``?

**Comment by peterjc** [comment]
Thanks for trying the pull request, that's merged now.
