### ISSUE TITLE
assertRaisesRegexp -> assertRaisesRegex

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2273]
The legacy ``unittest`` class method ``assertRaisesRegexp`` was deprecated in Python 3 in favour of ``assertRaisesRegex`` (no trailing p).

https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaisesRegex

However, Python 2.7 only has ``assertRaisesRegexp``

https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRaisesRegexp

So, **once we drop Python 2.7 support** in early 2020, we can convert all the trailing ``p`` cases.

**Comment by jimmytwright1** [comment]
Let me in

**Comment by 7291521417** [comment]
afirmarRaisesRegex # 2273

**Comment by dimucciojonathan** [comment]
Right here!

**Comment by peterjc** [comment]
I've just hidden a couple of apparently spam comments from accounts created in the last 24 hours (there was other spam/bot activity over the same time period).

@dimucciojonathan Was your comment in reply to one of those?

**Comment by dimucciojonathan** [comment]
No, I’m just someone who is looking to get into working with open source projects. Biopython seems like a great project, if you have anything that can be worked on / tested, I’m open to being pointed in the right direction!

**Comment by peterjc** [comment]
@dimucciojonathan Great. Anything with the "good first issue" tag would be worth a look. This particular issue will have to wait until early 2020 once we've done our final release with Python 2.7 support.

**Comment by dimucciojonathan** [comment]
Great, I will take a look later today. Thanks for the quick response

**Comment by joshuacooked** [comment]
Did this end up getting solved? If not I'd be more than happy to take it on?

**Comment by dimucciojonathan** [comment]
It has not been solved yet, feel free to take over!

**Comment by joshuacooked** [comment]
Sweet, I'll get to it.

**Comment by peterjc** [comment]
It can't be be solved until next year because in the short/medium term we still support Python 2.7, which does not have ``assertRaisesRegex``. Perhaps I didn't word this issue clearly enough?

**Comment by joshuacooked** [comment]
Yeah, I thought that may be the case. Im new to using Github so I thought
the commit could maybe be frozen until 2020.

Happy to fix around that date. Until then Ill look for other issues to
solve.

**Comment by peterjc** [comment]
Well, you could make a branch with the changes now - and while there could be no merge conflicts when we come to use it, the changes are it will need manual updating. I'd recommend leaving this issue for now.

**Comment by peterjc** [comment]
It is nearly 2020, and we have now dropped Python 2 support on the master branch - @joshuacooked if you would like to tackle this now, please go ahead. I appreciate it is holiday season, so no rush.

**Comment by mdehoon** [comment]
Fixed by #2574
