### ISSUE TITLE
key err in DNA_TMM1 of Bio.SeqUtils for two NN pairs

### ISSUE THREAD

**Issue by JJTimmons** [biopython/biopython#2280]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-18.6.0-x86_64-i386-64bit
1.74
```

### Expected behavior

All terminal mismatch pairs in the terminal mismatch table `DNA_TMM1` are included in nearest neighbor tm calculation

### Actual behaviour

I saw two keys with spaces in the terminal mismatch table `DNA_TMM1`: ` GG/CA` and ` CC/GC`. I don't see a trim or anything in `Bio.SeqUtils.Tm_NN` at this step, so I believe these two pairs are being missed during tm calculation and the tm's are a tad low.

`' GG/CA'`
`' CC/GC'`

and the code to calculate the tm with neighbors:

```python
    # Now for terminal mismatches
    left_tmm = tmp_cseq[:2][::-1] + '/' + tmp_seq[:2][::-1]
    if left_tmm in tmm_table:
        delta_h += tmm_table[left_tmm][d_h]
        delta_s += tmm_table[left_tmm][d_s]
        tmp_seq = tmp_seq[1:]
        tmp_cseq = tmp_cseq[1:]
    right_tmm = tmp_seq[-2:] + '/' + tmp_cseq[-2:]
    if right_tmm in tmm_table:
        delta_h += tmm_table[right_tmm][d_h]
        delta_s += tmm_table[right_tmm][d_s]
        tmp_seq = tmp_seq[:-1]
        tmp_cseq = tmp_cseq[:-1]
```

I can do a PR for this -- it's just a two character change. Please let me know.

### Steps to reproduce

```
from Bio.SeqUtils.MeltingTemp import Tm_NN
Tm_NN("AAAAAAGG", c_seq="TTTTTTCA")
```

**Comment by MarkusPiotrowski** [comment]
Thank you @jjtimmens, I'll have a look.
