### ISSUE TITLE
"make -C Doc/api/ html" exits with code 1 unless you create _static folder first

### ISSUE THREAD

**Issue by ExplodingCabbage** [biopython/biopython#2281]
In .travis-tox.ini, this command is run before `make -C Doc/api/ html`:

```
mkdir -p Doc/api/_templates Doc/api/_static Doc/api/_build
```

If I try to build the docs locally without doing this first, I get a warning at the start...

> WARNING: html_static_path entry '_static' does not exist

and ultimately the build reports a failure as a consequence:

```
build finished with problems, 1 warning.
make: *** [html] Error 1
```

This is fixed if I run the `mkdir` command before building. This seems like a minor but easily fixable source of confusion for someone trying to build the docs locally for the first time.

Some possible fixes:

- Commit `Doc/api/_static/.gitkeep` and `Doc/api/_templates/.gitkeep` to the repo; remove the line creating those folders from the `.travis-tox.ini`
- Move the `mkdir` command that creates them into the makefile instead of it being in `.travis-tox.ini`
- Change some config somewhere to remove the need for these folders to exist (the build never puts anything in them!) and then remove the line creating them from `.travis-tox.ini`

**Comment by peterjc** [comment]
Moving the ``mkdir`` in to ``Makefile`` sounds simplest - do you want to make a pull request on that?

**Comment by peterjc** [comment]
Fixed, thank you!
