### ISSUE TITLE
Motif from pfm-four-columns format doesn't work

### ISSUE THREAD

**Issue by menzel** [biopython/biopython#2284]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0]
CPython
Linux-5.2.13-arch1-1-ARCH-x86_64-with-arch
1.74

### Expected behaviour

weblogo should create a .pdf file with the logo of my given pfm

### Actual behaviour

"pfm-four-columns" is unknown to Bio.motifs.  In pfm.py line 31 it is excpected to have  underscores:

`if pfm_format == "pfm_four_columns":`

Yet in __init.py__ line 88 it is checked using minus signs:
 
`elif format in ("pfm-four-columns", "pfm-four-rows"):`

However, after I fix this locally it still doesn't work, instead of .pdf I get a html-page containing the error:

> ERROR: ('alphabet', 'Unknown sequence type.') 

### Steps to reproduce
```
from Bio import motifs

srf = motifs.read(open("motif"), "pfm-four-columns") 
srf.weblogo("test.pdf",format="pdf") 
```

Given a file named motif with something like this:

```
 0.566	0.008	0.168	0.258
 0.086	0.001	0.819	0.094
 0.001	0.169	0.001	0.829
 0.744	0.245	0.010	0.001
 0.849	0.140	0.010	0.001
 0.997	0.001	0.001	0.001
 0.001	0.507	0.001	0.491
 0.992	0.001	0.006	0.001 
```

**Comment by peterjc** [comment]
Looks like the left-over underscores are my fault, 5f9a853e7e06727631d1b31d1218f672be612634 - we must be missing a test case for this.

**Comment by peterjc** [comment]
@mdehoon the web-logo alphabet code expects ``'ACGT'``, but PFM, XMS, clusterbuster all use ``'GATC'``. Should the check be relaxed, or the order standardised?

**Comment by peterjc** [comment]
This should be fixed in the next release, thank you for reporting it.
