### ISSUE TITLE
pairwise2

### ISSUE THREAD

**Issue by Alp78** [biopython/biopython#2290]
when doing a pairwise alignment of two sequences that don't have the same length, but have big matching chunks from a long distance from the start of the long one (~400bp), pairwise2 is not picking these first, but starts matching little chunks down to the base from the start of the long sequence, stretching and splitting the short sequence so that both sequences match in length all the short bases get aligned with almost random long sequence's bases, with long unmatched parts between them, biasing the actual match. 

the expected result would be that the algorithm discovers the big matching chunks first, and starts filling the gap from there, ignoring the first 400bp before where only few bases match.

i get the expected result using this tool: https://fasta.bioch.virginia.edu/fasta_www2/index.cgi

attaching the result (**pairwise_PearsonLipman.txt**), along with the input sequences (**seq1_short.txt**, **seq2_long.txt**) and below code.

[seq2_long.txt](https://github.com/biopython/biopython/files/3666150/seq2_long.txt)
[seq1_short.txt](https://github.com/biopython/biopython/files/3666151/seq1_short.txt)
[pairwise_PearsonLipman.txt](https://github.com/biopython/biopython/files/3666152/pairwise_PearsonLipman.txt)

is there a way to tweak pairwise2's parameters so that it yields similar result and score?

```
from Bio import SeqIO
from Bio import pairwise2
from Bio.pairwise2 import format_alignment

with open('seq1_short.txt') as file:
    seq1_short = file.read()

with open('seq2_long.txt') as file:
    seq2_long = file.read()

file = open("global_alignment.txt","w")
global_alignments = pairwise2.align.globalxx(seq2_long, seq1_short)
for a in global_alignments:
    file.write(format_alignment(*a))
file.close()

file = open("local_alignment.txt","w")
local_alignments = pairwise2.align.localxx(seq2_long, seq1_short)
for a in local_alignments:
    file.write(format_alignment(*a))
file.close()
```

**Comment by MarkusPiotrowski** [comment]
@Alp78 
`globalxx` or `localxx` are not using very useful settings for your needs. Please have a look at the [api](http://biopython.org/DIST/docs/api/Bio.pairwise2-module.html). This explains how to use and set the different options of `pairwise2`.

'xx' means the following settings: match: 1, mismatch: 0, gap: 0

To make a meaningful DNA alignment you may want to use settings like: match: 5, mismatch: -4, gap-open: -10, gap-extension: -0.5.
Also, in your case, where you know that both sequences have different length and do not share homology over their full lengths, you may want to stay with a **local** alignment.

Try this:
```python
...
local_alignments = pairwise2.align.localms(seq2_long, seq1_short, 5, -4,
                                           -10, -0.5)
...
```

**Comment by Alp78** [comment]
great yes that's a lot better, thank you. i'll keep experimenting with the settings.

**Comment by mdehoon** [comment]
@alp78 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
