### ISSUE TITLE
Changing string in .gbk qualifiers introduces space after saving back to gbk

### ISSUE THREAD

**Issue by FantacticMisterFox** [biopython/biopython#2292]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)

3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

import platform; print(platform.python_implementation()); print(platform.platform())

CPython
Linux-5.2.17-200.fc30.x86_64-x86_64-with-fedora-30-Thirty

import Bio; print(Bio.__version__)

1.72
```

### Expected behaviour

I would expect that if I change the string of a qualifier in a sequence record this string is the same after saving the file to disk as a gbk file.

### Actual behaviour

Saving the string introduces white space at 52th and every (n*60+52)th position. Corresponds with line break in gbk file.

### Steps to reproduce

```
continous_string = "continous_string-------------------------------------------------------------------------"
record_dic = SeqIO.to_dict(SeqIO.parse("./ls_orchid.gbk", "genbank"))
record_dic["Z78533.1"].features[1].qualifiers["note"][0] = continous_string

SeqIO.write(record_dic.values(), "./new.gbk", "genbank")
new_record_dic = SeqIO.to_dict(SeqIO.parse("./new.gbk", "genbank"))

record_dic["Z78533.1"].features[1].qualifiers["note"][0] == continous_string
```
I used the ls_orchid.gbk file of the biopython cook book.

**Comment by peterjc** [comment]
This is unavoidable given the line wrapping design of the GenBank format. Most qualifiers (including "note") assumes free text with space separation, with default line breaking at a suitable space which is not explicitly recorded. This is usually only a problem with very long chemical names, for example when describing an enzyme. Note that some qualifiers assume no spaces, e.g. "translation".

What you are trying to do is probably not suitable for the GenBank/EMBL file format.

What are you trying to record?

**Comment by FantacticMisterFox** [comment]
Just a long ID. I mean I can remove all white spaces but as some qualifiers like the one you mentioned to not introduce white space but I assume that biopython does this internally. Anyhow if this is due to gbk than I will close the issue.

**Comment by peterjc** [comment]
Thanks. The only way to do this in GenBank format would be to break the line length limit, so there is no good workaround other than accepting line breaks will be inserted on output (and give you extra spaces on parsing).
