### ISSUE TITLE
PairwiseAligner() alignments have no attribute .aligned

### ISSUE THREAD

**Issue by jrjhealey** [biopython/biopython#2294]
### Setup

This issue is based on this BioStars thread (https://www.biostars.org/p/402141/#402156), and this twitter thread https://twitter.com/Biopython/status/1181892294485651456.

I can emulate this on my setup listed below, though I didn't originally report the problem (as per the biostars thread). I have asked the OP for their system details too.

```python
>> import sys; print(sys.version)
3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-18.7.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.73
```

### Expected behaviour

As per section 6.5.2.7 of the current online docs:

6.5.2.7 Alignment objects
The aligner.align method returns PairwiseAlignment objects, each representing one alignment between the two sequences.

```
>>> from Bio import Align
>>> aligner = Align.PairwiseAligner()
>>> seq1 = "GAACT"
>>> seq2 = "GAT"
>>> alignments = aligner.align(seq1, seq2)
>>> alignment = alignments[0]
>>> alignment
<Bio.Align.PairwiseAlignment object at 0x10204d250>
```
Each alignment stores the alignment score:
```
>>> alignment.score
3.0
```
as well as pointers to the sequences that were aligned:
```
>>> alignment.target
'GAACT'
>>> alignment.query
'GAT'
```
Print the PairwiseAlignment object to show the alignment explicitly:
```
>>> print(alignment)
GAACT
||--|
GA--T
<BLANKLINE>
```
You can also represent the alignment as a string in PSL (Pattern Space Layout, as generated by BLAT [26]) format:
```
>>> format(alignment, 'psl')
'3\t0\t0\t0\t0\t0\t1\t2\t+\tquery\t3\t0\t3\ttarget\t5\t0\t5\t2\t2,1,\t0,2,\t0,4,\n'
```
Use the aligned property to find the start and end indices of subsequences in the target and query sequence that were aligned to each other. Generally, if the alignment between target (t) and query (q) consists of N chunks, you get two tuples of length N:

(((t_start1, t_end1), (t_start2, t_end2), ..., (t_startN, t_endN)),
 ((q_start1, q_end1), (q_start2, q_end2), ..., (q_startN, q_endN)))
In the current example, ‘alignment.aligned‘ returns two tuples of length 2:
```
>>> alignment.aligned
(((0, 2), (4, 5)), ((0, 2), (2, 3)))
```
### Actual behaviour

Calling the `.aligned` object of the `alignment` yields an attribute error, an inspection of the `alignment` object shows no corresponding object:
```
>>> alignment.
alignment.path    alignment.query   alignment.score   alignment.target
```

### Steps to reproduce

Follow the docs through the sections above.

A minimal example from the biostars thread:

```python
from Bio import Align
aligner = Align.PairwiseAligner()

my_target = "ACTTGATCTTTCGT"
my_query = "CTTGATCT"

aligner.gap_score = -1
aligner.match = 1
aligner.mismatch = -1
aligner.query_end_gap_score = 0

alignments = aligner.align(my_target, my_query)
alignment = alignments[0]
print(alignment.aligned)
```

**Comment by jrjhealey** [comment]
Tagging @mdehoon as requested.

**Comment by MarkusPiotrowski** [comment]
AFAIK, `aligned()` was introduced post 1.73. Try updating to Biopython 1.74.

**Comment by jrjhealey** [comment]
BioStars OP confirmed updating to a newer version fixes, thanks!

**Comment by peterjc** [comment]
Thanks for being the relay, glad it was an easy one.
