### ISSUE TITLE
biopython - protein aromaticity estimation

### ISSUE THREAD

**Issue by rthapa26** [biopython/biopython#2313]
Hi,

I want to estimate protein aromaticity. I have a fasta file of protein sequences. I am using the following code but getting an error - (AttributeError: 'str' object has no attribute 'aromaticity'). Could you please provide any suggestion? Thanks

```python
from Bio import SeqIO 
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import sys 
from Bio.SeqUtils import ProtParamData  # Local 
from Bio.SeqUtils import IsoelectricPoint  # Local 
from Bio.Seq import Seq 
from Bio.Alphabet import IUPAC 
from Bio.Data import IUPACData 
from Bio.SeqUtils import molecular_weight 
from Bio import SeqIO
from CAI import CAI
from Bio.Seq import Seq
import os
out = open('output','a')
ss = []

for s in open('protein.fa'):
	if s.startswith('>'):continue
	ss.append(s.strip())
	print(ss)
	for i in ss: print(i.strip().aromaticity())
```

Edited by @MarkusPiotrowski for code formatting

**Comment by MarkusPiotrowski** [comment]
@rthapa26 Although you are importing many Biopython libraries, you are not using them. You open a file, read it line by line as strings and put the strings into a list. Then you go to the list and want to print each entry's aromaticity. But the entry (your `i`) is still a 'normal' Python string.

I strongly suggest investing some time in reading the [Biopython tutorial](http://biopython.org/DIST/docs/tutorial/Tutorial.html).

Here's an example of how to read a fasta file and calculate the aromaticity using Biopython:
```python
from Bio import SeqIO 
from Bio.SeqUtils.ProtParam import ProteinAnalysis

# Open fasta file and parse the content, returning SeqRecord objects
for seq_record in SeqIO.parse('protein.fa', 'fasta'):
    # Get the sequence from the sequence record and convert it into a string
    my_seq = str(seq_record.seq)

    # Make a ProteinAnalysis object:
    my_prot_analysis = ProteinAnalysis(my_seq)

    # Use method 'aromaticity()' of this object
    my_aromaticity = my_prot_analysis.aromaticity()

    print('Record: %s, aromaticity: %s' % (seq_record.id, my_aromaticity))
```

**Comment by MarkusPiotrowski** [comment]
@rthapa26 Did this solve your problem? Or do you have other questions?

**Comment by MarkusPiotrowski** [comment]
No more feedback from the OP; so closing now.
