### ISSUE TITLE
ValueError from BgzfBlocks on file created with BgzfWriter.write

### ISSUE THREAD

**Issue by MatthewRalston** [biopython/biopython#2316]
### Setup
Hi everyone,
I've read the documentation for [`Bio.bgzf`](https://biopython.org/DIST/docs/api/Bio.bgzf-module.html) and I'm sufficiently confused by a file being considered 'invalid' by `BgzfReader` when the file was produced by `BgzfWriter`.

```
3.7.4 (default, Oct 25 2019...)
[GCC 9.2.0]
Cpython
1.74
```

### Expected behaviour

I expect a new BGZF file created with the `BgzfWriter` and `write` methods to put the header and EOF bits, creating a valid BGZF file. In the example below, I try to write two blocks to a BgzfWriter handle.

### Actual behaviour

I see a ValueError from the BgzfReader class indicating that the file is malformed.

### Steps to reproduce

To create an example bgzf file, I've tried the following. The [`write`](https://github.com/biopython/biopython/blob/cfb26444d0c84fa5d0aa8f1ed897941afd02e58b/Bio/bgzf.py#L732) method internally uses `_write_block` which AFAICT adds a bgzf header. The `close` method flushes and adds the EOF marker.

```python

from Bio import bgzf

header="hello\nworld\somestuff"
text="an\nexample\nbody"

test=bgzf.BgzfWriter("helloworld.bgzf")
test.write(header)
test.write(text)
test.close() # works fine

```

But when parsing, I'm getting a `ValueError` when parsing the file. `zcat` works just fine at the command line.

```python
>infile=bgzf.BgzfReader("helloworld.bgzf")
>for values in bgzf.BgzfBlocks(infile):
>   print("Raw start %i, raw length %i; data start %i, data length %i" % values)
...
ValueError: A BGZF (e.g. a BAM file) block should start with b'\x1f\x8b\x08\x04', not 'hell'; handle.tell() now says 4
>ifile=open("helloworld.bgzf", 'rb')
>print(ifile.read(16))
b'\x1f\x8b\x08\x04\x00\x00\x00\x00\x00\xff\x06\x00BC\x02\x00'
>print(bgzf._bgzf_header)
b'\x1f\x8b\x08\x04\x00\x00\x00\x00\x00\xff\x06\x00BC\x02\x00' # exact match with the header
```

**Comment by MatthewRalston** [comment]
Upon another inspection of the codebase, it looks like the toy example I'm using to print the header and a simple block is too small to trigger the 'else' block which writes the header as well as the data. Instead, the [if statement](https://github.com/biopython/biopython/blob/cfb26444d0c84fa5d0aa8f1ed897941afd02e58b/Bio/bgzf.py#L795) is triggered, data is loaded into the buffer, and the method returns. The final flush writes the data to the file without either of the two block header.

**Comment by MatthewRalston** [comment]
Interestingly, the file `helloworld.bgzf` produces no errors when tested with the `bgzip` CLI. Moreover, decompression and recompression with `bgzip` still produces a file considered invalid by Bio.bgzf.

```bash
>bgzip -t helloworld.bgzf
>echo $?
0
>bgzip -c helloworld.bgzf > foo.bgzf
```

The `ValueError` persists when reading `foo.bgzf` as produced above.

**Comment by MatthewRalston** [comment]
Okay, the answer was quite simple:
I needed to open the bgzf with `mode='rb'`

```python
infile=bgzf.BgzfReader("helloworld.bgzf", 'rb')
for values in bgzf.BgzfBlocks(infile):
  print(...) # No ValueError
```

**Comment by peterjc** [comment]
Yes, this is what you were expected to use:

```python
>>> for values in bgzf.BgzfBlocks(open("helloworld.bgzf", "rb")):
...     print("Raw start %i, raw length %i; data start %i, data length %i" % values)
... 
Raw start 0, raw length 64; data start 0, data length 36
Raw start 64, raw length 28; data start 36, data length 0
```

The ``BgzfBlocks`` function expects a native binary handle - not a BGZF reader object as per the documentation via ``help(bgzf.BgzfBlocks)`` or online:

http://biopython.org/DIST/docs/api/Bio.bgzf-module.html#BgzfBlocks
https://biopython.org/docs/1.74/api/Bio.bgzf.html#Bio.bgzf.BgzfBlocks

Perhaps we should catch this user-error, and raise a ``TypeError`` for clarity...

**Comment by peterjc** [comment]
I think we can close this - the next release will make this easier for anyone else trying the same function. Thanks!
