### ISSUE TITLE
Biopython elink returns results for the wrong database

### ISSUE THREAD

**Issue by kenibrewer** [biopython/biopython#2322]
### Setup

I am reporting a problem with Biopython version 1.74, Python version 3.7.3, and running in a docker image based on jupyter/scipy-notebook. I also reproduced the problem in the official biopython/biopython-notebook docker image which runs Python 3.5.2. and Biopython version 1.69.dev0:

```
jovyan@cc9fb7577c50:~$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.9.184-linuxkit-x86_64-with-debian-buster-sid
>>> import Bio; print(Bio.__version__)
1.74
>>>
```

### Expected behaviour

Requesting links between from the nuccore database to assembly database should provide the correct links between the databases. 

The results for the specific example should mirror this Entrez link: 
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=nucleotide&db=assembly&id=1234394366

### Actual behaviour

Biopython instead returns self-referential links within Pubmed. 

![BiopythonEntrezError](https://user-images.githubusercontent.com/17461269/68088629-ff7f6300-fe2e-11e9-81f2-77cf9ee1c543.png)

### Steps to reproduce

```from Bio import Entrez
Entrez.email = ''
nuccore_id='1234394366'

assembly_link = Entrez.read(Entrez.elink(id=nuccore_id, db_from='nuccore', link_name='nuccore_genome', db='assembly'))
assembly_link
```

**Comment by kenibrewer** [comment]
Never mind. This error was caused by the presence of the "_"s in the db_from and "link_name" parameters. Perhaps it may be good to check the arguments and provide error messages if incorrectly spelled arguments are used.

**Comment by peterjc** [comment]
I have often wished the NCBI Entrez API had more consistent error handling. Anyway, glad you solved it.
