### ISSUE TITLE
Problems importing Bio.Align.substitution_matrices

### ISSUE THREAD

**Issue by THinnerichs** [biopython/biopython#2343]
Dear Biopython team,
I tried to use the substitution_matrices example code as described in your cookbook, but am here encountering some problems and unexpected errors.

Code as under 6.5.2.8 Examples:
```python
from Bio.Align import substitution_matrices
from Bio import Align, SeqIO
```
to execute the following
```python
aligner = Align.PairwiseAligner()
aligner.substitution_matrix = substitution_matrices.load("STR")
```

### Setup
3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]
CPython
Linux-4.19.84-1-MANJARO-x86_64-with-arch-Manjaro-Linux
1.74

### Expected behaviour
The import to actually happen.

### Actual behaviour
```
  File "similarity_measurement.py", line 240, in <module>
    test_biopython_PairwiseAligner()
  File "similarity_measurement.py", line 18, in test_biopython_PairwiseAligner
    from Bio.Align import substitution_matrices
ImportError: cannot import name 'substitution_matrices'
```

**Comment by peterjc** [comment]
You need Biopython 1.75 which added this new functionality.

**Comment by THinnerichs** [comment]
I thought I double checked on that, but I seems like I messed it up. Thanks a lot!

**Comment by eduamf** [comment]
How to find an example of a dictionary or matrix?

**Comment by THinnerichs** [comment]
Hello @eduamf 
Could you please open an new issue for your question? Also you should specify what you are looking for, I suggest.
