### ISSUE TITLE
ProteinAlphabet to ThreeLetterProtein converter

### ISSUE THREAD

**Issue by eleyine** [biopython/biopython#238]
This is a small issue but I haven't found a way to easily convert from the single-letter Protein alphabet to the three-letter alphabet and vice-versa.

It would be nice to have the possibility to specify the protein alphabet to translate to as such:

``` python
   from Bio.Seq import Seq
   from Bio.Alphabet import IUPAC, ThreeLetterProtein
   coding_dna = Seq("ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG", IUPAC.unambiguous_dna)
   protein = coding_dna.translate(alphabet=ThreeLetterProtein)
```

or define a converter function from one alphabet to the other.

**Comment by peterjc** [comment]
Cross reference #1681

**Comment by peterjc** [comment]
We're removing the ``Bio.Alphabet`` objects (see #2046), so I think this can be closed now.
