### ISSUE TITLE
Test suite regression for arm64 architecture

### ISSUE THREAD

**Issue by tillea** [biopython/biopython#2388]
Hi,
Debian has now activated Continuous Integration for arm64 (in addition to amd64).  As you can see in the [test log](https://ci.debian.net/data/autopkgtest/testing/arm64/p/python-biopython/3607200/log.gz) this leads to the following error:

    ======================================================================
    ERROR: test_three_letter_amino_acids_global (test_pairwise_aligner.TestSequencesAsLists)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/autopkgtest-lxc.ld_kz9w6/downtmp/autopkgtest_tmp/Tests/test_pairwise_aligner.py", line 1783, in test_three_letter_amino_acids_global
        score = aligner.score(seq1, seq2)
      File "/usr/lib/python2.7/dist-packages/Bio/Align/__init__.py", line 1527, in score
        return _aligners.PairwiseAligner.score(self, seqA, seqB)
    ValueError: sequence has unexpected format

    ======================================================================
    ERROR: test_three_letter_amino_acids_local (test_pairwise_aligner.TestSequencesAsLists)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/autopkgtest-lxc.ld_kz9w6/downtmp/autopkgtest_tmp/Tests/test_pairwise_aligner.py", line 1828, in test_three_letter_amino_acids_local
        score = aligner.score(seq1, seq2)
      File "/usr/lib/python2.7/dist-packages/Bio/Align/__init__.py", line 1527, in score
        return _aligners.PairwiseAligner.score(self, seqA, seqB)
    ValueError: sequence has unexpected format

    ======================================================================
    FAIL: test_aligner_string_errors (test_pairwise_aligner.TestArgumentErrors)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/autopkgtest-lxc.ld_kz9w6/downtmp/autopkgtest_tmp/Tests/test_pairwise_aligner.py", line 1859, in test_aligner_string_errors
        aligner.score("AAA", "AA&")
    AssertionError: ValueError not raised

    ----------------------------------------------------------------------
    Ran 192 tests in 365.415 seconds

    FAILED (failures = 1)
    Skipping any tests requiring internet access
    Python version: 2.7.17 (default, Oct 19 2019, 23:36:22)
    [GCC 9.2.1 20191008]
    Operating system: posix linux2

Any idea what might be wrong here?
Kind regards, Andreas.

**Comment by rikmills** [comment]
Ubuntu CI autopkgtests sees the same errors on 1.75+dfsg-1 for arm64, plus also armhf, ppc64el & s390x

**Comment by mdehoon** [comment]
Does this also happen with Python3? If the error only occurs with Python2, then there is no point in fixing it.

**Comment by mr-c** [comment]
@mdehoon Yes, the failures happen with Python3 as well

```
======================================================================
ERROR: test_three_letter_amino_acids_global (test_pairwise_aligner.TestSequencesAsLists)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Tests/test_pairwise_aligner.py", line 1783, in test_three_letter_amino_acids_global
    score = aligner.score(seq1, seq2)
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Align/__init__.py", line 1527, in score
    return _aligners.PairwiseAligner.score(self, seqA, seqB)
ValueError: sequence has unexpected format

======================================================================
ERROR: test_three_letter_amino_acids_local (test_pairwise_aligner.TestSequencesAsLists)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Tests/test_pairwise_aligner.py", line 1828, in test_three_letter_amino_acids_local
    score = aligner.score(seq1, seq2)
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Bio/Align/__init__.py", line 1527, in score
    return _aligners.PairwiseAligner.score(self, seqA, seqB)
ValueError: sequence has unexpected format

======================================================================
FAIL: test_aligner_string_errors (test_pairwise_aligner.TestArgumentErrors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-biopython-1.75+dfsg/.pybuild/cpython3_3.8/build/Tests/test_pairwise_aligner.py", line 1859, in test_aligner_string_errors
    aligner.score("AAA", "AA&")
AssertionError: ValueError not raised
```

**Comment by mdehoon** [comment]
@mr-c  Would you be able to compile and run some test code on arm64?

**Comment by mr-c** [comment]
@mdehoon Can you run a Docker container, or are you on a Debian derivative? I can send you a recipe using qemu for either situation.

**Comment by mdehoon** [comment]
@mr-c I have access to a cluster running Debian GNU/Linux 9.3 but I don't have admin rights there. Otherwise I can install docker on a Mac laptop.

**Comment by mr-c** [comment]
@mdehoon Here you go!

Make the following `Dockerfile` in an empty directory:

```
FROM arm64v8/debian:sid
RUN apt-get update && apt-get install -y \
        devscripts
WORKDIR /build
RUN dget https://deb.debian.org/debian/pool/main/p/python-biopython/python-biopython_1.75+dfsg-1.dsc
WORKDIR /build/python-biopython-1.75+dfsg
RUN apt-get dist-upgrade -y
RUN yes | mk-build-deps -i
RUN rm *.deb
RUN debian/rules binary
```

and then run
```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker build .
```

There is probably a more efficient, but complicated method, of using qemu directly in macOS, if this doesn't work.

**Comment by peterjc** [comment]
Is this likely to fail the same way on a Raspberry Pi? I have built and tests Biopython on there before (a few years ago I think), it worked but was slow (their newer hardware is much faster though - still an ARM variant).

**Comment by mr-c** [comment]
@peterjc Yeah, Raspberry Pi4 is arm64

**Comment by mdehoon** [comment]
@mr-c  Thanks! It turned out to be a simple bug caused by `char` being unsigned on arm64. Using `signed char` explicitly fixed the bug.
