### ISSUE TITLE
please add support to align two or more sequences in qblast() inside NCBIWWW.py

### ISSUE THREAD

**Issue by mzhou08** [biopython/biopython#2454]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
```
3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]
CPython
Darwin-19.0.0-x86_64-i386-64bit
1.74
```
### Expected behaviour

On the [NCBI BLAST web site](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&PROGRAM=blastp&BLAST_PROGRAMS=blastp&PAGE_TYPE=BlastSearch&BLAST_SPEC=blast2seq&DATABASE=n/a&QUERY=&SUBJECTS=),  there is a choice to align two or more sequences. 

However, this function is missing from the [NCBIWWW.py](https://github.com/biopython/biopython/blob/master/Bio/Blast/NCBIWWW.py) implementation. 

Those two sequences would be marked as "query" and "subject" sequences for blastp algorithm.

Could you please add the feature in?

**Comment by peterjc** [comment]
I'm not aware that the NCBI offer this via their API: https://ncbi.github.io/blast-cloud/dev/api.html

Unless you can find some information on how this might be done, we can't work on this request.

**Comment by mzhou08** [comment]
Thanks, @peterjc 

I have then requested a [ncbi/blast-cloud issue](https://github.com/ncbi/blast-cloud/issues/13)
