### ISSUE TITLE
Remove/refactor redundant `sys.version_info` checks

### ISSUE THREAD

**Issue by chris-rands** [biopython/biopython#2490]
As part of the upgrade to support Python 3.6+ only, many checks for `sys.version_info` are no longer required. Here is an approximate list:

```
$ grep "version_info" Bio/*.py Bio/*/*.py Bio/*/*/*.py Tests/*py 
Bio/File.py:if (sys.version_info >= (3, 7)
Bio/File.py:        or (sys.version_info == (3, 6)
Bio/File.py:        if sys.version_info[0] >= 3 and "U" in mode:
Bio/Seq.py:    if sys.version_info[0] == 3:
Bio/Seq.py:        if sys.version_info[0] == 3:
Bio/SeqRecord.py:            if sys.version_info[0] < 3:
Bio/bgzf.py:    if sys.version_info[0] >= 3:
Bio/Phylo/BaseTree.py:if sys.version_info[0] < 3:
Bio/SearchIO/__init__.py:if sys.version_info < (3, 6):
Bio/SearchIO/__init__.py:    if format == "blast-xml" and sys.version_info[0] > 2:
Bio/SeqIO/__init__.py:if sys.version_info < (3, 6):
Tests/common_BioSQL.py:        if sys.version_info[0] == 2:
Tests/test_Phylo.py:        if sys.version_info[0] < 3:
Tests/test_Phylo.py:            if sys.version_info[0] < 3:
Tests/test_SeqIO_SeqXML.py:    if not (sys.platform == "win32" and sys.version_info[0] >= 3):
Tests/test_SeqIO_index.py:    if sys.version_info[0] < 3 or format in SeqIO._BinaryFormats:
Tests/test_SeqRecord.py:    if sys.version_info[0] >= 3:
Tests/test_Seq_objs.py:if sys.version_info[0] < 3:
Tests/test_SffIO.py:        if sys.platform != "win32" and sys.version_info[0] < 3:
Tests/test_geo.py:if sys.version_info[0] >= 3:
Tests/test_pairwise_aligner.py:        if sys.version_info[0] >= 3:
```

I suggest tagging this with "Good first issue" and "Help wanted"

Note, the first case `sys.version_info >= (3, 7)` should be kept for now (although a separate discussion might be needed on whether or not it is safe to assume regular `dict`s retain insertion order from Python 3.6 onwards)

**Comment by mdehoon** [comment]
`Tests/test_pairwise_aligner.py` is being fixed in #2491 .

I would suggest to make separate pull requests for each file.

**Comment by deepaklorkhatri007** [comment]
Following files are being fixed (in #2496):
- Test/test_Phylo.py
- Test/test_SeqIO_index.py
- Test/test_SffIO.py
- Test/test_SeqRecord.py
- Test/common_BioSQL.py
- Test/test_geo.py
- Test/test_Seq_objs.py

`test_SeqIO_SeqXML.py` requires special attention @peterjc  @mdehoon

**Comment by nimne** [comment]
@chris-rands From the [python mailing list](https://mail.python.org/pipermail/python-dev/2017-December/151283.html), maintaining the insertion order of a `dict` is a language feature starting from 3.7. While it was a side-effect of a performance optimization in 3.6 (and wasn't recommended to be relied on), maintaining insertion order should be safe to assume in 3.7 and up.

**Comment by peterjc** [comment]
@nimne yes, that's what the code in question does - it falls back on ``OrderedDict`` under Python 3.6 when not using CPython or PyPy:

https://github.com/biopython/biopython/blob/biopython-176/Bio/File.py#L34

Arguably we could say since the only Python implementations of Python 3.6 in the wild are CPython and PyPy (which both use ordered dictionaries) that we don't need to worry about this and can effectively already assume ordered dicts. My expectation is that any future Python 3 implementation (e.g. an updated Jython or IronPython?) will start with ordered dictionaries.

My inclination is to leave this bit of code as it is - sooner or later we'll drop Python 3.6 anyway.

--

Happily all the other cases @chris-rands flagged are a much simpler, Python 3 or at least 3.6 onwards (which is what we now are focussed on).

**Comment by chris-rands** [comment]
@peterjc @nimne Yes, with the caveat that equality comparisons are still ordered insensitive in Python 3.7 with regular `dict`, which leads to different behaviours:

```
>>> import sys; sys.version_info[:2] 
(3, 7)
>>> from collections import OrderedDict
>>> OrderedDict([(1,1), (2,2)]) == OrderedDict([(2,2), (1,1)]) 
False
>>> dict([(1,1), (2,2)]) == dict([(2,2), (1,1)]) 
True
```

**Comment by peterjc** [comment]
That's an interesting subtle gotcha - although I don't think it would be an issue for the indexing code in ``Bio.File``.

Anyway, ``Bio/File.py`` aside, we're making steady progress:

```
$ grep "version_info" */*.py Bio/*/*.py Bio/*/*/*.py 
Bio/File.py:    sys.version_info >= (3, 7)
Bio/File.py:    or (sys.version_info == (3, 6) and platform.python_implementation() == "CPython")
Bio/File.py:        if sys.version_info[0] >= 3 and "U" in mode:
Bio/bgzf.py:    if sys.version_info[0] >= 3:
BioSQL/BioSeqDatabase.py:        if module_name == "mysql.connector" and sys.version_info[0] == 3:
Tests/test_SeqIO_SeqXML.py:    if not (sys.platform == "win32" and sys.version_info[0] >= 3):
Tests/test_SeqIO_index.py:    if sys.version_info[0] < 3 or format in SeqIO._BinaryFormats:
Bio/Phylo/BaseTree.py:if sys.version_info[0] < 3:
Bio/SearchIO/__init__.py:if sys.version_info < (3, 6):
Bio/SearchIO/__init__.py:    if format == "blast-xml" and sys.version_info[0] > 2:
Bio/SeqIO/__init__.py:if sys.version_info < (3, 6):
```

**Comment by peterjc** [comment]
I realise now that we have ordered dictionary code in _three_ places, ``Bio/File.py``, ``Bio/SearchIO/__init__.py`` and ``Bio/SeqIO/__init__.py`` - and they were not consistent. Thus in #2518 I propose we remove the checks and assume ordered dictionaries.

**Comment by peterjc** [comment]
Updated list assuming #2517 and #2518 are merged:

```
$ grep "version_info" */*.py Bio/*/*.py Bio/*/*/*.py 
Bio/File.py:        if sys.version_info[0] >= 3 and "U" in mode:
BioSQL/BioSeqDatabase.py:        if module_name == "mysql.connector" and sys.version_info[0] == 3:
Tests/test_SeqIO_SeqXML.py:    if not (sys.platform == "win32" and sys.version_info[0] >= 3):
Bio/Phylo/BaseTree.py:if sys.version_info[0] < 3:
Bio/SearchIO/__init__.py:    if format == "blast-xml" and sys.version_info[0] > 2:
```

There are four easy cases, just removing a clause from an if-statement. That would make a nice pull request (``Bio/File.py``, ``BioSQL/BioSeqDatabase.py``, ``Tests/test_SeqIO_SeqXML.py`` and ``Bio/SearchIO/__init__.py``)

For ``Bio/Phylo/BaseTree.py`` we need to remove the ``as_string`` function definition and replace all uses of it with ``str`` instead.

**Comment by deepaklorkhatri007** [comment]
> There are four easy cases, just removing a clause from an if-statement. That would make a nice pull request

I am working on these files :)
```
Bio/File.py:        if sys.version_info[0] >= 3 and "U" in mode:
BioSQL/BioSeqDatabase.py:        if module_name == "mysql.connector" and sys.version_info[0] == 3:
Tests/test_SeqIO_SeqXML.py:    if not (sys.platform == "win32" and sys.version_info[0] >= 3):
Bio/SearchIO/__init__.py:    if format == "blast-xml" and sys.version_info[0] > 2:
```

**Comment by mdehoon** [comment]
`Bio.Phylo.BaseTree` in #2526

**Comment by peterjc** [comment]
I've cherry-picked b07676d3e7597c9b2e36cd8532bf347a4c2f1a31 from #2517, so once #2526 is merged we can close this issue.

**Comment by peterjc** [comment]
Closing - thank you everyone!
