### ISSUE TITLE
ExPASy.sprot_search_ful and ExPASy.sprot_search_de do not work

### ISSUE THREAD

**Issue by miniocz** [biopython/biopython#253]
Both will return just pages stating "Please update your links/bookmarks" and eventually correct link at the end of page.
The functions use http://www.expasy.ch/cgi-bin/sprot-search-ful or http://www.expasy.ch/cgi-bin/sprot-search-de eventually, which pages do not exist anymore.

**Comment by peterjc** [comment]
I was reminded of this via #1826 and the tutorial having the (defunct) URLs http://www.expasy.org/cgi-bin/sprot-search-de and http://www.expasy.org/cgi-bin/sprot-search-ful

@bow Should we deprecate these two functions now? What state is the UniProt API wrapper?

**Comment by bow** [comment]
@peterjc Deprecating the functions seems sensible given that the upstream services are not there anymore. To be honest, I also have not touched the API for a very long time.
