### ISSUE TITLE
Replace flake8 git pre-commit hook with pre-commit

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2580]
Currently in ``CONTRIBUTING.rst`` we recommend using the flake8 pre-commit hook as follows:

```
$ flake8 --install-hook git
$ git config --bool flake8.strict true
```

There are at least two drawbacks. First, this only checks our Python code - it does not cover things like our RST files, or the sort order in the contributor listing (currently done via tox).

Also, the flake8 documentation http://flake8.pycqa.org/en/latest/user/using-hooks.html recommends moving to the pre-commit package instead:

https://pre-commit.com/

So, it would be a good idea to move all the style checks defined in ``.travis-tox.in`` (via tox) into ``.pre-commit-config.yaml`` instead:

https://github.com/biopython/biopython/blob/biopython-176/.travis-tox.ini#L117

```
commands =
    # PEP-8 and PEP-257 style checks:
    flake8
    # Now do various checks on our RST files:
    # Calling via bash to get it to expand the wildcard for us
    bash -c \'rst-lint --level warning *.rst\'
    # Check sort order (bash call work around for pipe character)
    bash -c \'grep "^- " CONTRIB.rst | LC_ALL=C sort -u -c -f\'
    # Check copyright date
    bash -c \'grep "1999-`date +'%Y'`" LICENSE.rst\'
    # Would like to tell doc8 to just check *.rst but does *.txt too:
    bash -c "doc8 --ignore-path 'Doc/examples/ec_*.txt' *.rst Doc/"
    # Check no __docformat__ lines
    bash -c "if grep --include '*.py' -rn '^__docformat__ ' Bio BioSQL Tests Scripts Doc ; then echo 'Remove __docformat__ line(s), we assume restructuredtext.'; false; fi"
    # Check DOI link style, see https://www.crossref.org/display-guidelines/
    bash -c "if grep --include '*.py' --include '*.rst' --include '*.tex' -rni 'doi:' Bio BioSQL Scripts Doc ; then echo 'Please use https://doi.org/... not the doi: or DOI: style.'; false; fi"
    bash -c "if grep --include '*.py' --include '*.rst' --include '*.tex' -rn 'dx\.doi\.org' Bio BioSQL Tests Scripts Doc ; then echo 'Please use https://doi.org/... not the dx.doi.org style.'; false; fi"
    bash -c "if grep --include '*.py' --include '*.rst' --include '*.tex' -rn 'http://doi\.org' Bio BioSQL Tests Scripts Doc ; then echo 'Please use https://doi.org/... not http://doi.org/...'; false; fi"
```

And then the tox configuration can just invoke that instead.

For anyone experienced with ``.pre-commit-config.yaml`` this shouldn't be too complicated, and would be a nice contribution to Biopython.

**Comment by JoaoRodrigues** [comment]
I was looking at pre-commit last week and ended up using it for one of my projects. I like it a lot. Wouldn't mind looking into it. Just the style checking? You can also have a black as a pre-commit hook: https://pre-commit.com/hooks.html

**Comment by peterjc** [comment]
Yes please!

The nice thing about pre-commit is it can do flake8, and black, and grep, and rst-lint, etc. I want to do all our stylistic checks this way (to avoid nasty surprises on TravisCI like aedc2450a5eca7a41dd58a78889ace3c4e2c4525).

Black can stay via flake8, or drop the flake8-black plugin and list ``black --check`` explicitly in the pre-commit configuration. Probably via flake8 is best right now since we have to ignore the black requirement on Tests/ and until #2579 is applied also Bio/

**Comment by JoaoRodrigues** [comment]
I'll try to get it working this weekend then. 

By the way, slightly off-topic, but I aggregated all my CI on Azure Pipelines since they can run all 3 OSes. Could be an interesting alternative to travis and appveyor. If you want, have a look [here](https://github.com/JoaoRodrigues/interfacea/tree/reorg), and specifically at [this file](https://github.com/JoaoRodrigues/interfacea/blob/reorg/azure-pipelines.yml). You can divide the workflow in stages that depend on each other (useful not to waste time if something fails early on) and most things are parallelized so it's quite fast. Example [from my project](https://dev.azure.com/jpglmrodrigues/interfacea-ci/_build).

**Comment by yursha** [comment]
Is this completed and can it be closed?

**Comment by JoaoRodrigues** [comment]
Not really no. Still working on it. The last few months have been quite intense with black + testing so it's been hard to have a stable base to compare pre-commit to the current workflow.

**Comment by peterjc** [comment]
With #2827 now merged, leaving this open until the CONTRIBUTING.rst file is updated.

Also https://biopython.org/wiki/GitUsage - anything else?

**Comment by peterjc** [comment]
Also how well does it work for TravisCI to call pre-commit for the style checks? It would be better to have a single configuration...

**Comment by JoaoRodrigues** [comment]
We could have TravisCI install pre-commit and just run it, like this:

```pip install pre-commit
pre-commit install
pre-commit run -a
```

**Comment by peterjc** [comment]
I'll give that a try on a branch...

**Comment by JoaoRodrigues** [comment]
This has the potential downside that it will run through ALL files. We could look into a way (maybe there is a simpler way) to just run pre-commit on the last committed changes? Without searching for anything, this would involve a little git-fu in TravisCI:

```
git pull ...  # how we get the code to test
git reset HEAD^1
git add --all
git commit -m "Trigger"
```

**Comment by peterjc** [comment]
I've opened #3214 to address a few points.

Having pre-commit including blacken docs is already a usability improvement.

We would ideally include the pre-commit equivalent ways to run the following checks currently done on TravisCI, but I am unclear how to define a completely new hook in pre-commit:

```
rst-lint --level warning *.rst
doc8 --ignore-path 'Doc/examples/ec_*.txt' 'Doc/doc.rst' *.rst Doc/
```

Plus these with grep - which I think ought to be easier:

```
grep "^- " CONTRIB.rst | LC_ALL=C sort -u -c -f
grep "1999-`date +'%Y'`" LICENSE.rst
grep --include '*.py' -rn '^__docformat__ ' Bio BioSQL Tests Scripts Doc
grep --include '*.py' --include '*.rst' --include '*.tex' -rni 'doi:' Bio BioSQL Scripts Doc
grep --include '*.py' --include '*.rst' --include '*.tex' -rn 'dx\.doi\.org' Bio BioSQL Tests Scripts Doc
grep --include '*.py' --include '*.rst' --include '*.tex' -rn 'http://doi\.org' Bio BioSQL Tests Scripts Doc
```

Extracted from the current ``.travis-tox.ini`` style rules.

**Comment by JoaoRodrigues** [comment]
See the list here: https://pre-commit.com/hooks.html. There seems to be an `rst-linter` we could use directly or adapt?

As for the greps, what exactly do they do? The first one is clear but the others not so much.

**Comment by peterjc** [comment]
I took the comments out of the grep commands, see https://github.com/biopython/biopython/blob/biopython-177/.travis-tox.ini#L122 with the explanations.

**Comment by JoaoRodrigues** [comment]
Maybe wrapping these in a small Python script and making a tiny pre-commit hook would be the best? On windows, unless you drop into WSL, there's not grep.

**Comment by peterjc** [comment]
My impression is that https://github.com/pre-commit/pygrep-hooks could be used to replicate the grep commands (and that would work on Windows). However, I've not tried yet.

It looks like doc8 can be used, see https://github.com/PyCQA/doc8/blob/master/.pre-commit-hooks.yaml

It looks like rst-lint is not, see https://github.com/twolfson/restructuredtext-lint/pull/51 - but perhaps https://github.com/Lucas-C/pre-commit-hooks-markup will be a fair substitute for this?

**Comment by peterjc** [comment]
doc8 is now listed in the official pre-commit documentation https://github.com/pre-commit/pre-commit.com/pull/380

**Comment by peterjc** [comment]
Another option for RST linting is https://github.com/myint/rstcheck which is again a docutils wrapper. Testing that now...

**Comment by peterjc** [comment]
I'm starting to find the default pre-commit output too verbose with multiple hooks. Doing a full test like this is OK, in part since it takes a while (lots of flake8 plugins):

```
$ time pre-commit run -a
Check that executables have shebangs.....................................Passed
Check JSON...............................................................Passed
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
black....................................................................Passed
flake8...................................................................Passed
blacken-docs.............................................................Passed
rstcheck.................................................................Passed
doc8.....................................................................Passed
Enforce https://doi.org/ style...........................................Passed

real	1m1.442s
user	5m6.137s
sys	0m5.981s
```

However, when only a few files have been edited:

```
$ git commit Bio/__init__.py -m "Use https for URL"
Check that executables have shebangs.................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
black....................................................................Passed
flake8...................................................................Passed
blacken-docs.............................................................Passed
rstcheck.............................................(no files to check)Skipped
doc8.................................................(no files to check)Skipped
Enforce https://doi.org/ style.......................(no files to check)Skipped
[precommit_grep 19651c4ff] Use https for URL
 1 file changed, 1 insertion(+), 1 deletion(-)
```

In this context I'd like to hide the skipped lines, and probably also the passed lines. See https://github.com/pre-commit/pre-commit/issues/823

**Comment by JoaoRodrigues** [comment]
Indeed, it'd be nice to skip the 'skipped' tests. I found the 'branding' excuse of the main developer a bit disappointing. Hopefully your patch will go through.

**Comment by peterjc** [comment]
Still https://biopython.org/wiki/GitUsage to update and a handful of trivial grep checks in ``.travis-tox.ini`` , plus this one:

``grep "^- " CONTRIB.rst | LC_ALL=C sort -u -c -f``

I don't know how easy that would be to handle in a cross platform way - probably simplest if rather than insist on adding everything to pre-commit, we leave a few things like this only on the Continuous Integration side (either in Tox as now, or directly in the TravisCI or AppVeyor configuration - whichever is easier).

Let's wait and see is the pre-commit verbosity can be improved, otherwise we may want to consolidate or prune a few things for brevity?

**Comment by JoaoRodrigues** [comment]
Honestly, I think what we've already done is a huge help. I've personally benefitted a ton from the flake8/black tests locally on each commit. So - let's wait and see!

**Comment by peterjc** [comment]
I'd gotten used to having flake8 and black locally already via the (deprecate) flake8 pre-commit hook and the flake8-black plugin. I'm pleased to have this cover the RST checks, and blacken-docs in particular is going to be very useful.

Which lead to https://github.com/biopython/biopython.github.io/pull/170 if anyone wants to review that...

**Comment by JoaoRodrigues** [comment]
Good idea - I'll have a look!

**Comment by rob-miller** [comment]
Worth mentioning in CONTRIBUTING.rst to remove any existing .git/hooks/pre-commit so that does not get migrated?  This caused me problems but may have just been a local issue due to updating pyton3.7->3.8 around the same time.

**Comment by MarkusPiotrowski** [comment]
Small issues (at least on Windows):

1. `doc8` seems to have problem with Window's line breaks:

```bash
$ git commit -am "Small rst bug"
Check that executables have shebangs.................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Debug Statements (Python)............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Mixed line ending........................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
blacken-docs.............................................................Passed
rstcheck.................................................................Passed
doc8.....................................................................Failed
- hook id: doc8
- exit code: 1

CONTRIBUTING.rst:1: D002 Trailing whitespace
CONTRIBUTING.rst:2: D002 Trailing whitespace
...
CONTRIBUTING.rst:121: D002 Trailing whitespace
CONTRIBUTING.rst:122: D002 Trailing whitespace
CONTRIBUTING.rst:1: D004 Found literal carriage return
CONTRIBUTING.rst:2: D004 Found literal carriage return
...
CONTRIBUTING.rst:121: D004 Found literal carriage return
CONTRIBUTING.rst:122: D004 Found literal carriage return
CONTRIBUTING.rst:70: D001 Line too long

Enforce https://doi.org/ style...........................................Passed
```

The error message (at least for D002) is misleading here. It was required that I converted the line ending to UNIX/OSX format to pass.

2.  I then tested a `.py` file by adding a comment to `pairwise2.py` and got:

```bash
$ git commit -am "Small line ending test"
Check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

Bio/pairwise2.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: chmod -x Bio/pairwise2.py
  If it is supposed to be executable, double-check its shebang.
```

I didn't follow the shebang discussion but I would expect that all files of the current code base stick to the tested rules? Or could this also be a Windows issue? Would be nice if someone can cross-check this on a Linux system.

**Comment by MarkusPiotrowski** [comment]
Ah, the shebang issue is already known on pre-commit: https://github.com/pre-commit/pre-commit-hooks/issues/435

It should be solved with https://github.com/pre-commit/pre-commit-hooks/pull/480 in recent versions of pre-commit

**Comment by MarkusPiotrowski** [comment]
The `doc8` issue with Windows line endings is also known but the author is not willing to fix it: https://github.com/PyCQA/doc8/issues/33

**Comment by peterjc** [comment]
Glad to hear the Windows specific executable issue has already been fixed.

There is an option with git about which new lines to use, so if your preferred editor supported it, you could in theory work with Unix style line endings on Windows - but it would be a little strange. I would want our pre-commit setup to work with Windows style new lines too.

A more optimistic reading on the doc8 newline issue is they won't do it themselves, but would be open to someone else fixing it?

**Comment by JoaoRodrigues** [comment]
@MarkusPiotrowski I feel your pain. I never had the line endings issue here, but I have this on my git config (`core.autocrlf=true`) so while I work with CRLF, when I commit it converts to LF.

As for the executables, I've been ignoring that with `--no-verify`...

**Comment by peterjc** [comment]
That's probably the git new line option I was thinking of - but I've not played with it to say how it interacts with a pre-commit hook. It sounds like it does avoid this problem with doc8?

(I am still working with macOS and Linux only, no Windows development machine setup as yet)

**Comment by JoaoRodrigues** [comment]
FWIW, you have to set it _before_ you clone for it to work right. There must be a way of 'resetting' line endings afterwards and letting git know it's OK too, but I didn't try that. It might avoid the problem with doc8 but since I never tested it I wouldn't know :)

**Comment by MarkusPiotrowski** [comment]
The line ending issue is not really a problem for me, I'm using Notepad++ for text editing (commit messages, working on `.rst` files) and changing the EOL is simple there. It's just uncomfortable and may be a problem for other Windows users. While we could think about turning off D004 (warning for carriage return), Windows line breaks also rise D002 (Trailing whitespace) and possibly D001 (Line too long) and we are not willing to turn off any of these. `git` itself is happy with any kind of EOL. It's  `doc8` that is complaining.

As for the executables, are we switching to a higher version of `pre-commit` soon? 
@JoaoRodrigues Can you switch off the shebang warning when doing a commit in git? Sorry, I haven't read much about `pre-commit`.

**Comment by JoaoRodrigues** [comment]
@MarkusPiotrowski yes, just use `git commit --no-verify -m "..."` _after_ you ran it normally and only the shebang issue remains. Otherwise you skip all pre-commit checks :)

**Comment by peterjc** [comment]
I think fixing doc8 is worth doing - anyone fancy having a go? Otherwise if there is no easy way to skip it on Windows within pre-commit, we could drop it (and call it separately on TravisCI, e.g. via the remaining Tox stub of style checks)/

**Comment by peterjc** [comment]
@MarkusPiotrowski would you be able to try https://github.com/peterjc/doc8/tree/dos_newlines ? I'd be delighted for you to turn that into a pull request. I'd do it myself if I had a Windows machine ready for testing...

**Comment by JoaoRodrigues** [comment]
@peterjc maybe a silly question but couldn't appveyor be used here for those tests?

**Comment by peterjc** [comment]
@JoaoRodrigues If you meant why don't we run the pre-commit checks on AppVeyor, we could do. However, it would slow down the AppVeyor build which historically has been longer than the TravisCI runs. If it is truly cross platform there is little reason to do style checks twice for every continuous integration test.

(Right now the AppVeyor runs are fast because I had to turn off most of the soft dependencies, see #3172)

If you mean testing the fun and games of different git new line settings, file modes, pre-commit, and doc8 with and without a patch - AppVeyor is not interactive enough.

**Comment by JoaoRodrigues** [comment]
I meant the latter - but I understand why it'd be frustrating to 'debug' stuff like this in Appveyor.

**Comment by MarkusPiotrowski** [comment]
> 
> 
> @MarkusPiotrowski would you be able to try https://github.com/peterjc/doc8/tree/dos_newlines ? I'd be delighted for you to turn that into a pull request. I'd do it myself if I had a Windows machine ready for testing...

I'll give it a try.

**Comment by MarkusPiotrowski** [comment]
With PR #3251 applied the only issue for Windows users which remains is the shebang issue. I can confirm that this issue is resolved in `pre-commit` v3.2.0.
Is there a reason to pin `pre-commit` to v2.3.0? Or can we upgrade?

**Comment by peterjc** [comment]
Please update it, this is a fix of direct relevance.

I can see the argument for typically static versions for style checks as we are otherwise at the mercy of other people’s release schedule. The downside is we must remember to periodically update all these tools, and address any new style issues identified.

**Comment by MarkusPiotrowski** [comment]
I just wondered if there is a known issue with more recent version, and we pinned it deliberately. Fine, I'll change it.

**Comment by peterjc** [comment]
I assume the initial pinned values were simple the latest at the time.

**Comment by JoaoRodrigues** [comment]
FYI: there is an `autoupdate` command for pre-commit that will update the hooks to the latest version. I've had mixed results using it because some hooks you do want pinned to a specific version. Thanks for all these windows checks @MarkusPiotrowski , I can conform they all work here as well.

**Comment by peterjc** [comment]
I think we can close this now - it seems to be working for people on Linux, macOS and Windows. Thanks everyone!
