### ISSUE TITLE
None doesn't have attribute nofuzzy_start

### ISSUE THREAD

**Issue by alexlenail** [biopython/biopython#2616]
```
3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)]
CPython
Darwin-19.2.0-x86_64-i386-64bit
1.76
```

I encountered this bug about a week ago, and fixed it by changing the following code: 

https://github.com/biopython/biopython/blob/51b37542e90362fb4cccbb76a17fe6335813e19f/Bio/SeqRecord.py#L505-L509

to

```
                    if (
                        hasattr(f.location, "nofuzzy_start")
                        and hasattr(f.location, "nofuzzy_end")
                        and start <= f.location.nofuzzy_start
                        and f.location.nofuzzy_end <= stop
                    ):
                        answer.features.append(f._shift(-start))
```

I was trying to create a new genbank SeqRecord by slicing the old SeqRecord (like `record[start:end]`).  I just moved on once I solved this bug, but I thought I should leave this here in case someone wanted to pick it up.

**Comment by peterjc** [comment]
How was the original SeqRecord created (and did the parser give you a warning about a feature having a problematic location)?

**Comment by alexlenail** [comment]
```
gb_file = next(SeqIO.parse(gb_filepath, 'genbank'))
```

```
/usr/local/lib/python3.7/site-packages/Bio/GenBank/Scanner.py:190: BiopythonParserWarning: line too short to contain a feature: '     misc_feature'
  BiopythonParserWarning,
```

Is that the culprit?

**Comment by peterjc** [comment]
Very likely - can you share that file, or at least a section including the suspect ``misc_feature``?

**Comment by alexlenail** [comment]
I'm happy just moving on :) Thanks for getting back!
