### ISSUE TITLE
Phylo.read: [ causing parsing problems

### ISSUE THREAD

**Issue by willpearse** [biopython/biopython#263]
...this isn't a huge thing, but I thought I should post it in case it's of interest.

    from Bio import Phylo
    from StringIO import StringIO
    #Works fine
    Phylo.read(StringIO("(A, (B, C), (D, E))"), "newick")
    #Error!
    Phylo.read(StringIO("[&U] (A, (B, C), (D, E))"), "newick")
    ...traceback...
    Bio.Phylo.NewickIO.NewickError: Parentheses do not match in (sub)tree: &U] (A, (B, C), (D, E)

The error seems to imply that the square brackets are parsed as though they were regular parentheses. Maybe you don't like all this '[&U]' stuff in Newick phylogenies; that's fair enough, but other packages sometimes put these into their output so it might be worth checking for. For example:

    import dendropy
    tree = dendropy.Tree.get_from_string("(A, (B, C), (D, E))", "newick")
    tree.write_to_path("test.tre", "newick")
    Phylo.read("test.tre", "newick")
    open("test.tre").readlines()
    ...shows that the file contains...
    ['[&U] (A,(B,C),(D,E));\n']

Thanks for BioPython; it's a great set of software, and makes my life significantly more pleasant :D

**Comment by etal** [comment]
The Newick parse seems to handle the leading bracketed bits safely now, treating the last bracketed word before the real Newick tree as a comment on that tree, e.g.

    cat "[&R] [&U] [&W3.5] (A,(B,C),(D,E));" > dirt.nwk
    python -c 'from Bio import Phylo; print Phylo.read("dirt.nwk", "newick")'
    Tree(rooted=False, weight=1.0)
        Clade(comment='&W3.5')
            Clade(name='A')
            Clade()
                Clade(name='B')
                Clade(name='C')
            Clade()
                Clade(name='D')
                Clade(name='E')

**Comment by willpearse** [comment]
Looks great; thanks!

Will
