### ISSUE TITLE
Overwrite line in bgzf [Enhancement request]

### ISSUE THREAD

**Issue by MatthewRalston** [biopython/biopython#2641]
Hello,
I understand enough about the bgzf format that after obtaining the block offset and line offset (pardon if my terminology is slightly off), the pointer jumps to the position on disk where the block begins, and can begin parsing the block start bits, and then jump to the line offset, where the user is requesting read or write access.

Is it possible to overwrite the current line with Bio.bgzf?

Something like

```python
filehandle.seek(offset) # here offset is the output of bgzf._make_offset or whatever the function is called
filehandle.writeline(line) # this overwrites the line in the middle of the block
```

If this is not possible, would it be possible to rewrite the block in the middle of the file.

How do I write data *in the middle* of a bgzf file without rewriting the entire file?

**Comment by peterjc** [comment]
I think this would be practically impossible - you'd have to replace a BGZF block mid file with a new block of the same size on disk.

**Comment by MatthewRalston** [comment]
Thanks Peter. My mistake. I guess I should just use regular databases for that. Closing.
