### ISSUE TITLE
Amend `Bio.SeqUtils.IsoelectricPoint`: updating source data

### ISSUE THREAD

**Issue by TianyiShi2001** [biopython/biopython#2648]
The data used in the module `Bio.SeqUtils.IsoelectricPoint` are based on articles in the 1990s — 30 years ago. Can we cite more recent literature, e.g. [Kozlowski 2016](https://doi.org/10.1186/s13062-016-0159-9) and update the data accordingly?

```
pK values and the methos are taken from::

    * Bjellqvist, B.,Hughes, G.J., Pasquali, Ch., Paquet, N., Ravier, F.,
    Sanchez, J.-Ch., Frutiger, S. & Hochstrasser, D.F.
    The focusing positions of polypeptides in immobilized pH gradients can be
    predicted from their amino acid sequences. Electrophoresis 1993, 14,
    1023-1031.

    * Bjellqvist, B., Basse, B., Olsen, E. and Celis, J.E.
    Reference points for comparisons of two-dimensional maps of proteins from
    different human cell types defined in a pH scale where isoelectric points
    correlate with polypeptide compositions. Electrophoresis 1994, 15, 529-539.
```

**Comment by MarkusPiotrowski** [comment]
Changing hardcoded values is problematic for backward compatibility. Also, although I can understand to use more recent and probably more accurate data, what do you do if next week there is another paper with even 'better' pKa datasets?
You may consider changing the module that it becomes easy to change the underlying datasets. I did a similar thing with `MeltingTemp`: I hardcoded several often used datasets from which the user can choose, but I also provided a method to update/modify one of the existing tables. The default datasets should be the 'old' one (for backward compatibility).

**Comment by TianyiShi2001** [comment]
> Changing hardcoded values is problematic for backward compatibility. Also, although I can understand to use more recent and probably more accurate data, what do you do if next week there is another paper with even 'better' pKa datasets?
> You may consider changing the module that it becomes easy to change the underlying datasets. I did a similar thing with `MeltingTemp`: I hardcoded several often used datasets from which the user can choose, but I also provided a method to update/modify one of the existing tables. The default datasets should be the 'old' one (for backward compatibility).

Sounds good. I'll create different datasets which allows for choice, and the default will be the current one (which is used by ExPASy). Probably I will also implement more choosable algorithms in the future.
