### ISSUE TITLE
No more cp27-cp27mu-manylinux1_x86_64 wheels?

### ISSUE THREAD

**Issue by abretaud** [biopython/biopython#2690]
I'm trying to install biopython 1.76 in a 2.7 virtualenv in ubuntu 18.04, but pip can't find a suitable wheel, and tries to compile biopython instead (and fails as gcc is not install).
Running pip install in verbose mode gives me (kept only version 1.76 with cp27):
```
   Skipping link: none of the wheel's tags match: cp27-cp27m-macosx_10_6_intel: https://files.pythonhosted.org/packages/d1/c4/9a1a1d79e228cd7626b2fe5c5386cdb67a63249e03737ad7dd8a5cb4d36e/biopython-1.76-cp27-cp27m-macosx_10_6_intel.whl#sha256=76a6bee1429e88eeaed4aa858bb9f656f44c79db40f726767659e4f95b2fcdb5 (from https://pypi.org/simple/biopython/)
  Skipping link: none of the wheel's tags match: cp27-cp27m-manylinux1_i686: https://files.pythonhosted.org/packages/5d/37/326dd89ad7ded90b8663732d0726e12895acf6655c96e05fd59bfa0f6656/biopython-1.76-cp27-cp27m-manylinux1_i686.whl#sha256=aee7756947bc79cbcf5a9087ae34d0318f02d85fd5e1914e7fe3dddd4df93520 (from https://pypi.org/simple/biopython/)
  Skipping link: none of the wheel's tags match: cp27-cp27m-win32: https://files.pythonhosted.org/packages/1e/ef/6d4ad6e86e529812b07b5c91f80f22f34385896b7f43894004e6decc4516/biopython-1.76-cp27-cp27m-win32.whl#sha256=45d91b68f65c1ec6f9bcae1b07bd836c2b99de612d1502a2f08d59502b77e5c6 (from https://pypi.org/simple/biopython/)
  Skipping link: none of the wheel's tags match: cp27-cp27m-win_amd64: https://files.pythonhosted.org/packages/e3/2a/c30007411423846ff08c20aa54a082972e6b830aa37229ea9f5dfe465372/biopython-1.76-cp27-cp27m-win_amd64.whl#sha256=e09d7ae93f93639d58d9314a47ccf8ee9fde4a9e36ba810cd0843b4afd1b1ddc (from https://pypi.org/simple/biopython/)
```

My python version is looking for cp27-cp27mu-manylinux1_x86_64, which is not available for 1.75 and 1.76.

For version <=1.74, there are some cp27-cp27mu-manylinux1_x86_64 wheels, that pip could use.

Is this intended?

**Comment by peterjc** [comment]
Note Biopython 1.77 onwards will not have Python 2 support _at all_. Which is not to say belatedly release the missing wheels is impossible.

It looks like you want the 64-bit Linux Python 2.7 manylinux1 wheel with the unicode width which unfortunately didn't work when building the wheels on the last two releases (this and the 32-bit one):

https://travis-ci.org/biopython/biopython-wheels/builds/627696491 (Biopython 1.76)
https://travis-ci.org/biopython/biopython-wheels/builds/608221827 (Biopython 1.75)

It appeared to be a ``Segmentation fault`` in ``test_pairwise_aligner.py``, CC @mdehoon

I can't find any email conversation after https://mailman.open-bio.org/pipermail/biopython/2019-November/016720.html noting the problem during the Biopython 1.75 release - it looks like we didn't solve it, and when doing the Biopython 1.76 release I ignored it given at the time ending Python 2 support was imminent, and no one seemed to have missed it for Biopython 1.75.

Are you interested in the pairwise alignment code? We could do a hack to disable that test, just to get the wheels (knowing they may crash on pairwise alignment on that precise platform). Would you need the wheel in PyPI, or would a separate URL be OK?

Or, given you are in a virtualenv, is using conda a practical alternative? The biopython packages via conda-forge cover all the main platforms:

https://anaconda.org/conda-forge/biopython/files?version=1.76
https://anaconda.org/conda-forge/biopython/files?version=1.76

**Comment by MarkusPiotrowski** [comment]
> Are you interested in the pairwise alignment code? We could do a hack to disable that test, just to get the wheels (knowing they may crash on pairwise alignment on that precise platform). Would you need the wheel in PyPI, or would a separate URL be OK?

This would not apply for the 'old' pairwise aligner `pairwise2`.

**Comment by peterjc** [comment]
Right - ``test_pairwise_aligner.py`` is for the 'new' pairwise aligner in ``Bio.Align`` (added in Biopython 1.72), not the 'old'  one in ``Bio.pairwise2``. I should have been clearer.

**Comment by abretaud** [comment]
Thanks for the explanation, I see the point now!
I needed it for installation in a docker image of galaxy. Switching to Python 3 is on its way for future versions of galaxy, but not yet for this one.
I think I'll just use the 1.74 version until we switch to python 3. It's better I think than distributing a slightly broken wheel that could give headaches to other people later

**Comment by peterjc** [comment]
That's pragmatic and hopefully a satisfactory solution. Sorry about that.
