### ISSUE TITLE
parsing of anisotropic B factors in MMCIFParser.py

### ISSUE THREAD

**Issue by andrei-istrate** [biopython/biopython#2713]
I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> print(sys.version)
3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-19.2.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.76
```
### Actual behaviour
In the current implementation the relation between _atom_site_anisotrop.id and _atom_site.id is not checked which means that the _atom_site_anisotrop.U values are correctly assigned only if _atom_site_anisotrop.id and _atom_site.id follow the same order and there are no missing _atom_site_anisotrop records.

An error is reported only if there are _atom_site_anisotrop records for exactly one atom:

Traceback (most recent call last):
File "/Users/andrei/PycharmProjects/3D-STRUDEL/playground/test.py", line 11, in 
structure = parser.get_structure('name', path)
File "/Users/andrei/PycharmProjects/3D-STRUDEL/venv/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 64, in get_structure
self.build_structure(structure_id)
File "/Users/andrei/PycharmProjects/3D-STRUDEL/venv/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 203, in build_structure
mapped_anisou = [float() for _ in u]
File "/Users/andrei/PycharmProjects/3D-STRUDEL/venv/lib/python3.6/site-packages/Bio/PDB/MMCIFParser.py", line 203, in 
mapped_anisou = [float() for _ in u]
ValueError: could not convert string to float: '.'

### Steps to reproduce

from Bio.PDB.MMCIFParser import MMCIFParser
parser = MMCIFParser(QUIET=True)
structure = parser.get_structure('6v9q.cif', '6v9q.cif')

**Comment by chris-rands** [comment]
Did you copy the traceback correctly? It should be `mapped_anisou = [float(_) for _ in u]`, `float()` with no arguments returns `0.0` and could not raise a `ValueError`

**Comment by svalqui** [comment]
I'll have a look at this, 2-3 days and I'll give further details.

**Comment by andrei-istrate** [comment]
> Did you copy the traceback correctly? It should be `mapped_anisou = [float(_) for _ in u]`, `float()` with no arguments returns `0.0` and could not raise a `ValueError`
> 
> Also, you have at least 2 python versions, 3.7 according to `sys.version` but calling `python3.6/site-packages/`

Sorry for the confusion. It seems that I did not run it with the latest version. As far as I can see it works fine with the latest version.
