### ISSUE TITLE
Deprecate/remove dead code detected via 'vulture'

### ISSUE THREAD

**Issue by chris-rands** [biopython/biopython#2757]
Spun out from https://github.com/biopython/biopython/pull/2717#issuecomment-589177971, [`vulture`]( https://github.com/jendrikseipp/vulture) allows the detection of putatively unused code. I guess code detected by `vulture` will require one of the following actions: removal (e.g. unused imports), deprecation (e.g. unused functions/classes), modification (e.g. detected bugs), no change (e.g. false positives). One way to remove false positives would be to add unit tests.

We could proceed module by module and start with the `--min-confidence 100` flag before moving to the less clear cases.

This is probably a substantial task since `vulture` detects 1208 cases when I ran it as follows:

```
$ vulture Bio BioSQL Tests | wc -l
    1208
$ vulture Bio BioSQL Tests | head
Bio/Affy/CelFile.py:159: unused function 'read_v4' (60% confidence)
Bio/Affy/CelFile.py:168: unused function 'read_v3' (60% confidence)
Bio/Align/AlignInfo.py:774: unused function 'get_residue' (60% confidence)
Bio/AlignIO/EmbossIO.py:23: unused class 'EmbossWriter' (60% confidence)
Bio/AlignIO/FastaIO.py:163: unused attribute '_al_start' (60% confidence)
Bio/AlignIO/FastaIO.py:164: unused attribute '_al_stop' (60% confidence)
Bio/AlignIO/FastaIO.py:189: unused attribute '_al_start' (60% confidence)
Bio/AlignIO/FastaIO.py:190: unused attribute '_al_stop' (60% confidence)
Bio/Alphabet/__init__.py:158: unused class 'SecondaryStructure' (60% confidence)
Bio/Alphabet/__init__.py:490: unused function '_verify_alphabet' (60% confidence)
```

**Comment by peterjc** [comment]
Interesting selection, the first makes sense immediately:

```
Bio/Affy/CelFile.py:159: unused function 'read_v4' (60% confidence)
Bio/Affy/CelFile.py:168: unused function 'read_v3' (60% confidence)
```

See #2533  - those are stubs which raise an error saying what to use instead.

**Comment by peterjc** [comment]
```
Bio/Align/AlignInfo.py:774: unused function 'get_residue' (60% confidence)
```

Could be a sign of poor test coverage?

```
Bio/AlignIO/EmbossIO.py:23: unused class 'EmbossWriter' (60% confidence)
```

Yes, an entire class labelled as a work in progress, and which I never came back to - and equally no one has asked about the missing functionality. Might as well remove it?

```
Bio/AlignIO/FastaIO.py:163: unused attribute '_al_start' (60% confidence)
Bio/AlignIO/FastaIO.py:164: unused attribute '_al_stop' (60% confidence)
Bio/AlignIO/FastaIO.py:189: unused attribute '_al_start' (60% confidence)
Bio/AlignIO/FastaIO.py:190: unused attribute '_al_stop' (60% confidence)
```

That pre-dated SearchIO, and provided an undocumented way to get at some of the results now available via SearchIO. That could be cleaned up... perhaps even refactored to avoid code duplication.

```
Bio/Alphabet/__init__.py:158: unused class 'SecondaryStructure' (60% confidence)
Bio/Alphabet/__init__.py:490: unused function '_verify_alphabet' (60% confidence)
```

Already on the chopping board as part of #2046

Probably vulture would be more useful of the test suite coverage was better?

**Comment by chris-rands** [comment]
Thanks Peter, yes, maybe this can be used to improve the test suite coverage in places?

Some changes will be trivial (e.g. unused import) but some will require more knowledge/judgement

Some stats by type:
```
$ vulture Bio BioSQL Tests | cut -f 3 -d ":" | cut -f 1 -d "'" | sort | uniq -c | sort -r
 459  unused function 
 292  unused attribute 
 212  unused variable 
 198  unused class 
  37  unused import 
   4  unused property 
   3  unsatisfiable 
   2  redundant if-condition (100% confidence)
   1  unreachable code after 
```

By module (top 20):
```
$ vulture Bio BioSQL Tests | cut -f 1 -d ":" | sort | uniq -c | sort -r | head -n 20
  58 Tests/pairwise2_testCases.py
  56 Tests/common_BioSQL.py
  54 Tests/test_pairwise_aligner.py
  42 Bio/Nexus/Nexus.py
  37 Bio/Entrez/Parser.py
  32 Tests/test_PAML_codeml.py
  29 Bio/PDB/mmtf/DefaultParser.py
  28 Tests/test_Crystal.py
  23 Bio/Graphics/GenomeDiagram/_CircularDrawer.py
  22 Tests/test_PAML_baseml.py
  20 Bio/Restriction/Restriction.py
  20 Bio/ExPASy/Prosite.py
  18 Tests/test_PAML_yn00.py
  17 Bio/Blast/ParseBlastTable.py
  15 Tests/test_PhyloXML.py
  15 Bio/Phylo/PhyloXML.py
  14 Bio/SeqIO/SeqXmlIO.py
  13 Bio/FSSP/__init__.py
  13 Bio/Emboss/Applications.py
  12 Bio/SubsMat/__init__.py
```

**Comment by peterjc** [comment]
My eye was drawn to these six:

```
   3  unsatisfiable 
   2  redundant if-condition (100% confidence)
   1  unreachable code after
```

Those all sound worth checking in detail.

**Comment by chris-rands** [comment]
The "redundant" are `if True:` clauses, apparently to preserve indentation. The "unsatisfiable" are `if False:`, presumably to skip the code blocks. The "unreachable" looks like a small but likely unimportant bug.

```
$ vulture Bio BioSQL Tests | grep -E "unsatisfiable|redundant if-condition|unreachable"
Bio/Nexus/Nexus.py:876: unreachable code after 'raise' (100% confidence)
Bio/Phylo/PAML/baseml.py:75: redundant if-condition (100% confidence)
Bio/Phylo/PAML/codeml.py:81: redundant if-condition (100% confidence)
Tests/test_BioSQL_sqlite3.py:33: unsatisfiable 'if' condition (100% confidence)
Tests/test_GraphicsChromosome.py:283: unsatisfiable 'if' condition (100% confidence)
Tests/test_SffIO.py:440: unsatisfiable 'if' condition (100% confidence)
```

**Comment by chris-rands** [comment]
Can these 3 code blocks be deleted or moved somewhere else? These code snippets were used to make the test files/data it seems. It might be useful to keep this code somewhere for reference I guess, but seem inappropriate to have it in `if False:` clauses in the test suite?

- https://github.com/biopython/biopython/blob/master/Tests/test_SffIO.py#L440-L544
- https://github.com/biopython/biopython/blob/master/Tests/test_BioSQL_sqlite3.py#L33-L51
- https://github.com/biopython/biopython/blob/master/Tests/test_GraphicsChromosome.py#L283-L302

**Comment by peterjc** [comment]
@chris-rands Do you have a better idea?

The current placement isn't ideal but it is clearly not being executed, and is easily seen if you want to work on the file. The other alternative I considered was using ``Roche/E3MFGYR02_random_10_reads.py`` (next to the file it would create, ``Roche/E3MFGYR02_random_10_reads.sff``), and put a big comment pointing there in ``test_SffIO.py`` instead?

**Comment by chris-rands** [comment]
I looked a bit more at the `vulture` outputs, but I don't believe there is substantial value to be added by going through these. Many cases are false positives (due to inadequate test coverage), other cases require a deep/historical knowledge of the code-base to make the right decision (and the benefit of deleting a few lines is rather minor anyway), so I'm closing this

**Comment by peterjc** [comment]
Thanks Chris - at least some code cleanup came from this work, even if less dramatic than we initially hoped.
