### ISSUE TITLE
getiterator was removed in favor of iter in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [biopython/biopython#2773]
https://github.com/biopython/biopython/blob/2b8559b7c1409cbc48d88a209f9db15c4731e53c/Bio/SeqIO/UniprotIO.py#L255

https://bugzilla.redhat.com/show_bug.cgi?id=1808737

**Comment by peterjc** [comment]
Good to know people are testing on Python 3.9 already :)

**Comment by tirkarthi** [comment]
Fedora does a mass rebuild of all it's packages with latest Python version for their releases. The report is from them.
