### ISSUE TITLE
Improve doc string for Bio.Blast.NCBIWWW.qblast

### ISSUE THREAD

**Issue by sorenwacker** [biopython/biopython#2783]
I want to make a Blast search with Bio.Blast.NCBIWWW.qblast for a protein sequence.

    from Bio.Blast.NCBIWWW import qblast
    qblast("blastp", "nt", sequence=seq)

The [help](https://biopython.org/DIST/docs/api/Bio.Blast.NCBIWWW-module.html) text is not very informative. It says you can for example use 'nt', but does not include a list of valid values or references to a list of such. I am specifically looking for a protein database. 'nt' stands for nucleotide.

It would be nice to have this information in the docstring or a reference to this information.

    Bio.__version__
    > '1.76'

**Comment by peterjc** [comment]
You need "nr" for the protein non-redundant database, which is listed already (did you make a typo or are you looking somewhere else), and "nt" for the nucleotide one. Those are the big two, and the NCBI documentation linked to has far more details.

Would you like to submit a pull request updating the docstring? In many ways fresh eyes of a new-comer are better for this kind of improvement, you can probably see missing assumptions which I can't anymore.

The docstring is here (line number 82 as of now):

https://github.com/biopython/biopython/blob/master/Bio/Blast/NCBIWWW.py#L82

It was line 49 in the Biopython 1.76 release:

https://github.com/biopython/biopython/blob/biopython-176/Bio/Blast/NCBIWWW.py#L49

You can edit this file within GitHub (in your browser) which will guide you though to making a pull request.

**Comment by peterjc** [comment]
See also the blast chapter of the tutorial, which is also quite brief on this function:

http://biopython.org/DIST/docs/tutorial/Tutorial.html
http://biopython.org/DIST/docs/tutorial/Tutorial.pdf

The source for that is here:

https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_blast.tex

**Comment by soerendip** [comment]
I think it would be better to provide a list with the valid parameters right in the docstring or list valid parameters in an error code in case the user provides something invalid. Then the user does not have to look for the tutorial etc.

**Comment by MarkusPiotrowski** [comment]
@soerendip You cannot anticipate and prevent any possible wrong input. We are not doing this deliberately. Also, it is fair to suspect that a user of some tool/service (like blast) has some basic knowledge about this tool/service. And it seems also fair to expect that a user of Biopython will take a look in our tutorial, which e.g. has an own chapter about using Blast.

**Comment by MarkusPiotrowski** [comment]
Besides the topic of documentation, it seems that the `qblast` method may be improved, because the NCBI server displays an error message (and returns an xml with no hits), when the database is not known (e.g. 'nt' for blastp). But the error message goes unrecognized by `qblast` (it only checks for error messages after sending the `put` command). I' ll have a look if we can catch this and throw a `ValueError`.

**Comment by peterjc** [comment]
Listing all valid parameters is a moving target with online API wrappers like this - the NCBI can and have added database for example. To me it more reasonable to list the main ones, and point to the official documentation.

**Comment by sorenwacker** [comment]
Closing this now. Feel free to reopen.
