### ISSUE TITLE
Coronavirus themed Biopython tutorial notebook?

### ISSUE THREAD

**Issue by chris-rands** [biopython/biopython#2808]
I’ve noticed there can be a barrier to entry for starting using Biopython. The official tutorial is excellent documentation, but too exhaustive for new users. [Peter’s Biopython workshop](https://github.com/peterjc/biopython_workshop) is a great resource (and could feature more prominently on the Biopython github), but I also wanted something more biological and in a Jupter notebook.

Given the times, with people working remotely, I was motivated to finally create a draft notebook tutorial, using a genome sequence from SARS-CoV-2 as a topical theme. The idea is to use several parts of Biopython to demonstrate the broad functionality, while keeping it lightweight, and biologically informative. In this case, there is an “unknown sequence”, which the tutorial reveals derives from SARS-CoV-2 and shows how to extract some simple metadata and perform rather basic analyses. I'm sure it could be expanded quite a bit if people like the idea.

I hope that no-one feels this is an insensitive choice on my part, given the pandemic is ongoing.

Currently, I’m storing this as a gist:
EDIT: the gist links have now been deleted, see instead, the [github repo](https://github.com/chris-rands/biopython-coronavirus)

I would very much like any feedback on the concept and tutorial content and any suggestions to improve it?

Also, is there an interest to integrate this into Biopython or not? If not, no worries, I will put it in a separate repo. At some point, I planned to give a Biopython workshop at my university, so it might be useful for this

**Comment by peterjc** [comment]
Sounds good to me - at very least add a link https://biopython.org/wiki/Documentation ?

I recall @tiagoantao did a lot of work with Jupyter Notebooks - something I personally have only dabbled with so far.

**Comment by chris-rands** [comment]
Thanks @peterjc , I'll probably move it from gist to a new github repo then. did the notebook render correctly for you? do you like the concept/content or not?

**Comment by tiagoantao** [comment]
I probably should add a link to this in the documentation: https://github.com/tiagoantao/biopython-notebook .
What do you think @peterjc ?

**Comment by peterjc** [comment]
Yes please Tiago

**Comment by peterjc** [comment]
Just some minor comments Chris:

Typo "intupretation"

I would be inclined to drop NCBIXML in the example and focus on SearchIO for parsing the BLAST results (deliberately only introduce the more general function).

For the Entrez call, I would use your-name@example.org or similar - i.e. one of the actual domains created specifically for use in documentation.

Getting the protein sequence from the parsed Entrez data seems cryptic/magic - but the XML parser is rather. We would request the file in GenBank format, which makes this a little more accessible? That would be a good excuse to include the link https://www.ncbi.nlm.nih.gov/nucleotide/MT072688.1 and point out where the information discussed is the GenBank annotation?

Perhaps the the what's next could explicitly suggest looking at how the poly-protein is truncated based on chunks matching known mature proteins? Or is this trivial from the existing annotation?

**Comment by BioGeek** [comment]
If one of the goals is to lower the barrier to entry for people to start using BioPython, wouldn't it then make more sense to share this as a Google collab notebook like this:

https://colab.research.google.com/drive/1bJl_SCDV0DXgzQay6KtVBaAKaudpKBkk

Then people just need to execute the first cell which contains 

    !pip install biopython

and then they can start to play around with the notebook right away, without needing to install BioPython locally.

Alternatively, you can add a link to the Google colab notebook at the top of the notebook (as is often seen in for example the Tensorflow notebooks that Google provides as documentation):

```
Note: We recommend running this tutorial in a Colab notebook, with no setup required!  Just click "Run in Google Colab".

<div class="devsite-table-wrapper"><table class="tfo-notebook-buttons" align="left">
<td><a target="_blank" href="https://colab.research.google.com/drive/1bJl_SCDV0DXgzQay6KtVBaAKaudpKBkk">
<img src="https://www.tensorflow.org/images/colab_logo_32px.png">Run in Google Colab</a></td>
<td><a target="_blank" href="https://gist.github.com/chris-rands/75ae77fe0d782bc9d331a0a1b933593c">
<img width=32px src="https://www.tensorflow.org/images/GitHub-Mark-32px.png">View source on GitHub</a></td>
</table></div>


```

**Comment by chris-rands** [comment]
@peterjc Thank you for the suggestions! I have tried to incorporate them and moved the Notebook into a proper github repo:

https://github.com/chris-rands/biopython-coronavirus

When it is finalised, I will submit a PR to add a link to the Biopython documentation like you suggested 

@tiagoantao Would be happy to have a link in your biopython-notebook too, thanks!

**Comment by chris-rands** [comment]
I also like @BioGeek 's idea of providing an option to  running the Notebook directly without local installation, but I'm not familiar with these tools. Google collab looks nice, but I notice that Tiago's existing notebooks can be ran via Binder (although it crashed when I tested it). Any views on the best way of doing this?

**Comment by tiagoantao** [comment]
The link is https://github.com/tiagoantao/biopython-notebook 
Thanks

**Comment by BioGeek** [comment]
@chris-rands I had to [rename ](https://github.com/chris-rands/biopython-coronavirus/pull/1) `biopython-coronavirus-environment.yml`
in your repository to simply `environment.yml`.  That way the requirements are picked up by mybinder.org and your notebook can now be launched by clicking on the button below:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/BioGeek/biopython-coronavirus/master?filepath=biopython-coronavirus-notebook.ipynb)

I have no preference between using mybinder versus Google Colab. The main difference that I noticed is that you are maybe up and running a bit faster on Google Colab because it takes less time to just intstall BioPython via pip then spinning up the Docker image that mybinder.org created.

**Comment by chris-rands** [comment]
Thanks to help from @BioGeek the notebook now runs with both Google colab and Binder

**Comment by chris-rands** [comment]
I've created PRs to add links to the tutorial as suggested above. If there are any other suggestions on the Notebook content, I would appreciate them, otherwise I'll close this issue after the PRs are handled

**Comment by manyshapes** [comment]
Awesome you did this. I'm a BioPyfhon novice using the package for a covid-19 sequences project. This will be so helpful!

**Comment by peterjc** [comment]
Glad to hear it is being useful. Chris - was there anything else still pending, or can we close this now?

**Comment by chris-rands** [comment]
Thanks all! Closing this now- any further issues or suggestions can be raised in the new repo
https://github.com/chris-rands/biopython-coronavirus
