### ISSUE TITLE
ImportError: cannot import name '_aligners'

### ISSUE THREAD

**Issue by udavdasha** [biopython/biopython#2809]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
```
3.6.2 (default, Aug 11 2017, 16:17:11)
[GCC 5.4.0 20160609]

```python
import platform; print(platform.python_implementation()); print(platform.platform())
```
CPython
Linux-4.4.0-174-generic-x86_64-with-debian-stretch-sid
```python
import Bio; print(Bio.__version__)
```
1.76

### Expected behaviour
```python
from Bio import SeqIO
```
I try to import **SeqIO** module from **Bio** and expect it to be imported.

### Actual behaviour

While running this command I received an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Bio/SeqIO/__init__.py", line 390, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/usr/local/lib/python3.5/dist-packages/Bio/Align/__init__.py", line 24, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners'
```

While googling an error message, I found this issue: https://github.com/biopython/biopython/issues/1991 and checked if my `Bio.__file__` shows that I try to "import directly from the biopython source directory" (whatever that means) as suggested, and ran the following:
```python
Bio.__file__
```
The result was:
`'/usr/local/lib/python3.5/dist-packages/Bio/__init__.py'`

Thus, this is not the issue. It was also mentioned that this issue could be due to some installation or compilation fail, but I installed biopython with the typical **pip** command.

### Steps to reproduce
```python
from Bio import SeqIO
```
P.S. I am running into this issue on Ubuntu 16.04.6 LTS, but on my Windows 7 machine everything is perfect...

**Comment by MarkusPiotrowski** [comment]
@udavdasha Can you check if you have a compiled `_aligners` file in your `.../Bio/Align` folder. On Linux it is `_aligners.so` (? ), I guess.

**Comment by udavdasha** [comment]
Here is the content of this folder, the **.so** file is there:

```
udavdasha@UdavServer:/usr/local/lib/python3.5/dist-packages/Bio/Align$ ls -l
total 456
-rw-r--r-- 1 root staff 228502 мар 17 01:27 _aligners.c
-rwxr-xr-x 1 root staff 127176 мар 17 01:27 _aligners.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 1 root staff  31635 мар 17 01:27 AlignInfo.py
drwxr-sr-x 3 root staff   4096 мар 17 01:27 Applications
-rw-r--r-- 1 root staff  57451 мар 17 01:27 __init__.py
drwxr-sr-x 2 root staff   4096 мар 17 01:27 __pycache__
drwxr-sr-x 4 root staff   4096 мар 17 01:27 substitution_matrices
```

**Comment by mdehoon** [comment]
@udavdasha  In which directory are you when you start Python? Or does this happen from any directory?

Also, does the PYTHONPATH environment variable point to anything? You can find out by running
```
echo $PYTHONPATH
```
on the Ubuntu command prompt.

**Comment by udavdasha** [comment]
@mdehoon This happens from any directory. I tried to do it from my home directory or from, e.g., /mnt/Data.

Currently my $PYTHONPATH is empty. I tried to play with it and with the **pip** instalation folder, because previously for some reason **pip** installed all modules into the /usr/local/lib/python3.5/dist-packages, despite I had Python 3.6. Thus now I managed to get Biopython installed into /usr/local/lib/python3.6/site-packages, and this path is inside the sys.path variable:
```python
import sys; print (sys.path)
```
Result: `['', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages']`
```python
import Bio; print(Bio.__file__)
```
Result: `/usr/local/lib/python3.6/site-packages/Bio/__init__.py`

But this did not solve my problem :(

**Comment by MarkusPiotrowski** [comment]
@udavdasha 

It could also be that you have several versions of Python and Biopython installed at different locations and that you 'standard' Python is directing to an older Biopython installation?

Can you try the following:
```python
import Bio
print(Bio.__version__)
from Bio import SeqIO
```

You can also try to start your Python interpreter in your `.../python3.6/site-packages` folder (so directly sitting on top of the Bio folder) and do the same?

**Comment by udavdasha** [comment]
@ MarkusPiotrowski
Regretfully, it appears to be same issue from both folders...

This is what I do from my home folder:
```
udavdasha@UdavServer:~$ python3
Python 3.6.2 (default, Aug 11 2017, 16:17:11)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> print(Bio.__version__)
1.76
>>> from Bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 390, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/usr/local/lib/python3.6/site-packages/Bio/Align/__init__.py", line 24, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners'
```

And this is the same from `.../python3.6/site-packages`:
```
udavdasha@UdavServer:/usr/local/lib/python3.6/site-packages$ python3
Python 3.6.2 (default, Aug 11 2017, 16:17:11)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> print(Bio.__version__)
1.76
>>> from Bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 390, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/usr/local/lib/python3.6/site-packages/Bio/Align/__init__.py", line 24, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners'
```

**Comment by mdehoon** [comment]
One thing has changed: Before you got
```
...
  File "/usr/local/lib/python3.5/dist-packages/Bio/Align/__init__.py", line 24, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners'
```
Now you are getting
```
...
  File "/usr/local/lib/python3.6/site-packages/Bio/Align/__init__.py", line 24, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners'
```
So before it was trying to read from `/usr/local/lib/python3.5`; now it is trying to read from `/usr/local/lib/python3.6`.

**Comment by mdehoon** [comment]
This may be due to a problem with file permissions. I can trigger this import error if I change the file permission of the `Bio.Align` directory:

```
$ sudo chmod 111 /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/biopython-1.77.dev0-py3.6-macosx-10.6-intel.egg/Bio/Align/

$ python
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/biopython-1.77.dev0-py3.6-macosx-10.6-intel.egg/Bio/SeqIO/__init__.py", line 382, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/biopython-1.77.dev0-py3.6-macosx-10.6-intel.egg/Bio/Align/__init__.py", line 21, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners'
>>> 
```

You could try
```
ls -l /usr/local/lib/python3.6/site-packages/Bio/Align
```
to check if you can read this directory.

**Comment by udavdasha** [comment]
@mdehoon 
1) Regarding the path change from `/usr/local/lib/python3.5` to `/usr/local/lib/python3.6`: I've did this intentionally while trying to figure out where exactly is Biopython installed in my system and how is it red by python. The answer was yes, I can understand and control this, but no, this did not solve my problem.

2) Reading rights seems to be OK:
```
udavdasha@UdavServer:~$ ls -l /usr/local/lib/python3.6/site-packages/Bio/Align
total 456
-rw-r--r-- 1 root root 228502 мар 17 18:01 _aligners.c
-rwxr-xr-x 1 root root 127176 мар 17 18:01 _aligners.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root  31635 мар 17 18:01 AlignInfo.py
drwxr-xr-x 3 root root   4096 мар 17 18:01 Applications
-rw-r--r-- 1 root root  57451 мар 17 18:01 __init__.py
drwxr-xr-x 2 root root   4096 мар 17 18:01 __pycache__
drwxr-xr-x 4 root root   4096 мар 17 18:01 substitution_matrices
```

I also tried to make this folder writeable and executable for everybody, but this did not solve my problem:
```
udavdasha@UdavServer:/usr/local/lib/python3.6/site-packages/Bio$ sudo chmod a+wx -R Align
udavdasha@UdavServer:/usr/local/lib/python3.6/site-packages/Bio$ ls -l Align
total 456
-rwxrwxrwx 1 root root 228502 мар 17 18:01 _aligners.c
-rwxrwxrwx 1 root root 127176 мар 17 18:01 _aligners.cpython-35m-x86_64-linux-gnu.so
-rwxrwxrwx 1 root root  31635 мар 17 18:01 AlignInfo.py
drwxrwxrwx 3 root root   4096 мар 17 18:01 Applications
-rwxrwxrwx 1 root root  57451 мар 17 18:01 __init__.py
drwxrwxrwx 2 root root   4096 мар 17 18:01 __pycache__
drwxrwxrwx 4 root root   4096 мар 17 18:01 substitution_matrices
```

Finally, I made all Bio folder readable for everybody, but with no use:
```
sudo chmod a+r Bio -R
```

**Comment by udavdasha** [comment]
WOW, I think I got a solution! It is closely related to an answer by @MarkusPiotrowski. For some reason, the file `.../Bio/Align/_aligners.cpython-35m-x86_64-linux-gnu.so` was not OK for my Ubuntu (while also weird name `_aligners.cp38-win32.pyd` was OK for Win7).

Thus I simply made a copy of it with the name `_aligners.so`:
```
cp _aligners.cpython-35m-x86_64-linux-gnu.so _aligners.so
```
Still I do not understand why this was happening in my case, seems like an installation or reading issue. Maybe an error message could be fixed in order to lead to solve the problem in this was?

**Comment by MarkusPiotrowski** [comment]
From the 'weird' name I'm tempting to guess that this compiled C file was for Python 3.5 while you are running Python 3.6. Maybe you had an active Python 3.5 when you installed Biopython, which would also explain why the installation ends up in the python 3.5 folder originally.

**Comment by MarkusPiotrowski** [comment]
I don't think that we can put a meaningful error message for this into Biopython. Actually it's a problem on your Linux system. As you said, everything is fine on your Windows computer (which, looking at the name of the `pyd` file seems to run Python 3.8).

**Comment by udavdasha** [comment]
That is really weird, because originally when this error happened I also had python 3.6.2 (as I reported in the first post). But you seems to be correct: perhaps I had python 3.5 once, and **pip** was installed for it. This is what I see when I check its version:
```
udavdasha@UdavServer:/usr/local/bin$ pip3 -V
pip 19.0.3 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```
Maybe this is the reason why it decided to compile the `_aligners.c` for python3.5?

Despite I changed **pip** path to my current `/usr/local/lib/python3.6/site-packages/` and re-installed Biopython, **pip** remained the same and the issue was not fixed.

**Comment by mdehoon** [comment]
@udavdasha  Do you get the same problem with other C modules in Biopython? For example,
```
>>> from Bio import Cluster
>>> Cluster._cluster
<module 'Bio.Cluster._cluster' from '/home/mdehoon/lib/python3.7/site-packages/Bio/Cluster/_cluster.cpython-37m-x86_64-linux-gnu.so'>
```

**Comment by MarkusPiotrowski** [comment]
@mdehoon I guess the general problem is solved, @udavdasha installed Biopython under Python 3.5 but is running Python 3.6. Thus the compiled C files had the wrong naming scheme and were not found by the Python interpreter.

Why this happened, e.g. why his standard `pip` is still for Python 3.5, is something that we probably cannot solve. I have only litte knowledge about Linux systems, but it seems that the system is still assuming Python 3.5 as the standard Python. Maybe the one from the "superuser domain" (sorry for this completely wrong name, but you probably know what I mean, is it 'root'?).
However, clearly not a Biopython issue.

One solution may be to navigate the command line to the Python 3.6 folder which contains the `pip` executable and start it manually from there?
In cases like this, where one cannot really be sure, which Python or pip version is 'activated', one should think about a clean re-install, i.e. delete all Python versions and start from scratch.

**Comment by udavdasha** [comment]
@MarkusPiotrowski 
Yeah, now I understand it has nothing to do with Biopython, but this is something messed up in my system. I cannot figure out how to clean this mess, but it is another issue :)

@mdehoon
The same errors occur with any C libraries; I tried to import **Cluster** as you suggested, but it turned out to be dependent on **numpy**. I installed it, but upon import it had an error with a long error message, one line of which points to the original issue:
```
Importing the numpy c-extensions failed.
```
And indeed all *.so files were compiled by **pip** to fit python 3.5:
```
udavdasha@UdavServer:/usr/local/lib/python3.6/site-packages/numpy$ find -name *.so
./linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
./linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
./random/_sfc64.cpython-35m-x86_64-linux-gnu.so
./random/mtrand.cpython-35m-x86_64-linux-gnu.so
./random/_mt19937.cpython-35m-x86_64-linux-gnu.so
./random/_common.cpython-35m-x86_64-linux-gnu.so
./random/_pcg64.cpython-35m-x86_64-linux-gnu.so
./random/_bit_generator.cpython-35m-x86_64-linux-gnu.so
./random/_generator.cpython-35m-x86_64-linux-gnu.so
./random/_philox.cpython-35m-x86_64-linux-gnu.so
./random/_bounded_integers.cpython-35m-x86_64-linux-gnu.so
./fft/_pocketfft_internal.cpython-35m-x86_64-linux-gnu.so
./core/_multiarray_tests.cpython-35m-x86_64-linux-gnu.so
./core/_umath_tests.cpython-35m-x86_64-linux-gnu.so
./core/_operand_flag_tests.cpython-35m-x86_64-linux-gnu.so
./core/_rational_tests.cpython-35m-x86_64-linux-gnu.so
./core/_struct_ufunc_tests.cpython-35m-x86_64-linux-gnu.so
./core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so
./.libs/libopenblasp-r0-34a18dc3.3.7.so
```

The only idea what to do now is to switch back to Python 3.5 and forget about Python 3.6 (which, as I now see, does not have its own **pip** and cannot install one because of the **zlib** dependencies... trash!)
