### ISSUE TITLE
Add "topics" to repo

### ISSUE THREAD

**Issue by chris-rands** [biopython/biopython#2822]
In 2017 github [introduced topics](https://github.blog/2017-01-31-introducing-topics/) as a way of labelling repos, increasing visibility and search-ability. Appropriate topic tags could easily be added to this repo, e.g. bioinformatics, python, biopython, genomics etc.

**Comment by peterjc** [comment]
I missed that announcement but have added those and a couple more - let's leave this open a week or so for any more suggestions?

**Comment by chris-rands** [comment]
Thanks, good idea, could add: phylogenetics, dna, fasta etc. but I'm not sure how many topics is a good number before things start to look cluttered

**Comment by peterjc** [comment]
Yes, too many is going to look cluttered and may undermine the usefulness
