### ISSUE TITLE
print Feature Location in a tab-delimited format

### ISSUE THREAD

**Issue by YiweiZhu** [biopython/biopython#2840]
Hi!
I want to print the start and end sites of all CDS from a gbk file to further produce a BED file. However, I cannot print the Feature Location as a string with the code like print("%s"%(location)). I wonder how to print the start and end sites with other features of genes in a tab-delimited format?

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
CPython
Windows-10-10.0.18362-SP0
1.76
```

### Expected behaviour

473144 473993 -
474148 475024 +

### Actual behaviour

```
[473144:473993](-)
[474148:475024](+)
```

### Steps to reproduce

```python
for seq_record in gbk.features:
    if seq_record.type == "CDS":     
            location=seq_record.location  
            print(location)
```

**Comment by peterjc** [comment]
This should be close to what you want:

```python
for feature in gbk.features:
    if feature.type == "CDS":     
            location=feature.location  
            print("%s\t%i\t%i" % (gbk.id, location.start, location.end))
```

Both Biopython and BED use zero-based counting, so that should give you a minimal BED line:
https://genome.ucsc.edu/FAQ/FAQformat.html#format1

**Comment by peterjc** [comment]
Also, use ``location.strand`` for the strand - and if you need the CDS name, look in the dictionary ``feature.qualifiers`` dictionary, perhaps ``feature.qualifiers['product'][0]`` depending on the way your file has been annotated?

**Comment by YiweiZhu** [comment]
Many Thanks! @peterjc
