### ISSUE TITLE
SeqIO cannot parse newest swiss format

### ISSUE THREAD

**Issue by ATPs** [biopython/biopython#2855]
### Setup

I am reporting a problem with Biopython version 1.76, Python version 3.7.1, and operating
system as follows:

```python
from Bio import SeqIO
for s in SeqIO.parse('uniprot_trembl_viruses.dat','swiss'):break
```

file `uniprot_trembl_viruses.dat` is from `ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_trembl_viruses.dat.gz`

### Expected behaviour

the file can be parsed

### Actual behaviour

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-14-1ef837cc9a2c> in <module>
----> 1 for s in SeqIO.parse(filename,'swiss'):break

~/p/anaconda3/lib/python3.7/site-packages/Bio/SeqIO/SwissIO.py in SwissIterator(handle)
     90         swiss_records = SwissProt.parse(handle)
     91
---> 92         for swiss_record in swiss_records:
     93             # Convert the SwissProt record to a SeqRecord
     94             seq = Seq.Seq(swiss_record.sequence, Alphabet.generic_protein)

~/p/anaconda3/lib/python3.7/site-packages/Bio/SwissProt/__init__.py in parse(handle)
    138     """
    139     while True:
--> 140         record = _read(handle)
    141         if not record:
    142             return

~/p/anaconda3/lib/python3.7/site-packages/Bio/SwissProt/__init__.py in _read(handle)
    253             _read_kw(record, value)
    254         elif key == "FT":
--> 255             _read_ft(record, line)
    256         elif key == "SQ":
    257             cols = value.split()

~/p/anaconda3/lib/python3.7/site-packages/Bio/SwissProt/__init__.py in _read_ft(record, line)
    592         description = line[29:70].rstrip()
    593     if not name:  # is continuation of last one
--> 594         assert not from_res and not to_res, line
    595         name, from_res, to_res, old_description, old_ft_id = record.features[-1]
    596         del record.features[-1]

AssertionError:                 /note="Removed; by host"

----------
it is because that the current `.dat` file changed how the 'FT' lines. Previously it is like
```
FT   TRANSIT       1     73       MITOCHONDRION.
FT   CHAIN        74    282       COMPLEMENT COMPONENT 1, Q SUBCOMPONENT
FT                                BINDING PROTEIN.
```

currently
```
FT   INIT_MET        1
FT                   /note="Removed; by host"
FT                   /evidence="ECO:0000256|HAMAP-Rule:MF_04075"
FT   CHAIN           2..400
FT                   /note="Large envelope protein"
FT                   /evidence="ECO:0000256|HAMAP-Rule:MF_04075"
FT                   /id="PRO_5023162156"
FT   TOPO_DOM        2..253
FT                   /note="Intravirion; in internal conformation"
FT                   /evidence="ECO:0000256|HAMAP-Rule:MF_04075"

```

**Comment by peterjc** [comment]
And the CC lines too, see #2417 :(

**Comment by peterjc** [comment]
Can you retest with the latest code from GitHub? It looks like it may have been fixed, but we forgot to close #2417.

**Comment by ATPs** [comment]
thanks.

**Comment by ATPs** [comment]
I just checked with the latest code from GitHub. Now it is working. Thank you again! @peterjc

**Comment by peterjc** [comment]
It was @mdehoon who fixed it, but thank you for letting us know it works now 👍
