### ISSUE TITLE
Problem in parsing pdb structures raised by Entity.py

### ISSUE THREAD

**Issue by DarioMarzella** [biopython/biopython#2892]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows: 

```
>>> import sys; print(sys.version)
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
>>> import Bio; print(Bio.__version__)
1.76

```
### Expected behaviour

Whether a residue is defined two times, add() or insert() functions in  Entity.py should raise the following exception, that should not break the code:
```
PDBConstructionException("%s defined twice" % entity_id)
```
### Actual behaviour

The Exception string is not correctly formatted, thus the following error is raised, and this blocks the running parser:
```
  File "/home/dario/anaconda3/lib/python3.7/site-packages/Bio/PDB/Entity.py", line 215, in add
    raise PDBConstructionException("%s defined twice" %entity_id)
TypeError: not all arguments converted during string formatting
```

### Steps to reproduce
1) Download the following pdb structure:

http://www.imgt.org/3Dstructure-DB/IMGT-FILE/IMGT-1T0M.pdb.gz

2) Unzip it to IMGT-1T0M.pdb

3) run:
```
from Bio.PDB import PDBParser

pdbf = 'IMGT-1T0M.pdb'
P = PDBParser(QUIET=1)
structure = P.get_structure('s', pdbf)
```

**Comment by peterjc** [comment]
#2891 should fix this problem, which was introduced accidentally in f97a7ada67b597ac557aae51fb08868348e0943b - tuples are a problem with the classic % formatting in Python.

**Comment by DarioMarzella** [comment]
> #2891 should fix this problem, which was introduced accidentally in [f97a7ad](https://github.com/biopython/biopython/commit/f97a7ada67b597ac557aae51fb08868348e0943b) - tuples are a problem with the classic % formatting in Python.

Thanks for the answer. I have communicated about this issue directly with Joao Rodrigues, and he asked me to post it here as well, even if he was already fixing the problem, which for some reason was still unnoticed.
