### ISSUE TITLE
SeqIO runs into "KeyError: 'Assembly-Data" when parsing NIH genbank files

### ISSUE THREAD

**Issue by mvhanson** [biopython/biopython#2894]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

>>> import sys
>>> print(sys.version)
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
>>> import platform
>>> print(platform.python_implementation())
CPython
>>> print(platform.platform())
Windows-10-10.0.18362-SP0
>>> print(Bio.__version__)
1.76

### Expected behaviour

I'm working with some genbank seq files downloaded from NIH and have the following code:

for seq_record in SeqIO.parse("datafile_location", "genbank"):

And while it can run through most of the seqs in the seq file (which contains multiple seqs) I get the error in the "actual behavior" block below. Any thoughts about how to fix this?

Maybe delete the offending seq? It can parse to record 92126 of 93145 and then throws the error. If you want to try it out it's gbvrl18.seq that's throwing the error. 

I have tried re-downloading the seq file, but that doesn't fix the problem. 

SeqIO is smooth as silk for hundreds of thousands of other seqs in other files. 

Thank you guys for building this btw, it's a huge contribution to mankind. Kudos. 

### Actual behaviour

> File "C:\python38\lib\site-packages\Bio\GenBank\Scanner.py", line 516,
in parse_records record = self.parse(handle, do_features) File
> "C:\python38\lib\site-packages\Bio\GenBank\Scanner.py", line 499, in
parse if self.feed(handle, consumer, do_features): File
> "C:\python38\lib\site-packages\Bio\GenBank\Scanner.py", line 466, in
feed self._feed_header_lines(consumer, self.parse_header()) File
> "C:\python38\lib\site-packages\Bio\GenBank\Scanner.py", line 1801, in
feed_header_lines previous_value_line = structured_comment_dict[ KeyError: 'Assembly-Data'

### Steps to reproduce

See above -- I'm assuming this is an error in the gbvrl18.seq seq file -- but is there a workaround for the problematic seq? Jump over it? Delete it?

**Comment by peterjc** [comment]
Sounds like  #2844 & #2859 (but for a different record), a malformed record. We this we fixed this in #2851 to give a warning and continue.

If you are comfortable installing from source, you can install the latest master - or wait a bit longer as we're trying to get Biopython 1.77 out shortly.

**Comment by mvhanson** [comment]
Seems like whatever you did in 1.77 solved the problem. 

Here is the output from the affected line (92126 of 93145 in gbvrl18.seq).

Now the program just skips over it and makes it to the end of the file. 

![genbank_capture](https://user-images.githubusercontent.com/10411681/82129120-7b6b4800-978e-11ea-865e-aa499827b1e6.PNG)

Many thanks and kudos again for all you are doing. 
> 
> 
> Sounds like #2844 & #2859 (but for a different record), a malformed record. We this we fixed this in #2851 to give a warning and continue.
> 
> If you are comfortable installing from source, you can install the latest master - or wait a bit longer as we're trying to get Biopython 1.77 out shortly.

**Comment by peterjc** [comment]
Perfect - thanks for testing and letting us know.

**Comment by sofsta** [comment]
Hello!

Will 1.77 be available in conda any time soon?

**Comment by peterjc** [comment]
Hopefully later this month (doing the BioConda release usually takes less than a day after the Biopython release itself). You can subscribe to our mailing list if you like, or the news feed https://biopython.org/wiki/News

**Comment by sofsta** [comment]
@peterjc Sounds good!
