### ISSUE TITLE
Concatenate output  of different genes is not as expected .

### ISSUE THREAD

**Issue by limin321** [biopython/biopython#2895]
### Setup
I wrote the following codes to extract genes from a genome, and then concatenate them all as +1 strand.   While Concatenate output is not correct. 

```python
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

strains = ['But001']

# create two empty lists
loc_list = []
gen_list = []

for strain in strains:
    records = SeqIO.parse(strain+'.gb', 'genbank') # parse genbank file
    for record in records:
        if "chromosome circular" in record.description: # get circular chromosome and save it for 6 housekeeping gene extraction
            cir = record
            #print(cir.description)

            # The for loop extracting 6 genes location and add to loc_list
            for feature in cir.features:
                if feature.type != 'CDS':
                    continue
                else:
                    genes = [['glnA'], ['atpD'], ['dnaK'], ['rpoB'], ['recA'],['threonine synthase']]
                    if feature.qualifiers.get('gene') in genes or feature.qualifiers['product'] in genes:
                        lo = feature.location
                        #print(lo)
                        loc_list.append(lo)
                        print(len(loc_list))
     # This for loop create 6 SeqRecord based on 6 location given by loc_list and add to gene_list.
    for item in loc_list:
        gene = cir[item.start:item.end]
        #print(gene)
        gen_list.append(gene)
        #print(len(gen_list))
        #print(type(gene))
    #print(gen_list)
    gen6 = SeqRecord("")
    for item in gen_list:
        for feature in item.features:
            if feature.type != 'CDS':
                continue
            else:
                if feature.strand == -1:
                    # print(item.seq)
                    item = item.seq.reverse_complement()
                    print(item)
                    item = item.reverse_complement()
                    print(type(item))
                else:
                    item = item
                    print(item.seq)

        gen6 = gen6 + item

    SeqIO.write(gen6, "gene6_2020.fasta", 'fasta')
    print(len(gen6.seq))
    print(type(gen6))
    print(gen6)
```
(*Please copy and run the above in your Python, and copy-and-paste the output*)
<img width="573" alt="Screen Shot 2020-05-15 at 7 23 08 PM" src="https://user-images.githubusercontent.com/42760669/82108173-83b97980-96e1-11ea-98a3-cb87443a4530.png">

### Expected behaviour
why each gene I print either start with ATG or GTG, while after I concatenate them, it starts with CTA. I checked the total length is right. Just the concatenate output is not what I expected. Can anyone please explain to me what might be the problem?

Your help are greatly appreciated.

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

**Comment by peterjc** [comment]
I am having trouble following what the code is trying to do. You make a list of locations with genes of interest, then you make a list of fragments of the parent ``SeqRecord`` - but this doesn't worry about which record the location came from. Some GenBank files contain more than one record. If your files like ``But001.gb`` only ever have one record, then it might be clearer to use this and avoid one loop:

```python
record = SeqIO.read(strain + '.gb', 'genbank') # parse genbank file
```
You might find the ``feature.extract(...)`` method easier to use than checking the strand yourself - particularly if it is a complicated location using join. Perhaps something like this (untested):

```python
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

strains = ['But001'] # extend this will more input strains
genes = [['glnA'], ['atpD'], ['dnaK'], ['rpoB'], ['recA'], ['threonine synthase']]

for strain in strains:
    six_genes = Seq()
    for record in SeqIO.parse(strain + '.gb', 'genbank') # parse genbank file
        for feature in record.features:
            if feature.type != 'CDS':
                continue
            if feature.qualifiers.get('gene') in genes or feature.qualifiers['product'] in genes:
                six_genes += feature.extract(record.seq)
    print(len(six_genes))
    print(type(six_genes))
    print(gen6)
    SeqIO.write(SeqRecord(six_genes, id=strain + "_gene6"), "gene6_2020.fasta", 'fasta')
```

Note I've built up the six gene sequences as a ``Seq`` object, and given it a meaningful identifier when at the end I wrap it into a ``SeqRecord`` object.

Potential problem with this (or your version): This may not output the concatenation of six CDS genes, depending on the annotation it could be any number. The gene order in the output will depend on the order they appear in the GenBank file, not the order in your list.

**Comment by limin321** [comment]
> I am having trouble following what the code is trying to do. You make a list of locations with genes of interest, then you make a list of fragments of the parent `SeqRecord` - but this doesn't worry about which record the location came from. Some GenBank files contain more than one record. If your files like `But001.gb` only ever have one record, then it might be clearer to use this and avoid one loop:
> 
> ```python
> record = SeqIO.read(strain + '.gb', 'genbank') # parse genbank file
> ```
> 
> You might find the `feature.extract(...)` method easier to use than checking the strand yourself - particularly if it is a complicated location using join. Perhaps something like this (untested):
> 
> ```python
> from Bio import SeqIO
> from Bio.Seq import Seq
> from Bio.SeqRecord import SeqRecord
> 
> strains = ['But001'] # extend this will more input strains
> genes = [['glnA'], ['atpD'], ['dnaK'], ['rpoB'], ['recA'], ['threonine synthase']]
> 
> for strain in strains:
>     six_genes = Seq()
>     for record in SeqIO.parse(strain + '.gb', 'genbank') # parse genbank file
>         for feature in record.features:
>             if feature.type != 'CDS':
>                 continue
>             if feature.qualifiers.get('gene') in genes or feature.qualifiers['product'] in genes:
>                 six_genes += feature.extract(record.seq)
>     print(len(six_genes))
>     print(type(six_genes))
>     print(gen6)
>     SeqIO.write(SeqRecord(six_genes, id=strain + "_gene6"), "gene6_2020.fasta", 'fasta')
> ```
> 
> Note I've built up the six gene sequences as a `Seq` object, and given it a meaningful identifier when at the end I wrap it into a `SeqRecord` object.
> 
> Potential problem with this (or your version): This may not output the concatenation of six CDS genes, depending on the annotation it could be any number. The gene order in the output will depend on the order they appear in the GenBank file, not the order in your list.

Thank you so much. You made the codes much cleaner.  I didn't know the feature.extract() method.  And you are right, all my genomes have more than one SeqRecord, so I use the first if statement ``` if "chromosome circular" in record.description: 
            cir = record``` to pick the SeqRecord I want since I already know all genes are on the same seqrecord, and save it as cir, here it is.
```
 strains = ['But001']
genes = [['glnA'], ['atpD'], ['dnaK'], ['rpoB'], ['recA'],['threonine synthase']]
# create two empty lists

six_genes = Seq("")

for strain in strains:
    records = SeqIO.parse(strain+'.gb', 'genbank') # parse genbank file
    for record in records:
        if "chromosome circular" in record.description: # get circular chromosome and save it for 6 housekeeping gene extraction
            cir = record
            #print(cir.description)

            # The for loop extracting 6 genes location and add to loc_list
            for feature in cir.features:
                if feature.type != 'CDS':
                    continue
                else:
                    if feature.qualifiers.get('gene') in genes or feature.qualifiers['product'] in genes:
                        print(feature.extract(record.seq))
                        six_genes += feature.extract(record.seq)
    print(len(six_genes))
    print(type(six_genes))
    print(six_genes)
    SeqIO.write(SeqRecord(six_genes, id=strain + "_gene6"), "gene6_2.fasta", 'fasta')
```
This works perfect.  I still have questions:
does feature.extract() method by default extract DNA sequence as positive (+ strand), because when I print it out , they all start with either ATG or GTG, which are exactly what I want. Here is the output:

<img width="441" alt="Screen Shot 2020-05-16 at 9 59 46 AM" src="https://user-images.githubusercontent.com/42760669/82125625-f9fac200-975b-11ea-8883-1a802763865a.png">

However, when concatenate them, you see the last sequence printed out starting with GTG, I know only ["threonine synthase"] starts with GTG,  which means still six_genes are not concatenated in the order of ```genes = [['glnA'], ['atpD'], ['dnaK'], ['rpoB'], ['recA'],['threonine synthase']]```. This will be an issue, as you said the gene order in different genbank files will be different.

One reason of my old version is if I save each gene as SeqRecord, and put them in one list, then I can use .sort() method of list. This way I can make sure they all concatenate in the same gene order, while I still need to make sure all genes sequence are positive(+1) before doing that. Eventually I will run into the original problem again, don't know how to concatenate it.  Do you have any better suggestions?

Thanks a lot.
Best,

**Comment by peterjc** [comment]
Your example shows six genes, the first starting GTG then 5 starting ATG - and you concatenated them in that order so the combined sequence starts GTG.

I am guessing you want to do a multi-gene phylogeny, making an alignment combining all the glnA sequences, then the atpD, etc. i.e. The order must be the same for each strain.

I would turn this round, and rather than looping over all the features in each genome, loop over the 6 target genes and find them one by one:

```python
strains = ['But001']
genes = ['glnA', 'atpD', 'dnaK', 'rpoB', 'recA', 'threonine synthase'

for strain in strains:
    six_genes = Seq("")
    records = SeqIO.parse(strain+'.gb', 'genbank') # parse genbank file
    for record in records:
        if "chromosome circular" not in record.description:
            continue
        for gene_name in genes:
            for feature in cir.features:
                if feature.type != 'CDS':
                    continue
                if gene_name in feature.qualifiers.get('gene') or gene_name in feature.qualifiers['product']:
                    print(gene_name, feature.extract(record.seq))
                    six_genes += feature.extract(record.seq)
    print(len(six_genes))
    print(type(six_genes))
    print(six_genes)
    SeqIO.write(SeqRecord(six_genes, id=strain + "_6genes"), "six_genes.fasta", 'fasta')
```

Note you might want to consider making six individual alignments (one for each gene), and then concatenating the alignments (see "Manipulating Alignments" in the tutorial).

**Comment by peterjc** [comment]
P.S. You need to reset the ``six_genes`` variable inside the strain loop - otherwise the second strain's sequence will have twelve genes (6 from the first strain, 6 from the second), and so on.

**Comment by limin321** [comment]
> P.S. You need to reset the `six_genes` variable inside the strain loop - otherwise the second strain's sequence will have twelve genes (6 from the first strain, 6 from the second), and so on.
> 
> P.P.S. Do you want one multi-sequence FASTA file at the end, or one file per strain?

Your idea is amazing, opening my mind a lot. I didn't know there are so many possibilities to solve this issue.

Yes, I want one multi-sequence FASTA.  The only way I know how to do it is to use  cat  command to combine all files together.  You have better solution using python??

Your solution will make me love python, though I am just a beginner.

**Comment by peterjc** [comment]
Given these are relatively small datasets, simple is best - make a list of all six ``SeqRecord`` objects, and write them out at once to a single FASTA file. Something like this:

```python
records_to_save = []
for ...:
    # details omitted
    records_to_save.append(SeqRecord(...))
SeqIO.write(records_to_save, "all_in_one.fasta", "fasta")
```

There are other ways of solving this, including opening an output handle and writing out one record at a time.

**Comment by limin321** [comment]
> Given these are relatively small datasets, simple is best - make a list of all six `SeqRecord` objects, and write them out at once to a single FASTA file. Something like this:
> 
> ```python
> records_to_save = []
> for ...:
>     # details omitted
>     records_to_save.append(SeqRecord(...))
> SeqIO.write(records_to_save, "all_in_one.fasta", "fasta")
> ```
> 
> There are other ways of solving this, including opening an output handle and writing out one record at a time.

wow. I didn't know you can write a list to a file. I learned in python class that write() method is used to write strings to a file. However, here you the elements of records_to_save list is SeqRecord. I had never thought about that you can write a list with elements not strings into a python. Is this a specific biopython thing? or also apply to normal python write() method. 
Thank you so much.  Great appreciation from my heart.
Best,

**Comment by peterjc** [comment]
You've learnt about the Python file object's ``.write(...)`` method which takes strings.

Here we are using the ``write(...)`` function defined in ``Bio.SeqIO`` which takes lists of ``SeqRecord`` objects (or a single ``SeqRecord`` object), a filename or output file object, and a sequence format name like ``"fasta"`` or ``"genbank"`` (as a string).

We give an overview here https://biopython.org/wiki/SeqIO but I really would recommend working though the chapter in the Biopython Tutorial http://biopython.org/DIST/docs/tutorial/Tutorial.html

**Comment by limin321** [comment]
> You've learnt about the Python file object's `.write(...)` method which takes strings.
> 
> Here we are using the `write(...)` function defined in `Bio.SeqIO` which takes lists of `SeqRecord` objects (or a single `SeqRecord` object), a filename or output file object, and a sequence format name like `"fasta"` or `"genbank"` (as a string).
> 
> We give an overview here https://biopython.org/wiki/SeqIO but I really would recommend working though the chapter in the Biopython Tutorial http://biopython.org/DIST/docs/tutorial/Tutorial.html

Thank you so much.  I will definitely go back to read Biopython SeqIO  tutorial again.  I have a followed up question, the previous codes can be used to extract genes whose gene name or product name are known.  In reality, there are many incomplete genomes whose assembly is scaffold or contig level.  When I download these genome, there is no good annotation.  To extract genes from these genome, 
the way I did is using the known genes DNA sequence to blast against incomplete genome fasta using blastn command in terminal, then the output will tell me if those six genes are there and their location. And I have to extract them by manually tell biopython the location to extract my 6 target genes.  Do you have any better suggestion to extract genes  from incomplete genomes?

Best,

**Comment by peterjc** [comment]
You might want to try automated (re)annotation of the draft genomes?

You might also want to use Biopython to parse the BLASTN output (see ``Bio.SearchIO``, perhaps use the XML or tabular output), and programmatically pull out the matching regions of interest. You could use use the start/end coordinates of the match to pull out the match, but BLAST+ can give you the matched sequence as one of the fields in the tabular output.

If you are dealing with a very small number of genomes, with only six genes each, in your position I would want to review all of the output manually. However, if you want to look at hundreds of genomes, you will need to automate. Either way, beware of pulling in weak matches which are irrelevant false positives, or partial genes at the end of a contig etc.

I would hope you have a bioinformatics supervisor/advisor/mentor you can talk to - someone who knows about the genomes, the state of their annotation (which are the "gold standards" in each genus), and can look at your code with you, etc. If not, it would be worth trying to at least find a local Python programmer you can talk to - this is especially valuable as a novice. I appreciate given the current pandemic this is going to be much harder that it would be on a university campus or similar. Look out for a Software Carpentry Workshop maybe (covering Python, git and the command line) - some will be online so there could be one in your timezone?

**Comment by limin321** [comment]
Thank you so much for those advice. I want to learn bioinformatics
that's why I choose bacterial genomics as my project. Unfortunately, I am
not in bioinformatics lab and no one works in genomics in my lab, but I am
taking python courses this quarter, at the same time, I am reading
biopython tutorial. That's how I made progress little by little. Really it
is very struggling to learn from zero.  That's why I have to post questions
on github asking for help. I also learned a little bit R and command line,
which also helped.  Now I am starting to question my choice, as I learned
more, I noticed labs recruiting bioinformatics people will ask to have
computer science background, which I don't think I could get one at this
point. But I have no choice, I need this project for graduation and I just
learned things slowly.

NCBI by default use PGAP for annotation, I also submit my genomes to NCBI
for annotation, because I couldn't install PGAP locally. Though I tried
prokka, while the annotation results are a little different from PGAP,
that's why I am thinking using blastn to search their location.
I basically have to learn to teach myself everything, Really appreciate
your suggestion. That's very helpful, I do need advice from expert like you.

Best,

**Comment by limin321** [comment]
> I am having trouble following what the code is trying to do. You make a list of locations with genes of interest, then you make a list of fragments of the parent `SeqRecord` - but this doesn't worry about which record the location came from. Some GenBank files contain more than one record. If your files like `But001.gb` only ever have one record, then it might be clearer to use this and avoid one loop:
> 
> ```python
> record = SeqIO.read(strain + '.gb', 'genbank') # parse genbank file
> ```
> 
> You might find the `feature.extract(...)` method easier to use than checking the strand yourself - particularly if it is a complicated location using join. Perhaps something like this (untested):
> 
> ```python
> from Bio import SeqIO
> from Bio.Seq import Seq
> from Bio.SeqRecord import SeqRecord
> 
> strains = ['But001'] # extend this will more input strains
> genes = [['glnA'], ['atpD'], ['dnaK'], ['rpoB'], ['recA'], ['threonine synthase']]
> 
> for strain in strains:
>     six_genes = Seq()
>     for record in SeqIO.parse(strain + '.gb', 'genbank') # parse genbank file
>         for feature in record.features:
>             if feature.type != 'CDS':
>                 continue
>             if feature.qualifiers.get('gene') in genes or feature.qualifiers['product'] in genes:
>                 six_genes += feature.extract(record.seq)
>     print(len(six_genes))
>     print(type(six_genes))
>     print(gen6)
>     SeqIO.write(SeqRecord(six_genes, id=strain + "_gene6"), "gene6_2020.fasta", 'fasta')
> ```
> 
> Note I've built up the six gene sequences as a `Seq` object, and given it a meaningful identifier when at the end I wrap it into a `SeqRecord` object.
> 
> Potential problem with this (or your version): This may not output the concatenation of six CDS genes, depending on the annotation it could be any number. The gene order in the output will depend on the order they appear in the GenBank file, not the order in your list.

Good morning, 
when I went back take a look at my original codes again. The following part actually works,  concatenating different genes by adding SeqRecords sequentially.  
```
gen6 = SeqRecord(Seq(""))
    for item in gen_list:
        for feature in item.features:
            if feature.type != 'CDS':
                continue
            else:
                if feature.strand == -1:
                    # print(item.seq)
                    item = item.seq.reverse_complement()
                    print(item)
                    item = item.reverse_complement()
                    print(type(item))
                else:
                    item = item
                    print(item.seq)

        gen6 = gen6 + item
```
The reason it didn't work because in the second if statement, I did reverse_complement() twice, which I originally tried to test if I could do reverse_complement() on both Seq() and SeqRecord() objects, and then I forgot to comment one.   Just want to share this with you.  Thanks a lot.

Have a good day.

**Comment by limin321** [comment]
> Your example shows six genes, the first starting GTG then 5 starting ATG - and you concatenated them in that order so the combined sequence starts GTG.
> 
> I am guessing you want to do a multi-gene phylogeny, making an alignment combining all the glnA sequences, then the atpD, etc. i.e. The order must be the same for each strain.
> 
> I would turn this round, and rather than looping over all the features in each genome, loop over the 6 target genes and find them one by one:
> 
> ```python
> strains = ['But001']
> genes = ['glnA', 'atpD', 'dnaK', 'rpoB', 'recA', 'threonine synthase'
> 
> for strain in strains:
>     six_genes = Seq("")
>     records = SeqIO.parse(strain+'.gb', 'genbank') # parse genbank file
>     for record in records:
>         if "chromosome circular" not in record.description:
>             continue
>         for gene_name in genes:
>             for feature in cir.features:
>                 if feature.type != 'CDS':
>                     continue
>                 if gene_name in feature.qualifiers.get('gene') or gene_name in feature.qualifiers['product']:
>                     print(gene_name, feature.extract(record.seq))
>                     six_genes += feature.extract(record.seq)
>     print(len(six_genes))
>     print(type(six_genes))
>     print(six_genes)
>     SeqIO.write(SeqRecord(six_genes, id=strain + "_6genes"), strain + "_6genes.fasta", 'fasta')
> ```
> 
> Note you might want to consider making six individual alignments (one for each gene), and then concatenating the alignments (see "Manipulating Alignments" in the tutorial).

Hi I tested the above codes today, Here are the codes and error message.
```
strains = ['But001']
genes = [['glnA'], ['atpD'], ['dnaK'], ['rpoB'], ['recA'],['threonine synthase']]
#genes = ['glnA', 'atpD', 'dnaK', 'rpoB', 'recA','threonine synthase']

for strain in strains:
    # create an empty Seq(), later will be used for concatenation.
    six_genes = Seq("") # this must be under the for loop, otherwise, it will concatenate genes from all strains.
    records = SeqIO.parse(strain+'.gb', 'genbank') # parse genbank file
    for record in records:
        if "chromosome circular" not in record.description: # get circular chromosome and save it for 6 housekeeping gene extraction
            continue
            #print(cir.description)
        for gene_name in genes:
            for feature in record.features:
                if feature.type != 'CDS':
                    continue
                if gene_name in feature.qualifiers.get('gene') or gene_name in feature.qualifiers['product']:
                    print(gene_name, feature.extract(record.seq))
                    six_genes += feature.extract(record.seq)
    print(len(six_genes))
    print(type(six_genes))
    print(six_genes)
    SeqIO.write(SeqRecord(six_genes, id = strain + '_6genes'), strain + '_6genes.fasta', 'fasta')
```
Output Error msg

```
/Users/dklabuser/PycharmProjects/biopython/venv/test.py
Traceback (most recent call last):
  File "/Users/dklabuser/PycharmProjects/biopython/venv/test.py", line 24, in <module>
    if gene_name in feature.qualifiers.get('gene') or gene_name in feature.qualifiers['product']:
TypeError: argument of type 'NoneType' is not iterable

Process finished with exit code 1
```
where is the 'NoneType' argument from??

**Comment by peterjc** [comment]
Sorry. I've accidentally creating a learning opportunity. This might explain the error message:

```python
>>> "glnA" in None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'NoneType' is not iterable
```

In Python, when an object is "iterable" it means it is a container of other objects, and you can iterate over it (e.g. with a "for" loop), or check for membership ("in").

The Python dictionary's ``.get(key)`` method defaults to returning ``None`` if the key is not found. In order to cope with missing annotation, I should have said something more robust like this:

```python
...
if gene_name in feature.qualifiers.get('gene', []) or gene_name in feature.qualifiers.get('product', []):
    ...
```

**Comment by peterjc** [comment]
As to the colours, that is a GitHub markdown trick.

Blocks of code surrounded with triple back-ticks, that's the ` symbol, are shown as a code block.

If you start with triple back-ticks and a language name like python, then it gets formatted accordingly.

~~~
```python
print("Hello world")
```
~~~

rather than just:

~~~
```
print("Hello world")
```
~~~

This is documented here https://github.github.com/gfm/#info-string which says you can also use triple tilde, which is how I got the above to work.

**Comment by limin321** [comment]
> ```python
> if gene_name in feature.qualifiers.get('gene', []) or gene_name in feature.qualifiers.get('product', []):
> ```

Thank you for the learning opportunity, which is what I want. Appreciate that.
This time, the codes work perfectly.  You are such a good teacher.  I really like the way you explain things, wish you are my real teacher.
Now I can close this and soon I think I will have to post more other questions.

Have a good one.
