### ISSUE TITLE
incomplete/inaccessible SeqFeatures for SeqRecord objects of differing type (gene vs chromosome)

### ISSUE THREAD

**Issue by apsamuel** [biopython/biopython#2899]
### Setup

I am reporting a problem with Biopython version 1.76 , Python version (3.7.4), and operating
system as follows:

System version (sys.version)
```
3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

Python Version (print(platform.python_implementation()); print(platform.platform()))
```
print(platform.python_implementation()); print(platform.platform())
CPython

$ python --version
Python 3.7.4
```

OS
```
Darwin-19.4.0-x86_64-i386-64bit
```

### Expected behaviour

features attached to seqRecord objects to match the features returned in NCBI UI.

### Actual behaviour

There is no exception message, but the object does not appear to have the data seen in the two equivalent records in the UI. 

record for the gene in NCBI nucleotide DB: https://www.ncbi.nlm.nih.gov/nuccore/388428999
record for the chromosome in NCBI nucleotide DB: https://www.ncbi.nlm.nih.gov/nuccore/NC_000013.11 

when you view the sequence features the gene, it is equivalent to the features in the object for gene (43 features), when you view the sequence features for the chromosome, there are several hundred, if not more however the corresponding sequence record object only has 1 feature, which is the `source`.

### Steps to reproduce
execute the following
```
#ref sequence chromosome 13
rec_refseq_chr = SeqIO.read( Entrez.efetch(db='nucleotide', rettype='gb', retmode='text', id='568815585'), 'gb')
#ref sequence BRCA2
rec_refseq_gene = SeqIO.read( Entrez.efetch(db='nucleotide', rettype='gb', retmode='text', id='388428999'), 'gb')

#checking the feature counts on each
len(rec_refseq_gene.features)
Out[38]: 43
len(rec_refseq_chr.features)
Out[39]: 1
```

compare to the following:

https://www.ncbi.nlm.nih.gov/nuccore/568815585 (chromosome -> corresponds to rec_refseq_chr)
https://www.ncbi.nlm.nih.gov/nuccore/NG_012772.3 (gene -> corresponds to rec_refseq_gene)

Thanks in advance, please let me know if i should add more info.

**Comment by peterjc** [comment]
On https://www.ncbi.nlm.nih.gov/nuccore/568815585 I see one feature, with a banner suggesting using the customise view panel.

In Entrez you probably need to change between ``rettype='gb'`` (some records are abbreviated, e.g. described in terms of other records) and ``rettype='gbwithparts'`` which in the website download options is labelled as "GenBank (full)".

**Comment by apsamuel** [comment]
Thanks a lot for the tip @peterjc, this worked as suggested. I believe my issue is resolved.

```
rec_refseq_chr = SeqIO.read( Entrez.efetch(db='nucleotide', rettype='gbwithparts', retmode='text', id='568815585'), 'gb')
len(rec_refseq_chr.features)
Out[45]: 7254
```


> On https://www.ncbi.nlm.nih.gov/nuccore/568815585 I see one feature, with a banner suggesting using the customise view panel.
> 
> In Entrez you probably need to change between `rettype='gb'` (some records are abbreviated, e.g. described in terms of other records) and `rettype='gbwithparts'` which in the website download options is labelled as "GenBank (full)".
