### ISSUE TITLE
Version specific API links in Tutorial

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2904]
As of #2903 for Biopython 1.77, we replaced the links to the old epydoc generated API documentation to point at the Sphinx generated version (see #906).

However, those URLs are deliberately version specific. That means we need a plan for the next release. Options which come to mind:

- (a) Manually update the version in the document title and these links?
- (b) Can we update the LaTeX to define the Biopython version once, and use that for the document title and within the links? If so, can that be adapted to RST assume we do convert away from LaTeX later on? See #907
- (c) Can we add a redirecting latest version link to the website? See also how does ReadTheDocs do this?

**Comment by peterjc** [comment]
* (d) Just point at the dev version of the API docs, which is the cutting edge and a useful proxy for the latest version?

**Comment by chebizarro** [comment]
Initially I was thinking that (b) would be a relatively simple solution as the version could be defined in the Makefile (or as a ENV variable) and passed to LaTeX document as an argument (as per [this question](https://tex.stackexchange.com/questions/270755/passing-arguments-to-latex-file)). Sphinx has the [extlinks](https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html) extension which looks like it could do the job for an RST conversion with the added convenience of the version number being defined once in the `config.py` file.

(d) is a much simpler approach overall but could be confusing for end users if the Tutorial version is always "dev". If you're going to update the front page with the version you may as well do (b) anyway.

I can put together a pull request for (b) in any case for testing purposes.

**Comment by peterjc** [comment]
Sounds good Chris - yes please.

**Comment by peterjc** [comment]
Good job.

OK, we just need to simplify https://biopython.org/wiki/Building_a_release to match, and we can close this.

**Comment by peterjc** [comment]
Lovely, thank you!
