### ISSUE TITLE
Version switching on the Sphinx API docs

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2906]
We now have:

- https://biopython.org/docs/1.74/api/
- https://biopython.org/docs/1.75/api/
- https://biopython.org/docs/1.76/api/
- https://biopython.org/docs/1.77/api/
- ...
- https://biopython.org/docs/dev/api/

The webpage source for these exists here:

https://github.com/biopython/docs

The Sphinx configuration to build them is here:

https://github.com/biopython/biopython/tree/master/Doc/api

Can we add some JavaScript or otherwise like on ReadTheDocs to make it easy to toggle between version from within the browse?

This likely means some changes to our Sphinx configuration (e.g. the common templates), and therefore would require backporting to regenerate the old pages - which would be OK.

This could also resolve #2904.

**Comment by morrme** [comment]
Hi! 
Looks like https://github.com/sphinx-contrib/sphinxcontrib-versioning could work.

**Comment by peterjc** [comment]
That sounds worth exploring (GitHub emailed me after your edit, I must have missed your comment back in June - sorry)

**Comment by MarkusPiotrowski** [comment]
https://github.com/biopython/biopython/blob/f95d94573b7f45728cbb66814bfe2cad3e7f0e2e/Doc/api/conf.py#L134-L147

Is this 'active', has it any effect? Where would be the files that are mapped here?

I also found this SO question: https://stackoverflow.com/questions/49331914/enable-versions-in-sidebar-in-sphinx-read-the-docs-theme which may help here.

I guess there is no other way than testing such things locally, am I right? So I would need to install Sphinx and make local copies of the respective repositories/folders?

**Comment by peterjc** [comment]
Yes, doing it locally would be best - but this should work with minimal manual dependency installation:

```
$ git clone git@github.com:biopython/biopython.git
$ cd biopython
$ tox -c .travis-tox.ini -l  # optional
$ tox -c .travis-tox.ini -e api # currently reports lots of warnings 
$ open Doc/api/_build/html/index.html
```

Running locally will not attempt to push the build to the GitHub Pages docs repository - you won't need to touch that until we have something ready to live test. If you want to test online, you could use your personal github pages setup, for example https://peterjc.github.io/ currently has a copy of the main home page.

**Comment by peterjc** [comment]
As an aside, maybe we should rename ``.travis-tox.ini`` to just ``.tox.ini`` (still hidden) or one of the defaults like ``tox.ini`` (clutters the top level file listing slightly).

**Comment by MarkusPiotrowski** [comment]
Making the api docs with Sphinx under Windows
---------------------------------------------------
(for reference, if someone, e.g. me, has similar problems in the future)

System setup: Windows 10, 64 bit, Python 3.7.4, installed with Miniconda, Visual Studio 19 command line tools installed (for compiling C files)

Before starting, I installed `tox` and `Sphinx` (via `conda install ...`)

In my Bopython git environment:
```
$ git checkout -b api_docs
$ tox -c .travis-tox.ini -e
```

The adventure begins!

Quests (not in chronological order)

- Although Git for Windows operates with a MinGW bash commandline, it does not have the command `make`. Pimp your MinGW with `make` as described here: https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058
- Although Git for Windows ... (see above), paths need backslashes as separator, so `travis-tox.ini` must be changed to
  ```
  commands =
    bash -c \'python setup.py install' # don't know how to  > /dev/null\' here
    make -C Doc\api\ html
  ```
- Use `tox` with verbosity, best `-vv`. In my git environment, `tox` tends to crash or hang silently without returning when encountering an error condition. With verbosity on it will display the error messages and returns (yes, that's strange, but really, I spent at least 30 min waiting for `tox` to return and report something).
- Although at the beginning `tox` declares happily that all requirements are meet and everything has been installed, later it (or Sphinx?) complains about missing dependencies. I had to manually install `numpydoc` and `sphinx_rtd_theme`
- `setup.py install` fails with the error that a Visual C compiler is needed. So I did the build separately/manually (install will use the files in the `build` folder)
- Finally everything run through but `tox` exited with an error condition, although everything seems to have worked:
  ```
  build finished with problems, 12 warnings.
  make: *** [Makefile:20: html] Error 1
  make: Leaving directory 'E:/git_32bit/biopython/Doc/api'
  ERROR: InvocationError for command 'E:\git_32bit\mingw32\bin\make.EXE' -C 'Doc\api\' html (exited with code 2)
  api finish: run-test  after 379.18 seconds
  api start: run-test-post
  api finish: run-test-post  after 0.00 seconds
  ___________________________________ summary ___________________________________
  ERROR:   api: commands failed
  ```

- The contents are fetched from the systems's Biopython. My doc html files are labelled as `1.76` and have the corresponding content (e,g., `Bio.Seq.Seq` still having the alphabet), while my git Biopython is 1.79dev.

Now I can start experimenting...

**Comment by peterjc** [comment]
Ah - I thought I was seeing it build Docs for the installed Biopython rather than the local copy (macOS). Perhaps Sphinx is escaping Tox's environment somehow... but it works on TravisCI. Strange.

**Comment by MarkusPiotrowski** [comment]
We now have version switching for the documentations of Biopython 1.74 to 1.78 (dev version is to come) with the options "Previous|Latest|Develop".

The previous version number is calculated in `conf.py` from the latest version number (version - 1 or version - 2 if dev-version), which is a bit fragile in case we should have version gaps (can this happen?).

Whatever, it seems that there is no easy way to extract the number and names of archived documentations from the biopython/biopython repository; in biopython/docs one could read the directory to list the available documentation versions, but this is not accessible to `conf.py`.

Thus, I'd like to suggest putting a text file to biopython/biopython's `Doc/api` folder which contains a list of the available Sphinx-generated documentation versions. This could be read and automatically updated by `conf.py` and would allow for more flexible version switching (if desired).

**Comment by peterjc** [comment]
I'm unclear what the text file listing adds over the directory listing?

**Comment by MarkusPiotrowski** [comment]
How can `conf.py` easily access the directory listing in a different repository?

**Comment by peterjc** [comment]
I was thinking in terms of the deployment script (which would have both repositories). Fair point, in the context of building the docs, we don't have this information.
