### ISSUE TITLE
MMCIFParser fails to load atom serial numbers.

### ISSUE THREAD

**Issue by ChrisMoth** [biopython/biopython#2913]
I have a fix for this.  Please let me know if you approve this issue, and whether you'd like a pull request.

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

I also downloaded the latest version of Biopython to verify that the problem is still in the code.

### Expected behaviour

When structure_builder.init_atom() is called from MMCIFParser.py, the atom serial_number would be initialized in of StructureBuilder.py , and in turn, the parsed structure would be saveable with the original atom serial numbers.

The demo  program below should print "serial #1" following both pdb and mmcif parsers.

pdb   first atom serial # 1
mmcif first atom serial # 1

The demo program should successfully write 4 .pdb files to /tmp.

### Actual behaviour

Atom serial numbers, available as mmcif_dict['_atom_site.id'] are disregarded by the MMCIF parser.  Attempting to save the parsed mmCIF structure to PDB with the preserve_atom_number_flag=True crashes.

Specifically, the demo  program below outputs:
pdb   first atom serial # 1
mmcif first atom serial # **None**

and only 3 of the 4 .pdb files are properly written to temp.

The 4th, which attempts to save the mmcif structure as pdb with "preserve_atom_number_flag=True" generate this exception:

Traceback (most recent call last):
  File "./atom_serial_bug.py", line 26, in <module>
    pdbio.save('/tmp/cif_crashes_with_preserve.pdb',preserve_atom_numbering=True)
  File "/home/mothcw/anaconda3/lib/python3.7/site-packages/Bio/PDB/PDBIO.py", line 353, in save
    chain_id,
  File "/home/mothcw/anaconda3/lib/python3.7/site-packages/Bio/PDB/PDBIO.py", line 218, in _get_atom_line
    return _ATOM_FORMAT_STRING % args
**TypeError: %i format: a number is required, not NoneType**

### Steps to reproduce
0) Create a working directory
1) Download 1cek.pdb from rcsb.org
2) Download 1cek.cif from rcsb.org

Run this short program to demonstrate that atom serial numbers are not populated by the mmCIF parser:
---------------------------------------------------------------------------------------------------------------------
```
#!/usr/bin/env python

"""Short program to demonstrate that atom serial numbers are not 
   read by the MMCIF parser"""

# Parse in the small 1cek.cif file downloaded from rcsb
from Bio.PDB import MMCIFParser
mmCIF_parser = MMCIFParser(QUIET=True)
structure_cif = mmCIF_parser.get_structure('1cek','1cek.cif')

# Parse in 1cek.pdb file downloaded from rcsb
from Bio.PDB import PDBParser
pdb_parser = PDBParser(QUIET=True)
structure_pdb = pdb_parser.get_structure('1cek','1cek.pdb')

print("pdb   first atom serial # %s"%list(structure_pdb.get_atoms())[0].get_serial_number())
print("mmcif first atom serial # %s"%list(structure_cif.get_atoms())[0].get_serial_number())

from Bio.PDB import PDBIO
pdbio = PDBIO()
pdbio.set_structure(structure_pdb)
pdbio.save('/tmp/pdb_saves_ok_without_preserve.pdb',preserve_atom_numbering=False)
pdbio.save('/tmp/pdb_saves_ok_with_preserve.pdb',preserve_atom_numbering=True)
pdbio.set_structure(structure_cif)
pdbio.save('/tmp/cif_saves_ok_without_preserve.pdb',preserve_atom_numbering=False)
pdbio.save('/tmp/cif_crashes_with_preserve.pdb',preserve_atom_numbering=True)
```

**Comment by JoaoRodrigues** [comment]
Thanks for the issue. How do you propose fixing this issue?

**Comment by ChrisMoth** [comment]
João, I apologize for missing previously filed issue 1206.  I thought I 
had searched for "serial" and "atom serial" both. Google found it - 
already here:

https://github.com/biopython/biopython/issues/1206


I am disappointed to further read that the mmcif IDs need not be ints 
that correspond to PDB serial numbers:

https://www.ebi.ac.uk/pdbe/docs/exchange/mmcif_pdbx.dic/Items/_atom_site.id.html

This "atom serial number" problem is very minor.  I like the proposed 
"option 1" in issue 1206, and my code could perform that easily, if 
you'd like me to wire that in.  Here is the idea:

---------------------------------

Prior to my reading the above two changes to MMCIFPArser.py seemed 
sufficient.

Around like 78 add a single line to reference what appears to be the 
serial numbers (bolded here):

     mmcif_dict =self._mmcif_dict
*atom_serial_id_list = mmcif_dict[**"_atom_site.id"**]*
    atom_id_list = mmcif_dict["_atom_site.label_atom_id"]

Around line 199 you need the serial number to be based to init_atom (code bolded).  Stylistically, I suppose it'd be nicer to have this up above where the other things[i] are converted
to single variable names....  and perhaps have a "try" in case there is a bad structure without ints in this dictionary component.

     structure_builder.init_atom(
         name, coord, tempfactor, occupancy, altloc, name,*serial_number **= **int**(atom_serial_id_list[i])*,element=element
     )

This would also need to be added to the 'FastMMCIFParser'

---------------------------------


FINALLY - I have a cultural question/request.  I use BOTH the "Structure" and the (excellent) mmcif_dict for much of my work.   I certainly do not want to have to call MMCIF2Dict AND  MMCIFParser.get_structure()
Today, I sin, and I shamefully reference the self._mmcif_dict dictionary after parsing, before the parser goes out of scope.

For reference, In MMCIFParser.get_structure(sef,structure_id,filename) there is:
       self._mmcif_dict = MMCIF2Dict(filename)
       self._build_structure(structure_id)

It would be a very nice thing if "filename" parameter could alternate be the mmcif dictionary itself, so that reading the dictionary would be done outside the get_structure().  The code above would simply become:

       if type(filename) == dict:
           self._mmcif_dict = filename
       else:
            self._mmcif_dict = MMCIF2Dict(filename)
       self._build_structure(structure_id)

Or if that feels wrong, perhaps we need a "get_structure_from_mmcif_dict(self,structure_id)" call to avoid reading the filesystem twice (or shameful hacks).

**Comment by ChrisMoth** [comment]
On 3rd thought, Structure/Model/Chain/Residue/Atom may simply need to change a bit when constructed from an mmCIF dict, vs. a PDB file.  'atom serial number' is a member of Atom that _only_ has meaning.  We perhaps need an Atom.site_id to be populated when construction is coming from an mmCIF dict.

Restated, the world is inexorably moving to mmCIF.  We should not patch the mmCIF side of the library to hang on to fading ".pdb" format orientation.

Perhaps, on initial load of an mmCIF structure, the atom serial numbers should simply be initialized to 1,2,3,4,...,N.  That would at least stop the pdb-save-time exception.  I don't see it causing harm, even as the Atom.site_ids, in most cases, will be initialized identically to the Atom.serials

Perhaps, when pdbio.set_structure() is called, then at _that_ point the atom serial numbers should be filled in, if not present due to an mmCIF based initial Structure construction.  Though modifying the argument to "set_structure()" seems like a bad idea.

Or, perhaps the (increasingly legacy) pdbio.save() needs a new cif compatability argument 'atom_serial_from_unique_id=False' argument, and exceptions to more verbosely/clearly  crash when the source mmcif dict has not-integer atom identifiers.  (The current crash at format of the PDB line is annoying to have to stop and debug).

Sorry for over-thinking this very minor issue.  I had always thought mmCIF was a superset of PDB format.  In case of the silly atom serial numbers, I know now this is not quite true.

Going forward, however this is solved (or ignored), continuing to center our notion of "Structure" on mmCIF, while reaching back to PDB until it is fully deprecated, must be the right approach.

**Comment by JoaoRodrigues** [comment]
Hi Chris,

Thanks for the detailed thoughts and the time you put into this. Reading the mmCIF specification (http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Items/_atom_site.id.html) it seems that this field is required but indeed, it does not necessarily have to be numerical.

I think a plausible solution would be to force serial numbers in PDBIO to be numerical (because there they must be), but in MMCIFIO they can be whatever we want. Any None values should translate to an empty string upon parsing to keep it simple. That way the Structure object keeps whatever you read, and it's up to the writer to either try to convert (PDB) or not (MMCIF).

**Comment by JoaoRodrigues** [comment]
After a bit of digging, filling in the serial number is actually left to `StructureBuilder`, which defaults to `None`. Since we do parse it in `MMCIFParser`, we should just pass it to the builder? Maybe this would solve the issue?

**Comment by JoaoRodrigues** [comment]
I pushed a tentative fix to a branch on my fork. @ChrisMoth could you check it? We would need to write a test or two to make sure that all these combinations work.

The branch is here: https://github.com/JoaoRodrigues/biopython/tree/mmcif_atomid_fix

I added a check to PDBIO to fail if it cannot convert the serial number to a number. Also changed the mmCIF parser to read the serial number from the files and add it to the Atom object as they build the structure.

**Comment by ChrisMoth** [comment]
Thank you.  My code works with these changes.  My code now replicates PDB python2 structure pre-processing code for Rosetta ddg-monomer calculations in python3, with Biopython, starting from mmcif files.  With preserve_atom_number, I can output PDBs with skipped atom serial numbers (which is an odd thing to want to do of course).

I continue to worry that it is not strategic to assigning mmcif dictionary components to Structure elements using legacy PDB naming conventions.  And, I wonder what it would take for the world to embrace a single python3 module for initial parsing of mmCIF files.  I'd like it to come from BioPython!

The mmCIF "_anything**.id**" components are offen unique keys that demand our closer attention, as deferencing across the entire dictionary must often be accomplished through them, and by default, those cross-references are not created by Biopython's mmCIF parser.  So, renaming this to serial number in our legacy PDB-based Atom class may not be optimal.

I have not yet studied the BioPython testing approach, and I don't have a small test top-of-mind.  Sorry.

Looking at the code you've written, I can't imaginable problem with external code already in production.

Thank you for jumping on my request so quickly(!).  

I suggest both #2913 and #1206 can be moved to "pending testing" (as long as we all keep thinking about a more complete transition to mmCIF, and away from PDB format :) )

Stay safe!

**Comment by JoaoRodrigues** [comment]
Thanks for the comments @ChrisMoth and for checking that my fix works. I will work on the tests. Usually we just take a small data file (PDB and mmCIF in this case) and write a small function that replicates the bug we are trying to fix and check it doesn't happen anymore.

I understand that the world should move to mmCIF files, but unfortunately most of us still work with PDB files.. I will close this issue at we can move the discussion to the PR I just opened: #2924
