### ISSUE TITLE
Seq("X").join(single_string) fails

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2919]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:05:27) 
[Clang 9.0.1 ]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-19.4.0-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.78.dev0
```

### Expected behaviour

The ``Seq`` object should match the Python string's join method with single string arguments:

```
>>> "X".join("a")
'a'
>>> "X".join("abc")
'aXbXc'
```

### Actual behaviour

```
>>> from Bio.Seq import Seq
>>> Seq("X").join("abc")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pc40583/repositories/biopython/Bio/Seq.py", line 1244, in join
    raise ValueError("Input must be an iterable")
ValueError: Input must be an iterable
>>> Seq("X").join("a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pc40583/repositories/biopython/Bio/Seq.py", line 1244, in join
    raise ValueError("Input must be an iterable")
ValueError: Input must be an iterable
```

### Steps to reproduce

Given above. Noted by @chris-rands here: https://github.com/biopython/biopython/pull/2916#issuecomment-635193611

**Comment by peterjc** [comment]
I suspect the reason I didn't implement this originally was the extra work to make ``Seq("X").join(Seq("abc"))`` respect the alphabets.

**Comment by peterjc** [comment]
WIP here: https://github.com/peterjc/biopython/tree/seq_join_solo

Has highlighted a corner where we raise ValueError but ought to raise TypeError to better match the string join.

**Comment by chris-rands** [comment]
What are the biological use cases for `Seq.join()`, i understand wanting to match python string behaviour, but why interleave biological sequences?

Also the Tutorial is outdated and says "Unlike the Python string, the Biopython Seq does not (currently) have a .join method."

**Comment by peterjc** [comment]
Opps - if you want to deal with that Tutorial update, please do.

The main motivation is Seq matching the built in Python string - we've talked about one day subclassing it, but at very least we are agreed on making it more Python string like.

For a specific biological use case, ``fake_genome = spacer.join(contigs)`` is a real example. You might use just something simple like ``Seq("N" * 50)`` as the spacer, or a more complicated artificial sequence with stop codons in all six frames.

**Comment by peterjc** [comment]
@chris-rands can you take a look at #2926?
