### ISSUE TITLE
Installing on old pythons.

### ISSUE THREAD

**Issue by cjw85** [biopython/biopython#2942]
### Setup

I am reporting a problem with Biopython source, and Python 3.5. This stems from the pypi packages not declaring for which versions of python they are compatible (not specifying `python_requires="....",` in the call to `setup()` in `setup.py`.

### Expected behaviour

Trying to install biopython with pip should install a version of biopython that is compatible with python 3.5.

### Actual behaviour

Without a version specified pip will download the latest and then when `setup.py` is invoked the python version is caught and the install exits.

### Steps to reproduce

```pip install biopython

Collecting biopython
  Downloading biopython-1.77.tar.gz (16.8 MB)
     |████████████████████████████████| 16.8 MB 9.5 MB/s
    ERROR: Command errored out with exit status 1:
     command: /home/OXFORDNANOLABS/cwright/git/medaka/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fal177xf/biopython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fal177xf/biopython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-c1oi4si4
         cwd: /tmp/pip-install-fal177xf/biopython/
    Complete output (1 lines):
    Biopython requires Python 3.6 or later. Python 3.5 detected.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by peterjc** [comment]
Biopython 1.76 was our final release to support Python 3.5

It does look like we should add ``python_requires=">=3.6"`` to ``setup.py``, but that won't fix Biopython 1.77 which is already out.

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires 

Do you want to submit that as a pull request?
