### ISSUE TITLE
does pairwise2 have the function to fix one sequence of two input sequence

### ISSUE THREAD

**Issue by jeongmeani** [biopython/biopython#2948]
Hi, 

These days, i have ampliseq reads. and i have to align this to specific sequence.
and i want to fix one sequence.

for example : 
X = ATAGGAGATT
Y = CGGATTGAGC

=> i want to X fixed like 'ATAGGAGATT'. not open the gap.  not like 'AT--AG--GAG--ATT'

so what should i do?

Best Regards.

Jeongmin

**Comment by mdehoon** [comment]
You could use `PairwiseAligner` in `Bio.Align`, and assign a very low score (e.g. -100000) to `target_gap_score`.

**Comment by MarkusPiotrowski** [comment]
In principle, yes. E.g. by using `Bio.pairwise2.align.globalmd`

```
>>> from Bio import pairwise2
>>> help(pairwise2.align.globalmd)
Help on alignment_function in module Bio.pairwise2 object:

globalmd = class alignment_function(builtins.object)
 |  globalmd(name)
 |
 |  globalmd(sequenceA, sequenceB, match, mismatch, openA, extendA, openB, extendB) -> alignments
 |
 |  match is the score to given to identical characters.
 |  mismatch is the score given to non-identical ones.
 |
 |  openA and extendA are the gap penalties for sequenceA,
 |  and openB and extendB for sequenceB.  The penalties
 |  should be negative.
 |
 |  alignments is a list of tuples (seqA, seqB, score, begin, end).
 |  seqA and seqB are strings showing the alignment between the
 |  sequences.  score is the score of the alignment.  begin and end
 |  are indexes into seqA and seqB that indicate the where the
 |  alignment occurs.
...
```
I wrote "in principle", because it seems that this returns empty alignments, which is a bug. Need to have a look.

**Comment by mdehoon** [comment]
@jeongmeani  With the `PairwiseAligner`, actually you would need `target_internal_gap_score`:

```
>>> from Bio.Align import PairwiseAligner
>>> aligner = PairwiseAligner(target_internal_gap_score=-10000)
>>> alignments = aligner.align("ATAGGAGATT", "ATAGGAAGATT")
>>> print(alignments[0])
ATAGGAGATT----
||||||-|------
ATAGGA-A--GATT

>>> print(alignments[0].score)
7.0
```
while this alignment (with a gap in the target sequence) is effectively disallowed:
```
ATAGG-AGATT
|||||-|||||
ATAGGAAGATT
```

@MarkusPiotrowski  Note that in the alignment returned by the `PairwiseAligner` there is a "gap" on the right hand side of the target sequence. If `Bio.pairwise2` includes this gap in the score calculation, then the aligner has no way of generating a reasonable alignment. Perhaps this could be the cause of the bug in `Bio.pairwise2`?

**Comment by jeongmeani** [comment]
@mdehoon , @MarkusPiotrowski 
very thank you!
your code is much helpful to me :)

i have one more question.
is there way to fix both sequence X,Y?

Best Regards.

Jeongmin

**Comment by mdehoon** [comment]
>  is there way to fix both sequence X,Y?

For `PairwiseAligner`, assign a very low score to both `target_gap_score` and `query_gap_score`.

**Comment by mdehoon** [comment]
Can this issue be closed?

**Comment by jeongmeani** [comment]
Ok!

Thank you for helping 👍

**Comment by mdehoon** [comment]
@jeongmeani 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
