### ISSUE TITLE
PDBParser does not parse all records (HETATOM->ATOM->HETATOM transition)

### ISSUE THREAD

**Issue by mcbeaker** [biopython/biopython#2963]
### Setup

I am reporting a problem with my system as follows:

```python commands
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
```python output
 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
CPython
Windows-10-10.0.18362-SP0
1.77
```
### Expected behaviour

PDBParser to parse all atoms within PDB - expected to parse 6 records from pdbFile.pdb below

### Actual behaviour

Reads only atoms up to and including the record "ATOM 2077 SG ..." from the PDB below - output from code.py (below) print only 3 record ids

### Steps to reproduce

```pdbFile.pdb

HETATM63667 FE1  ICS A 502      91.938  16.527 207.262  1.00 14.93          FE
HETATM63678  S2A ICS A 502      94.125  16.505 206.670  1.00 11.73           S
ATOM   2077  SG  CYS A 275      91.258  17.999 208.896  1.00 14.12           S
HETATM63682  S4A ICS A 502      90.748  16.404 205.320  1.00 15.43           S
HETATM63676  S1A ICS A 502      91.635  14.498 208.320  1.00 10.45           S
```

```python code.py
from Bio.PDB.PDBParser import PDBParser

p = PDBParser()
structure = p.get_structure("struct", "pdbFile.pdb")

for atom in structure.get_atoms():
        print(atom.get_full_id())
```

**Comment by peterjc** [comment]
Can you share the PDB file you are using? Or the ID if from the structure database?

**Comment by mcbeaker** [comment]
Hi Peter, thank you for your fast reply! The PDB is in the Steps to Reproduce section - I also will upload it - I missed the part that says "Attach files ..." below - sorry about that

[findgeo.input.copy.pdb.txt](https://github.com/biopython/biopython/files/4742306/findgeo.input.copy.pdb.txt)

**Comment by JoaoRodrigues** [comment]
Hi @mcbeaker 

Thank you for reporting this! Where did you get this structure from?

The issue with your PDB is that the residue ordering is not correct. You have A502, A275, and then again A502. The parser interprets this as a duplicated residue and ignores it because it does not find different insert codes. You should see some warnings when you run that script:

```
D:\Miniconda3\envs\biopy-dev\lib\site-packages\Bio\PDB\PDBParser.py:397: PDBConstructionWarning: PDBConstructionException: ('H_ICS', 502, ' ') defined twice at line 5.
Exception ignored.
Some atoms or residues may be missing in the data structure.
  PDBConstructionWarning,
('struct', 0, 'A', ('H_ICS', 502, ' '), ('FE1', ' '))
('struct', 0, 'A', ('H_ICS', 502, ' '), ('S2A', ' '))
('struct', 0, 'A', (' ', 275, ' '), ('SG', ' '))
```

The PDB format vaguely states that the atoms should be ordered, so you should not usually have this problem: "ATOM records for proteins are listed from amino to carboxyl terminus.".

**Comment by mcbeaker** [comment]
Hi Joao, thank you for getting back to me so quickly! 

This is a file that is spit out from a program called findgeo, which finds the coordination geometry of every metal present in the protein. Thanks for catching that the residue numbering is off rather then it being a ATOM to HETATOM then back to HETATOM error.

I actually had PDBParser(QUIET=“True”) so that explains not seeing the error. Weird findgeo would output such a structure. 

Much gratitude 🙏, 

Ken

**Comment by JoaoRodrigues** [comment]
No problem!

I wrote a small set of tools to manipulate PDB files (outside biopython) and there is a `pdb_sort` function in there. Maybe you can just plug that after you run findgeo to fix the files before parsing in Biopython: http://www.bonvinlab.org/pdb-tools/

**Comment by mcbeaker** [comment]
Beautiful Joao - nice to meet you - I have seen your tools before - I am used to using the other persons tools - thank you for reintroducing me - these are fantastic - I would be quiet interested in being a fly on the wall when you realized you needed such functions in your toolbox and which problem you were addressing.
