### ISSUE TITLE
Bio pairwise local alignment

### ISSUE THREAD

**Issue by unfashionable** [biopython/biopython#297]
the speed pairwise2.align.localxx(seq1,seq2) is too slow!
I'm using emboss water, it is very faster. Can you incorporate water in your Biopython?

**Comment by peterjc** [comment]
Thanks to @MarkusPiotrowski who has done a lot of work on ``Bio.pairwise2`` this should be much faster with our next release (Biopython 1.68) onwards. Marking as fixed.
