### ISSUE TITLE
Error reading msf file using Bio.AlignIO.MsfIO

### ISSUE THREAD

**Issue by Meirom-Michal** [biopython/biopython#2970]
@peterjc 
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Biopython 1.7.6
Python 3.6
Ubuntu 18.04

### Expected behaviour

parsing msf file using Bio.AlignIO.MsfIO

### Actual behaviour

raise ValueError("Expected sequence for %r, got: %r" % (name, line))

### Steps to reproduce

msf file is attached

[try_msf.zip](https://github.com/biopython/biopython/files/4763054/try_msf.zip)

**Comment by peterjc** [comment]
Good news, I can reproduce it - but I don't immediately see what the parser is unhappy about.

```
$ python -c "from Bio import AlignIO; print(AlignIO.read('try_msf.msf', 'msf'))"
Traceback (most recent call last):
...
    raise ValueError("Expected sequence for %r, got: %r" % (name, line))
ValueError: Expected sequence for 's322a91814fe3', got: '           s322a91814fe0  .......... .......... .......... .......... ..........\n'
```

Lines in MSF where the sequence is all dots are not unusual, and the order of the sequences seems to be consistent.

**Comment by peterjc** [comment]
Do you know how the MSF file was generated? e.g. Tool name, or if a public project a URL?

**Comment by Meirom-Michal** [comment]
The MSFfile was generated using Multalin. 
Attached, the original file, which I've made some edits  (adding header and Type of sequence).


[try_msf_original.zip](https://github.com/biopython/biopython/files/4780172/try_msf_original.zip)

**Comment by peterjc** [comment]
OK, the original file from Multalin does not have an MSF header that we
know about - "!!NA_MULTIPLE_ALIGNMENT", "!!AA_MULTIPLE_ALIGNMENT", and
"PileUp".

Also, the MSF line is just:

```
 MSF:    975    Check:   0
```

This is missing the "Type:" entry which the parser currently expects. You
fixed both of those but the other change needed was a blank line after this
one. Then it works:

```
$ diff try_msf_original.msf try_msf_hack.msf
0a1
> !!NA_MULTIPLE_ALIGNMENT 1.0
16c17,18
<  MSF:    975    Check:   0         ..
---
>  MSF:    975     Type: N    Check:   0         ..
>
```

We could probably tweak the parser to accept the missing "Type: ..." entry
but I am unclear if this is mandatory or not. Likewise accepting the blank
line seems a reasonable change.

Are you in contact with the Multalin team? These would be small changes for
them and increase the likelihood of other tools being able to parse their
MSF files directly.

**Comment by Meirom-Michal** [comment]
Great, it's working now.
Yes, I did notify the Multalin team. 

Thanks for your help!
