### ISSUE TITLE
ResidueDepth

### ISSUE THREAD

**Issue by DuanhaoranCC** [biopython/biopython#2983]
Hello,

My biopython version is 1.73, executing `rd= PDB.ResidueDepth (model)` , but I'm sorry to report an error.`The runtime error: failed to generate surface file usingcommand:` I have downloaded the binary file of MSMS. What else should I do? Environment variable? Or something.

**Comment by peterjc** [comment]
Can you manually run the command it tried to use as the terminal, and does that work or give a more helpful error message?

Also in case it is relevant, which version of MSMS do you have, and what OS?

**Comment by DuanhaoranCC** [comment]
I'm sorry. I didn't give you a detailed description,

My computer is windows 10 64bit. I use MSMS's official website (http://mgltools.scripps.edu/downloads),MSMS 2.6.1 - current release downloaded Binaries of the MSMS C library,After that, no configuration was made.

Then I called RD in the python program. `PDB.ResidueDepth (model, 'D:/benchmark5/structures/1DFJ_ R_ b. PDB')`, an error is displayed

`C:~\Programs\Python\Python36\lib\site-packages\Bio\PDB\ResidueDepth.py:533: BiopythonDeprecationWarning: ResidueDepth no longer requires a pdb file. This argument will be removed in a future release of Biopython. "of Biopython.", BiopythonDeprecationWarning)
'msms' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "E:/jupyter/GCN/10.py", line 30, in <module>
    rd = PDB.ResidueDepth(model, 'D:/blast-2.10.1+/msms_win32_6.2.1/1crn.pdb')
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\PDB\ResidueDepth.py", line 541, in __init__
    surface = get_surface(model)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\Bio\PDB\ResidueDepth.py", line 486, in get_surface
    "command:\n%s" % make_surface)
RuntimeError: Failed to generate surface file using command:
msms -probe_radius 1.5 -if C:\Users\lenovo\AppData\Local\Temp\tmpwxg9y2o2 -of C:~\AppData\Local\Temp\tmpnap3uxk4 > C:~\AppData\Local\Temp\tmpo6jelb8m

I can run on the windows command line msms.exe Yes, but not in the program. I guess the program can't find this msms.exe , but I don't know how to configure
`

**Comment by peterjc** [comment]
The simplest option is to add the folder containing the MSMS binary to you PATH environment variable.

Or, you should be able to specify the full path to the binary - strangely the class ``ResidueDepth`` does not let you do that, just the function ``get_surface`` which it calls internally. That would mean a code change in Biopython to allow this - something like this maybe:

```python
rd = PDB.ResidueDepth(model, MSMS=r"C:\Program Files\Some Folder\MSMS.exe")
```

Does that sound like a good idea? Is it something you feel confident about trying - and turning into a pull request to improve Biopython?

Note I would recommend using raw strings (prefix with r) to avoid Python trying to interpret Windows slashes as escape characters (e.g. "\t" for tab). Or, Unix style slashes should work too.

**Comment by rraadd88** [comment]
I couldn't find the `MSMS` parameter because I was importing the `ResidueDepth` module just as mentioned in the [documentation](https://biopython.org/docs/latest/api/Bio.PDB.ResidueDepth.html) i.e.
```
from Bio.PDB.ResidueDepth import ResidueDepth
```
In this case, `msms_exec` parameter is where the path to the MSMS binary goes. e.g.
```
ResidueDepth(model,msms_exec='/path/to/msms')
```

**Comment by peterjc** [comment]
@rraadd88 Yes. Earlier in this issue, I suggested we add something to allow this:

```python
rd = PDB.ResidueDepth(model, MSMS=r"C:\Program Files\Some Folder\MSMS.exe")
```

But as per the discussion on #3005, the update allows this:

```python
rd = PDB.ResidueDepth(model, msms_exec =r"C:\Program Files\Some Folder\MSMS.exe")
```
