### ISSUE TITLE
Error importing SeqIO

### ISSUE THREAD

**Issue by tokeru** [biopython/biopython#2997]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

>>> import sys; print(sys.version)
3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Windows-10-10.0.18362-SP0
>>> import Bio; print(Bio.__version__)
1.77

### Expected behaviour

When I try 
`from Bio import SeqIO`
this works fine in my IDE and also when I start my program from windows power shell.

### Actual behaviour

When I try it in the python shell and therefore also when I try to simply run my python script with double click in windows it raises an error:
`>>> from Bio import SeqIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alb18\AppData\Roaming\Python\Python37\site-packages\Bio\SeqIO\__init__.py", line 382, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "C:\Users\alb18\AppData\Roaming\Python\Python37\site-packages\Bio\Align\__init__.py", line 21, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners' from 'Bio.Align' (C:\Users\alb18\AppData\Roaming\Python\Python37\site-packages\Bio\Align\__init__.py)`

I've seen that there was some discussion on this error. But I cant figure out how to fix this error and why it is working when started from the shell.

**Comment by peterjc** [comment]
Can you tell where (which directory) the double click example starts from? If that happens to be within the Biopython source code tree, bad things happen. You get local imports (where the C code is missing) rather than importing from the installed copy in site-packages. But we have a specific error message for that situation, so something else is evidently breaking here.

Can you check the IDE and the command line / double click are all using the same copy of Python? You may have more than one installed.

I don't have access to a Windows machine so am not in a position to try to recreate this locally.

**Comment by tokeru** [comment]
The Double Click starts from a generic path in my windows partition, nothing to do with python. (C:\Daten\Alex\NTDB).
While I think that I only have one Python Installation, I'm not entirely sure wether my IDE (Thonny) uses a different one. But I can tell that double click and command line shall use the same. I also looked in my PATH which python it is targeting. I then opened the Python shell in my PATH variable and tried the import there with same error.
As far as my knowledge goes, the installation in PATH should be the one that is startet in the power shell.

**Comment by peterjc** [comment]
How did you install Python? e.g. Windows installer from python.org, or using something else like Anaconda?

How did you install Biopython? e.g. "pip install biopython"

@mdehoon do you have any idea why this might fail to import ``_aligners``?

**Comment by tokeru** [comment]
Python windows installer from python.org. biopython installed first with thonny plugin manager. Then during this Problem already tried to uninstall and reinstall with pip.
I can also add that from Bio import Seq for example works fine. Importing aligners directly also dont work.

**Comment by peterjc** [comment]
And the IDE you are using where it works is Thonny? https://thonny.org/ says "Thonny comes with Python 3.7 built in" (by default), so perhaps you only have Biopython installed properly on the Thonny provided Python, not the Python.org installed Python?

**Comment by tokeru** [comment]
I would admit but as i told Import bio works as well as from bio import seq

**Comment by MarkusPiotrowski** [comment]
I also have the feeling that you have different python installations. 

One indication is the installation path which is quite deep in your user folder; I'd expect it to be somewhere in programs or programs x86. Is this the same path which is set in your path variable? 

When you right click your python file, you should be able to see in the properties how it is started. Or the information is stored in the registry. 

Can you check this?

**Comment by tokeru** [comment]
While this would not explain why, in the same python shell, import bio works but from bio import seqio doesnt, i will Check again. As it is the pc at my work I have to wait till tomorrow.

**Comment by MarkusPiotrowski** [comment]
It could be that one of the putative installations is missing the compiled C files. E.g. the Bio folder should contain a pairwise2-...pyd file. Imports not requiring a C file will work, others not.

**Comment by peterjc** [comment]
Closing as no further information provided.
