### ISSUE TITLE
Option to write nucleotide SeqRecord to protein FASTA

### ISSUE THREAD

**Issue by rchurt** [biopython/biopython#3002]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
CPython
Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
1.77

### Expected behaviour

Unless I'm mistaken, the only way to write a protein FASTA is to pass a SeqRecord object containing protein sequences into SeqIO.write. However, it's commonly the case that one is working with a SeqRecord object containing _nucleotide_ sequences with CDSs annotated as features or with translation qualifiers. In this case, you would need to go through an extra step of creating a new SeqRecord object containing protein sequences before writing. It seems like you should be able to do something like SeqIO.write(nt_SeqRecord, handle, 'fasta_protein'), and have it _either_ translate CDSs annotated as features and extract them or directly extract translation qualifiers, and write those as a protein FASTA in a single step.

Please let me know if I'm mistaken and there's already a built-in command for this.

**Comment by peterjc** [comment]
What is your actual goal here? Converting an annotated genome in GenBank or EMBL to a FASTA file of protein sequences using the given amino acid translations? If so, this is probably what you need - a specialised GenBank parser which gives one SeqRecord per CDS:

```python
from Bio import SeqIO
SeqIO.convert("input.gbk", "genbank-cds", "proteins.fasta", "fasta")
```

Otherwise, you've need to convert each genomic SeqRecord into multiple protein SeqRecord object - most likely by looping over the features and for the CDS features calling the extract method to get the (spliced) sequence and translating that. Or, just take the given amino acid translation from the CDS feature annotation (only option for things with complicated post translational modification).

**Comment by rchurt** [comment]
Thanks very much for this.

My goal here is to take several genomic regions, get the name, nucleotide sequence, and protein sequence of each CDS, and combine all of these from all genomes into a single nucleotide multiFASTA and a single protein multiFASTA. However, in the middle, I have to do a few processing steps (e.g., I want the name to be 'organism name|CDS label' since all CDSs from all organisms are going into the same FASTA, I want to remove any entries that are exact duplicates of each other at the nucleotide or protein sequence level, and if there are any names that are identical, append numbers to them so downstream scripts don't freak out).

To be honest, this is my first time using BioPython, and since I'm not so comfortable with it, what I did was to take all the input sequences, convert them to a dataframe with columns for species, sequence, label, translation, etc., do my processing on the entries in the dataframe, then convert each row to a nucleotide seqrecord with translations, and finally export my nucleotide and protein multiFASTAs.

I might take a crack at doing the whole process while keeping them as seqrecord objects, but even if I'm able to get it to work this way, I still think it would be useful to be able to write protein FASTAs from a nucleotide FASTA directly, since the information is already there.

**Comment by peterjc** [comment]
The trouble with "directly" is all the special cases processing is likely to be use case specific, like your particular naming requirement. I suspect any sufficiently flexible function to do this would be overly complicated to document (and implement and test). But I could be wrong.

**Comment by rchurt** [comment]
Sure, I think that to simplify things, the command could do exactly what `SeqIO.write(nt_SeqRecord, handle, 'fasta')` does (meaning not edit the SeqRecord at all) but instead of grabbing the Seq and ID from the record, grab the translation and ID. I think this alone would be helpful--would that be simple to implement?

**Comment by mdehoon** [comment]
My impression is also that this is a specific use case that does not need to be in Biopython for general use.

**Comment by rchurt** [comment]
Gotcha, just so I understand, why do you think that writing protein sequences is a specific use case but writing nucleotide sequences is built in? It seems to me like these would be equally common, but I might be mistaken.

**Comment by peterjc** [comment]
Parsing the nucleotide sequence in a genomic GenBank file is built in - it is the primary sequence of the record after all. Try ``SeqIO.parse("input.gbk", "genbank")`` or if you have a single record ``record = SeqIO.read("input.gbk", "genbank")``

Parsing the given protein translations in a genomic GenBank file is also built in - the CDS features within the record. Try ``SeqIO.parse("input.gbk", "genbank-cds")``

Biopython can write out either nucleotides or proteins.

**Comment by rchurt** [comment]
Thank you, these functions are very helpful, in particular `SeqIO.parse("input.gbk", "genbank-cds")`. Out of curiosity, does that extract the nucleotide sequences in addition to the protein sequences? I see that it extracts the coordinates, but I couldn't find the nt sequence. If not, should I open up a separate issue to request this?

Regarding the subject of this thread, it's up to you whether you think it's worth adding that feature. I see it as the output analog of the command `SeqIO.parse("input.gbk", "genbank-cds")`, which takes a nucleotide sequence and extracts the translations from it for the purpose of working with them in BioPython--the proposed command would do the same, but for the purpose of writing them. But you of course know more about the internal logic of BioPython, so if you don't think it makes sense to have such a feature, then you're probably right.

**Comment by peterjc** [comment]
No, ``SeqIO.parse("input.gbk", "genbank-cds")`` just grabs the stated translation, there is nothing built in to grab the nucleotide sequence from a subset of the features for you. You would be back to looping over the ``SeqFeature`` objects, filtering on type, and using their ``.extract(...)`` method as outlined earlier.

Note that you may be able to get exactly what you want already in FASTA format from the NCBI FTP site, although it may depend on your organisms of choice. For bacteria they have/had matching sets of GenBank file, FASTA for the genome, FASTA nucleotide for the genes, FASTA amino acid for the proteins, and a few more.

**Comment by rchurt** [comment]
Ok, got it. And thank you, I didn't realize that, but that's handy.
