### ISSUE TITLE
SeqIO.parse does not allow to close handle in 1.77.

### ISSUE THREAD

**Issue by naumenko-sa** [biopython/biopython#3015]
### Setup

I am reporting a problem with Biopython version **1.77** , Python version **3.6.10**, and operating
system as follows:
```
CPython
Linux-5.3.0-1028-aws-x86_64-with-debian-buster-sid
```

### Expected behaviour

A handle closes without error

### Actual behaviour

```AttributeError: 'FastqPhredIterator' object has no attribute 'close'```

### Steps to reproduce

```python
>>> from Bio import SeqIO
>>> from bcbio.bam.fastq import open_fastq
>>> in_handle = SeqIO.parse(open_fastq("test_1.fq.gz"), "fastq-sanger")
>>> read = next(in_handle)
>>> in_handle.close()
```

It passes with biopython 1.76 and earlier: https://github.com/bcbio/bcbio-nextgen/issues/3277

SN

**Comment by peterjc** [comment]
I am puzzled if and why this ever might have worked even on an older Biopython. ``SeqIO.parse(...)`` does not return a handle, it returns an iterator - an object you loop over. You could use a context manager here to close the handle (a with statement).

I'm not sure off hand what the ``open_fastq`` function returns - presumably the equivalent of ``import gzip`` and ``gzip.open("test_1.fq.gz")`` which is the approach we document for reading gzipped FASTQ with Biopython.

**Comment by naumenko-sa** [comment]
Thanks for your time @peterjc. Easy fix.

**Comment by chris-rands** [comment]
In biopython 1.76 `SeqIO.parse()` returned a generator, which has a `.close()` method. See https://github.com/biopython/biopython/pull/2321

**Comment by peterjc** [comment]
Thanks - I was looking in our code and failing to find any relevant ``def close(self, ...)`` - I'd missed the fact the built in generator functions automatically have a ``.close()`` method:

https://docs.python.org/3/reference/expressions.html#generator.close
