### ISSUE TITLE
BUG: comparing two DNA strings, same length, allow IUPAC

### ISSUE THREAD

**Issue by YichaoOU** [biopython/biopython#3023]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```python
>>> import sys; print(sys.version)
3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-redhat-7.6-Maipo
>>> import Bio; print(Bio.__version__)
1.74
```

### Expected behaviour

AGG should equal to NGG
RGG should equal to NGG

### Actual behaviour

```python
>>> from Bio.Seq import Seq
>>> from Bio.Alphabet import generic_dna
>>> seq1=Seq("AGG",generic_dna)
>>> seq2=Seq("NGG",generic_dna)
>>> seq1 in seq2
False
>>> seq1 == seq2
False
>>> seq1=Seq("RGG",generic_dna)
>>> seq2=Seq("NGG",generic_dna)
>>> seq1 in seq2
False
>>> seq1 == seq2
False
```

### Steps to reproduce

```python
>>> from Bio.Seq import Seq
>>> from Bio.Alphabet import generic_dna
>>> seq1=Seq("AGG",generic_dna)
>>> seq2=Seq("NGG",generic_dna)
>>> seq1 in seq2
False
>>> seq1 == seq2
False
>>> seq1=Seq("RGG",generic_dna)
>>> seq2=Seq("NGG",generic_dna)
>>> seq1 in seq2
False
>>> seq1 == seq2
False
```

**Comment by peterjc** [comment]
This is by design and explicitly documented as such - sequence comparison acts like string comparison, even if your strings were DNA and protein.

Function ``nt_search`` in ``Bio.SeqUtils`` might be close to what you want, but telling us more about your use case would help. For example, is one sequence ambiguous and the other unambiguous?

**Comment by YichaoOU** [comment]
Both sequences may contain ambiguous letters, such as RGG vs NGG. I have tried `nt_search`. It didn't give matched results.

**Comment by peterjc** [comment]
They both have ambiguities? That does make things harder. I suspect this can be done with regular expressions, but there is likely a better way. How long might the sequences be?

Do you care about gaps/insertions - or allowing any mismatches - in which case I would suggest pairwise alignment.

**Comment by YichaoOU** [comment]
It's OK. I think in 99.9%, it will be "AGG" vs. "NGG". 

Regular expression is good way to go. Thanks.

I tried `from skbio.alignment import global_pairwise_align_nucleotide`, they do not support ambiguous letters.

The max length is 5.

**Comment by peterjc** [comment]
Given these are short sequences, you could map each letter to its possible meanings, N=A,C,G,T (could store this as four bits) and then take the logical AND to get any overlap. For example W = A,T and M = A,C. Now logical AND or set intersection gives A. So W and M have a shared value of A in common, and so "match".

You could have a function returning None or the match string, thus ``compare("AGGN", "NGGN") = "AGGN"`` while ``compare("WGGN", "MGGM") = "AGGM"`` etc. But maybe you just need a true/false?

**Comment by YichaoOU** [comment]
Sounds like an efficient way! Yes, I just need true or false.

**Comment by peterjc** [comment]
This dictionary might help,

```
from Bio.Data.IUPACData import ambiguous_dna_values
```

**Comment by peterjc** [comment]
Or possibly this dictionary used in ``Bio.Restriction``?:

```
matching = {
    "A": "ARWMHVDN",
    "C": "CYSMHBVN",
    "G": "GRSKBVDN",
    "T": "TYWKHBDN",
    "R": "ABDGHKMNSRWV",
    "Y": "CBDHKMNSTWVY",
    "W": "ABDHKMNRTWVY",
    "S": "CBDGHKMNSRVY",
    "M": "ACBDHMNSRWVY",
    "K": "BDGHKNSRTWVY",
    "H": "ACBDHKMNSRTWVY",
    "B": "CBDGHKMNSRTWVY",
    "V": "ACBDGHKMNSRWVY",
    "D": "ABDGHKMNSRTWVY",
    "N": "ACBDGHKMNSRTWVY",
}
```
