### ISSUE TITLE
record.format("fasta") Multi-Line vs Single Line.

### ISSUE THREAD

**Issue by LeeBergstrand** [biopython/biopython#306]
Through my research I have encountered two ways of formatting FASTA files:

Multi-Line (The sequence is broken down into spans for readability):

```
>ACY32031.1 Twin-arginine translocation pathway signal [Comamonas testosteroni CNB-2].\n
MSGNKKEESMESVNQGVDRRGFIQGAGAVAAATAMPAMAAQKKNEATAVDGYAWAEQIRR\n
GDITPLEALEAAIARTEALPKLNAVVIKDYDLARDQARQMSALGSAARAEATARAPMWGV\n
PFLLKDLNQYLKGTVTTNGCRFFKGAVAEYDSTLVARYKAAGLNIFGKTASPEFGQTPTT\n
ESLLYGKSPNPWNAAHTTGGSSGGAASVVAAGIVPVAHASDGGGSIRIPASHCGLFGLKP\n
SRGRLPAGPANMEGWMGLSMNHVISRSVRDSAHLLDLTQGREPGSRTVPPRDVEGSYLDA\n
LKQAPKKLRIAVWSRNYFGIPVHADCQAAVDKAIKACLALGHEIVEDMPELPVAEVFSGL\n
GVVTSVGMMASIRAREKLLGRAVRQDEVEQMDWLYLEKAKSYTAEQMLMARTNFDTAGQI\n
LDRFFLKYDLILTPVMAVPPPLLGVLTLDQPYDSFAREAVKASPYTALFNMTGQPAMSVP\n
MHWTADKLPIGAHFAAPFGREGRLLALAAQLEQSVPWAHRQPDLSVFKA\n
```

or 

Single Line (The sequence is written on a single line):

```
>ACY32031.1 Twin-arginine translocation pathway signal [Comamonas testosteroni CNB-2].\n
MSGNKKEESMESVNQGVDRRGFIQGAGAVAAATAMPAMAAQKKNEATAVDGYAWAEQIRRGDITPLEALEAAIARTEALPKLNAVVIK. . .\n
```

Obviously the Multi-Line format is more readable, however it has some disadvantages. 
1. Some bioinformatics software tools (ex. HMMER) do not expect Multi-Line FASTA files and require single line FASTA flies.
2. You cannot use **grep** too extract sequences from a Multi-Line Multi-SequenceFASTA file. (grep -A 1 "SeqID" file.faa)

I think there should be a secondary format called **"fastasl"** that makes Biopython format the string as a Single Line FASTA rather than a Multi-Line FASTA:

```
print record.format("fasta") # Creates multi-line FASTA string.
print record.format("fastasl") # Creates single line FASTA string.
```

**Comment by peterjc** [comment]
I happened to find this old issue while looking for something else - there was a happier ending:

As of Biopython 1.71 (April 2018), Bio.SeqIO now supports reading and writing two-line-per-record FASTA files under the format name "fasta-2line", useful if you wish to work without line-wrapped sequences. See pull request #1450
