### ISSUE TITLE
How to use no parameter options in NcbiblastnCommandline

### ISSUE THREAD

**Issue by Huangzhiqang** [biopython/biopython#3118]
Dear developer:

my Python version: 3.7.4
Biopython version: 1.77
operating system: [GCC 7.3.0] CPython Linux-4.15.0-76-generic-x86_64-with-debian-buster-sid
ncbi-blast+ version: 2.10.1+

example:
>>> from Bio.Blast.Applications import NcbiblastnCommandline
>>> cline = NcbiblastnCommandline(query="m_cold.fasta", db="nt", strand="plus", evalue=0.001, out="m_cold.xml", outfmt=5)

this example works well in python. However for some no parameter options of blastn such as "-subject_besthit", "-remote", "-help", "-version", how to make it work in NcbiblastnCommandline? There may be same question in other wrapped softwore.

**Comment by peterjc** [comment]
We called those switches rather than options in the code which implements the wrapper. Just use remote=True here.

**Comment by Huangzhiqang** [comment]
thank you! I want to use -subject_besthit I check the Applications.py

**Comment by peterjc** [comment]
Glad to help, and yes #2184 covers that particular missing recent addition to NCBI BLAST+.
