### ISSUE TITLE
PDBIO save failed when chain_id is more that one character long

### ISSUE THREAD

**Issue by akabiraka** [biopython/biopython#3134]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
1.77
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
CPython
Linux-5.4.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
```
### Error
I am trying to save a chain (BBB) of protein 6tif using PDBIO where the chains are AAA and BBB (not single character). While saving it is getting:
```
File "$HOME/python3_venv/lib/python3.6/site-packages/Bio/PDB/PDBIO.py", line 218, in _get_atom_line
    return _ATOM_FORMAT_STRING % args
TypeError: %c requires int or char
```
Because the expected chain_id should be 1 char long.

**Comment by peterjc** [comment]
Are you trying to save in PDB text format? I'd have to check the file format specification as that could be the limitation (in which case this exception could be clearer).

**Comment by akabiraka** [comment]
I was trying to save in pdb format. The problem occurs in the following 2 lines.
```
17. _ATOM_FORMAT_STRING = ( 
18.    "%s%5i %-4s%c%3s %c%4i%c   %8.3f%8.3f%8.3f%s%6.2f      %4s%2s%2s\n" 
19. )
```

and
```
286                      fp.write( 
287                          "TER   %5i      %3s %c%4i%c                                                      \n" 
288                          % (atom_number, resname, chain_id, resseq, icode) 
289                      ) 
```

In this format, chain_id is considered as a single character. So I am getting error while saving "6tif" whose chain ids are AAA and BBB!!!

**Comment by peterjc** [comment]
https://www.rcsb.org/structure/6tif does not offer this structure in PDF format - did you start with their mmCIF file perhaps?

**Comment by akabiraka** [comment]
Yes, I started with their mmCIF format, and trying to save only chain BBB in pdb format.

**Comment by rob-miller** [comment]
I think you will need to change the chain ID to a single character in your
script.  Even if PDBIO succeeded to write it out as is, it would not be a
valid PDB file so nothing would read it in.  I don't think there is a good
way that PDBIO could automatically guess what character to choose from the
three letter code, so you would need to help it along.

**Comment by akabiraka** [comment]
@rob-miller thanks, I can do that.

Since I am very novice, I never thought chain_id could be more than a single character.

**Comment by peterjc** [comment]
It looks like this is something the more modern mmCIF format allows, which was not possible in the older PDB format.

**Comment by akabiraka** [comment]
Thanks @peterjc for your help. Either I shall change the chain_in into a single character or save that into mmCIF format.

**Comment by peterjc** [comment]
Excellent - I'll close this issue then.
