### ISSUE TITLE
Dead links in the README

### ISSUE THREAD

**Issue by jvfe** [biopython/biopython#3137]
In the "Optional Dependencies" part, regarding networkx and pygraphviz,

- Networkx should be https://networkx.github.io/ not http://networkx.lanl.gov/

- Pygraphviz should be https://pygraphviz.github.io/ not http://networkx.lanl.gov/pygraphviz/

I can submit a quick PR if that's all there is to it.

**Comment by peterjc** [comment]
Yes please
