### ISSUE TITLE
How to retrieve the number of articles from mesh or NCT

### ISSUE THREAD

**Issue by federiconuta** [biopython/biopython#3174]
### Setup

Hi all,

I am currently trying to extract the number of articles from a set of conditions that I have stored in my db. The point is that I cannot simply input the names that I have since variations of them (e.g. "Diabetes" instead of "diabetes" or "short term insomnia" rather than "short-term insomnia") may lead to different results.
Hence my ideas were basically 2: 1) associate a mesh term to each condition in the data and then associate to each mesh term the number of article referred to it; 2) better option: since I have the New Clinical trials IDs (NCTIDs) of the conditions, use the NCT as secondary identifiers to retrieve the number of articles.

Now I have failed to do both since I cannot understand neither how to reteieve mesh terms (from mesh database) inputting a condition (avoiding the mentioned problems of different results for differently written conditions) nor how to input NCT as secondary IDs. For the moment I have, for a single NCT Id the following:

```python
from Bio import Entrez
Entrez.email = myemail@gmail.com
id = "NCTid[si]"  #i.e. a generic id that I have
handle = Entrez.efetch(db="pubmed", id=id, rettype="gb",retmode="xml")
record =Entrez.handle
abstract =["PubmedArticle"][0]["MedlineCitation]"Article]
```
Moreover I would like to have the number of citations in a single year fro. 2004 to 2013. So, the expected results should be:
Input = NCTid
Output = number of articles for that NCT in 2004,number of articles for that NCT in 2005,...number of articles for that NCT in 2013.

The above code it's just an attempt but it does not give me what I would like.

Is there a way to reach my goal?

Thank you,

Federico

**Comment by peterjc** [comment]
I don't know. The fact that you are using Biopython to connect to the NCBI Entrez API seems to me a minor detail here. You might have more success in getting advice on this by asking your fundamental question about NCBI MESH and NCT identifiers on somewhere like BioStars or Stack Exchange?

https://www.biostars.org/
https://bioinformatics.stackexchange.com/

**Comment by federiconuta** [comment]
Thank you,

Federico

**Comment by peterjc** [comment]
https://bioinformatics.stackexchange.com/questions/14046/nct-search-in-pubmed-via-entrez-python

Closing this, good luck.
