### ISSUE TITLE
Bio/Statistics/lowess.py trys to import non-existant  Bio.Cluster.median

### ISSUE THREAD

**Issue by mr-c** [biopython/biopython#3189]
https://github.com/biopython/biopython/blob/master/Bio/Statistics/lowess.py#L27

`Bio.Cluster.median` was removed in 2017 via bd91de581a76f6f4a8c61a2d9c54636625104c15

There's a fallback to numpy, shall I remove the `from Bio.Cluster import median` ?

**Comment by mdehoon** [comment]
Yes that is fine.

Note that the Bio.Statistics module has been deprecated, so an alternative is to just remove Bio.Statistics altogether.

**Comment by mr-c** [comment]
@mdehoon Thanks! https://github.com/biopython/biopython/pull/3190 is ready for review & merging
