### ISSUE TITLE
Wrappers for blastdb_aliastool, blastdbcmd in Biopython modules?

### ISSUE THREAD

**Issue by bsmith4133** [biopython/biopython#3197]
Hello, 

I'm trying to make a pipeline using the Bio.Blast.Applications module. In the BioPython documentation, there doesn't seem to be wrappers for tools such as blastdb_aliastool and blastbcmd. Does anyone know if they exist? If not, would the best alternative be to use the Python subprocess module for command line use?

Thanks!

**Comment by chris-rands** [comment]
See https://github.com/biopython/biopython/issues/1463

**Comment by peterjc** [comment]
Thanks Chris. And yes, subprocess is a good alternative - but see also discussion on #2877

**Comment by bsmith4133** [comment]
Thanks so much for pointing out the resources - they are very helpful. I was wondering if anyone could speak a little about platform compatibility (Linux, Windows) for subprocess module and Blast.Applications? To assemble the command line in su process, are there drawbacks to using a string and running it vs. creating a Popen object with a list of commands?

Thank you!

**Comment by peterjc** [comment]
We tried to hide Windows vs Linux/Mac differences in the ``Bio.Application`` framework although I understand people have had trouble with at least some of the tutorial examples. Please add to the discussion on #2877.
