### ISSUE TITLE
Emboss Command Line - Stdout issue

### ISSUE THREAD

**Issue by antoinekoehl** [biopython/biopython#3202]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-18.7.0-x86_64-i386-64bit
1.76

### Expected behaviour
I am trying to align two sequence using the python wrapper to EMBOSS Needle. When I initialize the needle_cline object with `needle_cline.outfile = 'test.txt'` it works and generates the Needle alignment file as normal. The outfile is identical to the one produced by running command line Needle with the same sequences.

When I instead specify `needle_cline.stdout = True` , it gives me the following error:

### Actual behaviour

---------------------------------------------------------------------------
ApplicationError                          Traceback (most recent call last)
<ipython-input-232-e2126670d200> in <module>
----> 1 stdout, stderr = needle_cline()

/opt/miniconda3/envs/Remote_Homology/lib/python3.6/site-packages/Bio/Application/__init__.py in __call__(self, stdin, stdout, stderr, cwd, env)
    529         if return_code:
    530             raise ApplicationError(return_code, str(self),
--> 531                                    stdout_str, stderr_str)
    532         return stdout_str, stderr_str
    533 

ApplicationError: Non-zero return code 1 from 'needle -stdout -asequence=/Users/antoinekoehl/Documents/GitHub/remote_homology/PDBs/5A31N.fa -bsequence=/Users/antoinekoehl/Documents/GitHub/remote_homology/PDBs/4ZU9A.fa -gapopen=10 -gapextend=0.5', message 'Needleman-Wunsch global alignment of two sequences'

### Steps to reproduce
```
from Bio.Emboss.Applications import NeedleCommandline
needle_cline = NeedleCommandline()
needle_cline.asequence = pdb_dir + '/5A31N.fa'
needle_cline.bsequence = pdb_dir + '/4ZU9A.fa'
needle_cline.gapopen = 10
needle_cline.gapextend = 0.5
needle_cline.stdout = True
stdout, stderr = needle_cline()
```

When I `print(needle_cline)` the command appears correct:

needle -stdout -asequence=/Users/antoinekoehl/Documents/GitHub/remote_homology/PDBs/5A31N.fa -bsequence=/Users/antoinekoehl/Documents/GitHub/remote_homology/PDBs/4ZU9A.fa -gapopen=10 -gapextend=0.5

I did notice that using command line needle (to stdout) first gives me the output : Needleman-Wunsch global alignment of two sequences. When I then press enter, the alignment shows up.

**Comment by peterjc** [comment]
You need to add ``-auto`` to the command line to say automated mode, do not prompt the used. i.e. ``needle_cline.auto = True`` in your example.

**Comment by peterjc** [comment]
I'm assuming you got this to work, closing issue.
