### ISSUE TITLE
Allow Bio.Align.PairwiseAligner to handle letters not in the score matrix

### ISSUE THREAD

**Issue by ccwang002** [biopython/biopython#3205]
### Setup

3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09) 
[Clang 9.0.1 ]
CPython
macOS-10.15.6-x86_64-i386-64bit
1.77

### Expected behaviour
I was trying to align [Q92813](https://www.uniprot.org/uniprot/Q92813)'s protein sequence to its isoform, which contains an amino acide Selenocysteine `U`. For simplicity, let's just align a part of this protrein's sequence to itself: `HWLEKNFSKRUKKTRLAG`. I ran the global alignment using EMBOSS Needle with the default score matrix BLOSUM62, and here is the output:

```
#=======================================
# Matrix: EBLOSUM62
# Gap_penalty: 10.0
# Extend_penalty: 0.5
#
# Length: 18
# Identity:      17/18 (94.4%)
# Similarity:    17/18 (94.4%)
# Gaps:           0/18 ( 0.0%)
# Score: 93.0
#=======================================

EMBOSS_001         1 HWLEKNFSKRUKKTRLAG     18
                     |||||||||| |||||||
EMBOSS_001         1 HWLEKNFSKRUKKTRLAG     18
```

Despite that `U` is not in BLOSUM62 (should it be covered by `X`?), Needle is able to generate an alignment with `U` being mismatch. Currently Bio.Align.PairwiseAligner will raise an exception of having unknown letter in the sequence.

I was wondering if there could be an option in Bio.Align.PairwiseAligner to enable the handling of unknown letter in the sequence. If so, I expect it to perform the same as Needle given the same parameters. Unfortunately, I wasn't sure how Needle handles an unknown letter (their method is in `emboss/needle.c`), nor how the Needleman–Wunsch algorithm should handle it in general.

### Actual behaviour
Currently, Bio.Align.PairwiseAligner will raise an exception when encountering an unknown letter in the score matrix:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-b582941a1d95> in <module>
----> 1 aligner.align(seq1, seq2)[0]

~/miniconda3/envs/cptac/lib/python3.8/site-packages/Bio/Align/__init__.py in align(self, seqA, seqB)
   1554         if isinstance(seqB, Seq):
   1555             seqB = str(seqB)
-> 1556         score, paths = _aligners.PairwiseAligner.align(self, seqA, seqB)
   1557         alignments = PairwiseAlignments(seqA, seqB, score, paths)
   1558         return alignments

ValueError: sequence contains letters not in the alphabet
```

If the score matrix is not defined, the alignment works as expected:

```pycon
>>> aligner2 = Align.PairwiseAligner()
>>> print(aligner2.align(seq1, seq2)[0])
HWLEKNFSKRUKKTRLAG
||||||||||||||||||
HWLEKNFSKRUKKTRLAG
```

### Steps to reproduce

```python
from Bio import Align
from Bio.Align import substitution_matrices

# Act like EMBOSS Needle
aligner = Align.PairwiseAligner()
aligner.mode = "global"
aligner.open_gap_score = -10
aligner.extend_gap_score = -0.5
aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")
seq1 = 'HWLEKNFSKRUKKTRLAG'
seq2 = 'HWLEKNFSKRUKKTRLAG'
aligner.align(seq1, seq2)  # raise exception
```

**Comment by mdehoon** [comment]
The next release of Biopython adds a `select` method to create a new matrix from an existing one. This will allow you to select the letters of the matrix you want to keep, but also to add new letters. Then you can do
```
matrix = substitution_matrices.load("BLOSUM62")
matrix = matrix.select(matrix.alphabet + "U")
aligner.substitution_matrix = matrix
```
By default, the score will be zero; you can set it to some other value before using the aligner.
If you want to use this feature now, you could grab it from the Biopython github site.

**Comment by ccwang002** [comment]
I can confirm it works! Thank you!!

Here's the output using the developmental version of biopython(`52c01e5`):

```python
>>> aligner.align(seq1, seq2)[0].score
93.0
>>> aln = aligner.align(seq1, seq2)[0]
>>> print(aln)
HWLEKNFSKRUKKTRLAG
||||||||||||||||||
HWLEKNFSKRUKKTRLAG
```
