### ISSUE TITLE
read ACE files  alignement

### ISSUE THREAD

**Issue by simonjuleseric2** [biopython/biopython#3207]
### Setup

I am reporting a problem with Biopython version 1.76, Python version 3.7.7, and operating
system as follows:

### Expected behaviour

Shown in this exemple:

https://biopython.org/wiki/ACE_contig_to_alignment

### Actual behaviour
ModuleNotFoundError: No module named 'Bio.Align.Generic'

### Steps to reproduce

(*Please fill this in *)
from Bio.Align.Generic import Alignment

**Comment by peterjc** [comment]
That old example needs quite a lot of updates... does the ACE support in Bio.SeqIO cover your immediate needs? https://biopython.org/wiki/SeqIO

**Comment by peterjc** [comment]
I've updated the example, the website should update in a few minutes. It should now start:

```python
from Bio.Sequencing import Ace
from Bio.Align import MultipleSeqAlignment
```

Does that work for you now?

**Comment by simonjuleseric2** [comment]
Yes it works now, thanks
