### ISSUE TITLE
Atom object has no attribute atom.disordered_get_list when saving PDB file

### ISSUE THREAD

**Issue by Minys233** [biopython/biopython#3213]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
3.8.5 (default, Aug  5 2020, 08:36:46) 
[GCC 7.3.0]
CPython
Linux-5.4.0-42-generic-x86_64-with-glibc2.10
1.77

### Expected behaviour

`PDBIO.save()` function should save a `Chain` object normally.

### Actual behaviour
The function failed on calling `atom.disordered_get_list()` on some proteins. For example, `pdb/ah/pdb1ah7.ent.gz`, which was directly downloaded from RCSB PDB. 

```bash
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    io.save('test.pdb')
  File "/home/minys/.conda/envs/bio/lib/python3.8/site-packages/Bio/PDB/PDBIO.py", line 339, in save
    for atom in residue.get_unpacked_list():
  File "/home/minys/.conda/envs/bio/lib/python3.8/site-packages/Bio/PDB/Residue.py", line 88, in get_unpacked_list
    undisordered_atom_list += atom.disordered_get_list()
AttributeError: 'Atom' object has no attribute 'disordered_get_list'
```

### Steps to reproduce
To run this piece of code, please download `pdb1ah7.ent.gz` in advance, for simplicity, here PDBList is not used. The task is to save a protein chain into an individual file.

This issue may be related to #455 , which seems not fixed yet.

```python
from Bio.PDB import PDBIO, PDBParser
import gzip

pdb_file = '/data/pdb/ah/pdb1ah7.ent.gz'
pdbparser = PDBParser()
target = pdbparser.get_structure('id', gzip.open(pdb_file, 'rt'))[0]['A']
io = PDBIO()
io.set_structure(target)
io.save('test.pdb')
```

**Comment by peterjc** [comment]
@JoaoRodrigues are you able to look at this?

**Comment by JoaoRodrigues** [comment]
Will do.

**Comment by JoaoRodrigues** [comment]
Will write here as I work through the issue. Hopefully we can close this and other related issues once and for all...

The issue here is that when PDBIO rebuilds the full SMCRA model (we're only giving it a chain here), it loses the DisorderedAtom objects. They become simple Atom objects. This happens on `Entity.copy`.
