### ISSUE TITLE
SeqIO error: local variable 'qual' referenced before assignment

### ISSUE THREAD

**Issue by khp1** [biopython/biopython#3221]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]

import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Windows-10-10.0.18362-SP0

import Bio; print(Bio.__version__)
1.76
```

### Expected behaviour

I send some samples for Sanger sequencing to a commercial facility. I'm able to read the files they send using the command
```
from Bio import SeqIO
from Bio import Seq
rec = SeqIO.read("isolation-round4/3dr23_Forward.ab1",'abi-trim').seq
```

This worked fine until now. 
### Actual behaviour
But recently, due to a move, we had to send the samples elsewhere for sequencing. Now, if I try to run the same command on the files they send to me, I get an error:
``UnboundLocalError: local variable 'qual' referenced before assignment    in
  File "C:\Users\Anaconda3\lib\site-packages\Bio\SeqIO\AbiIO.py", line 462, in AbiIterator
    letter_annotations={"phred_quality": qual}``

### Steps to reproduce

I have uploaded two files, one that works with the above code and one that does not.  They can be downloaded here: [https://easyupload.io/m/k2f60x](url) 

I posted this problem on Biostars ([https://www.biostars.org/p/455577/#455598](url)) and was told to open an issue here. I had also posted it on Stackoverflow ([https://stackoverflow.com/questions/63420626/biopython-seqio-error-local-variable-qual-referenced-before-assignment](url))

This is my first time opening an issue here, so please let me know if you need any more information from me. 
I would appreciate any help with this!
Thank you.

**Comment by peterjc** [comment]
I think this was fixed in #1037, can you try Biopython 1.77 please?

**Comment by khp1** [comment]
I upgraded it to 1.77, but still get the same error. :(

**Comment by peterjc** [comment]
Ah. I was hoping this would be very easy. On the bright side, your example breaks for me too (macOS):

```
$ python -c "from Bio import SeqIO; print(SeqIO.read('Works.ab1', 'abi').seq)"
NNCTACGGTAGGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGCAGGCGGTTCGGAAAGAAAGATGTGAAATCCCAGAGCTTAACTTTGGAACTGCATTTTTAACTACCGAGCTAGAGTGTGTCAGAGGGAGGTGGAATTCCGCGTGTAGCAGTGAAATGCGTAGATATGCGGAGGAACACCGATGGCGAAGGCAGCCTCCTGGGATAACACTGACGCTCATGCACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCCGGTAGTCCGGCTGACTGACTTAGCTCGTAACTATCTCGTATGCCGTCTTTCTGCTTGAGA
```

And,

```
$ python -c "from Bio import SeqIO; print(SeqIO.read('Doesnotwork.ab1', 'abi').seq)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/site-packages/Bio/SeqIO/__init__.py", line 656, in read
    record = next(iterator)
  File "/Users/xxx/site-packages/Bio/SeqIO/Interfaces.py", line 71, in __next__
    return next(self.records)
  File "/Users/xxx/site-packages/Bio/SeqIO/AbiIO.py", line 444, in iterate
    letter_annotations={"phred_quality": qual},
UnboundLocalError: local variable 'qual' referenced before assignment
```

**Comment by peterjc** [comment]
Interesting. The problem file does not have the PCON2 field (or the PCON1 field) for quality scores - only:

``['AEPt1', 'AEPt2', 'ASPt1', 'ASPt2', 'B1Pt1', 'B1Pt2', 'CMNT1', 'CTTL1', 'DATA1', 'DATA2', 'DATA3', 'DATA4', 'DATA5', 'DATA6', 'DATA7', 'DATA8', 'DATA9', 'DATA10', 'DATA11', 'DATA12', 'EVNT1', 'EVNT2', 'EVNT3', 'EVNT4', 'FWO_1', 'LANE1', 'LIMS1', 'MCHN1', 'MODL1', 'NAVG1', 'NLNE1', 'PBAS1', 'PBAS2', 'PDMF1', 'PDMF2', 'PLOC1', 'PLOC2', 'RUND1', 'RUND2', 'RUND3', 'RUND4', 'RUNT1', 'RUNT2', 'RUNT3', 'RUNT4', 'RevC1', 'S/N%1', 'SMPL1', 'SPAC1', 'SPAC2', 'SPAC3', 'SVER1', 'SVER2', 'SVER3', 'THUM1', 'THUM2']``

The following patch "works" in that you can parse the file and get a sequence, but I'd like to know what is different here:

```
$ git diff
diff --git a/Bio/SeqIO/AbiIO.py b/Bio/SeqIO/AbiIO.py
index 89c3a391f..1a0c3e90a 100644
--- a/Bio/SeqIO/AbiIO.py
+++ b/Bio/SeqIO/AbiIO.py
@@ -382,6 +382,7 @@ class AbiIterator(SequenceIterator):
         sample_id = "<unknown id>"
 
         raw = {}
+        seq = qual = sample_id = None
         for tag_name, tag_number, tag_data in _abi_parse_header(header, handle):
             key = tag_name + str(tag_number)
 
@@ -441,8 +442,10 @@ class AbiIterator(SequenceIterator):
                 name=file_name,
                 description="",
                 annotations=annot,
-                letter_annotations={"phred_quality": qual},
             )
+        if qual:
+            # Expect this to be missing for FSA files.
+            record.letter_annotations["phred_quality"] = qual
 
         if self.trim and not is_fsa_file:
             record = _abi_trim(record)
```

Presumably the second sequencing centre have their ABI machine setup differently... but how and why?

Can you take a look please @bow?

**Comment by bow** [comment]
@peterjc It looks like indeed [this if clause is never hit](https://github.com/biopython/biopython/blob/19f72932e1ed7e4e035a0f12dc1074f91aca5a53/Bio/SeqIO/AbiIO.py#L394), which means qual is never defined, and so the fix works.

But as to why the sequencing machine did not add the quality information to the file, it seems to be something you need to cross-check with the sequencing provider @khp1.

I haven't worked with Sanger sequencing machines for a while now, but all non-FSA format ABIF files (that is, all `*.ab1`) format that I have seen have the quality information for each base calls. This assumption underlies the parser as well (i.e. if it's an `.ab1` file, it must have quality values), which is why the parser now breaks and you're seeing the error.

If it is indeed possible (perhaps newer generation machines?) to create `.ab1` files, perhaps other parts of the parser need to be updated as well.

**Comment by peterjc** [comment]
@bow Should I turn that patch into a pull request?

**Comment by khp1** [comment]
Thank you! I will check with the sequencing facility as to why the quality was not included.

**Comment by khp1** [comment]
The sequencing facility told me that the files they sent were manually edited to only have high quality data and that's why the quality information is not available. They told me to specifically request for unedited files in future.
