### ISSUE TITLE
StructureBuilder cannot handle non-canonical altloc ordering written by PDBIO

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#3231]
Parsing a PDB file with disordered atoms where the first instance of the disordered atom has a non-blank altloc but other instances are blank fails - second instance is ignored.  See this example:

 - PDB 5j2u, line 10598: No altloc in first instance of disordered atom H (goes from blank to `B`):
```
ATOM   9132  N   SER B 155      30.962  53.255  26.071  1.00 48.84           N
ATOM   9133  CA  SER B 155      32.293  52.794  26.445  1.00 56.65           C
ATOM   9134  C   SER B 155      33.375  53.714  25.883  1.00 50.84           C
ATOM   9135  O   SER B 155      34.387  53.970  26.534  1.00 53.74           O
ATOM   9136  CB  SER B 155      32.510  51.365  25.951  1.00 57.00           C
ATOM   9137  OG  SER B 155      33.470  50.690  26.748  1.00 59.12           O
ATOM   9138  H   SER B 155      30.485  52.658  25.676  1.00 58.61           H
ATOM   9139  H  BSER B 155      30.485  52.658  25.676  0.00 58.61           H
ATOM   9140  HA  SER B 155      32.369  52.794  27.412  1.00 67.98           H
ATOM   9141  HB2 SER B 155      31.669  50.885  26.004  1.00 68.40           H
ATOM   9142  HB3 SER B 155      32.815  51.390  25.032  1.00 68.40           H
ATOM   9143  HG  SER B 155      33.579  49.907  26.465  1.00 70.94           H
```

PDBParser will do its job right, but then PDBIO will place atom 9139 before 9138, which mangles the round-trip parsing. Looking into `StructureBuilder`, it seems the logic behind the disordered atoms could use some improvement since it checks directly for a non-blank altloc code. Although this is not 'canonical' PDB format, it's a tiny improvement to our parser to make it more robust. We should also maybe add some logic to PDBIO to write blank altlocs first, and then named ones - fixing the problem from both ends.

**Comment by JoaoRodrigues** [comment]
It was easier to simply add a sorting call to `DisorderedAtom`.

**Comment by jgreener64** [comment]
Sounds sensible, though that PDB entry looks pretty dodgy since the atoms 9138/9139 have the same coordinates. I sent a comment to the PDB about it, they sometimes amend entries.

**Comment by JoaoRodrigues** [comment]
And 0 occupancy for altloc B... Thanks!

**Comment by jgreener64** [comment]
5J2U will be amended in next week's PDB release to remove the rogue atom.
