### ISSUE TITLE
Extract Molecule information

### ISSUE THREAD

**Issue by Chokerino** [biopython/biopython#3234]
Hello,

Is there any way to extract info/names of the molecules present for a pdb id except for the one explicitly mentioned as entities? For example for [4u0g](https://www.rcsb.org/structure/4U0G) is shows various small molecules but they are not so easy to extract from the pdb.

**Comment by JoaoRodrigues** [comment]
@Chokerino what do you mean by info/names of molecules? Do you mean ligands?

**Comment by Chokerino** [comment]
Yes ligands and other molecules and I found the the pdbe API from ebi.
Sorry forgot to close the issue.

Coordinator | BioBytes
Btech Undergrad '22 IIITD

**Comment by JoaoRodrigues** [comment]
I still don't understand your question. Can you give me a precise example of what you are looking for?

You can use our parsers to read the PDB/mmCIF files and then you have access to all the coordinates/information. The headers are not parsed completely however. If you would be looking for ligands you could do something like:

```python
from Bio.PDB import PDBParser

p = PDBParser()
s = p.get_structure('4u0g', '4u0g.pdb')  # you have to download the structure first somehow

# iterate and print residue names of HETATM records, usually ligands
for res in s.get_residues():
    if res.id[0] != " ":
        print(res.resname)
```

**Comment by Chokerino** [comment]
I was looking for all molecules that are bound to the complex and this is
not generally available in the header of a pdb.

Coordinator | BioBytes
Btech Undergrad '22 IIITD

**Comment by Chokerino** [comment]
I was looking for all molecules that are bound to the complex and this is
not generally available in the header of a pdb. Thanks for your help though.

**Comment by JoaoRodrigues** [comment]
OK, then you might be interested in doing distance calculations. If you know the protein chains, you can figure out which other residues are close by using `NeighborSearch`. Taking the example above:

```python
from Bio.PDB import (
    NeighborSearch,
    PDBParser,
    Polypeptide
)

# Read in PDB file
p = PDBParser()
s = p.get_structure('4u0g', '4u0g.pdb')  # you have to download the structure first somehow

# Find protein chains
protein_chains = set()
aanames = set(Polypeptide.standard_aa_names)
for chain in s.get_chains():
    for res in chain:
        if res.name in aanames:
            protein_chains.add(chain.id)
            break

# Search for neighbors
ns = NeighborSearch(list(s.get_atoms()))
for chain in s.get_chains():
    if chain.id not in protein_chains:  # is ligand
        for lig in chain:
            lig_atom = res.child_list[0]  # random atom, not ideal but...
            neighbors = ns.search(lig_atom, radius=10.0, level='C')  # ...large cutoff of 10A should make up for it
            for n in neighbors:
                if n.id in protein_chains: 
                    print(f'Ligand {res.resname} of chain {chain.id} is close to protein chain {n.id})
```

**Comment by rob-miller** [comment]
I think what he's looking for is a way to list the HETATMs (not every atom
but each entity).  Like for 4u0g something like HOH, SO4, ZIL ?
Not sure how to do that from Biopython structures though.

**Comment by Chokerino** [comment]
@rob-miller yes that's what I was looking for. I found the PDBe API much easier so I just went ahead with that.

**Comment by JoaoRodrigues** [comment]
Then my first reply is the best we can do. It lists residue names, so it'll print, HOH, SO4, etc.
