### ISSUE TITLE
biopdb_faq.pdf not updated?

### ISSUE THREAD

**Issue by rob-miller** [biopython/biopython#3238]
Copies of 'The Biopython Structural Bioinformatics FAQ' do not seem to be updated on the web.  [pdf](http://biopython.org/DIST/docs/tutorial/biopdb_faq.pdf) and [html](https://biopython.org/wiki/The_Biopython_Structural_Bioinformatics_FAQ) do not reflect e.g. #2400, #2874, or  382831b .  
Sorry if I'm looking at something irrelevant or cached?

**Comment by peterjc** [comment]
Looks like an oversight. It needs to be added explicitly to https://biopython.org/wiki/Building_a_release along side updating the tutorial (pull request welcome).

You could build it locally (the Makefile covers this) and submit a pull request to https://github.com/biopython/DIST/blob/gh-pages/docs/cookbook/biopdb_faq.pdf ?

**Comment by JoaoRodrigues** [comment]
I would also be happy to go over it soon and rewrite/update certain parts that are outdated. Or should we just merge most of this content into the Tutorial?

**Comment by peterjc** [comment]
I would prefer to have it all in one place, and since both are written in LaTeX, the Tutorial seems best.

As to updating the PDB FAQ on website in the short term, I'd suggest building it as of the last release?

**Comment by peterjc** [comment]
OK, that's the current copy on the website updated & the procedure for releases updated to include it in future releases. Closing this issue, thank you!
