### ISSUE TITLE
 How to retrieve Header of blast from XML format result

### ISSUE THREAD

**Issue by Huangzhiqang** [biopython/biopython#3239]
Hello,

I have obtained XML format BLAST result with local blastn program. I know  NCBIXML.read or NCBIXML.parse can be used to parse BLAST xml format output, but it seems that NCBIXML.read or NCBIXML.parse can not extract Header of blast result.
So, are there other ways to retrieve header from XML file?
result_handle = open("blastn.xml","r")
blast_record = NCBIXML.read(result_handle)
print type(blast_record)  # class 'Bio.Blast.Record.Blast'
![image](https://user-images.githubusercontent.com/52337195/91555295-524c7d00-e963-11ea-9c08-a34378314a3a.png)

**Comment by peterjc** [comment]
Have you tried ``dir(blast_record)``? The header attributes are there on the blast object which inherits from multiple classes - see https://github.com/biopython/biopython/blob/biopython-177/Bio/Blast/Record.py#L442

Example:

```pycon
>>> from Bio.Blast import NCBIXML
>>> with open("xml_2900_tblastx_001.xml") as handle:
...     record = NCBIXML.read(handle)
... 
>>> record.database
'nr'
>>> record.application
'TBLASTX'
```

See also the BLAST XML support in SearchIO which uses a different object model intended to work with other pairwise comparison tools.

**Comment by Huangzhiqang** [comment]
I am a new for python and Biopython, thank you for your patience, this really resolved my problem!
