### ISSUE TITLE
 Bio/Medline/__init__.py  - textkeys list issue

### ISSUE THREAD

**Issue by azurele** [biopython/biopython#3241]
### Setup

I am reporting a problem with Biopython latest version with the "Bio/Medline/__init__.py file 

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
CPython
Linux-4.15.0-1050-azure-x86_64-with-Ubuntu-18.04-bionic
1.77

Line number 127 in the python notebook assigns a list of values to the textkeys variable which seems to have only have 34 values. But from the PubMed/Medline data description - [https://www.nlm.nih.gov/bsd/mms/medlineelements.html](https://www.nlm.nih.gov/bsd/mms/medlineelements.html) there are more than 34 values that can be parsed. This will limit the functionality of the code to only the listed values and other values can't be parsed from a Medline object.

(*Please fill this in*)

### Actual behaviour

textkeys = (
        "ID",
        "PMID",
        "SO",
        "RF",
        "NI",
        "JC",
        "TA",
        "IS",
        "CY",
        "TT",
        "CA",
        "IP",
        "VI",
        "DP",
        "YR",
        "PG",
        "LID",
        "DA",
        "LR",
        "OWN",
        "STAT",
        "DCOM",
        "PUBM",
        "DEP",
        "PL",
        "JID",
        "SB",
        "PMC",
        "EDAT",
        "MHDA",
        "PST",
        "AB",
        "EA",
        "TI",
        "JT",
    )

### Steps to reproduce
Open the below link
[https://github.com/biopython/biopython/blob/6a4faac53be9fe78e16df2fcd991209116c5607a/Bio/Medline/__init__.py](https://github.com/biopython/biopython/blob/6a4faac53be9fe78e16df2fcd991209116c5607a/Bio/Medline/__init__.py)
Line number 127, textkeys assignment lists the values.

**Comment by peterjc** [comment]
I believe you are mistaken, the list ``textkeys`` values (a tuple not a list) is merely those which are known to be text based and concatenated together as a single string versus treated as a list.

I suggest you give a concrete example with a specific record and the URL to get it, along with the output and any fields you see are missing.

**Comment by azurele** [comment]
My bad, it's a tuple. Closing the issue.
