### ISSUE TITLE
Improve version string of development versions

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#3243]
Given the somewhat long periods of time between releases, there might be a substantial number of users (and developers) using git versions of Biopython. As such, it would be nice to adopt a more precise version scheme for the development git version. For instance, instead of `1.78,dev0`, we could have `1.78.123abc` where `123abc` is the latest commit hash. This is a compromise between keeping the current version scheme and a full transition to semantic versioning. Since releases are done manually, we could control those version changes manually as well.

I've looked a bit into this (and implemented something similar in another repo of mine - [here](https://github.com/haddocking/pdb-tools/blob/master/.github/workflows/bump-version-on-push.yml)). StackOverflow has a couple of nice answers, namely [this one](https://stackoverflow.com/questions/5581722/how-can-i-rewrite-python-version-with-git). 

We could have a github action running after each commit to the `master` branch to automatically update the version tag for us. In principle, this is completely independent and automated so it wouldn't bother other parts of our pipeline, either CI or add overhead to our own local development workflow.

Thoughts? @peterjc @mdehoon and others?

**Comment by peterjc** [comment]
I didn't get what you meant about automatic version tagging - currently tagging a version in git is quite a deliberate action as part of our release process.

Git hashs are not going to sort chronologically (and are not https://www.python.org/dev/peps/pep-0440/ compliant), but if you are not suggesting releasing those on PyPI it might not be a big issue? I can see this being useful if lots of people were installing from git and reporting issues against a cutting edge release - but Biopython developers aside, do many people do that?

I would much rather do more frequent releases - and the improvements to the release process in theory make that easier. https://github.com/biopython/biopython-wheels/issues/6 is probably the only thing holding up the release of Biopython 1.78 which Michiel and I had agreed to try to do in August.

**Comment by JoaoRodrigues** [comment]
Sorry id I wasn't clear. I meant it would be nice to have an automated way to add a commit hash (or any identifiable number really) to the development version number. Right now it's impossible to know what codebase `1.78.dev0` refers to without additional info.

Git hashes would not sort chronologically but they are unique so we would know exactly which version we were talking about. And yes, I meant to use this just for development, not for PyPI. But it indeed does break PEP440.. `git describe` actually gives a pretty string to identify the version: `biopython-177-398-gdb43482c7`, where 177 is the last release, 398 is the number of commits since then, and then is g+latest commit hash. What if we use this number of commits after latest release after `dev` in the version? That's chronological and would be easy to find the right commit to reproduce issues.

I agree that more frequent releases would be great by the way - not sure how to help here though.
