### ISSUE TITLE
Add unicode support to pairwise alignment

### ISSUE THREAD

**Issue by zl-zhou** [biopython/biopython#3254]
Hello! I know that this package is primarily for biologists, but I'm a linguist and couldn't help but wish that I could use your alignment algorithms to answer some questions I've had recently. Would it be possible to add unicode support to the strings that pairwise2 can align — strings like "mɛɾɪtʰəreniən" — as well as to penalty matrices?

**Comment by mdehoon** [comment]
See section 6.6.2.9  in the Biopython tutorial for generalized pairwise alignments.
