### ISSUE TITLE
Can't output to .genbank file after parsing from FASTA in Bio.SeqIO

### ISSUE THREAD

**Issue by Bhuvanesh09** [biopython/biopython#3259]
### Setup

I am reporting a problem with Biopython 1.78, Python 3.7, and operating
system Ubuntu 18.04 as follows:

```python
from Bio import SeqIO
records = SeqIO.parse("batCov.fasta", "fasta")
SeqIO.write(records,"try2.gb", "gb")
```

### Expected behaviour

Should successfully write to genBank file.

### Actual behaviour

Throws the following error
![image](https://user-images.githubusercontent.com/16082479/92332282-5894d480-f09a-11ea-80a3-2af20c7fdbdf.png)

### Steps to reproduce

Just run the code attached above

**Comment by peterjc** [comment]
This is expected, the GenBank format needs to know DNA vs RNA vs Protein. How you specify this depends on the version of Biopython and changed in 1.78, see also example on https://biopython.org/wiki/Alphabet

Shortest alternative, assuming DNA here:

```python
from Bio import SeqIO
SeqIO.convert("batCov.fasta", "fasta", "try2.gb", "gb", "DNA")
```
