### ISSUE TITLE
Get EC number from a Bio.KEGG.KGML.KGML_pathway object

### ISSUE THREAD

**Issue by iquasere** [biopython/biopython#3260]
Greetings!

I am attempting to retrieve the EC numbers from a Bio.KEGG.KGML.KGML_pathway object. The closest I have come to was getting the name of the graphics with 
```
mmap = KGML_parser.read(kegg_get("ko00010", "kgml"))
mmap.orthologs[0].graphics[0].name
``` 
but this gives me the KO: ```'K01623...'```
I wanted to know if somewhere in this object are there the EC numbers directly available. I know I can convert to EC numbers with the KEGG API, but that doesn't return me EC numbers for all KOs.

Thank you for your attention, and for an amazing tool!

**Comment by peterjc** [comment]
Have you looked at the raw file to see if the information you want is there? I've only dabbled with KEGG so don't know the answer. @widdowquinn might be able to advise.

**Comment by iquasere** [comment]
You mean the raw KGML, right? It is not there. However, everything is there, so My guess is that that information is really not obtainable through the KGML_pathway object

**Comment by widdowquinn** [comment]
Hi - I don't think KEGG gives you that information directly in all maps. The `REST.kegg_link()` function might be useful to you:

```python
>>> from Bio.KEGG.REST import kegg_link
>>> kegg_link("enzyme", "K01623").read()
'ko:K01623\tec:4.1.2.13\n'
>>> kegg_link("enzyme", "rn:R01070").read()
'rn:R01070\tec:4.1.2.13\n'
```

So it should be possible to iterate over each reaction in the map, and link to the EC number in this way:

```python
for rxn in mmap.reaction_entries:
    try:
        print(kegg_link("enzyme", rxn.reaction).read())
    except:
        rxns = rxn.reaction.split()
        for _ in rxns:
            print(kegg_link("enzyme", _).read())
```

There are a couple of things to watch out for: some reactions have multiple `rn:RNNNNN` entries, which is a problem for `kegg_link()` if you don't split before you search; many reactions will return multiple EC numbers from the KEGG enzyme database. But I hope this helps!

**Comment by iquasere** [comment]
Wow, it seems all KOs in the pathways have EC numbers! If there are multiple ECs, it is more problematic, but maybe it will be possible to put two or three in a box. Otherwise, just the first or a random, they will likely point to the same functionallity, as I have seen very different EC numbers point to the same function. 

Thank you very much to you both!

**Comment by widdowquinn** [comment]
Glad to be of help!

FWIW, it's worth keeping in mind that each EC number refers to a specific kind of chemical interconversion, rather than "enzyme function" - an enzyme may catalyse multiple distinct reactions, and enzymes with different "function" may catalyse the same chemical reaction/EC number. I'd argue that it's usually best to label with all values, rather than choose one from a group.

**Comment by iquasere** [comment]
Will have to adapt the font size for those multiple EC numbers xD One per box is just so clean...
