### ISSUE TITLE
convert doesn't close files when done

### ISSUE THREAD

**Issue by theitush** [biopython/biopython#3264]
looks like convert should be given file handles and not file paths as it doesn't close the files when done.
This is in contrast with [the documentation](https://biopython.org/wiki/SeqIO)

Easiest fix would be to change the documentation to reflect that convert should get handles instead of files.
A better solution would be to make sure that it closes the files it opens.

**Comment by peterjc** [comment]
It should be closing the handles. Can you provide more details of how you are testing this please.

**Comment by peterjc** [comment]
Sorry, let me clarify:

If you give it a filename it should open and close the handle internally.

If you give it a handle, you should close it (e.g. using a with statement)

**Comment by theitush** [comment]
yeah sorry looks like it was a mistake on my side!

thanks for the (slightly too) quick reply!

**Comment by peterjc** [comment]
No problem - always happy to get feedback on possible bugs or things that could be clearer in the documentation. Thanks.
