### ISSUE TITLE
MultipleSeqAlignment object from numpy array

### ISSUE THREAD

**Issue by turovapolina** [biopython/biopython#3270]
Dear @team,

Thank you very much for you wonderful module! I am a new user and I am trying to create a phylogenetic tree from my data (which is in numeric format and presented in numpy array).
Unfortunately I didn't found any example of numpy arrays transformation into MultipleSeqAlignment objects.
When I am trying to use MultipleSeqAlignment() function it produces a mistake like this:
![image](https://user-images.githubusercontent.com/61549119/92935654-be45df80-f451-11ea-9660-b5083479f916.png)

I am not sure if biopython is able to work with numpy arrays, but it seems to be applicable because in this case distance matrix also can be calculated and fed to the tree constructor.

I also had a look at previous issues and only found question about converting Seq into the numeric format (like issue #1474).

Could you please give me advice regarding my case?
Thank you very much in advance!

Best regards,
Polina

**Comment by turovapolina** [comment]
Dear @peterjc,

Thank you for your answer!
The problem is that my data is presented in float numbers, so there is no opportunity to turn it into letters.
It just seems to me that the whole idea of phylogenetic trees is suitable for my case because I am trying to build some hierarchy across my samples.
Does it mean that unfortunately float type of my data is not suitable at all for the biopython library at all?

Best regards,
Polina

**Comment by peterjc** [comment]
My knowledge in this area is very limited - the only examples I've seen had information encoded in a single letter (or digit).

Have you tried building a floating point distance matrix and used that with ``Bio/Phylo/TreeConstruction.py`` directly?

**Comment by turovapolina** [comment]
Dear @peterjc,

I thought that I am able to create an object from class Bio.Phylo.TreeConstruction.DistanceMatrix only from MSA object, but this was a mistake!
I successfully created DistanceMatrix from distances calculated by scipy module and drew my tree.
Thank you very much!

Best regards,
Polina Turova
