### ISSUE TITLE
PDBParser and MMCIFParser assign HETATM ids differently

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#3272]
This issue comes from the benchmark in #3230. 

The first item in the residue id of HETATMs is `"H_" + res.resname`. Because the PDB format is a column-delimited format, we don't strip the empty spaces around residue names with less than 3 characters (e.g. MG) and end up with something like `H_ MG` in the id. The MMCIFParser, on the other hand, does strip this whitespace so we end up with `H_MG` for the same atom. This discrepancy makes it impossible to compare two structures in mmCIF and PDB formats - we get a lot of "mismatches".

A simple fix would be to strip the whitespace of the residue name in PDBParser and, if necessary, adapt PDBIO to pad/align residue names accordingly when writing to file.

I'm leaving this open for a little bit with a tag for newcomers since it's not a pressing issue and might be a good first issue for people looking into contributing to open-source.

Small test sample:

model.cif
```
data_1VQL
# 
loop_
_atom_site.group_PDB 
_atom_site.id 
_atom_site.type_symbol 
_atom_site.label_atom_id 
_atom_site.label_alt_id 
_atom_site.label_comp_id 
_atom_site.label_asym_id 
_atom_site.label_entity_id 
_atom_site.label_seq_id 
_atom_site.pdbx_PDB_ins_code 
_atom_site.Cartn_x 
_atom_site.Cartn_y 
_atom_site.Cartn_z 
_atom_site.occupancy 
_atom_site.B_iso_or_equiv 
_atom_site.pdbx_formal_charge 
_atom_site.auth_seq_id 
_atom_site.auth_comp_id 
_atom_site.auth_asym_id 
_atom_site.auth_atom_id 
_atom_site.pdbx_PDB_model_num 
HETATM 91426 MG MG    . MG  XL 33 .    ? 27.783  125.521 83.164  1.00 41.37  ? 8109 MG  Y MG    1 
#
```

model.pdb
```
HETATM91458 MG    MG Y8109      27.783 125.521  83.164  1.00 41.37          MG  
```

script.py
```python
from Bio.PDB import PDBParser, MMCIFParser

p_pdb = PDBParser(QUIET=1)
p_cif = MMCIFParser(QUIET=1)

s_pdb = p_pdb.get_structure("", "model.pdb")
s_cif = p_cif.get_structure("", "model.cif")

atom_pdb = [a for a in s_pdb.get_atoms()][0]
atom_cif = [a for a in s_cif.get_atoms()][0]

assert atom_pdb.get_full_id() == atom_cif.get_full_id()  # this should be True.
```

**Comment by sgalpha01** [comment]
Hello, can I handle this issue?

**Comment by JoaoRodrigues** [comment]
Hi @sgalpha01,

Of course! Let me add a small example to reproduce the problem to the issue.

**Comment by sgalpha01** [comment]
@JoaoRodrigues ,  this is a kind of quickfix. I am not sure if this is sufficient.

**Comment by sgalpha01** [comment]
``` Python3
from Bio.PDB import PDBParser, MMCIFParser

p_pdb = PDBParser(QUIET=1)
p_cif = MMCIFParser(QUIET=1)

s_pdb = p_pdb.get_structure("", "model.pdb")
s_cif = p_cif.get_structure("", "model.cif")

atom_pdb = [a for a in s_pdb.get_atoms()][0]
atom_cif = [a for a in s_cif.get_atoms()][0]

assert atom_pdb.get_full_id() == atom_cif.get_full_id()  # this should be True.
```

This script is now working fine, but it broke something else as shown by [appveyor](https://ci.appveyor.com/project/biopython/biopython/builds/35177337) and [travis-ci](https://travis-ci.org/github/biopython/biopython/builds/726755974) checks.
