### ISSUE TITLE
TypeError in "SummaryInfo._get_column_info_content"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [biopython/biopython#3292]
Hello,

While analyzing biopython on SonarCloud I saw what looks like an error in [`Bio/Align/AlignInfo.py`](https://github.com/biopython/biopython/blob/05107f5cfd1f8d67dbc4d472268618f2b6d93bc2/Bio/Align/AlignInfo.py#L490):

<img width="1824" alt="Screenshot 2020-10-02 at 18 12 39" src="https://user-images.githubusercontent.com/40498978/94945494-0b5e2400-04db-11eb-85b1-2bd4ead4dcf5.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_biopython&issues=AXTqE7oaA4gH5cbKom8q&open=AXTqE7oaA4gH5cbKom8q).

I don't know what the developer expected to do, but the `-` operator cannot be called on two lists. If this code is reached it will raise the following exception:
```
TypeError: unsupported operand type(s) for -: 'list' and 'list'
```

In case you want to scan biopython on SonarCloud [you can use a configuration similar to this one](https://github.com/nicolas-harraudeau-sonarsource/biopython/commit/9952e28e9c411a626620a78993fd9af8d24dd9ab) when you enable automatic analysis. SonarCloud is free for open source projects.

**Comment by peterjc** [comment]
Wow. The bug dates back 20 years to 4b5a86bdaac511c4dd0d9211c9b478e30662c605

Probably we need something like this:

```python
raise ValueError(f"Frequency table provided does not contain observed letter {key}")
```

Does that make sense to you?

**Comment by nicolas-harraudeau-sonarsource** [comment]
HI @peterjc,

Thanks for answering so rapidly.
The message you suggest matches what I understand of the function and current exception, but in all honesty I am not familiar with this code base.

At SonarSource, the company which created SonarQube/SonarCloud/SonarLint, we analyze the code of popular open source projects to make sure we find valid issues and raise no false positives. Biopython is one of the projects we analyze. I saw this bug and reported it as best I could. I can explain the problem as I am myself a python developer, but I can't be sure that the fix is valid in this case.

**Comment by peterjc** [comment]
Understood. If you want to submit a pull request, that'd be welcome. Otherwise I'll try to make the proposed fix next week.

The fact we never noticed the bug means our unit test coverage doesn't trigger this exception. It should be fairly easy to add that too...
