### ISSUE TITLE
"__getitem__" called by mistake on "_codons2re" function

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [biopython/biopython#3293]
Hello,

While analyzing biopython on SonarCloud I saw what looks like two similar errors in `Bio/codonalign/__init__.py`: [here](https://github.com/biopython/biopython/blob/05107f5cfd1f8d67dbc4d472268618f2b6d93bc2/Bio/codonalign/__init__.py#L609) and [here](https://github.com/biopython/biopython/blob/05107f5cfd1f8d67dbc4d472268618f2b6d93bc2/Bio/codonalign/__init__.py#L675):

<img width="1613" alt="Screenshot 2020-10-03 at 16 08 21" src="https://user-images.githubusercontent.com/40498978/94993700-27bd9780-0593-11eb-9d5c-3c5f9cacd887.png">

<img width="1613" alt="Screenshot 2020-10-03 at 16 10 53" src="https://user-images.githubusercontent.com/40498978/94993709-3015d280-0593-11eb-98b7-b479a44c2852.png">

You can see the corresponding issue in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_biopython&issues=AXTqE7kmA4gH5cbKom2x&open=AXTqE7kmA4gH5cbKom2x) and [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_biopython&issues=AXTqE7kmA4gH5cbKom2y&open=AXTqE7kmA4gH5cbKom2y).

The problem is that `_codons2re` [is a function](https://github.com/biopython/biopython/blob/05107f5cfd1f8d67dbc4d472268618f2b6d93bc2/Bio/codonalign/__init__.py#L203), thus it is not subscriptable, i.e. you can't call `__getitem__` on it. The developer probably meant to use parentheses instead of square brackets [as it is the case here](https://github.com/biopython/biopython/blob/05107f5cfd1f8d67dbc4d472268618f2b6d93bc2/Bio/codonalign/__init__.py#L242-L243). Reaching this code will raise the following exception:
```
TypeError: 'function' object is not subscriptable
```

In case you want to scan biopython on SonarCloud [you can use a configuration similar to this one](https://github.com/nicolas-harraudeau-sonarsource/biopython/commit/9952e28e9c411a626620a78993fd9af8d24dd9ab) when you enable automatic analysis.

**Comment by peterjc** [comment]
Problem dates back 7 years, 8df9bcae42eda5c8f1bd574fa49f3e3dddffddd7 - looks like no one triggered this in all that time?

Pretty sure it should just be round brackets - do you agree @zruan ?

**Comment by zruan** [comment]
I submit a pull request to fix this issue. There is another bug in which the `complete_protein` option is set to False, so that the code calling `_codons2re` never got used. This is also fixed. A unit test with `complete_protein` set to True is also added.
