### ISSUE TITLE
Exception not raised in "SeqXmlWriter._write_species" because the "raise" keyword is missing

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [biopython/biopython#3294]
Hello,

While analyzing biopython on SonarCloud I saw what looks like an error in [`Bio/SeqIO/SeqXmlIO.py`](https://github.com/biopython/biopython/blob/05107f5cfd1f8d67dbc4d472268618f2b6d93bc2/Bio/SeqIO/SeqXmlIO.py#L556-L559):

<img width="1600" alt="Screenshot 2020-10-03 at 16 53 09" src="https://user-images.githubusercontent.com/40498978/94994610-ffd13280-0598-11eb-8cba-dc5d8368a7a2.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_biopython&issues=AXTqE7mUA4gH5cbKom5n&open=AXTqE7mUA4gH5cbKom5n).

The problem is quite simple: an exception is created but never raised because the `raise` keyword is missing. This is a pretty common mistake in python ;)

In case you want to scan biopython on SonarCloud [you can use a configuration similar to this one](https://github.com/nicolas-harraudeau-sonarsource/biopython/commit/9952e28e9c411a626620a78993fd9af8d24dd9ab) when you enable automatic analysis. SonarCloud is free for open source projects.

**Comment by peterjc** [comment]
Good catch. Fix coming soon.

I wonder if anyone has written a flake8 plugin for catching that anti-pattern?

**Comment by nicolas-harraudeau-sonarsource** [comment]
Thanks @peterjc. Happy to help.

I don't know if such a plugin exists. [shameless plug on] All I can say is that SonarCloud has its own analyzer but it can also import flake8 issues in case developers want to have pycodestyle issues, or if they want to see issues from a specific flake8 plugin. So you can have both flake8 and SonarCloud issues in your continuous integration workflow if you want. If you want those issues in your IDE there is SonarLint. You can use both products for free.[shameless plug off]

**Comment by peterjc** [comment]
SonarCloud reminds me a little of the ultimately unsuccessful LandScape.io (see https://landscape.io/the-current-state-of-landscape.html etc) and other systems. It is evidently multi-language, not just Python.

Having been looking at this for #3295, some of the things it spots are impressive (probably driven by some introspection and/or type inference), not just the simple pattern matching that I am used to in most of the flake8 ecosystem.

This specific error of an un-raised exception however (and a few others like a pointless ``return`` or ``pass`` statement) do seem like the kind of thing the flake8 ecosystem covers, and would be low hanging fruit for our pre-commit setup for local and online testing.

**Comment by nicolas-harraudeau-sonarsource** [comment]
Thanks for your praises! I shared them with our team and they are really happy that they could help.

Thank you also for your comments in the Pull Request. This will help me improve our bug detection rules.

Regarding your last comment, detecting un-raised exceptions is a bit more tricky than it looks. We don't raise on every constructor because there can be hidden side effects. This rule focuses on exceptions' constructors only. The case detected here is easy to detect as `ValueError` is a builtin exception. But SonarCloud's python analyzer can also detect custom exception classes which are defined in the project, or even more complex, exceptions from third party projects (as long as they are also defined in Typeshed, it is a current limitation).

I read the article you shared about Landscape.io. It is a good comparison. In this article the author says:
> I wanted something like SonarQube but for Python
SonarQube is one of the products we develop :) It is the on premise equivalent of SonarCloud.
However we now also cover the security aspect, not only code quality. SonarCloud and SonarQube have a taint analysis engine.

I'll now stop talking about SonarCloud/SonarQube/SonarLint. Don't hesitate to reach out on the community forum if you have any question, bug report or suggestion ;)

Cheers,

**Comment by peterjc** [comment]
Thank you, that's been useful and interesting.

And yes, the easy case for spotting un-raised exceptions would be only the built-in exceptions. You and your team are clearly working several levels beyond that.
