### ISSUE TITLE
Use Python 3.9 on TravisCI

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#3300]
Don't think this is on TravisCI yet, at least https://docs.travis-ci.com/user/languages/python/ not updated. May want to consider if we need all of 3.6, 3.7, 3.8 and 3.9 (maybe focus on 3.6 and 3.9 only?).

Our AppVeyor setup should just take the latest Python 3 builds from https://repo.anaconda.com/miniconda/ and thus start using Python 3.9 automatically once it is released.

**Comment by speleo3** [comment]
Travis was dropped in f16150d076b682247f26d764039d647f1726172b, looks like this ticket can be closed.

**Comment by peterjc** [comment]
Thanks!
