### ISSUE TITLE
UnknownSeq inconsistency

### ISSUE THREAD

**Issue by mdehoon** [biopython/biopython#3301]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
>>> import sys; print(sys.version)
3.7.2 (default, Feb 26 2019, 11:04:42) 
[GCC 6.3.0 20170516]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.15.0-45-generic-x86_64-with-debian-9.3
>>> import Bio; print(Bio.__version__)
1.78
```

Comparing the behavior of a `Seq` object to that of an `UnknownSeq` object:
```python
>>> from Bio.Seq import *
>>> s = Seq("TTTTTT")
>>> print(s)
TTTTTT
>>> print(s.transcribe())
UUUUUU
>>> print(s.complement())
AAAAAA
>>> u = UnknownSeq(6,character="T")
>>> print(u)
TTTTTT
>>> print(u.transcribe())
UUUUUU
>>> print(u.complement())
TTTTTT
```

i.e. `transcribe` treats the `UnknownSeq` as 6 thymine nucleotides, while `complement` treats the same `UnknownSeq` as a sequence of 6 unknown nucleotides.
This implies that the definition of an `UnknownSeq` is unclear. Currently, it has two purposes: (1) storing a long stretch of the same nucleotide efficiently; (2) representing an undefined sequence. If it's (1), then `print(u.complement())` should return `AAAAAA`; if it's (2), then `print(u.transcribe())` should return `TTTTTT`.

**Comment by peterjc** [comment]
Using "T" is rather strange for ``UnknownSeq``, the use cases I had in mind would be an unknown letter - so "N" or "n" would be the only sensible choice for an RNA/DNA/nucleotide, "X" or "x" for a protein, and something else like "?" for completely unknown.

One option would be to restrict the possible character choices so that NnXx or symbols are the only valid entries.

However, I would change the complement method to match the others - quick PR for comment soon.

**Comment by peterjc** [comment]
How about "fixing" the complement, and add a warning for using letters other than N or X, to become a ValueError in a subsequent release?

**Comment by mdehoon** [comment]
> How about "fixing" the complement, 

Yes we should.

> and add a warning for using letters other than N or X, to become a ValueError in a subsequent release?

I wouldn't do that.

**Comment by peterjc** [comment]
OK

**Comment by peterjc** [comment]
Thank you!

**Comment by mdehoon** [comment]
Thinking about this again: Perhaps we don't need an `UnknownSeq` class at all. As far as I can tell, it's only used in `Bio.GenBank` and `Bio.SeqIO.QualityIO`, and there it would suffice to just set `seq._data` to `None` (and store the sequence length in some other attribute). If we do have an `UnknownSeq` class, then we get into the strange situation that `UnknownSeq(6, 'A')` and `Seq('AAAAAA')` behave the same, but the former is considered to be unknown in some parts of Biopython.

**Comment by peterjc** [comment]
It should be possible to tweak the ``Seq`` object to handle this case, but that complexity would come at a cost. The ``UnknownSeq`` lets you access string like behaviour on demand.

I think adding a warning and later a ``ValueError`` in ``UnknownSeq`` when using other than X, x, N, n or punctuation makes more sense.

**Comment by mdehoon** [comment]
> I think adding a warning and later a `ValueError` in `UnknownSeq` when using other than X, x, N, n or punctuation makes more sense.

Then you run into the issue that `UnknownSeq(6, 'N')` and `Seq('NNNNNN')` are both equal to `"NNNNNN"`, but one is "unknown" and treated as such, while the other is not.

**Comment by peterjc** [comment]
What is the issue you mean? Other than if checking their class, and their ``__reprr__`` value,  objects ``UnknownSeq(6, 'N')`` and ``Seq('NNNNNN')`` should behave the same.

**Comment by mdehoon** [comment]
We are checking if a sequence is an `UnknownSeq` in several places in Biopython.

**Comment by peterjc** [comment]
Yes: The GenBank writer (because we use ``UnknownSeq`` when parsing a GenBank/EMBL file with no actual sequence; likewise parsing "qual" files), and BioSQL (where again we use the ``UnknownSeq`` for storing unknown sequences where we only have the length). This is precisely the use-case it was introduced for.

Are you suggesting those checks also look at the letter being used to confirm the sequence really is unknown and not a homopolymer like AAAAAAA?

**Comment by mdehoon** [comment]
> Are you suggesting those checks also look at the letter being used to confirm the sequence really is unknown and not a homopolymer like AAAAAAA?

I am suggesting to remove `UnknownSeq` altogether, and use a `Seq` object with `_data` set to `None`.

**Comment by peterjc** [comment]
OK. That is clear now. I still don't think it will be any clearer as a user, and expect it to me more complicated to implement than the current subclass approach. But if you want to experiment on a branch, perhaps you can convince me otherwise?
