### ISSUE TITLE
Add Type Hints to existing methods/functions

### ISSUE THREAD

**Issue by sgalpha01** [biopython/biopython#3304]
Due to Dynamic nature of Python, sometimes it becomes difficult to check type of objects used. To make object type more explicit, Python introduced Type Hinting. 

More information can be found here:
- [PEP 483](https://www.python.org/dev/peps/pep-0483/)
- [PEP 484](https://www.python.org/dev/peps/pep-0484/)
- [typing](https://docs.python.org/3/library/typing.html)

This is just a small suggestion.

**Comment by MarkusPiotrowski** [comment]
Dear @sgalpha,

thank you, I think we are already considering type hints and type annotations, see #2236 and #3165.

**Comment by sgalpha01** [comment]
Oh, okay. Sorry, I didn't see that.

**Comment by MarkusPiotrowski** [comment]
No problem, thank you for your motivation to contribute.
