### ISSUE TITLE
Seq equality should check for type

### ISSUE THREAD

**Issue by mdehoon** [biopython/biopython#3313]
The `__eq__(self, other)` method of `Seq` objects applies `str` to `other` without checking the type of `other`.
This can lead to surprising results, for example
```python
>>> from Bio.Seq import Seq
>>> s = Seq("6")
>>> s == 6
True
>>> s = Seq("None")
>>> s == None
True
```
I think then that `__eq__` should check if `other` is a `Seq`, `MutableSeq`, or `str`, and return `False` if it is not.

**Comment by peterjc** [comment]
That seems reasonable - are there any others like bytes, or bytes array where is makes sense?

**Comment by mdehoon** [comment]
Currently `__eq__` will not treat `bytes` or `bytearray` in a reasonable way, as e.g. `str(b'ABCD')` returns `"b'ABCD'"`, not `'ABCD'`. So `Seq('ABCD') == b'ABCD'` is `False`.

**Comment by peterjc** [comment]
I know, but subject to the encoding we could support ``Seq('ABCD') == b'ABCD'``, but probably safest to behave as string like as possible.

**Comment by mdehoon** [comment]
Other methods in `Bio.Seq` are also broken:
```python
>>> from Bio.Seq import Seq
>>> s = Seq("ACGT ")
>>> s.strip()
Seq('ACGT ')
# should be Seq('ACGT')
>>> s.strip(None)
Seq('ACGT ')
# should be Seq('ACGT')
>>> s = Seq("None ")
>>> s.strip()
Seq(' ')
# should be Seq("None")
>>> s.strip(None)
Seq(' ')
# should be Seq("None")
```

**Comment by mdehoon** [comment]
This bug was introduced when the alphabet check was dropped from string-like methods:

https://github.com/biopython/biopython/commit/41cc2624ab3126985499510c02f487123ae52d8d#diff-bdfee92a19a985d8313cb909cc673c4f02acb6d54f4aeea337b0e03e7f6b5803

**Comment by peterjc** [comment]
The whitespace strip not working is most likely to catch people out, although our parsers avoid making strings with spaces. Still, that's an unfortunate oversight in our tests, a double failing.

**Comment by peterjc** [comment]
Similar issue in the find, index, and split methods, see #3315

**Comment by mdehoon** [comment]
Also in `count` and `count_overlap`.
