### ISSUE TITLE
'ls_orchid.fasta' can't be read

### ISSUE THREAD

**Issue by ardsatcg** [biopython/biopython#3317]
Still got an error, how do i ?
![Screenshot 2020-10-20 225505](https://user-images.githubusercontent.com/71117550/96604310-8e7ad900-1327-11eb-825a-1637d87ecf59.png)
#3315 

```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-32-77ca58053425> in <module>
      1 from Bio import SeqIO
----> 2 for seq_record in SeqIO.parse("ls_orchid.fasta", "fasta"):
      3         print(seq_record.id)
      4         print(repr(seq_record.seq))
      5         print(len(seq_record))
~\anaconda3\lib\site-packages\Bio\SeqIO\__init__.py in parse(handle, format, alphabet)
    605     iterator_generator = _FormatToIterator.get(format)
    606     if iterator_generator:
--> 607         return iterator_generator(handle)
    608     if format in AlignIO._FormatToIterator:
    609         # Use Bio.AlignIO to read in the alignments
~\anaconda3\lib\site-packages\Bio\SeqIO\FastaIO.py in __init__(self, source, alphabet, title2ids)
    181             raise ValueError("The alphabet argument is no longer supported")
    182         self.title2ids = title2ids
--> 183         super().__init__(source, mode="t", fmt="Fasta")
    184 
    185     def parse(self, handle):
~\anaconda3\lib\site-packages\Bio\SeqIO\Interfaces.py in __init__(self, source, alphabet, mode, fmt)
     45             raise ValueError("The alphabet argument is no longer supported")
     46         try:
---> 47             self.stream = open(source, "r" + mode)
     48             self.should_close_stream = True
     49         except TypeError:  # not a path, assume we received a stream
FileNotFoundError: [Errno 2] No such file or directory: 'ls_orchid.fasta'
```

**Comment by peterjc** [comment]
This is a path problem - if you use just a filename like ``ls_orchid.fasta`` it has to be in the current directory, i.e. next to your Python script.

You may prefer to use absolute paths, e.g. something like ``/home/ardsatcg/project/biopython_tests/ls_orchid.fasta``

Also, you should NOT put your scripts within Python's ``site-packages`` folder mixed up with Biopython's files. That will cause problems with import commands.

**Comment by ardsatcg** [comment]
> This is a path problem - if you use just a filename like `ls_orchid.fasta` it has to be in the current directory, i.e. next to your Python script.
> 
> You may prefer to use absolute paths, e.g. something like `/home/ardsatcg/project/biopython_tests/ls_orchid.fasta`
> 
> Also, you should NOT put your scripts within Python's `site-packages` folder mixed up with Biopython's files. That will cause problems with import commands.


I put this file on C:\Users\LENOVO\anaconda3\Scripts\biopython_tests\ls_orchid.fasta
but seem's didn't work, still the same message

**Comment by ardsatcg** [comment]
![Screenshot 2020-10-22 053852](https://user-images.githubusercontent.com/71117550/96790219-00871700-1429-11eb-92d6-d3cb67a53232.png)

like this?

**Comment by peterjc** [comment]
OK, so your code is running in ``C:\Users\LENOVO\`` - If you refer to the FASTA file as just ``ls_orchid.fasta`` then Python will look for ``C:\Users\LENOVO\ls_orchid.fasta``

Beyond that since I can now see you are using Jypyter, have a look at e.g. https://stackoverflow.com/questions/15680463/change-ipython-jupyter-notebook-working-directory and the Jypyter commands for setting or changing the default.

**Comment by ardsatcg** [comment]
> OK, so your code is running in `C:\Users\LENOVO\` - If you refer to the FASTA file as just `ls_orchid.fasta` then Python will look for `C:\Users\LENOVO\ls_orchid.fasta`
> 
> Beyond that since I can now see you are using Jypyter, have a look at e.g. https://stackoverflow.com/questions/15680463/change-ipython-jupyter-notebook-working-directory and the Jypyter commands for setting or changing the default.

So, what i'm gonna do with this jupyter nb/lab, i'll changes the jupyter directory or make new ones?

**Comment by ardsatcg** [comment]
> I personally have not used Jupyter enough to have a strong view on how best to work with directories there. I would suggest having the notebook and the data files together in the same directory?
> 
> Can we close this issue now?

yup, thx 👍

**Comment by peterjc** [comment]
Hope that was helpful.
