### ISSUE TITLE
module pairwise2.align.globalmx runs multiple times 

### ISSUE THREAD

**Issue by nyck33** [biopython/biopython#3319]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
output:
```
(bio) nobu@gold3forever:~/Desktop/BioInformatics/code_git/a2$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.4.0-48-generic-x86_64-with-glibc2.10
>>> import Bio; print(Bio.__version__)
1.78

```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Expecting this code:
```
    for a in pairwise2.align.globalmx(a1, a2, 2, -1):
        print(pairwise2.format_alignment(*a))
```
to run once and only once from: https://biopython.org/docs/1.75/api/Bio.pairwise2.html

but it runs multiple times.

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

My python file called a2e1.py (school assignment)
```
from Bio import pairwise2


def gap_pen(a1, a2):
    for a in pairwise2.align.globalmx(a1, a2, 2, -1):
        print(pairwise2.format_alignment(*a))

def open_extend(a1, a2):
    for a in pairwise2.align.globalms(a1, a2, 2, -1, -5, -1): #match, mismatch, gap open, gap extend
        print(pairwise2.format_alignment(*a))

def no_extend():
    a1 = 'TCTCCTGACCCC'
    a2 = 'TCT----AGTCC'
    gap_pen(a1, a2)

def main():

    no_extend()

    a1 = 'TCTCCTGACCCC'
    a2 = 'TCT----AGTCC'
    print('part b')
    open_extend(a1, a2)

    a3_1 ='TCTCCTGACCCC'
    a3_2 ='TCT--AGTCC--'

    a4_1 = 'TCTCCTGACCCC'
    a4_2 = 'TCT----AGTCC'

    a5_1 = 'TCTCCTG-ACCCC'
    a5_2 = 'TCT--AGT-CC--'

    a6_1 = 'TCT---CCTGACCCC'
    a6_2 = 'TCTAGTCC-------'

    alignments_arr = [a3_1, a3_2, a4_1, a4_2, a5_1, a5_2]

    print('part c')
    count = 1

    for i in range(0, len(alignments_arr), 2):
        print(f'{i} th pair')
        open_extend(alignments_arr[i], alignments_arr[i+1])
        count += 1



if __name__ =="__main__":
    main()
```
the output, part a is the part I am concerned about:
```
/home/nobu/anaconda3/envs/bio/bin/python /home/nobu/Desktop/BioInformatics/code_git/a2/a2e1.py
TCTCCTG----ACC--CC
  | || |||||    ||
--T-CT-----A--GTCC
  Score=12

TCTCCTG----ACC--CC
|   || |||||    ||
T---CT-----A--GTCC
  Score=12

TCTCCTG----ACC--CC
  || | |||||    ||
--TC-T-----A--GTCC
  Score=12

TCTCCTG----ACC--CC
|  | | |||||    ||
T--C-T-----A--GTCC
  Score=12

TCTCCTG----ACC--CC
||   | |||||    ||
TC---T-----A--GTCC
  Score=12

TCTCCTG----ACC--CC
|||    |||||    ||
TCT--------A--GTCC
  Score=12

TCTCCT-----GACC-CC
  | |||||| |    ||
--T-CT----AG---TCC
  Score=12

TCTCCT-----GACC-CC
|   |||||| |    ||
T---CT----AG---TCC
  Score=12

TCTCCT-----GACC-CC
  || ||||| |    ||
--TC-T----AG---TCC
  Score=12

TCTCCT-----GACC-CC
|  | ||||| |    ||
T--C-T----AG---TCC
  Score=12

TCTCCT-----GACC-CC
||   ||||| |    ||
TC---T----AG---TCC
  Score=12

TCTCCT-----GACC-CC
|||   |||| |    ||
TCT-------AG---TCC
  Score=12

part b
TCTCCTGACCCC
|||    |..||
TCT----AGTCC
  Score=6

part c
0 th pair
TCTCCTGACCCC
|||  .|.||  
TCT--AGTCC--
  Score=6

2 th pair
TCTCCTGACCCC
|||    |..||
TCT----AGTCC
  Score=6

4 th pair
TCTCCTG-ACCCC
|||  .|  ||  
TCT--AGT-CC--
  Score=5


Process finished with exit code 0
```

### Steps to reproduce

(*Please fill this in *)
copy paste into pycharm.  
use this yml to create a conda env:
```
name: bio
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bcrypt=3.1.7=py38h7b6447c_1
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.3=py38he30daa8_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1h=h7b6447c_0
  - plotly=4.11.0=py_0
  - pycparser=2.20=py_2
  - python=3.8.5=h7579374_1
  - readline=8.0=h7b6447c_0
  - retrying=1.3.3=py_2
  - setuptools=49.6.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - biopython==1.78
    - chardet==3.0.4
    - cycler==0.10.0
    - idna==2.10
    - kiwisolver==1.2.0
    - matplotlib==3.3.2
    - ncbi-genome-download==0.3.0
    - numpy==1.19.2
    - pandas==1.1.2
    - pillow==7.2.0
    - pip==20.2.3
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - requests==2.24.0
    - urllib3==1.25.10
prefix: /home/nobu/anaconda3/envs/bio
```

**Comment by chris-rands** [comment]
The alignment is ran once- multiple different possible high scoring alignments are returned, but none of these are identical, does that answer your question?

**Comment by MarkusPiotrowski** [comment]
@nyck33 , as @chris-rands already mentioned, `pairwise2` will return a list of all alignments (up to 1000) that have the same maximum score. If you want it to return only one alignment, you can use the option `one_alignment_only=True`. 

Besides that, I see that you apply sequences that already contain gaps. You should no do this, alignment programs expect to get ungapped sequences. `pairwise2` will not understand that there are already gaps. In your case, the gap `-` is interpreted as just another residue (like A, G, C, T). It's the job of the alignment program to introduce gaps. So all your results are useless/wrong, unless you did this deliberately.

**Comment by chris-rands** [comment]
Good catch Markus- might be worth raising a warning/error when the input string/object for an alignment contains `'-'`?(here and in `Bio.Align`)

**Comment by nyck33** [comment]
@chris-rands @MarkusPiotrowski  thanks for the clarification.
Can someone point me to the right module for alignments for sequences with gaps?

**Comment by chris-rands** [comment]
@nyck33 I think you misunderstand- biological sequences never contain gaps, gaps are added *during* the alignment. They are used to display the position of insertions/deletions when comparing 2 or more different sequences

**Comment by nyck33** [comment]
@chris-rands   I apologize I just read that in my class notes.  I'm a bioinformatics noob, only took Bio 12 in high school no uni bio courses until now.  Thanks.

**Comment by MarkusPiotrowski** [comment]
@nyck33 
If you should 'just' calculate the score of a given alignment, aligner programs are not suitable for that task.
In your case you should do a character-by-character string comparison. Something like (attention: this is not complete and hasn't been tested):
```python
gap_opened = False
score = 0
match = ...
...
for letter_a, letter_b in zip(seq1, seq2):
   if letter_a == '-' or letter_b == '-':
        if gap_opened:
            score += gap_cost
        else:
            score += gap_open_cost
            gap_opened = True
    elif letter_a == letter_b:
        score += match
        gap_opened = False
...
```

**Comment by MarkusPiotrowski** [comment]
> 
> 
> Good catch Markus- might be worth raising a warning/error when the input string/object for an alignment contains `'-'`?(here and in `Bio.Align`)

I don't think so. `pairwise2` and `Aligner` are quite universal and can even be used (and have been used) for text comparisons. So I'm not keen on checking the input content.
People who do sequence alignments should know that the seqs should not contain gaps, and we can't make everything fool-proof.
