### ISSUE TITLE
Failing to parse Swiss format

### ISSUE THREAD

**Issue by jones-gareth** [biopython/biopython#3320]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```console
Python 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
; print(3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
mport Bio; print(Bio.__version__)CPython
Linux-4.19.84-microsoft-standard-x86_64-with-debian-buster-sid
>>> import Bio; print(Bio.__version__)
1.78
>>>
```

### Expected behaviour

I have Emboss database installed and am using Biopython to parse the output from seqret (swiss format). In previous versions of 
Biopython this has worked fine

### Actual behaviour

On some records fails with: 
```
Bio.SwissProt.SwissProtParserError: Unknown keyword ';
' found
```

This is caused by a line containing only a `;` following a PE annotation.

Example failing record [test.txt](https://github.com/biopython/biopython/files/5425840/test.txt)

Looking at https://github.com/biopython/biopython/blob/master/Bio/SwissProt/__init__.py it is clear that parsing this record will fail.

### Steps to reproduce

```python
from Bio import SeqIO

SeqIO.read('test.txt', 'swiss')
```

### Workaround

In case anyone else has this issue I am wrapping a file handle to strip out the offending lines:

```python

class SwissIOWrapper(TextIOWrapper):
    def __init__(self, handle: TextIOWrapper):
        super().__init__(handle)
        self.handle = handle
        self.read_pe = False

    def readline(self, size=-1) -> str:
        line = self.handle.readline(size)
        if self.read_pe and line.startswith(';'):
            self.read_pe = False
            return self.readline(size)
        self.read_pe = line.startswith('PE')
        return line

  with open(out_file, 'r') as fh:
        swiss_fh = SwissIOWrapper(fh)
        for record in SeqIO.parse(swiss_fh, 'swiss'):
           do_stuff()
```

**Comment by mdehoon** [comment]
The example does look like an invalid SwissProt file. See https://web.expasy.org/docs/userman.html for a definition of the format.

**Comment by peterjc** [comment]
Agreed, this looks like an invalid file:

```
ID   A0A494C0M7_HUMAN        Reviewed;         322 AA.
AC   A0A494C0M7;
DT   05-JUN-2019, integrated into UniProtKB/TrEMBL.
DT   05-JUN-2019, sequence version 1.
DT   12-AUG-2020, entry version 10.
...
DR   SUPFAM; SSF81296; SSF81296; 1.
PE   1: Evidence at protein level;
;
KW   Ion channel {ECO:0000256|ARBA:ARBA00023303, ECO:0000256|RuleBase:RU003822};
KW   Ion transport {ECO:0000256|ARBA:ARBA00023065,;
...
```

We could perhaps catch a line consisting of ``;\n`` only as a special case and ignore it with a warning, but we'd need some justification that this was a common problem. 

Does it affect lots of the files you are working with, or just one or two?

You mention EMBOSS. Did it generate the file for your, in which case which version(s) of EMBOSS had this problem - does their latest (final?) release too? It could perhaps related to a trailing new line on the evidence annotation it read in?

If EMBOSS didn't generate the file, just perhaps download it on your behalf, this could be a problem in the data source... it looks OK here https://www.uniprot.org/uniprot/A0A494C0M7.txt but that could be a live recreation of the file.

**Comment by jones-gareth** [comment]
@mdehoon and @peterjc Thanks for your quick replies. It certainly looks like an invalid entry- I'm sorry I rushed to file an issue before investigating more.

I'm using Emboss 6.6 which is the latest release.  After looking further I'm pretty sure this is an issue within Emboss that (at least) affects output from the the `seqret` command.  In the `dat` file for the Emboss database the entry for A0A494C0M7_HUMAN is correct (no `;` line trailing the `PE` field).  So it is not a trailing newline on the evidence field, nor would it seem to be an issue with the data source 

```
ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_trembl_human.dat.gz
```

Nevertheless, `seqret` adds the illegal line when retrieving the sequence:
```console
gareth@p1-win10 [11:04] 2005 $ grep -c '^;' /home/db/emboss/trembl/uniprot_trembl_human.dat
0
gareth@p1-win10 [11:04] 2006 $ seqret -sequence='up_tbl_human:A0A494C0M7_HUMAN' -osformat=swiss -outseq=test.seq
Read and write (return) sequences
gareth@p1-win10 [11:04] 2007 $ grep -c '^;' test.seq
1
```
I first caught this issue in a unit test that returned 7 bad entries from a total of 488
```console
gareth@p1-win10 [11:04] 2008 $ seqret -sequence='up_tbl_human:*M7_HUMAN' -osformat=swiss -outseq=test.seq
Read and write (return) sequences
gareth@p1-win10 [11:07] 2009 $ grep -c '^ID' test.seq
488
gareth@p1-win10 [11:07] 2010 $ grep -c '^;' test.seq
7
```
That's a error rate of 1.5%. Given the popularity of Emboss and Biopython, it may make sense for you to log an error, rather than raise an exception.  That said, I seem to be the only person who has raised the issue and I have a workaround.

**Comment by fabianegli** [comment]
@jones-gareth Can you please post your workaround/fix, so people coming past this issue because of the same problem can use it, too?

I think raising an error is the right thing to do for biopython. Solid input validation is priceless. It is better to find the issue and fix it instead of ignoring it with who knows what consequences.

**Comment by peterjc** [comment]
Good point, the ``sed`` fix is another nice workaround. We can revisit this if anyone else finds the issue, but closing for now. Thanks all.
