### ISSUE TITLE
Can I add "csv" to SeqIO.write, which is very similar to "tab" format?

### ISSUE THREAD

**Issue by YipingRuan** [biopython/biopython#3327]

**Comment by peterjc** [comment]
The same idea with just two columns?

I'm curious what you would use this for.

**Comment by YipingRuan** [comment]
Normally we can just do a search & replace use normal text editor, until I got a giant file.

And CSV is also a popular format.

**Comment by peterjc** [comment]
So someone else is sending you sequences in CSV format? Usual, I don't think I've ever seen that - even TSV is rare.

And this is definitely just two columns? That should avoid all the pain with commas appearing in free text - a comma in an identifier is unusual... but even so, CSV usually comes with the expectation of being able to optionally quote strings. These considerations make supporting CSV more trouble than TSV.

(As an aside, I find the command line tool ``xsv`` very handy for CSV and TSV files, including converting between the two)

**Comment by MarkusPiotrowski** [comment]
Just want to add that in countries where the comma is used as decimal separator, `CSV` usually _means_ `ssv` (semi-colon separated values), at least when working with Excel.
