### ISSUE TITLE
can NcbiblastpCommandline or NcbiblastnCommandline read from stdin?

### ISSUE THREAD

**Issue by jvollme** [biopython/biopython#3329]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
Biopython : 1.7.4
```

### Question
the ncbi blast+ tools ```blastn``` and ```blastp``` (and most others, too) can read query sequences from sdtin. However the biopython wrappers  ```NcbiblastpCommandline``` and ```NcbiblastnCommandline``` do not seem to have an option for this, or it is not documented?

being able to pipe queries directly to these tools via stdin would be highly desirable, because this would remove unnecessary read/write processes to hard-disk.

Is this possible using these wrappers? And if yes, how?

**Comment by peterjc** [comment]
I believe the default ``-query`` argument of "-" means read from stdin, so you could use that explicitly or just not set the input argument. If you are only passing a few short sequences, then you would call the command line wrapper with the stdin as a string argument.

However, heavy use of stdin would be best involving the command via ``subprocess`` explicitly, using the command line wrapper just to build the command line string. At that point you might as well ignore the wrapper, see discussion on #2877
