### ISSUE TITLE
Bio::SeqIO error

### ISSUE THREAD

**Issue by SAMANDOLL** [biopython/biopython#3337]
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /Users/padana/opt/anaconda3/lib/site_perl/5.26.2/darwin-thread-multi-2level /Users/padana/opt/anaconda3/lib/site_perl/5.26.2 /Users/padana/opt/anaconda3/lib/5.26.2/darwin-thread-multi-2level /Users/padana/opt/anaconda3/lib/5.26.2 .) at add_ka_ks.pl line 1.
BEGIN failed--compilation aborted at add_ka_ks.pl line 1.

Kindly guide me , how i can solve this problem.

**Comment by peterjc** [comment]
You are dealing with BioPerl, not Biopython - our ``Bio.SeqIO`` module was named following their ``Bio::SeqIO`` convention.

The message is telling you that BioPerl (or at least, the ``Bio/SeqIO.pm`` file) is not installed.

If you are still stuck, see https://bioperl.org or https://github.com/bioperl/bioperl-live
