### ISSUE TITLE
Some of the Bio.Phylo tutorials do not work with Python3

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#334]
In my attempt to convert part of the tutorial to notebooks I have found a couple of problems with the examples:

Snippet one:

```
trees = Phylo.parse(".../phyloxml_examples.xml", "phyloxml")
for tree in trees:
    print(tree)
```

This works out of the box, but because Phylo.parse returns a generator this is now consumed, thus the following snippet will not work (generator consumed)

```
tree1 = trees[0]
Phylo.write(tree1, "tree1.xml", "phyloxml")
```

One could go the lazy way (as I did) and do

```
trees = list(trees)
```

But then the bytes to strings stuff comes back to haunt us:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-28-d98fbd125e52> in <module>()
      1 tree1 = trees[0]
----> 2 Phylo.write(tree1, "tree1.xml", "phyloxml")

/home/tra/.local/lib/python3.4/site-packages/Bio/Phylo/_io.py in write(trees, file, format, **kwargs)
     81         trees = [trees]
     82     with File.as_handle(file, 'w+') as fp:
---> 83         n = getattr(supported_formats[format], 'write')(trees, fp, **kwargs)
     84     return n
     85 

/home/tra/.local/lib/python3.4/site-packages/Bio/Phylo/PhyloXMLIO.py in write(obj, file, encoding, indent)
    126         raise ValueError("First argument must be a Phyloxml, Phylogeny, "
    127                 "Tree, or iterable of Trees or Phylogenies.")
--> 128     return Writer(obj).write(file, encoding=encoding, indent=indent)
    129 
    130 

/home/tra/.local/lib/python3.4/site-packages/Bio/Phylo/PhyloXMLIO.py in write(self, file, encoding, indent)
    673         if indent:
    674             _indent(self._tree.getroot())
--> 675         self._tree.write(file, encoding)
    676         return len(self._tree.getroot())
    677 

/usr/lib/python3.4/xml/etree/ElementTree.py in write(self, file_or_filename, encoding, xml_declaration, default_namespace, method, short_empty_elements)
    776                 serialize = _serialize[method]
    777                 serialize(write, self._root, qnames, namespaces,
--> 778                           short_empty_elements=short_empty_elements)
    779 
    780     def write_c14n(self, file):

/usr/lib/python3.4/contextlib.py in __exit__(self, type, value, traceback)
     64         if type is None:
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:
     68                 return

/usr/lib/python3.4/xml/etree/ElementTree.py in _get_writer(file_or_filename, encoding)
    835                 # destroyed
    836                 stack.callback(file.detach)
--> 837                 yield file.write
    838 
    839 def _namespaces(elem, default_namespace=None):

/usr/lib/python3.4/contextlib.py in __exit__(self, *exc_details)
    334                 # set-up context
    335                 fixed_ctx = exc_details[1].__context__
--> 336                 raise exc_details[1]
    337             except BaseException:
    338                 exc_details[1].__context__ = fixed_ctx

/usr/lib/python3.4/contextlib.py in __exit__(self, *exc_details)
    319             cb = self._exit_callbacks.pop()
    320             try:
--> 321                 if cb(*exc_details):
    322                     suppressed_exc = True
    323                     pending_raise = False

/usr/lib/python3.4/contextlib.py in _exit_wrapper(exc_type, exc, tb)
    265         """
    266         def _exit_wrapper(exc_type, exc, tb):
--> 267             callback(*args, **kwds)
    268         # We changed the signature, so using @wraps is not appropriate, but
    269         # setting __wrapped__ may still help with introspection

TypeError: must be str, not bytes
```

**Comment by vincentdavis** [comment]
What is the status here, is 7c1b492 the last fix?

**Comment by peterjc** [comment]
I guess we need to audit the LaTeX looking for examples not flagged as doctests, enable them, and try them via ``test_Tutorial.py`` (see also the chapter in the tutorial for more about how this works).

And/or someone can manually go though the chapter trying the examples under Python 3.

**Comment by yogeshhk** [comment]
In chapter 13.2

Tried:
Phylo.convert("data/other_trees.nwk", "newick", "data/other_trees.xml", "nexml")

Got errors...

Error 1:
Traceback (most recent call last):
  File "C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\Bio\File.py", line 72, in as_handle
    yield fp
  File "C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\Bio\Phylo\_io.py", line 77, in write
    n = getattr(supported_formats[format], "write")(trees, fp, **kwargs)
  File "C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\Bio\Phylo\NeXMLIO.py", line 96, in write
    return Writer(trees).write(handle, plain=plain, **kwargs)
  File "C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\Bio\Phylo\NeXMLIO.py", line 287, in write
    handle.write(reparsed.toprettyxml(indent="  ").encode("utf8"))
TypeError: write() argument must be str, not bytes


Error 2:
Traceback (most recent call last):
  File "C:/YogeshKulkarni/Personal/Github_BioNLP/src/BioPythonTutorial/biopython_tutorial.py", line 57, in <module>
    Phylo.convert("data/other_trees.nwk", "newick", "data/other_trees.xml", "nexml") # add this in between
  File "C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\Bio\Phylo\_io.py", line 86, in convert
    return write(trees, out_file, out_format, **kwargs)
  File "C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\tf2\lib\site-packages\Bio\Phylo\_io.py", line 77, in write
    n = getattr(supported_formats[format], "write")(trees, fp, **kwargs)
  File "C:\Users\yogesh.kulkarni\AppData\Local\Continuum\anaconda3\envs\tf2\lib\contextlib.py", line 126, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()

I am new to Bioython, but still wish to guess possible solutions:

Error 1: In Bio\Phylo\_io.py
line 76:  with File.as_handle(file, "w+") as fp:
should be: with File.as_handle(file, "w+", encoding="utf-8") as fp:

Error 2: In Bio\Phylo\_io.py
line 85: trees = parse(in_file, in_format, **parse_args)
should be: trees = list(parse(in_file, in_format, **parse_args))

**Comment by peterjc** [comment]
I've turned @yogeshhk's example into a self contained test and logged it as #3206. This does look like a Python 2 to 3 oversight with the code not being consistent about text vs binary mode (unicode strings vs bytes).
