### ISSUE TITLE
Git line-ending settings affect test results

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#3350]
Reporting a minor problem. Depending on the line endings of the OS, some tests fail (e.g. `test_MafIO_index`). You can see the issue on the GHA branch [here](https://github.com/JoaoRodrigues/biopython/runs/1372046459?check_suite_focus=true), or in detail:
```
======================================================================
ERROR: test_correct_retrieval_1 (test_MafIO_index.TestSpliceGoodMAF)
Correct retrieval of Cnksr3 in mouse.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\biopython\biopython\Tests\test_MafIO_index.py", line 671, in test_correct_retrieval_1
    result = self.idx.get_spliced(
  File "D:\a\biopython\biopython\build\lib.win-amd64-3.8\Bio\AlignIO\MafIO.py", line 648, in get_spliced
    fetched = list(self.search(starts, ends))
  File "D:\a\biopython\biopython\build\lib.win-amd64-3.8\Bio\AlignIO\MafIO.py", line 620, in search
    raise ValueError(
ValueError: Expected 3185728-3185797 @ offset 1974167, found 3185634-3185640

----------------------------------------------------------------------
```

The issue comes from one of the test data files needing `LF` line endings and failing when those are `CRLF`. My local git autocrlf is set to `auto`, which masks the problem since it converts endings on checkout and commit. Running the tests manually results in this error. I can avoid it either by setting autocrlf to `false` and doing a clean `git clone` or using `dos2unix` to convert line endings forcefully.

Maybe we should add a couple of rules to `.gitattributes` to fix this, or maybe look at what the issue might be with the code itself? Having results depending on line endings doesn't sound great.

**Comment by MarkusPiotrowski** [comment]
@JoaoRodrigues Just to make it more clear to me:
1. On which system do you see the error?
2. When you say 'running the tests manually' then you mean outside the git environment?

I do not know anything about the code in `MafIO.py` but I guess you will always encounter such problems with line endings when you access a file byte-wise, am I right?

**Comment by peterjc** [comment]
The underlying problem in this case is #1149, can we close this as a duplicate?

IIRC, we've explicitly set some of the test files to binary mode it git where we want to test a precise form of a text file. Perhaps that would be a workaround here.

**Comment by MarkusPiotrowski** [comment]
> IIRC, we've explicitly set some of the test files to binary mode it git where we want to test a precise form of a text file. Perhaps that would be a workaround here.

As @JoaoRodrigues said, set `cnksr3.fa`  from `Tests/MAF/` to `.gitattributes` as binary as workaround for the test suite.

**Comment by peterjc** [comment]
That sounds like a good idea 👍

**Comment by JoaoRodrigues** [comment]
Sorry for the duplicate issue @pjcock!

That's likely the reason @MarkusPiotrowski, let me test that on my end. As
for your questions: I'm on Win10 and ran tests with `python run_tests.py
test_MafIO_index.py`.

**Comment by JoaoRodrigues** [comment]
Closing as duplicate of #1149

**Comment by peterjc** [comment]
@JoaoRodrigues does the ``. gitattributes`` change solve the test failure? If so that's worth committing.

**Comment by JoaoRodrigues** [comment]
Still debugging!
