### ISSUE TITLE
Cannot read Prokka gbk into BioPython. 

### ISSUE THREAD

**Issue by CarmenSheppard** [biopython/biopython#3379]
Not sure if this is a BioPython or Prokka issue, or maybe to do with the Node names produced by the assembler.

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
CPython
Linux-4.15.0-118-generic-x86_64-with-glibc2.10
Bio 1.78

### Expected behaviour

Expected read gbk file (created by Prokka V1.13) from Unicycler or Spades assemblies.

### Actual behaviour

ValueError: Did not recognise the LOCUS line layout:
LOCUS       NODE_1_length_191762_cov_13.6631191762 bp   DNA linear

### Steps to reproduce

SeqIO.read(open("prokka_file.gbk", "r"), "genbank")

**Comment by peterjc** [comment]
The name and the length have merged into one with no space. I think there is an open Prokka issue about this... will check later if you don't beat me to it.

**Comment by CarmenSheppard** [comment]
Thanks @peterjc  I think I just came to the same conclusion. I couldnt' see anything when I searched the Prokka repo, but maybe I didn't use the right search terms. The node names on the assembly are long. I was thinking of clipping them before running Prokka, but I'm hoping to not have to do that if there's a way around it!

**Comment by peterjc** [comment]
See https://github.com/tseemann/prokka/issues/153 - maybe try ``--compliant`` mode in prokka?

**Comment by CarmenSheppard** [comment]
Many thanks.. yes that worked and now I see there's lots of similar threads there. not sure how I missed it except I guess I was searching on the BioPython ValueError text.
