### ISSUE TITLE
Wrong score output by biopython.PairwiseAligner

### ISSUE THREAD

**Issue by aditi741997** [biopython/biopython#3390]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
>>> import sys; print(sys.version)
3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.4.0-1029-aws-x86_64-with-Ubuntu-18.04-bionic
>>> import Bio; print(Bio.__version__)
1.78
```

### Expected behaviour

get global alignment with score -5. [Denoted by L1_Score in the output below]

### Actual behaviour

Getting correct alignment, but wrong score value.
GlobalAlign score:  -4.0 , time:  0.0002446174621582031
WEIRD:: Different score for this pair. L1_score: -5.000000, L3_score: -4.000000
Alignment:
```
MAHAAQVGLQDATSPIMEELIIFHDHALMIIFLICFLILYALFLTLTTKLTNTSISDAQEMETVWTILPAIILVLIALPSLRILYMTDEVNDPSFTIKSIGHQWYWTYEYTDYGGLIFNSYMLPPLFLEPGDLRLLDVDNRVVLPVEAPIRMMITSQDVLHSWAVPTLGLKTDAIPGRLNQTTFTATRPGVYYGQCSEICGANHSFMPIVLELIPLKIFEMGPVFTL
|||||||||||||||||||||||||||||||||||||.|||||||||||||||||||||||||||||||||||||||||||||||||..||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||.||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||.||
MAHAAQVGLQDATSPIMEELIIFHDHALMIIFLICFLVLYALFLTLTTKLTNTSISDAQEMETVWTILPAIILVLIALPSLRILYMTXKVNDPSFTIKSIGHQWYWTYEYTDYGGLIFNSYMLPPLFLEPGDLRLLDVDNRVVLPVEAPVRMMITSQDVLHSWAVPTLGLKTDAIPGRLNQTTFTATRPGVYYGQCSEICGANHSFMPIVLELIPLKIFEMGPVLTL
```

### Steps to reproduce

Pairwise sequence aligner with parameters
  match_score: 0.000000
  mismatch_score: -1.000000
  target_internal_open_gap_score: -1.000000
  target_internal_extend_gap_score: -1.000000
  target_left_open_gap_score: -1.000000
  target_left_extend_gap_score: -1.000000
  target_right_open_gap_score: -1.000000
  target_right_extend_gap_score: -1.000000
  query_internal_open_gap_score: -1.000000
  query_internal_extend_gap_score: -1.000000
  query_left_open_gap_score: -1.000000
  query_left_extend_gap_score: -1.000000
  query_right_open_gap_score: -1.000000
  query_right_extend_gap_score: -1.000000
  mode: global

```python
# Code begins
from Bio import Align
l3_aligner = Align.PairwiseAligner()
l3_aligner.match_score = 0
l3_aligner.mismatch_score = -1
l3_aligner.gap_score = -1
l3_aligner.mode = 'global'
l3_aligner.substitution_matrix = None
print(l3_aligner)
s1 = 'MAHAAQVGLQDATSPIMEELIIFHDHALMIIFLICFLILYALFLTLTTKLTNTSISDAQEMETVWTILPAIILVLIALPSLRILYMTDEVNDPSFTIKSIGHQWYWTYEYTDYGGLIFNSYMLPPLFLEPGDLRLLDVDNRVVLPVEAPIRMMITSQDVLHSWAVPTLGLKTDAIPGRLNQTTFTATRPGVYYGQCSEICGANHSFMPIVLELIPLKIFEMGPVFTL'
s2 = 'MAHAAQVGLQDATSPIMEELIIFHDHALMIIFLICFLVLYALFLTLTTKLTNTSISDAQEMETVWTILPAIILVLIALPSLRILYMTXKVNDPSFTIKSIGHQWYWTYEYTDYGGLIFNSYMLPPLFLEPGDLRLLDVDNRVVLPVEAPVRMMITSQDVLHSWAVPTLGLKTDAIPGRLNQTTFTATRPGVYYGQCSEICGANHSFMPIVLELIPLKIFEMGPVLTL'
score = l3_aligner.score(s1,s2 )
alignments = l3_aligner.align(s1,s2)
for align in alignments:
    print(align)
# Code ends
```

In the alignment, there are clearly 5 dots denoting mismatches. The score value should've been -5, but it is -4.

**Comment by peterjc** [comment]
I added some triple back-ticks for formatting on GitHub.

I note one of your mismatches is X with D, where X is conventionally any amino acid.

Your code example is apparently missing the line "print(score)" or similar. On the current code in GitHub, this does give -5. Does installing the as yet unreleased Biopython from GitHub work for you? This should be fairly easy to do on Linux.

@mdehoon do you agree this example changed since Biopython 1.78?

**Comment by mdehoon** [comment]
@peterjc Yes this example has changed. Originally the pairwise aligner automatically considered `X` to be a wildcard character that can be any amino acid. This changed when we added full unicode support to the pairwise aligner; the user can now set the wildcard character to any letter. By default, the wildcard character is `None`, i.e. no wildcard character. For the example above, we are now getting
```python
>>> l3_aligner.wildcard = 'X'
>>> print(l3_aligner)
Pairwise sequence aligner with parameters
  wildcard: 'X'
  match_score: 0.000000
  mismatch_score: -1.000000
  target_internal_open_gap_score: -1.000000
  target_internal_extend_gap_score: -1.000000
  target_left_open_gap_score: -1.000000
  target_left_extend_gap_score: -1.000000
  target_right_open_gap_score: -1.000000
  target_right_extend_gap_score: -1.000000
  query_internal_open_gap_score: -1.000000
  query_internal_extend_gap_score: -1.000000
  query_left_open_gap_score: -1.000000
  query_left_extend_gap_score: -1.000000
  query_right_open_gap_score: -1.000000
  query_right_extend_gap_score: -1.000000
  mode: global

>>> l3_aligner.score(s1,s2)
-4.0
>>> l3_aligner.wildcard = None
>>> print(l3_aligner)
Pairwise sequence aligner with parameters
  wildcard: None
  match_score: 0.000000
  mismatch_score: -1.000000
  target_internal_open_gap_score: -1.000000
  target_internal_extend_gap_score: -1.000000
  target_left_open_gap_score: -1.000000
  target_left_extend_gap_score: -1.000000
  target_right_open_gap_score: -1.000000
  target_right_extend_gap_score: -1.000000
  query_internal_open_gap_score: -1.000000
  query_internal_extend_gap_score: -1.000000
  query_left_open_gap_score: -1.000000
  query_left_extend_gap_score: -1.000000
  query_right_open_gap_score: -1.000000
  query_right_extend_gap_score: -1.000000
  mode: global

>>> l3_aligner.score(s1,s2)
-5.0
```

I believe that fixes this issue.

**Comment by aditi741997** [comment]
Thankyou very much for the quick and helpful responses!
Setting wildcard to None works, I hadn't realized there was an X in the sequence.
