### ISSUE TITLE
pairwise2 memory error for long sequence alignment and Align.PairwiseAligner() finishes with exit code 137

### ISSUE THREAD

**Issue by nyck33** [biopython/biopython#3407]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
```
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
CPython
Linux-5.4.0-54-generic-x86_64-with-glibc2.10
1.78
```
(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
pairwise2 returns memory error on my Lenovo T420 with 8 GB RAM when I try to align two of the longest DNA sequences:  https://www.ncbi.nlm.nih.gov/nuccore/AE014297
and https://www.ncbi.nlm.nih.gov/nuccore/LR899430.1

```


MemoryError: Out of memory
Traceback (most recent call last)

    File "/home/nobu/Desktop/BioInformatics/bio_pam_blosum/frontend/needleman_callbacks/entrez_callbacks.py", line 339, in run_needleman

    needle.align_global()

    File "/home/nobu/Desktop/BioInformatics/bio_pam_blosum/backend/bio_needleman.py", line 65, in align_global

    alignments = pairwise2.align.globalds(seq1, seq2, self.matrix,

    File "/home/nobu/anaconda3/envs/bio/lib/python3.8/site-packages/Bio/pairwise2.py", line 493, in __call__

    return _align(**keywds)

    File "/home/nobu/anaconda3/envs/bio/lib/python3.8/site-packages/Bio/pairwise2.py", line 560, in _align

    matrices = _make_score_matrix_fast(

    MemoryError: Out of memory

```

(*Please fill this in*)

### Actual behaviour
See above error.
(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce
This is my dash app with biopython engine doing the alignments: https://github.com/nyck33/bio_pam_blosum
Use requirements.txt to create a virtual environment, run from main directory with python main.py, go to the second page called Entrez, upload the two above sequences (after downloading the Fasta files) and scroll down to the bottom and click Run Waterman.  The actual biopython method is called in bio_pam_blosum/backend/bio_needleman.py", line 65, in align_global per above error message.
(*Please fill this in *)

**Comment by nyck33** [comment]
I tried using Align on the same sequences:
```
from Bio import pairwise2
from Bio import SeqIO
from Bio.Align import substitution_matrices
#local alignment using Aligner:
from Bio import Align


matrix=substitution_matrices.load("BLOSUM62")
#seq1 = SeqIO.read("example_fasta_files/homo_sapiens_lactate.fasta", "fasta")
#seq2 = SeqIO.read("example_fasta_files/mus_musculus_lactate.fasta", "fasta")
# very long sequences
seq1 = SeqIO.read("example_fasta_files/corvyllus.fasta", "fasta")
seq2 = SeqIO.read("example_fasta_files/drosophilaAE014297.fasta", "fasta")
#params: match, mismatch, gap open, gap extend

seq_str1 = seq1.seq
seq_str2 = seq2.seq


match = 2
mismatch = -1
gap_open = -10
gap_extend = -0.5


aligner = Align.PairwiseAligner()
aligner.open_gap_score = gap_open
aligner.extend_gap_score = gap_extend
aligner.mode= 'local'
for alignment in aligner.align(seq_str1, seq_str2):
    print("Score = %.1f:" % alignment.score)
    print(alignment[:200])
```
and get
```
/home/nobu/anaconda3/envs/bio/bin/python /home/nobu/Desktop/BioInformatics/bio_pam_blosum/backend/trials/biopython_blosum.py

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```
The only other thing I did while it was executing was to run `top` in the terminal to watch the process's CPU usage.

**Comment by mdehoon** [comment]
I don't think there is a bug here. What you are trying to do will take a huge amount of memory; this causes the `MemoryError` with `Bio.pairwise2`. The `PairwiseAligner` in `Bio.Align` is more memory-efficient and can perform this alignment in principle, but with two very long sequences the alignment will take a very long time. I guess you killed the process at some point?

**Comment by nyck33** [comment]
pairwise2 was running over 20 minutes so I killed it and that was on protein sequences (Titin and another one around 28k residues long).  Is there any way to store the long sequences in secondary storage and to cache the section being aligned bit by bit, automatically or manually adjusting how much to read into memory at a time via parameters?

**Comment by mdehoon** [comment]
The memory error is not due to the sequences themselves but to the trace matrix used by the algorithm. Its size is `len(seq_str1) * len(seq_str2)` bytes.

**Comment by nyck33** [comment]
I looked for the underlying implementation to check if Numpy was used for the matrices but could not locate the source.  If not currently used, would using Numpy lower the memory footprint?  Then a dictionary can "translate" which number code refers to which amino acid residue or nucleotide.

**Comment by mdehoon** [comment]
@nyck33  It would not. At least in the pairwise aligner, the trace matrix is already fully optimized. If anything, numpy would use more memory.

**Comment by MarkusPiotrowski** [comment]
@nyck33 As @mdehoon explained, the memory usage will be at least `len(seq1) * len(seq2)`, that is because of the underlying algorithms. Regarding the implementation there is not much to optimize, `PairwiseAlginer` is more or less pure C, `pairwise2` has a significant part written in Python (the back tracing). However, we will not further optimise `pairwise2` because it will be deprecated in the near future.
Pairwise alignments are memory demanding, as long as you keep the matrix (or the matrices) in memory you will hit your system's memory capacity with very long sequences. A solution would be to write the data to disc but this would slow it down and this is not possible with the current `PairwiseAligner` or `pairwise2`. 

There are linear space algorithms for pairwise alignments (where the memory usage is linear to `len(seq)`). One is implemented in `Emboss'` Stretcher. Maybe you want to try that (https://www.ebi.ac.uk/Tools/psa/emboss_stretcher/).

**Comment by nyck33** [comment]
@MarkusPiotrowski @mdehoon Thanks for the link.
