### ISSUE TITLE
RuntimeError: DocSum Backend failed: Couldn't resolve #docsum?dbaf=sra, the address table is empty

### ISSUE THREAD

**Issue by eduardopdev** [biopython/biopython#3444]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0]
CPython
Linux-4.15.0-126-generic-x86_64-with-debian-stretch-sid
1.78
```
### Expected behaviour
I was messing around with the library to understand how it works. I have a file wit a bunch of SRA Ids and the idea was to pass them to esummary a hundred at a time and, after getting the result, print the number of the loop.
### Actual behaviour

Through the execution of the script, this error shows up:
`RuntimeError: DocSum Backend failed: Couldn't resolve #docsum?dbaf=sra, the address table is empty`
and i don't know what it means

### Steps to reproduce
This is my code:

```python
from Bio import Entrez

def get_docsum(id_list,database):
    handle = Entrez.esummary(db=database, id=','.join(id_list))
    record = Entrez.read(handle)
    return record

ids_file = open('file_with_the_id_list.txt','r').readlines()
for i in range(len(ids_file)):
    ids_file[i] = ids_file[i].strip()

number_of_loops = 1
id_list = []
while len(ids_file) > 0:
    id_list = ids_file[:100]
    xml_result = get_docsum(id_list, 'sra')
    ids = ids_file[100:]
    print(number_of_loops)
    number_of_loops += 1
```

And the file with the IDs looks like this:

`1415218
3910021
3772444
1551059
1560896
7091422
1042740
9210125
4413829
8149129
5865318
1303069
3638154
10721408
8916178
6466446
200743`

It actually has almost 80000 Ids, but i guess there's no need to put them all here

**Comment by mdehoon** [comment]
I think we will need you to investigate this a bit more. What is the smallest script that shows the problem?

**Comment by eduardopdev** [comment]
I am really really sorry. My code is wrong.
` ids = ids_file[100:]`
should be 
` ids_file = ids_file[100:]`
I corrected it and the script worked.
Sorry for making you lose your time.
