### ISSUE TITLE
Add support for EMBOSS-style Uniform Sequence Addresses (USAs)?

### ISSUE THREAD

**Issue by gouttegd** [biopython/biopython#3462]
Programs in the [EMBOSS package](http://emboss.open-bio.org/) use a concept known as *Uniform Sequence Addresses* (*USAs*) to refer to biological sequences from different sources (plain files, databases, or external programs) in a unified way.

USAs are [fully described](http://emboss.sourceforge.net/docs/themes/UniformSequenceAddress.html) in EMBOSS’s documentation, but to get an idea, here are some examples:

* `genbank::myfile.gb:SEQ1[20:100]` refers to the segment 20..100 from the sequence named `SEQ1` in the file `myfile.gb`, which is expected to be in the *GenBank* format;
* `uniprot:P49450` refers to the sequence with ID P49450 from Uniprot;
* `mydb:des:hippo` refers to all sequences whose *description* field contains the word *hippo*, in a locally-defined database named *mydb*;
* `swiss:fetchseq arg...|` refers to sequences returned by calling the hypothetical program `fetchseq`, which is here assumed to write SwissProt-formatted sequences to standard output.

Is there an interest to add support for this kind of syntax into Biopython?

I have a working implementation (I personally like the concept and use USAs abundantly) outside of Biopython that supports most of the features from the EMBOSS specification, I can make my code into a pull request. It would be a fair amount of code though, especially with the database access feature, so I figured I’d rather check if there is an interest before dropping a pull request.

If there *is* an interest I am also open to discussing the interface to use the feature. For now the interface I am envisioning would simply be something like the following:

```
from Bio.SeqIO.USA import read_usa, write_usa

records = read_usa("input_usa_as_a_string")
write_usa(records, "output_usa_as_a_string")
```

**Comment by peterjc** [comment]
I'd wondered about this myself some years back, and concluded it was a large amount of work to setup, and then an ongoing maintenance problem. I concluded we had enough trouble with keeping wrappers for online services already. Others may have different opinions?

**Comment by gouttegd** [comment]
I think it’s probably safe to say that either there’s no interest in such a feature or nobody thinks it is worth the hassle to implement and maintain. :)

I’m closing here, if anyone wants to weigh in feel free to re-open.
