### ISSUE TITLE
Calling a pairwise2.align.globalXX function with keyword arguments

### ISSUE THREAD

**Issue by jmueller95** [biopython/biopython#3467]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0]

CPython
Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic

1.70
```

### Expected behaviour

I want to call the pairwise alignment functions `pairwise2.align.globalXX` with keyword arguments to make my code easier to understand. I expect this to work exactly the same as if I used positional arguments.

### Actual behaviour
E.g. using the function `globalcx`, I get this error message:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3/dist-packages/Bio/pairwise2.py", line 406, in __call__
    keywds = self.decode(*args, **keywds)
  File "/usr/lib/python3/dist-packages/Bio/pairwise2.py", line 344, in decode
    len(args)))
TypeError: globalcx takes exactly 3 argument (0 given)
```
(other `globalXX` functions give analogous error messages).

### Steps to reproduce

```
from Bio import pairwise2

#This works fine
pairwise2.align.globalcx("HELLO",
                         "WORLD",
                         lambda a,b: -1 if a!=b else 0)

#This should give identical results, but instead yields the above error message
pairwise2.align.globalcx(sequenceA="HELLO",
                         sequenceB="WORLD",
                         match_fn=lambda a,b: -1 if a!=b else 0)
```

**Comment by MarkusPiotrowski** [comment]
@jmueller95 Thanks for reporting. Without having looked into the code, it is tempting to blame the lambda function. 

Would be helpful if you can check if
a. the error also appears if you define a function and call this and
b. what happens if you only use the keywords 'sequenceA' and 'sequenceB' and supply the lambda function without keyword?

Just to check if this is specific to the combination of keyword and lambda function or a general problem with the handling of the `match_fn` keyword.

Could you do this? Thanks!

**Comment by peterjc** [comment]
Keywords versus positional arguments might be down to how this code is written in C?

**Comment by jmueller95** [comment]
Hello Markus and Peter,
thank you for your replies, I didn't find the time to get back to it until now.

a. Indeed, the error still appears:
```
from Bio import pairwise2

def myfunction(a,b):
    return -1 if a!=b else 0

pairwise2.align.globalcx(sequenceA="HELLO",
                         sequenceB="WORLD",
                         match_fn=myfunction)
```
Still gives `TypeError: globalcx takes exactly 3 argument (0 given)`

b. I can't do that, since Python doesn't allow positional arguments to follow keyword arguments. However, I think it's safe to say that this has nothing to do with the lambda, since I can reproduce the error when using the `globalxx` function, which just takes the two sequences and no other parameters:

```
#This works fine
pairwise2.align.globalxx("HELLO",
                         "WORLD",)

#This gives: TypeError: globalxx takes exactly 2 argument (0 given)
pairwise2.align.globalxx(sequenceA="HELLO",
                         sequenceB="WORLD")
```

**Comment by MarkusPiotrowski** [comment]
@jmueller95 Ups, sorry, but I just realized that you are using Biopython 1.70? The keyword argument option was introduced in Biopython 1.77.

**Comment by jmueller95** [comment]
Oops, I didn't know. Yup, that was it. Thank you!
