### ISSUE TITLE
Help I am getting an Error setting up biopython

### ISSUE THREAD

**Issue by BTL1008** [biopython/biopython#3479]
### Setup

Hi I am trying to install bio python and I have tried doing the following
`pip install biopython==1.78
pip install biopython --upgrade
pip install Bio
pip3 install Bio
pip3 install biopython`

I keep getting the following error and I am not sure what I'm doing wrong.
`ERROR: Command errored out with exit status 1:
     command: 'c:\users\landr\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\landr\\AppData\\Local\\Temp\\pip-install-pvvz900d\\biopython_1762d3b712844d66830aa25a6426b76d\\setup.py'"'"'; __file__='"'"'C:\\Users\\landr\\AppData\\Local\\Temp\\pip-install-pvvz900d\\biopython_1762d3b712844d66830aa25a6426b76d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\landr\AppData\Local\Temp\pip-record-0dh050ay\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\landr\appdata\local\programs\python\python39\Include\biopython'`

Between these two errors were about 100 lines of code of `copying Bio\Entrez\DTDs\`
 
`ERROR: Command errored out with exit status 1: 'c:\users\landr\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\landr\\AppData\\Local\\Temp\\pip-install-pvvz900d\\biopython_1762d3b712844d66830aa25a6426b76d\\setup.py'"'"'; __file__='"'"'C:\\Users\\landr\\AppData\\Local\\Temp\\pip-install-pvvz900d\\biopython_1762d3b712844d66830aa25a6426b76d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\landr\AppData\Local\Temp\pip-record-0dh050ay\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\landr\appdata\local\programs\python\python39\Include\biopython' Check the logs for full command output.`

I am new to coding and am taking several Bioinformatic classes for my degree and I need Biopython before the course starts next week.

**Comment by peterjc** [comment]
I take it this is on Windows, with Python 3.9?

Try just "pip install biopython" after doing any pip updates.

You should probably not being ask pip to install "bio" which is something completely unrelated on PyPI: https://pypi.org/project/bio/

**Comment by BTL1008** [comment]
Turns out pipwin is all i had to do. oops

**Comment by peterjc** [comment]
Glad you could solve this - sadly I don't have a Windows development machine myself anymore, so didn't have the experience to give a more direct answer.
