### ISSUE TITLE
BiopythonParserWarning with (some) NCBI PGAP files

### ISSUE THREAD

**Issue by MrTomRod** [biopython/biopython#3481]
### Setup

```python3
import sys; print(sys.version)
# 3.9.1 (default, Jan 20 2021, 00:00:00) 
import platform; print(platform.python_implementation()); print(platform.platform())
# [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
# CPython
# Linux-5.10.14-200.fc33.x86_64-x86_64-with-glibc2.32
import Bio; print(Bio.__version__)
# 1.78
```

### Expected behaviour

Can parse NCBI PGAP output files without warnings.

### Actual behaviour

```python3
with open('FAM19160-i1-1.1.gbk', "r") as input_handle:
    for scf in SeqIO.parse(input_handle, "genbank"):
        for f in scf.features:
            break
        break
```

```text
/venv/lib64/python3.9/site-packages/Bio/GenBank/Scanner.py:1530: BiopythonParserWarning: Attempting to parse malformed locus line:
'LOCUS       FAM19160-i1-1_scf1 320564 bp    DNA     linear   BCT 25-MAY-2020\n'
Found locus 'FAM19160-i1-1_scf1' size '320564' residue_type 'DNA'
Some fields may be wrong.
  warnings.warn(
```

### Steps to reproduce

This warning happens whenever a line has fewer than 80 characters. The very first line in the file triggers it:

```LOCUS       FAM19160-i1-1_scf1 320564 bp    DNA     linear   BCT 25-MAY-2020```

However, the file was produced by NCBI's own [PGAP pipeline](https://github.com/ncbi/pgap) (version `2020-03-30.build4489`).

I cannot publish the file, unfortunately.

### Workaround

Disable warnings like this:

```python3
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    with open('database/organisms/FAM19160/genomes/FAM19160-i1-1.1/2_cds/FAM19160-i1-1.1.gbk', "r") as input_handle:
        for scf in SeqIO.parse(input_handle, "genbank"):
            for f in scf.features:
                break
            break
```

**Comment by peterjc** [comment]
I would try filing an issue with the NCBI PGAP team - Ideally they would follow the historic column based alignment if it fits.

https://github.com/biopython/biopython/blob/biopython-178/Bio/GenBank/Scanner.py#L1529

Would you like to file this issue?

They may disagree, in which case we'd probably have to remove the warning... or add some additional conditions to it?

**Comment by MrTomRod** [comment]
I checked newer files, and it seems that they have fixed the problem already! So I guess no action is required from your or their side. (Close the issue if you agree.)

It's just annoying that I've ended up with odd files...

**Comment by peterjc** [comment]
Thanks - there are enough slightly odd non-NCBI GenBank files out there that I would prefer to keep the warning if the LOCUS line is ambiguous.
