### ISSUE TITLE
error parsing cif files

### ISSUE THREAD

**Issue by FadiKhateeb** [biopython/biopython#3483]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
GCC 7.3.0
Linux-4.4.0-190-generic-x86_64-with-debian-stretch-sid
1.78
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

### Actual behaviour

Hi I am trying to extract some chains from this mmcif file,4UDF, so I wrote this code:

chain_letters=["A","B","I"]
io = MMCIFIO()
parser = MMCIFParser()
structure = parser.get_structure("4UDF", "4UDF.cif")
io.set_structure(structure)
io.save(structure.get_id()+".cif",select=SelectChains(chain_letters))

but when the code try to run this line:

structure = parser.get_structure("4UDF", "4UDF.cif")

we get this exception:
![image](https://user-images.githubusercontent.com/64142214/107922252-6cf9c900-6f78-11eb-82c9-33e20daedffb.png)

but I need to extract some chains from it, so how can I solve this problem?

Best,
Fadi

### Steps to reproduce

(*Please fill this in *)

**Comment by JoaoRodrigues** [comment]
Hi @FadiKhateeb ,

It seems that your structure has multiple instances of the same atom defined in that residue. I can reproduce the error here but with such a large structure it's hard to debug. I'll look into it over the next days.

**Comment by JoaoRodrigues** [comment]
Seems that the structure has an issue and indeed, the atom (and others) are defined twice. Maybe they should have an altloc field?

```
ATOM 2175   N N    . LYS B  2 91  ? 132.029  4.598    9.264    0.00 14.01 ? 91  LYS 1B N    1 
ATOM 2176   C CA   . LYS B  2 91  ? 130.914  3.677    9.073    0.00 12.01 ? 91  LYS 1B CA   1 
ATOM 2177   C C    . LYS B  2 91  ? 130.121  3.988    7.861    0.00 12.01 ? 91  LYS 1B C    1 
ATOM 2178   C C    . LYS B  2 91  ? 132.302  0.684    6.868    0.00 1.00  ? 91  LYS 1B C    1 
ATOM 2179   O O    . LYS B  2 91  ? 129.178  4.752    7.931    0.00 16.00 ? 91  LYS 1B O    1 
ATOM 2180   O O    . LYS B  2 91  ? 131.229  1.256    6.845    0.00 1.00  ? 91  LYS 1B O    1 
ATOM 2181   C CB   . LYS B  2 91  ? 129.941  3.571    10.261   0.00 12.01 ? 91  LYS 1B CB   1 
ATOM 2182   C CG   . LYS B  2 91  ? 130.532  2.822    11.459   0.00 12.01 ? 91  LYS 1B CG   1 
ATOM 2183   C CD   . LYS B  2 91  ? 129.687  2.915    12.728   0.00 12.01 ? 91  LYS 1B CD   1 
ATOM 2184   C CE   . LYS B  2 91  ? 128.602  1.839    12.822   0.00 12.01 ? 91  LYS 1B CE   1 
ATOM 2185   N NZ   . LYS B  2 91  ? 129.207  0.545    13.214   0.00 14.01 ? 91  LYS 1B NZ   1 
```

I would contact the RCSB PDB and ask about this structure.
