### ISSUE TITLE
Importing SeqIO Causes Crash

### ISSUE THREAD

**Issue by RPINerd** [biopython/biopython#3491]
So here is the literal entirety of my code:
`import sys`
`import os`
`from Bio import SeqIO`
`print("hello testing!")`
`r1_file = sys.argv[1]`
`print(r1_file)`
`r2_file = sys.argv[2]`
`print(r2_file)`

And here is the output of running this:
`Traceback (most recent call last):
  File "/home/rpinerd/bin/script.py", line 3, in <module>
    from Bio import SeqIO;
  File "/home/rpinerd/.local/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 658
    raise ValueError("No records found in handle") from None
`

What on earth could possibly be going on here? It's as if the simple act of importing is trying to run some sort of SeqIO.parse() call?

https://github.com/biopython/biopython/blob/7a887cfe6cfde2d88cc51179e64920a15adee83f/Bio/SeqIO/__init__.py#L659

**Comment by peterjc** [comment]
That is very odd. You haven't been editing the copy of Biopython? And you haven't got at local files named ``Bio.py`` or ``SeqIO.py`` which might be getting imported instead?

**Comment by RPINerd** [comment]
Nope, it is just installed with `pip install biopython` as per usual
I've even tried uninstalling/reinstalling as I have seen other users have some odd issues when dependencies are screwy

**Comment by mdehoon** [comment]
How exactly do you run your script?

**Comment by chris-rands** [comment]
Not sure it's related, but you seem to be running Python 3.9, which I don't think Biopython officially supports yet

**Comment by peterjc** [comment]
Good point. We should expand the CI testing to cover Python 3.9 now that it is out, which should be a formality but there could be a surprise there...

**Comment by peterjc** [comment]
Cross reference #3493 on testing with Python 3.9

**Comment by RPINerd** [comment]
Hmm I believe I am running Python3.9, I'll try it with an older version!
Still baffles me that this specific line in the import throws an error with no other outside access

> How exactly do you run your script?

python script.py file1.fastq file2.fastq

**Comment by RPINerd** [comment]
Okay looks like a versioning issue!

Python3.9 and Python3.7 give the error from the original post
Python3 seems fine!

**Comment by mdehoon** [comment]
I cannot replicate this bug with Python 3.7 or Python 3.8.

**Comment by peterjc** [comment]
Can you clarify what you mean by a versioning issue @RPINerd? I don't think this is a problem with any particular version of Python (our tests are working on Python 3.6, 3.7, 3.8 and now also on 3.9).

It may be you have one or more broken Python installations, or perhaps a ``$PYTHONPATH`` pointing to an older set of libraries?

**Comment by RPINerd** [comment]
> Can you clarify what you mean by a versioning issue @RPINerd?

Oh I just meant that on my end, it only works on python3. If no one else is having this issue then clearly my install of python3.7 and 3.9 are funky

When I get some time, I'll look into the installs as well as $PYTHONPATH to see if anything looks amiss, but in the meantime its working as intended so I'm going to go ahead and close this

Thanks everyone!!

**Comment by peterjc** [comment]
OK, good luck.
