### ISSUE TITLE
Record overwritten when appending to list

### ISSUE THREAD

**Issue by ViriatoII** [biopython/biopython#3497]
Hi,

I have a problem and think this might be a bug.. In this simplified example, I read a fasta file with 1 sequence manually break it into 2. I simply overwrite seq_record.seq and seq_record.id twice and append that to a list, so that in the end I can write both sequence fragments in one file. This works, but somehow **appending the 2nd seq_record overwrites the 1st one**

`       

        seq_record = SeqIO.parse("tmp.fasta", "fasta")

        # Save 2nd part of seq for later
        partB = seq_record.seq[200:]
        
        # Write 1st part of seq
        seq_record.id += "_1"
        seq_record.seq = seq_record.seq[:200)]
        all_seqs.append(seq_record)
        
        print(all_seqs)   # Notice this prints seq_record 1!
        
        # Write 2nd part 
        seq_record.id = seq_record.id[:-2] + "_2"
        seq_record.seq = partB        
        all_seqs.append(seq_record)

        print(all_seqs)   # Notice this prints seq_record 2 twice, first one was overwritten!
    `
    
1st print:    # Notice this prints seq_record 1!
```     
[SeqRecord(seq=Seq('AAAAATGAAAAGAGATAATAAACTTTTTATAGTAAATGAATGATGATTTTTTTA...GGA', SingleLetterAlphabet()), id='2_1', name='', description='', dbxrefs=[])]          ```

```
2nd print:    # Notice this prints seq_record 2 twice, first one was overwritten!
```
[SeqRecord(seq=Seq('AGGAATTCAACATTTTTTTTAGGACAGAGATGGTTTTACAACAGATTGAAAAAT...TGT', SingleLetterAlphabet()), id='2_2', name='', description='', dbxrefs=[]),        
SeqRecord(seq=Seq('AGGAATTCAACATTTTTTTTAGGACAGAGATGGTTTTACAACAGATTGAAAAAT...TGT', SingleLetterAlphabet()), id='2_2', name='', description='', dbxrefs=[])]
```

**Comment by chris-rands** [comment]
Can you show a fully reproducible example? seq_record here is initially defined as an iterator of records and not an individual record. 

Anyway, I think the issue is that you have a single seqrecord object here with two references to it (you never copy it). You would get the same with regular python lists, e.g. 

```
>>> a = [1,2,3]
>>> b = []
>>> b.append(a)
>>> b
[[1, 2, 3]]
>>> a[1] = "it changed"
>>> b
[[1, 'it changed', 3]]
>>> b.append(a)
>>> b
[[1, 'it changed', 3], [1, 'it changed', 3]]
>>> b[0] is b[1]
True
```

**Comment by ViriatoII** [comment]
Thank you @chris-rands! The problem was me not understanding this basic concept of references. 

This works:
```
from copy import copy

a = [1,2,3]

b = []

b.append(a)
print(b, "   before changing")

c= copy(a)
c[1] = "it changed"
print(b, "  just changed a")

b.append(c)
print(b,     "appended a")

b[0] is b[1]
```


Cheers,
Ricardo
