### ISSUE TITLE
SeqIO truncates sequence Ids in Fasta files

### ISSUE THREAD

**Issue by jaredsagendorf** [biopython/biopython#3500]
Fasta File:
```
>2GCC_1|Chain A|ATERF1|Arabidopsis thaliana (3702)
AKGKHYRGVRQRPWGKFAAEIRDPAKNGARVWLGTFETAEDAALAYDRAAFRMRGSRALLNFPLRVNSGE
```
Code:
```
    # download sequence for this pdbid
    url = "https://www.rcsb.org/fasta/entry/{}/download".format(pdbid)
    with urlopen(url) as response:
        with tempfile.NamedTemporaryFile(delete=False) as tmp_file:
            shutil.copyfileobj(response, tmp_file)
    
    with open(tmp_file.name) as tmp:
        records = SeqIO.parse(tmp, "fasta")

        for record in records:
            print(record.id)
            print(record.seq)
```

Output:
```
2GCC_1|Chain
AKGKHYRGVRQRPWGKFAAEIRDPAKNGARVWLGTFETAEDAALAYDRAAFRMRGSRALLNFPLRVNSGE
````

VERY annoying... why does it throw away most of the header info when that may be important?

**Comment by JoaoRodrigues** [comment]
The `id` attribute gives you the identifier only. Try `record.description`, does it help?

**Comment by jaredsagendorf** [comment]
Ah, yes that is what I needed! I guess "id" is delimited by white space? Although I'm sure much data does not follow that convention

**Comment by JoaoRodrigues** [comment]
You're welcome.

I'm sure there are better sources for the format reference but both [Wikipedia](https://en.wikipedia.org/wiki/FASTA_format#Description_line) and the [NCBI BLAST page](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp) seem to agree that spaces in that identifier field (after the first |) are a no no.

**Comment by peterjc** [comment]
Yes, breaking on the first white space is a near universal convention for interpreting FASTA.
