### ISSUE TITLE
Implementation of direct BLAST reads, MSA software

### ISSUE THREAD

**Issue by Chokyotager** [biopython/biopython#3507]
Hi there,

I've been using BP for a while now.

Is there any particular reason as to why Biopython does not have any system to directly do BLASTs through the Command Line using `os.system` or similar, upon detection of these optionally installed dependencies?

ClustalW, MultAlin, or even Magic-BLAST can be considered as third-party add-ons, and using Biopython to parse them into temp files, and read using SeqIO or similar, and then deleting the temporary files, similar to what NCBI's Genome Workbench does.

- Hilbert

**Comment by peterjc** [comment]
It does (currently), there are command line wrappers for helping you invoke various command line tools including Clustal and BLAST via ``subprocess`` (considered preferable over ``os.system``), and examples in the tutorial combining this with ``stdin`` and ``stdout`` and ``Bio.SeqIO``.

However, as of #3344 and our next release (Biopython 1.79), we're deprecating the command line wrappers in favour of encouraging calling ``subprocess`` directly. See discussion on #2877.

Do you have anything you'd like to add to this discussion?

**Comment by Chokyotager** [comment]
Yup, I'm aware of the current wrappers around it and have used them before, but it does seem a bit less elegant than having it output directly into Python objects.

Speaking of which, are there any plans to implement RNA sequencing software wrappers/or direct `subprocess` as you mentioned? And if not, are you guys open to adding said software?

If you guys are open to using other software I'm willing to try to code and maybe send a pull request for some of these things... MultAlin is very frequently used by the scientists I work with given its pretty image output, and I noticed that there seems to be no RNA processing capability in BP right now.

- Hilbert

**Comment by peterjc** [comment]
If you are asking about parsing, see also ``Bio.AlignIO`` (for clustal etc) and ``Bio.SearchIO`` (for blast etc). Most should accept ``stdin``.

I don't recall any active RNA based work, but that likely reflects the interests of the current contributors - perhaps you? Again though, writing command line wrappers just to build and execute the command line would be discouraged.

**Comment by Chokyotager** [comment]
Not asking about parsing, asking about directly running the command from BioPython for MultAlin. Wrappers make everything so much more complicated as it is.

Alrighty then, if there are generally no objections against doing the RNA work, I will give implementing it a shot. ;)

Apologies that my previous response was ambiguous.

**Comment by peterjc** [comment]
I'm still unclear what you mean but "running directly", perhaps executing the tool (using ``subprocess`` or other) _and_ parsing the output all in one go?

**Comment by Chokyotager** [comment]
Yup!

Save whatever output from the command line to a temp file, read it and parse it into Biopython's existing classes, and then secure erase the temp file.

**Comment by peterjc** [comment]
Or using stdin/stdout to avoid temporary files if possible and reliable.

OK, I understand your request now, but think that given we are intending to deprecate the existing command line wrappers, this does not make sense for multiple sequence alignments or BLAST.

This may still make sense from some specialised tools where there is some significant user advantage in invoking the command line tool, e.g. DSSP in our PDB code. I suggest you open new issue(s) for any RNA work you have in mind, and I will close this now. Thank you!
