### ISSUE TITLE
MafIO.MafIndex error

### ISSUE THREAD

**Issue by jodyhey** [biopython/biopython#3512]
3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-10-10.0.19041-SP0
1.78

and 

3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]
CPython
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.10
1.78

### Expected behaviour

generate an index of a large maf file  with the following code: 

from Bio.AlignIO import MafIO
mafdir =  r"E:\genemod\better_dNdS_models\drosophila\11_6_2020\cactus_work"
maff = mafdir + "\\" + "drosophila_cactus.maf"
mafindex = mafdir + "\\" + "drosophila_cactus.bio.mafindex"
idx = MafIO.MafIndex(mafindex, maff, "D_melanogaster")

### Actual behaviour

Traceback (most recent call last):
  File "E:\genemod\better_dNdS_models\drosophila\11_6_2020\Dmel_maf_work.py", line 6, in <module>
    idx = MafIO.MafIndex(mafindex, maff, "D_melanogaster")
  File "C:\Users\jodyhey\miniconda3\lib\site-packages\Bio\AlignIO\MafIO.py", line 279, in __init__
    self._record_count = self.__check_existing_db()
  File "C:\Users\jodyhey\miniconda3\lib\site-packages\Bio\AlignIO\MafIO.py", line 293, in __check_existing_db
    ).fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

### Steps to reproduce

happens everytime I run the code,  both on windows and ubuntu

**Comment by jodyhey** [comment]
followup.  Still got the same problem,  but now I think I'm using target_sequence properly and have confirmed that it does occur in the maf file.

MafIO.MafIndex("Xindex", "drosophila_cactus.maf", 'D_melanogaster.NC_004354.4')

Traceback (most recent call last):
  File "E:\genemod\better_dNdS_models\drosophila\11_6_2020\Dmel_maf_work.py", line 12, in <module>
    MafIO.MafIndex(mfi, maff, target)
  File "C:\Users\jodyhey\miniconda3\lib\site-packages\Bio\AlignIO\MafIO.py", line 282, in __init__
    self._record_count = self.__make_new_index()
  File "C:\Users\jodyhey\miniconda3\lib\site-packages\Bio\AlignIO\MafIO.py", line 411, in __make_new_index
    batch = list(islice(mafindex_func, 100))
  File "C:\Users\jodyhey\miniconda3\lib\site-packages\Bio\AlignIO\MafIO.py", line 462, in __maf_indexer
    % (self._target_seqname,)
ValueError: Target for indexing (D_melanogaster.NC_004354.4) not found in this bundle

**Comment by peterjc** [comment]
The exact string for the index sequence is likely critical, what names do you see from a simple ``Bio.AlignIO.read(maff, "maf")`` or equivalently ``MafIO.MafIterator(open(maff))``?

P.S. I suggest using ``os.path.join(...)`` rather than adding strings together with hard-coded path separators.

**Comment by jodyhey** [comment]
It seems the indexer only runs when all the reference strings match the target.  Is that the intended function? 

I'm now running a loop over all records in the maf file and writing separate maf files (using MafIO.Maf Writer.write_alignment()) based on reference strings,  one per chromosome.   Presumably  I can then index them individually. 

Does that make sense?   (more documentation would be helpful).

**Comment by peterjc** [comment]
My understanding is that it indexes with respect to the single specified reference. This makes sense if you are looking at a population of variants with a reference assembly.

https://biopython.org/docs/1.78/api/Bio.AlignIO.MafIO.html

You may find the test cases instructive?

https://github.com/biopython/biopython/blob/master/Tests/test_MafIO_index.py

**Comment by jodyhey** [comment]
MafIndex runs ok once I made chromosome specific maf files
