### ISSUE TITLE
Codon 'GT' is invalid

### ISSUE THREAD

**Issue by mertbozkir** [biopython/biopython#3522]
Hello everybody I am new with biopython tool. I have this Gene 

![image](https://user-images.githubusercontent.com/63906053/113477172-c9fa0180-9488-11eb-820a-334358ca52cd.png)

But when I trying to create sequence, I am getting this error. 

![image](https://user-images.githubusercontent.com/63906053/113477155-af278d00-9488-11eb-831c-de4841e34d24.png)

I don't understand why **Codon 'GT' is invalid**.

**Comment by MarkusPiotrowski** [comment]
Have a look at the read sequence, and you will see that your `Gene` still contains the line break characters (`\n`).

Thus, the error message is not `Codon 'GT' is invalid` but `Codon 'G\nT' is invalid`, which is of course true.

There are several way to remove the line breaks or to prevent reading them at first place. E.g. you could just add a header line like ">my_gene" to your file and then use `SeqIO` to read the sequence as fasta file.

**Comment by mertbozkir** [comment]
@MarkusPiotrowski Thank you for comment. I realize thath 'G\nT' is invalid. and (\n) thing. I fixed with your suggest. Thank you.
