### ISSUE TITLE
Using handle.close() in Bio.Entrez?

### ISSUE THREAD

**Issue by gumption** [biopython/biopython#353]
I've forked and am making some edits to the LaTeX source of Chapter 9 in the Biopython Tutorial and Cookbook ("Accessing NBCI's Entrez databases"), based on modifications I made in creating <a href="http://nbviewer.ipython.org/github/gumption/Using_Biopython_Entrez/blob/master/Biopython_Tutorial_and_Cookbook_Chapter_9.ipynb">an IPython Notebook version of the chapter</a> .

One thing that I noticed in this chapter was that there were few/no calls to the close() method of the handle objects created by calls to the EUtils wrapped by Bio.Entrez.

Based on the use depicted in the tutorial, I've been assuming that the handle objects act like file objects, and so it would be good programming practice to explicitly close such objects after they are processed (e.g., via calls to Entrez.read()).

Before I go through and add close() calls to the LaTeX source, I figured it would be good to get input on whether this would be a relevant practice to promote in the tutorial.

Input is welcome.

**Comment by peterjc** [comment]
Biopython ended support for Python 2.6 with Biopython 1.68, so we should now be safe to assume all the network handles will work as context managers.

**Comment by souravsingh** [comment]
@peterjc I would like to work on the issue.How do I start?

**Comment by peterjc** [comment]
@souravsingh Basically replace code examples like this in our documentation:

``` python
handle = some_online_function(...)
# do stuff with handle
handle.close()
```

with:

``` python
with some_online_function(...) as handle:
    # do stuff with handle
```

(and test the example before and after the change).

Here the online function could be things like ``efetch`` from ``Bio.Entrez`` etc.

Are you familiar with git? See also http://biopython.org/wiki/GitUsage

Are you familiar with GitHub pull requests?

**Comment by souravsingh** [comment]
@peterjc Is the issue now fixed?

**Comment by peterjc** [comment]
Probably not, although there are still bits of Python 2.7 where file like handles do not support with statements:

```
$ grep "\.close" Doc/Tutorial/chapter_entrez.tex
>>> handle.close()
>>> handle.close()
    out_handle.close()
    net_handle.close()
>>> handle.close()
>>> search_handle.close()
    fetch_handle.close()
out_handle.close()
    fetch_handle.close()
out_handle.close()
```

**Comment by peterjc** [comment]
I just tried this with the remaining Tutorial examples for Entrez, and it breaks under Python 2.7:

```
$ python --version
Python 2.7.10
$ python test_Tutorial.py
Running Tutorial doctests...
**********************************************************************
File "test_Tutorial.py", line 238, in __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066
Failed example:
    with Entrez.einfo() as handle:
        result = handle.read()
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.TutorialDocTestHolder.doctest_test_chapter_entrez_line_00066[4]>", line 1, in <module>
        with Entrez.einfo() as handle:
    AttributeError: addinfourl instance has no attribute '__exit__'
**********************************************************************
```

So until we drop Python 2.7, or deliberately wrap or monkey patch the returned handle which seems unwise, we can't do anything more here.

Closing issue.
