### ISSUE TITLE
When I use SeqIO.read(),it occured TypeError: __init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by XiaoxingDu** [biopython/biopython#3534]
I want to read a single fasta data, and I run :

```
> seq_file_read = SeqIO.read("D:/googledownload/sequence.fasta","fasta")
seq_file_read
```

But it ocurred:

```
> TypeError                                 Traceback (most recent call last)
<ipython-input-39-8f8281cb5053> in <module>
      1 # Loading FASTA file
      2 
----> 3 seq_file_read = SeqIO.read("D:/googledownload/sequence.fasta","fasta")
      4 seq_file_read



> C:\ProgramData\Anaconda3\lib\site-packages\Bio\SeqIO\__init__.py in read(handle, format, alphabet)
>     742     shown in the example above).  Instead use:
>     743 
> --> 744     >>> from Bio import SeqIO
>     745     >>> record = next(SeqIO.parse("GenBank/cor6_6.gb", "genbank"))
>     746     >>> print("First record's ID %s" % record.id)



> C:\ProgramData\Anaconda3\lib\site-packages\Bio\SeqIO\FastaIO.py in FastaIterator(handle, alphabet, title2ids)

>     192                 Seq(sequence, alphabet),
>     193                 id=first_word,
> --> 194                 name=first_word,
>     195                 description=title,
>     196             )
> 
> TypeError: __init__() takes 2 positional arguments but 3 were given
> 
```

I did input 2 positional arguments,why ?

My system:
python 3.8.5
Biopython 1.75

**Comment by peterjc** [comment]
I added markup to show the quoted code more clearly on GitHub.

Something strange is happening, normally in a traceback error message the relevant lines of code would be quoted - and the lines pointed at for line 774 of ``Bio\SeqIO\__init__.py`` are in the middle of a documentation comment. I wonder if there is something broken in your Python installation (more than one copy or something).

Also, it looks like from the appearance of ``alphabet`` arguments in the error text that you are using an old copy of Biopython - we dropped all the alphabet bits in Biopython 1.78.

Could you start with your system details please? You appear to be using Biopython (which version?), on Python (which version) from Anaconda3 on Windows.

**Comment by XiaoxingDu** [comment]
@peterjc  Hi hi, I felt so nice that you reply so fastly. I have updated my system information! ^^

**Comment by XiaoxingDu** [comment]
> I added markup to show the quoted code more clearly on GitHub.
> 
> Something strange is happening, normally in a traceback error message the relevant lines of code would be quoted - and the lines pointed at for line 774 of `Bio\SeqIO\__init__.py` are in the middle of a documentation comment. I wonder if there is something broken in your Python installation (more than one copy or something).
> 
> Also, it looks like from the appearance of `alphabet` arguments in the error text that you are using an old copy of Biopython - we dropped all the alphabet bits in Biopython 1.78.
> 
> Could you start with your system details please? You appear to be using Biopython (which version?), on Python (which version) from Anaconda3 on Windows.

**Comment by XiaoxingDu** [comment]
> I added markup to show the quoted code more clearly on GitHub.
> 
> Something strange is happening, normally in a traceback error message the relevant lines of code would be quoted - and the lines pointed at for line 774 of `Bio\SeqIO\__init__.py` are in the middle of a documentation comment. I wonder if there is something broken in your Python installation (more than one copy or something).
> 
> Also, it looks like from the appearance of `alphabet` arguments in the error text that you are using an old copy of Biopython - we dropped all the alphabet bits in Biopython 1.78.
> 
> Could you start with your system details please? You appear to be using Biopython (which version?), on Python (which version) from Anaconda3 on Windows.

Just now I install the newest version(Biopython 1.78), this error happened as well.@-@

**Comment by peterjc** [comment]
It does seem like you had Biopython 1.74 (which is quite old now), at least the quoted lines match:

https://github.com/biopython/biopython/blob/biopython-175/Bio/SeqIO/__init__.py#L744
https://github.com/biopython/biopython/blob/biopython-175/Bio/SeqIO/FastaIO.py#L194

The errors and the quoted files don't seem to match, which puzzles me though. It is as though the line numbers are from a different version to the text quoted?

Are you sure there isn't more than one copy of Biopython present? Do you have a copy of the Biopython source code in your working directory or something?

**Comment by peterjc** [comment]
Can you run this command in the terminal?

```
python -c "import Bio; print(Bio.__file__); print(Bio.__version__)
```

Or, in a new Python session:

```pycon
>>> import Bio
>>> print(Bio.__file__)
>>> print(Bio.__version__)
```

On my Mac I get this:

```
$ python -c "import Bio; print(Bio.__file__); print(Bio.__version__)"
/Users/xxx/miniconda3/lib/python3.7/site-packages/Bio/__init__.py
1.79.dev0
```

i.e. It will tell you where Python is importing Biopython from (my copy of Python 3.7 under conda here), and which version (I have the soon to be released but still in development 1.79).

**Comment by XiaoxingDu** [comment]
sure！
> (base) C:\Users\dolly.du>python -c "import Bio; print(Bio.__file__); print(Bio.__version__)
> C:\ProgramData\Anaconda3\lib\site-packages\Bio\__init__.py
> 1.78

**Comment by peterjc** [comment]
That looks fine, and the path matches that in your original report so installing Biopython 1.78 has replaced 1.75 (good).

Do you still get a similar error though? Could you copy and paste the new error output please?

**Comment by XiaoxingDu** [comment]
> That looks fine, and the path matches that in your original report so installing Biopython 1.78 has replaced 1.75 (good).
> 
> Do you still get a similar error though? Could you copy and paste the new error output please?

 I still get a similar error after using biopython=1.78.
 I try to build a new virtual env，download the necessary libraries, it runs correctly！It may have a copy of the Biopython source code in my base working directory.
Thanks for your  advice！

**Comment by peterjc** [comment]
I suggest you delete or move the copy of the Biopython source in your base working directory - probably that is being imported and used, not the Biopython installed at ``C:\ProgramData\Anaconda3\lib\site-packages\Bio``
