### ISSUE TITLE
SearchIO returns wrong hsp.hit_end if hit is revcomp'ed

### ISSUE THREAD

**Issue by ClaudiaPaetzold** [biopython/biopython#3553]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
System: CPython, Windows-10-10.0.18362-SP0
Biopython 1.78, running within a Jupyter Notebook

### Expected behaviour

I am using the SearchIO module to read in Exonerate output files in text format and I'm trying to extract the start and end coordinates of the target region. 

### Actual behaviour
If the target is matched in the 'input' direction, this works fine. However, if the target region is revcombed to match the query, the module returns a wrong end coordinate of the hit. 

### Steps to reproduce

I a pasting two exonerate results here, one where the target is reverse complemented:

> C4 Alignment:
> ------------
>        Query: UMUL-6227 
>        Target: NODE_1_length_270_cov_4.751295 [revcomp]
>        Model: protein2genome:local
>        Raw score: 269
>        Query range: 35 -> 91
>        Target range: 219 -> 51
>
>  36 : GlyValGluSerGlyGlyAsnAlaAlaLysAlaGlyLeuLysValGlyAspGlnValLeuTyrT :  57
>       !.!||||||!:!|||||||||||||||!:!|||||||||!:!!.!|||||||||||||||||||
>       AlaValGluAsnGlyGlyAsnAlaAlaArgAlaGlyLeuArgAlaGlyAspGlnValLeuTyrT
> 219 : GCTGTAGAGAATGGTGGAAATGCTGCGAGAGCCGGACTTAGAGCTGGGGACCAGGTACTCTATA : 156
>
>  58 : hrSerSerPhePheGlyAspGluLeuTrpProAlaAspLysLeuGlyPheThrLysThrAlaIl :  78
>       ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
>       hrSerSerPhePheGlyAspGluLeuTrpProAlaAspLysLeuGlyPheThrLysThrAlaIl
> 155 : CCAGCAGCTTCTTTGGAGATGAGCTTTGGCCTGCTGATAAGCTGGGCTTTACAAAAACTGCAAT :  93
>
>  79 : eGlnAlaLysProAspSerValTyrPheValValSerArg :  91
 >      ||||||||||||||||||||||||||||||||||||||||
>       eGlnAlaLysProAspSerValTyrPheValValSerArg
>  92 : CCAAGCAAAGCCAGATTCTGTCTATTTTGTTGTTAGCAGG :  52
>
>vulgar: UMUL-6227 35 91 . NODE_1_length_270_cov_4.751295 219 51 - 269 M 56 168

and one where the target is matched in the original direction:

>C4 Alignment:
>------------
>         Query: UMUL-6227 
>         Target: NODE_1_length_334_cov_52.322957
>         Model: protein2genome:local
>         Raw score: 287
>         Query range: 31 -> 99
>         Target range: 83 -> 287
>
>  32 : ValValIleThrGlyValGluSerGlyGlyAsnAlaAlaLysAlaGlyLeuLysValGlyAspG :  53
>       ||||||:!!! !!.!||||||.!!||||||||||||||||||||||||||||||!.!|||||||
>       ValValValLysAlaValGluGlyGlyGlyAsnAlaAlaLysAlaGlyLeuLysAlaGlyAspG
>  84 : GTTGTTGTTAAGGCCGTAGAGGGTGGTGGGAATGCTGCAAAAGCAGGGCTCAAGGCTGGGGACC : 147
>
>  54 : lnValLeuTyrThrSerSerPhePheGlyAspGluLeuTrpProAlaAspLysLeuGlyPheTh :  74
>       ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
>       lnValLeuTyrThrSerSerPhePheGlyAspGluLeuTrpProAlaAspLysLeuGlyPheTh
> 148 : AGGTACTCTACACCAGCAGTTTCTTTGGAGATGAACTTTGGCCCGCTGATAAGTTGGGATTTAC : 210
>
>  75 : rLysThrAlaIleGlnAlaLysProAspSerValTyrPheValValSerArgPheLeuGlyAla :  95
>       ||||||||||||||||||||||||||||||||||||||||||||||||||||! !|||..!  !
>       rLysThrAlaIleGlnAlaLysProAspSerValTyrPheValValSerArgSerLeuSerLeu
> 211 : AAAAACTGCCATTCAAGCAAAACCAGACTCTGTTTACTTTGTTGTCAGCAGGTCTCTTTCTCTC : 273
>
>  96 : GluValAspVal :  99
>       ...:!!  !|||
>       SerLeuPheVal
> 274 : TCTCTATTTGTT : 287
>
>vulgar: UMUL-6227 31 99 . NODE_1_length_334_cov_52.322957 83 287 + 287 M 68 204

if I run the following code on each of the files (denonted as 'testfile'): 

```python
from Bio import SearchIO
res = SearchIO.read(testfile, 'exonerate-text')
    # the id of the query
    print(res.id)


    for frag in res:

    # the id of the hit
        print(frag.id)
        print(frag.description)
        #  acess to the hsp of the hit
        # now access the elements of the hsp
        hsp = frag[0]
        print(hsp.hit_start)
        print(hsp.hit_end)
```

The output for the first example (revcombed) is:

```
UMUL-6227
NODE_1_length_270_cov_4.751295
[revcomp]
219
387
```

Here the expected end hit  51, instead, it produces 387. I cannot see where this result comes from.

for the second example (input direction) the output is:
```
UMUL-6227
NODE_1_length_334_cov_52.322957

83
287
```

Thank you.

**Comment by peterjc** [comment]
Fixed the markup, should be triple back-ticks not triple single quotes

**Comment by ClaudiaPaetzold** [comment]
I just noticed, that the coordinated for introns produced by `hsp.hit_inter_ranges` are also affected. That is to say, the coordinates are wrong, when the target sequence is reverse complemented. Please let me know, if you need an example for that as well.

**Comment by peterjc** [comment]
Pull request #3757 was merged, so that should have resolved this issue too - closing.
