### ISSUE TITLE
Problem with PPbuilder 

### ISSUE THREAD

**Issue by davidRFB** [biopython/biopython#3554]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
CPython
Linux-5.4.0-71-generic-x86_64-with-glibc2.10
1.78

### Expected behaviour

After load a pdb using the PDB.PDBparser and use the PPBuilder I only expect a Polypeptide objects that start in residue 1 and finish in 394. 

### Actual behaviour

However I am getting to polypeptides without any particular reason or change in protein chain. 
```
from Bio.PDB.PDBParser import PDBParser
from Bio.PDB.Polypeptide import PPBuilder
ppb=PPBuilder()
pdbid="1qlp.pdb"
structure = PDBParser().get_structure(pdbid.split(".")[0], 'PDBs/{}'.format(pdbid))
structure
ppb.build_peptides(structure)

output : [<Polypeptide start=1 end=20>, <Polypeptide start=23 end=394>] 
```

### Steps to reproduce
Execute de code in Actual Behaviour, 
[1qlp.txt](https://github.com/biopython/biopython/files/6519778/1qlp.txt)

Here is the 1qlp file with txt extension. The file has a PDB structure. 

Thank you very much.

**Comment by peterjc** [comment]
Looking at https://www.ebi.ac.uk/pdbe/entry/pdb/1qlp there was nothing obvious there about a break or uncertainly between residues 21 and 22...

Not a direct answer, but does it perhaps work better with mmCIF format? (The PDB format is obsolete)

**Comment by JoaoRodrigues** [comment]
The structure you attached has very weird geometry for that region (residues 20-24). This is a model right, not an actual structure downloaded from the PDB?

**Comment by davidRFB** [comment]
Yes is a model builded with PDBFIXER of openmm. Yes actually I saw the pdb from RSCB and there is a lot of missing residues that could break the builder. I would try with the mmCIF. Thank you very much.

**Comment by JoaoRodrigues** [comment]
PDBFixer is great to fill-in missing sidechains and other very small changes, definitely not for this level of modeling. One thing you can try to do is to run a tiny minimization with OpenMM afterwards to regularize the geometry of these bonds. Have a look at https://github.com/JoaoRodrigues/openmm_scripts for some ideas (or just to use the scripts out of the box).
