### ISSUE TITLE
GenomeDiagram track name and color problem

### ISSUE THREAD

**Issue by gonzalezibeas** [biopython/biopython#3561]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.8.5 (default, Jan 27 2021, 15:41:15) 
CPython
Linux-5.11.0-7614-generic-x86_64-with-glibc2.29
BioPython 1.78

### Expected behaviour

I am trying to plot a genome stretch from a GFF3 file with Genomediagram. Some tracks complement the information of the main one, they must be without the grey background but I want to name the tracks.

### Actual behaviour

When I set greytrack=0 to remove the grey background, the name of the track also disappears. I can not change the color of the greytrack, there is no option. Additionally, if I set greytrack_font_color='black', I can not change the color of the font.

### Steps to reproduce

from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.colors import Color
from Bio.Graphics import GenomeDiagram
from Bio.SeqFeature import SeqFeature, FeatureLocation

gdd = GenomeDiagram.Diagram('gene')
gdt_features = gdd.new_track(0, greytrack=True, name='gene_xx', greytrack_labels=1, greytrack_font_color='black',
                                greytrack_fontsize=20, greytrack_font_rotation=90,
                                scale=1, scale_largetick_interval=1000, scale_smalltick_interval=100)

**Comment by peterjc** [comment]
Correct, the grey track background is hard coded as ``colors.Color(0.96, 0.96, 0.96)`` and cannot currently be changed. If I recall correctly, I have added a full length full width feature (first to ensure drawn at the back) to cover it or replace it when I really wanted to alter the visual appearance. Does that work around suffice?

As to the follow on question, ``greytrack_font_color='black'`` is how to request black labels. Your question drew my eye to an underscore inconsistency with the argument name and attribute: ``.greytrack_fontcolor = greytrack_font_color``:

https://github.com/biopython/biopython/blob/biopython-178/Bio/Graphics/GenomeDiagram/_Track.py#L186

**Comment by gonzalezibeas** [comment]
Thank you for the answer. The problem is that if I set a white feature spanning the entire track, I also overlaps the name of the track, so it is not very helpful (unless I have not understood the advice).

Your are right, the "greytrack_fontcolor" works well, I finally can change the color of the font (although I have to use the Colors of reportlab, the typical 'red' or 'black' doesn't work). The "greytrack_font_color" doesn't work.

**Comment by peterjc** [comment]
In this context, I would put the track label on the background feature - not ideal, but workable.

Very often for a final publication I would make some final cosmetic tweaks in a PDF editor (e.g. z-order changes, or fine-tuning a label location). e.g. Figure 2 from https://doi.org/10.1371/journal.pone.0040683

**Comment by gonzalezibeas** [comment]
Incredible, it works, thank you. The only comment here is that this solution increases the complexity of the code (I have to add a feature and set the feature attributes for each track I want to name), but as you said it is workable. Thank you for the help.
