### ISSUE TITLE
KEGG Pathway doesn't deal with all boxes

### ISSUE THREAD

**Issue by iquasere** [biopython/biopython#3563]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
i3.7.6 (default, Jan  8 2020, 19:59:22)
CPython
imLinux-4.15.0-142-generic-x86_64-with-debian-buster-sid
1.77
```

### Expected behaviour

All function boxes in the map are altered, should all show similar altered background and label (KO...).

### Actual behaviour

Some boxes are altered, others are not.

### Steps to reproduce

```
from Bio.KEGG.REST import kegg_get
from Bio.KEGG.KGML import KGML_parser
from Bio.Graphics.KGML_vis import KGMLCanvas

with open('map00471.xml', 'w') as f: 
    f.write(kegg_get("ko00471", "kgml").read())
KGMLCanvas(KGML_parser.read(open('map00471.xml')), import_imagemap=True, label_orthologs=True, label_compounds=True, label_maps=True, label_reaction_entries=True).draw('test.pdf')
```

**Comment by peterjc** [comment]
Have you looked at the XML from KEGG? Is the difference there, or in our drawing code?

**Comment by iquasere** [comment]
The XML obtained with kegg_get seems to be missing many reactions. This behaviour is reproduced if I go to the [map at KEGG](https://www.kegg.jp/pathway/ko00471). The only boxes that can be interacted with are the same as with Biopython. Seems like KEGG hasn't built the links to these reactions yet.

**Comment by peterjc** [comment]
You'll have to ask KEGG then.

**Comment by iquasere** [comment]
Yes, sorry for the disturbance xD

**Comment by peterjc** [comment]
Good luck - and it was worth checking here, it might have been a problem in Biopython.
