### ISSUE TITLE
PDBParser does not work properly.

### ISSUE THREAD

**Issue by smallhuman83** [biopython/biopython#3574]
python version: 3.6.9
Biopython version: 1.78

O code
```python
from Bio.PDB.PDBParser import PDBParser
from Bio.PDB import PDBIO

parser=PDBParser()
structure=parser.get_structure("temp", "input.pdb")
ioHandle=PDBIO()
ioHandle.set_structure(structure)
ioHandle.save("out.pdb")
exit()
```

O Expected Behavior
- input file and outfile are the same, or the essential part of the input file should not be changed
  * Because this board does not accept .pdb, I changed the extension to .txt.

O Actual Behavior
- Codes of some ATOMS are changed to HETATM , and some coordinates are changed as well.
  * check serial numbers around 1900 and 3800
- two TER entries are lost.

[input.txt](https://github.com/biopython/biopython/files/6590502/input.txt)
[out.txt](https://github.com/biopython/biopython/files/6590503/out.txt)

[warning.txt](https://github.com/biopython/biopython/files/6590567/warning.txt)

**Comment by JoaoRodrigues** [comment]
Thanks for reporting this.

There is a reordering of the HETATM, but there is no loss of information. Same with TER statements: both are present. The PDB format specification is ambiguous when it comes to the placement of HETATM. Sometimes you will see then after the atom lines of the same chain, sometimes they all come at the end of the file.

The two TER statements are also in your output, at the end of each chain.

As for coordinate changes, there are none. Try running this:

```
from Bio.PDB import PDBParser

p = PDBParser()

s1 = p.get_structure("i", "input.txt")
s2 = p.get_structure("o", "out.txt")

s1_atoms = list(s1.get_atoms())
s2_atoms = list(s2.get_atoms())

assert len(s1_atoms) == len(s2_atoms)  # should pass

s1_atoms.sort()
s2_atoms.sort()

dist = [a - b for a, b in zip(s1_atoms, s2_atoms)]
print(sum(dist))  # should be 0.0
```
