### ISSUE TITLE
count of pubmed article pulled by websearch and through biopython API is different

### ISSUE THREAD

**Issue by ranjan-sumit** [biopython/biopython#3587]
### Count of pubmed article pulled by web search and through biopython API is different

I am reporting this as I found that when I tried searching pubmed articles through web search and API call from biopython, I found the differences. 

Steps to reproduce:

Code to pull counts from Web search/ we can also directly search on https://pubmed.ncbi.nlm.nih.gov/ . And term we are search for is rsv[title], we can search any other term as well

from bs4 import BeautifulSoup
import urllib.request
ret = list()

for p in range(9):

    url = "https://pubmed.ncbi.nlm.nih.gov/?term=rsv[title]&sort=pubdate&size=200&page={}".format(p+1)

    r = urllib.request.urlopen(url).read()

    soup = BeautifulSoup(r, 'lxml')

    ret.extend([x.text for x in soup.findAll('span', attrs={'class': 'docsum-pmid'})])

print(len(ret))

The result is : 1757

When I searched using biopython api:

from Bio import Entrez, Medline
Entrez.email = 'mlrsv@pfizer.com'
sres = Entrez.read(

            Entrez.esearch(
                db="pubmed",
                term='rsv[title]',
                retmax=1800,
                retstart=0,
                datetype="pdat",
                usehistory="y"
            )

         )

 print(len(sres['IdList']))

This give count as : 1754

Please let me know reason for difference in count of result.

**Comment by mdehoon** [comment]
I think this is an issue for NCBI.
This gives you the URL that Biopython is using:
```
>>> handle = Entrez.esearch(
...             db="pubmed",
...             term='rsv[title]',
...             retmax=1800,
...             retstart=0,
...             datetype="pdat",
...             usehistory="y"
...         )

>>> 
>>> handle.url
'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=rsv%5Btitle%5D&retmax=1800&retstart=0&datetype=pdat&usehistory=y&tool=biopython
```
and if you put that URL in your web browser, it will show 1754. So, accessing NCBI directly or via EUtils gives different answers; this is independent of Biopython.

**Comment by mdehoon** [comment]
@ranjan-sumit  Can we close this issue?

**Comment by ranjan-sumit** [comment]
Thanks for input. Closing the issue
