### ISSUE TITLE
A potential typo in SeqRecord

### ISSUE THREAD

**Issue by zhuchcn** [biopython/biopython#3591]
There is a  `__le___` method defined in the SeqRecord, with three trailing underscores instead of two. By any chance this is a typo?

https://github.com/biopython/biopython/blob/60b013cb81bedf671d5c77adcd4bfe3335482d3f/Bio/SeqRecord.py#L788

**Comment by mdehoon** [comment]
Yes that is a typo. I found a few more places in docstrings where a triple underscore was used instead of a double underscore.

**Comment by peterjc** [comment]
Would you like to submit a pull request to fix this @zhuchcn?

Using a simple grep for "___" I found others, but as @mdehoon noted only in docstrings:

```
$ grep "___" */*.py Bio/*/*.py Bio/*/*/*.py
```

**Comment by zhuchcn** [comment]
Sure, happy to! @peterjc

**Comment by peterjc** [comment]
Thank you!
