### ISSUE TITLE
Why is the SeqFeature attribute qualifiers (still) an OrderedDict?

### ISSUE THREAD

**Issue by fabianegli** [biopython/biopython#3594]
The current implementation of the SeqFeature attribute qualifiers likes them to be of type `OrderedDict` from the collections built in. It is not clear to me why this could not be a builtin dict. Since Python 3.6+ dictionaries are ordered anyway.

```
$ python3.6
>>> {1: 1, 2: 2}
{1: 1, 2: 2}
>>> {2: 2, 1: 1}
{2: 2, 1: 1}
```

**Comment by fabianegli** [comment]
```
$ git grep "OrderedDict("
Bio/AlignIO/StockholmIO.py:        ids = OrderedDict()  # Really only need an OrderedSet, but python lacks this
Bio/GenBank/Scanner.py:                    structured_comment_dict = OrderedDict()
Bio/GenBank/Scanner.py:                                    structured_comment_key, OrderedDict()
Bio/SearchIO/HHsuiteIO/hhsuite2_text.py:        hit_dict = OrderedDict()
Bio/SearchIO/_model/query.py:        self._items = OrderedDict()
Bio/SearchIO/_model/query.py:            new_hits = OrderedDict()
Bio/SeqFeature.py:        self.qualifiers = OrderedDict()
```

In Pyhton 3.6+ set is intrinsically ordered as well - so OrderedDict should be an overly complicated solution in `Bio/AlignIO/StockholmIO.py`, too.

The other occurrences would need additional inquiry and I am not sure about the usage of these OrderedDicts.

**Comment by fabianegli** [comment]
Hmmm, I missed that the order preserving feature of dict in Python 3.6 is considered an implementation detail. From https://docs.python.org/3/whatsnew/3.6.html#new-dict-implementation:

>The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon (this may change in the future, but it is desired to have this new dict implementation in the language for a few releases before changing the language spec to mandate order-preserving semantics for all current and future Python implementations; this also helps preserve backwards-compatibility with older versions of the language where random iteration order is still in effect, e.g. Python 3.5).

**Comment by fabianegli** [comment]
So the OrderedDict is necessary if the ordering is really desirable, but is it? 

And sets seem to be ordered, too.

But the real question is why the `ids` in Bio/AlignIO/StockholmIO.py would need an order at all? I think this question is worth asking for any instance of OrderedDict.

**Comment by peterjc** [comment]
We are about to drop Python 3.6 so little reason now to use the OrderedDict explicitly when base dict will do what we want.
https://mailman.open-bio.org/pipermail/biopython/2021-June/016872.html

**Comment by fabianegli** [comment]
> Desirable to round trip annotation rich sequence formats like GenBank

If I understand it correctly, this was potentially true for any SeqRecord with 2+ annotations in Python <3.6? But not since Python >=3.6

Indeed, since Python 3.7 dict ordering is guaranteed:
https://docs.python.org/3.8/whatsnew/3.8.html#collections

If you'd like I'll make a PR removing all Ordered dicts. I am not sure if this should be done with a deprecation notice before the change takes effect.

**Comment by peterjc** [comment]
Yes, that is correct. I think we can just make the switch now that Python 3.7 onwards (and effectively Python 3.6) offers order preserving dicts. PyPy also does this.

I see no reason for a deprecation notice here, there is no meaningful change in behaviour (unless someone was checking the exact type?)

**Comment by fabianegli** [comment]
There is a sorting in the SeqFeature print.

https://github.com/biopython/biopython/blob/870f623005ed1b95df877f618cbb12a815bd5696/Bio/SeqFeature.py#L298-L299

Should we remove that? I think it would be nice to get rid of that because the dicts are already ordered and sort removes that intrinsic ordering. Curious about your take.

**Comment by mdehoon** [comment]
Probably it's better to remove `sorted` here, though you may find that then some of the Biopython tests will fail, as the output order changed.

**Comment by fabianegli** [comment]
Indeed, the tests need to be adapted to the removed sorting.

**Comment by fabianegli** [comment]
I am not quite sure what to make of this part that references ordered dicts...

https://github.com/biopython/biopython/blob/870f623005ed1b95df877f618cbb12a815bd5696/Bio/SearchIO/_model/query.py#L599-L666

I don't see the added value of allowing a default. What am I missing? A simple `popped = d.pop() if d else default` does the trick without all the extra object instantiation and testing.

**Comment by fabianegli** [comment]
Removing the default in pop at least didn't break any tests... It smells like feature creep to me.

**Comment by fabianegli** [comment]
> Probably it's better to remove `sorted` here, though you may find that then some of the Biopython tests will fail, as the output order changed.

Should I remove the sorted in PR #3598 or in a separate PR?

**Comment by peterjc** [comment]
Either, personally I'd do a follow up PR

**Comment by peterjc** [comment]
Pop method discussion -> #3604

**Comment by fabianegli** [comment]
I am not sure anymore if it is clever to remove the sorting from the print statement. The sorting makes the print ordering independent form the construction details and I think this is a desirable feature, even if it would not be necessary in a world where the construction of the dict is guaranteed to remain the same. However, it is not and we don't know how people use the printed output. Also, I assume the sorting has a negligible performance impact overall (print is normally quite time consuming compared to sorting relatively small lists.)

Conclusion: I am not planning to create a PR to remove this sorting.

**Comment by peterjc** [comment]
That's fine by me.
