### ISSUE TITLE
Deprecations in SeqFeature

### ISSUE THREAD

**Issue by fabianegli** [biopython/biopython#3603]
Is there a schedule to add the deprecation warning as per:

https://github.com/biopython/biopython/blob/870f623005ed1b95df877f618cbb12a815bd5696/Bio/SeqFeature.py#L158-L175

**Comment by peterjc** [comment]
Now? I was thinking this having looked at the code recently on one of your pull requests.

**Comment by fabianegli** [comment]
Great! Help wanted and good first issue?

**Comment by peterjc** [comment]
Tagged, although a first timer may need a bit more guidance...

**Comment by rajpratyush** [comment]
hey is this issue open for work?

**Comment by peterjc** [comment]
Yes - are you clear on what we have in mind here, or do you need more guidance before tackling this with a PR?

**Comment by rajpratyush** [comment]
I think i have somewhat. could you please clarify whether my thoughts are correct or not?
i am thinking here just like there is a custom message while raise of typeerror when the condition `sub_features is not none:` similarly we have to raise depreciation warnings for location_operator, strand, ref, ref_db

**Comment by peterjc** [comment]
The four lines ``# TODO - Deprecation warning`` in the quoted text should replaced with something like:

```python
warnings.warn(
    "Using the XXX argument is deprecated, and will be removed in a future release. "
    "Please use YYY instead.", DeprecationWarning
)
```

(This code change should be formatted using the tool ``black``, see our CONTRIBUTING file for details)

You will also need to add ``import warnings`` to the top of the file next to the other standard library imports.

**Comment by rajpratyush** [comment]
Great and i have past experience of working with black and warnings in microaoft graspologic so i shall submit the PR by tonight

**Comment by rajpratyush** [comment]
@peterjc what is the replacement for the depreciated functions

**Comment by peterjc** [comment]
There are no functions being deprecated, only arguments to the ``__init__`` method. See the docstring which says:

```
        Note that the strand, ref and ref_db arguments to the SeqFeature are
        now obsolete and will be deprecated in a future release (which will
        give warning messages) and later removed. Set them via the location
        object instead.

        Note that location_operator and sub_features arguments can no longer
        be used, instead do this via the CompoundLocation object.
```

That will need updating too.

**Comment by rajpratyush** [comment]
sure i got it all what i needed @peterjc
