### ISSUE TITLE
Running the tests produces `Tests/.coverage` which git tracks

### ISSUE THREAD

**Issue by fabianegli** [biopython/biopython#3606]
### Setup

Running the tests in `Tests` with `python run_tests.py --offline` on a local machine produces a .coverage file that git marks as changed.

### Expected behaviour

git ignores the `Tests/.coverage` file.

### Actual behaviour

git doesn't ignores the `Tests/.coverage` file.

### Steps to reproduce

Follow the development setup and run the tests.

### Why it bothers me

I always have to make sure not to track commit the `Tests/.coverage` file.

### Proposed resolution

Add `Tests/.coverage` to `.gitignore`.

**Comment by peterjc** [comment]
Curious, I have an old ``Tests/.coveragerc`` from 2019, but no ``.coverage`` file. I wonder if you have something extra installed locally?

Anyway, by all means submit a pull request ignoring that file.

**Comment by fabianegli** [comment]
I must have produced that with one of my first ( and probably failed) attemts at running the tests. I can'r reproduce the behaviour. Closing the issue without changes to `.gitignore`.
