### ISSUE TITLE
Biopython global and local alignment methods not working on Heroku?

### ISSUE THREAD

**Issue by nyck33** [biopython/biopython#3607]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.8.0-55-generic-x86_64-with-glibc2.10
>>> import Bio; print(Bio.__version__)
1.78

```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)
I have a Plotly Dash application that calls global and local alignment methods:
```
alignments = pairwise2.align.globalds(seq1, seq2, self.matrix,
                                              self.gap_open, self.gap_extend,
                                              penalize_end_gaps=False)
```
and
```
alignments = pairwise2.align.localds(seq1, seq2, self.matrix,
                                              self.gap_open, self.gap_extend)
```
When manually testing locally,  both my Needleman and Waterman buttons run the methods and produce output which are the alignments.
But when deployed, I have a loading icon thing that shows the output is waiting for er, output but nothing appears.
So I am wondering if this is a Biopython issue, or a Heroku one say if I have to enable something else on Heroku to be allocated a CPU to perform calculations (on free dyno right now), etc.    

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)
No output, my app is here:  https://bio-pam-blosum.herokuapp.com/entrez-parameters
### Steps to reproduce

(*Please fill this in *)
"Instructions:\n "
                    "Please enter your email at the top input before making any API calls to NCBI."
                    "1. Search two sequences to align from the Entrez Page.\n"
                    "2. Run global or local alignment which are stored automatically.\n"
                    "3. Press button to make the aligned fasta file.\n"
                    "4. Press button to download aligned.fasta.\n"

**Comment by nyck33** [comment]
Do I need a worker for these alignment methods to execute on Heroku?

https://devcenter.heroku.com/articles/python-rq

**Comment by nyck33** [comment]
My Heroku logs:
```
2021-06-09T21:34:36.242086+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/_dash-update-component" host=bio-pam-blosum.herokuapp.com request_id=20d65242-8af7-4c54-9b9d-1f3e842385dc fwd="184.151.230.196" dyno=web.1 connect=2ms service=30000ms status=503 bytes=0 protocol=https
2021-06-09T21:34:36.560751+00:00 app[web.1]: [2021-06-09 21:34:36 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:9)
2021-06-09T21:34:37.592599+00:00 app[web.1]: [2021-06-09 21:34:37 +0000] [39] [INFO] Booting worker with pid: 39
2021-06-09T21:35:26.689465+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/_dash-update-component" host=bio-pam-blosum.herokuapp.com request_id=5312b37f-109d-4efb-8117-a3b6eb873922 fwd="184.151.230.196" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
2021-06-09T21:35:26.809748+00:00 app[web.1]: [2021-06-09 21:35:26 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:10)
2021-06-09T21:35:27.864494+00:00 app[web.1]: [2021-06-09 21:35:27 +0000] [54] [INFO] Booting worker with pid: 54
```

**Comment by MarkusPiotrowski** [comment]
Dear @nyck33 
As there does not exist a problem with Biopython itself, I'm out. I don't know anything about Heroku.

**Comment by mdehoon** [comment]
I agree with @MarkusPiotrowski  , this does not seem to be a Biopython problem.

**Comment by nyck33** [comment]
That's good to know.  I posted this without looking at any of what's under the hood for these Biopython methods.

**Comment by nyck33** [comment]
Actually I'm having problems now trying to queue the method in Python RQ.
The RQ docs here https://python-rq.org/docs/ state:
_Make sure that the function’s __module__ is importable by the worker. In particular, this means that you cannot enqueue functions that are declared in the __main__ module._

So when I try this:
```
job = q.enqueue(pairwise2.align.globalds,
                             args=(seq1, seq2, matrix,
                             gap_open, gap_extend),
                             kwargs={'penalize_end_gaps':False,
                             'one_alignment_only':True})
```
I get:
``
Traceback (most recent call last):
  File "/media/nobu/NTFSUbuWin/bio_pam_blosum/frontend/needleman_callbacks/entrez_callbacks.py", line 387, in run_needleman
    job = q.enqueue(pairwise2.align.globalds,
  File "/home/nobu/anaconda3/envs/bioapp/lib/python3.8/site-packages/rq/queue.py", line 419, in enqueue
    return self.enqueue_call(
  File "/home/nobu/anaconda3/envs/bioapp/lib/python3.8/site-packages/rq/queue.py", line 366, in enqueue_call
    job = self.enqueue_job(job, at_front=at_front)
  File "/home/nobu/anaconda3/envs/bioapp/lib/python3.8/site-packages/rq/queue.py", line 474, in enqueue_job
    job.save(pipeline=pipe)
  File "/home/nobu/anaconda3/envs/bioapp/lib/python3.8/site-packages/rq/job.py", line 608, in save
    mapping = self.to_dict(include_meta=include_meta)
  File "/home/nobu/anaconda3/envs/bioapp/lib/python3.8/site-packages/rq/job.py", line 552, in to_dict
    'data': zlib.compress(self.data),
  File "/home/nobu/anaconda3/envs/bioapp/lib/python3.8/site-packages/rq/job.py", line 242, in data
    self._data = self.serializer.dumps(job_tuple)
_pickle.PicklingError: Can't pickle <class 'Bio.pairwise2.alignment_function'>: attribute lookup alignment_function on Bio.pairwise2 failed
```
Does this mean I have to copy and paste the pairwise2.align() function into another function?

**Comment by mdehoon** [comment]
@nyck33  Can you try using the pairwise aligner instead? See section 6.6.2 in the Biopython documentation. It can be pickled, which seems to be the issue here with `Bio.pairwise2`.

**Comment by nyck33** [comment]
@mdehoon Thanks.  But I was wondering is there a way to get the alignment for each sequence separately so I can make a "aligned.fasta" file?  
Previously with pairwise2 I did something like:
```
            # get the sequences from the first alignment and store
            # for chart
            aligned_seq1 = alignments[0].seqA
            aligned_seq2 = alignments[0].seqB
            #jsonify
            aligned1_json = json.dumps(aligned_seq1)
            aligned2_json = json.dumps(aligned_seq2)
```
Later I load the jsons for seqA and seqB and make a file like:
```
>NP_001239370.1 protein TOPAZ1 [Bos taurus]
MPRAPPSGPTTAPGREDDARGLRKRSRRPGLGEAGGCGPEAEGLEESRQK
RMVARASGREEVESDKSAKEKRKVTEASSDDPQPGIDLVRKESLTSSES
PTVECSEFQSMAF---LQSLGKERL--------------VEGIKRRIRI
KCKSLESPALKMTENKATQNSKVEFQDELYKNTLKYSCNSLS---PGVE
NSVLKLHDCSCLSHSKDCNDENNLAYKPDGGCMHVPENSSKSKKENPRS
IDKTDPSNIPQLLQTEENVMRVSQLLLEENDSYLSKNNGLFSCLQSEKT
HSIEESSIGRKSRKRMKVSEKGNGMVIEMKFSNMCNKS----------E
MLQGN-----QTGADGKETEILEAKKSSLKV------LRKVNNNTLSPM
PLLSLPETGKKTSPEHCANAVFQKALEQLSK------------------
----------------------EETKNVSQP-LGCTSMDPPED--YFKS
KNSLVKSLSDCFPIEKRSSRESLKNEA--EESKYSCQRTIPMT------
GKRTWPCYSCARI------------------------SAQCWKKASLPQ
SRQDDFLKHQMNQTHLTDSKLMLQSSVTETNSASSSIEKLDSNLNCLPS
STVEPTSVVIKEPIVNDDEKMKSEELSRSASEVVSNTTEDTSLTNMTHN
TGSKKKDRGNLTKLNLTVASQDGQEANNSTSKTVHRKACITKQALVVPD
VKILNTGRLTNFKIPLLKNKTEKRKEINAKSSEREVYSPLELLDSVSGA
VRQSRTKENAVTVTSGPQSLSIQRSVIPVQASSDSFCSKNSCIIAPSFL
QGNNKQPSNHISASGRIISNNAAGSLTVENNTFSCDPGCIEKNPTFYSN
QEPFKAVSSEVSGRKMTENFSEIKVGFPDILKAYEDDVLLIDVIQDDPD
FGVSNEGELSFPSEVPMISQEPNVAEEHQSTDSKHMELPDKKEPSNALR
LPVPDPGSMKSEICASLSAASEIKHDSKDANISLGEVTHETSSNEKPRG
SEQTKSSDLDEKCRFSDKVAIREEKETISEVCRRDSKNTEIMVGECHLA
LVSKPLCLPVPLPPLNLNAHQEDTLLNPQMNDFRLPGKHSVLKLQNPEI
EIFKREKNVGVFQKPLGLMIPHRYCKFHFNTLRGCERSQCKFGHVPEQG
EKVCMDVFKKYISINELCLLQRAANMFMEYYRKFLPGIHFDLQVLNDLL
SLLKHCLLKEVFQVMNLCIMIKMLPALKILLKIFEYVATMKLRNAVPAL
NIFCKLLEAGMVLDPEHFNYIVKLLYQVQASKQEITAVLEMKSRLHMRQ
KKNWKCDLEAALNEIEHCKEKGDWTKLGNVYLNIKMSCEKFADFQRFCA
IAETLTKDCKEERPGVPFCEFAETVSKDLQNSEVDKTLLGRIGISAMYF
HKLLQWSKGRKVLDKLYELKIHFTSLKGLIGPEKLAPRCQIVNIAAEIF
KSGSLDGAIWVLRESEWIINTPVWPCDRLDVLNRHNLLCTIAHEILAKS
YRQTFEVLQNLPGFQNSQETVEVSQYSLLFNKLLDACIESNSLGMSSSV
EFMISKSIPIDFSFLRRLITSLGRSCLWLKARAHYKSALSLGCYPPLEG
LYRKLLLIPSYLSEIEMLLAIEIFLVSNASSIQSPGTSTQMLQIVLKRS
ENKSRSKDDYQAAVERLITAARISDPKLFIKHMTVNVNKEQVYSLEQCS
LKWLKENMKWAGKVWLFNNH
>NP_715630.3 MHC class I-like protein MILL1 precursor [Mus musculus]
--------------------------------------------------
-------------------------------------------------
----------MLLSRNLRALAAIHLWIVYLLLEDLLGTCAEGDNQRL--
-VASAPYQDIEITLEKPRVQAVAE------PHTLRYDLMALSLEVPGLP
FLTLRYFD-----------DEPFLPYK---------KNSSITDSQEPR-
------------------------------------------------I
DHLRAETWGRETDDLQEEEEQLKGMLAEITAQNGQNTDLHILQATFGCE
QRNGSTRGFWKLGYDGQNFLTFDQKTLTWTVDGPSTQKNKTFWKTRAPR
DLV-------KTFLDDICPAQLQRYLASLRNGLLNTGFPKVIVTFRNYP
GRITLTCRAFRLYTRVATLTWLQYRKPVQQKTFGSETILPSGDGTYQAW
SIRVLPGQESQFSCNLKHGNHNINEPAATEAPVYGARREQPPTSGVGSR
GKSLWSAMTTALVVISWTLSQKLMGPLLWFCSGGFCSFLQCW-------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
--------------------
```
I did not see in pairwise aligner the capability to do this.

**Comment by peterjc** [comment]
You can pull out the aligned sequences (more easily in the next release via #3584), and turn them into FASTA trivially easily.

**Comment by nyck33** [comment]
@peterjc  and @mdehoon  yes, thanks for that I just noticed I can cast to `str` then pull out until newlines.

**Comment by nyck33** [comment]
Toy example for reference purposes
```
x = "AAAAA"

y = "TTTTT"
aligner = Align.PairwiseAligner()

alignments = aligner.align(x,y)

target = str(alignments[0])

seq_arr = target.split()
```

**Comment by nyck33** [comment]
@mdehoon 

It pickled with Python RQ but there is an unpickling error of the result.

I used function tester() here: https://github.com/nyck33/bio_pam_blosum/blob/main/backend/q_tester.py

tester() calls `global_align2()` here: https://github.com/nyck33/bio_pam_blosum/blob/main/backend/biop_pairwise_aligner.py
which instantiates the `aligner = Align.PairwiseAligner()` in the function because it would not pickle if I instantiated outside the function and tried to use the instance object `aligner` as a parameter to a function being pickled.  

But then the result has an unpickling error:
```
(bioapp) nobu@nobu-IdeaPad-3-15IIL05:/media/nobu/NTFSUbuWin/bio_pam_blosum/backend$ python worker2.py & python q_tester.py
[31] 22090
17:56:03 default: biop_pairwise_aligner.global_align2('ACGTACGT', 'TACGTACG', Array([[ 4., -1., -2., -2.,  0., -1., -1.,  0., -2., -1., -1., -1., -1.,
  ...) (46de6b9b-4c76-4b74-a2aa-ddfdfa0c2511)
17:56:03 Worker rq:worker:7dda74e7fcb24620b3297de3c70f8b99: started, version 1.8.1
17:56:03 Subscribing to channel rq:pubsub:7dda74e7fcb24620b3297de3c70f8b99
17:56:03 *** Listening on high, default, low...
17:56:03 default: Job OK (46de6b9b-4c76-4b74-a2aa-ddfdfa0c2511)
17:56:03 Result is kept for 500 seconds
Traceback (most recent call last):
  File "q_tester.py", line 56, in <module>
    tester()
  File "q_tester.py", line 25, in tester
    print(f'job.get_id(): {job.get_id()}\n'
  File "/home/nobu/anaconda3/envs/bioapp/lib/python3.8/site-packages/rq/job.py", line 472, in result
    self._result = self.serializer.loads(rv)
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by mdehoon** [comment]
@nyck33  I am not familiar with RQ, but I would suggest to start from the smallest possible script, make sure it works, and then start adding lines back in until it stops working. Then you will know where the problem lies.

**Comment by nyck33** [comment]
@mdehoon  thanks!  I can return 1 alignment, ie. `return alignments[0]` and it works.

**Comment by mdehoon** [comment]
@nyck33  The issue may then have been that `alignments` is an iterator, not a list, i.e. `aligner.align` is a generator function. If you need all alignments, you could return `list(alignments)` instead of `alignments`. Note that the number of alignments can be extremely large, so it's better to check the number of alignments first before returning the list.

**Comment by nyck33** [comment]
@mdehoon thanks for the heads up.  I'll try something like check length of `list(alignments)` then return the first 10 or 20 or so.

**Comment by mdehoon** [comment]
@nyck33 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
