### ISSUE TITLE
bug in pairwise2

### ISSUE THREAD

**Issue by peterthorpe5** [biopython/biopython#3634]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)

3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]

import platform; print(platform.python_implementation()); print(platform.platform())

CPython
Windows-10-10.0.19041-SP0

import Bio; print(Bio.__version__)

1.72
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
When aligning 2 sequences, the alignment contains extra "-" in the top then in the bottom sequence to represent an amino acid change (please see below example), when actually the only change is a single amino acid, not insertion,, so no "|" in the visualization. 

    alignments = pairwise2.align.globalxx(wt_seq, alt_seq)
    # and then visulaising them:
    f_align.write(format_alignment(*alignments[0]))

Expected: Alignments where a single amino acid change is represented in the aliment as a "blank":

In this example instead of representing P for the L, it add a "-" in the top and bottom sequence. 

KTRK**P**-KPKKPTL*
||||  ||||||||
KTRK-**L**KPKKPTL*

### Actual behaviour

what should happen is that P is swapped with R, so this should be represented as not having a "|", just a blank and not having the extra "-" added in. 

### Steps to reproduce

alignments = pairwise2.align.globalxx(wt_seq, alt_seq)
f_align.write(format_alignment(*alignments[0]))

I hope that makes sense, it is hard to explain.

**Comment by MarkusPiotrowski** [comment]
This is not a bug, this is a feature ;-)

For the conditions you set (by using `globalxx`) two gaps are actually cheaper than a mismatch. In fact, gaps cost nothing with these settings, but a mismatch would have a penalty of 1.

For protein alignments I would recommend using `globaldx` with a proper matrix, as described in the docstrings, e.g.

```python
>>> from Bio.Align import substitution_matrices
>>> matrix = substitution_matrices.load("BLOSUM62")
>>> for a in pairwise2.align.globaldx("KEVLA", "EVL", matrix):
...     print(format_alignment(*a))
KEVLA
 ||| 
-EVL-
  Score=13
```
Read the docstrings and the manual (http://biopython.org/DIST/docs/tutorial/Tutorial.pdf , chapter 6.6) for more information about pairwise alignments. I'd also recommend using our new `PairwiseAligner`.

**Comment by peterthorpe5** [comment]
Dear Marcus,  Thank you very much!!

This is really useful, thank you.

Pete

**Comment by mdehoon** [comment]
@peterthorpe5 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
