### ISSUE TITLE
Don't use isinstance(..., int)

### ISSUE THREAD

**Issue by mdehoon** [biopython/biopython#3641]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

>>> import sys; print(sys.version)
3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:44:01) 
[Clang 12.0.0 (clang-1200.0.32.27)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-10.15.7-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.80.dev0

### Expected behaviour

Indexing works with numpy integers

### Actual behaviour

Indexing does not work with numpy integers

### Steps to reproduce

```python
from numpy import *
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

record = SeqRecord(Seq("ACGT"))
ii = zeros(10, int)
i = ii[0]
record[0]  # return 'A'
record[i]   # raises ValueError
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biopython-1.80.dev0-py3.9-macosx-10.9-universal2.egg/Bio/SeqRecord.py", line 519, in __getitem__
    raise ValueError("Invalid index")
ValueError: Invalid index
```

In `SeqRecord`'s `__getitem__`, Instead of `isinstance(..., int)`, you can use
```
import numbers
isinstance(0, numbers.Integral)
isinstance(i, numbers.Integral)
```
Both return `True`.

**Comment by peterjc** [comment]
I'm curious why would you want to pass a numpy integer to slice a SeqRecord, but if you really want to, this looks like a bigger issue:

```
$ grep -E "isinstance\(" */*.py Bio/*/*.py Bio/*/*/*.py | grep ", int" -c
234
```

(Some of those will be false positives in the sense they are using internal variables rather than user supplied int-like objects)

Anyway, we have plenty of ``isinstance(..., int)`` and variations on that like ``isinstance(..., (str, int))`` which you might want to change too - including in ``Bio/Seq.py`` and ``Bio/SeqFeature.py`` which would maybe be needed for this use case too?

**Comment by mdehoon** [comment]
> I'm curious why would you want to pass a numpy integer to slice a SeqRecord

This will happen if the integer was taken from a numpy array, as in the example above.
Note that Python allows numpy integers to be used as indices, for example for strings, lists, and tuples:

```python
>>> from numpy import *
>>> ii = arange(10)
>>> type(ii[0])
<class 'numpy.int64'>
>>> type(ii[1])
<class 'numpy.int64'>
>>> s = "tralala"
>>> t = ('a', 'bb', 'ccc')
>>> L = ['a', 'bb', 'ccc']
>>> s[ii[0]]
't'
>>> s[ii[1]]
'r'
>>> t[ii[0]]
'a'
>>> t[ii[1]]
'bb'
>>> L[ii[0]]
'a'
>>> L[ii[1]]
'bb'

```

**Comment by peterjc** [comment]
I suspect this will be more work than the two line change, for what seems a quite small improvement. Do you want to make a PR doing this?
