### ISSUE TITLE
SequenceRecord.Seq access raising `UndefinedSequenceError`breaks backward compatibility with pre-1.79 code

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#3645]
### Setup

Hi,
I'm reporting an issue trying to run a code base that has to deal with WGS master genbank records (that don't contain a sequence because they just refer to the accession numbers containing the actual sequences) while trying to write nice-to-read code and trying to stay compatible to pre-1.79 code bases.

In particular, I'll be running with these setups:

**1.79**
```
3.9.5 (default, May 26 2021, 13:30:54) 
[GCC 5.5.0]
CPython
Linux-5.4.0-73-generic-x86_64-with-glibc2.31
1.79
```

**1.78**
```
3.9.5 (default, May 26 2021, 13:30:54) 
[GCC 5.5.0]
CPython
Linux-5.4.0-73-generic-x86_64-with-glibc2.31
1.78
```

### Expected behaviour

Given a pre-1.78 code base like
```python
#!/usr/bin/env python3

import sys
from Bio import SeqIO
from Bio.Seq import UnknownSeq

def main():
    if len(sys.argv) < 2:
        print("Usage:", sys.argv[0], "<input gbk>")
        exit(2)

    records = list(SeqIO.parse(sys.argv[1], "genbank"))

    for record in records:
        if not check_record(record):
            print(record.id, "is not a good sequence")


def check_record(record):
    if not is_nucleotide_sequence(record.seq):
        print("uh oh, is this a protein sequence?")
        return False

    # many
    # more
    # things
    # here

    if is_wgs_seq(record):
        print("uh oh, this is a WGS master record")
        return False


def is_nucleotide_sequence(sequence):
    other = str(sequence).lower()
    for char in "acgtn":
        other = other.replace(char, "")
    return len(other) < 0.2 * len(sequence)

def is_wgs_seq(record):
    if isinstance(record.seq, UnknownSeq) and ('wgs_scafld' in record.annotations
                                               or 'wgs' in record.annotations
                                               or 'contig' in record.annotations):
        return True
    return False


if __name__ == "__main__":
    main()
```

The code runs like so:
```
./example.py AHIW00000000.1.gbk 
uh oh, this is a WGS master record
AHIW00000000.1 is not a good sequence
```

I can run in environments that did a `pip install biopython` after 1.79 released without breaking environments that are older than a month and thus still have 1.78 installed.

### Actual behaviour

The old code breaks, because instead of still using the newly-deprecated `UnknownSeq` and raising a `DeprecationWarning` to let developers know that they need to update their code, the new `UndefinedSequenceError` is raised:

**Using 1.79**
```./example.py AHIW00000000.1.gbk 
Traceback (most recent call last):
  File "/home/kai/dev/antismash/testfiles/./example.py", line 49, in <module>
    main()
  File "/home/kai/dev/antismash/testfiles/./example.py", line 15, in main
    if not check_record(record):
  File "/home/kai/dev/antismash/testfiles/./example.py", line 20, in check_record
    if not is_nucleotide_sequence(record.seq):
  File "/home/kai/dev/antismash/testfiles/./example.py", line 35, in is_nucleotide_sequence
    other = str(sequence).lower()
  File "/home/kai/.virtualenvs/newbp/lib/python3.9/site-packages/Bio/Seq.py", line 326, in __str__
    return self._data.decode("ASCII")
  File "/home/kai/.virtualenvs/newbp/lib/python3.9/site-packages/Bio/Seq.py", line 147, in decode
    return bytes(self).decode(encoding)
  File "/home/kai/.virtualenvs/newbp/lib/python3.9/site-packages/Bio/Seq.py", line 2795, in __bytes__
    raise UndefinedSequenceError("Sequence content is undefined")
Bio.Seq.UndefinedSequenceError: Sequence content is undefined
```

Now, you could update the code to use the new exception (optimised for a small diff):
```diff
--- example.py	2021-06-28 13:52:06.568909483 +0200
+++ example_new.py	2021-06-28 14:02:35.436253474 +0200
@@ -2,7 +2,7 @@
 
 import sys
 from Bio import SeqIO
-from Bio.Seq import UnknownSeq
+from Bio.Seq import UnknownSeq, UndefinedSequenceError
 
 def main():
     if len(sys.argv) < 2:
@@ -12,7 +12,11 @@
     records = list(SeqIO.parse(sys.argv[1], "genbank"))
 
     for record in records:
-        if not check_record(record):
+        try:
+            if not check_record(record):
+                print(record.id, "is not a good sequence")
+        except UndefinedSequenceError:
+            print("uh oh, no sequence provided?")
             print(record.id, "is not a good sequence")
```

But now it won't work on older Biopython releases:

```
Traceback (most recent call last):
  File "/home/kai/dev/antismash/testfiles/./example.py", line 5, in <module>
    from Bio.Seq import UnknownSeq, UndefinedSequenceError
ImportError: cannot import name 'UndefinedSequenceError' from 'Bio.Seq' (/home/kai/.virtualenvs/oldbp/lib/python3.9/site-packages/Bio/Seq.py)
```

To support both, I need to do a feature detection dance for the exception, and then branch around the new `try: ... except` logic added with the above patch, like so:

```diff
--- example_new.py	2021-06-28 14:02:35.436253474 +0200
+++ example_both.py	2021-06-28 14:08:48.498894832 +0200
@@ -2,7 +2,14 @@
 
 import sys
 from Bio import SeqIO
-from Bio.Seq import UnknownSeq, UndefinedSequenceError
+from Bio.Seq import UnknownSeq
+
+try:
+    from Bio.Seq import UndefinedSequenceError
+    HAVE_UNDEFINED_SEQUENCE_ERROR = True
+except ImportError:
+    HAVE_UNDEFINED_SEQUENCE_ERROR = False
+
 
 def main():
     if len(sys.argv) < 2:
@@ -12,12 +19,16 @@
     records = list(SeqIO.parse(sys.argv[1], "genbank"))
 
     for record in records:
-        try:
+        if HAVE_UNDEFINED_SEQUENCE_ERROR:
+            try:
+                if not check_record(record):
+                    print(record.id, "is not a good sequence")
+            except UndefinedSequenceError:
+                print("uh oh, no sequence provided?")
+                print(record.id, "is not a good sequence")
+        else:
             if not check_record(record):
                 print(record.id, "is not a good sequence")
-        except UndefinedSequenceError:
-            print("uh oh, no sequence provided?")
-            print(record.id, "is not a good sequence"
```

This adds a lot of clutter to even this simple example. On a real code base, this will be even worse.

**Comment by kblin** [comment]
And yes, the "simple fix" for this toy example would be to simply change the order of the checks, but that's less straightforward on a real code base with years of assumptions baked in what you can do with your `record.seq` and what you can't do with it.

**Comment by peterjc** [comment]
So at the fine level, this bit breaks now at the ``.lower()`` call saying ``UndefinedSequenceError`` instead:

```python
def is_nucleotide_sequence(sequence):
    other = str(sequence).lower()
    for char in "acgtn":
        other = other.replace(char, "")
    return len(other) < 0.2 * len(sequence)
```

Previously with the ``UnknownSeq`` I presume you'd have ended up with length zero unexpected bases and returned true?

**Comment by kblin** [comment]
Ok, I've just checked, and apparently the `isinstance(record.seq, UnknownSeq)` check will not trigger in 1.79, so reordering the checks doesn't solve the issue either: `record.seq type: <class 'Bio.Seq.Seq'> is an UnknownSeq instance: False`

**Comment by peterjc** [comment]
Cross reference https://github.com/biopython/biopython/blob/biopython-178/Bio/GenBank/__init__.py#L1411 which decided if the ``UnknownSeq`` was a run of ``N`` or ``X`` characters, perhaps this?

```python
def is_nucleotide_sequence(record):  # not sequence!
    try:
        return record.annotations["molecule_type"] != "protein" 
    except KeyError:
        pass
    # Fall back for Biopython 1.78:
    other = str(record.sequence).lower()
    for char in "acgtn":
        other = other.replace(char, "")
    return len(other) < 0.2 * len(sequence)
```

However, that needs checking a few versions back as the molecule type stuff shifted with the dropping of the alphabet module.

**Comment by kblin** [comment]
We can't rely on the molecule type in the real code, because our input might be FASTA, not GenBank.

**Comment by kblin** [comment]
The least painful-to-read code I could come up with to work with both 1.78 and 1.79 is
```python
#!/usr/bin/env python3

import sys
from Bio import SeqIO
from Bio.Seq import UnknownSeq

try:
    from Bio.Seq import UndefinedSequenceError
except ImportError:
    class UndefinedSequenceError(Exception):
        pass

def main():
    if len(sys.argv) < 2:
        print("Usage:", sys.argv[0], "<input gbk>")
        exit(2)

    records = list(SeqIO.parse(sys.argv[1], "genbank"))

    for record in records:
        if not check_record(record):
            print(record.id, "is not a good sequence")


def check_record(record):
    if is_wgs_seq(record):
        print("uh oh, this is a WGS master record")
        return False

    if not is_nucleotide_sequence(record.seq):
        print("uh oh, is this a protein sequence?")
        return False


def is_nucleotide_sequence(sequence):
    other = str(sequence).lower()
    for char in "acgtn":
        other = other.replace(char, "")
    return len(other) < 0.2 * len(sequence)

def is_wgs_seq(record):
    try:
        str(record.seq)
        is_unknown_seq = isinstance(record.seq, UnknownSeq)
    except UndefinedSequenceError:
        is_unknown_seq = True
    if is_unknown_seq and ('wgs_scafld' in record.annotations
                                               or 'wgs' in record.annotations
                                               or 'contig' in record.annotations):
        return True
    return False


if __name__ == "__main__":
    main()
```
But it contains a useless string conversion to trigger the new exception on 1.79.

**Comment by kblin** [comment]
And of course requires a re-order of the checks.

**Comment by kblin** [comment]
> Cross reference https://github.com/biopython/biopython/blob/biopython-178/Bio/GenBank/__init__.py#L1411 which decided if the `UnknownSeq` was a run of `N` or `X` characters, perhaps this?

Ooh, I think that's what bites us... if that detection worked properly for WGS records, it'd create an `UnknownSeq` instead of a `Seq` and the `isintance` check would work.

**Comment by mdehoon** [comment]
@kblin
> But it contains a useless string conversion to trigger the new exception on 1.79.
You could call `bytes` on the `Seq` object instead of `str`, then there won't be any conversion.

**Comment by kblin** [comment]
Ok, I guess basically what's breaking us is that `UnknownSeq` was ambiguous, and now it isn't, but Biopython made it mean the thing we didn't use it for. And because there's no backwards compatible replacement thing for the meaning we used it for, our code just breaks instead of giving a deprecation warning and giving us some time to migrate.

**Comment by mdehoon** [comment]
On 1.78 you will get a `TypeError`, which you can ignore if you call `bytes` after checking for `UnknownSeq`.

**Comment by kblin** [comment]
You mean like:
```python
def is_wgs_seq(record):
    try:
        is_unknown_seq = isinstance(record.seq, UnknownSeq)
        bytes(record.seq)
    except UndefinedSequenceError:
        is_unknown_seq = True
    except TypeError:
        pass
    if is_unknown_seq and ('wgs_scafld' in record.annotations
                                               or 'wgs' in record.annotations
                                               or 'contig' in record.annotations):
        return True
    return False
```
That's a lot of extra magic... :disappointed:

**Comment by mdehoon** [comment]
@kblin 

> Ok, I guess basically what's breaking us is that UnknownSeq was ambiguous, and now it isn't, but Biopython made it mean the thing we didn't use it for. And because there's no backwards compatible replacement thing for the meaning we used it for, our code just breaks instead of giving a deprecation warning and giving us some time to migrate.

Yes that is exactly right. Similarly, the alphabets we used to have were removed because they were ambiguous.

**Comment by peterjc** [comment]
> Ok, I guess basically what's breaking us is that `UnknownSeq` was ambiguous, and now it isn't, but Biopython made it mean the thing we didn't use it for. And because there's no backwards compatible replacement thing for the meaning we used it for, our code just breaks instead of giving a deprecation warning and giving us some time to migrate.

Almost - the previously ambiguous `UnknownSeq` is effectively gone (it remains only in deprecated form, and it still accepted in ``SeqRecord`` objects people might create for things like file output).

Cross reference #3446 but I think one of the related issues had more discussion on it.

**Comment by mdehoon** [comment]
@kblin  

> That's a lot of extra magic... 😞

Looks great to me!

**Comment by kblin** [comment]
Won't go through our linter, I guess I'll need something like
```python
#!/usr/bin/env python3

import sys
from Bio import SeqIO

try:
    from Bio.Seq import UndefinedSequenceError
except ImportError:
    from Bio.Seq import UnknownSeq
    class UndefinedSequenceError(Exception):
        pass

def main():
    if len(sys.argv) < 2:
        print("Usage:", sys.argv[0], "<input gbk>")
        exit(2)

    records = list(SeqIO.parse(sys.argv[1], "genbank"))

    for record in records:
        if not check_record(record):
            print(record.id, "is not a good sequence")


def check_record(record):
    if is_wgs_seq(record):
        print("uh oh, this is a WGS master record")
        return False

    if not is_nucleotide_sequence(record.seq):
        print("uh oh, is this a protein sequence?")
        return False


def is_nucleotide_sequence(sequence):
    other = str(sequence).lower()
    for char in "acgtn":
        other = other.replace(char, "")
    return len(other) < 0.2 * len(sequence)

def is_wgs_seq(record):
    try:
        # This will fail with a TypeError on Biopython < 1.79
        # It will fail with an UndefinedSequenceError on 1.79+ iff the sequence is empty
        bytes(record.seq)
        # Nothing failed, so the sequence isn't empty
        is_unknown_seq = False
    except UndefinedSequenceError:
        is_unknown_seq = True
    except TypeError:
        # Old Biopython, so check for UnknownSeq instead
        is_unknown_seq = isinstance(record.seq, UnknownSeq)
    if is_unknown_seq and ('wgs_scafld' in record.annotations
                                               or 'wgs' in record.annotations
                                               or 'contig' in record.annotations):
        return True
    return False


if __name__ == "__main__":
    main()
```

**Comment by mdehoon** [comment]
@peterjc 
`UnknownSeq` is still ambiguous:
```python
>>> from Bio.Seq import *
>>> u = UnknownSeq(9, character='A')
>>> v = u.translate()
UnknownSeq(3, character='K')
>>> v == "KKK"
True
```

**Comment by kblin** [comment]
Sure, but `Bio.GenBank` no longer uses it the way it used to.

**Comment by kblin** [comment]
Ok, after discussing this internally a bit, we'll just pin our current stable branch to 1.78, and replace the affected code for the next minor release to then require 1.79+. That seems more sane than the gymnastics required to support both versions.

Just a bit bad luck that both our release and biopython 1.79 happened on the same day. Oh well.

Closing this issue, because I guess everything in biopython works as designed...

**Comment by peterjc** [comment]
That was unlucky timing with the releases, and unfortunate you were using the old ambiguous behaviour which was taken away in Biopython 1.79 :(
