### ISSUE TITLE
questions about the cut site of HandIII

### ISSUE THREAD

**Issue by biozzq** [biopython/biopython#3647]
Hi,

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.10
>>> import Bio; print(Bio.__version__)
1.76
>>> 
```
rest_dict["HindIII"] = {
    "charac": (1, -1, None, None, "AAGCTT"),
    "compsite": "(?=(?P<HindIII>AAGCTT))",
    "dna": None,
    "freq": 4096.0,
    "fst3": -1,
    "fst5": 1,
    "inact_temp": 65,
    "opt_temp": 37,
    "ovhg": -4,
    "ovhgseq": "AGCT",
    "results": None,
    "scd3": None,
    "scd5": None,
    "site": "AAGCTT",
    "size": 6,
    "substrat": "DNA",
    "suppl": ("B", "C", "I", "J", "K", "M", "N", "O", "Q", "R", "S", "V", "X", "Y"),
}
```

I want to know which key represents the information of the cut site. Such as above example, for HindIII, we know the cut site should be A/AGCTT.

Best wishes,
Zheng zhuqing

**Comment by MarkusPiotrowski** [comment]
First, you can use the enzyme's `elucidate` method, which returns a string representation of the cutting site, with `^` representing the cut site on the sense/+ strand and `_` representing the cut site on the antisense/- strand:

```python
>>> from Bio.Restriction import EcoRI, KpnI, EcoRV, SnaI, HindIII
>>> EcoRI.elucidate()   # 5' overhang
'G^AATT_C'
>>> KpnI.elucidate()    # 3' overhang
'G_GTAC^C'
>>> EcoRV.elucidate()   # blunt
'GAT^_ATC'
>>> SnaI.elucidate()    # NotDefined, cut profile unknown.
'? GTATAC ?'
>>> HindIII.elucidate()
'A^AGCT_T'
>>>

``` 
Second, the keys you are asking for are `fst3` and `fst5`:
fst5 -> first 5' cut ((current strand) or None
fst3 -> first 3' cut (complementary strand) or None

The same information is stored in the key `charac` (first two numbers of the tuple). You can also use the method `characteristic` for this:
```python
>>> HindIII.characteristic()
(1, -1, None, None, 'AAGCTT')
>>>
```
You may also want to have a look at the Restriction manual: https://biopython.org/DIST/docs/cookbook/Restriction.html

**Comment by biozzq** [comment]
Thank you very much.
