### ISSUE TITLE
Outputting consensus line in an alignment

### ISSUE THREAD

**Issue by ijmcf** [biopython/biopython#365]
I can generate an alignment (using e.g. ClustalwCommandLine) and output it in ClustalW format:
        AlignIO.write(alignments, output_text_file_handle, "clustal")
But the output doesn't include the "consensus line" - the line of asterisks and periods that denotes the consensus. For example:

<pre><code>ATCG
ACGG
*..*
</code></pre>

Looking at the code in AlignIO.ClustalIO.ClustalWriter.write_alignment(), I see that it can write the consensus line if it's present in the _star_info attribute of the alignment. But that is specific to the Bio.ClustalW which is deprecated. The newer Bio.Align.Applications.ClustalwCommandline does not seem to generate the _star_info attribute. 

Any suggestions?

**Comment by jocelyne8** [comment]
FYI:
It looks like the _star_info doesn't get sliced.

No consensus line for this:
`
alignment._star_info = consensus
AlignIO.write(alignment[:, start:end], sys.stdout, 'clustal')
`

But it works for this:
`
palign = alignment[:, start:end]
palign._star_info = consensus[start:end]
AlignIO.write(palign, sys.stdout, 'clustal')
`

**Comment by peterjc** [comment]
Yes, you're right @jocelyne8 - but I am reluctant to change the class to special case slicing ``._star_info`` here.

We should resolve this generally, see #516.

**Comment by jocelyne8** [comment]
Sounds good. This was mostly for the next person who stumbles on this thread before the general fix is released.
