### ISSUE TITLE
Error while trying to set custom matrix

### ISSUE THREAD

**Issue by StephaneKazmierczak** [biopython/biopython#3658]
### Setup

3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]
CPython
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.17
1.79

### Expected behaviour

this code from the documentation to set a custom matrix return an error 
```python
matrix = {('A','A'): 1.0, ('A','B'): -1.0, ('B','B'): 2.0}
aligner.substitution_matrix = matrix
```
```txt
   2245             raise AttributeError("'PairwiseAligner' object has no attribute '%s'" % key)
-> 2246         _aligners.PairwiseAligner.__setattr__(self, key, value)
   2247 
   2248     def align(self, seqA, seqB, strand="+"):
```

ValueError: expected a matrix

### Actual behaviour

should return no error

### Steps to reproduce

run the snippet from documentation after installing latest version

**Comment by mdehoon** [comment]
@StephaneKazmierczak  Where do you find this in the documentation?

**Comment by mdehoon** [comment]
I found it here:

https://biopython.readthedocs.io/en/latest/chapter_align.html

However, this is pointing to an outdated version of the documentation. If you follow the "Edit on GitHub" at the top, it will take you to https://github.com/biopython/biopython/blob/sphinx/Doc/chapter_align.rst which apparently was last updated on July 31, 2019 by @peterjc .

**Comment by peterjc** [comment]
That is from an experimental branch https://github.com/biopython/biopython/tree/sphinx - see https://github.com/biopython/biopython/issues/907#issuecomment-512962377 - and https://biopython.readthedocs.io/ should not be live.

**Comment by peterjc** [comment]
So, this was out of date documentation (sorry about that), and would have reflected Biopython 1.74 which was released earlier in July 2019.

The current documentation is (and has been for a very long) at http://biopython.org/DIST/docs/tutorial/Tutorial.html and http://biopython.org/DIST/docs/tutorial/Tutorial.pdf

**Comment by mdehoon** [comment]
@StephaneKazmierczak  With recent versions of Biopython, you would use
```python
from Bio.Align import substitution_matrices
matrix = substitution_matrices.Array(data={('A','A'): 1.0, ('A','B'): -1.0, ('B','B'): 2.0})
aligner.substitution_matrix = matrix
```

**Comment by StephaneKazmierczak** [comment]
Thank you guys for the explanations
