### ISSUE TITLE
Entrez.efetch reaises a urllib.error.URLError

### ISSUE THREAD

**Issue by hainesm6** [biopython/biopython#3671]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.8.5 (default, Aug  3 2020, 18:14:17)
[GCC 9.3.0]

CPython
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29

1.79
```

### Expected behaviour

Entrez.efetch returns handle to the given fasta file.

### Actual behaviour

Returns the following error:

```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1123)>
```

### Steps to reproduce

```python
Entrez.email = "Your.Name.Here@example.org" # I used my actual email address.
handle = Entrez.efetch(db="nucleotide", id="AY851612", rettype="gb", retmode="text")
```

### Additional notes

Firstly I just want to say I don't often work with requests and haven't worked with urllib so appologies if I've done something obviously wrong in my setup. I did however find a workaround online using the following:
```python
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context
```
Still, this doesn't fix the underlying problem and instead uses an insecure connection and so feels wrong.

**Comment by peterjc** [comment]
This kind of error is usually something in the Python stack about missing SSL certificates, an unlikely to be Biopython specific.

How was your Python installed? I'm guessing you are using Python under the Windows Linux subsystem but that isn't clear either.

**Comment by hainesm6** [comment]
Yes, I am using Windows Linux subsystem. Although, I have used `Entrez.efetch` in the past using the same setup with no problem. I guess I thought it might be an update to urllib or NCBI making the `Enrez.efetch()` incompatible. However, If you can't reproduce the error feel free to close the issue and I'll have a deeper look.

**Comment by peterjc** [comment]
It works for me (from a Mac with Python installed via conda), so it isn't a general NCBI problem.

Can you double check what date your Windows Linux subsystem reports? It could be wrong which might explain ``certificate is not yet valid`` in the error message.

**Comment by hainesm6** [comment]
Spot on! My system clock was wrong and that was playing havoc with SSL certificates. I've updated the clock and works fine now. In case anyone else comes with the same issue, you can point them [here](https://github.com/microsoft/WSL/issues/6974). Thanks for your help with this @peterjc!
