### ISSUE TITLE
github actions macOS pypy broken

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#3674]
Compiling a working numpy from source for pypy under macOS is failing (and there are currently no pre-compiled wheels available for pip to use), e.g.

https://github.com/biopython/biopython/runs/3189739916

```
Traceback (most recent call last):
  File "run_tests.py", line 41, in <module>
    import numpy
  File "/Users/runner/hostedtoolcache/PyPy/3.6.12/x64/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

Fixing the environment to build numpy looks non-trivial:

https://foss.heptapod.net/pypy/pypy/-/issues/3268

Can we skip this entry in the test matrix? Just pypy on Linux ought to suffice.

**Comment by peterjc** [comment]
See also #3580

**Comment by peterjc** [comment]
See also https://github.com/biopython/biopython/pull/3675#issuecomment-890394740 which suggest at least in the short term we may want to skip pypy under Windows too.

**Comment by JoaoRodrigues** [comment]
So, keep PyPy only on Linux. Sounds reasonable, I personally never used PyPy so I defer to you!

**Comment by peterjc** [comment]
Well, I'd like to have pypy tested on all three OS - but Linux only is pragmatic in the short term.

Getting pypy on macOS should be trivial if and when there are numpy wheels for it.

Getting pypy on Windows to pass the tests should be doable too, but fiddly. I made a similar effort in the past with adding explicit handle closures, but I think I had a Windows machine for local testing back then. Right now I feel having the CI always fail is a bigger problem.
