### ISSUE TITLE
Allow using Entrez.read to parse local archives of pubmed 

### ISSUE THREAD

**Issue by ldorigo** [biopython/biopython#3683]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
CPython
Linux-5.8.0-63-generic-x86_64-with-glibc2.29
1.79

### Expected behaviour

I have a local copy of pubmed as described [here](https://dataguide.nlm.nih.gov/edirect/archive.html) and want to be able to parse the xml files in there using Entrez.read. 

### Actual behaviour
The parser fails with the following error message:

```
NotXMLError: Failed to parse the XML data (XML declaration not found). Please make sure that the input data are in XML format.
```

### Steps to reproduce

Download the attached file  [10.xml.txt](https://github.com/biopython/biopython/files/6916375/10.xml.txt) (it's an xml file - github doesn't allow files with ,xml extension...). This is a sample file from the pubmed archive. Run the following snippet:

```python
from Bio import Entrez

with open("10.xml", "rb") as f:
    Entrez.read(f)
```

**Comment by mdehoon** [comment]
The error message is correct.

**Comment by ldorigo** [comment]
Yes, but that doesn't change the underlying issue: it isn't currently possible to parse local pubmed archives with Entrez.read. 

If I manually add an xml declaration at the beginning of the file, the error is then:

```
ValueError: As the XML data contained neither a Document Type Definition (DTD) nor an XML Schema, Bio.Entrez is unable to parse these data. We recommend using a generic XML parser from the Python standard library instead, for example ElementTree.
```

**Comment by ldorigo** [comment]
So if I was to manually prepend something like `<?xml version="1.0" encoding="ISO-8859-15"?>` to every single file in the archive, the issue is similar to this one: #805 - there is no embedded DTD in the local pubmed files, and there is no way to tell Entrez.read to use a specific dtd - so no way to parse the local files.

**Comment by mdehoon** [comment]
Which DTD would you like to use?

**Comment by mdehoon** [comment]
Actually, if you look at the BIopython test files, you will find pubmed7.xml in Tests/Entrez with this header:
```
<?xml version="1.0" ?>
<!DOCTYPE PubmedArticleSet PUBLIC "-//NLM//DTD PubMedArticle, 1st January 2019//EN" "https://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_190101.dtd">
<PubmedArticleSet>
```
If you put that at the beginning of your file, and `</PubmedArticleSet>` at the end, you can parse the file with `Bio.Entrez`.

**Comment by ldorigo** [comment]
The specific dtd file is here:https://dtd.nlm.nih.gov/ncbi/pubmed/doc/out/190101/index.html 

But while passing it manually would be better than nothing, ideally Bio.Entrez.read should be able to use that automatically - or even better, provide an option to retrieve files from a local archive rather than the online database ( using the command-line utilities, using a local cache rather then online DB is as simple as setting an environment variable: https://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Local_PubMed_Cache)

**Comment by ldorigo** [comment]
> Actually, if you look at the BIopython test files, you will find pubmed7.xml in Tests/Entrez with this header:
> 
> ```
> <?xml version="1.0" ?>
> <!DOCTYPE PubmedArticleSet PUBLIC "-//NLM//DTD PubMedArticle, 1st January 2019//EN" "https://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_190101.dtd">
> <PubmedArticleSet>
> ```
> 
> If you put that at the beginning of your file, and `</PubmedArticleSet>` at the end, you can parse the file with `Bio.Entrez`.

Thanks, this will save me lots of time as a temporary workaround - but I think this issue is still valid: when doing large scale text processing, it's much better to have a local pubmed instance rather than querying the online database, and thus it would be great to have support for this in biopython.

**Comment by mdehoon** [comment]
Sorry, but you already have a local pubmed instance, right? Obtained using NCBI's guidelines as described here:

https://dataguide.nlm.nih.gov/edirect/archive.html

Then what is missing in Biopython?

**Comment by ldorigo** [comment]
> Sorry, but you already have a local pubmed instance, right? Obtained using NCBI's guidelines as described here:
> 
> https://dataguide.nlm.nih.gov/edirect/archive.html

Correct.

> Then what is missing in Biopython?

The ability to use biopython's Entrez utilities with that local archive :-)
Unless I missed something, there is no way to point biopython to the local archive rather than to the online database.

**Comment by mdehoon** [comment]
>  > Then what is missing in Biopython?

> The ability to use biopython's Entrez utilities with that local archive :-)
> Unless I missed something, there is no way to point biopython to the local archive rather than to the online database.

But your example
```python
from Bio import Entrez

with open("10.xml", "rb") as f:
    Entrez.read(f)
```
does exactly that, once you fix the `10.xml` file as explained above.

**Comment by ldorigo** [comment]
Example usecase: I am using `Entrez.egquery(term="foo")` to retrieve a list of pmids corresponding to my query. 

Currently, we were then retrieving the corresponding articles doing something like:

```python
        abstracts_handle = Entrez.efetch(db="pubmed", id=ids, retmode="xml")
        abstracts_record: Optional[EntrezElement] = Entrez.read(
           abstracts_handle, validate=False
        )
```

We now want to do the same but with a local pubmed archive. 

Ideally,  `Entrez.efetch` would take an additional argument which is the path to the local archive, and automatically return a handle to the xml files in the correct format for further processing (with Entrez.read).

**Comment by ldorigo** [comment]
> > > Then what is missing in Biopython?
> 
> > The ability to use biopython's Entrez utilities with that local archive :-)
> > Unless I missed something, there is no way to point biopython to the local archive rather than to the online database.
> 
> But your example
> 
> ```python
> from Bio import Entrez
> 
> with open("10.xml", "rb") as f:
>     Entrez.read(f)
> ```
> 
> does exactly that, once you fix the `10.xml` file as explained above.

`10.xml` is an example of one of the 38 million files that constitute the pubmed archive. While it is of course technically possible to "fix" them as per your description, it would 

1. Take many hours (120Gb need to be unzipped, rewriten, and re-zipped)
2. Render the local archive unusable with the entrez command-line utilities, since they expect the original xml, not the modified one.

**Comment by ldorigo** [comment]
It is of course also possible to prepend/append those lines in python, at runtime - but since Entrez.read expects a handle to binary data, it's not entirely trivial to do so...? And it also means that anyone who wants to do this in the future needs to find this issue first :-)

**Comment by mdehoon** [comment]
> Ideally, Entrez.efetch would take an additional argument which is the path to the local archive, and automatically return a handle to the xml files in the correct format for further processing (with Entrez.read).

There is no easy way of doing that. The database is too large to keep in memory, so you would have to use some efficient database implementation like mysql. Not something Biopython can easily replicate.

**Comment by mdehoon** [comment]
> 10.xml is an example of one of the 38 million files that constitute the pubmed archive. While it is of course technically possible to "fix" them as per your description, it would

>    Take many hours (120Gb need to be unzipped, rewriten, and re-zipped)
>    Render the local archive unusable with the entrez command-line utilities, since they expect the original xml, not the modified one.

The problem is that the "XML" file you got from the Entrez command-line utilities is not an XML file. The XML declaration is missing, and the reference to the DTD is missing. This is something to complain to NCBI about.

**Comment by ldorigo** [comment]
Getting to a local file given a pmid is pretty easy, I actually already wrote code for it - no need for a database: 

```python
def get_local_file(pmid, archive_path):
    basepath = Path(archive_path)
        pmid_full = pmid.zfill(8)
        finalpath = (
            basepath
            / pmid_full[:2]
            / pmid_full[2:4]
            / pmid_full[4:6]
            / f"{pmid}.xml.gz"
        )
       return gzip.open(finalpath, "rb") # returns a handle, but doesn't work as per our previous discussion
```

**Comment by mdehoon** [comment]
Then it's easy. Read the data from `get_local_file`, add the missing bits, store the result in a `BytesIO` object, and call `Entrez.read` on that.

**Comment by ldorigo** [comment]
> > 10.xml is an example of one of the 38 million files that constitute the pubmed archive. While it is of course technically possible to "fix" them as per your description, it would
> 
> > Take many hours (120Gb need to be unzipped, rewriten, and re-zipped)
> > Render the local archive unusable with the entrez command-line utilities, since they expect the original xml, not the modified one.
> 
> The problem is that the "XML" file you got from the Entrez command-line utilities is not an XML file. The XML declaration is missing, and the reference to the DTD is missing. This is something to complain to NCBI about.

I see pretty small chances of success getting the NCBI to make a backwards-incompatible change to their pubmed dumps - but of course I also understand if this is too niche to include in the actual biopython package.

**Comment by mdehoon** [comment]
NCBI may be willing to add an optional argument to their Entrez-Direct utilities to get XML files with the appropriate header. Such an option may even already exist. If not, adding it on the fly should work. Yes I think this is too much of a niche issue for inclusion in Biopython - it would basically be a workaround for a bug elsewhere.

**Comment by mdehoon** [comment]
@ldorigo  Can we close this issue?

**Comment by ldorigo** [comment]
Yes, thank you for the quick response and solution :-)
