### ISSUE TITLE
lcc.lcc_mult returns extra zero value

### ISSUE THREAD

**Issue by ybendana** [biopython/biopython#3696]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
CPython
Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
1.78

### Expected behaviour

[1.9056390622295662]

### Actual behaviour

[0, 1.9056390622295662]

### Steps to reproduce

lcc.lcc_mult('ACGATAGC', 8)

In addition according the [article](https://www.researchgate.net/publication/229964618_Sequence_Complexity_and_Composition), the calculation of LCC uses log base 4 but the implementation uses log base 2.  That is why for the example sequence 5 in Table 1 the value shown is half the function value.

**Comment by sbassi** [comment]
I reproduced the error, working on this now.
