### ISSUE TITLE
[Question] need documentation on submat module and matrix details

### ISSUE THREAD

**Issue by StephaneKazmierczak** [biopython/biopython#3719]
Hello, 

I am working on some peptide/protein alignments with biopython, my collegue are particularly interested in conserving the structure with the aligment. So far I worked with the Blosum62 and PAM30 matrix. 
But I noticed the module "bio.submat" as other matrix too, 

``` python
from Bio.SubsMat import MatrixInfo
print(MatrixInfo.available_matrices)
```
``` txt 
['benner6', 'benner22', 'benner74', 'blosum100', 'blosum30', 'blosum35', 'blosum40', 'blosum45', 'blosum50', 'blosum55', 'blosum60', 'blosum62', 'blosum65', 'blosum70', 'blosum75', 'blosum80', 'blosum85', 'blosum90', 'blosum95', 'feng', 'fitch', 'genetic', 'gonnet', 'grant', 'ident', 'johnson', 'levin', 'mclach', 'miyata', 'nwsgappep', 'pam120', 'pam180', 'pam250', 'pam30', 'pam300', 'pam60', 'pam90', 'rao', 'risler', 'structure']
```

The problem is that I can't find documentation outside of blosum and pam on the biopython website  
and can't find anything in the github, it seems the module is missing from the sources.

**Comment by peterjc** [comment]
I have good news and bad, ``Bio.SubMat`` was deprecated in Biopython 1.78, and has now been removed in #3713.

As an alternative, please consider using ``Bio.Align.substitution_matrices`` which hopefully is better documented.

**Comment by peterjc** [comment]
As per https://github.com/biopython/biopython/tree/master/Bio/Align/substitution_matrices/data/README.txt 

```
The BLOSUM and PAM matrices in this directory were obtained from NCBI
(ftp://ftp.ncbi.nih.gov/blast/matrices/).

All other matrices were obtained from the primary literature, as indicated in
the header of each file.
```

**Comment by mdehoon** [comment]
> I have good news and bad, `Bio.SubMat` was deprecated in Biopython 1.78, and has now been removed in #3713.
> 
> As an alternative, please consider using `Bio.Align.substitution_matrices` which hopefully is better documented.

I only see good news here :-).

The old `Bio.SubsMat` module did not have references to the primary literature but instead pointed to a web page with incomplete reference information. That web page had since been removed and is only accessible through the web archive. The new `Bio.Align.substitution_matrices` module has references to the primary source for all matrices.

**Comment by StephaneKazmierczak** [comment]
Thank you guys for the clarification, I will check out and use the new module ! sorry I couldn't find it earlier !

**Comment by peterjc** [comment]
Great - and if you can see any documentation improvements we can make, we'd be happy to hear them (via a pull request or issue). I'm going to close this issue now, thank you.
