### ISSUE TITLE
Can't write peptide genbank files with extra long headers

### ISSUE THREAD

**Issue by seanrjohnson** [biopython/biopython#3732]
This line
https://github.com/biopython/biopython/blob/cb4f6edf59f9434c177dcd1af21dd588f9dfa161/Bio/SeqIO/InsdcIO.py#L799

should be changed to:

```
splitline[3].strip() == "aa"
```

because in genbank peptide files there isn't a molecule type, so that field gets eaten by the split and it won't ever be `""`

**Comment by peterjc** [comment]
I think you're right - would you like to submit that as a pull request please?

**Comment by peterjc** [comment]
You may be right, I've not looked at NCBI GenPept files to check.

But still, would you like to submit that as a pull request please, with a test case ideally.

**Comment by seanrjohnson** [comment]
Ok, I submitted the patch. Also, here is a link to an example peptide record from NCBI, so you can see that the locus line does not have a molecule type specified, but it has the rest of the locus fields.

[https://www.ncbi.nlm.nih.gov/Class/MLACourse/Modules/Format/sample_record_genpept.html](https://www.ncbi.nlm.nih.gov/Class/MLACourse/Modules/Format/sample_record_genpept.html)

**Comment by seanrjohnson** [comment]
Anything else you need from me on this? I saw that a couple of the CI tests failed, but as far as I can tell, the failed tests don't have anything to do with the code I changed.
