### ISSUE TITLE
ValueError: Unknown prefix 'ali' with uri 'http://www.niso.org/schemas/ali/1.0/'

### ISSUE THREAD

**Issue by raceee** [biopython/biopython#3734]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.7.11 (default, Jul  3 2021, 18:01:19) 
[GCC 7.5.0]
CPython
Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
1.79
```

### Expected behaviour

Entrez.parse returns a generator that can be lazily iterated through

### Actual behaviour
Entrez.parse breaks because of unrecognized prefix when loop is entered

### Steps to reproduce
I understand that ```fetched = Entrez.efetch(db='pmc', id=id)``` can take more than 1 id I was iterating for explicitness 
```python
handle = Entrez.esearch(db="pmc", term="open access[filter]", retmax="10" )
record = Entrez.read(handle)
for id in record["IdList"]:
  fetched = Entrez.efetch(db='pmc', id=id)
  rrr = Entrez.parse(fetched, validate=False, escape=False) # type(rrr) returns generator
  for a in rrr:
   print(a)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-a2a93f872fc4> in <module>()
      3   rrr = Entrez.parse(fetched, validate=False, escape=False)
      4   print(type(rrr))
----> 5   for a in rrr:
      6     print(a)
      7 

1 frames
../Modules/pyexpat.c in StartNamespaceDecl()

/usr/local/lib/python3.7/dist-packages/Bio/Entrez/Parser.py in startNamespaceDeclHandler(self, prefix, uri)
    469                 assert uri == "http://www.w3.org/1999/xlink"
    470             else:
--> 471                 raise ValueError("Unknown prefix '%s' with uri '%s'" % (prefix, uri))
    472             self.namespace_level[prefix] += 1
    473             self.namespace_prefix[uri] = prefix

ValueError: Unknown prefix 'ali' with uri 'http://www.niso.org/schemas/ali/1.0/'
```

**Comment by peterjc** [comment]
#3738 adds the DTD file to Biopython but why wasn't it automatically  downloaded?

**Comment by mdehoon** [comment]
@peterjc  It was not just the missing DTDs, NCBI was also changing how to refer to the DTD from the XML. Seems to be for PubMed Central downloads only, though; the other databases are not affected as far as I have checked.

**Comment by peterjc** [comment]
Ah, I see the Python changes now (``if prefix == "ali":`` etc), GitHub wasn't showing that by default. Thanks!

**Comment by mdehoon** [comment]
You can download the current Biopython code from github and install it. Or, you could just download the new `Bio/Entrez/Parser.py` file and copy it over your existing one.
```
>>> from Bio.Entrez import Parser
>>> Parser.__file__
```
will tell you where your current one is located.
