### ISSUE TITLE
Add support for a codon optimization algorithm

### ISSUE THREAD

**Issue by pcapel** [biopython/biopython#3740]
I have recently been investigating various approaches to [codon optimization](https://pubmed.ncbi.nlm.nih.gov/32311016/) and I am curious if there is any desire or existing effort to include one in this project?

I would be happy to try and contribute an effective algorithm. I'm still researching various approaches, and I'm by no means an expert. Any insight into what would be a good fit for the project would be very helpful. An example of one such algorithm would be [COSMO](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7358382/#).  I'm not a professional researcher in this space, so take this as an amateur looking to be helpful. I'm also unsure how licensing works for using code from research like this. The [source](http://rna.eit.hirosaki-u.ac.jp/cosmo/) is made available through the website of the author Akito Taneda.

I'm fairly new to contributing, so if anyone is interested in working with me it would be greatly appreaciated!

**Comment by mdehoon** [comment]
@pcapel  Thank you for offering to contribute. My feeling is that codon optimization is a bit too specialized for inclusion into Biopython. Perhaps there are other ways to get involved with Biopython?

**Comment by pcapel** [comment]
I'm sure there are! This was a problem that most recently got the juices flowing. Unfortunately while I like the project and I enjoy contributing, I don't work with it daily. I'm more of a "bioinformatics adjacent" software developer who likes to help out. Perhaps I can try implementing something _using_ biopython to scratch that itch. I did notice there was some work on getting `assert` moved over to throwing more specific errors. That could be interesting too. I'll keep my eyes on the issues!
