### ISSUE TITLE
BgzfReader argument `mode` not tested if a fileobj is specified

### ISSUE THREAD

**Issue by fabianegli** [biopython/biopython#3748]
`BgzfReader.__init__()` has an argument mode, which is thoroughly tested, but only if a filename is specified, not in the case of a fileobj.

https://github.com/biopython/biopython/blob/207af955f21628f0b0e002f9c86ef2eefaf7ef14/Bio/bgzf.py#L558-L583

The placing of the `mode` argument testing in the else code block seems to indicate it has something to do with opening the file, but it doesn't, but the error message does. The word variable name mode here apparently confused the programmer and maybe a "content_mode" instead of mode for the treatment of the file content would remove some of the confusion. The mode for opening is hardcoded as 'rb'. Also the mode/content_mode is not well documented for users. Working the comments into a docstring would solve that. 

I believe that the use of the mode argument might have changed over time, because it contains the "r" in the BgzfReader docstring which has no effect whatsoever in the current code.

**Comment by peterjc** [comment]
It controls if we are in text mode or bytes mode (line 579 as quoted):

```python
self._text = "b" not in mode.lower() 
```

The internal handle to the compressed file itself is always in binary (bytes) mode.

**Comment by fabianegli** [comment]
I agree whit what you say. The initial Title and isse was a reflection of my misunderstanding of the internal workings of BgzfReader, but the issue now raised above are real. Don't you agree?

**Comment by peterjc** [comment]
I disagree. New title says "BgzfReader argument mode not tested if a fileobj is specified", but it is checked:

```python
        if fileobj:
            if "b" not in fileobj.mode.lower():
                raise ValueError("fileobj not opened in binary mode")
            handle = fileobj
```

Internally the compressed data handle must be binary. So if given a file object we check is it binary, but if given a file name we open that as binary.

The mode argument to ``__init__`` is only for controlling the datatype of the decompressed data we are going to  provide, i.e. this controls unicode strings (text mode) versus bytes (binary mode). Note this class only offers input, not output, which is the other thing a file mode argument usually deals with.

The function might benefit from having a docstring which discusses this? Do you feel you could write that now?

**Comment by fabianegli** [comment]
Please see the history: mode was once used in open, but when that use changed, the code didnt change consistently throughout the __init__ function. Some context here: https://github.com/fabianegli/biopython/blame/791f9803892536fc643191ded7bb20fd61606ae9/Bio/bgzf.py

**Comment by fabianegli** [comment]
> I disagree. New title says "BgzfReader argument mode not tested if a fileobj is specified", but it is checked:

This is exactly my issue: when you say the mode is checked, you think of the mode of the fileobj, but what I am talking about is that the `mode` argument is not checked. It is this confusion of the mode for file IO and mode of file content that makes it difficult.

**Comment by peterjc** [comment]
Are you saying this should be run regardless of being given filename or fileobj?

```python
         if "w" in mode.lower() or "a" in mode.lower(): 
             raise ValueError( 
                 "Must use read mode (default), not write or append mode" 
             ) 
```

That looks like a sensible improvement (not tested).

**Comment by fabianegli** [comment]
No, I think this test is completely obsolete now. Mode isn't used for file opening any more. This test should be removed completely.

Another fact that adds to the confusion is that the function definition sets `mode="r"`. But the only thin that matters is whether the `mode` argument contains a "b" or not when the `_text` attribute is computed.

**Comment by peterjc** [comment]
Yes, right now the main thing that matters is if the ``mode`` argument contains ``"b"`` or not.

However, asking for write with ``mode='w'`` or ``mode="wb"``, or append with ``mode='a'`` or ``mode="ab"`` etc should fail explicitly (and not silently be treated as read mode).

Also, cross reference #2166 for getting append mode to work.

**Comment by fabianegli** [comment]
A different test would be in order for mode. It is only a boolean choice, but the argument accepts a string that resembles a mode.

Options: 

* Change the argument name to something like content_mode and make it boolean.
* Keep the name but only accept "b" or "latin-1", because that's what it is decoded as.

**Comment by peterjc** [comment]
No. It deliberately follows the Python ``open(...)`` and ``gzip.open(...)`` function argument name.

Right now it only needs to accept "r", "rt", or "rb", so that validation test could be turned round (instead of complaining if it sees "a" or "w").

**Comment by fabianegli** [comment]
> It deliberately follows the Python open(...) and gzip.open(...) function argument name.

This is where I disagree, because mode is not used the same way and has a different meaning.

There is a discrepancy between how the mode argument is used in the reader and writer object. While the reader only uses it to know the content mode, the writer selects the file io mode with it.

**Comment by fabianegli** [comment]
> Right now it only needs to accept "r", "rt", or "rb", so that validation test could be turned round (instead of complaining if it sees "a" or "w").

It does not. You can use it with even weirder mode, e.g.

````python
bgzf.BgzfReader("./Tests/Quality/example.fastq.bgz", "somethin else")
```

**Comment by fabianegli** [comment]
```python
>>> bgzf.BgzfReader(fileobj=open("./Tests/Quality/example.fastq.bgz", "rb"), mode="ra")
<Bio.bgzf.BgzfReader object at 0x1080779d0>
>>> bgzf.BgzfReader(filename="./Tests/Quality/example.fastq.bgz", mode="ra")
...
ValueError: Must use read mode (default), not write or append mode
```

The above code clearly shows that the same mode will for one file input but not the other. That shouldn't be the case.

The problem is that the mode argument is sometimes thought to handle file IO and sometimes the encoding. This is not just confusing, but bound to be erroneous because only one argument has to handle two switches, one for the encoding and one for file IO. This is neither easy to follow when reading code nor easy to understand as user nor do I think it is good practice to hide different code switches behind a single argument. What happens is that a choice unrelated to the mode argument in the builtin open (namely the encoding) needs to be added to the string of the mode argument, but not only that it is also encoded as "b" which by itself has a meaning in the builtin open mode (file IO as bytes) but a different one what it stands for when used in `bgzf.open` (latin-1 encoding or not).

**Comment by fabianegli** [comment]
> However, asking for write with mode='w' or mode="wb", or append with mode='a' or mode="ab" etc should fail explicitly (and not silently be treated as read mode).

I agree that the mode (and generally any argument) needs to be well defined and the user input tested.

**Comment by peterjc** [comment]
Your example shows way always running this snippet is worth doing for consistency:

```
         if "w" in mode.lower() or "a" in mode.lower(): 
             raise ValueError( 
                 "Must use read mode (default), not write or append mode" 
             ) 
```

**Comment by peterjc** [comment]
See discussion about encodings and why it is hard coded to ``latin-1`` here:

https://github.com/biopython/biopython/blob/biopython-179/Bio/bgzf.py#L223

**Comment by mdehoon** [comment]
I haven't really followed this discussion, but wouldn't it be better to use `io.TextIOWrapper` as a wrapper to take care of the bytes-to-string conversion? This is the approach taken by `gzip` in the standard library. It seems odd to have things like `self._newline` hardcoded in `Bio.bgzf`.

**Comment by peterjc** [comment]
About supporting encodings, see #2512.

I have a pull request nearly ready with a longer docstring and stricter mode argument check.

**Comment by peterjc** [comment]
@fabianegli I take it from your "thumbs up" on the PR that #3750 address (most of) your concerns?

**Comment by fabianegli** [comment]
Yes, most of it. I still find it weird that the "b" basically jumps the file (because the actual file is always opened in binary mode) level and applies directly to the content. At leas this is my interpretation/how I understand it. I don't think it is nice, but I also don't think it is worth spending another day discussing that. I see the temptation to use one "mode" for both levels in an attempt to make it (look) more pythonic but don't necessarily agree with it. Of course I am also aware that splitting mode into two arguments to be more verbose would require an undesirable API change and I am not sure that would be worth the trouble.
