### ISSUE TITLE
Add .islower() and .isupper() methods to Seq?

### ISSUE THREAD

**Issue by chris-rands** [biopython/biopython#3753]
Some time ago there was the aim to make the Seq object more 'string-like'. This could include .islower() and .isupper() methods. Relevant SO question: https://stackoverflow.com/questions/69176192/attributeerror-seq-object-has-no-attribute-islower-in-protparam-module-of-b

**Comment by mdehoon** [comment]
I am not sure when it would be useful. The `islower` and `isupper` methods are used in a few places in Biopython, but there it would probably be faster to just call `upper` or `lower` always.

**Comment by mdehoon** [comment]
Btw the three instances of `islower` in `Bio.SeqUtils` contain a bug: Sequences with mixed case are not converted to upper case. Protein sequences in all upper case or all lower case are handled correctly, but sequences with mixed case are not:

```python
>>> from Bio.SeqUtils.ProtParam import ProteinAnalysis
>>> p = ProteinAnalysis("MVKLS")
>>> p.secondary_structure_fraction()
(0.4, 0.2, 0.4)
>>> p = ProteinAnalysis("mvkls")
>>> p.secondary_structure_fraction()
(0.4, 0.2, 0.4)
>>> p = ProteinAnalysis("MVkls")
>>> p.secondary_structure_fraction()
(0.2, 0.0, 0.2)
```

The bug occurs in the initialization of `ProteinAnalysis`:
```python
        if prot_sequence.islower():
            self.sequence = Seq(prot_sequence.upper())
        else:
            self.sequence = Seq(prot_sequence)
```
This should be
```python
        if not prot_sequence.isupper():
            self.sequence = Seq(prot_sequence.upper())
        else:
            self.sequence = Seq(prot_sequence)
```
However, `isupper` is much slower than `upper` (about 12 times slower), so you may as well call `upper` without checking for `isupper`.

**Comment by peterjc** [comment]
That looks like an easy fix - Chris do you want to do that?

**Comment by peterjc** [comment]
As to the original issue, I favour adding ``.isupper()`` and ``islower()`` following string-like behaviour expectations (and indeed, the bytes object does this too), even if usage will be rare.

**Comment by deepto98** [comment]
@peterjc Hi, I'd like to work on this issue. If it isn't assigned already, can you please assign this to me? Also, since I'm new to the project, can you please point me to the relevant files, that I'd need to look at?

**Comment by mdehoon** [comment]
@peterjc As to the original issue, I favour adding `.isupper()` and `islower()` following string-like behaviour expectations (and indeed, the bytes object does this too), even if usage will be rare.

I still think we should think of a use case first.

**Comment by peterjc** [comment]
Use case: Many external sequence analysis tools use upper/lower case to indicate masking part of a sequence, thus ``my_seq.isupper()`` would indicate no lower-case masking is present.

**Comment by mdehoon** [comment]
@peterjc OK, that is a good point. Then I am also in favor of adding `islower` and `isupper`.

**Comment by peterjc** [comment]
Returning ``UndefinedSequenceError`` seems reasonable there.

**Comment by erik-whiting** [comment]
Should I add these methods to the deprecated `UnknownSeq` class as well? If so, should it also raise an `UndefinedSequenceError`? Or perhaps they should just behave normally? Thoughts?

**Comment by mdehoon** [comment]
@erik-whiting  I don't think it is needed to add these methods to `UnknownSeq`.

**Comment by erik-whiting** [comment]
I made a PR for this. The original one failed due to test coverage differences that I'm pretty sure I addressed. The check isn't running on my updates though so I can't get that check to turn green. Any advice on re-triggering that check? otherwise, the PR is ready for review I think.

**Comment by peterjc** [comment]
I think GitHub actions needs approval from a maintainer for first time contributors to run the tests, anyway #3776 is in hand now.
