### ISSUE TITLE
Parsing Exonerate text output with SearchIO does not assign target strand correctly

### ISSUE THREAD

**Issue by chrisjackson-pellicle** [biopython/biopython#3757]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
Python 3.8.3 (default, May 19 2020, 13:54:14)
CPython
macOS-10.15.7-x86_64-i386-64bit
BioPython 1.78
```

### Expected behaviour

When parsing the output of an Exonerate search performed using the model `protein2genome`, `SearchIO.parse(<exonerate_output_file>, 'exonerate-text')` should assign hsp strands to `-` (converted to `-1) when the nucleotide hit is on the negative strand. 

### Actual behaviour

All hsps get assigned to the positive strand `+` (converted to `1`), regardless of whether the nucleotide hit is on the positive or negative strand.

### Steps to reproduce

Tested with Exonerate v2.2 and v2.4.

Using the attached Exonerate output file  [exonerate_results.fasta.zip](https://github.com/biopython/biopython/files/7263583/exonerate_results.fasta.zip) the SearchIO command is:

`exonerate_hits_from_alignment = list(SearchIO.parse('exonerate_results.fasta', 'exonerate-text'))`

Nucleotide hits are on the negative strand (target description contains `[revcomp]`). However:

```
for qresult in exonerate_hits_from_alignment:
    for hsp in qresult.hsps:
        print(hsp.hit_strand_all)
```

Output:
```
[1]
[1]
[1]
[1]
[1]
[1]
[1, 1]
[1]
```

I think this might be due to the code [here](https://github.com/biopython/biopython/blob/1e4acd3cc6a1ef1c79da187b0aaea8a34586d6d9/Bio/SearchIO/ExonerateIO/_base.py#L391); the strand is set based on the presence of the string `:[revcomp]` in the query or target description line, whereas the Exonerate output in version 2.2 and 2.4 contains `[revcomp]` instead , i.e. no preceeding colon.

Cheers,

Chris

**Comment by peterjc** [comment]
Your analysis sounds sensible - do you fancy making a pull request to address this? Ideally with a small test case from a recent version of Exonerate?

CC @bow
