### ISSUE TITLE
AttributeError: module 'Bio' has no attribute '__version__'

### ISSUE THREAD

**Issue by AnranNoinin** [biopython/biopython#3760]
### Setup

I am reporting a problem with Biopython version, Python version, and operating system as follows:

```
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

### Expected behaviour

import modules

### Actual behaviour

AttributeError: module 'Bio' has no attribute '__version__'

**Comment by peterjc** [comment]
How did you install this? And do you happen to have a file called ``Bio.py`` in your current directory?

This may help explain what is happening: ``import Bio; print(Bio.__file__)``

**Comment by JishuPagag** [comment]
I need to install biopython version-1.76 in windows-11. When I install with command 
>>pip install biopython
It installed defaultly biopython-1.79. For prody software, I need specifically biopython-1.76. I am using python-3.10.6 and pip3
How can I install a specific version of biopython-1.76?

**Comment by peterjc** [comment]
@JishuPagag your question is unrelated to this issue, but try ``pip install biopython==1.76`` if you really want the older version - which will find a pre-compiled wheel for Python 2.7, 3.5, 3.6, 3.7, or 3.8 only (being the versions supported at the time):

https://pypi.org/project/biopython/1.76/#files

i.e. If you have Python 3.10 you would either need to compile Biopython (non-trivial on Windows), or downgrade your Python (simpler).

However, https://github.com/prody/ProDy suggests the latest release of Biopython should work. If not, please open a bug with ProDy.

Please open a new issue if you wish to continue this discussion.

**Comment by peterjc** [comment]
Closing issue as no further information provided from the original author.
