### ISSUE TITLE
How to use Gotoh algorithm?

### ISSUE THREAD

**Issue by bonaventuredossou** [biopython/biopython#3762]
Hello, the following algorithm is intended to use the Gotoh algorithm

aligner = PairwiseAligner() # for example
aligner.mode = 'global'
aligner.query_extend_gap_score = x
aligner.query_open_gap_score = y # st x != y
aligner.align(X, Y)

Is it sufficient to set x != y ? Because I went through the [code](https://github.com/biopython/biopython/blob/master/Bio/Align/_aligners.c) but there are no real standard/default values in there.
Please help me with standard/usual values for this. I am relatively new so I am trying to learn. Thanks

**Comment by mdehoon** [comment]
```python
>>> from Bio.Align import PairwiseAligner
>>> aligner = PairwiseAligner()
>>> aligner.algorithm
'Needleman-Wunsch'
>>> aligner.query_extend_gap_score = -3
>>> aligner.query_open_gap_score = -4
>>> aligner.algorithm
'Gotoh global alignment algorithm'
>>> aligner.query_open_gap_score = -3
>>> aligner.algorithm
'Needleman-Wunsch'
>>> aligner.mode = 'local'
>>> aligner.algorithm
'Smith-Waterman'
>>> aligner.query_open_gap_score = -7
>>> aligner.algorithm
'Gotoh local alignment algorithm'
```
