### ISSUE TITLE
MSMS program

### ISSUE THREAD

**Issue by Chenwf1025** [biopython/biopython#3770]
Hello，I just wonder where I can download MSMS program for ResidueDepth computing? 
http://mgltools.scripps.edu/packages/MSMS just redirects to https://ccsb.scripps.edu/mgltools/, and I can not find MSMS program package.

**Comment by KevinCrp** [comment]
You can install MSMS using bioconda 

`conda install -c bioconda msms`

https://anaconda.org/bioconda/msms

**Comment by Chenwf1025** [comment]
> You can install MSMS using conda
> 
> `conda install -c bioconda msms`
> 
> https://anaconda.org/bioconda/msms

It's coooool! Thanks!

**Comment by peterjc** [comment]
Oh, it looks like the URL we have http://mgltools.scripps.edu/packages/MSMS gets redirected to https://ccsb.scripps.edu/mgltools/

Perhaps MSMS is not longer maintained?
