### ISSUE TITLE
Casting Seq objects to list requires iterative __getitem__ calls

### ISSUE THREAD

**Issue by hypostulate** [biopython/biopython#3772]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)]
CPython
Darwin-20.6.0-x86_64-i386-64bit
1.79
```

### Expected behaviour

Casting a `Seq` object to `list` should behave the same as casting a `str` to `list` AND it should have approximately the same performance qualities. Currently it does produce the same output, but casting `list(Seq(...))` is *significantly* slower due to the absence of an `__iter__` method.`list(Seq("ATG"))` should have approximately the same performance as `list(str(Seq("ATG")))`.

### Actual behaviour

Currently `list(Seq("ATG"))` will internally call `Seq.__getitem__` three times, once for each position. For long sequences, this can take a significant amount of time. 

### Steps to reproduce

Run cProfile and evaluate the difference between `list(Seq("ATG"))` and `list(str(Seq("ATG")))`.

### Solution

Add an `__iter__` method to `_SeqAbstractBaseClass`.

**Comment by peterjc** [comment]
This is probably a regression with the recent ABC added to ``Bio/Seq.py`` - previously it more-or-less wrapped a string. But maybe the old code was doing this too?

**Comment by mdehoon** [comment]
> > This is probably a regression with the recent ABC added to `Bio/Seq.py` - previously it more-or-less wrapped a string. But maybe the old code was doing this too?
> 
> I think it was also the case with the old `Seq(object):`, at least in 1.70. I'm not sure if there was ever an `__iter__` method on `Seq` and that is really what you need to avoid `list(Seq(...))` defaulting to iterative `Seq.__getitem__` calls based on my understanding.

I think @hypostulate  is right; we did not have an `__iter__` method before either.

These are some timings for calling `list(seq)` or `list(str(seq))` on `seq = Seq("ABCD"*1000000)` ten times:

Biopython 1.75, before introducing the ABC:

`list(str(seq))`: 0.43 seconds
`list(seq)`: 10.38 seconds

Biopython 1.79, with the ABC:

`list(str(seq))`: 0.45 seconds
`list(seq)`: 11.82 seconds

Biopython 1.79 after #3773:

`list(str(seq))`: 0.46 seconds
`list(seq)`: 0.42 seconds

**Comment by peterjc** [comment]
Thanks both - this makes quite a big difference doesn't it? :)

**Comment by hypostulate** [comment]
Thanks for the quick turnaround. Glad I was able to contribute!
