### ISSUE TITLE
question: how to seek an Entrez.efetch handle (read N bytes beginning at given position)

### ISSUE THREAD

**Issue by abubelinha** [biopython/biopython#3791]
Sorry for the dumb question. I am trying to use Biopython for quite basic stuff.
I want to read Entrez nucleotide database records, and process them one by one (I want to search specific strings inside). 

```Python
from Bio import Entrez
Entrez.email = "Your.Name.Here@example.org"
idsList = ['AR063183.1', 'AR063184.1', 'AR063185.1']
# now I want to retrieve full information about each record
handle = Entrez.efetch(db="nuccore", id=idsList, rettype="gb", retmode="text")
```
At this point, I could get the full handle to a string, with `handle.read()`
Or I could read it line by line, with `handle.readline()`
I also tried `handle.read(1000)`, and I got the first 1000 characters.

But are there any chances that I can do read 1000 characters while specifying a start point within the handle?

In .gb format each record has multiple lines, ended by a "`//`" string in the last line.

```
LOCUS       AR063183                 327 bp    DNA     linear   PAT 29-SEP-1999
DEFINITION  Sequence 1 from patent US 5844093.
ACCESSION   AR063183
VERSION     AR063183.1
(... many other lines ...)
//

LOCUS       AR063184                 357 bp    DNA     linear   PAT 29-SEP-1999
DEFINITION  Sequence 3 from patent US 5844093.
ACCESSION   AR063184
VERSION     AR063184.1
(... many other lines ...)
//

LOCUS       AR063185                 339 bp    DNA     linear   PAT 29-SEP-1999
DEFINITION  Sequence 5 from patent US 5844093.
ACCESSION   AR063185
VERSION     AR063185.1
(... many other lines ...)
//


```

So I'd rather prefer to read the handle by chunks of a given size (i.e. 1000 bytes/characters), so I can (1) read at once enough bytes to ensure I got all lines corresponding to the current record. (2) look for the `//` mark where current record ends, and save its position within handle. (3) move the handle reading pointer to that position, so I can proceed reading the next 1000 bytes.

When reading a python file I can do this using the `seek` method.
https://stackoverflow.com/questions/11696472/seek-function/11696554#11696554
https://www.geeksforgeeks.org/python-seek-function/

But this doesn't seem to work with Biopython Entrez handle, which does not support `seek()` method.
```Python 
# Of course this would be done looping until the end of handle. This is just an example:
data = handle.read(1000) 
# I process data string, do my work, and find out the end mark "//" at a certain position (i.e. 748 bytes)
start=748 # position where I found the end of the last record I parsed from .gb file
handle.seek(start)  # I move handle to the point where I would like to continue reading it
data = handle.read(1000) 
# I process the next record ... and so on
```
Output:
```Python
handle.seek(start)
io.UnsupportedOperation: underlying stream is not seekable
```
I can circumvent this writing the full handle to a file, and then reading it again from disk in order to use seek method.
I could also use the handle.readline() method until I find `//` mark.

But I wonder if it is also possible to read directly N-sized random chunks of the original handle.

Thanks

**Comment by mdehoon** [comment]
You could use `Bio.SeqIO` to parse the data:
```python
>>> from Bio import SeqIO
>>> records = SeqIO.parse(handle, "genbank")
>>> for record in records:
...     # do what you want with record
```

**Comment by peterjc** [comment]
Exactly - ``SeqIO.parse`` (or the underlying GenBank parser) will read enough lines to parse each record before reading any more data.

**Comment by peterjc** [comment]
Closing issue as stale, hopefully the suggestion worked.
