### ISSUE TITLE
pairwise2 alignments are much slower when using Bio.Align.substitution_matrices.Array compared to a regular dictionary

### ISSUE THREAD

**Issue by clami66** [biopython/biopython#3807]
When using `pairwise2.aligndX` (biopython==1.78, python==3.8.6) I noticed that alignments are much slower when doing as shown [in the docs](https://biopython.org/docs/1.75/api/Bio.pairwise2.html):

```
from Bio.Align import substitution_matrices
matrix = substitution_matrices.load("BLOSUM62")
for a in pairwise2.align.globaldx("KEVLA", "EVL", matrix):
    print(format_alignment(*a))
```
If I run `align.globaldx` (or any other alignment function using a similarity matrix) on two long-ish sequences (200 and 900 AAs), execution time is ~10s:

```python
start = time.time()
sequenceA = "..."
sequenceB = "..."
blosum = substitution_matrices.load("BLOSUM62")
alignments = pairwise2.align.globaldx(sequenceA, sequenceB, blosum)
end = time.time()
print(f"Time: {end - start}")
-----------
Time: 9.997540712356567

```
But if I convert the blosum object (which is of type Bio.Align.substitution_matrices.Array) into a regular dictionary, runtime is ~30x faster:

```python
start = time.time()
blosum_dic = as_dictionary(blosum) # convert the blosum object into a normal dictionary
alignments = pairwise2.align.globaldxs(sequenceA, sequenceB, blosum_dic)
end = time.time()
print(f"Time: {end - start}")
-----------
Time: 0.31342601776123047
```

I suggest this conversion is done automatically inside `pairwise2` when using a scoring matrix

**Comment by MarkusPiotrowski** [comment]
@clami66 Thanks for reporting this and showing how this can be made much faster. I guess the problem has come when we changed the implementation of the substitution matrices. It could be that the match function in the C code cannot handle the new substitution matrices and instead the Python replacement code is used.

Note that we are thinking about to declare pairwise2 deprecated, you may want to try the "new" ```Pairwise.Aligner```.

**Comment by peterjc** [comment]
Having decided to deprecate ``Bio. pairwise2``, I don't think we'll work on this. But thank you for diagnosing the issue and reporting it.

**Comment by mdehoon** [comment]
@clami66 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
