### ISSUE TITLE
Python 3 porting issue, example getgene.py does not work

### ISSUE THREAD

**Issue by anders-was-here** [biopython/biopython#3809]
### Setup

I am reporting a problem with Biopython version 1.79, Python 3 version

File:
https://github.com/biopython/biopython/blob/master/Doc/examples/getgene.py#L39-L68

In Python3 the string module does not containt `split()` or `strip()`. Please note, I'm not a user of this file, 
i found this while trying out the pytype tool. So I don't know is this is worth fixing. 
(For example, does the program still need to run in Python 2?)

### Expected behaviour

No traceback

### Actual behaviour

Traceback in Python 3

### Steps to reproduce (just proving that string.split does not work anymore)

```
$ python2 -c 'import string; print(string.split("a.b", "."))'
['a', 'b']

$ python3 -c 'import string; print(string.split("a.b", "."))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'string' has no attribute 'split'

```

### Possible fix, something like this could work:

```
python3 -c 'print(str.split("a.b", "."))'
python3 -c 'print(str.strip(" zzz  "))'
```

**Comment by peterjc** [comment]
I think this should just use the string method of the same name instead, e.g. ``string.split(entry, "\n")`` becomes ``entry.split("\n")``. Do you want to make a pull request?

Or, we could just delete this elderly file - the ``SeqIO.index_db(...)`` functionality ought to cover all of this.

**Comment by anders-was-here** [comment]
> Or, we could just delete this elderly file - the `SeqIO.index_db(...)` functionality ought to cover all of this.

Obviously no one have complained about it not working in Python 3 so if we can improve Biopython by retire the file, I'm all for that.
