### ISSUE TITLE
local pairwise alignment using pairwise2

### ISSUE THREAD

**Issue by renzilin** [biopython/biopython#3825]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
[GCC 9.3.0]
CPython
Linux-5.11.0-41-generic-x86_64-with-debian-bullseye-sid
1.78

# also tested on windows-subsystem
3.9.7 (default, Sep 16 2021, 13:09:58)
[GCC 7.5.0]
CPython
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
1.78
```

### Expected behaviour

The local pairwise alignment between **seq1** and **seq2** were performed using `localms` function:

```Python
seq1 = "AATTCCAGTGTCAGACCCTGTTCTAAGTACTTCTATCTATCTATC"
seq2 = "CTGTGTCAGACCCTGTTCTAAGTACTTCCT"
alignments = align.localms(seq1.upper(), seq2.upper(), 1, -0.9, -0.75, -0.1)
[aln_ref, aln_seq, aln_score, aln_start, aln_end] = alignments[0]
```
Considering the gap open penalty is -0.75 and extend penalty is -0.1, and the number of gap shouldn't exceed 3. The result should be the following, which only contains one gap: 
```
AATTCCAGTGTCAGACCCTGTTCTAAGTACTTC-TATCTATCTATC
-----CTGTGTCAGACCCTGTTCTAAGTACTTCCT-------
```

### Actual behaviour
However, the result contains 3 gaps,
```
AATTCCAGTGTCAGACCCTGTTCTAAGTACTTCTATCTATCTATC
-----CTGTGTCAGACCCTGTTCTAAGTACTTC---CT-------
```
And then,
I exchanged the input order:
```
alignments = align.localms(seq2.upper(), seq1.upper(), 1, -0.9, -0.75, -0.1)
```
The result is the same.

Looking forward to your reply, thanks!

**Comment by MarkusPiotrowski** [comment]
Actually, the `pairwise2` alignment is correct. The larger gap subtracts only 0.2 from the score but adds 2 matches, while your alignment hasn't the 0.2 penalty but also only has 1 match after the gap. So the score of your alignment is 26.35 but the score of `pairwise2`'s alignment has a score of 27.15.

**Comment by MarkusPiotrowski** [comment]
@renzilin Can we close this?

**Comment by renzilin** [comment]
Oh sorry!
Thanks for your quick and helpful reply.

________________________________

**Comment by mdehoon** [comment]
@renzilin 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
