### ISSUE TITLE
align.globaldx() stucks in specific sequences

### ISSUE THREAD

**Issue by ozgurcanarican** [biopython/biopython#3827]
### Setup

I tried pairwise global alignment with align.globaldx() method of Biopython on a protein dataset included protein sequence information. Initially it was working properly then I realized that it stucks when trying to find the best alignment in some specific sequences. I could not catch the error with try-except error handler because it acts like running an infinite loop inside the method and returns nothing. Here is my code includes that specific protein sequences as query and subject:

```python
query = "GGGGGAGCCGAAAGGCGAAGAACCCAPEASYVRFEVPEDMQNEALSLLEKVRESGKVKKGTNETTKAVERGLAKLVYIAEDVDPPEIVAHLPLLCEEKNVPYIYVKSKNDLGRAVGIEVPCASAAIINEGELRKELGSLVEKIKGLQK"
subject = "MYRDLVLNPQNRSVNRGDDEISLTKREYDLLNILMTNMNRVMTREELLSNVWKYDEAVETNVVDVYIRYLRGKIDIPGKESYIQTVRGMGYVIREK"

from Bio.pairwise2 import align, format_alignment
from Bio.SubsMat import MatrixInfo

for aa in align.globaldx(query, subject, MatrixInfo.blosum62):
    alignment = format_alignment(*aa)
    print(alignment)
    
    match = alignment.splitlines()[1].count("|")
    aligned_length = len(alignment.splitlines()[1])
    
    identity = match / aligned_length
    
    print(match)
    print(aligned_length)
    print(identity)
```

Anyway, I solved my issue with adding "one_alignment_only" parameter as "True", because I just needed the percentage identity as just below:

```python
query = "GGGGGAGCCGAAAGGCGAAGAACCCAPEASYVRFEVPEDMQNEALSLLEKVRESGKVKKGTNETTKAVERGLAKLVYIAEDVDPPEIVAHLPLLCEEKNVPYIYVKSKNDLGRAVGIEVPCASAAIINEGELRKELGSLVEKIKGLQK"
subject = "MYRDLVLNPQNRSVNRGDDEISLTKREYDLLNILMTNMNRVMTREELLSNVWKYDEAVETNVVDVYIRYLRGKIDIPGKESYIQTVRGMGYVIREK"

from Bio.pairwise2 import align, format_alignment
from Bio.SubsMat import MatrixInfo

for aa in align.globaldx(query, subject, MatrixInfo.blosum62, one_alignment_only = True):
    alignment = format_alignment(*aa)
    print(alignment)
    
    match = alignment.splitlines()[1].count("|")
    aligned_length = len(alignment.splitlines()[1])
    
    identity = match / aligned_length
    
    print(match)
    print(aligned_length)
    print(identity)
```

However, somebody else still would need the best alignment, so I just wanted to inform you about my experience with "globaldx". Thanks in advance.

### Expected behaviour

The method must return the alignments and the scores as just below:

```python
GGGGGAGCCGAAAGGCGAAGAACCCAPEAS-YVRFE-V--PEDMQN--------EALSLLE-KVRE----SGKVKKG--TNET-----TKAVERG-LAKL--V--YIAEDVDPPEIVAHLPLLCEEK-NVP---YI-YVKSKNDLGRAVG-IEVPCASAAIINEGELRKELGSL-VEK-IKGL-----QK
                               | | . |  |   ||        | .| |  | ||    .  .     ||       |.  |   |  |  |  |     |  |  |    .  |  ||    || |      | |  | |..|         |   ||  |  ..  ..|.     .|
------------------------------MY-R-DLVLNP---QNRSVNRGDDE-IS-L-TK-REYDLLN--I---LMTN--MNRVMTR--E--EL--LSNVWKY-----D--E--A----V--E-TNV-VDVYIRY------L-R--GKIDIP---------G---KE--S-YIQ-TVRGMGYVIREK
  Score=237
```

### Actual behaviour

The method continues running and returns nothing.

**Comment by mdehoon** [comment]
@ozgurcanarican  
`Bio.pairwise2` will be deprecated in the next release of Biopython; see #3817 . You can use the pairwise aligner in `Bio.Align` instead. It is already available in recent releases of Biopython.

**Comment by ozgurcanarican** [comment]
@mdehoon 
Thanks for your answer. I will test those sequences with Bio.Align.PairwiseAligner as soon as possible.
