### ISSUE TITLE
Define SeqFeature __sub__ for integer offset

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#3831]
See https://github.com/biopython/biopython/blob/master/Bio/SeqFeature.py and ``__add__``, need to do the same specifically for integer offsets.

Workaround ``feature + (-5)`` instead of ``feature - 5``, see https://twitter.com/tomeraltman/status/1473764959347638273

**Comment by BusinessLanguage** [comment]
Hello

Is this issue still open?

Thank you

**Comment by peterjc** [comment]
Yes, still open - waiting for a review on #3835 before merging that.

**Comment by alexdt1982** [comment]
Is this issue still open?

**Comment by peterjc** [comment]
Yes, was waiting for reviews on #3835 but I think some of that might be being done on another PR now...
