### ISSUE TITLE
Detect missing residues in mmcif

### ISSUE THREAD

**Issue by tueboesen** [biopython/biopython#3855]
I am trying to make a robust script that can detect missing residues in mmcif files, but I'm honestly not sure exactly how that would even work for mmcif files.
In pdb files I understand that missing residues are generally reported in REMARK 465, which BioPython can read and extract, but after manually looking in similar mmcif files, I don't actually see any good consistent meta information to even indicate missing residues. The especially tricky missing residues are the ones at the beginning or end of a peptide chain, since you can't really detect those just from the atomic coordinate section.  
Does anyone know how to detect something like this in mmcif? which header information might be relevant or is this just something that is missing from the mmcif format?

As example I am currently looking at 6gj5, which has missing residues in both the beginning and middle of the chain.

**Comment by JoaoRodrigues** [comment]
You could parse the mmCIF file with `MMCIF2Dict` and then access the `_entity_poly_seq` field. Compare that with the residues for which you have coordinates and you should be able to get the missing ones.

**Comment by tueboesen** [comment]
What you are suggesting is more or less also the only solution that I have found.
The problem with that approach is that _entity_poly_seq doesn't actually give me any more information than just the simple one letter sequence string. So I would still have to match two sequences up against each other, which is neither elegant nor very robust. 

I find it strange that this information has been lost in the translation from pdb to cif, since it seems like very relevant meta information.

**Comment by JoaoRodrigues** [comment]
According to the documentation in the PDB website: `_pdbx_unobs_or_zero_occ_residues` (https://www.wwpdb.org/documentation/procedure#toc_5)

**Comment by tueboesen** [comment]
This is exactly what I was looking for! Both the actual keyword, and the link to the documentation (For some reason this is not easy to find through rcsb.org). 
Thank you very much.

**Comment by tueboesen** [comment]
Just a little followup to anyone else that might encounter this problem. This is the code I ended up with.

```
def detect_missing_residues(filename):
    """
    Reads the header information in mmcif files and creates a dictionary containing all chains, 
    and for each chain it contains a boolean array showing which sequences have coordinate information.
    Hence to get the status of coordinates missing in chain B do: chain_coords_exists['B']
    """    
    mmcif_dict = MMCIF2Dict(filename)
    seqs = [seq.replace("\n",'') for seq in mmcif_dict['_entity_poly.pdbx_seq_one_letter_code_can']]
    strand_ids = [seq.replace("\n",'') for seq in mmcif_dict['_entity_poly.pdbx_strand_id']]
    strand_ids = [id.split(',') for id in strand_ids]
    chain_coords_exist = {}
    for seq, strand_id in zip(seqs,strand_ids):
        for strand_id_i in strand_id:
            if strand_id_i in chain_coords_exist:
                continue
            else:
                chain_coords_exist[strand_id_i] = [True]*len(strand_id_i)
    if '_pdbx_unobs_or_zero_occ_residues.auth_seq_id' in mmcif_dict:
        missing_res_chain = mmcif_dict['_pdbx_unobs_or_zero_occ_residues.label_asym_id']
        missing_res = mmcif_dict['_pdbx_unobs_or_zero_occ_residues.label_seq_id']
        for (chain,seqidx) in zip(missing_res_chain,missing_res):
            chain_coords_exist[chain][seqidx] = False
    return chain_coords_exist

```
