### ISSUE TITLE
molecular_weight in SeqUtils

### ISSUE THREAD

**Issue by Durgaburande** [biopython/biopython#3859]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)
3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-10-10.0.19041-SP0
1.79

calculating the protein mass for the following sequence:
protein="TRLSTYWVDCYIGYQCWFRTQPWKQSKFICDNRVYRHSNGFACLLHHCILPTIAHGGNILPVYYAAEQVHEQQEKPDNFVSSLSVNSVNQDEMMCKAFTRFQGNLIGCPQLYRYYLIWRMRADYWRYTLQFSSTTAMNLMITFKEEDAIGWAEPAKDHFPCYSPGFMRGSIDNRDDRVNLKQFMVTALEFIYAGIPCFLHVKLMPTRQLMIHYQLIHRLHKAAFMPSCMDFGPQMMCNTTGPSPIVHRGRNIEIEALKYERPPVPPEVNRAQLQEQPTFCMHCWSSLWGQGIWPETGLATFTMGDKVFPMGYQACMQEAAREPLSFHIMYASTELRAVRQKAQLVINLFAPCVCVHAVEGHFRLHWPWVDTWDSADIELNTKRHCTTFTSAIILWMRGYHGRYWSEQAVLLGMKLTEVMVDQIAYILDENRHFKQMGLAPMDQWHGQFETTHQCVLGQRVMYTEMHMRHELVNRNQNFAMIHVFMKINCCKGFYGFPTWHHKDFNGKFDRHFTHMCTAKTPKKLICYVQRYRSDARQQANSMFIFTTGSQICAWSMGTWIAGVNRLWDVLYGKTLEWGESINYELCADERSGIRAITKGIYWMSGFNIKDQHMTYAHDICNSMFHKSEFHNIVSRCLCGDRQRCNWIKAKGTHSEADDGGKPTLTGGQKAKPHFDSIAIRWSVWEWSGNCSQRPCLMKRNAAHHHHGDWLMAADLGYVIEELWKCESDPRPGNQKQILTVLNHMFYSAPCADESVRHHFLFKWTMGWDGDATKFARLIHDFFMPHEDTKLEYDNLRMMRYTCFDRHPHGVGQKCNTDNAIDHYSFPWAADWTNMSLHTHRPTVNMAEMQITVPRQWCSWMRPCPECLSWNHQDGCNSHESQWGKPIEHMDLQCEFVLQWVDESFYFDPFAQILYKFMFTMVTYPAECSNNSVNTQDINLEIMKMAVYRFNEVRSFEFCVLKQGRMVNICMGIGCHC"

### Expected behaviour
114277.313

### Actual behaviour
114371.197

### Steps to reproduce
when the molecular weight of the protein is calculated; it is not showing the accurate mass. maybe the values of average amino acid given are not accurate for some as per given in  https://en.wikipedia.org/wiki/Proteinogenic_amino_acid#Mass_spectrometry Wikipedia.
need to change the average mass of amino acids.

**Comment by MarkusPiotrowski** [comment]
@Durgaburande Can you say, which calculator you used for your output?
E.g. ExPASy's ProtParam tool (https://web.expasy.org/protparam/) gives 114372.27 and the same is output (114372.27) is given by the EMBOSS pepstats tool (https://www.ebi.ac.uk/Tools/seqstats/emboss_pepstats/).
Thus, the value given by Biopython is quite close to the output of the other tools (off by 1 Dalton), while your result is off by 95 Daltons.

**Comment by MarkusPiotrowski** [comment]
You may have used monoisotopic data and probably have forgotten to add the mass of another water molecule. This would explain your result perfectly.

Using monoisotopic masses, Biopython would give 114295 Dalton. If you add 18 (mass of one water molecule) to your result, this is the same.

**Comment by Durgaburande** [comment]
Ohh ok I didn't know about this, In Rosalind, there was a question to calculate the protein mass. and the answer for this was 114277.313 Dalton. and they have used a monoisotopic mass table.
in biopython it is giving 114371.197 which is more than 18 Daltons. any other reason for this?

**Comment by MarkusPiotrowski** [comment]
First, I think the Rosalind result is wrong, because they forgot to add the water molecule. Obviously, they used masses for amino acids in proteins, which, due to the binding of two amino acids together, are 18 Da less than the masses of free amino acids, because for each peptide bond one molecule of water is released:

AA1 + AA2 = AA1-AA2 + H2O
AA1-AA2 + AA3 = AA1-AA2-AA3 + H2O

E.g. the mass of free alanine is 89 Da, but the mass of alanine in a protein is 71 Da. 

However, as you see, only n-1 water molecules (each 18 Da) are released. Thus, you need to add the mass of one water molecule for the whole protein at the end.

Second, Biopython by default uses average amino acid masses, but can also use monoisotopic data:

```python
from Bio.SeqUtils import molecular_weight

protein = # your protein sequence
print('Average mass:')
print(molecular_weight(protein, 'protein'))
print('Monoisotopic mass:')
print(molecular_weight(protein, 'protein', monoisotopic=True))
```
Result:
```
Average mass:
114371.19730000071
Monoisotopic mass:
114295.32416399977
```

**Comment by Durgaburande** [comment]
Then difference between average mass and monoisotopic mass should be 18 only tight? But here it is 75.873...why so?

**Comment by Durgaburande** [comment]
Okay got it, Thank you so much!!
