### ISSUE TITLE
Use of substitution_matrices is much slower than MatrixInfo in pairwise alignment

### ISSUE THREAD

**Issue by lqtza** [biopython/biopython#3862]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```
3.9.7 (default, Oct 13 2021, 06:45:31)
[Clang 13.0.0 (clang-1300.0.29.3)]
CPython
macOS-11.6.1-x86_64-i386-64bit
1.78
```

### Expected behaviour

Pairwise alignment with penalties input as matrix (`substitution_matrices.load("BLOSUM62")`) and dict (`matlist.blosum62`) should not vary. 

### Actual behaviour

Pairwise alignment with `matlist.blosum62` is 100x faster than with `substitution_matrices.load("BLOSUM62")`.

### Steps to reproduce

```
from Bio import pairwise2
from Bio.SubsMat import MatrixInfo as matlist
from Bio.Align import substitution_matrices
from Bio.Align import PairwiseAligner

import time

s1 = "MNSFSEILCRHLPRAGTLSGPLANTEIYRVDEVYELTPIVYDPSVYFVAQGEKEAWLQEQRYVYNPGQFLLLTVPLPLHCRVFNATPRKPFLAIKLNIDLSVLKELLGQMQTVEADTDQSDSGIFVSNMTDNLKDAVHRFISTLDHPEQQSVLAPMIYREILFHILQGPEAQRLRGFATADRHSNRIALVIDFIHQNFSRTMRIEELAAIAAMSESTFYEHFKNVTQLSPLQYLKNIRLHHARHQISVEQLPVSEAAYLVGYESPSQFSREYKRLFGFSPAQHSA"

s2 = "MNLATIAELVDSMVQAEGMSQNLLPFTSLYRVTEPQPLTPLVYDPSIYFVVQGEKEAWLREQRFVYNEFQYLVLTVPLPLRCRVFNAQPAKPFLAIRLDIDLTILAELVNQLPAHSMQADQSDSGIFVSESNEALAGSIHRLISTAQQPEQAAVLAPMYYREILFHLLQGTQAHLLRNFVTQDRHNNRIAQVVHYIHRHYNHALKVEELADIAAMSPSTFHEHFKNVTHLSPLQYVKNIRLHHAKHQIFIEQLPVNEAAFNVGYESPSQFSREYKRLFGLSPVQHLRQSVI"

# 0.04-0.05 seconds
t = time.time()
pairwise2.align.globaldx(s1, s2, matlist.blosum62)
print(time.time() - t)

matrix = substitution_matrices.load("BLOSUM62")

# 4.3 seconds
s = time.time()
pairwise2.align.globaldx(s1, s2, matrix)
print(time.time() - t)

aligner = PairwiseAligner(mode='global', substitution_matrix=matrix)

# 4.3 seconds
s = time.time()
aligner.align(s1, s2)
print(time.time() - t)
```

**Comment by peterjc** [comment]
Note ``Bio.pairwise2`` is being deprecated in Biopython 1.80 (#3817), but that is still a striking difference in speed.

**Comment by MarkusPiotrowski** [comment]
See also #3807 (closed)
Dear @lqtza Thank you for reporting this. The probable reason for this may be an error that was introduced with the new substitution matrices, which probably (by a possible problem in the C code) forces `pairwise2` to use the Python-only replacement method.

Since we declared `pairwise2` deprecated (and I'm possibly not able to fix the underlying C code), it is unlikely that we are going to address this.

Instead, please consider using the new `PairwiseAligner`.

**Comment by lqtza** [comment]
@mdehoon that was it (ughhh silly copying error) `PairwiseAligner` runs at `0.0006690025329589844`. Sorry for the bother and thanks for clearing this up folks.

**Comment by MarkusPiotrowski** [comment]
Note for us: I never investigated this in detail, but the striking difference in speed let me suggest that `pairwise2` is falling back to it's pure-Phython replacement code. That this is only happening with substitution matrices let me also suggest that this is connected to the switch to substitution matrix objects.

**Comment by peterjc** [comment]
@MarkusPiotrowski Possibly - but looking more closely, ``Bio.SubsMat`` had already been deprecated and has been removed for Biopython 1.80 anyway (#3713). I should have spotted that earlier.

**Comment by MarkusPiotrowski** [comment]
Adding this to `pairwise2`'s `dictionary_match` (and importing `Bio.Align.substitution_matrices`):

```python
# Check for new substitution matrix object:
        try:
            if isinstance(score_dict, substitution_matrices.Array):
                dict_ = {}
                for a in score_dict.alphabet:
                    for b in score_dict.alphabet:
                        dict_[(a, b)] = score_dict[a, b]
            score_dict = dict_
        except NameError:
            pass
```
makes it faster again. With the above script:

```python
0.09000015258789062   # pairwise2 with Bio.SubsMat
0.1900005340576172  # pairwise2 with Bio.Align.substitution_matrices and conversion to dic
0.0  # PairwiseAligner
```
Some trade-off due to the conversion, but much better than about 8 secs (on my computer).
@mdehoon: Is there a faster method to convert a Numpy array into the desired dictionary (with `(x, y)` as keys)?
@peterjc Shall I make a PR for this? `pairwise2` has still some fans out there...

**Comment by peterjc** [comment]
It feels a bit odd to speed up a ``Bio.pairwise2`` use case in the same release we're deprecating it, but I have no objection in principle.

**Comment by MarkusPiotrowski** [comment]
Sorry, just realized that `dict(substitution_matrix)` will do. Still worth to include this as own method?

**Comment by peterjc** [comment]
Using ``dict`` should suffice over the extra function, but does that mean we need to add that cast explicitly somewhere in the code path?

Or might the new ``Bio.Align.substitution_matrices.Array`` benefit from some more dict-like behaviour?

**Comment by MarkusPiotrowski** [comment]
The advantage of an extra function would be to make this option visible to the user. For me, it was not clear that a `substitution_matrices.Array` access is so slow compared to a `dict`. A user who just wants to use the predefined matrices (like BLOSUM) may not be aware that he can gain a performance boost by converting the array to a `dict`.

**Comment by mdehoon** [comment]
@MarkusPiotrowski  Are there any use cases (other than performing pairwise alignments) where fast access as a dictionary is important? The pairwise aligner in `Bio.Align` converts the sequences to integers, and uses those as indexes into the substitution matrix, which should be much faster than using a dictionary.

**Comment by MarkusPiotrowski** [comment]
I'm not sure about other use cases. People may want to use the pre-defined matrices for programming another pairwise aligner or to calculate the score of a large given alignment, or whatever they like to do.
These matrices are public in the code, so why don't tell the user that using them as dict may have positive-side effects for their use case?
In addition, something like `Bio.Align.substitution_matrices.as_dict('BLOSUM62')` could directly replace `Bio.SubsMat.MatrixInfo.blosum62` (substituting a dict with a dict). There are more than 4k code pages on GitHub alone which use `Bio.SubsMat`. Do you know how many of them need fast(er) access to these matrices? On the other hand, for us, it would mean to add just a few lines of code.

**Comment by mdehoon** [comment]
> There are more than 4k code pages on GitHub alone which use Bio.SubsMat. Do you know how many of them need fast(er) access to these matrices? 

None of them. If I am wrong and somebody approaches us with an actual use case where faster access is important, I am happy to reconsider. Even in that case, adding an `as_dict` function may not be the right solution; we won't know until we see an actual use case.

If you really want fast dictionary-like access, a better approach is to optimize the `__getitem__` method of the `Array` class in `Bio.Align.substitution_matrices`.

**Comment by MarkusPiotrowski** [comment]
One use case that I'm aware of is Biopython's `pairwise2`...

So I give up. I guess that most users who want to use a substitution matrix outside the context of `PairwiseAligner` are happy with a simple dictionary. We take away these dictionaries and provide instead a fancy Numpy array replacement which is optimized for the use with `PairwiseAligner` but otherwise has a low performance when being used in the same way as these matrices were used before.

**Comment by mdehoon** [comment]
> One use case that I'm aware of is Biopython's `pairwise2`...

The other one I can think of is #3538. There also the numpy-based substitution matrix will be much faster than a dictionary-based one. Much easier to code, also.

Note that nowadays `Bio.Align` can parse alignment formats such as BED, PSL, Clustalw etc., so the numpy-based substitution matrix does not just benefit the pairwise aligner.

**Comment by MarkusPiotrowski** [comment]
@mdehoon I already gave up. I don't understand why you resist so strongly a tiny addition which would possibly benefit a number of our users but will harm no one (no one would be forced to use an `as_dict` method).

**Comment by peterjc** [comment]
@mdehoon does optimisation of ``__getitem__`` for the dictionary style usage look easy? I agree that would be even better than adding an ``.as_dict`` method.

**Comment by mdehoon** [comment]
@MarkusPiotrowski  I resist because tiny additions add up. The biggest issue I see with Biopython is the existence of multiple modules doing overlapping things. This happened because code was added to Biopython too easily in the past.  Adding code is easy; removing code requires deprecation and waiting for two releases. Disentangling this is taking years.

**Comment by mdehoon** [comment]
@peterjc  I don't think it is that difficult. The C code effectively does that already.

**Comment by mdehoon** [comment]
These are some timings:

```python
>>> s = "KEVLA" * 100
>>> m = substitution_matrices.load("BLOSUM62")
>>> d = dict(m)
>>> aligner = PairwiseAligner()
>>> aligner.substitution_matrix = m
>>> alignments = list(pairwise2.align.globaldx(s, s, m))  # 18.3 seconds
>>> alignments = list(pairwise2.align.globaldx(s, s, dict(m)))  # 0.188 seconds
>>> alignments = list(pairwise2.align.globaldx(s, s, d))  # 0.173 seconds
>>> alignments = list(aligner.align(s, s))  # 0.0023 seconds
```

The first case is `pairwise2` with a matrix from `substitution_matrices`. It is slow.
The second case is effectively what we are now doing after #3865 . It speeds up `pairwise2` by a factor of 100.
The third case is effectively the same as using `Bio.SubsMat`. It is 8% faster than the second case.
The fourth case is the new pairwise aligner. It is 75 times faster than `pairwise2` with `Bio.SubsMat`.
