### ISSUE TITLE
NCBIWWW.qblast CPU usage limit error

### ISSUE THREAD

**Issue by freiburgermsu** [biopython/biopython#3868]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
CPython
Windows-10-10.0.19041-SP0
1.79

### Expected behaviour

An XML file that possesses a complete set of information for all of the sequences from the parameterized FASTA file.

### Actual behaviour
The follow error is acquired from both BLASTp and BLASTn searches `<Iteration_message>[blastsrv4.REAL]: Error: CPU usage limit was exceeded, resulting in SIGXCPU (24).</Iteration_message>`. Is this the consequence of the BLAST server being unable to process the size of the sequence? How can the `NCBIWWW.qblast` function be successfully operated?

### Steps to reproduce
This function call
```python
protein_blast_results = NCBIWWW.qblast('blastp', database, protein_fasta)
```
with this FASTA sequence
```python
protein_fasta = '''>Protein - 9_residues - 1157.2049_amu
                    MLNTGYNSN*'''
```
fails to execute.

**Comment by MarkusPiotrowski** [comment]
Looks like this is/was a temporary problem with the blast server. For me, it did run fine, just didn't find any hits due to the short sequence. You may want to set `short_query=True`. 

```python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from Bio.Blast.NCBIWWW import qblast
>>> protein_fasta = '''>Protein - 9_residues - 1157.2049_amu
MLNTGYNSN*'''
>>> print(protein_fasta)
>Protein - 9_residues - 1157.2049_amu
MLNTGYNSN*
>>> blast_result = qblast('blastp', 'nr', protein_fasta)
>>> from Bio.Blast import NCBIXML
>>> record = NCBIXML.read(blast_result)
>>> record.alignments
[]
>>> blast_result = qblast('blastp', 'nr', protein_fasta, short_query=True)
>>> record = NCBIXML.read(blast_result)
>>> len(record.alignments)
1
>>> print(record.alignments[0])
gb|PYS05490.1| hypothetical protein DMG12_07515 [Acidobacteria bacterium]
           Length = 346

>>>

**Comment by freiburgermsu** [comment]
Hello @MarkusPiotrowski,

I repeated the error from [this FASTA file](https://github.com/freiburgermsu/codons/blob/main/examples/MERS/codons-30_proteins/protein_sequence.fasta), in which the first sequence is the protein that you verified to operate, yet it fails in this context. Here is [the exported XML file](https://github.com/freiburgermsu/codons/blob/main/examples/translation-transcription/codons-BLASTp/protein_blast_results.xml). Could the error be in how [this function](https://github.com/freiburgermsu/codons/blob/main/codons/genes.py#L334-L364) that calls `qblast`? or perhaps is the error in the structure of the above multi-FASTA file itself? 

Would the `short_query` argument be applicable for a multi-FASTA file that has a large diversity in the lengths of the protein sequences?

I greatly appreciate your code and support.

**Comment by MarkusPiotrowski** [comment]
@freiburgermsu

Reading [here](https://www.ncbi.nlm.nih.gov/guide/howto/submit-mult-seq-blast/) and [here](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=FAQ#sigxcpu) it seems that you need to reduce the number of sequences.

Regarding short queries, I would use the `short_query` argument only for short queries. I haven't the number of aa in my mind, but something like <10 aa sounds sensible.

**Comment by freiburgermsu** [comment]
Hello @MarkusPiotrowski ,

[Running each sequence individually](https://github.com/freiburgermsu/codons/blob/main/codons/genes.py#L384-L389), and using `short_query` ad hoc, seems to have resolved the bug. Thank you for the links and suggestion.
:)

Andrew

**Comment by MarkusPiotrowski** [comment]
@freiburgermsu You're welcome.

Closing now.

**Comment by CDI-PMCC** [comment]
it means 1000DNAsequence unable to blast through the function? but i got positive result once ,but further same problem
