### ISSUE TITLE
Stack trace with Entrez.read from medline efetch on Alpine Linux 3.12–3.15

### ISSUE THREAD

**Issue by nutjob4life** [biopython/biopython#3869]
### Setup

| Component   | Version                                         |
|:------------|:------------------------------------------------|
| Python      | `3.9.5 (default, Nov 24 2021, 21:19:13)`        |
| Platform    | `CPython`, `Linux-5.10.47-linuxkit-x86_64-with` |
| `biopython` | `1.79`                                          |
| OS          | Alpine 3.15                                     |
| Docker      | `20.10.10`                                      |

I'm running the following:

```python
from Bio import Entrez
from contextlib import closing
Entrez.tool = 'xml-parse-error'
Entrez.email = 'sean.kelly@nih.gov'
pubMedIDs = ['12810677']
with closing(Entrez.efetch(db='pubmed', retmode='xml', rettype='medline', id=pubMedIDs)) as ef:
    records = Entrez.read(ef)
```

### Expected behaviour

I expect no output.

### Actual behaviour

I get a stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.9/site-packages/Bio/Entrez/__init__.py", line 508, in read
    record = handler.read(handle)
  File "/usr/lib/python3.9/site-packages/Bio/Entrez/Parser.py", line 335, in read
    self.parser.ParseFile(handle)
  File "/home/buildozer/aports/main/python3/src/Python-3.9.7/Modules/pyexpat.c", line 407, in StartElement
  File "/usr/lib/python3.9/site-packages/Bio/Entrez/Parser.py", line 596, in startElementHandler
    parent.store(element)
  File "/usr/lib/python3.9/site-packages/Bio/Entrez/Parser.py", line 200, in store
    raise ValueError("Unexpected item '%s' in dictionary" % key)
ValueError: Unexpected item 'AffiliationInfo' in dictionary
```

### Steps to reproduce

```console
$ docker container run --rm --interactive --tty --entrypoint /bin/sh alpine:3.15
/ # apk update --quiet
/ # apk add --no-progress --quiet gcc libxml2-dev libxslt-dev musl-dev python3-dev py3-numpy
/ # python3 -m ensurepip --upgrade
Looking in links: /tmp/tmp_t9ga3a1
Processing /tmp/tmp_t9ga3a1/setuptools-57.4.0-py3-none-any.whl
…
/ # pip3 install --quiet --upgrade pip setuptools wheel biopython==1.79
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager
…
/ # python3
Python 3.9.7 (default, Nov 24 2021, 21:15:59) 
[GCC 10.3.1 20211027] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import Entrez
>>> from contextlib import closing
>>> Entrez.tool = 'xml-parse-error'
>>> Entrez.email = 'sean.kelly@nih.gov'
>>> pubMedIDs = ['12810677']
>>> with closing(Entrez.efetch(db='pubmed', retmode='xml', rettype='medline', id=pubMedIDs)) as ef:
...     records = Entrez.read(ef)
...
Traceback (most recent call last):
…
ValueError: Unexpected item 'AffiliationInfo' in dictionary
```

👉 **Note:** If you change `alpine:3.15` to `alpine:3.11` or earlier, then it works.

### Workaround

(Sorry for the late edit.) The problem seems to be exposed by the `expat` package. If you do:
```console
$ docker container run --rm --interactive --tty --entrypoint /bin/sh alpine:3.15
/ # echo '@old https://dl-cdn.alpinelinux.org/alpine/v3.11/main' >> /etc/apk/repositories
/ # apk update --quiet
/ # apk add --no-progress --quiet gcc libxml2-dev libxslt-dev musl-dev python3-dev py3-numpy
/ # apk add expat@old
(1/1) Downgrading expat@old (2.4.5-r0 -> 2.2.9-r1)
Executing busybox-1.34.1-r3.trigger
OK: 316 MiB in 54 packages
```
then proceed to `ensurepip`, `pip install`, etc., it also works on Alpine 3.15. However, it'd be nice to use Expat ≥ 2.4 as these contain [security fixes](https://libexpat.github.io/doc/news/).

**Comment by mdehoon** [comment]
I cannot reproduce this with Biopython 1.79. Since the bug disappears if you use `alpine:3.11`, the problem may lie with `alpine:3.15` instead of in Biopython.

**Comment by nutjob4life** [comment]
@mdehoon looks like you won't have to change a thing:

⚠️ Expat 2.4.6 (released 2022-02-20) identifies and fixes a [regression in elementDecl handling](https://github.com/libexpat/libexpat/blob/R_2_4_6/expat/Changes) which Entrez's Parser uses quite a bit to figure out the DTD. 

Upgrading to Expat 2.4.6 fixes things!

But others be warned: if you're using Expat 2.4.5—especially with Musl libc, apparently—you may encounter problems.
