### ISSUE TITLE
Clarification on license

### ISSUE THREAD

**Issue by pnsvk** [biopython/biopython#3871]
When I tried to fetch this package through our enterprise internal scanner, it failed with the message: UNKNOWN License..

Checked PYPI to find that it is released under: Biopython License Agreement.

Can you let me know where the license detail exists ? and are there any plans to release it under more popular licenses like BSD, MIT etc.

**Comment by peterjc** [comment]
See https://github.com/biopython/biopython/blob/master/LICENSE.rst

Being described as "UNKNOWN" likely reflects that *Biopython License Agreement* is a unique license, we are working towards adopting the 3-clause BSD license which is very widely recognised - see #898.

**Comment by pnsvk** [comment]
Thank You.. for the update.. @peterjc 
#898 seems to be a never ending thread.. Can you let me know if there is a time-line on that transition ? (to reflect on PYPI I mean.. Coz, that's where our package pipeline pulls --> scans from)

**Comment by peterjc** [comment]
No end date in sight, there are assorted sub-issues for specific modules where we're having trouble tracking down one or two final contributors. And then we'll start on the test suite.

For now, you have to just use *Biopython License Agreement* which is very nearly the same as https://opensource.org/licenses/HPND
