### ISSUE TITLE
Still getting memory leaks with global mode PairwiseAligner (v 1.79)

### ISSUE THREAD

**Issue by derrik-gratz** [biopython/biopython#3879]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 16:02:23) [Clang 11.1.0 ] CPython
macOS-10.15.7-x86_64-i386-64bit
1.79

I have also replicated this on my windows machine, also with python 3.10 and Biopython 1.79

### Expected behaviour

My program calls `PairwiseAligner` to do many global comparisons, sometimes 50 million or more. On smaller datasets, it is able to run to completion, but larger datasets crash with out of memory errors.

### Actual behaviour

Using the `PairwiseAligner` for global alignment with large datasets causes my program to crash with an out of memory error. Tracing memory use with `memory_profiler` shows memory incrementally increasing with each call of `PairwiseAligner`. If I instead use `pairwise2`, the memory use stays constant.

### Steps to reproduce

```
#!/usr/bin/env python
from Bio import Align
from Bio import pairwise2

aligner = Align.PairwiseAligner()# add parameters here
aligner.mode = 'global'
aligner.match_score = 4
aligner.mismatch_score = -4
aligner.query_open_gap_score = -4
aligner.query_extend_gap_score = -3.99
aligner.target_open_gap_score = -4
aligner.target_extend_gap_score = -3.99

tmp1 = "TGAATTGGAACTGTGCAATTCGAGTGGCTTTGACAATCCCTTGTTACTAGAGTGCTGCCCAACTCG"
tmp2 = "TGAGTTGGAACTGTGCAATTCGAGTGGCTTTGACAATCCCTTGTTACTAGAGTGCTGCCCAACTCG"

import os, psutil
process = psutil.Process(os.getpid())

print('First, memory use with pairwise2')
for i in range(100000):
    a = pairwise2.align.globalms(tmp1, tmp2, 4, -4, -4, -3.99, one_alignment_only=True)
    if i % 10000 == 0:
        print(process.memory_info().rss)

print('\nNow the PairwiseAligner approach')
for i in range(100000):
    a = aligner.align(tmp1, tmp2)[0]#oligos[read.mapping_oligo][args.primer1:args.primer1+align_length])
    if i % 10000 == 0:
        print(process.memory_info().rss)
print("\nNow PairwiseAligner in local mode")
aligner.mode="local"
for i in range(100000):
    a = aligner.align(tmp1, tmp2)[0]#oligos[read.mapping_oligo][args.primer1:args.primer1+align_length])
    if i % 10000 == 0:
        print(process.memory_info().rss)
```

```
First, memory use with pairwise2
27860992
29954048
30052352
30093312
30134272
30154752
30154752
30162944
30171136
30171136

Now the PairwiseAligner approach
30236672
45461504
62038016
78626816
95215616
111800320
128376832
144957440
161550336
178135040

Now PairwiseAligner in local mode
194711552
194719744
194719744
194719744
194719744
194719744
194719744
194719744
194719744
194719744
```

**Comment by peterjc** [comment]
Are you able to compile the latest code from source? It appears to be working for me on macOS (no memory increases on the ``PairwiseAligner`` examples, although there may be a leak in the deprecated ``pairwise2`` example):

```
$ python bug3879.py 
/Users/.../repositories/biopython/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
First, memory use with pairwise2
27271168
28704768
28831744
28872704
28913664
28934144
28962816
28979200
29003776
29003776

Now the PairwiseAligner approach
29052928
29052928
29052928
29052928
29052928
29052928
29052928
29052928
29052928
29052928

Now PairwiseAligner in local mode
29061120
29061120
29061120
29061120
29061120
29061120
29061120
29061120
29061120
29061120
```

**Comment by peterjc** [comment]
(Your example run on your machine appears to show a possible memory leak in both ``pairwise2`` and global ``PairwiseAligner``, so it appears the global ``PairwiseAligner`` leak has been fixed)

**Comment by derrik-gratz** [comment]
I will try compiling the latest version. I should have mentioned my Biopython version was downloaded through the conda-forge conda channel.

**Comment by mdehoon** [comment]
@derrik-gratz  With PairwiseAligner, there is a memory leak in release 1.79. This memory leak has been fixed, so could you try again with the latest Biopython source from github?

**Comment by derrik-gratz** [comment]
Downloading the latest version from github did fix this. Is there a timeline for when the package is expected to be updated in conda? I am trying to distribute a snakemake pipeline with conda envs so users don't have to manually download and compile from github.

**Comment by derrik-gratz** [comment]
Thank you!
