### ISSUE TITLE
FastaIterator has no attribute `next` 

### ISSUE THREAD

**Issue by michaelfyc** [biopython/biopython#3884]
### Setup

I am reporting a problem with Biopython 1.79, Python 3.10, and operating
system Windows 10.

I was trying to split a large fasta file into fragments with fixed sequence length by the `batch_iterator` method written here: https://biopython.org/wiki/Split_large_file

But when reading fasta file, the iterpreter complains that FastaIterator has no `next()` attribute.

### Expected behaviour

Split the fasta file into fragments in batch size.

### Actual behaviour

![image](https://user-images.githubusercontent.com/45136049/159156334-e1d357a3-785d-4192-a2a6-7179431b6c37.png)

### Steps to reproduce
1. Define the `batch_iterator` method as the wiki link demonstrates;
2. run 

```python
	record_iter = SeqIO.parse(open('path/to/sequence.fna'), 'fasta')
    for i, batch in enumerate(batch_iterator(record_iter, 3000)):
        filename = 'reference_%i.fasta' % (i + 1)
        with open('/path/files/' + filename, 'w') as output_handle:
            count = SeqIO.write(batch, output_handle, 'fasta')
        print('Wrote %i records to %s' % (count, filename))
```

**Comment by peterjc** [comment]
The example needs updating for Python 3, to use the built-in ``next(...)`` function.

**Comment by peterjc** [comment]
I wonder if there is a more elegant solution, nothing in https://docs.python.org/3/library/itertools.html looks quite right though...

**Comment by BrutalStark** [comment]
change entry = iterator.next() in function batch_iterator -> entry = next(iterator)

**Comment by peterjc** [comment]
@BrutalStark yes, that's what I meant. Since the original reported never replied, do you want to make the change?

**Comment by peterjc** [comment]
Ah, the "next" was never in the example page - it was in the code. You must have used an older Biopython which lacked that Python 3 fix?
