### ISSUE TITLE
Blast search hangs indefinitely instead of throwing error

### ISSUE THREAD

**Issue by luojxxx** [biopython/biopython#3886]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:25:35) 
[Clang 12.0.5 (clang-1205.0.22.11)]
CPython
macOS-12.0.1-x86_64-i386-64bit
1.79

### Expected behaviour

I'm attempting to blast search the elephant refseq genome database (taxid: 9785) using the p53 cds as the query.

### Actual behaviour

Hangs indefinitely

### Steps to reproduce

`result_handle = NCBIWWW.qblast("blastn", "refseq_genomes", sequence_variable)`

When searching database 'nt', it does eventually work. However, 'refseq_genomes' just hangs. And also I can't seem to figure out how to limit the search to just elephants, which is contributing to the problem, since it's a required parameter in the ncbi website's blast gui. I guess I'm expecting it to throw an error with appropriate information about how to specify the organism and correct the query.

**Comment by MarkusPiotrowski** [comment]
Try to include `entrez_query="txid9780 [ORGN]"` to restrict your search to elephants.

Regarding "hangs indefinitely": This is mainly a problem of the Blast server itself (which just can take forever). The other problem is that `NCBIWWW.qblast` is forever waiting for a response. While we think about including a `timeout` option to allow the user to stop a search, this also bears the risk that such an option would be misused to repeatedly sending a request that does seem to 'hang'. I guess this may the main reason why the `qblast` function was designed in the way it is.

**Comment by luojxxx** [comment]
Thank you for the suggestion, I didn't know about entrez, so it worked once (although now the same query is back to hanging indefinitely). But ultimately it seems like the API works at an order of magnitude slower than the website, so I'll need to switch to querying the sequence locally. Thank you again for the help!
