### ISSUE TITLE
How to easily check for ambiguous alphabet/letters in a sequence?

### ISSUE THREAD

**Issue by liubovch** [biopython/biopython#3892]
Hi,

After the Alphabet was removed, what is a Biopython way to check for ambiguous letters now? For example, I have a set of proteins records, and I would like to catch those sequences that use other than generic letters?

**Comment by peterjc** [comment]
Curiously ``Bio.Alphabet`` never helped validate or enforce specific letters in sequences anyway. I would use these two strings defined in IUPACData and Python sets, e.g.

```
from Bio.Data.IUPACData import protein_letters, extended_protein_letters
my_seq = "MAPR*"
print(set(my_seq).difference(protein_letters))
```

**Comment by liubovch** [comment]
That is true, and I only remember using Alphabet's letters attribute for a similar check. Thank you a lot for pointing me out to the IUPACData module!

**Comment by peterjc** [comment]
Ah yes, the ``Bio.Alphabet`` had IUPAC protein classes using those two letter lists from ``Bio.Data.IUPACData``. Glad that's resolved.
