### ISSUE TITLE
Matching internal coordinates between protein structures doesn't work as expected (?)

### ISSUE THREAD

**Issue by AndreeaMusat** [biopython/biopython#3900]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]

CPython
Linux-5.13.0-30-generic-x86_64-with-debian-bullseye-sid

1.79

### Expected behaviour

The ```atom_to_internal_coordinates()``` method computes the internal coordinates of a protein, namely: dihedral angles (for backbone + side chains), as well as bond lengths and angles. In order to play around with this functionality, I am considering the following toy problem: given two conformations of the same protein (one chain each, same residues and atoms, but different 3D positions), I want to generate internal coordinates for both of them, then I want to update the internal coordinates of the first one in order to be equal to the internal coordinates of the second one. 

By doing this, after assembling back the 3D coordinates from the internal ones using the ```internal_to_atom_coordinates()``` method, I expect the two protein structures to be the same up to a rotation and a translation (i.e. I expect Kabsch RMSD to be close to zero). 

### Actual behaviour

What happens in practice, though, is that the Kabsch RMSD increases after updating the first structure.  For example, in the image below, the cyan and green ones are initial structure1 and structure2, respectively, while the pink one is structure1 after changing its internal coordinates to match the ones of structure2. As you can see, the pink one is extremely different.

![biopython_internal_coord_post_matching](https://user-images.githubusercontent.com/9498914/162024587-0f7f387a-6cd5-475f-b0c9-ddc4cdb7c368.png)

There might be something wrong with the way I update the structure1's internal coordinates to match structure2's internal coordinates, but I am not sure what, so could you please have a look at the code below?

Many thanks in advance!

### Steps to reproduce

Data: 
![protein1.pdb](https://github.com/AndreeaMusat/issues_files/blob/main/protein1.pdb)
![protein2.pdb](https://github.com/AndreeaMusat/issues_files/blob/main/protein2.pdb)

Code snippet:

```python
import Bio
import numpy as np

from Bio.PDB import *
from Bio.SVDSuperimposer import SVDSuperimposer


def get_atom_pos(structure):
	atom_pos = [a.get_coord() for a in structure.get_atoms()]
	atom_pos = np.array(atom_pos)

	return atom_pos


def compute_kabsch_rmsd_and_align(structure1, structure2):
	atoms1 = get_atom_pos(structure1)
	atoms2 = get_atom_pos(structure2)

	kabsch_rmsd_calculator = SVDSuperimposer()
	kabsch_rmsd_calculator.set(atoms1, atoms2)
	kabsch_rmsd_calculator.run()

	rmsd = kabsch_rmsd_calculator.get_rms()
	R, t = kabsch_rmsd_calculator.get_rotran()

	# Rotate structure1 onto structure2.
	for atom in structure1.get_atoms():
		atom.transform(R, t)

	return rmsd

# Proteins were manually processed (aligned, so some residues were removed).
# Increase MaxPeptideBond to still capture all angles.
internal_coords.IC_Chain.MaxPeptideBond = 100.0

parser = PDBParser(PERMISSIVE=1, QUIET=1)

# These 2 have the same chain, residues & atoms, but
# different atom positions.
structure1 = parser.get_structure('', 'protein1.pdb')
structure2 = parser.get_structure('', 'protein2.pdb')

rmsd_before = compute_kabsch_rmsd_and_align(structure1, structure2)
print('Kabsch RMSD before: {}'.format(rmsd_before))

# Generate internal coordinates for both.
structure1.atom_to_internal_coordinates()
structure2.atom_to_internal_coordinates()

# Toy example: set the torsion angles, angles and
# bond lengths of structure1 to the same values as
# structure2, reconstruct atom coordinates of 
# structure1 and expect the structures to be the
# same (up to a rotation and a translation)

# Each structure has exactly 1 chain.
ic_chain1 = list(structure1.get_chains())[0].internal_coord
ic_chain2 = list(structure2.get_chains())[0].internal_coord

# OK.
assert len(ic_chain1.dihedra) == len(ic_chain2.dihedra)
assert len(ic_chain1.hedra) == len(ic_chain2.hedra)

# Copy dihedral angles.
for key in ic_chain1.dihedra.keys():
	ic_chain1.dihedra[key].angle = ic_chain2.dihedra[key].angle

# Copy angles and bond lengths.
for key in ic_chain1.hedra.keys():
	ic_chain1.hedra[key].len12 = ic_chain2.hedra[key].len12
	ic_chain1.hedra[key].len23 = ic_chain2.hedra[key].len23
	ic_chain1.hedra[key].angle = ic_chain2.hedra[key].angle

# Assemble XYZ coordinates back for structure1.
structure1.internal_to_atom_coordinates()

# We now expect structure1 and structure2 to be the same up
# to a rotation and a translation.
rmsd_after = compute_kabsch_rmsd_and_align(structure1, structure2)
print('Kabsch RMSD after: {}'.format(rmsd_after))

# Write new structure1 for visualizing it.
io = PDBIO()
io.set_structure(structure1)
io.save('protein1_new.pdb')
```

**Comment by rob-miller** [comment]
Hi Andreea,

1. You found a bug in the setter for len12 in Biopython 1.79, sorry about that.  len12, angle, and len23 are tied to the .lal array in the Hedron class, and that array doesn't get updated by the len12 setter in 1.79 due to a misplaced comment.
2. To make your code do what you expect, change to this:
```
# Copy angles and bond lengths.
for key in ic_chain1.hedra.keys():
    ic_chain1.hedra[key].lal[0] = ic_chain2.hedra[key].lal[0]
    ic_chain1.hedra[key].len23 = ic_chain2.hedra[key].len23
    ic_chain1.hedra[key].angle = ic_chain2.hedra[key].angle
```
This makes the Kabsch RMSD come out to 0.583 .
3. This is fixed when Biopython 1.80 comes out and your original code works as expected - but the .lal attribute is removed, so the fix will not.  Re-writing to use the Hedron or Residue set_length() functions would work with both.

**Comment by rob-miller** [comment]
I think the best thing to do with a 1.79 installation is to fix it locally:

    python3 -m site

Will tell you where your site-packages are.  Edit `Bio/PDB/internal_coords.py`, find:

    @len12.setter
    def len12(self, len):
        """Set first length for Hedron; sets needs_update."""
        self.lal[0]  # _len12 = len
        self.cic.hAtoms_needs_update[self.cic.hedraNdx[self.aks]] = True

Change (one line) to:

    @len12.setter
    def len12(self, len):
        """Set first length for Hedron; sets needs_update."""
        self.lal[0] = len
        self.cic.hAtoms_needs_update[self.cic.hedraNdx[self.aks]] = True

With this fix (or monky-patching) your code will work with 1.79 and 1.80.  

On your code, adding:

    from Bio.PDB.PICIO import *
    ...
    write_PIC(structure1, "protein1.pic")
    write_PIC(structure2, "protein2.pic")
    ...
    write_PIC(structure1, "protein1_new.pic")

also helps to see what is happening if you look at the .pic files.

**Comment by AndreeaMusat** [comment]
many, many thanks for your help!
