### ISSUE TITLE
Bio.PDB.SASA.ShrakeRupley unable to deal with unknown atoms

### ISSUE THREAD

**Issue by ChrisChemHater** [biopython/biopython#3904]
### Setup

I am reporting a problem with Biopython version 1.79, Python version 3.9.10, and operating
system Ubuntu20.04.1 as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0]
CPython
Linux-5.13.0-39-generic-x86_64-with-glibc2.31
1.79

In fact this is a very simple mistake, probably caused by the author's carelessness. Anyone can locate and fix this in a second.

In `Bio/PDB/SASA.py`, line 44: 

`ATOMIC_RADII = collections.defaultdict(lambda x: 2.0)`

which should be:

`ATOMIC_RADII = collections.defaultdict(lambda : 2.0)`

The `default_factory` argument of `collections.defaultdict` is supposed to be 0-argument callable object (for details, see https://docs.python.org/3/library/collections.html#collections.defaultdict). Otherwise, you will receive an `TypeError` when trying to get an item that doesn't exist in the dictionary.

**Comment by ChrisChemHater** [comment]
Someone has already noticed this problem: https://github.com/biopython/biopython/pull/3777
Closing

**Comment by JoaoRodrigues** [comment]
Thanks for the report @ChrisInBed, the other PR had gone unnoticed but it's been merged now.
