### ISSUE TITLE
DSSP.py refers to unavailable and obsolete version

### ISSUE THREAD

**Issue by drlemmus** [biopython/biopython#3909]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

Biopython 1.75 and higher, Python: all, OS: all

### Expected behaviour

Reference to DSSP version 4.0 (https://github.com/PDB-REDO/dssp/)

### Actual behaviour

Reference to DSSP version 2.0 (with dead link)

### Steps to reproduce

Read documentation of Bio.PDB.DSSP module

### Background
There have been many update to DSSP functionality since version 2 including the addition of PPII (or kappa) helix detection, mmCIF support, and direct annotation of coordinate files. An updated reference to a more recent DSSP version could be beneficial to users.

**Comment by peterjc** [comment]
See #3775 and linked issues.
