### ISSUE TITLE
Full text links from Pubmed database on NCBI Entrez

### ISSUE THREAD

**Issue by Hilal-Urun** [biopython/biopython#3915]
Hi, I want to ask that  how can I get these full text links. For example 
`    def fetch_details(self, id_list):
        ids = ','.join(id_list)
        Entrez.email = 'your.email@example.com'
        handle = Entrez.efetch(db='pubmed',
                               retmode='xml',
                               id=ids)
        results = Entrez.read(handle)
        print(results)
        return results`
this fetch_details function returns a pubmed information for it but the links are not included, is there any method in Entrez for reaching this Links?
Thank you!
<img width="1088" alt="Screenshot 2022-04-29 at 17 19 54" src="https://user-images.githubusercontent.com/37075702/165963075-3eca28c2-f46d-4830-a5db-895288fd53bd.png">

**Comment by peterjc** [comment]
I don't know, perhaps via elink? You would be best emailing the NCBI contact address for advice - please do update this issue based on what feedback they give.

**Comment by simonmesmith** [comment]
Try this:

`link_handle = Entrez.elink(dbfrom="pubmed", id=ids, linkname="pubmed_pubmed", **cmd="llinkslib"**)
link_results = Entrez.read(link_handle)`

Using cmd="llinkslib" gets you linkouts for IDs provided, when available.

You'll have to traverse the results through IdUrlList -> IdUrlSet[] -> ObjUrl[] -> Url to get the links.

You'll then have to proceed depending on what link you get, such as to a third-party (like Elsevier) or a PMC article.

There may be a better way to do this, but I think this should work.

**Comment by Hilal-Urun** [comment]
hey @simonmesmith . yes it works. thank you so much ✨
