### ISSUE TITLE
SeqRecord object annotation field missing after slice 

### ISSUE THREAD

**Issue by edenagar** [biopython/biopython#3916]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.9.12 (main, Mar 26 2022, 15:51:15) 
[Clang 13.1.6 (clang-1316.0.21.2)]
CPython
macOS-12.2-x86_64-i386-64bit
1.79

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

when using slice method on a SeqRecord object that was generated from an AB1 using seqIO read
the annotation field should be aligned to the slice location

### Actual behaviour

the annotation field is empty 

### Steps to reproduce

slicing a seqRecord object that was generated from an AB1 using seqIO read like so
`data = SeqIO.read('./N2_em_nhr_100.ab1', `"abi")`

`sliced_Data = data[:6]`

**Comment by peterjc** [comment]
So which data are you missing?

**Comment by edenagar** [comment]
'abif_raw' of the sliced data

**Comment by peterjc** [comment]
This is appears to be behaving as designed and documented https://biopython.org/docs/latest/api/Bio.SeqRecord.html#Bio.SeqRecord.SeqRecord.__getitem__

The 'abif_raw' is a very complicated dictionary giving access to all the ABI raw data, and while some of those fields might be suitable for slicing (?), most are not. If you need any of that data, it is up to you to decide how to interpret it.
