### ISSUE TITLE
Convert Bio.Seq.Seq to np.ndarray

### ISSUE THREAD

**Issue by hadim** [biopython/biopython#392]
I am surprise to not find a function or method to "numerize" a sequence into a numpy array. Am I missing something ?

**Comment by Svikashini** [comment]
I got an error Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'module' object has no attribute 'numerize' while i gave the code seq_array = Bio.numerize(seq) to convert the sequence into numpy array
how to rectify it

**Comment by peterjc** [comment]
@Svikashini there is no ``Bio.numerize`` method, that was @rrymer's suggestion. I gave a working example earlier in this issue.

**Comment by Svikashini** [comment]
i couldnt found out the example. 
Kindly suggest me again

**Comment by peterjc** [comment]
@Svikashini The example I'm talking about is already in the Tutorial, search for "Alignments as arrays" http://biopython.org/DIST/docs/tutorial/Tutorial.html

```
>>> import numpy as np
>>> from Bio import AlignIO
>>> alignment = AlignIO.read("PF05371_seed.sth", "stockholm")
>>> align_array = np.array([list(rec) for rec in alignment], np.character)
>>> print("Array shape %i by %i" % align_array.shape)
Array shape 7 by 52
```

If you want to turn a single sequence into a one dimensional array you can do something very similar.

**Comment by Svikashini** [comment]
I need to do single sequence into an one dimensional array
how can we do that

**Comment by peterjc** [comment]
Here is one way to turn a string into a one dimensional numpy array,

```
>>> import numpy as np
>>> my_array = np.array(list("Hello world"), np.character)
>>> my_array
array(['H', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd'], 
      dtype='|S1')
```

You can do the same to turn a Biopython ``Seq`` object into a one dimensional numpy array of characters - in fact in this case the list function isn't needed:

```
>>> from Bio import Seq
>>> from Bio.Seq import Seq
>>> from Bio.Alphabet import generic_dna
>>> my_seq = Seq("ACGTACGT", generic_dna)
>>> import numpy as np
>>> my_array = np.array(my_seq, np.character)
>>> my_array
array(['A', 'C', 'G', 'T', 'A', 'C', 'G', 'T'], 
      dtype='|S1')
```

**Comment by Svikashini** [comment]
I need to convert 'ACTTCAG' into [0, 1, 2, 2, 1, 0, 3].
how can i acheive this.

**Comment by peterjc** [comment]
@Svikashini This would have been more suited to ask this on our mailing list or somewhere like http://www.biostars.org (tag the question with biopython), rather than an existing GitHub issue on a different topic.

You should include in your question the full desired mapping (e.g. ``'A'`` to ``0``) including what you want to do about mixed case (also ``'a'`` to ``0``?), ambiguous bases (e.g. ``'N'`` or ``'W'``) or characters which are not DNA letters (e.g. ``'-'`` or ``'9'``).
