### ISSUE TITLE
Trying to access go term evidence codes on a SeqRecord.

### ISSUE THREAD

**Issue by mah51** [biopython/biopython#3924]
### Setup

```python
proteins = SeqIO.parse(input_file, "uniprot-xml")
```

The go terms are in the dbxrefs array, however they aren't paired with their ECO codes. Is this information parsed?

Thanks

**Comment by peterjc** [comment]
The database cross references list was a very simple data structure pre-existing the UniProt parser, and keeping the same structure as our older parsers was likely prioritised.

I see nothing specific to GO terms in https://github.com/biopython/biopython/blob/master/Bio/SeqIO/UniprotIO.py - which XML tags are you looking at?

Capturing more details may require changes to the parser, perhaps storing GO ECO codes in a dictionary in the record's annotation dict?

**Comment by mah51** [comment]
```
<dbReference xmlns="http://uniprot.org/uniprot" type="GO" id="GO:0042610">
    <property type="term" value="F:CD8 receptor binding"/>
    <property type="evidence" value="ECO:0000314"/>
    <property type="project" value="UniProtKB"/>
</dbReference>
```

The Gene Ontology type dbReference tag. It contains an evidence code which I need to check. I did find some evidence codes in the annotation.types array.

What would be the best way to go about changing the parser? do you mean locally or as a pr?


Thanks!

**Comment by peterjc** [comment]
Depending on your needs, you might find using an XML parser from the standard Python library a better fit than trying to modify the ``SeqRecord``-centric design in ``Bio/SeqIO/UniprotIO.py``. I would recommend this if you only care about the ECO terms for each record.

If you are already heavily using the ``SeqRecord``, then I would start with modifying the parser locally and if you can get something useful then consider making a pull request.

**Comment by mah51** [comment]
great, thank you.

**Comment by mah51** [comment]
@peterjc Sorry to be a nuisance but looking at the UniprotIO class there is a function _parse_dbReference: https://github.com/biopython/biopython/blob/master/Bio/SeqIO/UniprotIO.py#L309. Unfortunately I am not very experienced with python so I am not sure how to but is it possible to 'hot swap' a function of my own in place of the libraries function?

Thanks

**Comment by peterjc** [comment]
I would guess it is the last line of that method you might want to change:

``pass  # this data cannot be fitted in a seqrecord object with a simple list. however ..``

In Python "hot swaps" are usually called "Monkey Patching", and here I think you would have to directly use an instance of the ``Parser`` class in order to do that. i.e. Not using ``Bio.SeqIO.parse(...)`` or ``Bio.SeqIO.read(...)``, but instead using a modified version of the ``UniprotIterator`` function. This would be messy.

It would certainly be easier to start by modifying your local copy of Biopython.

**Comment by mah51** [comment]
Ah I see, thanks for all your help.
