### ISSUE TITLE
AttributeError: 'IntegerElement' object has no attribute 'value'

### ISSUE THREAD

**Issue by phage-GP** [biopython/biopython#3929]
### Setup

I'd like to know how to get the value from class 'Bio.Entrez.Parser.xxxElement', an example  is here: 

```python
>>> result[0]['PubMedIds']
[IntegerElement(35502319, attributes={})]
>>> type(result[0]['PubMedIds'][0])
<class 'Bio.Entrez.Parser.IntegerElement'>
>>> result[0]['PubMedIds'][0].attributes
{}
>>> result[0]['PubMedIds'][0].value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IntegerElement' object has no attribute 'value'
```

### Expected behaviour

`Bio.Entrez.Parser.IntegerElement(value, tag, attributes, key=None)`
In this example, my goal is to get the number(35502319) in it.

--------------
Thanks for your help!

**Comment by mdehoon** [comment]
Have you tried
```python
>>> int(result[0]['PubMedIds'][0])
```

**Comment by mdehoon** [comment]
Btw probably you won't need to convert an `IntegerElement` to a plain `int`; you can use an `IntegerElement` as if it were a plain `int`. For example,
```python
>>> result[0]['PubMedIds'][0] == 35502319
True
```

**Comment by phage-GP** [comment]
> 你试过吗
> 
> ```python
> >>> int(result[0]['PubMedIds'][0])
> ```

👍 :Thanks. It works.

**Comment by phage-GP** [comment]
> Have you tried
> 
> ```python
> >>> int(result[0]['PubMedIds'][0])
> ```

👍 Thanks. It works. @mdehoon
