### ISSUE TITLE
how to extract residue coordinates from mmcif file by using Bio?

### ISSUE THREAD

**Issue by onlyonewater** [biopython/biopython#3932]
hi, I am new to bioinformatics, and I want to know how to extract residue coordinates from mmcif file by using Bio?

**Comment by onlyonewater** [comment]
Nobody knows?

**Comment by JoaoRodrigues** [comment]
Hi there,

Have you checked our tutorial and/or documentation? There's a section on
"Going 3D" that covers the MMCIF parser and the Structure object we use to
store coordinate data. See
https://biopython.org/DIST/docs/tutorial/Tutorial.html#sec182

Unless you have a more specific question, I suggest you start there.

**Comment by onlyonewater** [comment]
oh, I get it, thanks!!!
