### ISSUE TITLE
Access to canonical REBASE identifiers via Bio.Restriction

### ISSUE THREAD

**Issue by jakebeal** [biopython/biopython#3934]
I would like to request a feature to be added to Biopython.

The `Bio.Restriction` package is excellent in providing access to the REBASE database of restriction enzymes. However, there is currently no way to access the canonical REBASE identifiers.

For FAIR sharing of data, it is strongly preferable to use stable identifiers, such as those provided in identifiers.org. REBASE has an entry there already: https://registry.identifiers.org/registry/rebase

The canonical identifiers for REBASE, however, are numerical identifiers and not names. For example, the `SapI` enzyme is identifier 1593, accessible through the canonical ID rebase:1593 or https://identifiers.org/rebase:1593. 

Currently, in order to map between REBASE IDs and objects in Bio.Restriction, it is necessary to maintain a separate dictionary. Instead, it would be good to make the identifiers accessible via dictionaries in Bio.Restriction. All of the information is readily available at the building for `Restriction_Dictionary.py`, but isn't currently used.

**Comment by MarkusPiotrowski** [comment]
@jakebeal I have always thought about `Bio.Restriction` as a tool for people who use it for cloning (or writing programs that assist in cloning) or drawing plasmid maps etc. In this context, I have never stumbled across REBASE identifiers for restriction enzymes (except their unique name).
Apart from that, `Bio.Restriction` uses the REBASE `emboss` files via the two scripts `rebase_update.py` and `ranacompiler.py`  (which you find both in the Script folder of our repository). You wrote that "the information is readily available at the building for `Restriction_Dictionary.py`" but, as far as I can see, the `emboss` files do *not* contain a REBASE identifier for the enzymes, do they?

I want to add that `Bio.Restriction` is a rather ancient part of Biopython, and we are happy if we could keep it living. There have been at least one attempt to write a new `Restriction` module for Biopython (PR #268), but to no avail so far.

**Comment by jakebeal** [comment]
Hmm... looks like you're right, and the emboss files dont' have it. There are a separate set of NCBI LinkOut files that they serve that do appear to have that information, however. I'm going to play with them some and see if I can figure out a mashup.

**Comment by jakebeal** [comment]
Looks like Bairoch format is a good answer: http://rebase.neb.com/rebase/rebase.f19.html
I am working on a patch to add an "id" and "uri" field to restriction enzymes based on these entries.

**Comment by jakebeal** [comment]
@MarkusPiotrowski I've had a pull request pending for more than a week now with zero response: the maintainers have not enabled the CI run yet. Any idea if this is typical for the maintainers, or if there is somebody that I should be pinging?
