### ISSUE TITLE
Unclear alternative for obsolete code in `Bio.SeqFeature`

### ISSUE THREAD

**Issue by mdehoon** [biopython/biopython#3961]
Some methods in `Bio.SeqFeature` are declared obsolete with a suggested alternative.
However, I don't see how the alternative could be applied without knowing the class.

As an example, the `position` attribute is declared obsolete. The alternatives depend on the class: 
```python
ExactPosition: int(self)
UnknownPosition: None
WithinPosition: self._left
BetweenPosition: self._left
BeforePosition: int(self)
AfterPosition: int(self)
OneOfPosition: min(int(pos) for pos in self.position_choices)
```

The `position` attribute is used, for example, in the `__init__`` function of `FeatureLocation`:
```python
        if (
            isinstance(self.start.position, int)
            and isinstance(self.end.position, int)
            and self.start > self.end
        ):
```

If the `position` attribute is obsolete, we should not be using it. But to replace it, we'd have to know the class, so you would have to replace
```python
start = self.start.position
```
by something like
```python
if isinstance(self.start, (ExactPosition, BeforePosition, AfterPosition)):
    start = int(self.start)
elif isinstance(self.start, (WithinPosition, BetweenPosition)):
    start = self._left
elif isinstance(self.start, UnknownPosition):
    start = None
elif isinstance(self.start, OneOfPosition):
    start = min(int(pos) for pos in self.position_choices)
```
which is not clean Python code.

**Comment by peterjc** [comment]
In general use the object directly or wrap with ``int(...)``, almost all are subclasses of ``int``:

```
$ grep ^class SeqFeature.py 
class SeqFeature:
class Reference:
class FeatureLocation:
class CompoundLocation:
class AbstractPosition:
class ExactPosition(int, AbstractPosition):
class UncertainPosition(ExactPosition):
class UnknownPosition(AbstractPosition):
class WithinPosition(int, AbstractPosition):
class BetweenPosition(int, AbstractPosition):
class BeforePosition(int, AbstractPosition):
class AfterPosition(int, AbstractPosition):
class OneOfPosition(int, AbstractPosition):
class PositionGap:
```

Those positions which do not directly subclass ``int``,

* AbstractPosition - base class
* UncertainPosition - subclass of ExactPosition, and thus also of int
* UnknownPosition - cannot be cast into an int, could use NA as a float, but returning ``None`` was the historic position behaviour. Used for SwissProt / UniProt text files.
* PositionGap - unused, we should deprecate and remove that. It was added 21 years ago in 106be62b9f44c0640726492b645e2e10bb93e987 and last used in Biopython 1.55 in the GenBank parser. That usage was removed in 3e85df787b4968e284929ee9ca01bf3a9e87b41f (September 2021) when the old location parser location was removed in favour of the regular expression based code.

So, deprecate/remove ``PositionGap``, and we're left with a single exception - the ``UnknownPosition`` which cannot be treated as an integer.

And you're right the ``__init__`` method shouldn't be using ``.position`` anymore.

And we should formally deprecate the ``.position`` and ``.extension`` attributes now.

**Comment by mdehoon** [comment]
For `OneOfPosition`, `WithinPosition` and `BetweenPosition`, calling `int` on the object or using the `position` attribute will return a different number.

I think we should implement the rich comparison methods on `AbstactPosition`, overriding them in the derived classes when needed. Then we don't need to make use of `.position` in the `__init__` method of `FeatureLocation`.

**Comment by peterjc** [comment]
I've been looking at this, and specifically on the ```.position`` and ``.extension`` attributes, recall I was considering replacing ``.position`` ("left most") and ``.extension`` (right-more minus left-most, usually zero) with something like ``.left`` and ``.right``, or ``.lower_bound`` and ``.upper_bound``.  These values are actually used in GenomeDiagram and other visualisation use cases.

As to the class setup, we can't have ``AbstactPosition`` inherit from ``int`` yet have ``UnknownPosition`` not inherit, can we? Perhaps a new (private) ``KnownPosition`` class would work? i.e.

```python
class ExactPosition(AbstactPosition):
    # ...
```

becomes:

```python
class _KnownPosition(int, AbstactPosition):
    # define default comparison and any left/right methods here
    
    
class ExactPosition(_KnownPosition):
    # ...
```

**Comment by mdehoon** [comment]
> As to the class setup, we can't have `AbstactPosition` inherit from int yet have `UnknownPosition` not inherit, can we? 

That is correct.

> Perhaps a new (private) `KnownPosition` class would work?

Not sure if I understand. How would introducing a `KnownPosition` class help?

**Comment by mdehoon** [comment]
> If we need a shared class to define integer-like behaviour methods etc, it may have to be outside the `UnknownPosition` class parentage.

You could define them in the `AbstractPosition` class, and override them in the `UnknownPosition` class.

**Comment by peterjc** [comment]
Yes... that should work even if the default method implementations might assume subclassing of ``int``.

**Comment by peterjc** [comment]
PR nearly ready, chasing down a few unwanted deprecation warnings from code still using the old properties...

**Comment by peterjc** [comment]
See PR #3964 for cleanup, with a third PR pending for the ``.position`` and ``.extension`` deprecation.
