### ISSUE TITLE
Bio.Seq.translate output different result from ape::trans (in R language)

### ISSUE THREAD

**Issue by hubutui** [biopython/biopython#3969]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```text
3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
CPython
Linux-5.18.7-arch1-1-x86_64-with-glibc2.35
1.79
```

### Expected behaviour

`Bio.Seq.translate` output the same result from `ape::trans` (in R language)

### Actual behaviour

for a simple sequence, `G--`, `ape::trans` ([doc link](https://www.rdocumentation.org/packages/ape/versions/5.6-2/topics/trans)) outputs `X` while `Bio.Seq.translate` ([doc link](https://biopython.org/docs/latest/api/Bio.Seq.html?highlight=translate#Bio.Seq.translate)) raise invalid codon error.

### Steps to reproduce

(*Please fill this in *)

### Questions
How could I make biopython output the same result as R language's `ape::trans`. 

I'm trying to translate DNA to protein with over 1 million sequences, the original R code read all the sequences all at once which cause OOM. I'm not familiar with R, so I would like to write Python code with biopython to do this. I have check #3854, and make sure that I could read the fasta file, get a iterator, and write the result in an appending way to the output file.
Any suggestion?

**Comment by peterjc** [comment]
If you really want to do this (and you may have good reason to do so but I am struggling to thinking of a use case), you must supply your own lookup table as the first argument to the translate function/method which includes mapping ``"G--"`` to ``"X"`` (etc).

I am surprised ``ape::trans`` would translate ``G--`` as ``X``. That is a partial codon, a single G and two gap characters. It would mean translating ``G---AA`` as ``XX`` (two unknown amino acids) when I would personally want to consider either ``---GAA`` or ``GAA---`` giving ``-E`` or ``E-`` (one amino acid and one gap).

i.e. If you are translating aligned CDS sequences, you should translate a codon-aware alignment. Or translate into protein and align the protein.

```pycon
>>> from Bio.Seq import translate
>>> translate("GAA---", gap="-")
'E-'
>>> translate("---GAA", gap="-")
'-E'
>>> translate("G---AA", gap="-")
Traceback (most recent call last):
...
Bio.Data.CodonTable.TranslationError: Codon 'G--' is invalid
```

**Comment by hubutui** [comment]
Yes, I have run mafft, and then translate from DNA to protein.

According to the [ape doc](https://www.rdocumentation.org/packages/ape/versions/5.6-2/topics/trans):
> Alignment gaps are simply ignored (i.e., AG- returns X with no special warning or message).

**Comment by peterjc** [comment]
I do not understand the rational for the ape translation behaviour of partial codons.

I suggest you translate into protein, align the protein, then "back-translate" to get a codon aware nucleotide alignment.

See e.g. https://github.com/peterjc/pico_galaxy/tree/master/tools/align_back_trans although that was written back on Biopython 1.67, and at the time of writing would need updating not to use ``Bio.Alphabet`` otherwise it would break on Biopython 1.78 onwards.

**Comment by MarkusPiotrowski** [comment]
For a dirty hack you may also consider just to replace all your gaps with 'N's and do the translation then. This could make sense when your gaps are the result of sequencing errors and these sequences have been mapped/aligned to correct sequences.

**Comment by hubutui** [comment]
@MarkusPiotrowski Thanks, that's what I'm looking for.
