### ISSUE TITLE
Add option to silence/capture stdout/stderr from Bio.PDB.PSEA

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#3999]
Spun from #3980.

Running `p-sea` through `Bio.PDB.PSEA` will always print output to standard out. We should refactor the code to use `subprocess.run` and add a keyword to the top-level `run_psea` function to control whether to print or capture the tool's output.

A mock implementation that adds some better error handling would be:

```import subprocess

def run_psea(pname, verbose=True):
    cmd = [...]
    try:
        p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    except subprocess.CalledProcessError as err:
        print(f"Command {cmd} failed")
        raise

    if verbose:
        print(p.stdout)
    ...
```

**Comment by peterjc** [comment]
That sounds sensible, assuming we want to run p-sea on the user's behalf in the first place.

Cross reference #3344 deprecating our Bio.Application framework for wrapping command line tools.
