### ISSUE TITLE
Deprecate Bio.Wise?

### ISSUE THREAD

**Issue by mdehoon** [biopython/biopython#4010]
`Bio.Wise` is mainly a command-line interface.
It is not described in the BIopython tutorial, and it seems to be an orphan module.

As command line application wrappers are scheduled to be deprecated, should we also deprecate `Bio.Wise`?

```
CPython
macOS-10.15.7-x86_64-i386-64bit
1.80.dev0
```

**Comment by peterjc** [comment]
That seems reasonable to me, +1

**Comment by mdehoon** [comment]
Deprecated in #4013
