### ISSUE TITLE
Biopython 1.79 Fails to parse new Uniprot file in SwissProt text format

### ISSUE THREAD

**Issue by avivrosenberg** [biopython/biopython#4021]
There are some new Uniprot records in SwissProt format which biopython fails to parse.

Here's an example of a file which biopython fails to parse (UniProt accession `P00720`):
[P00720.txt](https://github.com/biopython/biopython/files/9257269/P00720.txt)
Note that this file was updated recently on uniprot (03-AUG-2022). 

Here's a previous version of `P00720` (from 26-FEB-2020), which biopython does parse successfully:
[P00720.txt](https://github.com/biopython/biopython/files/9257277/P00720.txt)

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)

3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:33:09)
[Clang 11.1.0 ]
CPython
macOS-10.16-x86_64-i386-64bit
1.79
```

### Expected behaviour

Biopython's `Bio.SwissProt.read()` should correctly parse the file, and return a `Bio.SwissProt.Record`.

### Actual behaviour

Exception is raised when parsing the feature (`FT`) lines:

```python
File ~/mambaforge/envs/proteins/lib/python3.8/site-packages/Bio/SwissProt/__init__.py:257, in read(source)
    255 handle = _open(source)
    256 try:
--> 257     record = _read(handle)
    258     if not record:
    259         raise ValueError("No SwissProt record found")

File ~/mambaforge/envs/proteins/lib/python3.8/site-packages/Bio/SwissProt/__init__.py:371, in _read(handle)
    369     _read_kw(record, value)
    370 elif key == "FT":
--> 371     _read_ft(record, line)
    372 elif key == "SQ":
    373     cols = value.split()

File ~/mambaforge/envs/proteins/lib/python3.8/site-packages/Bio/SwissProt/__init__.py:830, in _read_ft(record, line)
    828 # this line is a continuation of the description of the previous feature
    829 keys = list(feature.qualifiers.keys())
--> 830 key = keys[-1]
    831 description = value.rstrip('"')
    832 old_description = feature.qualifiers[key]

IndexError: list index out of range
```

### Steps to reproduce

Just run the following snippet (adapted from the official biopython documentation).
 
```python
from Bio import ExPASy, SwissProt

accession = "P00720"
handle = ExPASy.get_sprot_raw(accession)
record = SwissProt.read(handle)
```

Or, parse the files attached above, the first (newer one) should fail and the second should succeed.

Another example failing in the same way is with accession `Q72J47`.

**Comment by fredricj** [comment]
The relevant news item: https://www.uniprot.org/release-notes/2022-08-03-release

This affects us as well so I looked at fixing this. The naive fix is to add ligand, ligand_id, ligand_label and ligand_label as the keys in the same way as evidence and note, but maybe there is a better way which also improve the error message for the future.

**Comment by fredricj** [comment]
The current feature parser also misparse the feature when the unknown key is after a known key:
```
FT   TURN            159..161
FT                   /evidence="ECO:0000244|PDB:2O7A"
FT   HELIX           162..164
FT                   /evidence="ECO:0000244|PDB:4ARJ"
FT                   /ligand="ECO:000024"
```
produces:
```
type: TURN
location: [158:161]
qualifiers:
    Key: evidence, Value: ECO:0000244|PDB:2O7A

type: HELIX
location: [161:164]
qualifiers:
    Key: evidence, Value: ECO:0000244|PDB:4ARJ/ligand="ECO:000024
```

**Comment by peterjc** [comment]
With 8 new ligand associated keys, it looks like this block needs to be refactored to cope with arbitrary /key=value entries, not just the historic three kinds:

```python
    else:  # new-style FT line
        value = line[21:].rstrip()
        if value.startswith("/id="):
            qualifier_type = "id"
            value = value[4:]
            assert value.startswith('"')
            assert value.endswith('"')
            feature.id = value[1:-1]
            return
        elif value.startswith("/evidence="):
            value = value[10:]
            assert value.startswith('"')
            if value.endswith('"'):
                value = value[1:-1]
            else:  # continues on the next line
                value = value[1:]
            assert "evidence" not in feature.qualifiers
            feature.qualifiers["evidence"] = value
            return
        elif value.startswith("/note="):
            value = value[6:]
            assert value.startswith('"')
            if value.endswith('"'):
                value = value[1:-1]
            else:  # continues on the next line
                value = value[1:]
            assert "note" not in feature.qualifiers
            feature.qualifiers["note"] = value
            return
```

Something like this, possibly using a regex rather than looking for the equals sign?:

```python
    else:  # new-style FT line
        value = line[21:].rstrip()
        # Check for /key=value style entry, possibly quoted and multiline
        if value.startswith("/") and "=" in value:
            ...
            return
```

As an aside, it should avoid using ``assert`` statements but instead raise a ``ValueError`` - see #3600.

If you were thinking along similar lines, would you like to submit a pull request please?

**Comment by fredricj** [comment]
I was thinking something along those lines. I guess we could match on "^/[a-z_]+="
I was trying to figure out a better way that doesn't silently accept input it is not handling correctly. The current idea I had was to look for a keyword when we are outside quotes, but to support that we would need some kind of state machine which I'm not sure how we would add without rewriting the current line-based parser.

**Comment by joaomcteixeira** [comment]
Hi,

I faced this issue just yesterday. Thanks for having solved it. It is important all the new changes are deployed to PyPI and `conda`.

Great work, everyone.
Cheers

**Comment by davmlaw** [comment]
Confirmed that this is still broken with current UniProt file on latest PyPI release and fixed in GitHub master
