### ISSUE TITLE
SearchIO parse - RuntimeError: generator didn't stop after throw()

### ISSUE THREAD

**Issue by Tim-Kirkwood** [biopython/biopython#4040]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
CPython
Windows-10-10.0.19041-SP0
1.79
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

Parses blast-xml file to generator object.

 
### Actual behaviour

```
Traceback (most recent call last):

  File "<ipython-input-33-24319554c163>", line 3, in <module>
    for query in generator:#generator, test for debugging only

  File "C:\ANACONDA3\lib\site-packages\Bio\SearchIO\__init__.py", line 306, in parse
    yield from generator

  File "C:\ANACONDA3\lib\contextlib.py", line 161, in __exit__
    raise RuntimeError("generator didn't stop after throw()")

RuntimeError: generator didn't stop after throw()
```

### Steps to reproduce

**Please note:**  I recently re-installed biopython after it got removed during installation of another program.  I believe the re-installed biopython may be a more recent version (I can't remember what it was originally).  I was originally generating my xml using `Bio.Blast.Applications.NcbiblastpCommandline`, which then integrated with the rest of my pipeline fine.  I am now getting `SearchIO.parse()` runtime errors when I try and parse the blast-xml file generated using a blastp process started with subprocess (`def blastP_subprocess` under 'how to reproduce'), which is suggested in the docs as the `Applications `module is now [obsolete](https://biopython.org/docs/latest/api/Bio.Application.html).  

I don't know if my subprocess workflow is flawed or whether there is some updated behaviour for `SearchIO.parse()` in version 1.79 biopython.

Original xml generation function:

```
def blastP_subprocess(evalue_user, query_user, blastp_exe_path, results_out_path, db_user, thread_num):
    '''this runs the biopython blastp wrapper, key details:  
        -xml output format 
        -parse deflines - this means you keep fasta heads, which is essential for coordinating rbh 
        -link to wrapper description - https://biopython.org/docs/1.75/api/Bio.Blast.Applications.html#Bio.Blast.Applications.NcbiblastpCommandline.  
    NB - the DB outpath should have the full path up until where you want the files to be made, including the name of the files (path\to\dir\name).  
    Normally, name would have a suffix (e.g. .txt), but in this case do NOT include a file suffix. 
    You are referenceing a collection of db files (.pdb, .phr, .pin, .pot, .psq, .ptf, .pto) not a single file.'''
    blastp_cline = NcbiblastpCommandline(cmd=blastp_exe_path, 
                                         out=results_out_path, 
                                         query=query_user, 
                                         db=db_user, 
                                         evalue=evalue_user, 
                                         outfmt=5, 
                                         num_threads=thread_num, 
                                         parse_deflines=True)#parse deflines#, best_hit_overhang=0.1, best_hit_score_edge=0.1)#, num_threads=3)
    stdout,sterr=blastp_cline()   
```

generating xml with subprocess:
```
def run_blast_process(cmd:list):
    '''this runs the BLAST+ BLASTP exe using Python via the subprocess module.  
    It uses error handlng to ease diagnostics - the return codes from BLAST+ 
    do not always match those of windows so (for example) 
    successful database creation can throw an error.'''
    try:
        return subprocess.run(cmd, check=True, capture_output=True, env={'BLASTDB_LMDB_MAP_SIZE':'1000000'})
    except FileNotFoundError as e1:
        print ('Command:  ', cmd)
        print ('FileNotFoundError:\n', e1)
        return e1
    except subprocess.CalledProcessError as e2:
        print ('Command:  ', cmd)
        print ('CalledProcessError:')
        print ('\nError object:\n',e2)
        print ('\nStd_err:\n',e2.stderr)
        print ('\nStd_out:\n',e2.stdout)
        return e2

def blastP_subprocess(evalue_user, query_user, blastp_exe_path, results_out_path, db_user, thread_num):
    '''this runs the biopython blastp wrapper, key details:  
        -xml output format 
        -parse deflines - this means you keep fasta heads, which is essential for coordinating rbh 
        -link to wrapper description - https://biopython.org/docs/1.75/api/Bio.Blast.Applications.html#Bio.Blast.Applications.NcbiblastpCommandline.  
    NB - the DB outpath should have the full path up until where you want the files to be made, including the name of the files (path\to\dir\name).  
    Normally, name would have a suffix (e.g. .txt), but in this case do NOT include a file suffix. 
    You are referenceing a collection of db files (.pdb, .phr, .pin, .pot, .psq, .ptf, .pto) not a single file.'''
    return run_blast_process([blastp_exe_path, 
                                         '-out', fr'{results_out_path}', 
                                         '-query', fr'{query_user}', 
                                         '-db', fr'{db_user}', 
                                         '-evalue', fr'{evalue_user}', 
                                         '-outfmt', '5', 
                                         '-num_threads', fr'{thread_num}', 
                                         '-parse_deflines'])
```

Make an xml file with this:
```
blastp_exe_path=fr'{work_dir}\Backend\Executables\NCBI\blast-2.10.1+\bin\blastp.exe'
user_db=fr'{work_dir}\Backend\Precomputed_files\database\myDB'
error_file=r'path\to\errors.txt'
blastP_subprocess(evalue_user = 0.0005, query_user = 'path\to\my\query.txt', blastp_exe_path, results_out_path ='path\to\results.xml', db_user = user_db, thread_num = os.cpu_count())
```

Then try and parse it - please note I had a quick look at the xml file in notepad and it isn't obviously flawed:
```
generator=SearchIO.parse(fw_xml_results_path,"blast-xml")
queries=[]
for query in generator:#generator, test for debugging only
    print (len(query.hits))
    continue
```
Please note Python's `contextlib `is throwing the error after 'generator' is assigned, so it looks like an issue with the generator object format coming from SearchIO.parse(), not an error when SearchIO.parse() is called.

**Comment by Tim-Kirkwood** [comment]
To make this a bit more standardisable, I did a BLASTP for a random protein using the ncbi web portal:

MSERLLLLVESNTTGTGRLFARRAADLGVVPVLLCADPGRYPYAAEDRVRTVTVDTSDEGALWAAVEALAGEDRVAGVLTSSEYYVPTAAALAARLGLPGPSAEAVRACRDKAEQRRVLAAAGVGGPGFAVVSQESGVSQESGVTGVTGVTGAVEAARAIGLPVVVKPVQGSGSLGVRLCADLDEVAAHAGTLLAATVNERGVAVPARILVEEYLTGPEFSVEVFGTEAVVTVAKHVGPLPVFVEVGHDVPAPLPGDRDRALREAAVAAVEALGLGWGAAHVELRLTGTDSGAVRVIEVNPRLAGGMIPELVRGACGIDLVLAQVQAALGGVPELGRGGYARASIRFLTSGRDGVLAPAAVVADAVERARAVPDTVEAVLYRAAGERVGPAEDFRGRFGHVIAVADHGGLAAEAADRAVALLGGAVSYPEPQGEAASSTDQHDGGDRMSTTGDPAANEARGVDTGRLKAALDAEAHRIVYDQYLPGAAGDGLGEELRCISEVDRAHLIMLTECGIVDAGRAAALLRAIEELRGQDFAAVRAAPMPRGVYLAYEGRLIEQLGDGTGGILHTGRSRNDLNATTTRLKTRGPYLALLDAVERLAGVLLAKAAEYQDVVMPAYTHGQPAVPISYGHYLAGVAGAVLRAYEALLDAGRQLDVNPLGAGAIGGTSVPIDPRRTAGLLGFTSAAPNSVDAVASRDFVLDLLSASAVLGVTLARAGRDLSTWTSEEFGLLRVADTLVGSSSMMPQKRNPFLLEHIQGRSTASLGAFVSAASAMTTGGYTNAIAVGTEAVRHLWPGLSGATDAVTLLSLVVAGTEPERGRMAERAVDGFTSATYLAERLVLDGMPFRAAHHLVGETVLGALDSGRSLVDAAEFSAVGDGGLAPDRVAGACVHGGGPGSTAAGIQEIDAHLASLRAELTARRTRWSDAATLLSQAVLKAVTS

I then downloaded results in xml format to "my/file/path".

I then copied the docs and wrote:

```
from Bio import SearchIO
p = "my\file\path"
qresults = SearchIO.parse(p, 'blast-xml')
for qresult in qresults:
    print("Search %s has %i hits" % (qresult.id, len(qresult)))  
```
 Again, I got:

```
Traceback (most recent call last):

  File "<ipython-input-44-f3824e682622>", line 4, in <module>
    for qresult in qresults:

  File "C:\ANACONDA3\lib\site-packages\Bio\SearchIO\__init__.py", line 306, in parse
    yield from generator

  File "C:\ANACONDA3\lib\contextlib.py", line 161, in __exit__
    raise RuntimeError("generator didn't stop after throw()")

RuntimeError: generator didn't stop after throw()
```

**Comment by Tim-Kirkwood** [comment]
changed seqio to searchio in title

**Comment by peterjc** [comment]
Can you share the problematic XML file?

**Comment by bow** [comment]
@Tim-Kirkwood Echoing @peterjc comment above: having the problematic XML file would help a lot here. Additionally, what does running `python --version` in the shell output in your system?

**Comment by Tim-Kirkwood** [comment]
Hello, 

I couldn't find the file so I re-ran the blastp using the sequence above and re-downloaded the xml file.  After this everything worked fine and I could not replicate the error.  

I suspect that the original xml file was not properly downloaded when I ran the script, perhaps due to a slow internet connection.  This could then cause unexpected errors from trying to read a partial file. 

Sorry for wasting your time!
Tim

**Comment by peterjc** [comment]
It could be a corrupted file, but we'd still like to see an example if it happens again as the failure is odd, and could be handled better. Thanks.

**Comment by Tim-Kirkwood** [comment]
Will keep my eyes peeled!  Cheers for spending time on this.
