### ISSUE TITLE
Windows fatal error C1001: Internal compiler error.

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4052]
Recent Windows CI builds are failing, circumstantial evidence suggests a build environment change in the last few days:

20 August 2022 - https://github.com/biopython/biopython/commit/1ebd1bb919a45908da4db46468a5180203377471 worked post PR https://github.com/biopython/biopython/pull/4045 merger

23 August 2022 - https://github.com/biopython/biopython/commit/07026ecbd0282de326c3e6a73109fc608f961b6e failed post PR https://github.com/biopython/biopython/pull/4046 merger

```
...
Generating code
D:\a\biopython\biopython\Bio\Cluster\cluster.c(1495) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com/ 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  link!RaiseException()+0x62
  link!RaiseException()+0x62
  link!InvokeCompilerPass()+0xdf7f1
  link!CloseTypeServerPDB()+0xe97e1
  link!CloseTypeServerPDB()+0x3b101

error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 3765260340
```

Note the ``SetuptoolsDeprecationWarning`` issue recently logged as #4050 affected both the above commits, so that appears to be an unrelated earlier change to our build environment.

**Comment by mdehoon** [comment]
See #4054 . The compilers barfs on lines with floating-point comparisons. However, this is legal C code.

The  compiler may have been fixed:
https://devblogs.microsoft.com/cppblog/c-compiler-front-end-fixes-in-vs2015/

Does our compiler have all current patches and updates?

**Comment by peterjc** [comment]
Not sure, there is probably a GitHub issue tracker for this as part of GitHub Actions...

I found https://github.com/microsoftdocs/cpp-docs/blob/main/docs/error-messages/compiler-errors-1/fatal-error-c1001.md

**Comment by mdehoon** [comment]
See https://github.com/biopython/biopython/actions/runs/2917927027 ; the compilation finishes without problems after switching the Windows compiler for `windows-latest` (i.e. 2022) to `windows-2019`.

**Comment by peterjc** [comment]
Great, that solves our immediate problem. Does this deserve reporting to https://developercommunity.visualstudio.com/  as per the message from the compiler error?

**Comment by peterjc** [comment]
Closed by https://github.com/biopython/biopython/commit/5f0d64bb2a4abc3d360248c17fa2bcac2bd2a3ad
