### ISSUE TITLE
PEP8 cleanup (without functional code changes)

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#406]
Tracking issue for applying small PEP8 changes like white space which do NOT alter the code behaviour, and discussion of dividing labour to avoid stepping on each other's toes. i.e. You can comment here if you are planning to work on a batch of modules.

Ideally this will allow us to routinely use a git pre-commit hook like https://github.com/cbrueffer/pep8-git-hook as outlined on the mailing list thread, http://mailman.open-bio.org/pipermail/biopython-dev/2014-October/020741.html

CC @carlosp420 and @twrightsman

**Comment by peterjc** [comment]
Having been using the commit hook on (some of) my own machines, there are still plenty of (harmless) white space issues in the code base which do not follow PEP8, e.g. spaces around mathematical operators. I've been fixing this as an when I happen to touch a file for another reason.

**Comment by carlosp420** [comment]
I included these exceptions in my pre-commit hook:

E261 	at least two spaces before inline comment
E225 	missing whitespace around operator
E226  	missing whitespace around arithmetic operator
E227 	missing whitespace around bitwise or shift operator
E228 	missing whitespace around modulo operator

as suggested here
http://mailman.open-bio.org/pipermail/biopython-dev/2014-October/020748.html

Maybe those are the spaces that you keep finding?


Dr. Carlos Peña
Laboratory of Genetics
Department of Biology
University of Turku
20014 Turku
FINLAND

* Associate Editor: Revista peruana de Biología
http://is.gd/TwbW

* The Nymphalidae Systematics Group
http://nymphalidae.utu.fi/db.php

**Comment by peterjc** [comment]
Yes, and in general I found following these makes the code a little bit clearer - although for some of the more complex mathematical formulas it can be useful to omit the spaces around multiplication, to emphasise visually that happens before any addition/subtraction.

**Comment by peterjc** [comment]
I'm going to mark this as closed, and focus next on adopting the pre-commit git hook, new issue #493
