### ISSUE TITLE
Sparky Blast type implementation for Blast

### ISSUE THREAD

**Issue by nyck33** [biopython/biopython#4071]
Is there any Spark-related implementation of Blast like https://github.com/Sherynan/SparkyBlast

If not, where can I find the source code for Blast in Biopython?

Thanks in advance for your time.

**Comment by peterjc** [comment]
Biopython does not implement the BLAST algorithm, only parsers for the output from the NCBI BLAST+ tools and web-based API, and code for calling that API.
