### ISSUE TITLE
SeqIO.write() is not case sensitive

### ISSUE THREAD

**Issue by Ieremie** [biopython/biopython#4079]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ]
CPython
macOS-10.16-x86_64-i386-64bit
1.79
```

### Expected behaviour
```
with open("3unb_T", "w") as handle:
            SeqIO.write(record, handle, "fasta")

with open("3unb_t", "w") as handle:
            SeqIO.write(record, handle, "fasta")
```
Should generate two different fasta files.

### Actual behaviour
A single fasta file is generated, which overwrites the old one. 

### Steps to reproduce

```
all_pdb_fasta = SeqIO.to_dict(SeqIO.parse(pdb_fasta_path, "fasta"), lambda rec: rec.id)
record1 = all_pdb_fasta["3unb_T"]
record2 = all_pdb_fasta["3unb_t"]

with open("3unb_T", "w") as handle:
            SeqIO.write(record1, handle, "fasta")

with open("3unb_t", "w") as handle:
            SeqIO.write(record2, handle, "fasta")


```

**Comment by peterjc** [comment]
This isn't a Biopython issue, or a Python issue. This is down to the default filesystem on macOS and Windows which is case in-sensitive (but does remember the case).

Try it yourself at the terminal:

```
$ touch eg-NAME.txt
$ touch eg-name.txt
$ ls -1 eg-*.txt
eg-NAME.txt
```

You could use Linux, or make a new partition on macOS and choose the format options... but I'd recommend avoiding the issue as it will break on other people's computers.
