### ISSUE TITLE
Entrez biopathways database has been retired, Entrez test fails

### ISSUE THREAD

**Issue by jlumpe** [biopython/biopython#4086]
NCBI [retired](https://ncbiinsights.ncbi.nlm.nih.gov/2021/08/10/retire-biosystems-database/) the `biosystems` database earlier this year. This is causing an error in one of the [tests](https://github.com/biopython/biopython/blob/518c4be6ae16f1e00bfd55781171da91282b340a/Tests/test_Entrez_online.py#L126-L132) in `test_Entrez_online.py` when I run it locally.

**Comment by peterjc** [comment]
Nice diagnosis. That sounds easy to fix - remove the test here:

https://github.com/biopython/biopython/blob/biopython-179/Tests/test_Entrez_online.py#L126

Do you want to make a pull request?

**Comment by jlumpe** [comment]
Yeah I can do that
