### ISSUE TITLE
Access to Traceback Matrix of Pairwise function?

### ISSUE THREAD

**Issue by CCranney** [biopython/biopython#4121]
This is not for a bug - I'm trying to determine if biopython has a specific feature and can't find it on the docs/in the code. This probably means the feature does not exist, but thought I would ask.

I am trying to access the traceback matrix that is used in the Bio.Align.PairwiseAligner.align() function (or the deprecated pairwise2.align.globalms() function) for a personal project. Is there a way to include that matrix as output from the function, or to produce it in another way? I can and have written the basic code myself for testing purposes, but your function is significantly more efficient, and I'm not finding a way to access that data.

**Comment by mdehoon** [comment]
The traceback matrix is encoded in C and is currently not exposed at the Python level. It is possible to make the traceback matrix available from Python, but it would require some additional C coding. I don't think I will be able to find the time for it myself, but I won't object if you want to give it a try. It may not be so easy - the traceback matrix also remembers the last path that was taken through it (this is how we can iterate over different alignments), and you would have to figure out how to represent this in Python. Maybe a numpy array with `bytes` would work. And for alignments with different gap opening and gap extend scores (Gotoh algorithm), there will be three traceback matrices.

**Comment by CCranney** [comment]
Good to know, thank you! I played around with the PairwiseAligner() class and discovered its "aligned" property could meet my needs.
