### ISSUE TITLE
'indices' function is present in the github doc, but missing in the local doc

### ISSUE THREAD

**Issue by xiaojingsui** [biopython/biopython#4131]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23) 
[Clang 13.0.0 (clang-1300.0.29.30)]
import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-12.3-arm64-arm-64bit
import Bio; print(Bio.__version__)
1.79
```

### Expected behaviour
I found the function of 'indices' from the doc of github version. 
https://github.com/biopython/biopython/blob/master/Bio/Align/__init__.py
![image](https://user-images.githubusercontent.com/115586445/195762569-0c571699-3425-432b-bf90-4189905f3da4.png)

### Actual behaviour
However, the function of 'indices' is not in the local doc. Is there a way to put this function back?

**Comment by mdehoon** [comment]
@xiaojingsui  What do you mean by "local doc"?

**Comment by peterjc** [comment]
This isn't in the current release Biopython 1.79, https://github.com/biopython/biopython/blob/biopython-179/Bio/Align/__init__.py

You'll need to install from source (i.e. from GitHub), or wait for Biopython 1.80

**Comment by xiaojingsui** [comment]
> @xiaojingsui What do you mean by "local doc"?
Sorry for the confusion. The 'local doc' refers to Biopython 1.79 that I installed on my computer. @peterjc has addressed my question. Thanks.
