### ISSUE TITLE
Diff between two SeqRecords

### ISSUE THREAD

**Issue by manulera** [biopython/biopython#4132]
Hello,

I am working on a changelog for gene structures in PomBase. The idea is to report the differences in gene features between two versions of the genome (between two `SeqRecord`s): `SeqFeature.location` or `SeqFeature.qualifiers`. Is there something in place already in the library for doing this?  Otherwise, would you welcome a contribution for something like this (if so, some recommendations for the output format)?

Thanks!

**Comment by peterjc** [comment]
We don't have anything built in. The best way to present this probably depends on your audience, but also the kind of changes you are expecting. e.g. updates to the annotation text, without touching locations is one thing. Adding/removing features is another. The hardest would be things like gene changes, also gene fission and fusion.

Are you able to easily match up the features (e.g. suppose you're looking at a bacterial assembly and in one revision the original is shifted, all that changes is the locations and the order of the features)? Or another "simple" change, the main contig is reverse complemented, so all the feature locations and strands values change.

**Comment by manulera** [comment]
Hi @peterjc thanks for the comprehensive answer. Yes, that makes total sense. I was thinking of our genome change log for PomBase, where the underlying sequence does not change, but the features do. Indeed as soon as the DNA sequence changes, all features will change so it makes little sense.
