### ISSUE TITLE
Masking is lost when reading in a genbank file

### ISSUE THREAD

**Issue by HASaunders** [biopython/biopython#4148]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

```shell
3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)]
CPython
macOS-10.16-x86_64-i386-64bit
1.79
```

### Expected behaviour

The following code works as expected. The masking (lower case letters) in the sequence are preserved. 
```python
from Bio import SeqIO
from io import StringIO
s = StringIO(">sequence\nAAATTggTgggaaTAAAA")
rec = SeqIO.read(s, format='fasta')
str(rec.seq)
```

```shell
'AAATTggTgggaaTAAAA'
```

I would expect this to to also be true when reading a sequence from a genbank file as follows:
```
record = SeqIO.read(open(file_name,"r"), "genbank")
str(record.seq)
```

### Actual behaviour

In the 2nd example, when reading in a sequence from the genbank file, the masking is lost and the sequence is returned in all capital letters. I would however like to preserve the masking. 

Taking a look at the code I can see that in [line 818 here](https://github.com/biopython/biopython/blob/master/Bio/GenBank/__init__.py), you do `.upper()` on the sequence. Is this necessary? It would great if this could be removed so that the lower case letters are preserved when importing a genbank file.

### Steps to reproduce

```
record = SeqIO.read(open(file_name,"r"), "genbank")
str(record.seq)
```

where `file_name` is the path to any genbank file with a sequence containing both upper and lower case letters.

**Comment by peterjc** [comment]
NCBI don't do mixed case on their sequences, and store it lower case. Most formats store it upper case, so this is a long standing Biopython convention. Changing that would break lots of existing scripts.

**Comment by peterjc** [comment]
A workaround is call the scanner/consumer directly, but subclass the consumer to modify the ``.sequence(...)`` method not to use uppercase.
