### ISSUE TITLE
'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 3765260340

### ISSUE THREAD

**Issue by 000camerashy000** [biopython/biopython#4151]
**Python version 3.11, trying to install BioPython 179/178**

I am constantly getting this error,
Before when my computer didn't had Build Tools the error was to install MS VS C++ 14 or later,
After installing VS and Build Tools I have installed every optional package available while installing VS C++ than also getting the error again and again
![image](https://user-images.githubusercontent.com/115683900/199827417-23bcd480-4893-4a7c-8aa6-6b5afb845868.png)

**'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 3765260340** 

![image](https://user-images.githubusercontent.com/115683900/199828740-d72c2bd6-98b2-4aed-b269-424f9b1dd17e.png)

The first error i am getting in logs is that **FAILED Building wheels for biopython**  in the logs and subsequently
**Running setup.py install for biopython did not run successfully.**

![image](https://user-images.githubusercontent.com/115683900/199828893-07f6f4b0-c3ad-433c-bd89-f82081ecb2a4.png)

**Also Facing Kind of similar issue while installing PyBio**

**Comment by peterjc** [comment]
Right now I would suggest you downgrade to Python 3.10 if your priority is easy installation of Biopython and other projects. Python 3.11 is still very new.

https://peps.python.org/pep-0664/

I'm not sure if anyone has tried Biopython on Windows with Python 3.11 yet.

We did Python 3.10 wheels for Biopython 3.10 (see #3824), it might be easy to do that again for Python 3.11

**Comment by peterjc** [comment]
Let's see if https://github.com/biopython/biopython-wheels/commit/83b76f279ff53c713dff6aa0d731fb4ae19e2a35 results in some Python 3.11 wheels...

**Comment by 000camerashy000** [comment]
> Right now I would suggest you downgrade to Python 3.10 if your priority is easy installation of Biopython and other projects. Python 3.11 is still very new.
> 
> https://peps.python.org/pep-0664/
> 
> I'm not sure if anyone has tried Biopython on Windows with Python 3.11 yet.
> 
> We did Python 3.10 wheels for Biopython 3.10 (see #3824), it might be easy to do that again for Python 3.11

I'll be switching to 3.10 as i'm having same issues with several other packages also;
Thankyou soo much! @peterjc

**Comment by peterjc** [comment]
It took a bit more effort, but as of https://github.com/biopython/biopython-wheels/commit/580d4e29c400723e6ba370b466e04f620ab2a100 we have wheels for Python 3.11 too. They are now on PyPI:

```
$ twine upload --skip-existing biopython-1.79-cp311-*.whl
Uploading distributions to https://upload.pypi.org/legacy/
Uploading biopython-1.79-cp311-cp311-macosx_10_9_x86_64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB • 00:07 • 337.4 kB/s
Uploading biopython-1.79-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB • 00:02 • 932.5 kB/s
Uploading biopython-1.79-cp311-cp311-win32.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB • 00:03 • 702.7 kB/s
Uploading biopython-1.79-cp311-cp311-win_amd64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB • 00:02 • 893.2 kB/s

View at:
https://pypi.org/project/biopython/1.79/
```

Checksums:

```
$ md5sum biopython-1.79-cp311-*.whl
54dae761a95f23fdd7b5489afcd4790b biopython-1.79-cp311-cp311-macosx_10_9_x86_64.whl
6d24e43634bbd94542ca3823312990e3 biopython-1.79-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
0eb01308025be498cb2bdf850ac12a8d biopython-1.79-cp311-cp311-win32.whl
c5505ed34493b9c13f89fab2b507d685 biopython-1.79-cp311-cp311-win_amd64.whl
```
