### ISSUE TITLE
primer_design() not able to run 

### ISSUE THREAD

**Issue by nick-chavez23** [biopython/biopython#4174]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
CPython
Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
1.80

### Expected behaviour

function primer_design() outputs an optimized set of primers for a sequence

### Actual behaviour

[/usr/local/lib/python3.7/dist-packages/Bio/SeqRecord.py](https://localhost:8080/#) in reverse_complement(self, id, name, description, features, annotations, letter_annotations, dbxrefs)
   1234             # Default to DNA)
   1235             seq = self.seq.reverse_complement(
-> 1236                 inplace=False
   1237             )  # TODO: remove inplace=False
   1238         if isinstance(self.seq, MutableSeq):

TypeError: reverse_complement() got an unexpected keyword argument 'inplace'

**Comment by peterjc** [comment]
Where is this ``primer_design`` function from? It isn't part of Biopython is it?
