### ISSUE TITLE
Biopython 1.80: No conda packages for python 3.7 at conda-forge 

### ISSUE THREAD

**Issue by BjornFJohansson** [biopython/biopython#4185]
Hi all,
There seems to be no builds for any platform: https://anaconda.org/conda-forge/biopython
AFAIK Biopython 1.80 still officially supports Python 3.7 even though it might be [dropped](https://github.com/biopython/biopython/blob/master/NEWS.rst#in-progress-not-yet-released-biopython-181) in 1.81 . 

There are conda packages for 1.79.

**Comment by peterjc** [comment]
The issue isn’t just what Biopython supports but also what conda-forge
supports, see
https://github.com/conda-forge/biopython-feedstock and
https://conda-forge.org/docs/user/announcements.html where it says Python
3.7 support was dropped in August 2022

**Comment by BjornFJohansson** [comment]
Ok, thanks for the heads up.
