### ISSUE TITLE
pairwise2 deprecation: how to align lists of sequences with the new PairwiseAligner?

### ISSUE THREAD

**Issue by trenslow** [biopython/biopython#4186]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
CPython
macOS-12.6.1-x86_64-i386-64bit
1.80

### Expected behaviour

As the new PairwiseAligner is supposed to cover the functionality of pairwise2, I would expect that it can also align lists of sequences. It would also be nice to customize the gap character like in pairwise2.

### Actual behaviour

When passing two lists to the PairwiseAligner, I get

```python
ValueError: alphabet is None; cannot interpret sequence
```

### Steps to reproduce

```python
from Bio import Align
list1 = ['i', 'love', 'bananas', 'and', 'cheese']
list2 = ['bandanas', 'blind', 'bees']
aligner = Align.PairwiseAligner()
alignments = aligner.align(list1, list2)
```

Would appreciate any direction on this matter. Thanks a lot :)

**Comment by mdehoon** [comment]
See section 6.6.11 in the documentation.

You need to tell the aligner the alphabet, i.e. which items are valid, as in this example:
```python
>>> from Bio import Align
>>> list1 = ['i', 'love', 'bananas', 'and', 'cheese']
>>> list2 = ['bandanas', 'blind', 'bees']
>>> aligner = Align.PairwiseAligner()
>>> 
>>> alphabet = sorted(set(list1+list2))
>>> alphabet
['and', 'bananas', 'bandanas', 'bees', 'blind', 'cheese', 'i', 'love']
>>> aligner.alphabet = alphabet
>>> alignments = aligner.align(list1, list2)
>>> print(alignments[0])
i love bananas and cheese -------- ----- ----
- ---- ------- --- ------ -------- ----- ----
- ---- ------- --- ------ bandanas blind bees

>>> list2 = ['bananas', 'blind', 'bees']
>>> alignments = aligner.align(list1, list2)
>>> print(alignments[0])
i love bananas and cheese ----- ----
- ---- ||||||| --- ------ ----- ----
- ---- bananas --- ------ blind bees

```
You can replace the gap character in the string before printing it:
```python
>>> print(str(alignments[0]).replace("-", "♣"))
i love bananas and cheese ♣♣♣♣♣ ♣♣♣♣
♣ ♣♣♣♣ ||||||| ♣♣♣ ♣♣♣♣♣♣ ♣♣♣♣♣ ♣♣♣♣
♣ ♣♣♣♣ bananas ♣♣♣ ♣♣♣♣♣♣ blind bees

```

**Comment by trenslow** [comment]
@mdehoon thanks so much for your quick response! We're starting to head in the right direction :)

Is there any reason you sorted the combination of the lists? Or was it just for readability? 

If I tune the penalty parameters, it's possible to get similar words to align, such as banana and bandana. In the old pairwise aligner, I could get two equal-length lists including the gaps from the output of the align function. E.g.:

```python
In [49]: old_alignments = pairwise2.align.globalms(list1, list2, ms, mms, ogs, egs, gap_char=['♣'])
In [50]: old_alignments[0][:2]
Out[50]: 
(['i', 'love', 'bananas', 'and', 'cheese'],
 ['♣', '♣', 'bandanas', 'blind', 'bees'])
```

How can I do that with the new pairwise aligner? I tried poking around the new alignments object and I didn't see anything properties or methods that could help me out.

Thanks for the help so far!

**Comment by mdehoon** [comment]
> Is there any reason you sorted the combination of the lists? Or was it just for readability?

Just for readability.

> How can I do that with the new pairwise aligner? I tried poking around the new alignments object and I didn't see anything properties or methods that could help me out.

What does `pairwise2.align.globalms(list1, list2, ms, mms, ogs, egs, gap_char=['♣'])`  do?
Then do the same with the aligner object, as described in the documentation.

**Comment by trenslow** [comment]
@mdehoon with the pairwise2 function I was just trying to illustrate that I can tune the penalty parameters (match score, open gap score, etc.) to align alike words. The pairwise2 function outputs a nice alignment representation which is very useful for my work.

If I do the same thing with the new aligner function like you proposed, I get an Alignment object rather than the tuple representation.
```python
In [100]: alignments = aligner.align(list1, list2)
In [101]: alignments[0][:2]
Out[101]: <Alignment object (2 rows x 5 columns) at 0x11a8c5210>
```

After looking through the documentation, I don't see how I can get the old pairwise2 tuple representation with equal-length lists out of the Alignment object. the closest I find is 
```python
In [108]: alignments[0].sequences
Out[108]: [['i', 'love', 'bananas', 'and', 'cheese'], ['bandanas', 'blind', 'bees']]
```
but then I lose the information about the gaps that were opened.

**Comment by mdehoon** [comment]
> with the pairwise2 function I was just trying to illustrate that I can tune the penalty parameters (match score, open gap score, etc.) to align alike words.

I don't think it is aligning alike words; the pairwise2 aligner has no way to know what "alike" means:

```python
>>> old_alignments = pairwise2.align.globalms(['i', 'love', 'bananas', 'and', 'cheese'], ['bandanas', 'blind', 'bees'], -2, -1, -2, -1, gap_char=['♣'])
>>> old_alignments[0][:2]
(['i', 'love', 'bananas', 'and', 'cheese'], ['♣', '♣', 'bandanas', 'blind', 'bees'])
>>> old_alignments = pairwise2.align.globalms(['i', 'love', 'bananas', 'and', 'cheese'], ['anything', 'blind', 'bees'], -2, -1, -2, -1, gap_char=['♣'])
>>> old_alignments[0][:2]
>>> (['i', 'love', 'bananas', 'and', 'cheese'], ['♣', '♣', 'anything', 'blind', 'bees'])
```

In any case, to get the same alignment, set the gap scoring paramaters on the `aligner` object:
```
>>> aligner.open_gap_score = -2
>>> aligner.extend_gap_score = -1
>>> alignments = aligner.align(['i', 'love', 'bananas', 'and', 'cheese'], ['bandanas', 'blind', 'bees'])
>>> print(alignments[0])
i love bananas  and   cheese
- ---- .......  ...   ....  
- ---- bandanas blind bees  
```
For your last question:
> The pairwise2 function outputs a nice alignment representation which is very useful for my work.

What do you do with the alignment representation you got from `pairwise2`?

**Comment by trenslow** [comment]
@mdehoon I try to find common typos for given words. Instead of trying to interpret which words the user meant to type by hand, the alignment function is super useful for doing this automatically. After using it for a few years, I do get the feeling it has an idea of which words are somewhat alike, even if it's not exactly what it was designed to do. 

I haven't gotten a chance to explore it yet, but I would also like to play around with the new substitution matrices to better represent a keyboard so that e.g. substitutions between 't' and 'y' are penalized less than 't' and 'm'.

**Comment by mdehoon** [comment]
> After using it for a few years, I do get the feeling it has an idea of which words are somewhat alike, even if it's not exactly what it was designed to do.

The aligner just checks whether two words are the same or different, but it does not align the two words and does not evaluate their similarity. If one word in a sentence has a spelling error, it may align to the correct word just because the other words in the sentence are aligned to each other.

> I haven't gotten a chance to explore it yet, but I would also like to play around with the new substitution matrices to better represent a keyboard so that e.g. substitutions between 't' and 'y' are penalized less than 't' and 'm'.

Here also, the aligner does not align the words, so the substitution matrices won't make any difference. As an alternative, you could design some function that evaluates how close two words are, and use that function instead of the substitution matrix.

We could modify `Bio.Align` such that `alignment[i]` returns something useful when the aligned sequences are lists. Currently it does
```python
>>> alignment[0]
"['i', 'love', 'bananas', 'and', 'cheese']---"
>>> alignment[1]
"-----['bandanas', 'blind', 'bees']"
```
which is just useless. This could be
```python
>>> alignment[0]
['i', 'love', 'bananas', 'and', 'cheese']
>>> alignment[1]
[None, None, 'bandanas', 'blind', 'bees']
```

**Comment by trenslow** [comment]
@mdehoon 

> We could modify `Bio.Align` such that `alignment[i]` returns something useful when the aligned sequences are lists.

Yes! That would be extremely useful :) 

In the old pairwise2 function, I could also pass a "gap_char" parameter, which would allow me to customize what the Nones would be (I think it defaulted to "-"), which would also be helpful. One not immediately clear thing about that parameter was that it has to be the same type as the sequences to be aligned. If you do consider the gap_char parameter, it would be nice to have appropriate documentation/type-hinting for it.

**Comment by mdehoon** [comment]
In the `Alignment` class, we are separating the alignment information (i.e. where are the gaps) from the alignment representation (e.g., gap characters). In the previous `MultipleSeqAlignment` class those two things were mixed, which limited its usability. I am very hesitant to add representation stuff to the output of `alignment[i]`. For example, what to do if one of the objects you are aligning happens to be `"-"`? Or if you are aligning objects of different classes? In any case, you can always replace `None` with the gap character of your choice afterwards.

**Comment by trenslow** [comment]
@mdehoon ah, that's a very good point. Adding in the gap characters after the fact is definitely more robust :)

**Comment by mdehoon** [comment]
@trenslow 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
