### ISSUE TITLE
Limitation on retmax and max length of records['IdList'] in Bio.Entrez.esearch

### ISSUE THREAD

**Issue by WBY20** [biopython/biopython#4189]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]
CPython
Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
1.79

### Steps to reproduce
```python
from Bio import Entrez
Entrez.email = 'Mymail'
Entrez.api_key = 'My key'

handle = Entrez.esearch(db="pubmed", term='Cholesterol', sort="relevance", retmode="xml", retmax=20000)
records = Entrez.read(handle)
len(records['IdList'])
```
9999

Hello,
It seems that records['Count'] is 319477, much more than 10K.  And records['WarningList'] returns ''Restrictions achieved. start and count adjusted to 0, 9999'. If I set up 'retstart' to more than 10K,  it returns 'Search Backend failed: Exception:
Position 15000 is out of acceptable range [9999,9998]'. So I wonder if there is any way to remove the limitation of Bio.Entrez.esearch?

**Comment by mdehoon** [comment]
Biopython doesn't set any restrictions, it just parses the data returned by NCBI Entrez. To debug this, I would suggest to look at `handle.url` in a web browser, and contact NCBI if the output is not consistent with the Entrez documentation.
