### ISSUE TITLE
Docs failing on CI actions

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4199]
Worked: https://github.com/biopython/biopython/actions/runs/3583510290/jobs/6029226495 30 Nov 2022
Failed: https://github.com/biopython/biopython/actions/runs/3612302775/jobs/6087366236 4 Dec 2022
i.e. Since https://github.com/biopython/biopython/pull/4187 was merged, but that is almost certainly not to blame.

Comparing the above logs, I am guessing this is the failure:

```
WARNING: autodoc: failed to import module 'pm_fitting' from module 'Bio.phenotype'; the following exception was raised:
Install scipy to extract curve parameters.
```

That comes from https://github.com/biopython/biopython/blob/master/Bio/phenotype/pm_fitting.py which has not changed recently, excerpt:

```python
try:
    from scipy.optimize.minpack import curve_fit
    from scipy.integrate import trapz
except ImportError:
    from Bio import MissingPythonDependencyError

    raise MissingPythonDependencyError("Install scipy to extract curve parameters.")
```

But scipy is listed in https://github.com/biopython/biopython/blob/master/ci-dependencies.txt which gets installed from https://github.com/biopython/biopython/blob/master/.github/workflows/ci.yml for docs.

Note also listed in https://github.com/biopython/biopython/blob/master/.circleci/requirements-sphinx.txt for CircleCI

There was no new release of scipy in that time window: https://pypi.org/project/scipy/#history

**Comment by Anika-Roy** [comment]
Hello! I'd like to contribute to biopython. I'd like to know if there are any prerequisites required. How should I get started?

**Comment by peterjc** [comment]
@Anika-Roy if you really want to try to work on _this_ issue, start by trying to run Sphinx locally, and see if you can trigger the same error message or not. However, this is not a good first-issue for a Python novice.

**Comment by acvander** [comment]
I was able to run the [CI actions on a fresh fork](https://github.com/acvander/biopython/actions/runs/3707184895) without errors. That run didn't have the same [autodoc warning that the problem runs demonstrated](https://github.com/acvander/biopython/actions/runs/3707184895/jobs/6283590406#step:9:614).

Is it possibly an issue with the cache being used in the docs step?

**Comment by peterjc** [comment]
@acvander that does seem possible if it worked on a fresh fork. I'm still more familiar with TravisCI and CircleCI than GitHub Actions, is it easy to manually reset the cache?

**Comment by acvander** [comment]
@peterjc it looks like the issue may be resolved already. On [CI1221](https://github.com/biopython/biopython/actions/runs/3708927338), the python version for the docs task was bumped up a patch version to 3.9.16 triggering creation of a new cache.

I'm not too familiar with GitHub Actions either. If you need to delete a cache in the future, go to the actions pane->sidebar "caches"->then select the trash can icon next to the cache you want to delete. I'm testing this out on my fork to see if it causes any problems.

**Comment by peterjc** [comment]
Thank you, those are useful insights.
