### ISSUE TITLE
'Seq' object has no attribute '_data'

### ISSUE THREAD

**Issue by Dan-Burns** [biopython/biopython#4214]
Biopython 1.80
Ubuntu 22.04.1
Python 3.10.8

I have pickled a dictionary with Seq objects as values. 

I can open the file but when I try to inspect the dictionary I get the following error.

```
File ~/.local/lib/python3.10/site-packages/Bio/Seq.py:355, in _SeqAbstractBaseClass.__repr__(self)
    353 def __repr__(self):
    354     """Return (truncated) representation of the sequence."""
--> 355     data = self._data
    356     if isinstance(data, _UndefinedSequenceData):
    357         return f"Seq(None, length={len(self)})"

AttributeError: 'Seq' object has no attribute '_data'
```
It's been a while but I thought I opened this in the past.  Don't know what I might have changed in my environment that could have caused this error to arise.

Thank you,
Dan

**Comment by mdehoon** [comment]
There have been some changes in the `Seq` class between recent versions of Biopython. If you pickle a Seq object with an older version of Biopython and unpickle it with a newer version of Biopython, you may then find such incompatibilities.
If you want to use the pickled data with a current version of Biopython, you could install the version of Biopython these data were created with, read the pickled data, save the data in some text file (maybe, use SeqIO to store them as a Fasta file), and then read in the text file with the current version of Biopython.

**Comment by peterjc** [comment]
Personally I'd only ever use pickle as a short term intermediate storage format (with any Python package), complex objects often evolve over time causing this kind of trouble.

As @mdehoon suggests, one of the standard sequence files formats would be best for long term storage - human readable as a bonus.

**Comment by Dan-Burns** [comment]
Thank you!
