### ISSUE TITLE
TypeError when get structure using MMCIFParser with parameter auth_residues=False

### ISSUE THREAD

**Issue by Koistory** [biopython/biopython#4216]
### Setup

Hi, I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-10-10.0.19044-SP0
1.80
```

### Expected behaviour

I want to exact the residues of `1FE4.cif` with mmcif-style residue index, so I look up the document and run the code
```
from Bio.PDB.MMCIFParser import MMCIFParser
parser = MMCIFParser(auth_chains=False, auth_residues=False)
pdb_structure = parser.get_structure("1FE4", "1fe4.cif")
```

### Actual behaviour

The code can run well with parameter auth_residues=True, but when I set auth_residues=False, it seems to be some mistakes with the usage of warning.warn in `_build_structure` of `\Bio\PDB\MMCIFParser.py` for the type of input
```
Traceback (most recent call last):
  File "c:\Users\86153\Desktop\ai\bio\code\bio.py", line 19, in <module>
    pdb_structure = parser.get_structure("1FE4", "1fe4.cif")
  File "C:\Users\86153\miniconda3\envs\bio\lib\site-packages\Bio\PDB\MMCIFParser.py", line 74, in get_structure
    self._build_structure(structure_id)
  File "C:\Users\86153\miniconda3\envs\bio\lib\site-packages\Bio\PDB\MMCIFParser.py", line 241, in _build_structure
    warnings.warn(
TypeError: 'type' object cannot be interpreted as an integer
```

The error happens in line 234-246 of `\Bio\PDB\MMCIFParser.py`
```python
if resseq == ".":
    # Non-existing residue ID
    try:
        msg_resseq = mmcif_dict["_atom_site.auth_seq_id"][i]
        msg = "Non-existing residue ID in chain '{}', residue '{}'".format(
            chainid, msg_resseq
        )
    except (KeyError, IndexError):
        msg = f"Non-existing residue ID in chain '{chainid}'"
    warnings.warn(
        "PDBConstructionWarning: ",
        msg,
        PDBConstructionWarning,
    )
    continue
```

I look up the usage of warnings.warn in python 3.10, and I find the third parameters of warnings.warn should be a interger of stack level, but in the code mentioned above, the type is `PDBConstructionWarning`. I guess the code want to concat the string "PDBConstructionWarning: " and msg, and let `PDBConstructionWarning` to be the second parameter which indicates the category of warning. I make some minor changes and it works
```
if resseq == ".":
    # Non-existing residue ID
    try:
        msg_resseq = mmcif_dict["_atom_site.auth_seq_id"][i]
        msg = "Non-existing residue ID in chain '{}', residue '{}'".format(
            chainid, msg_resseq
        )
    except (KeyError, IndexError):
        msg = f"Non-existing residue ID in chain '{chainid}'"
    warnings.warn(
        "PDBConstructionWarning: " +
        msg,
        PDBConstructionWarning,
    )
    continue
```
In addition, I find the same mistakes appear in `\Bio\PDB\MMCIFParser.py`. May you check the code and fix the minor mistakes in your latest version? Thank you!

**Comment by peterjc** [comment]
You change looks good - could you submit this as a pull request please? You can do a small edit like this entirely within GitHub's web interface. Thank you.

**Comment by Koistory** [comment]
Ok, I will soon close the issue and submit PR.

**Comment by peterjc** [comment]
Normally we'd leave the issue open until the pull request is merged, otherwise the problem might be forgotten in between - or someone might open a duplicate if by bad luck they find the same problem.

**Comment by peterjc** [comment]
This should be working now (thanks @jgreener64)! You'd need to install Biopython from source or wait for Biopython 1.82 to be released.
