### ISSUE TITLE
Standardize on import numpy as np

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4238]
I think we should follow the numpy documentation and avoid the plain ``import numpy`` form in favour of ``import numpy as np``.

With the current code base:

```
$ cat *.py */*.py */*/*.py | grep "import numpy" | sort | uniq -c
   1         >>> import numpy
   9     import numpy
   3     import numpy as np
   1     import numpy as np  # type: ignore
  17 import numpy
   1 import numpy  # type: ignore
   8 import numpy as np
   1 import numpy as np  # type: ignore
   1 import numpy.linalg
```

This is a fairly simple change with search-and-replace (e.g. using ``sed`` at the command line), suitable for a first-time contributor so marking as such.

**Comment by mdehoon** [comment]
Does the numpy documentation recommend using `np` instead of `numpy`? The latter is more explicit.

**Comment by peterjc** [comment]
Yes, e.g. https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-import-numpy

**Comment by PaarthAgarwal** [comment]
I'd like to work on this issue

**Comment by pvalle6** [comment]
About to make a pull request with this.

**Comment by peterjc** [comment]
Two volunteers at once? Oh well. There is plenty here, aside the main code base (tests, tutorial, website documentation, etc).

**Comment by pvalle6** [comment]
Ah, looks like I was beat by a couple minutes on these commits. If y'all have anymore good first issues, I'd love to help.

**Comment by PaarthAgarwal** [comment]
> Ah, looks like I was beat by a couple minutes on these commits. If y'all have anymore good first issues, I'd love to help.

Shouldn't have picked when someone is already working on it 🤷

**Comment by peterjc** [comment]
Unlucky timing @pvalle6, how about checking the website examples on https://github.com/biopython/biopython.github.io then?

**Comment by pvalle6** [comment]
For sure. Thanks for recommendation @peterjc

**Comment by mdehoon** [comment]
> Yes, e.g. https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-import-numpy

Before spending more time on this, you may want to reconsider if this is really a good idea. Yes, the numpy documentation says

"This is a widely adopted convention that you should follow"

but the rationale

"for better readability of code using NumPy"

does not really apply to Biopython.

Here, readability can mean using `np` as an abbreviation for `numpy` to make lines shorter and therefore more readable. But that is relevant only for code that does complex things with numpy. In Biopython, our use of numpy is simple, and any gain in code length by making this substitution is negligible.

Alternatively, readability can mean using `np` consistently for recognizability. But anyone who recognizes `np` as numpy will surely recognize `numpy` as numpy. And for people new to Python, using `np` instead of `numpy` will be one more potential source of confusion. It is also inconsistent with Python's rule that explicit is better than implicit.

Note also that "This is a widely adopted convention that you should follow" may just mean "if you use an alias, use `np`" rather than "you must always use an alias".

Practically speaking, replacing `numpy` by `np` will be more complicated than it may appear at first. For example, in the `test_Align*` scripts there are lots (hundreds?) of lines where `numpy` is used in lines where flake8/black code checking was turned off (because they insisted on unreadable code). Someone (i.e., not me) would have to go in and fix those by hand.

**Comment by PaarthAgarwal** [comment]
That's a valid point @mdehoon

**Comment by peterjc** [comment]
On that specific concern, we could leave the tests alone.

I do think user facing code should be updated (specifically documentation including the tutorial and the doctests). The easiest way to do that would be apply it to the ``Doc`` and source code under ``Bio``, ``Scripts`` (and if relevant ``BioSQL/``).

**Comment by mdehoon** [comment]
> I do think user facing code should be updated (specifically documentation including the tutorial and the doctests).

Why do you think so?

**Comment by JoaoRodrigues** [comment]
Just chiming in to say that while `import numpy as np` might not be a _de jure_ standard, it is the _de facto_ standard and as such, should not be confusing at all.

**Comment by peterjc** [comment]
Why? Because anywhere our documentation import numpy, it should use the ``import numpy as np`` style to match the convention set out by the numpy team. This will be easiest for our users, especially Python novices.

**Comment by Aum8** [comment]
@peterjc Is this issue still open? How can I contribute to it?

**Comment by pvalle6** [comment]
> It looks like https://github.com/biopython/biopython/pull/4242 is stalled, although @pvalle6 also offered to help on it. I'd say if @PaarthAgarwal doesn't reply this week, that @pvalle6 might as well take over that effort and/or start again if easier. If there is an obvious part of the work @Aum8 could handle, that would be nice.
> 
> Noting the discussion above, I would leave the ``Tests/`` alone for now.
> 
> In fact, it might be best to start small, for example only the tutorial under ``Doc/``?

I asked if he would accept a commit to his forked repo and never got a reply. I'd be happy to restart this. Although, I would rather start smaller.

**Comment by Aum8** [comment]
> It looks like #4242 is stalled, although @pvalle6 also offered to help on it. I'd say if @PaarthAgarwal doesn't reply this week, that @pvalle6 might as well take over that effort and/or start again if easier. If there is an obvious part of the work @Aum8 could handle, that would be nice.
> 
> Noting the discussion above, I would leave the `Tests/` alone for now.
> 
> In fact, it might be best to start small, for example only the tutorial under `Doc/`?

Thank you for guiding me on that! I would like to help with @pvalle6 on the tutorial under `Doc/` , if he is ok with that.

**Comment by pvalle6** [comment]
> > It looks like #4242 is stalled, although @pvalle6 also offered to help on it. I'd say if @PaarthAgarwal doesn't reply this week, that @pvalle6 might as well take over that effort and/or start again if easier. If there is an obvious part of the work @Aum8 could handle, that would be nice.
> > Noting the discussion above, I would leave the `Tests/` alone for now.
> > In fact, it might be best to start small, for example only the tutorial under `Doc/`?
> 
> Thank you for guiding me on that! I would like to help with @pvalle6 on the tutorial under `Doc/` , if he is ok with that.

I'm about to add some commits to my numpy-standardization branch, feel free to add anything you want to it. We can create a pull request whenever. I'm unsure if we can just keep an unmerged pull request and continually add to it.

**Comment by peterjc** [comment]
After the tutorial changes, my grep results above suggest just a single doctest needs updating (search for ``>>> import numpy``), perhaps there are more though?

**Comment by BabaYaga1221** [comment]
Recently, I create a PR on this issue. would you merge it?

**Comment by peterjc** [comment]
@BabaYaga1221 you mean your pull request #4259?

I have removed the "help wanted" label to stop any more volunteers for something already being worked on.

**Comment by BabaYaga1221** [comment]
OK. Got it. Can you assign me some other issue? @peterjc

**Comment by peterjc** [comment]
Just test files now, the biggest group being ``Tests/test_PDB_*.py`` which should be a nice batch to do as a single pull request.

**Comment by peterjc** [comment]
Current cases to fix:

```
$ grep -E "import numpy($|  #)" *.py */*.py */*/*.py
Tests/test_Align_codonalign.py:    import numpy
Tests/test_LogisticRegression.py:    import numpy
Tests/test_PDB_DSSP.py:    import numpy  # noqa: F401
Tests/test_PDB_Exposure.py:    import numpy
Tests/test_PDB_FragmentMapper.py:    import numpy
Tests/test_PDB_MMCIF2Dict.py:    import numpy
Tests/test_PDB_MMCIFParser.py:    import numpy
Tests/test_PDB_NACCESS.py:    import numpy
Tests/test_PDB_PDBParser.py:    import numpy
Tests/test_PDB_SMCRA.py:    import numpy
Tests/test_PDB_Superimposer.py:    import numpy
Tests/test_PDB_parse_pdb_header.py:    import numpy  # noqa F401
Tests/test_PDB_vectors.py:    import numpy
Tests/test_RCSBFormats.py:    import numpy
Tests/test_SeqIO_PdbIO.py:    import numpy
Tests/test_SeqRecord.py:    import numpy
Tests/test_Seq_objs.py:    import numpy
Tests/test_codonalign.py:    import numpy
Tests/test_kNN.py:    import numpy
Tests/test_phenotype.py:    import numpy
Tests/test_phenotype_fit.py:    import numpy
Tests/test_seq.py:    import numpy
Bio/phenotype/__init__.py:    import numpy
```

**Comment by john-science** [comment]
I have opened a PR for this issue over here: https://github.com/biopython/biopython/pull/4815

Simple enough, but I am happy to make any changes you like.
