### ISSUE TITLE
Unknown Seq deprecated without major version bump breaking BCBio.GFF 

### ISSUE THREAD

**Issue by corneliusroemer** [biopython/biopython#4239]
### Setup

I just installed the newest Biopython version 1.81 and got a bug that took some time to figure out.

Turns out, you deprecated UnknownSeq in 1.81, something that BCBio.GFF uses.

I discover (now) that you announced deprecation in a deprecated.rst for 1.81, but this wasn't quite easy to find - there's no mention of it in the release notes.

It would be great if you could put deprecations in release notes to make it easier to discover why something breaks.

Also, in general, it would be nice if you used semver and increased major version if you deprecate something.

Bug caused by this: https://github.com/nextstrain/augur/issues/1151

**Comment by Lioscro** [comment]
I also encountered this while using `BCBio`. Would have been great to have the deprecation noted in the changelogs and a major bump.

**Comment by mdehoon** [comment]
> Also, in general, it would be nice if you used semver and increased major version if you deprecate something.

This would not be realistic -- stuff gets deprecated in most if not all Biopython releases.

**Comment by corneliusroemer** [comment]
Hmm, I don't see why one can't bump major version in most releases. This is what browsers do for example. They deprecate stuff all the time, so they bump. 

At least a deprecation notice when importing this module would have been good, for the future. I don't think I ever saw a warning?

**Comment by JoaoRodrigues** [comment]
Note that we do list deprecations though: https://github.com/biopython/biopython/blob/master/DEPRECATED.rst#biosequnknownseq

**Comment by JoaoRodrigues** [comment]
And referencing the specific commit, we did do issue `DeprecationWarnings`: https://github.com/biopython/biopython/pull/4173/files#diff-bdfee92a19a985d8313cb909cc673c4f02acb6d54f4aeea337b0e03e7f6b5803L2220

Not blaming anyone for not noticing it, I know that deprecation warnings can be annoying and people often silence them, or if Biopython is an upstream dependency, you might never even see these warnings. So, in the future, we might want to add a note to the NEWS or so, pointing directly to the deprecations for each release, basically linking `NEWS.rst` and `DEPRECATED.rst` for easier browsing by users.

**Comment by siddhartasr10** [comment]
It is instantiated, it also creates a record with an UnknownSeq: https://github.com/chapmanb/bcbb/blob/dbfb52711f0bfcc1d26c5a5b53c9ff4f50dc0027/gff/BCBio/GFF/GFFParser.py#L543

 
But maybe it doesn't show because its done on a private method?

**Comment by peterjc** [comment]
@siddhartasr10 update your copy of BCBio, see https://github.com/chapmanb/bcbb/commit/8a36af0c1af2c2b39e841cea2496f7a367ffdae5
