### ISSUE TITLE
Human Readable PairwiseAligner String change - option for the old way?

### ISSUE THREAD

**Issue by CCranney** [biopython/biopython#4250]
Hi,

There was a change to how the `Bio.Align.PairwiseAligner` output is printed in [this pull request](https://github.com/biopython/biopython/pull/4145). Alignments are broken in multiple lines that specify index, target and query strands instead of the previous format, which had it all in one continuous format.

I am doubting this exists, but I don't see a way to optionally print in the old way. I have some code that relies on the old way that won't be easy to translate over. Is there such an option that I'm not seeing? I doubt it, but thought I would reach out in case there was.

**Comment by peterjc** [comment]
Have you explored the assorted format method outputs? Might one of them be close enough, and if not might adding a simple three-line format resolve this?

See also issue #3538 (implemented in #4221) for accessing the identities, mismatches and gaps counts which used to be easily computed from the string representation.

**Comment by CCranney** [comment]
Hi all,

Thank you for your responses. To your comment, @peterjc, I didn't find an assorted format methods for PairwiseAligner strings that work, though it's possible I missed one that would. The issue you mentioned was focused on counts, where my script looks for specific indices of those differences, if that makes sense. Brief explanation of what I'm doing in the next paragraph. @mdehoon, thank you for explaining how I could get the individual sequences. Unfortunately I do need the line printed between the two sequences, and because I'm hoping to maintain and share this script in the future can't rely on old releases. 

For context, my script determines the indices that specific indels/mutations occur at as well as what the changes themselves are. For example, the the tuple (23,23,"A") indicates an adenosine insertion at index 23, (23,24,"A") indicates a mutation at index 23, etc. I'm using this method to determine common differences between a target sequence and various query sequences for target sequence correction. This is fairly straightforward to deduce from the string output, so relied on that to get it to run.

Overall, I tinkered with the code and wrote a function that basically rewrites the new format back into the old format. It feels a little hacky, but I suppose so was writing code that depended on the string output in the first place. Thank you for your input, I'll go ahead and close this issue.

For reference, here is present algorithm. It needs to be cleaned up a bit, but it looks like it works at present:

```
def break_down_alignment_to_strings(alignment):
alignmentString = alignment.format()
if "target" in alignmentString:
    lines = alignmentString.split("\n")
    targetLines = lines[::4]
    matchLines = lines[1::4]
    queryLines = lines[2::4]
    searches = [re.search("([ATCG-])+", line) for line in targetLines]
    indices = [search.span() for search in searches if search]
    originalSequenceAlignment = "".join([targetLines[i][indices[i][0]:indices[i][1]] for i in range(len(indices))])
    indelIndicator = "".join([matchLines[i][indices[i][0]:indices[i][1]] for i in range(len(indices))])
    differentSequenceAlignment = "".join([queryLines[i][indices[i][0]:indices[i][1]] for i in range(len(indices))])
else:
    originalSequenceAlignment, indelIndicator, differentSequenceAlignment, _ = alignment.format().split("\n")
return originalSequenceAlignment, indelIndicator, differentSequenceAlignment
```

**Comment by mdehoon** [comment]
> ... and because I'm hoping to maintain and share this script in the future can't rely on old releases.

I meant copying the code in `_format_pretty` from Biopython 1.79 and pasting it into your script. Then you won't need to write new code.

**Comment by CCranney** [comment]
Oh! Sorry I misunderstood - I'll take a look at that function.
