### ISSUE TITLE
docs on scaling alignment slicing 

### ISSUE THREAD

**Issue by nick-youngblut** [biopython/biopython#4257]
The docs on alignment slicing currently state:

```
Combining this alignment slicing with alignment addition allows you to remove a section of the alignment. For example, taking just the first and last ten columns:

print(align[:, :10] + align[:, -10:])
Alignment with 7 rows and 20 columns
TATACATTAAGTGTACCAGA gi|6273285|gb|AF191659.1|AF191
TATACATTAAGTGTACCAGA gi|6273284|gb|AF191658.1|AF191
TATACATTAAGTGTACCAGA gi|6273287|gb|AF191661.1|AF191
TATACATAAAGTGTACCAGA gi|6273286|gb|AF191660.1|AF191
TATACATTAAGTGTACCAGA gi|6273290|gb|AF191664.1|AF191
TATACATTAAGTATACCAGA gi|6273289|gb|AF191663.1|AF191
TATACATTAAGTGTACCAGA gi|6273291|gb|AF191665.1|AF191
```

...but it appears that there are no docs on scaling/abstracting this slicing procedure to slice `n` number of regions from an alignment. Such docs would be quite helpful, since numpy array slicing is non-trivial for scaling to `n` slices.

**Comment by peterjc** [comment]
How would your n slices be defined? A list of booleans, one per column
should be fairly easy to use.

**Comment by nick-youngblut** [comment]
> How would your n slices be defined? 
Either a set of ranges (e.g., `1:3, 5:10, ...`) or just specific column indices (e.g., `1, 8, 22, ...`).

**Comment by peterjc** [comment]
We don't have anything like that in the current API.

Do you have a good example of slicing a single string like that, which could be useful in thinking about how to do this to the alignment instead.

Note this is not a numpy array (although you could turn it into a numpy array of single character strings and use numpy indexing).

**Comment by nick-youngblut** [comment]
The GPT-4 answer to this alignment slicing problem, which works:

```
from Bio.Align import MultipleSeqAlignment
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

# Create a sample MultipleSeqAlignment object
seq1 = SeqRecord(Seq("ACTGCTAG"), id="seq1")
seq2 = SeqRecord(Seq("AGTCGTAC"), id="seq2")
seq3 = SeqRecord(Seq("TGCACTGA"), id="seq3")

alignment = MultipleSeqAlignment([seq1, seq2, seq3])
print("Original alignment:")
print(alignment)

# Define the discontinuous position indices
positions_to_select = [1, 4, 7]

# Slice the alignment using a list comprehension
sliced_alignment = MultipleSeqAlignment([
    SeqRecord(Seq(''.join(seq.seq[i] for i in positions_to_select)), id=seq.id)
    for seq in alignment
])

print("Sliced alignment:")
print(sliced_alignment)
```
