### ISSUE TITLE
Misleading statement in CompoundLocation.end docstring

### ISSUE THREAD

**Issue by seanrjohnson** [biopython/biopython#4260]
I believe the text in parentheses `(minus one given how Python counts from zero)` is incorrect, and should be deleted.

https://github.com/biopython/biopython/blob/c0be3a0b477f9cce38f26d91af538b2b07ca4720/Bio/SeqFeature.py#L1849

When I load a circular record where the first features spans the origin.

```python
>>> int(rec.features[0].location.end) == len(rec)
True
```

This also makes sense with python slicing, because to slice an array/SeqRecord of size 1, you would do `a[0:1]` to get the entire array/SeqRecord, not `a[0:0]`.

**Comment by peterjc** [comment]
That does look wrong at first glance, have a look at your favourite circular genome, or from our tests https://github.com/biopython/biopython/blob/master/Tests/GenBank/NC_000932.gb

Please confirm with the source feature (``.features[0]`` in the record). I don't have time right now.

**Comment by seanrjohnson** [comment]
```python
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import SeqIO
>>> r = SeqIO.read("NC_000932.gb", "genbank")
>>> int(r.features[0].location.end) == len(r)
True
```

Yeah, it's true for that `NC_000932.gb` file.

I think it's not quite the latest version of biopython, probably 1.78 or so, but I guess numbering probably hasn't changed in a long time.

**Comment by peterjc** [comment]
Good, can you make a pull request to correct the text then? Thanks!

**Comment by peterjc** [comment]
I realise that the example I was looking at is not an origin-wrapping feature, but still the original text was wrong.
