### ISSUE TITLE
Reading in PWM (matrix format)

### ISSUE THREAD

**Issue by grexor** [biopython/biopython#4265]
Great job everyone on **biopython**!

I would like to read-in a motif matrix in the format below. Any ideas if its possible natively in biopython or I would need to re-parse this to another format?

Thanks,
Gregor

```
AC	K562.XRCC6.0
XX
TY	Motif
XX
ID	K562.XRCC6.0
XX
NA	K562.XRCC6.0
XX
DE	N=54, Consensus=NNTAACGAGNN, Score=77.0156261016856
P0	A	C	G	T
01	3	2	4	45	N
02	4	1	5	44	N
03	0	0	0	54	T
04	53	0	0	1	A
05	53	0	0	1	A
06	18	16	15	5	C
07	5	5	42	2	G
08	52	0	0	2	A
09	0	0	54	0	G
10	25	16	6	7	N
11	9	21	7	17	N
XX
IC	1.055 1.017 1.960 1.827 1.827 0.080 0.866 1.731 1.960 0.191 0.092
XX
XL
00	36
01	2
02	3
03	0
04	0
05	12
06	0
07	1
08	0
09	0
10	0
XX
```

**Comment by peterjc** [comment]
What file format is this (looks a bit like some of the EBI/EMBL files in style to me, but I don't work with motifs), and have you looked at the ``Bio.motifs`` module which is described in the Tutorial? https://biopython.org/DIST/docs/tutorial/Tutorial.html

**Comment by grexor** [comment]
Thank you Peter, I also don't know which kind of format is it, I asked the authors (https://zhanglab.c2b2.columbia.edu/mCrossBase/). I am familiar with the biopython tutorial yes, very nicely done!

**Comment by mdehoon** [comment]
See section 14.2.3 in the tutorial

**Comment by grexor** [comment]
Bingo:

```
from Bio import motifs
record = motifs.parse(open("data.mat"), "TRANSFAC", strict=False)
motif = record[0]
```

Thanks

**Comment by peterjc** [comment]
So it was TRANSFAC format then, closing :)
