### ISSUE TITLE
biopython has problems with the number of nested loops

### ISSUE THREAD

**Issue by z626093820** [biopython/biopython#4266]
### Setup
I am reporting a problem with Biopython version, Python version, and operating
system as follows:
windows11

When I use nested loops, the number of calculations is less than it should be
This is the number of sequences in the first file. it has the five sequences.
![image](https://user-images.githubusercontent.com/37371455/225906140-ce1cef59-dadf-4055-ac5c-6ca857d28a8f.png)

the second has the three sequences
![image](https://user-images.githubusercontent.com/37371455/225906020-27df799d-19bf-4f11-8b84-9360e347e4fc.png)

the nested loops number should be fifiteen,but it shows three
![image](https://user-images.githubusercontent.com/37371455/225906309-a286e648-ec26-4027-b1aa-282a5c65cc57.png)

what is wrong with this, THANK YOU!

**Comment by peterjc** [comment]
The iterator for seq2 can only be used once, the second time it is at the end of the file and give no more records. Simplest change would be replace:


```
ricecirc=SeqIO.parse(...)
```

with:

```
ricecirc=list(SeqIO.parse(...))
```

That will use more memory though.

**Comment by mdehoon** [comment]
Or you could call `ricecirc=SeqIO.parse(...)` inside the outer loop, if you want to avoid using more memory.

**Comment by z626093820** [comment]
> The iterator for seq2 can only be used once, the second time it is at the end of the file and give no more records. Simplest change would be replace:
> 
> ```
> ricecirc=SeqIO.parse(...)
> ```
> 
> with:
> 
> ```
> ricecirc=list(SeqIO.parse(...))
> ```
> 
> That will use more memory though.

THANK YOU!! this solve the problems

**Comment by z626093820** [comment]
> Or you could call `ricecirc=SeqIO.parse(...)` inside the outer loop, if you want to avoid using more memory.

i am not clear  how to write this code，would you guide me? THANK YOU !!

**Comment by mdehoon** [comment]
```python
record = SeqIO.parse(...)
for seq in record:
    ricecirc = SeqIO.parse(...)
    for seq2 in ricecirc:
        ...
```
