### ISSUE TITLE
SeqIO.write RuntimeError: generator didn't stop after throw()

### ISSUE THREAD

**Issue by z626093820** [biopython/biopython#4267]
### Setup

I am reporting a problem with Biopython 1.81, Python 3.10.9, and windows11 as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)
![image](https://user-images.githubusercontent.com/37371455/225913515-7d501f66-424c-4f6b-be7a-862f9987cbd8.png)

### Expected behaviour

When I use pandas to read the excel and use record to read the sequence and id in the dataframe, an error is reported during the final write. the error is SeqIO.write RuntimeError: generator didn't stop after throw()

**the dataframe is** 
![image](https://user-images.githubusercontent.com/37371455/225914556-f1ed3c47-cda9-4cab-8163-f1bedbd2620b.png)

**the Code is as follows**
![image](https://user-images.githubusercontent.com/37371455/225915461-46b0563b-7f08-4b3c-95c0-b0b25335239a.png)

how can i slove this ,THANK YOU!

**Comment by peterjc** [comment]
There are two exceptions here. We might be able to change something to stop the ``generator didn't stop after throw()``, but the  immediate cause is the error ``SeqRecord (id=oURF1) has an invalid sequence``.


Try setting the sequence to ``Seq("")`` explicitly?

**Comment by z626093820** [comment]
> Seq("")
**When i change the seq of uORF1, it also  have the problem. the seq of uORF1 seems correct.**
![image](https://user-images.githubusercontent.com/37371455/226089363-84339e8a-c1ba-48bb-86e6-868b4bc6d65e.png)

**Comment by peterjc** [comment]
It looks like you've set the sequence to a plain empty string, ``""``, not an empty sequence object, ``Seq("")``, which is different.

(Can you copy-and-paste the code or output next time instead of screenshot images?)

**Comment by z626093820** [comment]
> 
**hello,below is my code**
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio import Seq
import pandas as pd
record=[SeqRecord(df.AAseq[i],id=df.uORF_ID[i],description='') for i in range(len(df.uORF_ID))]
for i in record:
    if i.id=='uORF1':
        print(i.seq)
        i.seq=Seq('')
        print(i.seq)
SeqIO.write(record,r'E:\rawdata\ribo数据\ribo水稻转录组Riboseq数据\Ribo-seq\X101SC19120875-Z01-F003\X101SC19120875-Z01-J001-B1-35\uORF预测结果\06orfprediction\三重复-pep.fa','fasta')

it show the error "'module' object is not callable"
![image](https://user-images.githubusercontent.com/37371455/226162948-86bb6e29-b9f9-49a4-a5df-69802662193b.png)

**Comment by peterjc** [comment]
Use this form as per the tutorial and our other documentation:

from Bio.Seq import Seq

This is an unfortunate historical design choice which modern Python style
guides warn against because there is a Seq module and a Seq object.

**Comment by z626093820** [comment]
> 

**when i change the seq of uORF1, it shows the same error: generator didn't stop after throw() , the time it shows the uORF2 is wrong ** ,so it may be is wrong beacuse of the seq comes from dataframe(excel) not txt?

from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
import pandas as pd
record=[SeqRecord(df.AAseq[i],id=df.uORF_ID[i],description='') for i in range(len(df.uORF_ID))]
for i in record:
    if i.id=='uORF1':
        print(i.seq)
        i.seq=Seq('')
        print(i.seq)
SeqIO.write(record,r'E:\rawdata\ribo数据\ribo水稻转录组Riboseq数据\Ribo-seq\X101SC19120875-Z01-F003\X101SC19120875-Z01-J001-B1-35\uORF预测结果\06orfprediction\三重复-pep.fa','fasta')


![image](https://user-images.githubusercontent.com/37371455/226173175-a2e90b5e-43e1-4107-a266-1f66ac41813c.png)

**Comment by peterjc** [comment]
Try this:

```python
from Bio.SeqRecord import SeqRecord
from Bio import Seq
record=[SeqRecord(Seq(df.AAseq[i]),id=df.uORF_ID[i],description='') for i in range(len(df.uORF_ID))]
...
```

i.e. Turn the string from the data frame into a ``Seq`` object as part of building a ``SeqRecord`` object.

**Comment by z626093820** [comment]
> Try this:
> 
> ```python
> from Bio.SeqRecord import SeqRecord
> from Bio import Seq
> record=[SeqRecord(Seq(df.AAseq[i]),id=df.uORF_ID[i],description='') for i in range(len(df.uORF_ID))]
> ...
> ```
> 
> i.e. Turn the string from the data frame into a `Seq` object as part of building a `SeqRecord` object.

THANK YOU ! this method slove the error!

**Comment by peterjc** [comment]
Great, glad we could help.

**Comment by z626093820** [comment]
> Great, glad we could help.

Sorry to interrupt again, can SeqIO.write cancel the automatic line feed when writing sequences?

**Comment by peterjc** [comment]
Short answer, no. Omitting the new lines / line feed would risk invalid output.

If you need to customise FASTA output specifically, the format is simple enough you might prefer to write this yourself. You'd have full control over line wrapping etc.
