### ISSUE TITLE
No output from Bio.PDB.DSSP.DSSP

### ISSUE THREAD

**Issue by DaniBodor** [biopython/biopython#4269]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows: 
Biopython 1.79, python 3.9, Ubuntu 20.04 on WSL, mkdssp version 4.2.2.1

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
>>> import sys; print(sys.version)
3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
>>> import Bio; print(Bio.__version__)
1.79
```

### Expected behaviour

I expect to get a DSSP object containing secondary structure data of my *.pdb file, in the format stated [here](https://biopython.org/docs/1.76/api/Bio.PDB.DSSP.html#examples).

### Actual behaviour

2 versions:

If the *.pdb file does not start with "HEADER" I get:
```
UserWarning: Since the file did not start with a valid PDB HEADER line mmCIF was assumed, but that failed.
 >> parse error at line 1: This file does not seem to be an mmCIF file
```

Otherwise I get an empty DSSP object (of len 0)

### Steps to reproduce

I followed [these steps](https://biopython.org/docs/1.76/api/Bio.PDB.DSSP.html#examples) to generate a DSSP object:

``` python =
from Bio.PDB import PDBParser
from Bio.PDB.DSSP import DSSP
p = PDBParser()

# pdb_file = '1ak4' # returns error
pdb_file = '1CRN' # returns empty DSSP object

pdb_path = f'../data/pdb/{pdb_file}/{pdb_file}.pdb'

_structure = p.get_structure(pdb_file, pdb_path)
model = _structure[0]
dssp = DSSP(model, pdb_path, dssp='mkdssp')

print(len(dssp))
```

The files referred to can be found [here](https://github.com/DeepRank/deeprank-core/tree/main/tests/data/pdb).

**Comment by peterjc** [comment]
Is this issue #3433?

**Comment by DaniBodor** [comment]
I don't know to be honest. There it is said that it "chokes", but not in what way (error, no output).

Also, wasn't issue 3433 fixed already, arguing that it is something else?

**Comment by peterjc** [comment]
If you're really running Biopython 1.79, then I *think* that predates support for DSSP v4.0 added in #3775. Can you try Biopython 1.80 or better the current release Biopython 1.81 instead?

**Comment by DaniBodor** [comment]
You're right. Upgrading to 1.81 did solve the problem with files that have the proper header. Was a bit stupid of me not to try that first.

However, for *.pdb files that do not start with the correct header (e.g. the 1ak4 file above), I am still getting an exception: "DSSP failed to produce an output".

Unfortunately, I have quite a few pdb files that just start with the atomic information straight away, and do not contain the header. Is there a way to read those properly without having to adjust the files themselves?

**Comment by peterjc** [comment]
Without looking at any of the details, my guess is the DSSP tool needs
corrected (or at least modified) versions of those particular PDB files. As
I recall, Biopython is just calling the DSSP tool on your behalf.

You may be able to read the files with Biopython and write them out again
to add a minimal header? You might have to set a few placeholder values too
- just enough to satisfy DSSP. Or, since these are plain text files,
perhaps it would be easier to insert a minimal header with a bit of Python
code without using the Biopython PDB code.

It is also possible that DSSP itself might be tweaked to accept those files
as they are. You’d have to ask the authors, but that seems an ideal
solution.

**Comment by DaniBodor** [comment]
You're right. I will raise an issue on the DSSP repo and in the meantime try to adjust my pdb files.

**Comment by rob-miller** [comment]
According to the man page for my linux mkdssp v 4.0.4, "PDB files must have
a CRYST1 record", but apparently the record can have default values as
specified at
https://www.wwpdb.org/documentation/file-format-content/format33/sect8.html#CRYST1

As unannotated files of ATOM coordinates scare me (pray you never have to
find "that one from the other day"), there is Bio.PDB.ic_rebuild.write_PDB
<https://biopython.org/docs/latest/api/Bio.PDB.ic_rebuild.html#Bio.PDB.ic_rebuild.write_PDB>
but it only does properly formatted HEADER and TITLE records from values as
set on the PDB struct, and not the CRYST1 records - probably a useful
feature to add if dssp maintainers won't implement a --input-dssp flag.

You can also convert your PDB files to mmcif with mmcifio
<https://biopython.org/docs/latest/api/Bio.PDB.mmcifio.html>.

**Comment by DaniBodor** [comment]
I did a workaround by making my code write a HEADER and dummy CRYST1 line into each pdb file, which now solves the issue. Not ideal, but best I can do at the moment, I think.
