### ISSUE TITLE
Extracting CDS seuences from a genbank file with "feature that spans the origin"

### ISSUE THREAD

**Issue by o-william-white** [biopython/biopython#4284]
### Setup

3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
CPython
Windows-10-10.0.19043-SP0
1.81

### Expected behaviour

Extract CDS annotations from a genbank file generated by plastid genome annotator https://github.com/quxiaojian/PGA

### Actual behaviour

In some outputs generated by PGA, there are annotated sequences identified as spanning the origin. In these situations I believe Biopython sets the location to None and reports a warning message. 

However, when this happens, I am unable to extract any CDS sequences from the SeqIO record, even if their location is not None. Below is an example error message that I get. 

```
Warning (from warnings module):
  File "C:\Users\oliw\AppData\Local\Programs\Python\Python310\lib\site-packages\Bio\GenBank\__init__.py", line 729
    warnings.warn(
BiopythonParserWarning: it appears that '2096..2088' is a feature that spans the origin, but the sequence topology is undefined; setting feature location to None.
Traceback (most recent call last):
  File "C:/Users/oliw/Documents/python_scripts_testing/extract_genes_from_gb/pga_extract_cds.py", line 14, in <module>
    print(feature.extract(record))
  File "C:\Users\oliw\AppData\Local\Programs\Python\Python310\lib\site-packages\Bio\SeqFeature.py", line 488, in extract
    return self.location.extract(parent_sequence, references=references)
  File "C:\Users\oliw\AppData\Local\Programs\Python\Python310\lib\site-packages\Bio\SeqFeature.py", line 1496, in extract
    f_seq = parent_sequence[int(self.start) : int(self.end)]
  File "C:\Users\oliw\AppData\Local\Programs\Python\Python310\lib\site-packages\Bio\SeqRecord.py", line 509, in __getitem__
    if start <= f.location.start and f.location.end <= stop:
AttributeError: 'NoneType' object has no attribute 'start'
```

### Steps to reproduce

Example files attached.

This works as expected:
```
# read gb
record = SeqIO.read('BM000519864_Charo_A1_contig0.gb.txt', 'gb')

# extract features
for feature in record.features:
    if feature.type == 'CDS':
        print(feature.extract(record))
```

This does not work, returning the error above.  
```
# read gb
record = SeqIO.read('BM000519864_Charo_A1_contig5.gb.txt', 'gb')

# extract features
for feature in record.features:
    if feature.type == 'CDS':
        print(feature.extract(record))
```

I hope I haven't missed anything simple. Thanks for sharing and supporting biopython! 

Best wishes
Ollie

**Comment by o-william-white** [comment]
[BM000519864_Charo_A1_contig0.gb.txt](https://github.com/biopython/biopython/files/11252237/BM000519864_Charo_A1_contig0.gb.txt)
[BM000519864_Charo_A1_contig5.gb.txt](https://github.com/biopython/biopython/files/11252238/BM000519864_Charo_A1_contig5.gb.txt)

**Comment by o-william-white** [comment]
Hello, 

I managed to find a workaround but it seems a bit unneccessary. I found that if I create a new Seq object and extracted from this it seemed to work ok. Example code below. 

If one of the features in a SeqIO.read object has a location marked as None, does it just make it impossible to extract from this? 

Best wishes
Ollie

```
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

# read gb
record = SeqIO.read('BM000519864_Charo_A1_contig5.gb.txt', 'gb')

# create seq object
seq = Seq(record.seq)

# set up empty list
gene_list = []

# extract features
for feature in record.features:
    if feature.type == 'CDS' and feature.location != None:
        # get gene name
        gene_name = feature.qualifiers['gene'][0]
        # create new SeqRecord using extract from seq
        gene_seq = SeqRecord(
            feature.extract(seq),
            id=gene_name,
            name=gene_name,
            description='')
        # append to list
        gene_list.append(gene_seq)

# write fasta
SeqIO.write(gene_list, 'test.fasta', 'fasta')
```

**Comment by peterjc** [comment]
When the GenBank parser cannot understand a feature location, it will give a warning and set the location of that ``SeqFeature`` object to ``None``. It will then continue loading the rest of the file. When that happens, you cannot extract the matching sequence for that feature because we don't know where it should be.

Note stylistically it is better to use ``x is None`` or ``x is not None`` than equality, see e.g. https://peps.python.org/pep-0008/#programming-recommendations *"Comparisons to singletons like None ..."*

Sometimes the GenBank parser can recognise a special case malformed feature location where we are confident of the intended meaning, and they you just get a warning.

In this case, your GenBank file has a poorly defined origin spanning feature. Could you file a bug at https://github.com/quxiaojian/PGA/issues with more details?

Also, given you are working with a plasmid, I would strongly suggest you rotate the circle to avoid having the start of the circle within a coding gene.

**Comment by o-william-white** [comment]
Hi @peterjc 

Many thanks for your reply and thoughts on this. I expect this is due to using a poorly annotated reference sequence with PGA. 

I will file an issue on PGA if it continues with a better reference. 

Best wishes
Ollie
