### ISSUE TITLE
Quick docstring fix in Bio.Entrez.__init__.py

### ISSUE THREAD

**Issue by danielfrees** [biopython/biopython#4289]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.10.9 (main, Mar  8 2023, 04:44:36) [Clang 14.0.6 ]

CPython
macOS-10.16-x86_64-i386-64bit

1.78

### Expected behaviour

n/a

### Actual behaviour

There seems to be two errant lines (line 119 and 120) in the docstring for Bio.Entrez.__init__.py. Would suggest removing them for clarity!

### Steps to reproduce

n/a

**Comment by peterjc** [comment]
Please clarify, line 119 in Biopython 1.78 version is blank:

https://github.com/biopython/biopython/blob/biopython-178/Bio/Entrez/__init__.py#L119

Probably you mean the current file, which is as per Biopython 1.81:

https://github.com/biopython/biopython/blob/biopython-181/Bio/Entrez/__init__.py#L119

Those lines are the output of the example preceeding it:

```
          >>> handle = Entrez.esummary(db="pubmed", id="19304878,14630660", retmode="xml")
          >>> records = Entrez.parse(handle)
          >>> for record in records:
          ...     # each record is a Python dictionary or list.
          ...     print(record['Title'])
          Biopython: freely available Python tools for computational molecular biology and bioinformatics.
          PDB file parser and structure class implemented in Python.
          >>> handle.close()
```

This style is known as a doctest and is common in Python docstrings - we actually run these examples as part of our testing.

**Comment by danielfrees** [comment]
Hi Peter,Apologies, you are absolutely right. Had a brain fart reading the doctest. Please disregard.Have a nice evening!DanielSent from my iPhoneOn Apr 25, 2023, at 4:49 PM, Peter Cock ***@***.***> wrote:﻿
Please clarify, line 119 in Biopython 1.78 version is blank:
https://github.com/biopython/biopython/blob/biopython-178/Bio/Entrez/__init__.py#L119
Probably you mean the current file, which is as per Biopython 1.81:
https://github.com/biopython/biopython/blob/biopython-181/Bio/Entrez/__init__.py#L119
Those lines are the output of the example preceeding it:
          >>> handle = Entrez.esummary(db="pubmed", id="19304878,14630660", retmode="xml")
          >>> records = Entrez.parse(handle)
          >>> for record in records:
          ...     # each record is a Python dictionary or list.
          ...     print(record['Title'])
          Biopython: freely available Python tools for computational molecular biology and bioinformatics.
          PDB file parser and structure class implemented in Python.
          >>> handle.close()

This style is known as a doctest and is common in Python docstrings - we actually run these examples as part of our testing.

**Comment by peterjc** [comment]
No problem, it does look out of place to anyone not familiar with doctests. Thanks for confirming.
