### ISSUE TITLE
Please don't deprecate Bio.pairwise2

### ISSUE THREAD

**Issue by Pita** [biopython/biopython#4290]
Hello bio python people,

Thank you so much for this module! It's really great and has helped us a lot. My issue is the following, I keep getting the message:

```
Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
```

We've tried to replace it with `Bio.Align.PairwiseAligner`. But this one does not give us replacement values. For our use case, we need to know what was instead of the expected symbol. `Bio.Align.PairwiseAligner` does not seem to give us this information. 

Thank you!

**Comment by peterjc** [comment]
I don't understand what you mean by replacement values or expected symbols. Could you give a small example?

**Comment by Pita** [comment]
Let's assume there is two sequences

1) ATDA
2) AHDA

Bio.pairwise2 would create something like:

["A", "T", "D", "A"]
["A", "H", "D", "A"]

It's easy to tell that T was replaced with H. Our use case is not DNA, but something else, which I'm happy to tell you in a DM if you want. But for our use its very important to know what came instead.

**Comment by MarkusPiotrowski** [comment]
I guess you supply the "sequences' as lists in this case. If I'm not mistaken, you can also do this with `PairwiseAligner`, but @mdehoon is the better person to comment on this.

**Comment by MarkusPiotrowski** [comment]
He had a similar discussion before, here's the topic and a workaround: https://github.com/biopython/biopython/issues/4186#issue-1471436217

**Comment by Pita** [comment]
@MarkusPiotrowski That looks interesting, will try, thank you!

**Comment by Pita** [comment]
I it possible to have a `match_fn` or some other way of telling it that two symbols are identical?

**Comment by mdehoon** [comment]
Yes:
```python
from Bio.Align import PairwiseAligner
from Bio.Align.substitution_matrices import Array

alphabet = ("a", "b", "h", "m", "n", "s")
aligner = PairwiseAligner()
aligner.alphabet = alphabet
aligner.gap_score = -1

a = Array(alphabet, dims=2)
for c1 in alphabet:
    for c2 in alphabet:
        if c1 == c2:
            a[c1, c2] = 1.0
        else:
            a[c1, c2] = 0.0

print(a)
```

```
    a   b   h   m   n   s
a 1.0 0.0 0.0 0.0 0.0 0.0
b 0.0 1.0 0.0 0.0 0.0 0.0
h 0.0 0.0 1.0 0.0 0.0 0.0
m 0.0 0.0 0.0 1.0 0.0 0.0
n 0.0 0.0 0.0 0.0 1.0 0.0
s 0.0 0.0 0.0 0.0 0.0 1.0
```

```python
aligner.substitution_matrix = a

word_1 = ['b', 'a', 'n', 'a', 'n', 'a', 's']
word_2 = ['b', 'a', 'h', 'a', 'm', 'a', 's']

alignments = aligner.align(word_1, word_2)
print(alignments[0])
```

```
b a n a n a s
| | . | . | |
b a h a m a s
```

```python
a['n', 'm'] = -1000
a['m', 'n'] = -1000

print(a)
```

```
    a   b   h       m       n   s
a 1.0 0.0 0.0     0.0     0.0 0.0
b 0.0 1.0 0.0     0.0     0.0 0.0
h 0.0 0.0 1.0     0.0     0.0 0.0
m 0.0 0.0 0.0     1.0 -1000.0 0.0
n 0.0 0.0 0.0 -1000.0     1.0 0.0
s 0.0 0.0 0.0     0.0     0.0 1.0

```

```python
alignments = aligner.align(word_1, word_2)
print(alignments[0])
```

```
b a n a n - a s
| | . | - - | |
b a h a - m a s
```

**Comment by peterjc** [comment]
It sounds like the concerns here were met, so I'm closing this issue now.

(Feel free to reopen it if I misunderstood)

**Comment by mdehoon** [comment]
@Pita 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
