### ISSUE TITLE
SeqIO pdb-atom parsing sometimes adds AAs to end of structure sequences that are not there

### ISSUE THREAD

**Issue by Jeff-LaFrence** [biopython/biopython#4297]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
'3.10.9 (main, Dec  7 2022, 01:12:00) [GCC 9.4.0]'
import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
import Bio; print(Bio.__version__)
1.81
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
sequence from pdb-seqres has same characters or less than pdb-atom parsing ie. for pdb 1G55
header sequence: EPLRVLELYSGVGGMHHALRESCIPAQVVAAIDVNTVANEVYKYNFPHTQLLAKTIEGITLEEFDRLSFDMILMSPPCQPFTRIGRQGDMTDSRTNSFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQEFLLSPTSLGIPNSRLRYFLIAKLQSEPLPFQAPGQVLMEFPKIEIHRKNQQDSDLSVKMLKDFLEDDTDVNQYLLPPKSLLRYALLLDIVQPTCRRSVCFTKGYGSYIEGTGSVLQTAEDVQVENIYKSLTNLSQEEQITKLLILKLRYFTPKEIANLLGFPPEFGFPEKITVKQRYRLLGNSLNVHVVAKLIKILYE
should yield structure sequence:
EPLRVLELYSGVGGMHHALRESCIPAQVVAAIDVNTVANEVYKYNFPHTQLLAKTIEGITLEEFDRLSFDMILMSPPNSFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQEFLLSPTSLGIPNSRLRYFLIAKLQSEPLPFQAPGQVLMEFPKLSVKMLKDFLEDDTDVNQYLLPPKSLLRYALLLDIVQPTCRRSVCFTKGYGSYIEGTGSVLQTAEDVQVENIYKSLTNLSQEEQITKLLILKLRYFTPKEIANLLGFPPEFGFPEKITVKQRYRLLGNSLNVHVVAKLIKILYE
(*Please fill this in*)

### Actual behaviour
an extra C is added to the end yielding:
EPLRVLELYSGVGGMHHALRESCIPAQVVAAIDVNTVANEVYKYNFPHTQLLAKTIEGITLEEFDRLSFDMILMSPPNSFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQEFLLSPTSLGIPNSRLRYFLIAKLQSEPLPFQAPGQVLMEFPKLSVKMLKDFLEDDTDVNQYLLPPKSLLRYALLLDIVQPTCRRSVCFTKGYGSYIEGTGSVLQTAEDVQVENIYKSLTNLSQEEQITKLLILKLRYFTPKEIANLLGFPPEFGFPEKITVKQRYRLLGNSLNVHVVAKLIKILYEC

I have noticed that it does this with other structures as well, adding characters to the end of that are not actually in the structure or header sequence. It'll take a bit of digging but I think I can find a few more if needed.
(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce
    local_file_path_base = <where you put your pdbs>
    pdb = '1G55'
    chain = 'A'
    query_chain_id = f"{pdb}:{chain}"
    chain_header_seq = {record.id: record.seq for record in SeqIO.parse(f"{local_file_path_base}/{pdb}.pdb", "pdb-atom")}
    header_seq = str(chain_header_seq[query_chain_id])
    print(header_seq)
(*Please fill this in *)

**Comment by peterjc** [comment]
https://files.rcsb.org/view/1G55.pdb has just this for SEQRES lines (Chain A only):

```
SEQRES   1 A  343  GLU PRO LEU ARG VAL LEU GLU LEU TYR SER GLY VAL GLY          
SEQRES   2 A  343  GLY MET HIS HIS ALA LEU ARG GLU SER CYS ILE PRO ALA          
SEQRES   3 A  343  GLN VAL VAL ALA ALA ILE ASP VAL ASN THR VAL ALA ASN          
SEQRES   4 A  343  GLU VAL TYR LYS TYR ASN PHE PRO HIS THR GLN LEU LEU          
SEQRES   5 A  343  ALA LYS THR ILE GLU GLY ILE THR LEU GLU GLU PHE ASP          
SEQRES   6 A  343  ARG LEU SER PHE ASP MET ILE LEU MET SER PRO PRO CYS          
SEQRES   7 A  343  GLN PRO PHE THR ARG ILE GLY ARG GLN GLY ASP MET THR          
SEQRES   8 A  343  ASP SER ARG THR ASN SER PHE LEU HIS ILE LEU ASP ILE          
SEQRES   9 A  343  LEU PRO ARG LEU GLN LYS LEU PRO LYS TYR ILE LEU LEU          
SEQRES  10 A  343  GLU ASN VAL LYS GLY PHE GLU VAL SER SER THR ARG ASP          
SEQRES  11 A  343  LEU LEU ILE GLN THR ILE GLU ASN CSO GLY PHE GLN TYR          
SEQRES  12 A  343  GLN GLU PHE LEU LEU SER PRO THR SER LEU GLY ILE PRO          
SEQRES  13 A  343  ASN SER ARG LEU ARG TYR PHE LEU ILE ALA LYS LEU GLN          
SEQRES  14 A  343  SER GLU PRO LEU PRO PHE GLN ALA PRO GLY GLN VAL LEU          
SEQRES  15 A  343  MET GLU PHE PRO LYS ILE GLU ILE HIS ARG LYS ASN GLN          
SEQRES  16 A  343  GLN ASP SER ASP LEU SER VAL LYS MET LEU LYS ASP PHE          
SEQRES  17 A  343  LEU GLU ASP ASP THR ASP VAL ASN GLN TYR LEU LEU PRO          
SEQRES  18 A  343  PRO LYS SER LEU LEU ARG TYR ALA LEU LEU LEU ASP ILE          
SEQRES  19 A  343  VAL GLN PRO THR CSO ARG ARG SER VAL CYS PHE THR LYS          
SEQRES  20 A  343  GLY TYR GLY SER TYR ILE GLU GLY THR GLY SER VAL LEU          
SEQRES  21 A  343  GLN THR ALA GLU ASP VAL GLN VAL GLU ASN ILE TYR LYS          
SEQRES  22 A  343  SER LEU THR ASN LEU SER GLN GLU GLU GLN ILE THR LYS          
SEQRES  23 A  343  LEU LEU ILE LEU LYS LEU ARG TYR PHE THR PRO LYS GLU          
SEQRES  24 A  343  ILE ALA ASN LEU LEU GLY PHE PRO PRO GLU PHE GLY PHE          
SEQRES  25 A  343  PRO GLU LYS ILE THR VAL LYS GLN ARG TYR ARG LEU LEU          
SEQRES  26 A  343  GLY ASN SER LEU ASN VAL HIS VAL VAL ALA LYS LEU ILE          
SEQRES  27 A  343  LYS ILE LEU TYR GLU  
```

You example code outputs the expected value ending ``...LYE`` (for Leu, Tyr, Gly):

```
EPLRVLELYSGVGGMHHALRESCIPAQVVAAIDVNTVANEVYKYNFPHTQLLAKTIEGITLEEFDRLSFDMILMSPPCQPFTRIGRQGDMTDSRTNSFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQEFLLSPTSLGIPNSRLRYFLIAKLQSEPLPFQAPGQVLMEFPKIEIHRKNQQDSDLSVKMLKDFLEDDTDVNQYLLPPKSLLRYALLLDIVQPTCRRSVCFTKGYGSYIEGTGSVLQTAEDVQVENIYKSLTNLSQEEQITKLLILKLRYFTPKEIANLLGFPPEFGFPEKITVKQRYRLLGNSLNVHVVAKLIKILYE
```

This simplified example also works fine for me:

```
$ python -c "from Bio import SeqIO; print(SeqIO.read('1G55.pdb', 'pdb-seqres').seq)"
EPLRVLELYSGVGGMHHALRESCIPAQVVAAIDVNTVANEVYKYNFPHTQLLAKTIEGITLEEFDRLSFDMILMSPPCQPFTRIGRQGDMTDSRTNSFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQEFLLSPTSLGIPNSRLRYFLIAKLQSEPLPFQAPGQVLMEFPKIEIHRKNQQDSDLSVKMLKDFLEDDTDVNQYLLPPKSLLRYALLLDIVQPTCRRSVCFTKGYGSYIEGTGSVLQTAEDVQVENIYKSLTNLSQEEQITKLLILKLRYFTPKEIANLLGFPPEFGFPEKITVKQRYRLLGNSLNVHVVAKLIKILYE
```

I am running the very latest Biopython from GitHub, but I don't think that anything relevant changed. My guess is that there is something amiss with your PDB file?

**Comment by peterjc** [comment]
Ah, now that makes more sense. The SEQRES parser is very simply reporting on those specific lines in the header - not much can go wrong. The ATOM based parser looks at the coordinates etc and could be confused by non amino-acids which are part of the chain.

Now I see an extra C, but also a run of X in the middle too:

```
$ python -c "from Bio import SeqIO; print(SeqIO.read('1G55.pdb', 'pdb-atom').seq)"
EPLRVLELYSGVGGMHHALRESCIPAQVVAAIDVNTVANEVYKYNFPHTQLLAKTIEGITLEEFDRLSFDMILMSPPXXXXXXXXXXXXXXXXXXNSFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQEFLLSPTSLGIPNSRLRYFLIAKLQSEPLPFQAPGQVLMEFPKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXLSVKMLKDFLEDDTDVNQYLLPPKSLLRYALLLDIVQPTCRRSVCFTKGYGSYIEGTGSVLQTAEDVQVENIYKSLTNLSQEEQITKLLILKLRYFTPKEIANLLGFPPEFGFPEKITVKQRYRLLGNSLNVHVVAKLIKILYEC
```

CC @JoaoRodrigues

**Comment by JoaoRodrigues** [comment]
I was following this thread, but thanks for the mention Peter!

I think you're right, there's a difference between seqres (what construct
people put in the tube) vs atom (what people actually see in the density).
The atom sequence should have less aminoacids, but extra Xs (water,
additives, etc).

A segunda, 8/05/2023, 13:10, Peter Cock ***@***.***> escreveu:

**Comment by JoaoRodrigues** [comment]
The trailing C in the sequence is a modified cysteine ligand (resn SAH,
maps to C).

A segunda, 8/05/2023, 21:48, João Rodrigues ***@***.***>
escreveu:

**Comment by peterjc** [comment]
So is this working as intended?

**Comment by Jeff-LaFrence** [comment]
hmm, using X to represent both missing residues and ligands makes it a bit difficult to use for protein informatics. Unfortunately, authors indexes aren't really standardized either, quite often leading to those large gaps of X's in peterjc's output. To me at least the output can feel a bit raw still. 

Joao, you're right, most solutions I can think of are quite tricky/fallible as well. The best approach I can think of is to do an alignment with pdb-atom and pdb-seqres to determine the gaps and drop any residues that don't align from the actual structure as they are likely ligands. That or some other method of referencing back to the seqres is likely the most accurate representation of what protein residues are actually in the structure. If this is something that is actually desired by the community I'd be happy to look into it.
