### ISSUE TITLE
Release 1.82

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#4312]
Let's use this thread to track issues that should be included in the upcoming 1.82 release. Link this thread on those issues.

@peterjc @mdehoon

**Comment by mdehoon** [comment]
@JoaoRodrigues  Thank you!

**Comment by peterjc** [comment]
PR #4316 looks ready to merge and close #4314.

Nothing else was flagged as worth holding off the release for, was it? But perhaps we'll have some more suggestions this weekend at the BOSC 2023 CoFest...

**Comment by peterjc** [comment]
I don't think we have any outstanding issues or pull requests blocking the release.

I know @mdehoon has some on going Tutorial work for the alignment documention, but I don't think that need hold back the release. Likewise my work on LaTeX to RST is not ready yet either.

**Comment by peterjc** [comment]
Currently ``test_motifs_online.py`` is failing as the certificate for weblogo.threeplusone.com expired on 25/06/2023. See https://github.com/WebLogo/weblogo/issues/162

**Comment by mdehoon** [comment]
See also #3478 - Bio.codonalign may have a license problem.

**Comment by peterjc** [comment]
I think I can do the release tomorrow - expecting a quiet day before work closes for Christmas/New Year.

**Comment by peterjc** [comment]
Closed as of 2204ad0b0f92c4b8ed769ce4c1a8a3987b048c6f

**Comment by mdehoon** [comment]
@peterjc  Thanks! Great to see this release out.
