### ISSUE TITLE
Coordinates update after setting chi angle on aromatic residue doesn't work for the whole ring

### ISSUE THREAD

**Issue by niccolo93** [biopython/biopython#4318]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
CPython
Linux-5.19.0-43-generic-x86_64-with-glibc2.35
1.81

### Expected behaviour

If you try to set a new chi angle on an aromatic residue, i.e. Histidine, chi2 I would expect that all atoms coordinates involved in the ring are updated accordingly to the new chi angle. 

### Actual behaviour

Just the coordinates of the atoms involved in the chi angle are updated, causing the ring to collapse or losing its aromatic structure.

### Steps to reproduce

```
def apply_transformation(residue, chain, transformation):
            angle = "chi" + str(2)

           # Set the new angle
            residue.internal_coord.set_angle(angle, transformation)

            # Update coordinates
            chain.internal_to_atom_coordinates(verbose=True)
    return residue
```

https://github.com/biopython/biopython/assets/25704885/3fd14d62-6629-4ff8-8577-491d361cadd3

**Comment by niccolo93** [comment]
After few more checks it looks like the bug it's not limited to aromatic residues, but to every kind of residue. 
Attached a PDB file example of VAL.

[VAL.zip](https://github.com/biopython/biopython/files/11630936/VAL.zip)

**Comment by niccolo93** [comment]
After reading carefully the` internal_coords.py` code I found that the function that I should use to change a chi angle and update its coordinates for all the neighbours too is the `bond_set()`. 
I was misled by the documentation.

Thank you

**Comment by peterjc** [comment]
If you can suggest changes to the documentation to clarify this point, that'd be welcome. Thanks.

**Comment by rob-miller** [comment]
This doesn’t seem right, but even as a documentation error it is still an issue. I shall investigate, please reopen.

**Comment by niccolo93** [comment]
Reopening for further investigation

**Comment by rob-miller** [comment]
Just to update, yes I can reproduce your findings.  Well done reviewing the code and finding `bond_rotate()` and `bond_set()`, what you have done is indeed the correct workaround for sidechains at this time.  

The part that's not right is that `set_angle()` should work as described, suggesting a bug in a routine called `propagate_changes()` that I've not looked at yet. `propagate_changes()` is what makes it possible to `set_angle("psi", val)` and have the rest of the backbone make sense.  

Thank you for finding and reporting the problem.

**Comment by rob-miller** [comment]
Mea culpa.  There was nothing wrong with `propagate_changes()`, the issue was entirely my poorly designed user interface (as pointed out by @niccolo93) and incomplete testing.  Thank you for highlighting with fresh eyes.
