### ISSUE TITLE
Bio.exPASy.cellosaurus.parse misses some keys

### ISSUE THREAD

**Issue by yoonkihoon** [biopython/biopython#4323]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
Python 3.9.16 (main, Mar  8 2023, 04:29:44) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.9.16 (main, Mar  8 2023, 04:29:44) 
[Clang 14.0.6 ]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-10.16-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.81
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
Bio.exPASy.cellosaurus.parse returns a dict containing all the key/value pairs from [cellosaurus.txt](https://ftp.expasy.org/databases/cellosaurus/cellosaurus.txt) file. And, the text file lists the key at the beginning of the file as follow.
---------  ---------------------------     ----------------------
 Line code  Content                         Occurrence in an entry
 ---------  ---------------------------     ----------------------
 ID         Identifier (cell line name)     Once; starts an entry
 AC         Accession (CVCL_xxxx)           Once
 AS         Secondary accession number(s)   Optional; once
 SY         Synonyms                        Optional; once
 DR         Cross-references                Optional; once or more
 RX         References identifiers          Optional: once or more
 WW         Web pages                       Optional; once or more
 CC         Comments                        Optional; once or more
 ST         STR profile data                Optional; twice or more
 DI         Diseases                        Optional; once or more
 OX         Species of origin               Once or more
 HI         Hierarchy                       Optional; once or more
 OI         Originate from same individual  Optional; once or more
 SX         Sex of cell                     Optional; once
 AG         Age of donor at sampling        Optional; once
 CA         Category                        Once
 DT         Date (entry history)            Once
 //         Terminator                      Once; ends an entry

### Actual behaviour

But, actual implementation misses to parse out AG and DT.
    def __init__(self):
        """Initialize the class."""
        dict.__init__(self)
        self["ID"] = ""
        self["AC"] = ""
        self["AS"] = ""
        self["SY"] = ""
        self["DR"] = []
        self["RX"] = []
        self["WW"] = []
        self["CC"] = []
        self["ST"] = []
        self["DI"] = []
        self["OX"] = []
        self["HI"] = []
        self["OI"] = []
        self["SX"] = ""
        self["CA"] = ""

### Steps to reproduce

Well, missing keys are pretty obvious. And, Age and Date wasn't returned from parse.

**Comment by peterjc** [comment]
Reading the docstring and code in https://github.com/biopython/biopython/blob/master/Bio/ExPASy/cellosaurus.py when that was written the AG and DT lines did not exist.

It looks like it would be fairly simple to update this - would you like to make a pull request?

Also, if you are familiar with cellosaurus you can probably find an announcement from when this was changed (and see if anything else needs updating).

**Comment by yoonkihoon** [comment]
Sure. I will make a pull request. But, I don't expect I can find when it was changed.

**Comment by JudithBernett** [comment]
I have the same issue - why was this pull request not merged? :) https://github.com/biopython/biopython/pull/4452
