### ISSUE TITLE
SeqIO.index raises an error with `Path` objects as the *filename* argument

### ISSUE THREAD

**Issue by MordorianGuy** [biopython/biopython#4325]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:50:54) [MSC v.1934 64 bit (AMD64)]
CPython
Windows-10-10.0.19045-SP0
1.81

### Expected behaviour

Like `SeqIO.parse`, `.read`, & `.write`, to take `Path`-objects of `pathlib` as the *filename* argument.

### Actual behaviour

It checks *filename* for the `str` instantiation.

### Steps to reproduce

`SeqIO.index(Path("seqs.fas"), "fasta")`

**Comment by peterjc** [comment]
This seems a sensible extension to the code - do you feel up to submitting
a pull request? It wouldn’t need many additional unit tests, maybe just one
or two would be fine.

Peter
