### ISSUE TITLE
Multiple sequence alignments in A3M format

### ISSUE THREAD

**Issue by fmarotta** [biopython/biopython#4329]
### Setup

I am reporting a feature request with Biopython version, Python version, and operating
system as follows:

```
$ python
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-6.3.5-arch1-1-x86_64-with-glibc2.37
>>> import Bio; print(Bio.__version__)
1.81
```

### Parsing A3M alignments

It seems that Bio.AlignIO cannot read alignments in the A2M/A3M format (described [here](https://en.wikipedia.org/wiki/FASTA_format#Extensions:~:text=A2M/A3M%20are,discarded.%5B17%5D)), or am I missing something? I could try to prepare a pull request, if there is interest.

**Comment by mdehoon** [comment]
There is a parser for a2m files in `Bio/AlignIO` (creating a `MultipleSeqAlignment` object) and a newer parser in `Bio.Align` (creating an `Alignment` object).

**Comment by mdehoon** [comment]
@fmarotta  Can we close this issue?
