### ISSUE TITLE
CodonAdaptationIndex : why subtract 1.0

### ISSUE THREAD

**Issue by Hunter-Leo** [biopython/biopython#4337]
Hei, there. Why subtract 1.0 in the end of returning? There is no clues show in the paper.    
`def cai_for_gene(self, dna_sequence):
        """Calculate the CAI (float) for the provided DNA sequence (string).

        This method uses the Index (either the one you set or the one you
        generated) and returns the CAI for the DNA sequence.
        """
        cai_value, cai_length = 0, 0

        # if no index is set or generated, the default SharpEcoliIndex will
        # be used.
        if self.index == {}:
            self.set_cai_index(SharpEcoliIndex)

        dna_sequence = dna_sequence.upper()

        for i in range(0, len(dna_sequence), 3):
            codon = dna_sequence[i : i + 3]
            if codon in self.index:
                # these two codons are always one, exclude them:
                if codon not in ["ATG", "TGG"]:
                    cai_value += math.log(self.index[codon])
                    cai_length += 1
            # some indices may not include stop codons:
            elif codon not in ["TGA", "TAA", "TAG"]:
                raise TypeError(f"illegal codon in sequence: {codon}.\n{self.index}")

        return math.exp(cai_value / (cai_length - 1.0))
`

**Comment by peterjc** [comment]
Which file and which version are you quoting?

https://github.com/biopython/biopython/blob/biopython-181/Bio/SeqUtils/__init__.py#L643 - no minus one

https://github.com/biopython/biopython/blob/biopython-181/Bio/SeqUtils/CodonUsage.py#L159 - with minus one, but deprecated

**Comment by Hunter-Leo** [comment]
> Which file and which version are you quoting?
> 
> https://github.com/biopython/biopython/blob/biopython-181/Bio/SeqUtils/__init__.py#L643 - no minus one
> 
> https://github.com/biopython/biopython/blob/biopython-181/Bio/SeqUtils/CodonUsage.py#L159 - with minus one, but deprecated

Thank U. I was using Bio/SeqUtils/CodonUsage module and not noticed the warning message.  I will change my code next.

**Comment by peterjc** [comment]
There's probably an old issue about that change, but I didn't find it with a quick search.
