### ISSUE TITLE
can i convert protein to DNA? someone who can tell how to do it ,thank you.

### ISSUE THREAD

**Issue by qiuqingpo** [biopython/biopython#4348]
I can use it to convert DNA to protein very easy, but the reverse translate is difficult.  can you tell me how to do it ,thank you

**Comment by MarkusPiotrowski** [comment]
You can't do this in a biological meaningful way. Several codons encode the same amino acid. Of course, you can somehow back-translate a protein sequence to some DNA sequence, but it is highly unlikely that the resulting sequence does exist in real nature.
