### ISSUE TITLE
eread failure due to malformed NCBI output from elink

### ISSUE THREAD

**Issue by thedamlab** [biopython/biopython#4349]
NCBI is giving odd elink output for some protein accessions in the form of additional malformed <LinkSet> blocks that are missing elements. This causes Entrez.read to throw a ValueError exception. I would estimate about 20% of protein accessions have this issue. 

Here is an example of a problematic accession: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=protein&db=nuccore&id=WP_230077047.1

Is there any way to alter the input of Entrez.elink to suppress the malformed output from NCBI or otherwise suppress the ValueError and get the link data from the valid LinkSet blocks?

### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.8.13 (default, Nov  8 2022, 17:19:05)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
CPython
Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.2.5
1.81

### Expected behaviour

Return a list of link data, i.e.,:

[{'LinkSetDb': [{'Link': [{'Id': 'NZ_KB896151.1'}], 'DbTo': 'nuccore', 'LinkName': 'protein_nuccore'}, {'Link': [{'Id': 'NZ_KB896151.1'}], 'DbTo': 'nuccore', 'LinkName': 'protein_nuccore_wp'}], 'LinkSetDbHistory': [], 'ERROR': [], 'DbFrom': 'protein', 'IdList': ['WP_038840434.1']}]

### Actual behaviour

Dies with a ValueError exception due to malformed NCBI output

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    herp = Entrez.read(derp)
  File "/home/apps/python/lib64/python3.8/site-packages/Bio/Entrez/__init__.py", line 503, in read
    record = handler.read(handle)
  File "/home/apps/python/lib64/python3.8/site-packages/Bio/Entrez/Parser.py", line 392, in read
    self.parser.ParseFile(handle)
  File "/builddir/build/BUILD/Python-3.8.13/Modules/pyexpat.c", line 407, in StartElement
  File "/home/apps/python/lib64/python3.8/site-packages/Bio/Entrez/Parser.py", line 667, in startElementHandler
    parent.store(element)
  File "/home/apps/python/lib64/python3.8/site-packages/Bio/Entrez/Parser.py", line 196, in store
    raise ValueError("Unexpected item '%s' in dictionary" % key)
ValueError: Unexpected item 'Link' in dictionary

### Steps to reproduce

Try to perform an Entrez.read on one of these accessions that has the malformed output, e.g.:

test =  Entrez.elink(idtype='acc', dbfrom="protein", db="nuccore", id="WP_289277364.1")
Entrez.read(test)

Other accessions where this is an issue (all of them have that additional malformed LinkSet block): WP_249375263.1, WP_230077047.1, WP_253741979.1, WP_272254854.1

**Comment by peterjc** [comment]
Does adding ``validate=False`` to ``Entrez.read(...)`` help?

https://github.com/biopython/biopython/blob/biopython-181/Bio/Entrez/__init__.py#L458

**Comment by thedamlab** [comment]
> Does adding `validate=False` to `Entrez.read(...)` help?
> 
> https://github.com/biopython/biopython/blob/biopython-181/Bio/Entrez/__init__.py#L458

Thank you for your reply and suggestion. 

Unfortunately passing "validate = False" to Entrez.read results in the same ValueError exception. I also tried "ignore_errors = True" with and without "validate = False" since I noticed that in the code you linked me; no dice with that either. 

I'm pretty sure this is due to NCBI passing unexpected/bad output from their end on Entrez since I can't think of any sane use for that second <LinkSet> element and the fact that it only occurs on *some* protein accessions. So this may very well not be a BioPython problem but more NCBI confusing it (feel free to close if you agree).

I ended up working around it by passing the Entrez.elink to ElementTree and parsing the XML to grab the nuccore links (under ./LinkSet/LinkSetDb/Link/Id) which by necessity will ignore the odd extraneous output (by virtue of lacking the LinkSetDb element). That got us up and running again.

**Comment by peterjc** [comment]
Any ideas @mdehoon?

**Comment by mdehoon** [comment]
@peterjc  It's an NCBI issue.

The XML returned by elink contains this block:
```
  <LinkSet>
    <DbFrom>protein</DbFrom>

      <Link>
                                <Id>0</Id>
                        </Link>




  </LinkSet>
```
The header of the XML file refers to this DTD:
https://eutils.ncbi.nlm.nih.gov/eutils/dtd/20101123/elink.dtd

In this DTD, the `LinkSet` tag is defined as follows:
```
<!ELEMENT	LinkSet		(DbFrom, 
				((IdList?, ((ERROR?, LinkSetDb)*  |  (LinkSetDbHistory*, WebEnv))) | IdUrlList | IdCheckList | ERROR), ERROR?  
				)>

```

As it does not mention `Link` in this list, the `Link` block should never appear in a `LinkSet` block.

**Comment by thedamlab** [comment]
@mdehoon Thanks for confirming my suspicion that it's an NCBI issue. FWIW, I've reached out to them to let them know about this bad output. 

I'll go ahead and close this. Thanks again for the help and have a good weekend.

**Comment by thedamlab** [comment]
I wanted to follow up and let BioPython know that the NCBI HelpDesk confirmed that ELink is giving unexpected output not compliant with the published DTD. They forwarded the issue to their development team so hopefully they'll get this fixed at some point
