### ISSUE TITLE
RETMAX not working for pubmed

### ISSUE THREAD

**Issue by fransiss** [biopython/biopython#4353]
Hello 
I am trying to look up all the pubmed IDs for a specific query 

for example: I need all the paper on Alzheimer's and age

My code is:

from Bio import Entrez
string='(age[Title/Abstract] AND Alzheimer[Title/Abstract])'
handle = Entrez.esearch(db='pubmed',
                                term=string,
                                retmax=1000000)

record = Entrez.read(handle)
id_list = record['IdList']
num_article=record['Count']

the number of article is correct -36935 
but the id_list is limited to 9999 ids even id the retmax=1000000 is more 

anyone can help?
thanks

**Comment by peterjc** [comment]
This is an NCBI limitation - you will have to download the results in batches. There is an example in our Tutorial which should help...

**Comment by fransiss** [comment]
Hi 

i tried to follow the tutorial and do it in batches.
However also restart cannot be larger than 9998, I don t know how to solve the problem

string='(age[Title/Abstract] AND Alzheimer[Title/Abstract])'
handle = Entrez.esearch(db='pubmed',
                                term=string,
                                retmax='1000000')
    record = Entrez.read(handle)
    id_list = list(set(record['IdList']))
    num_art = int(record["Count"])
    
    batch_size = 9998
    ids_all_ff=[]
    for start in range(0, num_art, batch_size):
        end = min(num_art, start + batch_size)
        print("Going to download record %i to %i" % (start + 1, end))
        fetch_handle = Entrez.esearch(db='pubmed',
            term=string,
            retstart=start,
            retmax=batch_size
        )
        record = Entrez.read(fetch_handle)
        id_list = list(set(record['IdList']))
        fetch_handle.close()


this is the error I get

RuntimeError: Search Backend failed: Exception:
'retstart' cannot be larger than 9998. For PubMed, ESearch can only retrieve the first 9,999 records matching the query. To obtain more than 9,999 PubMed records, consider using EDirect that contains additional logic to batch PubMed search results automatically so that an arbitrary number can be retrieved. For details see https://www.ncbi.nlm.nih.gov/books/NBK25499/

**Comment by peterjc** [comment]
That's unfortunate - so the NCBI won't allow this via the Entrez API which is what Biopython is using. At least they offer an alternative (EDirect).

As a workaround, I would split the search - for example by date. You could try pre-2000, 2000-2010, 2010-2020, and post-2020 perhaps (or smaller windows if there are still too many results).

**Comment by fransiss** [comment]
Thanks!!! that worked

**Comment by peterjc** [comment]
Great. Can we close this issue as resolved then?
