### ISSUE TITLE
Bugs in Phylo tutorial

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#439]
Just for reference a few bugs that I have found on the Phylo tutorial

There are 3 problems, note that the data directories might be slightly changed

Problem 1:
On Python 2 this is failing:

trees = Phylo.parse("data/phyloxml_examples.xml", "phyloxml")
trees = list(trees)
for tree in trees:
    print(tree)

With:

Bio/Phylo/BaseTree.pyc in print_tree(obj, indent)
    953             This closes over textlines and modifies it in-place.
    954             """
--> 955             textlines.append(TAB * indent + repr(obj))  
    956             indent += 1
    957             for attr in obj.__dict__:

UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in
position 24: ordinal not in range(128)

This works on Python 3! But see problem 3 below

Problem 2:

On Python 3 this dialect does not work

trees = list(Phylo.parse("../../Tests/PhyloXML/phyloxml_examples.xml",
"phyl oxml"))
>>> tree1 = trees[0]
>>> others = trees[1:]  

(trees is a generator). There are different solutions here (like doing
trees=list(trees))
A trivial one

Problem 3:

While the code of problem 1 works on Python 3, the bit after does not
(I do not know with Python 2):

Phylo.write(tree1, "data/tree1.xml", "phyloxml")

Error:

Bio/Phylo/PhyloXMLIO.py in write(self, file, encoding, indent)
    675         if indent:
    676             _indent(self._tree.getroot())
--> 677         self._tree.write(file, encoding)  
    678         return len(self._tree.getroot())

TypeError: must be str, not bytes

Maybe putting all this on automated docstring test would be a good idea...

**Comment by vincentdavis** [comment]
I think all these issues are fixed?

**Comment by peterjc** [comment]
Good - thanks for checking @vincentdavis, let's close this issue then. Thanks @etal for the fixes & @tiagoantao for reporting them.

See also current conversation http://lists.open-bio.org/pipermail/biopython-dev/2015-December/021209.html about other problems in the Tutorial examples.
