### ISSUE TITLE
resolution of 5vrf.cif does not get correctly parsed

### ISSUE THREAD

**Issue by phonez** [biopython/biopython#4397]
### Setup

I am reporting a problem with Biopython 1.81, Python 3.9.16, and Ubuntu 18.04.6 as follows:

```python
Python 3.9.16 (main, May 15 2023, 23:46:34) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.9.16 (main, May 15 2023, 23:46:34) 
[GCC 11.2.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.3.0-47-generic-x86_64-with-glibc2.27
>>> import Bio; print(Bio.__version__)
1.81
```

### Expected behaviour
```python
structure = MMCIFParser(QUIET=True).get_structure('5vrf', '5vrf.cif')
print(structure.header['resolution'])
```
Expected output is 4.1, which is recorded in line 6275 in 5vrf.cif ("_em_3d_reconstruction.resolution                  4.1").

### Actual behaviour
Actual output is None. Probably the resolution is masked by line 609 ("_refine.ls_d_res_high                            . "), as [adam-kral](https://github.com/adam-kral) mentioned in https://github.com/biopython/biopython/pull/3229.

### Steps to reproduce

```python
# download 5vrf.cif, and run:
structure = MMCIFParser(QUIET=True).get_structure('5vrf', '5vrf.cif')
print(structure.header['resolution'])
```

**Comment by peterjc** [comment]
@rob-miller Does this look like something you'd like to work on?

**Comment by rob-miller** [comment]
Yes I will have a play
