### ISSUE TITLE
Open Issues Amount

### ISSUE THREAD

**Issue by valentin994** [biopython/biopython#4398]
When going through the open issues there are a bunch of them open that could be closed, and inactive ones. Maybe having a bot closing them after X amount of inactivity.

It would help greatly in searching for issues where someone could help, and there is a lot of questions like how to do X which shouldn't be an issue to begin with as it is not connected to biopython.

**Comment by peterjc** [comment]
If you would like to triage those, and comment on any which you think can be closed, I or others could do that. That'd be very helpful thank you.

**Comment by valentin994** [comment]
I could go through some, do you want me to tag you on those I comment or should I just comment?

**Comment by peterjc** [comment]
Either should work, but I'm happy for you to tag me explicitly.

**Comment by valentin994** [comment]
Okay, and as for the automation of stale ones we could implement something like 
https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues
