### ISSUE TITLE
Pairwise Alignment - support for substitution matrices with elements of differing lengths?

### ISSUE THREAD

**Issue by trenslow** [biopython/biopython#4429]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
CPython
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
1.81

### Expected behaviour

I would expect when doing pairwise alignment, I can define a substitution matrix using elements with different lengths.

### Actual behaviour

I get inconsistent behavior, so I'm unsure if this is a bug, or if there's no support for alphabets with varying length elements. See example below.

### Steps to reproduce

If I define an alphabet like so: 

```python
from Bio.Align import PairwiseAligner, substitution_matrices
alph = ('XY', 'YZ', 'ZX', 'X')
aligner = PairwiseAligner()
distances = {}
for char1 in alph:
    for char2 in alph:
        distances[(char1, char2)] = substitution_quantifier(char1, char2)
aligner.substitution_matrix = substitution_matrices.Array(data=distances)
```
I get the following error: `ValueError: alphabet contains 'X' more than once`

whereas if I sort the alphabet to have the longer elements last: 

```python
from Bio.Align import PairwiseAligner, substitution_matrices
alph = ('X', 'XY', 'YZ', 'ZX')
aligner = PairwiseAligner()
distances = {}
for char1 in alph:
    for char2 in alph:
        distances[(char1, char2)] = substitution_quantifier(char1, char2)
aligner.substitution_matrix = substitution_matrices.Array(data=distances)
````

I get no error and can do alignment.

Is this supported? If so, what's the safest way to define substitution matrices for pairwise alignment when the alphabet elements are of varying lengths?

**Comment by peterjc** [comment]
This looks similar to #4186
