### ISSUE TITLE
Align.PairwiseAligner produces nonsensical scores/alignments with custom substitution matrix

### ISSUE THREAD

**Issue by RaverJay** [biopython/biopython#4434]
Hi,

I try to build a custom substitution_matrix to score RNA complementarity by local alignments,
i.e. AU, GC and GU pairs score positive, all others and gaps score negative

```
Substitution matrix:
     A    T    G    C
A -7.0  4.0 -7.0 -7.0
T  4.0 -7.0  1.0 -7.0
G -7.0  1.0 -7.0  5.0
C -7.0 -7.0  5.0 -7.0
```

### Setup

Python
3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]

Biopython
1.81

Platform
CPython

### Actual behaviour

I get random alignments with insanely high scores:

```
target            0 CC--GGTT 6
                  0 ..--.... 8
query             0 GGCCCAAA 8

2.126370191119337e+248
target            0 CC-GGTT- 6
                  0 ..-....- 8
query             0 GGCCCAAA 8

2.126370191119337e+248
```

### Steps to reproduce

```python
from Bio import Align

# make matrix
alphabet = ('A', 'T', 'G', 'C')

score_mismatch = -7
score_AU = 4
score_GU = 1
score_GC = 5
score_gapopen = -8
score_gapextend = -3

subs_matrix = np.full((4, 4), score_mismatch)
subs_matrix[0,1] = subs_matrix[1,0] = score_AU
subs_matrix[1,2] = subs_matrix[2,1] = score_GU
subs_matrix[2,3] = subs_matrix[3,2] = score_GC

subs_matrix = Align.substitution_matrices.Array(alphabet, data=subs_matrix)
print('Substitution matrix:')
print(subs_matrix)


# make aligner
aligner = Align.PairwiseAligner(mode='global',
                                open_gap_score=score_gapopen,
                                extend_gap_score=score_gapextend)
aligner.substitution_matrix = subs_matrix
print(aligner)

for aln in aligner.align('CCGGTT', 'GGCCCAAA'):
    print(aln)
    print(aln.score)

```

**Comment by mdehoon** [comment]
The current code in master seems to work fine:
```python
>>> import Bio
>>> Bio.__version__
'1.82.dev0'

>>> import numpy as np
>>> from Bio import Align
>>> 
>>> # make matrix
>>> alphabet = ('A', 'T', 'G', 'C')
>>> 
>>> score_mismatch = -7
>>> score_AU = 4
>>> score_GU = 1
>>> score_GC = 5
>>> score_gapopen = -8
>>> score_gapextend = -3
>>> 
>>> subs_matrix = np.full((4, 4), score_mismatch)
>>> subs_matrix[0,1] = subs_matrix[1,0] = score_AU
>>> subs_matrix[1,2] = subs_matrix[2,1] = score_GU
>>> subs_matrix[2,3] = subs_matrix[3,2] = score_GC
>>> subs_matrix = Align.substitution_matrices.Array(alphabet, data=subs_matrix)
>>> print('Substitution matrix:')
Substitution matrix:
>>> print(subs_matrix)
     A    T    G    C
A -7.0  4.0 -7.0 -7.0
T  4.0 -7.0  1.0 -7.0
G -7.0  1.0 -7.0  5.0
C -7.0 -7.0  5.0 -7.0

>>> aligner = Align.PairwiseAligner(mode='global',
...                                 open_gap_score=score_gapopen,
...                                 extend_gap_score=score_gapextend)
>>> aligner.substitution_matrix = subs_matrix
>>> print(aligner)
Pairwise sequence aligner with parameters
  substitution_matrix: <Array object at 0x10c3a47c0>
  target_internal_open_gap_score: -8.000000
  target_internal_extend_gap_score: -3.000000
  target_left_open_gap_score: -8.000000
  target_left_extend_gap_score: -3.000000
  target_right_open_gap_score: -8.000000
  target_right_extend_gap_score: -3.000000
  query_internal_open_gap_score: -8.000000
  query_internal_extend_gap_score: -3.000000
  query_left_open_gap_score: -8.000000
  query_left_extend_gap_score: -3.000000
  query_right_open_gap_score: -8.000000
  query_right_extend_gap_score: -3.000000
  mode: global

>>> for aln in aligner.align('CCGGTT', 'GGCCCAAA'):
...     print(aln)
...     print(aln.score)
... 
target            0 CCGG--TT 6
                  0 ....--.. 8
query             0 GGCCCAAA 8

17.0
```

**Comment by RaverJay** [comment]
When will 1.82 release?


pairwise2 works on 1.81:

```
from Bio import pairwise2

for aln in pairwise2.align.localds('CCGGTT', 'GGCCCAAA', subs_matrix,
                                   open=score_gapopen, extend=score_gapextend):
    print(pairwise2.format_alignment(*aln, full_sequences=True))

```

Imho PairwiseAligner would benefit from the ability to specifically choose the algorithm used, in addition to the automatic choice

Cheers

**Comment by peterjc** [comment]
See #4312

**Comment by mdehoon** [comment]
> Imho PairwiseAligner would benefit from the ability to specifically choose the algorithm used, in addition to the automatic choice

Why do you think so?

**Comment by RaverJay** [comment]
> > Imho PairwiseAligner would benefit from the ability to specifically choose the algorithm used, in addition to the automatic choice
> 
> Why do you think so?

For clarity, so that users can avoid the algo switching 'under their nose' unnoticed when they change parameters.
At the very least the documentation should describe how the automatic selection works.

Also the parameters and ways to set them are not communicated clearly enough imho.
A PairwiseAligner reports its parameters like this:

```python
  target_internal_open_gap_score: -8.000000
  target_internal_extend_gap_score: -3.000000
  target_left_open_gap_score: -8.000000
  target_left_extend_gap_score: -3.000000
  target_right_open_gap_score: -8.000000
  target_right_extend_gap_score: -3.000000
  query_internal_open_gap_score: -8.000000
  query_internal_extend_gap_score: -3.000000
  query_left_open_gap_score: -8.000000
  query_left_extend_gap_score: -3.000000
  query_right_open_gap_score: -8.000000
  query_right_extend_gap_score: -3.000000
  mode: global
```

and these can be set manually, but one can also set `open_gap_score` and `extend_gap_score` to set groups of them together,
and all of that is not clear from the documentation

**Comment by mdehoon** [comment]
> For clarity, so that users can avoid the algo switching 'under their nose' unnoticed when they change parameters.

But why is that important? The pairwise aligner is exhaustive. It does not matter then which algorithm generated the alignments.

If you could set the algorithm manually, it just means that you can choose a more complex algorithm than needed. It will generate the exact same alignments, but just use more time and memory for it.

**Comment by mdehoon** [comment]
> Also the parameters and ways to set them are not communicated clearly enough imho.

This is described in Table 6.1 in the documentation. Feel free to submit a PR if you think any information is missing.

**Comment by RaverJay** [comment]
> > For clarity, so that users can avoid the algo switching 'under their nose' unnoticed when they change parameters.
> 
> But why is that important? The pairwise aligner is exhaustive. It does not matter then which algorithm generated the alignments.
> 
> If you could set the algorithm manually, it just means that you can choose a more complex algorithm than needed. It will generate the exact same alignments, but just use more time and memory for it.

Agreed, moot point


> > Also the parameters and ways to set them are not communicated clearly enough imho.
> 
> This is described in Table 6.1 in the documentation. Feel free to submit a PR if you think any information is missing.

Kindly point me to this table - don't find it on https://biopython.org/docs/latest/api/Bio.Align.html - thanks!

**Comment by MarkusPiotrowski** [comment]
The "Biopython Tutorial and Cookbook":
http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec103

**Comment by RaverJay** [comment]
Ty

**Comment by mdehoon** [comment]
Perhaps we should rename the "Biopython Tutorial and Cookbook" to "Biopython Documentation". Users sometimes dont' realize that the main documentation is in there.

**Comment by peterjc** [comment]
My plan on #907 will have the API documentation and the tutorial side by side in the HTML output, and make it easy to cross link between them long term.
