### ISSUE TITLE
[feature request] PairwiseAligner object format output same as pairwise2.format_alignment

### ISSUE THREAD

**Issue by drewaight** [biopython/biopython#4442]
Since pairwise2 is going away, can we have a format() output that matches the output of pairwise2.format_alignment? The current output of alignment object format is only really useful for printing to screen. It is broken up into 60 characters with many line breaks. The output of format_alignment is more useful for down stream tasks (such as identifying mismatches by location) because it outputs 3 simple lines which can be parsed by using splitlines(). Mabye there is a way to get the same output from the Bio.Align library but I have not found it. See my example below. 

```
from Bio import Align
from Bio import pairwise2
from Bio.pairwise2 import format_alignment

query= 'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPCDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK'

const = 'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK'

aligner = Align.PairwiseAligner()
aligner.internal_gap_score = -1
a = aligner.align(query , const)
a[0].format()
```

> 'target            0 ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSS\n                  0 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\nquery             0 ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSS\n\ntarget           60 GLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG\n                 60 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\nquery            60 GLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGG\n\ntarget          120 PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYN\n                120 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\nquery           120 PSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYN\n\ntarget          180 STYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDE\n                180 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\nquery           180 STYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDE\n\ntarget          240 LTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRW\n                240 |||||||||||||||||.||||||||||||||||||||||||||||||||||||||||||\nquery           240 LTKNQVSLTCLVKGFYPCDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRW\n\ntarget          300 QQGNVFSCSVMHEALHNHYTQKSLSLSPGK 330\n                300 |||||||||||||||||||||||||||||| 330\nquery           300 QQGNVFSCSVMHEALHNHYTQKSLSLSPGK 330\n'

```
a2 = pairwise2.align.globalxs(query, const, -5, -5)
format_alignment(*a2[0])
```

> 'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK\n|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||.||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\nASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPCDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK\n  Score=329\n'

**Comment by mdehoon** [comment]
```python
>>> alignment = a[0]
>>> alignment[0]
'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPCDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK'
>>> alignment[1]
'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK'
```

**Comment by drewaight** [comment]
^^ yes this is good but these are just the input sequences we also need the ||||||.|||| which denotes match/mismatch.

**Comment by mdehoon** [comment]
> ^^ yes this is good but these are just the input sequences we also need the ||||||.|||| which denotes match/mismatch.

These are not the input sequences; these are the aligned sequences.
With those, it's trivial to generate the `|||.||` string.

**Comment by drewaight** [comment]
show me.

**Comment by mdehoon** [comment]
@drewaight  Try yourself first please.

**Comment by peterjc** [comment]
This discussion looks like very similar to #4250 to me.

Anyway, something like this if you care about gaps?:

```python
from Bio import Align
from Bio import pairwise2
from Bio.pairwise2 import format_alignment

query= 'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPCDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK'

const = 'ASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK'

aligner = Align.PairwiseAligner()
aligner.internal_gap_score = -1
a = aligner.align(query , const)[0]  # take just the first alignment

def pretty_matches(seq1, seq2):
    assert len(seq1) == len(seq2)
    return "".join(
        "-" if (a == "-" or b == "-b") else "|" if a == b else "."
        for (a, b) in zip(seq1, seq2)
    )
print(a[0])
print(pretty_matches(a[0], a[1]))
print(a[1])
```

**Comment by DegnKristine** [comment]
If you need "-" in stead of "|" a simple solution that can be improved is: 

```
alignments = aligner.align(seqA, seqB)
a = alignments[0].format()
a = a.split("\n")    
seqA_aligned = a[0].replace(" ", "-")
seqB_aligned = a[2].replace(" ", "-")
```

I, have another issue with this feature. 

I am often in a case where I have seqA = "LKLAGHIEAG", and seqB = "LKLA--KKAG". where "-" in seq B indicates a gap. 
If I try to align these seqA and seqB, i get the "ValueError: sequence contains letters not in the alphabet" concerning the "-". One solution is to drop the gap and let the alignment find it on its own. But finding the correct spot has proven a challenge. The old pairwise2 has no issues with "-" characters. 

Is there a way around this?

**Comment by mdehoon** [comment]
@DegnKristine  Please open a separate issue for this. An example with the explicit code would help.

**Comment by mdehoon** [comment]
Can we close this issue?
