### ISSUE TITLE
unstable results

### ISSUE THREAD

**Issue by msatarnejad96** [biopython/biopython#4462]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
CPython
Linux-5.15.120+-x86_64-with-glibc2.35
1.81*)

### Expected behaviour

(*
results =Entrez.elink(dbfrom="gene", db="pubmed",
LinkName="gene_pubmed_rif", datetype='pdat',
mindate='2002', maxdate='2012',
id='10', api_key='...')
record = Entrez.read(results)
pm_ids = [link["Id"]
print(len(pm_ids))
*)
I get some times 66 and sometimes 94 as result every time i run the code.
### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

**Comment by peterjc** [comment]
Very strange, but you'll have to email the NCBI help desk. They may ask for the actual URL, try ``print(results.url)`` to get that.

**Comment by msatarnejad96** [comment]
I have done this before but there asked to email you.

**Comment by peterjc** [comment]
Can you record the URL for the 66 and 94 results, and confirm they match?

Without seeing your code I have nothing further to suggest, sorry.
