### ISSUE TITLE
Loading substitution matrices causes ResourceWarning

### ISSUE THREAD

**Issue by byerlyj** [biopython/biopython#4475]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

3.8.10 (pipelines/36268:97041de, Jun  4 2021, 13:53:01) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-10-10.0.19045-SP0
1.81

### Issue
loading a substitution matrix with `Bio.Align.substitution_matrices.load` causes a `ResourceWarning`

### Steps to reproduce
the following minimal snippet should reproduce this issue
```
from Bio.Align import substitution_matrices

def main():
    blosum_62 = substitution_matrices.load("BLOSUM62")
    assert blosum_62["A", "A"] == 4.0

if __name__ == '__main__':
    main()
```

I am pretty sure the issue is in `Bio.Align.substitution_matrices.__init__.read`; the `finally` clause on line 465 should be un-indented to apply to the outer try-except instead of the inner. better still, this file handling could be reworked to use a context manager

**Comment by mdehoon** [comment]
I don't get a `ResourceWarning` when I run your example.

> I am pretty sure the issue is in Bio.Align.substitution_matrices.__init__.read; the finally clause on line 465 should be un-indented to apply to the outer try-except instead of the inner.

Why do you think so?

**Comment by lennax** [comment]
@mdehoon `python3 -X dev` causes the `ResourceWarning` to show up for me.

**Comment by mdehoon** [comment]
> @mdehoon `python3 -X dev` causes the `ResourceWarning` to show up for me.

I see. I agree that the `finally` clause should be unindented. Can you prepare a pull request?

**Comment by byerlyj** [comment]
> > @mdehoon `python3 -X dev` causes the `ResourceWarning` to show up for me.
> 
> I see. I agree that the `finally` clause should be unindented. Can you prepare a pull request?

My initial thought was that the un-indent could be sufficient to correct the file management issue, but it occurred to me later that the code could be made less sensitive to such issues by using a context manager instead. This should be functionally identical to the un-indent of the `finally` clause, but has the added benefits of reducing complexity and allowing us to unify the filename and filehandle code paths! Is my current pull request sufficient or would you like me to roll back my changes?
