### ISSUE TITLE
OSS-Fuzz Integration Inquiry

### ISSUE THREAD

**Issue by capuanob** [biopython/biopython#4489]
Hello!

I have integrated a few open-sourced projects into OSS-Fuzz, a program sponsored by Google to provide continuous fuzz-testing of impactful open-sourced projects, and am wondering if BioPython's maintainers would approve me undertaking the work to develop a harness to fuzz-test this library and integrate it into OSS-Fuzz.

If you would like more details on what OSS-Fuzz is and what this work would entail, more details can be found [here](https://google.github.io/oss-fuzz/).

Thank you for your consideration and I look forward to working with you all!

**Comment by peterjc** [comment]
Cross reference #4223. Exploring fuzz testing outside of our CI and tests would seem a sensible first step.

**Comment by capuanob** [comment]
@peterjc Thank you for the issue reference! I don't want to step on his work, so I appreciate you pointing it out

**Comment by peterjc** [comment]
OK, then let's close this and continue any discussion on #4223.

I would like to see an example of the kind of useful changes in Biopython this might result in.

Thanks!
