### ISSUE TITLE
How to get the alignment line from HmmerIO / hmmer3_text

### ISSUE THREAD

**Issue by davidecrs** [biopython/biopython#4494]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:27:15) [Clang 11.1.0 ]

import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-13.5.2-arm64-arm-64bit

import Bio; print(Bio.__version__)
1.81
```

### Expected behaviour
Hi, 

I'm executing hmmsearch with the following command:
```bash
hmmsearch --domtblout hmmsearch_domtable.txt -E 0.00001 -o output.txt --cpu 5 --notextw MFS_efflux_PexA-NCBIFAM.HMM orf_predicted.faa

```
 and I would like to parse the file called `output.txt` to get the lines where there are the alignments
```
>> contig_204290_orf_3  
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  142.2  30.0   3.4e-43   2.5e-39      21     394 ..       7     374 ..       1     387 [. 0.91

  Alignments for each domain:
  == domain 1  score: 142.2 bits;  conditional E-value: 3.4e-43
  MFS_efflux_PexA-NCBIFAM  21 illgcglwpemellvpslpdmqrafniqdaqiqqlltanfvgfligvlfagplcdsagrrtvmmigtigylvssvlcpfcndfvllmiarffqglfmtgpviaggvllmeategvkqifwmsignaaitfcmaagpivgswintgfgyvgnlwsililgligclpalflvpes.lpvekraafhpkllfkgyfallkdfrfmclaipmcalaaaywiyvgvsalymvnqlgiaqemfgryqgpivgcfsiislgsskllqrfglmkclragivsmftgmllllgmsilsldhavattvfmmffvggmapicsmlfpyalghlpvdlkgnaqamvqairlffasigtslvgvfyksaflpvalimfaillfscyfl 394
                              i++ +    e++l+ ps+p++q  f +    ++ ll+ nfvg+ +g+lf g l+d  gr+ ++++g   +++ s++c +   + +l++ rf+qgl +++p     +++ ++     q +w+s+ n    +++  +p+ gs+in  f + gn+ ++l+lg+i ++ +++++p+  lp +     + kllfkg++ +++   +m l i +  +   ywi+ g+s l  +++lg++  +fg yqg +  +f++ s+  + +++++   k l    +  ++ ++ +   + l++d  +  t+ ++ f+       s+l+p +l + p   k++  a+++   l+++++   + g +y+ +f  + +i+  + +f+  f+
      contig_204290_orf_3   7 IMMDVLSGAEIDLIAPSFPEIQAQFGLTPFWVEALLSINFVGICLGLLFVGSLADHYGRKQIILLGLTIFILGSIFCLVPSSYNFLLVGRFLQGLGVSAPSTLSFLIIADSYSTKDQQYWLSMLNGVFNIIVGIAPVAGSYINIYFHWQGNFMTLLLLGIITAFMTIIFIPKYkLPEN-----KEKLLFKGFLPIFQSKPLMQLIICITLIVIPYWIFSGMSPLLYIEDLGVSLAIFGFYQGVLATIFALGSILFAMIIHKYDDKKWLNISCIIGLSSLVCIGVTTYLNIDTPLIITLSIIPFIISQIIPSSLLYPICLNFQPK-AKAKISALLKGGNLILSAVSLQIAGYYYQGSFQNIGIILS-VTIFAGLFM 374
                              4555555689********************************************************************************************************************************************************9999998887515554.....479**********************************************************************************9988887777777666789*****99999888766666555589********9995.79999*****************************998864.555655554 PP

```

In particular, I'm interested in getting the line with the "+" symbols in order to count the identical and similar matches.
```
i++ +    e++l+ ps+p++q  f +    ++ ll+ nfvg+ +g+lf g l+d  gr+ ++++g   +++ s++c +   + +l++ rf+qgl +++p     +++ ++     q +w+s+ n    +++  +p+ gs+in  f + gn+ ++l+lg+i ++ +++++p+  lp +     + kllfkg++ +++   +m l i +  +   ywi+ g+s l  +++lg++  +fg yqg +  +f++ s+  + +++++   k l    +  ++ ++ +   + l++d  +  t+ ++ f+       s+l+p +l + p   k++  a+++   l+++++   + g +y+ +f  + +i+  + +f+  f+
```

### Actual behaviour / Steps to reproduce

I've successfully read the `output.txt` file through this code
```python
from Bio import SearchIO

with open ("output.txt",'rU') as handle: 
    for record in SearchIO.parse(handle, 'hmmer3-text'):
        hits = record.hits
...
```
But I wasn't able to get that line. 
Do you know how to do it? Do you have other suggestions?

I appreciate any help you can provide.
Best regards

**Comment by peterjc** [comment]
I don't think the parser tries to capture the "match" string (this is something which varies considerably between file formats). I think you'd be better off counting matching letter explicitly.

**Comment by bow** [comment]
@davidecrs `hmmer3-text` does not indeed capture the similarity string.

We do capture it in other formats, putting the string under the `similarity` key of the `aln_annotation` dictionary attribute of the innermost alignment object.

I honestly can not remember why we did not add it. I like to believe the reason was mostly to keep complexity of the parser low. Also the fact that counting the matching strings might be preferable.

But to be honest, looking at the parser again, I feel complexity isn't increased much if we add this. Plus we are already doing similarity string parsing in other formats. [So I took a go at trying to do it](https://github.com/biopython/biopython/compare/master...bow:biopython:feat/hmmer3-text-similarity-string). 

@peterjc It seems like adding this wouldn't break any existing functionalities ~ I have not yet done thorough testing though, so no guarantees. I can continue to make a proper PR (adding more test cases and checking for more corner cases), if this is preferrable.

**Comment by davidecrs** [comment]
Hi @bow ,

many thanks for your answer! I'll wait for the next updates!

Many thanks again,
Best regards.

**Comment by peterjc** [comment]
@bow if you've captured this for other formats, we might as well do it here too.

**Comment by bow** [comment]
@davidecrs @peterjc Great :slightly_smiling_face: ~ I have expanded the tests and [opened the PR](https://github.com/biopython/biopython/pull/4500). Let's continue the discussion on the details there.
