### ISSUE TITLE
Missing Strand Information in Entrez-XML to Python Dictionary Conversion (Entrez.read / Entrez.parse)

### ISSUE THREAD

**Issue by AHK66** [biopython/biopython#4506]
Code for Reproduction in Biopython 1.81:
```python
from Bio import Entrez
import json
handle = Entrez.efetch(db="gene", id=27246, rettype="gb", retmode="xml")
dictionary = Entrez.read(handle)
handle.close()
print(json.dumps(dictionary, indent=2))
```
In the generated dictionary, all strand information is missing. The corresponding dictionary elements consistently show an empty string:
```python
"Seq-interval_strand": {
    "Na-strand": ""
},
```
In the original Entrez-XML, the strand information is represented via an attribute ```<Na-strand value="{plus|minus}"/>```. This attribute appears to be lost during the conversion from XML to a Python dictionary.

Best wishes,
AHK66

**Comment by mdehoon** [comment]
The XML code is 
```
                          <Na-strand value="minus"/>
```
instead of
```
                          <Na-strand>minus</Na-strand>
```
So you will find "minus" in the attributes of this element. See section 9.10 in the documentation for an example with attributes.

**Comment by AHK66** [comment]
Thank you for the fast reply! The dictionary entry looks, in fact, like this: 
```{'Na-strand': StringElement('', attributes={'value': 'minus'})}```. 
The JSON serialization swallows the StringElement.

Best wishes,
AHK66
