### ISSUE TITLE
Should steps different than 1 be allowed in SeqRecord?

### ISSUE THREAD

**Issue by manulera** [biopython/biopython#4509]
### Setup

Biopython version, Python version, and operating system as follows:

```python
>>> import sys; print(sys.version)
3.11.6 (main, Oct  6 2023, 11:55:02) [Clang 13.0.0 (clang-1300.0.29.30)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
macOS-12.7-x86_64-i386-64bit
>>> import Bio; print(Bio.__version__)
1.81
```

### Current behaviour

```python
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.SeqFeature import SeqFeature, SimpleLocation

feature = SeqFeature(SimpleLocation(2, 2, 1), type="CDS")
print(feature.location)
# [2:6](+)

seqr = SeqRecord(Seq('AAAAAAAAAAAAAA'), features=[feature])

print(seqr.features[0].location)
# [2:6](+)

seqr2 = seqr[::2]
print(len(seqr2.features))
# 0
```

### Question

Since slicing with step != 1 does not transmit the features, should this be allowed at all? If this is kept at least a warning could be issued that this operation might not give the expected result.

cc @BjornFJohansson

**Comment by peterjc** [comment]
Do you have a use case for slicing an annotated record with a step other than one?

(I can understand slicing a sequence with step 3 for working with codons, but there you would not need the annotation)

i.e. What do you need from ``my_record[::2]`` that ``my_record.seq[::2]`` doesn't offer?

**Comment by manulera** [comment]
> Do you have a use case for slicing an annotated record with a step other than one?

Hi @peterjc, I can't really think of a use case for this. Not allowing it is probably too much, but maybe a warning could be issued to tell the user that features will not be transmitted if step != 1.

Perhaps it's unnecessary and expected, but even single-base features are not transmitted, which may or may not be the expected result.

**Comment by peterjc** [comment]
You could apply !=1 steps to any per-letter-annotations (e.g. quality scores FASTQ files; easy to implement), or the special case of single base pair features (e.g. SNPs perhaps; harder to implement). Given there is scope for more than one interpretation, and lacking any use-case, I felt and still feel it was safer to raise an Exception, than implement something potentially unexpected (which might need to be changed).

**Comment by manulera** [comment]
> I felt and still feel it was safer to raise an Exception

Hi @peterjc I am not sure I understand what you meant there. As it is, no exception is raised if step != 1. You mean that you agree that code should be added so that an exception is raised? I would agree with this, but this would not be back-compatible (if someone was doing that for some reason).

**Comment by peterjc** [comment]
I didn't double check - you're right: https://github.com/biopython/biopython/blob/biopython-181/Bio/SeqRecord.py#L494

Making this an error now would probably break people's code; adding a warning _might_ be acceptable. I lean to leaving the code as is (and closing this issue).

**Comment by manulera** [comment]
Ok!
