### ISSUE TITLE
Is there any method for reversal distance in Biopython?

### ISSUE THREAD

**Issue by ozgurcanarican** [biopython/biopython#4512]
I need to calculate reversal distance between genome pairs. As I remembered there is a function that named reversal_distance under Bio.SeqUtils. Is it deprecated or is there another method for calculating reversal distances of genome rearrangement?

**Comment by peterjc** [comment]
That's not bringing up any hits with a GitHub search (eg not in the current SeqUtils code, nor the DEPRECATED file).

What is it you want to calculate (I don't know this term)?

**Comment by ozgurcanarican** [comment]
Reversal distance is a term related to the subject of genome rearrangement. To summarize briefly;

Let there be genes named 1, 2, 3, 4, and 5 on a genome. Let's show that the correct sequence of these genes is permuted (1, 2, 3, 4, 5) and let's call it P1. Let me have the permutation (5, 2, 3, 1, 4) and call it P2.

Let's assume that I turned P2 into P1 with the help of an algorithm (pancake sort, breakpoint reversal sort, etc.). Let this algorithm be completed in 4 steps. In this case, "the reversal distance" value of the relevant algorithm is 4. In other words, the reversal distance shows how many steps it takes to convert the P2 permutation to the P1 permutation.

I may be remembering wrong, perhaps there is no method in Biopython that performs this task. If you don't have it and consider adding it, I would be very happy.

**Comment by ozgurcanarican** [comment]
No, my question was not about phylogenetic trees.
