### ISSUE TITLE
BiopythonDeprecationWarning: The 'Bio.SearchIO._legacy' module

### ISSUE THREAD

**Issue by thekswenson** [biopython/biopython#4525]
### Setup

Python 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0] on linux

### Expected behaviour

I'm using the XML reading functionality for BLAST, and I receive a strange deprecation warning, as though I was giving the reader a text file rather than an XML file:

```
[nav] In [1]: from Bio import SearchIO

[nav] In [2]: SearchIO.read('test/NC_006884.2_results.xml', 'blast-xml')
Out[2]: QueryResult(id='NC_006884.2', 1 hits)
```

I'm expecting the read to happen without warning, since I'm using an XML file.

### Actual behaviour

I receive a warning message the first time I call `read`:

```
[nav] In [2]: SearchIO.read('test/NC_006884.2_results.xml', 'blast-xml')
/usr/lib/python3/dist-packages/Bio/SearchIO/_legacy/__init__.py:12: BiopythonDeprecationWarning: The 'Bio.SearchIO._legacy' module for parsing BLAST plain text output is deprecated and will be removed in a future release of Biopython. Consider generating your BLAST output for parsing as XML or tabular format instead.
  warnings.warn(
Out[2]: QueryResult(id='NC_006884.2', 1 hits)
```

### Steps to reproduce

1. open ipython3
2.  `from Bio import SearchIO`
3.  `SearchIO.read('test/NC_006884.2_results.xml', 'blast-xml')`

**Comment by peterjc** [comment]
That's odd - I agree the warning ought not to have been triggered by that example.

Are you using Biopython 1.81?

The good news is this should be "fixed" thanks to #4488 removing the legacy plain text BLAST parser in our next release (Biopython 1.82).

**Comment by thekswenson** [comment]
1.80
(sorry that I didn't include that)

**Comment by peterjc** [comment]
Oh well, the old code and the problematic warning are being removed - so I'll close this. Thanks for reporting - looking back I'm surprised no one else did.
