### ISSUE TITLE
Regexp for matching trees in PAML (codeml) output

### ISSUE THREAD

**Issue by jergosh** [biopython/biopython#453]
Hi all,
I've noticed that the parser doesn't always capture trees from codeml output. I can see in the code (here: https://github.com/biopython/biopython/blob/master/Bio/Phylo/PAML/_parse_codeml.py#L174) that the regex for deciding if the line contains a tree is "\\(\\(+" which I take to be 'left parenthesis followed by one or more left parentheses'. An example tree from one of my result files looks like this:

(GLN_GLV_YALI0E29865G: 8.494319, GLN_GLV_SAKL0A04796G: 1.449617, (((AFL078W: 4.846475, GLN_GLV_KLLA0E19449G: 3.372082): 1.075125, (GLN_GLV_ZYRO0G08558G: 2.931415, ((SMIK_6_402: 0.320244, (SBAY_16_110: 0.368757, (SKUD_16_82: 0.015513, PORT_16_86: 0.008132): 0.279255): 0.132022): 2.861413, (KNAG0D05130: 6.335563, KAFR0K00370: 2.459791): 0.491734): 0.868678): 1.003015): 0.720969, (KWAL56_23998: 2.000445, GLN_GLV_KLTH0H04510G: 1.613190): 2.588057): 0.560065);

i. e. starts with only one parenthesis and naturally the regex doesn't match. Am I missing something here or should the regex actually match lines which start with just one parenthesis in order to always correctly capture trees? If so, is there any lines which don't contain trees but start with a single parenthesis?

Best,
Greg

**Comment by peterjc** [comment]
This is probably a question for @etal or @brandoninvergo ...

@jergosh - do you have a sample file showing the problem which we could use for a functional test? If you could post it using https://gist.github.com or similar that would be great.

**Comment by jergosh** [comment]
Hi Peter,
Thanks for the quick reply. Sure, here's the full results file: https://gist.github.com/jergosh/972106cf182a53ea89f6

Best,
Greg

**Comment by brandoninvergo** [comment]
Unfortunately I can't test it at the moment but perhaps `"^\(.*\);$" would be better (might have to account for possible whitespace before the end of the line).
