### ISSUE TITLE
NewickIO.read: Incorrect deserialization of labels with correctly escaped single quotes

### ISSUE THREAD

**Issue by corneliusroemer** [biopython/biopython#4537]
### Expected Behaviour
When reading a Newick tree containing labels with escaped single quotes (i.e. duplicated single quotes in quoted labels) deserialized 

The first label in `('Node''Name':0.00000)Root:0.00000;` should deserialize to `Node'Name` when reading with `Bio.Phylo.read` per the [Newick file specification](https://web.archive.org/web/20170714111939/https://evolution.genetics.washington.edu/phylip/newick_doc.html). To quote the relevant bits: "Unquoted labels may not contain blanks, parentheses, square brackets, single_quotes, colons, semicolons, or commas. Single quote characters in a quoted label are represented by two single quotes."

### Actual Behaviour
Doubly Taxon names with single quotes are incorrectly serialized:

The first label in `('Node''Name':0.00000)Root:0.00000;` deserializes to `Name`, i.e. the `Node'` part is erroneously dropped.

### Steps to Reproduce

```python
from Bio import Phylo
from io import StringIO

# Newick string with a label containing escaped single quotes
newick_str = "('Node''Name':0.00000)Root:0.00000;"

# Reading the tree from the Newick string
tree = Phylo.read(StringIO(newick_str), "newick")

print(tree)
```

Correct output would be:
```
Tree(rooted=False, weight=1.0)
    Clade(branch_length=0.0, name='Root')
        Clade(branch_length=0.0, name="Node'Name")
```

Actual Output:
```
Tree(rooted=False, weight=1.0)
    Clade(branch_length=0.0, name='Root')
        Clade(branch_length=0.0, name='Name')
```

Potentially this is the issue that was reported in #2227 but without a good example.

Serialization is also wrong, see #4536

**Comment by corneliusroemer** [comment]
The token definition here for a quoted taxon is wrong, it says that single quotes can't appear in quoted taxons, but they can, per the specification:
https://github.com/biopython/biopython/blob/4ddf78a73853fa31a52fcbbadfb44c3626ad1b07/Bio/Phylo/NewickIO.py#L32
Specifically, the capture group only captures:
- Any escaped character. The double backslash `\\` is a literal backslash, and `.` matches any character except newlines.
- Any character that is not a single quote `'`

It should _also_ match two single quotes in a row.

**Comment by amatria** [comment]
I think this relates to #4139
