### ISSUE TITLE
run_tests inconsistency

### ISSUE THREAD

**Issue by mdehoon** [biopython/biopython#4538]
At the top of `Tests/run_tests.py`, we have

```python
    try:
        # NumPy 1.14 changed repr output breaking our doctests,
        # request the legacy 1.13 style
        np.set_printoptions(legacy="1.13")
    except TypeError:
        # Old Numpy, output should be fine as it is :)
        # TypeError: set_printoptions() got an unexpected keyword argument 'legacy'
        pass
```

This causes tests run through `run_tests.py` to behave differently from tests run directly.
For example, `python run_tests.py test_Tutorial` will set the numpy print options to the legacy 1.13 style, but `python test_Tutorial.py` will use the current numpy style.

We either need to put this block in all test scripts in which numpy arrays are printed, or we need to require numpy version >= 1.14 and fix the tests that rely on the legacy numpy print style.

**Comment by peterjc** [comment]
That was originally added 6 years ago for the doctests (see issue #1496 and PR #1541), but it does not surprise me that ``test_Tutorial.py`` is also affected.

I think updating the tests to expect the current numpy output is the best choice now.
