### ISSUE TITLE
Replacing PDB atom names with Biopython

### ISSUE THREAD

**Issue by pippo1990** [biopython/biopython#4542]
Would anybody be so kind to have a look at https://stackoverflow.com/questions/77660394/

I am using 1.80 version 

its not a real issue , is just to understand what goes on inside the hood of the BIO.PDB module and why it is difficult

to change atom.names without getting some sort of side effects, I know I should write down everything in a clear way here , but

its a long question , followed by 2 answers that try to overcame the initial question but revealing some oddities.

I'll try to report everything in here as soon as I have some spare time

Cheers P.

**Comment by peterjc** [comment]
I have commented there.

**Comment by pippo1990** [comment]
thanks Peterjc

**Comment by pippo1990** [comment]
closed

**Comment by pippo1990** [comment]
Thanks, Peterjc

**Comment by pippo1990** [comment]
Thanks Peterjc

**Comment by pippo1990** [comment]
Thanks Peterjc

**Comment by pippo1990** [comment]
Thanks Peterjc
