### ISSUE TITLE
Is it possible to update a pairwise alignment with a single substitution or indel ? 

### ISSUE THREAD

**Issue by gciaberi** [biopython/biopython#4548]
I'm using `Bio.Align.PairwiseAligner` to align two amino acid sequences A and B, and I'm interested in obtaining all the alignment scores resulting from all possible single residue substitutions and indels in sequence A. Currently I'm redoing the full alignment from scratch every time, but for two sequences of length N I have to perform approximately 40*N alignments, which is inevitably quite slow. Is there a way to do a partial update or something like that to avoid redoing the full alignment every time and that would be faster than what I'm currently doing ? 

Note that I have already implemented a simplified approach for substitutions where I assume that they don't impact the alignment and I therefore just update the alignment score using the substitution matrix values, but this is not ideal for my use case.

**Comment by mdehoon** [comment]
Currently it is not possible, and as far as I know no algorithm exists that would be able to do that.
