### ISSUE TITLE
PDB Entity.copy() mangles disordered atoms.

### ISSUE THREAD

**Issue by macraild** [biopython/biopython#455]
Disordered atoms dont inherit `disordered_get_list()` when a parent entity is copied. Eg:

```
>>> pdbl = Bio.PDB.PDBList(server='http://www.rcsb.org/pdb/files')
>>> pdbParser = Bio.PDB.PDBParser()
>>> struct_4LGR = pdbParser.get_structure('4LGR', pdbl.retrieve_pdb_file('4LGR'))
Downloading PDB structure '4LGR'...
>>> Bio.PDB.PPBuilder().build_peptides(struct_4LGR)
[<Polypeptide start=5 end=33>, <Polypeptide start=36 end=259>, <Polypeptide start=2 end=123>]
>>> Bio.PDB.PPBuilder().build_peptides(struct_4LGR.copy())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Polypeptide.py", line 357, in build_peptides
    and is_connected(prev_res, next_res):
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Polypeptide.py", line 417, in _is_connected
    nlist=n.disordered_get_list()
AttributeError: 'Atom' object has no attribute 'disordered_get_list'
```

**Comment by peterjc** [comment]
I suspect (from just browsing the code) that the problem is neither ``Bio.PDB.Atom.DisorderedAtom`` nor the underlying base class ``Bio.PDB.Entity.DisorderedEntityWrapper`` define a ``.copy()`` method?

**Comment by macraild** [comment]
That looks right to me. I'm not sure I completely understand how disorder is handled here, but from my reading ``.copy()`` should be defined at the ``DisorderedAtom`` level, and a minimal implimentation might be:

```
def copy(self):
    shallow = copy.copy(self)
    for child in self.child_dict.values():
        shallow.disordered_add(child.copy())
    return shallow
```

This fixes my immediate problem (ie. disordered ``Atom`` objects in copies are now appropriately contained in ``DisorderedAtom``, and ``Bio.PDB.PPBuilder`` now works). I may have missed something important in the above, and don't know what other behaviour needs to be tested here.

**Comment by peterjc** [comment]
@macraild Thanks for looking at this and coming up with a proposed fix, The very fact you hit this bug tells me we don't (yet) have a suitable test for this. As for running the existing tests, there is a chapter in the main tutorial that covers this if you are interested.

@etal, @lennax, @JoaoRodrigues - are any of you familiar with disordered atoms, or know who would be best to review this proposed fix? Thanks!

**Comment by JoaoRodrigues** [comment]
Hi,

Had a look at the code. Seems to be exactly the problem. The fix seems to work rather well. 

Just at thought, wouldn't be better to add it to the DisorderedEntityWrapper object? Seems cleaner. This will add a copy method to DisorderedResidues as well, although it doesn't seem to affect anything (tested with PDB 1IGY).

Cheers

**Comment by macraild** [comment]
@JoaoRodrigues On a closer look, I agree. This does look like it belongs in ``DisorderedEntityWrapper``. Except that then the existing tests break:

```
> python test_PDB.py
...
======================================================================
FAIL: Make a copy of a residue.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_PDB.py", line 1058, in test_entitity_copy
    ee = e.copy()
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Entity.py", line 182, in copy
    shallow.add(child.copy())
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Entity.py", line 182, in copy
    shallow.add(child.copy())
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Entity.py", line 182, in copy
    shallow.add(child.copy())
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Entity.py", line 243, in copy
    shallow.disordered_add(child.copy())
  File "/usr/lib/python2.6/site-packages/Bio/PDB/Residue.py", line 160, in disordered_add
    assert(not self.disordered_has_id(resname))
AssertionError

----------------------------------------------------------------------
Ran 35 tests in 1.862s

FAILED (failures=1)
```

Looks like ``DisorderedResidues`` need different treatment?
 
One other issue I've run into:
on Python2.6 the proposed fix (in either location) exposes something similar to this bug: http://bugs.python.org/issue5508 Everything still appears to work, but the error message is a bit disconcerting.

**Comment by JoaoRodrigues** [comment]
Check this commit here: a36605d2aafacb3f47de42844899b263c8c8de8b

The tests pass, but indeed that recursion warning shows up.. @peterjc Any ideas?

**Comment by peterjc** [comment]
So adding this ``.copy()`` to ``DisorderedEntityWrapper`` interacts badly with the existing ``.__getattr__(...)`` method? Strange.

If you add the ``.copy()`` method to ``DisorderedAtom`` does everything seem OK?

**Comment by schwarz-ben** [comment]
Hi, 
   
   First of all I want to thank you for the great job you are doing with biopython.

  In connection with the problem exposed here.
When copying a structure, applying a transformation, then saving : I first ran in the problem exposed by macraild. Using the "trick" he proposed on jan 8 2015 I was able to have my script working without complaining, but I realized afterwards that the atoms with alternate locations were not affected by the transformation : they simply stayed in place.

    Any idea how I can solve the problem ?

      --Ben

(using pytho2.7 on ubuntu, biopython version as found in __init__.py : 1.66)

**Comment by schwarz-ben** [comment]
Hi,

As a quick and dirty fix, in Bio.PDB.Residue.Residue.get_unpacked_list I replaced 

        if atom.is_disordered():
            undisordered_atom_list = (undisordered_atom_list + atom.disordered_get_list())

by

        if atom.is_disordered():
            atom.altloc=" "
            undisordered_atom_list.append(atom)

It seems this allows me to keep atoms for alternate location 'A'.

**Comment by jaredsagendorf** [comment]
I have run into the exact same issue as schwarz-ben.

When copying a structure and then applying a transformation to the copied structure, the transformation is not applied to the disordered atoms.

Any chance of getting this fixed relatively quickly? Seems like a pretty major bug which should have a simply fix...

**Comment by JoaoRodrigues** [comment]
Hi @jaredsagendorf 

Could you post here a simple script that reproduces this issue? I can try to fix this asap.

**Comment by schwarz-ben** [comment]
I think there are actually two problems colliding : copying a structure with alt-loc atoms, and transforming a structure with alt-loc atoms.

The sample code below should do.
 * Run as is it should crash (can't copy disordered atoms)
 * Uncommenting FIX1 (as suggested above in the thread) the script should execute, but the job is imperfectly done (alt-loc atoms aren't moved, neither in the loaded structure nor in its copy.).
 * Uncommenting FIX2 is ugly (I transform disordered in ordered, keeping only data from altloc 'A') but does the job

```python
import Bio.PDB

############# FIX 1

# copy=Bio.PDB.Atom.copy
# def myCopy(self):
#     shallow = copy.copy(self)
#     for child in self.child_dict.values():
#         shallow.disordered_add(child.copy())
#     return shallow
# Bio.PDB.Atom.DisorderedAtom.copy=myCopy

############# FIX 2

# def get_unpacked_list(self):
#     """
#     Returns all atoms from the residue,
#     in case of disordered, keep only first alt loc and remove the alt-loc tag
#     """
#     atom_list = self.get_list()
#     undisordered_atom_list = []
#     for atom in atom_list:
#         if atom.is_disordered():
#             atom.altloc=" "
#             undisordered_atom_list.append(atom)
#         else:
#             undisordered_atom_list.append(atom)
#     return undisordered_atom_list
# Bio.PDB.Residue.Residue.get_unpacked_list = get_unpacked_list

###########################

inputPdb = "/home/schwarz/tmp/4lgr.pdb"
output1  = "/home/schwarz/tmp/4lgr-t1.pdb"
output2  = "/home/schwarz/tmp/4lgr-t2.pdb"

parser = Bio.PDB.PDBParser()
struct = parser.get_structure("myStruct",inputPdb)
idMat=( (1,0,0), (0,1,0), (0,0,1) )
trVect=(20.,20.,20.)
s = struct.copy()
s.transform( idMat,trVect )
struct.transform( idMat,trVect )
pdbio = Bio.PDB.PDBIO()

pdbio.set_structure(struct)
with open(output1,"w") as fd :
  pdbio.save(fd)

pdbio.set_structure(s)
with open(output2,"w") as fd :
  pdbio.save(fd)
```
Adding these lines  as suggested in this thread should allow the script t

**Comment by JoshuaMeyers** [comment]
Just reporting that I ran into the same issue while using the `SuperImposer()` class and that @schwarz-ben's solution above resolved the issue. Eagerly awaiting that PR :D

**Comment by akabiraka** [comment]
> Hi,
> 
> As a quick and dirty fix, in Bio.PDB.Residue.Residue.get_unpacked_list I replaced
> 
> ```
>     if atom.is_disordered():
>         undisordered_atom_list = (undisordered_atom_list + atom.disordered_get_list())
> ```
> 
> by
> 
> ```
>     if atom.is_disordered():
>         atom.altloc=" "
>         undisordered_atom_list.append(atom)
> ```
> 
> It seems this allows me to keep atoms for alternate location 'A'.

Hi, I am very new in using Biopython. I had the same issue and did this bad thing as @schwarz-ben  suggested. And it did work.
