### ISSUE TITLE
IndexError raised when parsing some Uniprot Records with SwissProt package.

### ISSUE THREAD

**Issue by GCS-ZHN** [biopython/biopython#4554]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
output as following:
```
3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0]
CPython
Linux-5.4.0-147-generic-x86_64-with-glibc2.17
1.78
```

### Expected behaviour

here is code:
```
from Bio import ExPASy, SwissProt
record = SwissProt.read(ExPASy.get_sprot_raw('P33527'))
```

it should get a `Record` object, but a `IndexError` raised

### Actual behaviour
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/corp/hongning.zhang/data/.conda/lib/python3.8/site-packages/Bio/SwissProt/__init__.py", line 257, in read
    record = _read(handle)
  File "/data/corp/hongning.zhang/data/.conda/lib/python3.8/site-packages/Bio/SwissProt/__init__.py", line 371, in _read
    _read_ft(record, line)
  File "/data/corp/hongning.zhang/data/.conda/lib/python3.8/site-packages/Bio/SwissProt/__init__.py", line 832, in _read_ft
    key = keys[-1]
IndexError: list index out of range
```

I traceback the error and found it caused by such uniprot format content:
```
FT   BINDING         713
FT                   /ligand="ATP"
FT                   /ligand_id="ChEBI:CHEBI:30616"
FT                   /ligand_label="1"
```
'/ligand' is not a defined type in current version and code `keys = list(feature.qualifiers.keys())` in `Bio.SwissProt` at line 829 is a empty list.
So I modified code like this to ignore this type directly:
```
        keys = list(feature.qualifiers.keys())
        if len(keys) == 0:
            return
```

**Comment by peterjc** [comment]
Please re-test with a more recent Biopython to confirm this is still an issue, the current release is Biopython version 1.82

**Comment by GCS-ZHN** [comment]
Close it as not raised in latest version

**Comment by peterjc** [comment]
Thank you - I hoped this was the case, but wasn't in a position to check myself when I replied.
