### ISSUE TITLE
ImportError: cannot import name 'SCOPData' from 'Bio.Data'

### ISSUE THREAD

**Issue by palvinaveen** [biopython/biopython#4566]
I am using alphafold  for modeling protein, it  cannot import SCOPDATA from bio.data as mention below ,
![ImportError: cannot import name 'SCOPData' from 'Bio Data](https://github.com/biopython/biopython/assets/149134911/c46dcd7b-49b7-442b-921c-a45fd53df244)
when I went to your data file it is missing SCOPdata.py file  
![Screenshot from 2024-01-04 12-08-03](https://github.com/biopython/biopython/assets/149134911/1174be7d-8f00-483c-8dc8-6b583c295797)
could you help me why it cannot import SCOPDATA from biodata.
Is it because of missing file or anything which I am Doing wrong while executing the file.

Thank you

**Comment by peterjc** [comment]
See https://github.com/biopython/biopython/blob/master/DEPRECATED.rst which says:

> Declared obsolete in release 1.80, and removed in release 1.82. Please use Bio.Data.PDBData instead.

That ought to say it was deprecated in 1.80 (see #3985), the removal was indeed in release 1.82 (see #4496).

Does the ``protein_letters_3to1_extended`` dictionary work for you instead?

**Comment by peterjc** [comment]
Hopefully you can try this locally, and submit a PR to aplhafold - I don't see an issue on this https://github.com/google-deepmind/alphafold/issues

i.e. I would try changing ``from Bio.Data import SCOPData`` to ``from Bio.Data.PDBData import protein_letters_3to1_extended`` and changing ``code = SCOPData.protein_letters_3to1.get(monomer.id, 'X')`` to just ``code =protein_letters_3to1.get(monomer.id, 'X')``
