### ISSUE TITLE
Version switching when viewing Sphinx documentation

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4567]
Following with #907 now closed via #4371, the Tutorial is now generated by Sphinx from RST files:

https://biopython.org/docs/dev/ [dev meaning master branch]
https://biopython.org/docs/dev/api/
https://biopython.org/docs/dev/Tutorial/

The URL pattern already in use for the API is intended to be version agnostic:

https://biopython.org/docs/1.80/api/
https://biopython.org/docs/1.82/api/
https://biopython.org/docs/dev/api/ [master branch]
https://biopython.org/docs/latest/api/ [symlink to 1.82 currently]

Right now the version links on the new pages need tweaking, e.g. https://biopython.org/docs/1.81/ does not currently work.

This could direct to https://biopython.org/docs/1.81/api/ or better be a placeholder page with that API link plus https://biopython.org/DIST/docs/tutorial/Tutorial-1.81.html and https://biopython.org/DIST/docs/tutorial/Tutorial-1.81.pdf for the old LaTeX based HTML/PDF.

**Comment by mdehoon** [comment]
@peterjc  The new tutorial looks much better than the old one. Thanks!

**Comment by peterjc** [comment]
Agreed - the HTML version is much nicer. Hopefully we'll not get too frustrated with RST, we're both old-hands at interpretting latex error messages afterall :wink:

**Comment by peterjc** [comment]
That's place holder pages done back to Biopthon 1.74, the first release of the API docs.

I'm hoping it won't be too much work to find/create single-file HTML versions of the older tutorials, currently https://github.com/biopython/DIST/tree/gh-pages/docs/tutorial only has them from v1.80 - see https://github.com/biopython/DIST/pull/9

**Comment by peterjc** [comment]
Done, seems to be working as I expect now.
