### ISSUE TITLE
SeqIO.parse() support type GFA

### ISSUE THREAD

**Issue by Adamtaranto** [biopython/biopython#4597]
Can SeqIO support reading GFA files into SeqRecord objects?

**Comment by peterjc** [comment]
You mean http://gfa-spec.github.io/GFA-spec/GFA1.html ?

Not currently, and I suspect never given the nature of GFA as a graph-based format, it doesn't make sense to think of it as a list of sequences.

**Comment by Adamtaranto** [comment]
Hi Peter,

At it's core GFA is absolutely a list of sequences. The Segment lines contain the sequence name and the sequence itself, just like a FASTA, plus some optional metadata tags that are easily parsed. 

In a number of modern assemblers (i.e. Hifiasm) it is the sole format in which contigs are output. While it is easy enough to [covert a list of sequences in GFA to a list of sequences in FASTA](https://www.biostars.org/p/169516/), it creates unnecessary duplication when it would be trivial to import sequences from the GFA directly.

The "graph" aspect of GFA files comes from the Link lines. These could be imported separately for use with NetworkX or similar. I agree it probably doesn't make sense to work with network data in Biopython, but the extra info available in GFA files doesn't change the fact that it is a perfectly valid place to store/extract sequence records.

**Comment by peterjc** [comment]
I was perhaps wrongly assuming the sequences would be relatively small fragments compared to contigs from traditional assemblers. As long as the list of sequences from GFA alone is useful, then OK as an input format.

Is this something you'd like to work on?

**Comment by michaelfm1211** [comment]
I can work on this. If we're just ignoring everything except the "S" lines, then it should be a fairly simple task.

**Comment by peterjc** [comment]
Thank you both for working on this and testing it. Let's hope people find it useful 👍
