### ISSUE TITLE
BigTm discrepancy calculated by biopython 1.76 and 1.81

### ISSUE THREAD

**Issue by jinlingwanggit** [biopython/biopython#4610]
### Setup

I am reporting a problem with Biopython1.76 and 1.81, Python version 3.10, and operating
system as follows: Ubuntu 20.04

>>> import sys; print(sys.version)
platform3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
mport Bio; print(Bio.__version__)CPython
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31

### Expected behaviour
Tm should be same calculated by biopython 1,76 and 1.81

### Actual behaviou
Big Tm discrepancy : 10 degree dif was observed

### Steps to reproduce

biopython 1.76
>>> from Bio.SeqUtils import MeltingTemp as mt
>>> mt.Tm_NN(seq='CAGCGGCAGGAGCAAGGC', nn_table=mt.R_DNA_NN1, saltcorr=5, Mg=0, Na=660)
67.38272499082632

biopython 1.81
>>> from Bio.SeqUtils import MeltingTemp as mt
>>> mt.Tm_NN(seq='CAGCGGCAGGAGCAAGGC', nn_table=mt.R_DNA_NN1, saltcorr=5, Mg=0, Na=660)
76.75187612485894

**Comment by peterjc** [comment]
This change happened from Biopython 1.78 (Sept 2020) to 1.79 (June 2021) in pull request #3281: Melting temp, correct nearest neighbor table for DNA/RNA hybridization, to fix issue #3280 - a discrepancy in our copy of the Sugimoto et al (1995) table.

See also changes #4240 in Biopython 1.82, and #3846 in Biopython 1.80.
