### ISSUE TITLE
Flipping origin-spanning locations with strand=None in circular molecules

### ISSUE THREAD

**Issue by manulera** [biopython/biopython#4611]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

```
3.11.6 (main, Nov  2 2023, 04:51:19) [Clang 14.0.0 (clang-1400.0.29.202)]
CPython
macOS-12.6.7-x86_64-i386-64bit
1.81
```
In Biopython and GenBank files, locations that span the origin are represented by a compound location. For example, for a sequence of length 6 a feature that spans two residues before the origin and the first residue after the origin is represented as `join{[4:6](+), [0:1](+)}`. When we flip that feature, it becomes `join{[0:2](-), [5:6](-)}`. The order of the loc.parts and the strand is inverted, so the meaning of the flipping is clear.

However, when a feature without strand spans the origin in the same way (`join{[4:6], [0:1]}`) and gets flipped, the parts get inverted (`join{[0:2], [5:6]}`). It might be confusing to interpret that this is a feature that spans the origin.

The same applies to multi-part features, see example below:

```python
from Bio.SeqFeature import SimpleLocation, SeqFeature
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from Bio.SeqIO import write
loc = SimpleLocation(4, 6, 1) + SimpleLocation(0, 1, 1)
print(loc) # join{[4:6](+), [0:1](+)}
print(loc._flip(6)) # join{[0:2](-), [5:6](-)}

loc = SimpleLocation(4, 6, None) + SimpleLocation(0, 1, None)
print(loc) # join{[4:6], [0:1]}
print(loc._flip(6)) # join{[0:2], [5:6]}


# Example of a multi-part location that spans the origin of a sequence with length 20
loc = SimpleLocation(15, 16, 1) + SimpleLocation(18, 20, 1) + SimpleLocation(0, 1, 1) + SimpleLocation(5, 10, 1)
print(loc) # join{[15:16](+), [18:20](+), [0:1](+), [5:10](+)}
print(loc._flip(20)) # join{[4:5](-), [0:2](-), [19:20](-), [10:15](-)}
seqr = SeqRecord(Seq('A'*20), features=[SeqFeature(loc, type='misc_feature')], annotations={'molecule_type': 'DNA'})
write([seqr], 'example_strand1_fwd.gb', 'genbank')
seqr_rvs = seqr.reverse_complement()
seqr_rvs.annotations['molecule_type'] = 'DNA'
write([seqr_rvs], 'example_strand1_rvs.gb', 'genbank')

loc = SimpleLocation(15, 16, None) + SimpleLocation(18, 20, None) + SimpleLocation(0, 1, None) + SimpleLocation(5, 10, None)
print(loc) # join{[15:16], [18:20], [0:1], [5:10]}
print(loc._flip(20)) # join{[4:5], [0:2], [19:20], [10:15]}
seqr = SeqRecord(Seq('A'*20), features=[SeqFeature(loc, type='misc_feature')], annotations={'molecule_type': 'DNA'})
seqr_rvs = seqr.reverse_complement()
seqr_rvs.annotations['molecule_type'] = 'DNA'
write([seqr], 'example_strandNone_fwd.gb', 'genbank')
write([seqr_rvs], 'example_strandNone_rvs.gb', 'genbank')

```
In the example, I save the sequences with multi-part features to gb files. As you can see, snapgene interprets properly all cases, except the inverted feature without strand. You can access [gb files here](https://github.com/biopython/biopython/files/14111421/files.zip).

![Screenshot 2024-01-31 at 12 06 38](https://github.com/biopython/biopython/assets/22526102/9bc1e8e6-c3ec-4875-a33b-80de70f5e28d)

If you agree that this is something that should be changed, I can give it a go and propose a solution.

**Comment by peterjc** [comment]
This is handled by the private ``._flip`` method of the ``CompoundLocation`` class:

https://github.com/biopython/biopython/blob/biopython-183/Bio/SeqFeature.py#L1641

As per the motivating example documented there, the behaviour assumes the original feature's part order is meaningful (which is true for a gene or CDS record, but perhaps not true for your misc_feature?) and therefore deliberately preserves the part order.

**Comment by manulera** [comment]
> assumes the original feature's part order is meaningful and therefore deliberately preserves the part order

Hi @peterjc, I agree with this when the strand is indicated, but not sure if that should be the case for features without a strand if we consider the origin-spanning case. For instance, say we wanted to indicate a recombination hotspot, or something that does not have an orientation. If it would fall on the origin, then the example could be the same as above:

```python
loc = SimpleLocation(4, 6, None) + SimpleLocation(0, 1, None)
print(loc) # join{[4:6], [0:1]}
print(loc._flip(6)) # join{[0:2], [5:6]}
```

The most important consequence (I think) is that the second feature will not be interpreted correctly by SnapGene or other sequence viewers. The solution for this would be to invert the parts when flipping a feature with `strand = None`. In a way this makes some sense because when Biopython writes features to GenBank, it treats `strand=None` features as plus-strand features, so to be plus-like in the reverse-complemented Seqrecord, the elements should be inverted.

Perhaps the multi-part example without strand is not very meaningful, I struggle to imagine a use-case for it.

I don't feel very strongly about this, but the sequence viewer case makes me prefer the alternative solution.

**Comment by peterjc** [comment]
So your suggestion would be reverse the parts order if all the parts have no strand? That seems OK to me - if any have a strand then the orientation and order is in someway meaningful.

[And yes, GenBank/EMBL locations sadly do not have an explicit way to say no strand]

**Comment by manulera** [comment]
Happy to contribute a pull request if you don't think this will be disruptive / cause problems

**Comment by peterjc** [comment]
I think this proposal is narrow enough not to cause many problems - and should fix your use case. I'd be happy to review a pull request on this.

**Comment by manulera** [comment]
Hi @peterjc, I tried to send you an email to your hutton email address that I found on publications, but it was bounced, so putting it here!

Hi Peter,

It's @manulera, I have made some contributions to bioptyhon in the past. I was wondering if there is a way to get some visibility for this remote Hackathon event we are planning. If you think it's relevant, let me know if there are some Biopython channels that we could use to spread the word.

Best,
Manu

We are planning a remote Hackathon for pydna (a Biopython-based library for simulating / documenting DNA engineering and cloning in silico). You can use this python library to plan your Gibson Assemblies, restriction-ligation cloning, etc.

We will also do a guided struggle session for those interested in getting started with the library. If you are interested, see this discussion on GitHub:

https://github.com/BjornFJohansson/pydna/discussions/258

**Comment by peterjc** [comment]
Hello @manulera - I'm no longer at the Hutton but expect the old email address to resume again once my promised honorary associate status begins. The Google address is a safer bet.

I suggest you:
* add your event to https://github.com/biohackathons/biohackathons.github.io to appear on https://biohackathons.github.io/ 
* mention it on the OBF slack too - link in footer of https://www.open-bio.org/
* add it to the next OBF newsletter - see https://github.com/OBF/newsletter
