### ISSUE TITLE
Big discrepancy for Tm calculated by bipython version1.76 and 1.81

### ISSUE THREAD

**Issue by jinlingwanggit** [biopython/biopython#4612]
### Setup

I am reporting a problem with Biopython version 1.76 and 1.81, Python version 3.8, 3.10, 3.12 and operating
system as follows:

```
platform3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31
```

### Expected behaviour
Tm was calculated with Tm_NN biopyhton version 1.76 and 1.81.  The output Tm value should be the same or very close.

### Actual behaviour
Big Tm difference was observed

### Steps to reproduce
note: the code was run in python3.8, 3.10 and 3.12. They all produced the same results

Python 3.10.13 [GCC 11.2.0] on linux
biopython version 1.76
>>> from Bio.SeqUtils import MeltingTemp as mt
>>> mt.Tm_NN(seq='CAGCGGCAGGAGCAAGGC', nn_table=mt.R_DNA_NN1, saltcorr=5, Mg=0, Na=660)
67.38272499082632

biopython version 1.81
>>> from Bio.SeqUtils import MeltingTemp as mt
>>> mt.Tm_NN(seq='CAGCGGCAGGAGCAAGGC', nn_table=mt.R_DNA_NN1, saltcorr=5, Mg=0, Na=660)
76.75187612485894

**Comment by michaelfm1211** [comment]
Isn't this identical to #4610?

**Comment by jinlingwanggit** [comment]
yes. it is. sorry for accidentally submitted twice
