### ISSUE TITLE
Broken/Outdated eutils DTD due to changes in ClinVar data representation of eutils

### ISSUE THREAD

**Issue by koopmann** [biopython/biopython#4615]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]
CPython
Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
1.83

### Expected behaviour

            handle = Entrez.esummary(db='clinvar', id='931337')
            record = Entrez.read(handle)
            handle.close()

I can properly get  the record and work with it.

### Actual behaviour

Get this errror:

<html><body>
<h1>ValidationError
       at /variantdata/ClinVarAssertion/entrez/create/5195</h1>
  <pre class="exception_value">Failed to find tag 'germline_classification' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.</pre>
  
Request Method: | GET
-- | --
http://localhost:8055/variantdata/ClinVarAssertion/entrez/create/5195
4.2.3
ValidationError
Failed to find tag 'germline_classification' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.
/home/lubuntu/.local/lib/python3.11/site-packages/Bio/Entrez/Parser.py, line 715, in startElementHandler
variantmanagement.variantdata.views.functions.addClinVarAssertionsFromEntrezView.addClinVarAssertionsFromEntrezView
/usr/bin/python3
3.11.7
['/mnt/d/vm_shared_folder/src/python/variantmanagement',  '/mnt/d/vm_shared_folder/src/python/variantmanagement',  '/home/lubuntu/.pycharm_helpers/pycharm_display',  '/usr/lib/python311.zip',  '/usr/lib/python3.11',  '/usr/lib/python3.11/lib-dynload',  '/home/lubuntu/.local/lib/python3.11/site-packages',  '/usr/local/lib/python3.11/dist-packages',  '/usr/lib/python3/dist-packages',  '/home/lubuntu/.pycharm_helpers/pycharm_matplotlib_backend',  '/mnt/d/vm_shared_folder/src/python/variantmanagement/variantmanagement',  '/mnt/d/vm_shared_folder/src/python/variantmanagement/variantmanagement']
Thu, 01 Feb 2024 15:23:13 +0100

</body>
</html>

### Steps to reproduce

see. above,

current Workaround:

            handle = Entrez.esummary(db='clinvar', id='931337', old_xml='T')
            record = Entrez.read(handle, validate=False)
            handle.close()

as hinted here :

https://github.com/ncbi/clinvar/blob/master/E-utilities.md

Solution would probably to get the right DTD from NCBI eutilities crew...

**Comment by peterjc** [comment]
The XML can declared which DTD it uses, and Biopython should fetch the file if not already stored locally. However as I recall not all the NCBI systems declare a DTD, and I've not personally looked at clinvar in particular.

**Comment by mdehoon** [comment]
When I run it, the latest DTD gets downloaded and stored locally.

@koopmann  Would you be able to create a PR to include the latest DTD?

**Comment by koopmann** [comment]
@mdehoon see my pull request https://github.com/biopython/biopython/pull/4619, hope this could help.
thanks also to @peterjc for clarifying.

**Comment by koopmann** [comment]
If i use this setup:

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CPython
Linux-6.2.0-1019-azure-x86_64-with-glibc2.35
1.83

And use this code:

`handle = Entrez.esummary(db='clinvar', id='931337')
    record = Entrez.read(handle)
    handle.close()`



it's working and i got:

`{'DocumentSummarySet': DictElement({'DocumentSummary': [DictElement({'obj_type': 'single nucleotide variant', 'accession': 'VCV000931337', 'accession_version': 'VCV000931337.', 'title': 'NM_000548.5(TSC2):c.3132-3T>C', 'variation_set': [{'measure_id': '920355', 'variation_xrefs': [{'db_source': 'dbSNP', 'db_id': '2089821106'}], 'variation_name': 'NM_000548.5(TSC2):c.3132-3T>C', 'cdna_change': 'NM_000548.5(TSC2):c.3132-3T>C', 'aliases': [], 'variation_loc': [{'status': 'current', 'assembly_name': 'GRCh38', 'chr': '16', 'band': '16p13.3', 'start': '2079273', 'stop': '2079273', 'inner_start': '', 'inner_stop': '', 'outer_start': '', 'outer_stop': '', 'display_start': '2079273', 'display_stop': '2079273', 'assembly_acc_ver': 'GCF_000001405.38', 'annotation_release': '', 'alt': '', 'ref': ''}, {'status': 'previous', 'assembly_name': 'GRCh37', 'chr': '16', 'band': '16p13.3', 'start': '2129274', 'stop': '2129274', 'inner_start': '', 'inner_stop': '', 'outer_start': '', 'outer_stop': '', 'display_start': '2129274', 'display_stop': '2129274', 'assembly_acc_ver': 'GCF_000001405.25', 'annotation_release': '', 'alt': '', 'ref': ''}], 'allele_freq_set': [], 'variant_type': 'single nucleotide variant', 'canonical_spdi': 'NC_000016.10:2079272:T:C'}], 'supporting_submissions': {'scv': ['SCV001368581'], 'rcv': ['RCV001197802']}, 'germline_classification': {'description': 'Uncertain significance', 'last_evaluated': '2018/01/01 00:00', 'review_status': 'criteria provided, single submitter', 'trait_set': [{'trait_xrefs': [{'db_source': 'Orphanet', 'db_id': '538'}, {'db_source': 'MedGen', 'db_id': 'C0751674'}, {'db_source': 'MONDO', 'db_id': 'MONDO:0011705'}, {'db_source': 'OMIM', 'db_id': '606690'}], 'trait_name': 'Lymphangiomyomatosis'}]}, 'clinical_impact_classification': {'description': '', 'last_evaluated': '1/01/01 00:00', 'review_status': '', 'trait_set': []}, 'oncogenicity_classification': {'description': '', 'last_evaluated': '1/01/01 00:00', 'review_status': '', 'trait_set': []}, 'record_status': '', 'gene_sort': 'TSC2', 'chr_sort': '16', 'location_sort': '00000000000002079273', 'variation_set_name': '', 'variation_set_id': '', 'genes': [{'symbol': 'TSC2', 'GeneID': '7249', 'strand': '+', 'source': 'submitted'}], 'molecular_consequence_list': ['intron variant'], 'protein_change': '', 'fda_recognized_database': ''}, attributes={'uid': '931337'})], 'DbBuild': 'Build240204-2050.1'}, attributes={'status': 'OK'})}`

**Comment by koopmann** [comment]
same return value with the parameter old_xml='T', so my workaround is just working because of the "validate=False".

So question is, what is different between:

Working env:
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CPython
Linux-6.2.0-1019-azure-x86_64-with-glibc2.35
1.83

Not working env:
3.11.7 (main, Dec 8 2023, 18:56:58) [GCC 11.4.0]
CPython
Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
1.83

**Comment by koopmann** [comment]
As i can get the record with:

3.11.7 (main, Dec 8 2023, 18:56:58) [GCC 11.4.0]
CPython
Linux-6.2.0-1019-azure-x86_64-with-glibc2.35
1.83

from a commandline python code, it seems that the problem could also be, that running the code embedded in my application it somehow doesnt fetch the DTD  / doesnt save it or used an outdated one...

**Comment by mdehoon** [comment]
> from a commandline python code, it seems that the problem could also be, that running the code embedded in my application it somehow doesnt fetch the DTD / doesnt save it or used an outdated one...

Thank you Yes, it seems that that is what happened. Maybe your application had no directory to save to.

**Comment by peterjc** [comment]
So there are at least three ways to fix your application?

- wait for Biopython 1.84 with the new DTD bundled in,
- patch the embedded application's Biopython install to add the new DTD
- work out why the Biopython inside your application couldn't cache the new DTD

The logic it uses is at https://github.com/biopython/biopython/blob/biopython-183/Bio/Entrez/Parser.py#L329 and would be ``~/.config/biopython/Bio/Entrez/DTDs/`` on a Linux system. Does the application have a home folder, and if so can it create and write to that location?

**Comment by koopmann** [comment]
just to be complete, your idea was perfectly right as i saw in the logs this message which indicates that i need to properly configure the home folder first:

"/usr/local/lib/python3.11/site-packages/Bio/Entrez/Parser.py:1075: UserWarning: Failed to save esummary_clinvar.dtd at /nonexistent/.config/biopython/Bio/Entrez/DTDs/esummary_clinvar.dtd"

**Comment by atturk** [comment]
> * patch the embedded application's Biopython install to add the new DTD

I am having the same problem, I was thinking to patch Biopython, but how do I do that?

I added this https://github.com/biopython/biopython/blob/master/Bio/Entrez/DTDs/esummary_clinvar.dtd to /lib/python3.9/site-packages/Bio/Entrez/DTDs inside my project virtual environment, but it still doesn't seem to work, I also tried running the Parser.py file but it still doesn't work, am I missing something?

**Comment by peterjc** [comment]
Adding any new DTD files to that folder is what I meant, perhaps something else is wrong.

Does your system also expand ``~`` to ``nonexistent``? If so we should probably catch this and issue a more useful warning. Do you know of a suitable fall back location for such systems without a home folder?

**Comment by atturk** [comment]
> Adding any new DTD files to that folder is what I meant, perhaps something else is wrong.
> 
> Does your system also expand `~` to `nonexistent`? If so we should probably catch this and issue a more useful warning. Do you know of a suitable fall back location for such systems without a home folder?

The problem is that I'm not getting the same UserWarning that koopmann is getting, here's the traceback:

(I ran the code outside the venv to make sure that wasn't causing the problem and put the dtd file inside /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Bio/Entrez/DTDs)

`Traceback (most recent call last):
  File "/Users/.../prova/prova.py", line 11, in <module>
    main()
    └ <function main at 0x10270e320>
  File "/Users/.../prova/prova.py", line 8, in main
    cvrecord(gene)
    │        └ 'ALS2'
    └ <function cvrecord at 0x1341f7490>
  File "/Users/.../prova/utils.py", line 95, in cvrecord
    record = Entrez.read(handle)
    │        │           └ <http.client.HTTPResponse object at 0x134405600>
    │        └ <module 'Bio.Entrez' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Bio/Entrez/__init__.p...
    └ {'Count': '377', 'RetMax': '377', 'RetStart': '0', 'IdList': ['3009677', '2973077', '2967173', '2831433', '2824945', '2812833', ...
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Bio/Entrez/__init__.py", line 518, in read
    record = handler.read(source)
             │            └ <http.client.HTTPResponse object at 0x134405600>
             └ <Bio.Entrez.Parser.DataHandler object at 0x1341df370>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Bio/Entrez/Parser.py", line 403, in read
    self.parser.ParseFile(stream)
    │                     └ <http.client.HTTPResponse object at 0x134405600>
    └ <Bio.Entrez.Parser.DataHandler object at 0x1341df370>
  File "/Users/sysadmin/build/v3.10.6/Modules/pyexpat.c", line 416, in StartElement
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Bio/Entrez/Parser.py", line 715, in startElementHandler
    raise ValidationError(tag)
          │               └ 'germline_classification'
          └ <class 'Bio.Entrez.Parser.ValidationError'>
Bio.Entrez.Parser.ValidationError: Failed to find tag 'germline_classification' in the DTD. To skip all tags that are not represented in the DTD, please call Bio.Entrez.read or Bio.Entrez.parse with validate=False.`

**Comment by koopmann** [comment]
I believe the error message within my project is individual and should not be the general prob, since i am within a special docker container and the user which runs the django app doesnt have a home folder (e.g. the "cd ~" is complaining that /nonexistent doesnt exist...so i will try to fix that first.
