### ISSUE TITLE
Missing esearch.dtd in biopython Ubuntu64 python-biopython v1.63-1

### ISSUE THREAD

**Issue by rolfschr** [biopython/biopython#462]
I was asked by your software to report this.

My machine:
`$ uname -a
Linux rschroeder-VirtualBox 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

My stderr:

``/usr/lib/python2.7/dist-packages/Bio/Entrez/Parser.py:525: UserWarning: Unable to load DTD file esearch.dtd.

Bio.Entrez uses NCBI's DTD files to parse XML files returned by NCBI Entrez.
Though most of NCBI's DTD files are included in the Biopython distribution,
sometimes you may find that a particular DTD file is missing. While we can
access the DTD file through the internet, the parser is much faster if the
required DTD files are available locally.

For this purpose, please download esearch.dtd from

http://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd

and save it either in directory

/usr/lib/python2.7/dist-packages/Bio/Entrez/DTDs

or in directory

/home/rschroeder/.biopython/Bio/Entrez/DTDs

in order for Bio.Entrez to find it.

Alternatively, you can save esearch.dtd in the directory
Bio/Entrez/DTDs in the Biopython distribution, and reinstall Biopython.

Please also inform the Biopython developers about this missing DTD, by
reporting a bug on https://github.com/biopython/biopython/issues or sign
up to our mailing list and emailing us, so that we can include it with the
next release of Biopython.

Proceeding to access the DTD file through the internet...

  warnings.warn(message)``

**Comment by peterjc** [comment]
Thank you for taking the time to report this. With hindsight (although it would have been an even longer message), we should have said update to the latest Biopython before reporting it. Biopython 1.63 is now a year old.

This particular DTD file was already added as of https://github.com/biopython/biopython/commit/6c2e7dba2842b14099a0adec0d1bc2edf31af390 and included with Biopython 1.64 (which will automatically download missing DTD files for you).

**Comment by rolfschr** [comment]
Ok, good to know. I'm running 14.04 LTS so I guess some people might have the same problem. If you tell people they should use a newer version before reporting a problem: say they can't for some reason and they might not report thinking it might be fixed. If it isn't, you miss this. So kinda political decision which err msg to throw. Anywah, thanks for biopython!
