### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by kevin2022lee** [biopython/biopython#4633]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python 3.7
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```
centos 7 python3.7 version 1.81

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

      from Bio import Entrez
        from Bio import SeqIO
        Entrez.email="lxk@kodiabio.com"
        SeqId=request.POST['seqid']
        Start=int(request.POST['start'])
        End=int(request.POST['end'])
        handle=Entrez.efetch(db="nucleotide",rettype="gb",retmote="text",id=SeqId)

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by kevin2022lee** [comment]
>>> import sys; print(sys.version)
3.7.12 (default, Feb 21 2024, 22:00:35) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-4.18.0-193.28.1.el8_2.x86_64-x86_64-with-centos-8.2.2004-Core
>>> import Bio; print(Bio.__version__)
1.81

**Comment by kevin2022lee** [comment]
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTPError at /seqidtoentrez/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP Error 400: Bad Request</pre>
Request Method: | POST
-- | --
http://www.kunkundashen.cn:81/seqidtoentrez/
3.0
HTTPError
HTTP Error 400: Bad Request
/www/server/pyporject_evn/py3primer3_venv/lib/python3.7/urllib/request.py in http_error_default, line 649
/www/server/pyporject_evn/py3primer3_venv/bin/uwsgi
3.7.12
['.',  '',  '/www/server/pyporject_evn/py3primer3_venv/lib/python37.zip',  '/www/server/pyporject_evn/py3primer3_venv/lib/python3.7',  '/www/server/pyporject_evn/py3primer3_venv/lib/python3.7/lib-dynload',  '/www/server/pyporject_evn/py3primer3_venv/lib/python3.7/site-packages']
Thu, 22 Feb 2024 14:58:30 +0000

**Comment by peterjc** [comment]
You're using a slightly old Biopython, but I don't think anything relevant changed since then:

https://github.com/biopython/biopython/commits/master/Bio/Entrez/__init__.py

This might be an intermitent NCBI Entrez error on their side, or it might be an error in your seqid. Can you share a self contained example - the actual string being passed as ``id=...`` in your example?

**Comment by kevin2022lee** [comment]
LG143642.1

**Comment by peterjc** [comment]
Thank you, that now gives a self-contained example - but this is working for me:

```python
from Bio import Entrez
Entrez.email="lxk@kodiabio.com"
handle=Entrez.efetch(db="nucleotide",rettype="gb",retmote="text",id="LG143642.1")
print(handle.url)
print(handle.read())
```

As a single shell command:

```
$ python -c 'from Bio import Entrez; Entrez.email="lxk@kodiabio.com"; handle=Entrez.efetch(db="nucleotide",rettype="gb",retmote="text",id="LG143642.1"); print(handle.url); print(handle.read())'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&rettype=gb&retmote=text&id=LG143642.1&tool=biopython&email=lxk%40kodiabio.com
LOCUS       LG143642                1518 bp    DNA     linear   PAT 01-FEB-2017
DEFINITION  KR 1020160021344-A/14: HPV standard materials for evaluating the
            analysis of HPV genotyping.
ACCESSION   LG143642
VERSION     LG143642.1
KEYWORDS    KR 1020160021344-A/14.
SOURCE      unidentified
  ORGANISM  unidentified
            unclassified sequences.
REFERENCE   1  (bases 1 to 1518)
  AUTHORS   Rhee,J.E., Kim,S.S., Kee,M.K., Hong,S.R., Jeong,M.S., Seo,H.H. and
            Kim,T.J.
  TITLE     HPV standard materials for evaluating the analysis of HPV
            genotyping
  JOURNAL   Patent: KR 1020160021344-A 14 25-FEB-2016;
            Korea Center for Disease Control and Prevention|Cheil General
            Hospital & Women&quot;s Healthcare Center
COMMENT     KN   KR 1020140105893-A/14
            AN   KR 1020140105893
            AD   2014-08-14
            PN   KR 1020160021344
            PD   2016-02-25
            AT   HPV standard materials for evaluating the analysis of HPV
            AT   genotyping
            AI   Rhee, Jee Eun|Kim, Sung Soon|Kee, Mee Kyung|Hong, Sung
            AI   Ran|Jeong, Mi Seon|Seo, Hyun Hee|Kim, Tae Jin
            AA   Korea Center for Disease Control and Prevention|Cheil General
            AA   Hospital & Women's Healthcare Center
            PR
            OS   HPV standard for HPV 68b
            TY   DNA
            FH   Key     Location/Qualifiers.
FEATURES             Location/Qualifiers
     source          1..1518
                     /organism="unidentified"
                     /mol_type="unassigned DNA"
                     /db_xref="taxon:32644"
ORIGIN      
        1 atggcattgt ggcgctctag cgacaacatg gtgtatttgc ctcccccctc agtggcgaag
       61 gttgtcaata cagatgatta cgtaacacgc actggcattt attattatgc tggtacatct
      121 aggttattaa ctgtaggcca tccatatttt aaggtcccta tgtctggggg ccgcaagcag
      181 gacattccta aggtgtctgc atatcaatac agggtgttta gggtttccct acctgatcct
      241 aataaattta gtcttcctga gtctacatta tataaccctg atacgcagcg attggtatgg
      301 gcctgtgttg gtgttgaaat aggtaggggg cagccattag gtgttggcct tagtgggcat
      361 ccattatata ataggctaga tgatactgaa aattccccgt tttcctctaa caaaaatcct
      421 aaggacagta gggacaatgt ttcagtggac tataaacaaa cgcaactatg tattataggc
      481 tgtgttcctg ccattgggga gcactgggcc aaaggtaaat cttgtaagcc taacaatgtg
      541 cagcccgggg actgtccacc attagaatta gtaaatacac ctattcagga tggcgatatg
      601 attgatacag gatatggtgc tatggacttt agtacattac aagaaacaaa aagcgaggtg
      661 cctttagata tatgtcaatc ggtctgcaaa tatcctgact atttacaaat gtctgcagat
      721 gtctatgggg acagtatgtt tttttgttta cgtagggaac agttatttgc taggcatttt
      781 tggaatagag ggggcatggt aggggacact attcctactg aattgtatat taagggcact
      841 gacatacgtg acagtcctag tagttatgtg tatgccccct cgcctagtgg gtctatggta
      901 tcctcagact cccagttatt taacaagccc tattggctgc acaaggcaca aggacacaac
      961 aatggtattt gttggcataa tcaattattt cttactgttg tggataccac tcgcagtact
     1021 aattttactt tgtctactac tactgaatca gctgtaccaa atatttatga tcctaataaa
     1081 tttaaggaat atgttaggca tgttgaggaa tatgatttgc aattcatatt tcagttgtgt
     1141 actataacat tgtcaactga tgtaatgtcc tatatacata ctatgaatcc tgctatttta
     1201 gatgattgga attttggtgt tgcccctccg ccatctgcta gtcttgtaga tacataccgc
     1261 tatctgcaat cagcagcaat tacatgtcag aaagacgccc ctgcacctac taaaaaggat
     1321 ccatatgatg gcctaaactt ttggaatgta aatttaaagg aaaagtttag ttctgaactg
     1381 gaccagtttc ctttaggacg caaatttctt ttacaggcag gtgtccgccg acgacccact
     1441 ataggccccc gcaaacgccc tgccacagca cctactgcat ctacctctaa gcacaaacgt
     1501 aaacgtgtgt caaagtaa
//
```

This is consistent with my guess that it was a temporary NCBI server issue. But also I am running the current Biopython code, and doing this from a different network.

**Comment by kevin2022lee** [comment]
thanks peter,
 I found the reasion that because the network case. I visited GitHub based on proxy network access.When I accessed NCBI through this proxy network, I received this error

nice guy 
kevin

**Comment by kevin2022lee** [comment]
@peterjc  you re nice guy ！
