### ISSUE TITLE
Custom scoring function for aligner rather than a substitution matrix

### ISSUE THREAD

**Issue by offbynull** [biopython/biopython#4642]
Is this an option? I browsed through the Python and CPP code and found one for gap scoring but not for scoring two elements against each other. If I wanted to patch in such a function into the aligner, is there a central place in the code that I could do it? Or does it need to be patched in multiple places?

EDIT: Also, is it possible for my sequences to be some iterable type other than string? For example, instead of aligning two strs, could I align two list[tuple[str, int]].

**Comment by peterjc** [comment]
Do you mean standard scoring matrices like BLOSUM?
https://biopython.org/DIST/docs/tutorial/Tutorial-1.83.html#sec133
https://biopython.org/docs/dev/Tutorial/chapter_pairwise.html#loading-predefined-substitution-matrices

And yes, they don't have to be strings:
https://biopython.org/DIST/docs/tutorial/Tutorial-1.83.html#sec143
https://biopython.org/docs/dev/Tutorial/chapter_pairwise.html#generalized-pairwise-alignments

**Comment by peterjc** [comment]
If your function has the form ``scorer(letter1, letter2)``, then surely you can use it to build a static scoring matrix?

(The only reason I can see not to do that, is if your use case the set of "letters" is vastly bigger than expected with proteins or nucleotides, such that the matrix would be too large to build due to memory or run time.)

Beyond that, we'd have to hear from @mdehoon

**Comment by offbynull** [comment]
Imagine the following scenario: Instead of scoring two letters, you're
scoring two tuple[str, float]. The first element of the float is a regular
letter and the second letter is a scaling factor:

```
def scorer(e1: tuple[str, float], e2: tuple[str, float]) -> float:
    return matrix[e1[0], e2[0]] * e1[1] * e2[2]
```

In this case, building a static scoring matrix wouldn't be all that
feasible.

**Comment by mdehoon** [comment]
Floats and tuples are hashable, so in principle it is possible.
However, you would have to precalculate the scores for all possible tuple pairs that can appear in the substitution matrix.

**Comment by peterjc** [comment]
Point taken, floats are technically hashable in Python, but using them that way is unusual.

Could the class accept a dictionary-like or array-like class as the substitution matrix, but which computes the lookup values at run time?

**Comment by offbynull** [comment]
Before anyone tries to tackle this problem, let me ask this: Would a bioinformatician / computational biologist have a need for something like this? If the answer is no, maybe it makes sense to skip it. I'll admit my usecase is outside of bioinformatics. The reason I chose biopython is because (in my mind) it's the de facto python library for alignments.

**Comment by mdehoon** [comment]
> Could the class accept a dictionary-like or array-like class as the substitution matrix, but which computes the lookup values at run time?

It cannot. The aligner uses the buffer interface to access the values in the substitution matrix directly from the C code.

**Comment by mdehoon** [comment]
> Before anyone tries to tackle this problem, let me ask this: Would a bioinformatician / computational biologist have a need for something like this? 

One scenario is where the letters in the sequences have some weight, and we want to include the weight in the alignment score. But until someone actually has a concrete need for that in bioinformatics, I would say it is not needed in Biopython.

**Comment by offbynull** [comment]
What you described is exactly what I'm trying to do. If there's no need for
something like this in biopython right now, I can go ahead and write
something custom myself.

I think this issue can be closed.

Thanks.
