### ISSUE TITLE
Compile error on GCC 12 with Python3.11

### ISSUE THREAD

**Issue by surak** [biopython/biopython#4643]
OS: Linux Redhat Enterprise 8.9
Python: 3.11.3
GCC 12.3.0

While trying to install `prody==2.2.0`, I end up with this on biopython's compile process:

```
 gcc -DNDEBUG -g -fwrapv -O3 -Wall -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -fPIC -IBio -I/p/scratch/dachsador/DiffDock/sc_venv_template/venv/include -I/p/software/juwelsbooster/stages/2024/software/Python/3.11.3-GCCcore-12.3.0/include/python3.11 -c Bio/triemodule.c -o build/temp.linux-x86_64-cpython-311/Bio/triemodule.o
            Bio/triemodule.c: In function ‘PyInit_trie’:
            Bio/triemodule.c:837:25: error: lvalue required as left operand of assignment
              837 |     Py_TYPE(&Trie_Type) = &PyType_Type;
                  |                         ^
            error: command '/p/software/juwelsbooster/stages/2024/software/GCCcore/12.3.0/bin/gcc' failed with exit code 1
            [end of output]
```

**Comment by peterjc** [comment]
You didn't say which version of Biopython you are trying to install, but it must be quite old. Quoting https://github.com/biopython/biopython/blob/master/DEPRECATED.rst

> Bio.trie, Bio.triefind
> These modules were declared obsolete in Release 1.72, deprecated in Release 1.73, and removed in Release 1.77. We suggest pygtrie as an alternative library implementing a trie data structure.

You're not trying to use Python 2 are you?

**Comment by surak** [comment]
Look at the subject of the issue again ;-) It's python 3.11

It actually comes from https://github.com/gcorso/DiffDock - which tries to install prody 2.2.0, which itself is from 2022. Checking their pyproject.toml from 2.2.0, it says "biopython<=1.76"

This is for a user of our supercomputer. I will just tell them that this diffdock won't install, if it's that old. Thanks.

**Comment by peterjc** [comment]
Looking back at https://pypi.org/project/biopython/1.76/#files we did have wheels, but only for as recent as Python 3.8 - so you can't just install a wheel, thus you have to compile.

I'd guess GCC has gotten stricter, and that code would have compiled OK on an older GCC?

I'm almost certain prody doesn't need the trie module, so if you really needed this, I would suggest you edit the Biopython 1.76 source code to skip that module. i.e. comment out this in ``setup.py``:

```python
        EXTENSIONS.extend(
            [
                Extension(
                    "Bio.trie", ["Bio/triemodule.c", "Bio/trie.c"], include_dirs=["Bio"]
                )
            ]
        )
```

**Comment by surak** [comment]
Thanks, I will give it a try.

That thing also depends on openfold. It's going to be a long night...
