### ISSUE TITLE
Bug: Compatibility problem in python3: SeqIO.parse(gzip.open("seq.fq.gz"),"fastq")

### ISSUE THREAD

**Issue by shenwei356** [biopython/biopython#466]
CODE
====

	from Bio import SeqIO
	import gzip

	file = "test.fq.gz"
	fh = gzip.open(file, 'rb')

	for record in SeqIO.parse(fh,'fastq'):
		print(record.id)

	fh.close()

it works in python2, fails in python3

ERROR
====

	Traceback (most recent call last):
	File "/home/shenwei/tmp/python/test.py", line 7, in <module>
		for record in SeqIO.parse(fh,'fastq'):
	File "/usr/lib64/python3.4/site-packages/Bio/SeqIO/__init__.py", line 591, in parse
		for r in i:
	File "/usr/lib64/python3.4/site-packages/Bio/SeqIO/QualityIO.py", line 1033, in FastqPhredIterator
		for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
	File "/usr/lib64/python3.4/site-packages/Bio/SeqIO/QualityIO.py", line 902, in FastqGeneralIterator
		raise ValueError("Is this handle in binary mode not text mode?")
	ValueError: Is this handle in binary mode not text mode?

**Comment by peterjc** [comment]
Python 2 is more forgiving about text versus binary mode, but in Python 3 this difference is critical.

Biopython is trying to tell you to open the file in text mode NOT binary mode. What happens if you do this? This used to be broken in early Python 3, but it was fixed - see http://bugs.python.org/issue13989

**Comment by shenwei356** [comment]
Thank you @peterjc.

It works with *io.TextIOWrapper* in py3 (Python 3.4.1), but failed in py2.

    fh = io.TextIOWrapper(gzip.open(file, 'rb')) # same result with 'r' mode

**Comment by peterjc** [comment]
Sorry I was unclear - this ought to work on both Python 2.6, 2.7, 3.3 and 3.4

```
from Bio import SeqIO
import gzip

fh = gzip.open('test.fq.gz', 'rt')
for record in SeqIO.parse(fh, 'fastq'):
    print(record.id)
fh.close()
```

**Comment by shenwei356** [comment]
It works, thank you @peterjc.
