### ISSUE TITLE
BiopythonDeprecationWarning in Bio.pairwise2

### ISSUE THREAD

**Issue by shi-scala** [biopython/biopython#4671]
Hi,

I've been trying to resolve this deprecation by using the Bio.Align.PairwiseAligner module but have not been able to do so.
We use a python function to determine the alignment score in order to align tuples of sequence and secondary structure:
As an example:
SeqA = [('F', 'E'), ('T', 'E'), ...]
SeqB = [('F', 'E'), ('T', 'E'), ...]

How can I use a custom python function to determine the score between such tuples using Bio.Align.PairwiseAligner?

Thank you

**Comment by mdehoon** [comment]
> How can I use a custom python function to determine the score between such tuples using Bio.Align.PairwiseAligner?

If you can write the sequences as

```python
SeqA = ["FE", "TE", ...]
SeqB = ["FE", "TE", ...]
```

then define your alphabet as

```python
>>> alphabet = ("EE", "FE", "TE", ...)
```

Create a substitution matrix and fill it

```python
>>> from Bio.Align import substitution_matrices
>>> a = substitution_matrices.Array(alphabet, dims=2)
>>> for key1 in alphabet:
...     for key2 in alphabet:
...        a[key1+key2] = yourfunction(key1, key2)
```

Create the aligner and set its substitution matrix to the substitution matrix you just created:

```python
>>> from Bio.Align import PairwiseAligner
>>> aligner = PairwiseAligner()
>>> aligner.substitution_matrix = a
```
and align:
```python
>>> alignments = aligner.align(["EE", "EF", "FF"], ["EE", "FF"])
>>> alignment = next(alignments)
>>> print(alignment)
EE EF FF
|| -- ||
EE -- FF

```

**Comment by shi-scala** [comment]
That's a really cool implementation.
Thank you, I'll give it a try.

**Comment by peterjc** [comment]
Closing as this appears to have been resolved.
