### ISSUE TITLE
enhancement: make it possible to randomly access tabix indexed files

### ISSUE THREAD

**Issue by tommycarstensen** [biopython/biopython#468]
Are there any plans to make it possible to use a .tbi file to randomly access the associated bgzipped file?

**Comment by peterjc** [comment]
No firm plans currently. @eparker05 (Evan) has a look at this as part of his Google Summer of Code project for lazy-loading of sequence formats, with finer level indexing to allow pulling out parts of sequences (or their annotations).

**Comment by eparker05** [comment]
The product of the lazy loading parser GSoC effort is available in the feature branch associated with my pull request. For a variety of reasons I used an indexing format based on sqlite similar to the existing bio-python record-indexes. If this is a current need of yours I would encourage you to patch in my branch. 

As for the broader status of Python detailed index formats; there is at least one project I know of that supports faidx (https://github.com/mdshw5/pyfaidx) but it isn't yet oriented toward integration with biopython (although it would be easy enough to write a comparability layer). AFAIK there's no direct support for tabix indexes in any python bioinformatics project.

**Comment by tommycarstensen** [comment]
@eparker05 Check out pytabix, which is just a Python interface for tabix: https://pypi.python.org/pypi/pytabix

However, it doesn't allow me to retrieve the last line of a file without knowing the coordinate of the last line.

I'll close this issue.

**Comment by mdehoon** [comment]
I believe pysam can also handle tabix-indexed files.

**Comment by tommycarstensen** [comment]
@mdehoon Yes and no. If the file is indexed and you know the positions, then it can.
