### ISSUE TITLE
Entrez egquery example doctest breaking

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4698]
Our doctest:

```pycon
>>> from Bio import Entrez
>>> Entrez.email = "Your.Name.Here@example.org"
>>> handle = Entrez.egquery(term="biopython")
>>> record = Entrez.read(handle)
>>> handle.close()
>>> for row in record["eGQueryResult"]:
...     if "pmc" in row["DbName"]:
...         print(int(row["Count"]) > 60)
True
```

is failing with ``urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>``

This appears to be a general problem with EGQuery, consider the example given on https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EGQuery which is: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/egquery.fcgi?term=asthma

Right now in Firefox this redirects to https://ext-http-eutils.linkerd.ncbi.nlm.nih.gov/gquery?term=asthma&retmode=xml and gives "Server Not Found".

i.e. This looks like an NCBI problem, not a Biopython error.

**Comment by peterjc** [comment]
Workaround https://ncbi.nlm.nih.gov/gquery?term=asthma&retmode=xml works (no leading www or eutils subdomain).

**Comment by dk33145** [comment]
This seems to have broken egquery, possible to have a hotfix to the new url?

**Comment by peterjc** [comment]
This is an NCBI issue, they clearly document the domain used should be https://eutils.ncbi.nlm.nih.gov and it ought to be a relatively simple redirection fix on their side.

I would encourage you to ask the NCBI to help the prioritize this - you can cite my case number and/or this issue if you like.

**Comment by peterjc** [comment]
I'm afraid the NCBI are looking at withdrawing EGQuery - and I would expect something official documenting this in due course. For Biopython, we will have to deprecate and remove the EGQuery wrapper (leaving this issue open to track that).

If you need guidance on what to use instead, please do contact the NCBI.
