### ISSUE TITLE
Bio.Align.Alignment doesn't contain chromosome data?

### ISSUE THREAD

**Issue by royjacobson** [biopython/biopython#4704]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0]
CPython
Linux-5.14.0-162.6.1.el9_1.x86_64-x86_64-with-glibc2.34
1.83
```

I'm reading a BED alignment file using `Align.bed.AlignmentReader`, and the resulting `Alignment` objects don't seem to contain the `chrom` column anywhere except in the `id` field inside the first sequence. Is this the intended way to read this information?

**Comment by mdehoon** [comment]
@royjacobson  Please show your code.

**Comment by mdehoon** [comment]
@royjacobson  Can we close this issue?
