### ISSUE TITLE
BinaryCIF Parser

### ISSUE THREAD

**Issue by Will-Tyler** [biopython/biopython#4705]
### Background

I plan to implement a BinaryCIF parser, and I am opening this issue as a forum for those who are interested to discuss the implementation of the parser.

BinaryCIF is a data format that stores CIF files using an efficient binary encoding (rather than a text encoding such as ASCII). BinaryCIF uses several compression methods to compress the CIF data, then encodes the compressed CIF data using a binary encoding called [MessagePack](https://msgpack.org/). The specification of the BinaryCIF format is [here](https://github.com/molstar/BinaryCIF/blob/master/encoding.md).

### Existing BinaryCIF Parsers

The [py-mmcif](https://github.com/rcsb/py-mmcif) repository contains a pure-Python [BinaryCIF parser](https://github.com/rcsb/py-mmcif/blob/master/mmcif/io/BinaryCifReader.py). The parser uses [msgpack](https://pypi.org/project/msgpack/) to decode the BinaryCIF data. The `msgpack` module returns a dictionary with the decoded CIF data. The parser then uses Python methods/generators to decompress the decoded CIF data.

Another pure-Python approach exists [here](https://github.com/ihmwg/python-ihm/blob/main/ihm/format_bcif.py) with essentially the same approach.

### Proposed Biopython Implementation

I propose taking a similar approach to the two existing BinaryCIF parsers listed above: decoding the CIF data using `msgpack` and decompressing the CIF data using pure Python. The `msgpack` package supports Python versions 3.8 and greater—the same versions that Biopython supports. The `msgpack` package would be an optional requirement—only required to parse BinaryCIF files.

After decoding the CIF data using `msgpack`, the implementation would use Python methods/generators to decompress the decoded CIF data.

### Discussion

Using the `msgpack` package saves us the effort of writing and maintaining our own performant code to decode the MessagePack-formatted data. However, using this package does require the user to install it to use the BinaryCIF parser. Finally, using pure Python allows the parser to build a dictionary containing the CIF information and build the PDB structure similar to the way the mmCIF parser works.

**Comment by Will-Tyler** [comment]
Tagging @JoaoRodrigues (Bio.PDB maintainer)

**Comment by peterjc** [comment]
Handling ``msgpack`` as a soft dependency following approach used for the ``mmtf-python`` dependency for MMTF format seems very reasonable.
