### ISSUE TITLE
[feature] Phylo: miter settings when drawing trees

### ISSUE THREAD

**Issue by Kiri2002** [biopython/biopython#4709]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
![image](https://github.com/biopython/biopython/assets/125180256/1130c767-df27-423d-8597-fbbd0a617af1)

(*Please fill this in*)

### Actual behaviour
![image](https://github.com/biopython/biopython/assets/125180256/8d22220c-8c27-42eb-a44e-2c4422753f8c)

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)
- 1. run code:
```
from Bio import Phylo
import matplotlib.pyplot as plt
import io

newick = "(((A:0.1,B:0.2):0.3,(C:0.4,D:0.5):0.6):0.7,E:1.0);"
tree = Phylo.read(io.StringIO(newick), "newick")
Phylo.draw(tree)
```
- 2. zoom in

**Comment by peterjc** [comment]
This is the miter setting for corners when joining lines. One option is rounded ends of straight lines, or for what you want square end which extend beyond the specific end coordinates by half the line width.

This might be a one line of code fix to set an optional argument…
