### ISSUE TITLE
Blank altlocs in duplicate residue ILE (' ', 105, ' ')

### ISSUE THREAD

**Issue by non-name-2020** [biopython/biopython#4713]
When using MMCIFParser to parse "5o61.cif", raised Exception: Blank altlocs in duplicate residue ILE (' ', 105, ' ')

python==3.9
biopython==1.80

The code:

from Bio.PDB import MMCIFParser
cif_parser = MMCIFParser(QUIET=True)
cif_filepath = "example/5o61.cif"
structure = cif_parser.get_structure("5o61", cif_filepath)

How to solve it?
Thanks.

**Comment by JoaoRodrigues** [comment]
I think this might be a problem with that structure, not our parser. If you open the mmCIF file and look at the offending residue (ILE 105 of chain BI), you see this:

```
ATOM   138708 N  N     . ARG QA 43 105  ? 50.296  175.210 127.732 1.00 78.20  ?  105  ARG BI N     1 
ATOM   138709 C  CA    . ARG QA 43 105  ? 49.342  174.100 127.669 1.00 77.20  ?  105  ARG BI CA    1 
ATOM   138710 C  C     . ARG QA 43 105  ? 47.953  174.589 127.235 1.00 83.06  ?  105  ARG BI C     1 
ATOM   138711 O  O     . ARG QA 43 105  ? 47.216  173.890 126.508 1.00 89.24  ?  105  ARG BI O     1 
ATOM   138712 C  CB    . ARG QA 43 105  ? 49.270  173.376 129.018 1.00 76.20  ?  105  ARG BI CB    1 
ATOM   138713 C  CG    . ARG QA 43 105  ? 50.459  172.442 129.275 1.00 69.65  ?  105  ARG BI CG    1 
ATOM   138714 C  CD    . ARG QA 43 105  ? 50.843  172.419 130.745 1.00 72.27  ?  105  ARG BI CD    1 
ATOM   138715 N  NE    . ARG QA 43 105  ? 51.151  171.070 131.207 1.00 72.98  ?  105  ARG BI NE    1 
ATOM   138716 C  CZ    . ARG QA 43 105  ? 50.365  170.362 132.016 1.00 74.42  ?  105  ARG BI CZ    1 
ATOM   138717 N  NH1   . ARG QA 43 105  ? 49.227  170.880 132.459 1.00 75.87  1  105  ARG BI NH1   1 
ATOM   138718 N  NH2   . ARG QA 43 105  ? 50.718  169.139 132.393 1.00 76.05  ?  105  ARG BI NH2   1 
ATOM   138719 N  N     . ALA QA 43 106  ? 47.609  175.801 127.666 1.00 86.25  ?  106  ALA BI N     1 
ATOM   138720 C  CA    . ALA QA 43 106  ? 46.355  176.435 127.263 1.00 93.74  ?  106  ALA BI CA    1 
ATOM   138721 C  C     . ALA QA 43 106  ? 46.313  176.720 125.755 1.00 94.66  ?  106  ALA BI C     1 
ATOM   138722 O  O     . ALA QA 43 106  ? 45.240  176.675 125.139 1.00 97.11  ?  106  ALA BI O     1 
ATOM   138723 C  CB    . ALA QA 43 106  ? 46.135  177.728 128.051 1.00 95.46  ?  106  ALA BI CB    1 
ATOM   138724 N  N     . LEU QA 43 107  ? 47.474  177.014 125.166 1.00 90.89  ?  107  LEU BI N     1 
ATOM   138725 C  CA    . LEU QA 43 107  ? 47.546  177.222 123.715 1.00 91.42  ?  107  LEU BI CA    1 
ATOM   138726 C  C     . LEU QA 43 107  ? 47.327  175.923 122.915 1.00 98.52  ?  107  LEU BI C     1 
ATOM   138727 O  O     . LEU QA 43 107  ? 46.895  175.973 121.761 1.00 101.20 ?  107  LEU BI O     1 
ATOM   138728 C  CB    . LEU QA 43 107  ? 48.886  177.861 123.322 1.00 83.80  ?  107  LEU BI CB    1 
ATOM   138729 C  CG    . LEU QA 43 107  ? 49.102  179.293 123.825 1.00 84.46  ?  107  LEU BI CG    1 
ATOM   138730 C  CD1   . LEU QA 43 107  ? 50.281  179.980 123.126 1.00 88.01  ?  107  LEU BI CD1   1 
ATOM   138731 C  CD2   . LEU QA 43 107  ? 47.831  180.117 123.683 1.00 87.49  ?  107  LEU BI CD2   1 
ATOM   138732 N  N     . ILE QA 43 108  ? 47.622  174.772 123.523 1.00 100.98 ?  105  ILE BI N     1 
ATOM   138733 C  CA    . ILE QA 43 108  ? 47.336  173.468 122.901 1.00 105.61 ?  105  ILE BI CA    1 
ATOM   138734 C  C     . ILE QA 43 108  ? 45.865  173.100 123.085 1.00 101.71 ?  105  ILE BI C     1 
ATOM   138735 O  O     . ILE QA 43 108  ? 45.257  172.470 122.214 1.00 100.89 ?  105  ILE BI O     1 
ATOM   138736 C  CB    . ILE QA 43 108  ? 48.235  172.327 123.472 1.00 101.45 ?  105  ILE BI CB    1 
ATOM   138737 C  CG1   . ILE QA 43 108  ? 49.719  172.685 123.324 1.00 99.03  ?  105  ILE BI CG1   1 
ATOM   138738 C  CG2   . ILE QA 43 108  ? 47.926  170.980 122.792 1.00 89.98  ?  105  ILE BI CG2   1 
ATOM   138739 C  CD1   . ILE QA 43 108  ? 50.093  173.225 121.954 1.00 96.18  ?  105  ILE BI CD1   1 
ATOM   138740 N  N     . LEU QA 43 109  ? 45.296  173.489 124.225 1.00 100.16 ?  109  LEU BI N     1 
ATOM   138741 C  CA    . LEU QA 43 109  ? 43.856  173.318 124.429 1.00 100.15 ?  109  LEU BI CA    1 
ATOM   138742 C  C     . LEU QA 43 109  ? 43.021  174.134 123.424 1.00 105.10 ?  109  LEU BI C     1 
ATOM   138743 O  O     . LEU QA 43 109  ? 42.058  173.613 122.852 1.00 105.33 ?  109  LEU BI O     1 
ATOM   138744 C  CB    . LEU QA 43 109  ? 43.469  173.698 125.860 1.00 102.09 ?  109  LEU BI CB    1 
ATOM   138745 C  CG    . LEU QA 43 109  ? 44.151  172.889 126.968 1.00 103.80 ?  109  LEU BI CG    1 
ATOM   138746 C  CD1   . LEU QA 43 109  ? 43.611  173.296 128.342 1.00 101.51 ?  109  LEU BI CD1   1 
ATOM   138747 C  CD2   . LEU QA 43 109  ? 43.998  171.384 126.721 1.00 93.73  ?  109  LEU BI CD2   1
```

Seems like the "correct" residue number should be 108? You could reach out to the wwPDB and ask them to review the entry and make sure this is indeed a mistake.

**Comment by non-name-2020** [comment]
> I think this might be a problem with that structure, not our parser. If you open the mmCIF file and look at the offending residue (ILE 105 of chain BI), you see this:
> 
> ```
> ATOM   138708 N  N     . ARG QA 43 105  ? 50.296  175.210 127.732 1.00 78.20  ?  105  ARG BI N     1 
> ATOM   138709 C  CA    . ARG QA 43 105  ? 49.342  174.100 127.669 1.00 77.20  ?  105  ARG BI CA    1 
> ATOM   138710 C  C     . ARG QA 43 105  ? 47.953  174.589 127.235 1.00 83.06  ?  105  ARG BI C     1 
> ATOM   138711 O  O     . ARG QA 43 105  ? 47.216  173.890 126.508 1.00 89.24  ?  105  ARG BI O     1 
> ATOM   138712 C  CB    . ARG QA 43 105  ? 49.270  173.376 129.018 1.00 76.20  ?  105  ARG BI CB    1 
> ATOM   138713 C  CG    . ARG QA 43 105  ? 50.459  172.442 129.275 1.00 69.65  ?  105  ARG BI CG    1 
> ATOM   138714 C  CD    . ARG QA 43 105  ? 50.843  172.419 130.745 1.00 72.27  ?  105  ARG BI CD    1 
> ATOM   138715 N  NE    . ARG QA 43 105  ? 51.151  171.070 131.207 1.00 72.98  ?  105  ARG BI NE    1 
> ATOM   138716 C  CZ    . ARG QA 43 105  ? 50.365  170.362 132.016 1.00 74.42  ?  105  ARG BI CZ    1 
> ATOM   138717 N  NH1   . ARG QA 43 105  ? 49.227  170.880 132.459 1.00 75.87  1  105  ARG BI NH1   1 
> ATOM   138718 N  NH2   . ARG QA 43 105  ? 50.718  169.139 132.393 1.00 76.05  ?  105  ARG BI NH2   1 
> ATOM   138719 N  N     . ALA QA 43 106  ? 47.609  175.801 127.666 1.00 86.25  ?  106  ALA BI N     1 
> ATOM   138720 C  CA    . ALA QA 43 106  ? 46.355  176.435 127.263 1.00 93.74  ?  106  ALA BI CA    1 
> ATOM   138721 C  C     . ALA QA 43 106  ? 46.313  176.720 125.755 1.00 94.66  ?  106  ALA BI C     1 
> ATOM   138722 O  O     . ALA QA 43 106  ? 45.240  176.675 125.139 1.00 97.11  ?  106  ALA BI O     1 
> ATOM   138723 C  CB    . ALA QA 43 106  ? 46.135  177.728 128.051 1.00 95.46  ?  106  ALA BI CB    1 
> ATOM   138724 N  N     . LEU QA 43 107  ? 47.474  177.014 125.166 1.00 90.89  ?  107  LEU BI N     1 
> ATOM   138725 C  CA    . LEU QA 43 107  ? 47.546  177.222 123.715 1.00 91.42  ?  107  LEU BI CA    1 
> ATOM   138726 C  C     . LEU QA 43 107  ? 47.327  175.923 122.915 1.00 98.52  ?  107  LEU BI C     1 
> ATOM   138727 O  O     . LEU QA 43 107  ? 46.895  175.973 121.761 1.00 101.20 ?  107  LEU BI O     1 
> ATOM   138728 C  CB    . LEU QA 43 107  ? 48.886  177.861 123.322 1.00 83.80  ?  107  LEU BI CB    1 
> ATOM   138729 C  CG    . LEU QA 43 107  ? 49.102  179.293 123.825 1.00 84.46  ?  107  LEU BI CG    1 
> ATOM   138730 C  CD1   . LEU QA 43 107  ? 50.281  179.980 123.126 1.00 88.01  ?  107  LEU BI CD1   1 
> ATOM   138731 C  CD2   . LEU QA 43 107  ? 47.831  180.117 123.683 1.00 87.49  ?  107  LEU BI CD2   1 
> ATOM   138732 N  N     . ILE QA 43 108  ? 47.622  174.772 123.523 1.00 100.98 ?  105  ILE BI N     1 
> ATOM   138733 C  CA    . ILE QA 43 108  ? 47.336  173.468 122.901 1.00 105.61 ?  105  ILE BI CA    1 
> ATOM   138734 C  C     . ILE QA 43 108  ? 45.865  173.100 123.085 1.00 101.71 ?  105  ILE BI C     1 
> ATOM   138735 O  O     . ILE QA 43 108  ? 45.257  172.470 122.214 1.00 100.89 ?  105  ILE BI O     1 
> ATOM   138736 C  CB    . ILE QA 43 108  ? 48.235  172.327 123.472 1.00 101.45 ?  105  ILE BI CB    1 
> ATOM   138737 C  CG1   . ILE QA 43 108  ? 49.719  172.685 123.324 1.00 99.03  ?  105  ILE BI CG1   1 
> ATOM   138738 C  CG2   . ILE QA 43 108  ? 47.926  170.980 122.792 1.00 89.98  ?  105  ILE BI CG2   1 
> ATOM   138739 C  CD1   . ILE QA 43 108  ? 50.093  173.225 121.954 1.00 96.18  ?  105  ILE BI CD1   1 
> ATOM   138740 N  N     . LEU QA 43 109  ? 45.296  173.489 124.225 1.00 100.16 ?  109  LEU BI N     1 
> ATOM   138741 C  CA    . LEU QA 43 109  ? 43.856  173.318 124.429 1.00 100.15 ?  109  LEU BI CA    1 
> ATOM   138742 C  C     . LEU QA 43 109  ? 43.021  174.134 123.424 1.00 105.10 ?  109  LEU BI C     1 
> ATOM   138743 O  O     . LEU QA 43 109  ? 42.058  173.613 122.852 1.00 105.33 ?  109  LEU BI O     1 
> ATOM   138744 C  CB    . LEU QA 43 109  ? 43.469  173.698 125.860 1.00 102.09 ?  109  LEU BI CB    1 
> ATOM   138745 C  CG    . LEU QA 43 109  ? 44.151  172.889 126.968 1.00 103.80 ?  109  LEU BI CG    1 
> ATOM   138746 C  CD1   . LEU QA 43 109  ? 43.611  173.296 128.342 1.00 101.51 ?  109  LEU BI CD1   1 
> ATOM   138747 C  CD2   . LEU QA 43 109  ? 43.998  171.384 126.721 1.00 93.73  ?  109  LEU BI CD2   1
> ```
> 
> Seems like the "correct" residue number should be 108? You could reach out to the wwPDB and ask them to review the entry and make sure this is indeed a mistake.

Thank you very much. It works!
