### ISSUE TITLE
[Typo] Tutorial - Section 4.3.2.3

### ISSUE THREAD

**Issue by joseribon** [biopython/biopython#4717]
(No need to reproduce anything nor specify any setup)

There's a typo in the Tutorial for Biopython.

**Location:**
Doc/Tutorial/chapter_seq_annot.rst (line 498)

**Typo:**
"Basically there are several types of fuzzy positions, so we have five
classes **do** deal with them:"

**Suggested correction:**
"Basically there are several types of fuzzy positions, so we have five
classes **to** deal with them:"

**Comment by peterjc** [comment]
Yep, so if you wanted to go to https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_seq_annot.rst and click on the edit button, you can propose the one word fix entirely within your browser. GitHub would guide you though making a fork, committing the change, and making a pull request.

If not, I'll do it in a few days time - thanks for flagging it!

**Comment by peterjc** [comment]
Thank you - merged.

**Comment by joseribon** [comment]
Likewise. Hopefully the first one of a few more.
