### ISSUE TITLE
default matrix

### ISSUE THREAD

**Issue by DaniloArlt** [biopython/biopython#4718]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)

3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0]
CPython
Linux-6.5.0-28-generic-x86_64-with-glibc2.35
1.81
```

Relatively short question. I could not find an answer in the documentation. What is the default matrix value?

clustalw_cline = ClustalwCommandline("test/clustalw2", infile=in_file,  outfile=outfile, align=True, pim=True)

**Comment by DaniloArlt** [comment]
Sorry, I found a hint in ClustalW. In the menu it says "Gonnet series" for protein.

In Submatrix.cpp from ClustalW is this section with default values.



``` cpp
matrixNum = 3;
matrixName = new string("gonnet");
DNAMatrixNum = 1;
DNAMatrixName = new string("iub");
pwMatrixNum = 3;
pwMatrixName = new string("gonnet");
pwDNAMatrixNum = 1;
pwDNAMatrixName = new string("iub");
``

**Comment by peterjc** [comment]
I'm glad you could solve this.

Note ``ClustalwCommandline`` and all the other wrappers built on https://github.com/biopython/biopython/blob/master/Bio/Application/__init__.py are deprecated.
