### ISSUE TITLE
How to get the gap/mismatch positions of alignment

### ISSUE THREAD

**Issue by leon945945** [biopython/biopython#4731]
Hi, as the title descripts, can `biopython` get the gap/mismatch positions of alignment, I didn't find a function to implement it.

**Comment by leon945945** [comment]
Hi, maybe I find how to get the mismatch position.
A for-loop will solve the problem.
```
def get_mis_pos(align):
    pos = []
    for i in range(align.get_alignment_length()):
        if align[0][i]!=align[1][i] and align[0][i]!="-" and align[1][i]!="-":
            pos.append(i)
    return pos 
```

**Comment by peterjc** [comment]
You didn't make it clear which kind of alignments in Biopython you were talking about, but perhaps the multiple sequence alignment object's counts method added in #4221 is what you want?

**Comment by mdehoon** [comment]
For the new `Alignment` object in `Bio.Align`, you can use the `aligned` property to find out which letters are aligned and which are in a gap. Currently the `Alignment` class does not have a property showing the positions of matched and mismatched letters separately.
