### ISSUE TITLE
Plotting tracks with GenomeDiagram

### ISSUE THREAD

**Issue by jilguero888** [biopython/biopython#4736]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.8.10 (default, Nov 22 2023, 10:22:35)
CPython
Linux-6.0.12-76060012-generic-x86_64-with-glibc2.29
1.79

### Expected behaviour

I am trying to reproduce Proux et al 2002 Figure 6 from the Multiple Tracks section of GenomeDiagram of Biopython tutorial, using the code from GitHub:
https://github.com/biopython/biopython/blob/master/Doc/examples/Proux_et_al_2002_Figure_6.py
When genome file NC_003212.gbk is sliced (coordinates [2587879:2625807]), the SeqIO.read() function makes “some magic” and coordinates are re-calculated (0-based). Thus, the three genomes of the Figure (NC_002703.gbk, AF323668.gbk, NC_003212.gbk) have “artifitially" a similar range of genome coordinates and the figure fits very well. However, I am working with eukaryotic non-model organisms and gb files are not available, I only have an annotation file in GFF3 format from which I get coordinates and build manually the features and the links. I am having problems for plotting with GenomeDiagram when the coordinates range is very different among eukaryotic chromosomes, and the only solution I have found is to re-calculate the coordinates for the tracks to fit the figure, but I lose the original coordinate reference, which is very cumbersome. To exemplify the problem, I have removed the slicing step of genome  NC_003212 (line 35 of the code), and I get this figure:

[ProuxFig6_01.pdf](https://github.com/user-attachments/files/15514209/ProuxFig6_01.pdf)
![image](https://github.com/biopython/biopython/assets/85306514/04b62ce2-56fc-4b7f-8492-b5df205b032c)

as expected, the track is very large compared to the other two genomes, so I am setting the start and end of the track for this genome (lines 163 and 164 of the code), and I would expect that only the [2587879:2625807] region of genome NC_003212 is plotted and the track spans the entire width of the figure. I would also expect that the other two genome tracks extend and span the figure.

### Actual behaviour

After the code modification, I get this figure:

[ProuxFig6_02.pdf](https://github.com/user-attachments/files/15514217/ProuxFig6_02.pdf)
![image](https://github.com/biopython/biopython/assets/85306514/891a0158-4942-4752-90cc-620b6c028093)

only [2587879:2625807] region is plotted but it becomes unreadable. Tracks do not span the entire width of the figure. Is this a bug?. Is this normal?. I am playing with arguments of function gd_diagram.draw() (line 224 fo the code) such as “fragment_size” or “track_size”, but I get the same result, so I don’t know if I am missing something from the documentation. Thank you.

### Steps to reproduce

Line 35
C_rec = SeqIO.read("NC_003212.gbk", "gb")

lines 158 to 164
gd_track_for_features = gd_diagram.new_track(
        5 - 2 * i,
        name=record.name,
        greytrack=True,
        height=0.5,
        start=2587879,
        end=2625807,

line 224
gd_diagram.draw(format="linear", pagesize="A4", fragments=1, start=0, end=max_len)

**Comment by peterjc** [comment]
The diagrams have a single global linear axis, and you can draw a window of this (cropping).

The example code provided manipulates the reference sequences as ``SeqRecord`` objects, which will take care of the coordinates of the features which it stores as ``SeqFeature`` objects. So if you are using GFF input, make sure to turn this into a ``SeqRecord`` with features like that - see https://biopython.org/wiki/GFF_Parsing - there are some third party add ons for loading GFF, but sadly nothing currently built-in to Biopython itself.

If you want to parse the GFF file and draw the features in GenomeDiagram manually, you'll likely have to apply any offsets yourself.

You will need to offset one or more of the reference sequences to get the aligned region all in one region (roughly one above the other). One option is to slice the long sequence. Another option is to pad the short sequence (e.g. add a dummy sequence of lots of Ns to the record).

Your example has:

* short ref
* short ref
* long ref, of which you want to ignore the first XXXXX bases

You can do this (and draw everything):

* short ref
* short ref
* long ref with first XXXXX bases removed and features adjusted

Or this (and draw only a window starting from XXXXX bp):

* XXXXX bases of padding then short ref
* XXXXX bases of badding then short ref
* long ref with first XXXXX bases removed and features adjusted

(Likewise you may want to crop or remove the end of the long reference, which is easier as it does not change the feature coordinates).

**Comment by jilguero888** [comment]
But with other tools you can get a window with original coordinate numbering. Cropping the global linear axis with the gd_diagram.draw() function makes no sense if the track is not expanded to fill the full width. In any case, thank you, I will follow this.
