### ISSUE TITLE
Biopython PDB Parser trying to print all Atoms within a pdb file, Atom H defined twice in residue error.

### ISSUE THREAD

**Issue by hpalin2** [biopython/biopython#4738]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0]
CPython
Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-debian-bookworm-sid
1.81

### Expected behaviour
   <pre>
&lt;Atom C&gt;
&lt;Atom H&gt;
&lt;Atom H&gt;
&lt;Atom C&gt;
&lt;Atom O&gt;
&lt;Atom C&gt;
&lt;Atom O&gt;
&lt;Atom O&gt;
&lt;Atom H&gt;
&lt;Atom C&gt;
&lt;Atom H&gt;
&lt;Atom H&gt;
&lt;Atom C&gt;
&lt;Atom O&gt;
&lt;Atom O&gt;
&lt;Atom H&gt;
    </pre>

### Actual behaviour
<pre>
&lt;Atom C&gt;
&lt;Atom H&gt;
&lt;Atom O&gt;
</pre>
/home/hugh/anaconda3/envs/research/lib/python3.7/site-packages/Bio/PDB/PDBParser.py:421: PDBConstructionWarning: PDBConstructionException: Atom H defined twice in residue <Residue UNL het=H_UNL resseq=1 icode= > at line 13.
Exception ignored.
Some atoms or residues may be missing in the data structure.
  PDBConstructionWarning,
/home/hugh/anaconda3/envs/research/lib/python3.7/site-packages/Bio/PDB/PDBParser.py:421: PDBConstructionWarning: PDBConstructionException: Atom C defined twice in residue <Residue UNL het=H_UNL resseq=1 icode= > at line 14.
Exception ignored.
Some atoms or residues may be missing in the data structure.
  PDBConstructionWarning,
/home/hugh/anaconda3/envs/research/lib/python3.7/site-packages/Bio/PDB/PDBParser.py:421: PDBConstructionWarning: PDBConstructionException: Atom C defined twice in residue <Residue UNL het=H_UNL resseq=1 icode= > at line 16.
Exception ignored.
Some atoms or residues may be missing in the data structure.
  PDBConstructionWarning,
/home/hugh/anaconda3/envs/research/lib/python3.7/site-packages/Bio/PDB/PDBParser.py:421: PDBConstructionWarning: PDBConstructionException: Atom O defined twice in residue <Residue UNL het=H_UNL resseq=1 icode= > at line 17.

### Steps to reproduce
[Lig6IdealPosition.pdb.txt](https://github.com/user-attachments/files/15569972/Lig6IdealPosition.pdb.txt)
import numpy as np
from Bio.PDB import PDBParser, PDBIO
p = PDBParser()
structure = p.get_structure('X', 'Lig6IdealPosition.pdb')

for model in structure:
    for chain in model:
        for residue in chain:
            for atom in residue:
                print(atom)
I am simply printing all atoms within a pdb file that contains only one molecule. I trying to see if anyone else had this issue and came along this issue, https://github.com/biopython/biopython/issues/2963. I believe my structure is correct unlike his, what am I doing wrong?

**Comment by hpalin2** [comment]
I was parsing a pdb file that only contained one molecule not a whole protein structure. I am pretty sure that is why it was throwing me that error. I ended up just parsing it with my own script.

**Comment by peterjc** [comment]
You got multiple warnings like this: 

```
PDBConstructionWarning: PDBConstructionException: Atom H defined twice in residue <Residue UNL het=H_UNL resseq=1 icode= > at line 13.
Exception ignored.
Some atoms or residues may be missing in the data structure.
```

And yes, many atoms were missing as a result. In the default mode at least, the Biopython parser didn't like your PDB file. It seems likely other tools might struggle too...
