### ISSUE TITLE
meme

### ISSUE THREAD

**Issue by amathelier** [biopython/biopython#474]
Hello,

The new version of MEME from the MEME suite slightly changes the format of the header for each motif. Hence, the __read_motif_statistics function of Bio.motifs.meme.py has to be changed to reflect this.
I suggest to change it with the following working version:

```
def __read_motif_statistics(line):
    line = line[5:].strip()
    ls = line.split()
    indx_shift = 1 if ls[1] == "MEME" else 0  # meme 4.10 changed the format
    length = int(ls[3 + indx_shift])
    num_occurrences = int(ls[6 + indx_shift])
    evalue = float(ls[12 + indx_shift])
    return length, num_occurrences, evalue
```

I don't have writing access to the biopython package so cannot do it myself.

Thanks

**Comment by mdehoon** [comment]
Hi Anthony, Did you really intend to close this issue? It looks like the code has not yet been fixed.

**Comment by amathelier** [comment]
Hi Michiel,

This issue can be closed since it is a duplication of 
https://github.com/biopython/biopython/issues/461 where I posted today 
my suggested way (which is working on my toy examples) to fix this.

Best

On 02/16/15 18:19, mdehoon wrote:
>
> Hi Anthony, Did you really intend to close this issue? It looks like 
> the code has not yet been fixed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/biopython/biopython/issues/474#issuecomment-74607422>.Web 
> Bug from 
> https://github.com/notifications/beacon/AD0OUJN8m7zBf_vW29ByBiWUOAF6KngQks5nspylgaJpZM4DgT8T.gif
>

-- 
Anthony Mathelier, PhD
Deputy Group Leader
Dr. Wyeth W. Wasserman’s Lab
Centre for Molecular Medicine and Therapeutics (CMMT)
University of British Columbia | Child & Family Research Institute
980 West 28th Avenue, Room 3109 | V5Z 4H4, Vancouver, BC, Canada
amathelier@cmmt.ubc.ca
http://mathelierweb.com/bioinfo/
