### ISSUE TITLE
mmCIF writer should always write initial data_ token

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#4747]
As shown in #4744, we should always write a `data_` token at the beginning of a mmCIF file, otherwise we mess up the parsing. The key issue is with `MMCIF2Dict`, where we expect the first line to be a `data_` token which is always treated differently (see [here](https://github.com/biopython/biopython/blob/cca7983d2e054db56123295034f4eefc919cb7fa/Bio/PDB/MMCIF2Dict.py#L29)). I can't find a definite format spec saying that `data_` is mandatory, but since `data_` indicates the start of a data block, I think that's implicit.

We should do two things to mitigate this issue:
1. Ensure we always write a `data_` block header in mmcifio.py
2. Check that a mmcif file starts with `data_` otherwise fail early.

**Comment by thepug432** [comment]
Could I take this?

**Comment by thepug432** [comment]
The above should hopefully fix the issue.

**Comment by JoaoRodrigues** [comment]
Sure :) Thanks for picking it up so quickly, I'll have a look tomorrow at
your PR.

A terça, 18/06/2024, 19:29, Kiril Bourakov ***@***.***>
escreveu:

**Comment by thepug432** [comment]
This should be closed.

**Comment by JoaoRodrigues** [comment]
Indeed!
