### ISSUE TITLE
Py3 compatibility problem of Bio.motifs.Motif.weblogo

### ISSUE THREAD

**Issue by shenwei356** [biopython/biopython#475]
Biopython version:

    python3 -c 'import Bio; print(Bio.__version__)'
    1.65

Error when calling ```m.weblogo("motif.png")```:
    
    TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

Relative code: https://github.com/biopython/biopython/blob/master/Bio/Motif/_Motif.py#L663

Thank you guys.

**Comment by peterjc** [comment]
Thanks for the feedback @shenwei356.

Could you report your useful suggestion about ``motifs.create`` as a separate issue please?

The web-logo error is typical of the kind of problems we've had with moving to Python 3. This is likely another bytes string vs unicode issue we need to fix. Thank you for reporting this.

**Comment by DSLituiev** [comment]
I  pulled the latest version from this repository and still I get 

    TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

with Python3.4.  Looking into the code I do not see [the fix from @anntzer](https://github.com/anntzer/biopython/commit/54e5f4a9b5bc5d9e67c4998dfe72d48db6656754).

Can somebody make sure it is correctly merged?

**Comment by peterjc** [comment]
I think this is pull request #565, not merged yet.
