### ISSUE TITLE
Error in Bio.SeqUtils.MeltingTemp.salt_correction summation of monovalent cations

### ISSUE THREAD

**Issue by BjornFJohansson** [biopython/biopython#4766]
I am reporting a problem with Biopython version 1.84:

`Mon = Na + K + Tris / 2.0  # Note: all these values are millimolar`

The code line above in `Bio.SeqUtils.MeltingTemp.salt_correction` line [531](https://github.com/biopython/biopython/blob/c2ba43db03a0e95593edfe42f1b335513b4889f3/Bio/SeqUtils/MeltingTemp.py#L531) leads to dividing all cation concentrations
by two. I dont think this was intended. The objective is to divide the Tris concentration only and add the Na and K concentrations like so:

`Mon = Na + K + (Tris / 2.0)  # Note: all these values are millimolar`

@MarkusPiotrowski I would be grateful for a comment on this.

**Comment by MarkusPiotrowski** [comment]
Without having tested, I'm pretty sure that your statement is not correct. Division has prevalence to addition, hasn't it?

Can you show an example to proof your  statement?

**Comment by BjornFJohansson** [comment]
Yes I think you are right! My bad!
