### ISSUE TITLE
Date parsing of LOCUS entries in genbank files is too strict

### ISSUE THREAD

**Issue by tanhevg** [biopython/biopython#4775]
Strictly speaking, this is a bug in the tool that has generated the genbank file that I am using (GeneData Biologics). It writes out the date with a single digit day number, if it is less than 10, so `8-May-2024` in the example below as opposed to `08-May-2024`. Biopython fails to parse such files, however  files without a date are allowed. I can see problems like this causing grief to other users, and see no reason why Biopython needs to be so strict. So, rather than throwing a `ValueError`, it should probably just raise a warning and skip parsing the date.

### Setup

Biopython version 1.84
Python 3.11
MacOS Sonoma 14.4

### Expected behaviour

The genbank file should be parsed successfully, possibly with missing date

### Actual behaviour

Exception is thrown:
```
  File ".../lib/python3.11/site-packages/Bio/GenBank/Scanner.py", line 1434, in _feed_first_line
    raise ValueError(
ValueError: LOCUS line does not contain - at position 71 in date:
LOCUS       XXX-YYYYY               1234 bp    DNA     circular     8-May-2024 
```

### Steps to reproduce

Obtain a valid genbank file from any source, and replace the first line with the following:

```
LOCUS       XXX-YYYYY               1234 bp    DNA     circular     8-May-2024 
```

**Comment by peterjc** [comment]
Yes, you have an invalid file. Please report this to GeneData Biologics as it ought to be an easy fix for them.

If you think falling back on a warning and ignoring most of the LOCUS line is more helpful here, then by all means look at a pull request to do that. However, there are a lot of historical variations to this part of the specification and we don't want to break anything - so that could be quite tricky.

https://github.com/biopython/biopython/blob/biopython-184/Bio/GenBank/Scanner.py#L1243

**Comment by tanhevg** [comment]
Thank you for the quick response. You seem to be more familiar with the genbank format than me. Could you point me to the specification(s) that Biopython should be supporting?

**Comment by peterjc** [comment]
https://www.ncbi.nlm.nih.gov/genbank/samplerecord/#LocusB is a good starting point for the LOCUS line, also https://ftp.ncbi.nih.gov/genbank/gbrel.txt

**Comment by tanhevg** [comment]
@peterjc , could you please have a look at the pull request. I tried to make as few changes as possible, just replace the errors with warnings. On a broader point, the [NCBI specification](https://ftp.ncbi.nih.gov/genbank/gbrel.txt) is a bit self contradictory: section 3.4.4.1 recommends token-based parsing, and then section 3.4.4.2 proceeds with the details on how to parse based on fixed field width. One possible way of handling this is to create a separate, token-based, parser, and allow the user to specify which one to use. This could be addressed as a separate issue (enhancement). 

Also, I have tried raising this with GeneData Biologics, but did not get very far. The genbank files are not always generated directly by their software; sometimes they are uploaded from yet another system. In an ideal world we could chase every vendor to be 100% compliant with the spec (assuming the spec itself was clear), but in reality it's better to be more permissive.

**Comment by NicolasBio** [comment]
Hi @tanhevg,
I'm having the same issue as you and I'm actually also using GeneData Biologics. Did the change you made work in the end? I'm considering just using you pull request.
Regards

**Comment by peterjc** [comment]
@NicolasBio having you independently test the changes proposed here would be very reassuring.

I've not had much spare time for Biopython recently (I just started a new job this month).

**Comment by tanhevg** [comment]
> Hi @tanhevg, I'm having the same issue as you and I'm actually also using GeneData Biologics. Did the change you made work in the end? I'm considering just using you pull request. Regards

Yes, it does work, as indicated by passing all the tests, the old ones and the ones I have added specifically for this corner case :)

**Comment by NicolasBio** [comment]
> @NicolasBio having you independently test the changes proposed here would be very reassuring.
> 
> I've not had much spare time for Biopython recently (I just started a new job this month).

Hi @peterjc  I tried out the changes and they work. I now get a warning instead of an error as intended.

**Comment by manulera** [comment]
Hello! My two cents for the person who comes here next and wants a quick fix, or wants to parse files that are wrong and the fix should not go into biopython. You can easily create a custom parser for wrongly formatted LOCUS lines:

see: https://github.com/manulera/ShareYourCloning_backend/issues/197#issuecomment-2411937034
