### ISSUE TITLE
[feature] implement FOGSAA for global sequence alignment 

### ISSUE THREAD

**Issue by CallMeMisterOwl** [biopython/biopython#4776]
I would like to propose adding the option to use the "Fast Optimal Global Sequence Alignment Algorithm" (FOGSAA) [1] both for pairwise and multiple sequence alignments. Given that FOGSAA provides alignments of identical quality to those produced by the Needleman-Wunsch (NW) algorithm, it may even be beneficial to set FOGSAA as the default option for global alignments.

The FOGSAA has an average time complexity of O(m+n) and outperforms NW especially on sequence alignments with high sequence identities. This enhancement could offer substantial performance improvements in sequence alignment tasks. 

[1] _Chakraborty A, Bandyopadhyay S. FOGSAA: Fast Optimal Global Sequence Alignment Algorithm. Scientific reports. 2013;3(1). doi:https://doi.org/10.1038/srep01746_

Edit 1: typo 
‌

**Comment by peterjc** [comment]
Are you thinking of expanding the C code in ``Bio/Align/`` to do this?

Note the reference implementation no longer seems to be available, the website is archived on https://web.archive.org/web/20171122230405/http://www.isical.ac.in/~bioinfo_miu/FOGSAA.htm but not the software. I am unclear what license it used anyway, it may not have been compatible anyway.

**Comment by peterjc** [comment]
Working via https https://www.isical.ac.in/~bioinfo_miu/FOGSAA.htm but not http I think :)

**Comment by CallMeMisterOwl** [comment]
Fair point. I will write the author and let you know when I have more information. The algorithm in itself is not too complex, but I guess it wouldn't hurt to have working code one can refer to.

**Comment by CallMeMisterOwl** [comment]
I received following response from the author Angana Chakraborty:

> The code can be freely used for research and teaching. I would appreciate your effort in including FOGSAA in Biopython.   Please initiate. I will update the license information in the meantime.

**Comment by peterjc** [comment]
Note you'd probably want to write this in C for ease of use in Python. But before that, would it be useful in Biopython, and where would it fit? Is the pairwise alignment functionality in ``Bio/Align/`` closely enough related that it makes sense there?

CC @mdehoon

**Comment by CallMeMisterOwl** [comment]
> would it be useful in Biopython

Well, it depends. FOGSAA could be seen as a direct upgrade to the existing pairwise global alignment algorithms. Is it groundbreaking? No. Is it absolutely necessary? No. Would it be good to have? That mostly depends on how many users actually use the alignment functionality of this package and how many of those would benefit from faster calculation of alignments. Depending on the proficiency of the person implementing this, it could take quite some time and might not be worth the effort.

> where would it fit? Is the pairwise alignment functionality in Bio/Align/ closely enough related that it makes sense there? 
 
Given that FOGSAA is designed for global sequence alignments and considering that `Bio/Align/` currently handles pairwise and multiple sequence alignments, it seems logical to integrate FOGSAA within this module.
