### ISSUE TITLE
Bio.Phylo `write` branch length precision is insufficient for single mutations in e.g. mpox

### ISSUE THREAD

**Issue by corneliusroemer** [biopython/biopython#4777]
### Setup

I was surprised to find that Bio.Phylo `write` silently rounds branch lengths to 10^-5

This means that single mutations for mpox (~200kb length) get rounded to 0.

I couldn't find this documented, there's a constant `PRECISION_BRANCHLENGTH = 6` in `Bio.Nexus.Trees` but it's unused, is it essentially just for documentation purposes?

https://github.com/biopython/biopython/blob/d398dfacaae80ee2e438577172ff01f1eb1b7f7f/Bio/Nexus/Trees.py#L22

The precision could be changed by tweaking a few fstrings:
https://github.com/biopython/biopython/blob/d398dfacaae80ee2e438577172ff01f1eb1b7f7f/Bio/Nexus/Trees.py#L697
https://github.com/biopython/biopython/blob/d398dfacaae80ee2e438577172ff01f1eb1b7f7f/Bio/Nexus/Trees.py#L695
https://github.com/biopython/biopython/blob/d398dfacaae80ee2e438577172ff01f1eb1b7f7f/Bio/Nexus/Trees.py#L690
https://github.com/biopython/biopython/blob/d398dfacaae80ee2e438577172ff01f1eb1b7f7f/Bio/Nexus/Trees.py#L687

**Comment by corneliusroemer** [comment]
A workaround, if you care only about relative branch lengths is to multiply all branch lengths by a factor, e.g. 100:

```
    # Multiply all branch lengths by 100 to work around Bio.Phylo's lack of precision
    for clade in tree.find_clades():
        if clade.branch_length is not None:
            clade.branch_length *= 100
```

**Comment by corneliusroemer** [comment]
There _is_ a solution, I just didn't find it myself: adding `format_branch_length='%1.8f`

```
Phylo.write(tt.tree, outtree_name, 'newick', format_branch_length='%1.8f')
```

I should probably make a stackexchange Q&A for it, was hard to discover

**Comment by peterjc** [comment]
I would guess (but haven't checked) that the default PRECISION_BRANCHLENGTH = 6 in ``Bio.Nexus.Trees`` stems from the NEXUS file format definition, or typical usage at the time.
