### ISSUE TITLE
Show figure for GenomeDiagram.Diagram object?

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#478]
Hi, I have succesfully run a code snippet that outputs a pdf file with my figure:

```
#!/usr/bin/env python

from reportlab.lib import colors
from reportlab.lib.units import cm
from Bio.Graphics import GenomeDiagram
from Bio import SeqIO
from Bio.SeqFeature import SeqFeature, FeatureLocation

record = SeqIO.read("/home/chymera/data/CreBLseq/test_files/NC_005816.gb", "genbank")

gd_diagram = GenomeDiagram.Diagram(record.id)
gd_track_for_features = gd_diagram.new_track(1, name="Annotated Features")
gd_feature_set = gd_track_for_features.new_set()

for feature in record.features:
    if feature.type != "gene":
        #Exclude this feature
        continue
    if len(gd_feature_set) % 2 == 0:
        color = colors.blue
    else:
        color = colors.lightblue
    gd_feature_set.add_feature(feature, sigil="ARROW",arrowshaft_height=1.0,
                               color=color, label=True,
                               label_size = 14, label_angle=0)

#I want to include some strandless features, so for an example
#will use EcoRI recognition sites etc.
for site, name, color in [("GAATTC","EcoRI",colors.green),
                          ("CCCGGG","SmaI",colors.orange),
                          ("AAGCTT","HindIII",colors.red),
                          ("GGATCC","BamHI",colors.purple)]:
    index = 0
    while True:
        index  = recordnable to seq.find(site, start=index)
        if index == -1 : break
        feature = SeqFeature(FeatureLocation(index, index+len(site)))
        gd_feature_set.add_feature(feature, color=color, name=name,
                                   label=True, label_size = 10,
                                   label_color=color)
        index += len(site)

gd_diagram.draw(format="linear", pagesize='A4', fragments=4,
                start=0, end=len(record))
gd_diagram.write("plasmid_linear_nice.pdf", "PDF")
gd_diagram.write("plasmid_linear_nice.eps", "EPS")
gd_diagram.write("plasmid_linear_nice.svg", "SVG")
```

Sadly, I was unable to get the script to pop-up a window with the figure. I tried seeing if `gd_diagram` would allow `gd_diagram.show()` or `gd_diagram.imshow()` and I tried importing pylab, in the hope that `pylab.show()` would somehow catch my figure. But none of that worked... Can you help me out?

**Comment by peterjc** [comment]
The ``pylab`` library (aka ``matplotlib``) can save images as files, or show them in pop-up windows.

The ``reportlab`` library which is used in GenomeDiagram only generates images as files.

If you really want to view the image in a pop-up window, then perhaps you can do something like generating the image with GenomeDiagram, and then use ``pylab`` to load the image file and view it?

**Comment by TheChymera** [comment]
Many thanks for the info - so there is no way to plot biopython figures with matplotlib/pylab?

**Comment by peterjc** [comment]
Some other parts of Biopython do use matplotlib/pylab directly, but ``Bio.Graphics`` all uses ReportLab (only).

**Comment by TheChymera** [comment]
Thanks for your reply :) can I use any of those other Biopython parts to plot plasmids/genome sequences?

**Comment by peterjc** [comment]
No, the only relevant bit of Biopython for drawing plasmids/genome sequences is in ``Bio.Graphics`` and uses ReportLab.
