### ISSUE TITLE
Switch from MiniConda to MiniForge on AppVeyor

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#4788]
We currently use MiniConda which include's AnaConda's defaults channel, which is not 100% free https://docs.anaconda.com/miniconda/ - quote:

> Miniconda is free for anyone to use! However, access to Anaconda’s public repository of packages is only free to individuals and small organizations (<200 employees). A paid license is required for larger organizations and anyone embedding or mirroring Anaconda’s repository. See the [TOS](https://legal.anaconda.com/policies/en/) for details.

While I believe Biopython and OBF qualify, it would be prudent to avoid the defaults channel by switching to MiniForge and using just the community run conda-forge channel:

https://github.com/conda-forge/miniforge

For anyone already familiar with using conda at the command line on Windows, this should be a minor edit to https://github.com/biopython/biopython/blob/master/.appveyor.yml and perhaps some clarification in our installation instructions to steer users (we don't want Biopython users installing the non-free AnaConda content as many will be based at organizations with over 200 employees).

**Comment by flaar94** [comment]
Sorry, I'm not very familiar with AppVeyer, but would that just require changing
```  
- ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
- cmd: C:\Miniconda.exe /S /D=C:\Py
```
with 
```
  - ps: Start-FileDownload "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-$env:PYTHON_ARCH.exe" C:\Miniforge.exe; echo "Finished downloading miniforge"
  - cmd: C:\Miniforge.exe /S /D=C:\Py
```
?
I don't really have a good environment to test if it works well with AppVeyer's special Start-FileDownload command or how it handles bash commands (WSL doesn't want me running exe files). The pure ps approach would be 
`  - ps: start -Wait -FilePath C:\Miniforge.exe -ArgumentList "/S /D=C:\Py"`
I think.

**Comment by peterjc** [comment]
Baring any surprises, yes, that could be all this needs. Do you want to try this on a personal fork (you many need to turn on AppVeyor integration), and if it works submit a pull request? Thank you.

If you can switch the command to powershell syntax, that is probably worth doing too.

(I do currently have a borrowed Windows machine, but had it setup with WSL rather than as a test bed for Python directly under Windows. So I'm not really able to test this locally either)

**Comment by flaar94** [comment]
So I tried to build it on my fork, and realized we may have a bit of a snag. Unlike miniconda, miniforge doesn't appear to distribute 32 bit windows binaries, so the build breaks on the 'x86' architecture

It may not be necessary, though, given: https://github.com/conda-forge/miniforge/discussions/468

**Comment by flaar94** [comment]
Unfortunately it doesn't look like this is quite the same thing. Setting the subdir apparently tells conda to prioritize 32 bit packages when installing, but it seems to still uses a 64 bit python interpreter. You can tell by opening the REPL.
Here's 32 bit miniconda (on Windows 11):
```
PS C:\Users\Flaar\miniconda3> C:\Users\Flaar\miniconda3\python.exe
Python 3.9.12 (main, Apr  4 2022, 05:23:19) [MSC v.1916 **32 bit (Intel)**] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
```
Here's miniforge:
```
(win_32) PS C:\Users\Flaar> python
Python 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:38:07) [MSC v.1929 **64 bit (AMD64)**] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
(**'s added for emphasis)

**Comment by flaar94** [comment]
I guess my question would be: what exactly does this build script get used for? Anything besides the tests? If it's just tests, maybe we could also build from an official python release? Since we're installing with pip anyways.

The last miniconda 32 bit release was in 2022, so I'm not sure if they'll ever bother supporting it in miniforge

**Comment by peterjc** [comment]
The AppVeyor tests are to check Biopython works on Windows, especially our C code as cross-platform compiler issues are a thing.

We were using conda under AppVeyor was an easy way to install some dependencies.

As you suggest, running the Python.org release (or even simpler the AppVeyor default) would suffice, plus ``pip install numpy`` and anything else which is trouble free (i.e. provides windows wheels).

**Comment by peterjc** [comment]
The other option is stick with miniconda but explicitly remove the non-free defaults channel as per advice on https://conda.org/blog/2024-08-14-conda-ecosystem-explained/ and elsewhere.

**Comment by flaar94** [comment]
Well, that last option seems easy enough. I think that just requires adding a line 
`conda config --remove channels defaults`
I'm not sure we're even using conda's installation channels, except possibly with the `conda update conda` command. 

I was tempted to use the built-in python or miniconda, but it looks like the highest version of python in visual-studios-2015 is 3.8.0 and the set-up file says the minimum py version is 3.9, so maybe better to keep downloading some sort of latest release like with miniconda, unless we want to update the os image
