### ISSUE TITLE
CGI gateway not up to date on Bio.ExPASy

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#480]
Hi,

The cgi URLs on Bio.ExPASy sprot_search_de/full are not hosted on expasy.ch, but on uniprot.org.
One gets a 300 moved HTTP error if using them. I guess we have to update the URLs?

This might be useful:
http://www.uniprot.org/help/programmatic_access

**Comment by peterjc** [comment]
Yep, we've had to update other ``Bio.ExPASy`` URLs over the years. This probably means we're lacking a test here?

**Comment by tiagoantao** [comment]
I think that in this case the service was even discontinued there...

But yes, I suppose a online test case here would help.

**Comment by peterjc** [comment]
Closing as a duplicate of #253
