### ISSUE TITLE
Code Cleanup - unnecessary switch statement

### ISSUE THREAD

**Issue by john-science** [biopython/biopython#4819]
### Setup

In the file [`Test/test_Align_codonalign.py`](https://github.com/biopython/biopython/blob/f73c7d5c54324aa6c6e8756a95e64578e2ea17fc/Tests/test_Align_codonalign.py), NumPy is imported at the top:

https://github.com/biopython/biopython/blob/f73c7d5c54324aa6c6e8756a95e64578e2ea17fc/Tests/test_Align_codonalign.py#L10

But then, lower down in the same file, there is this switch statement, used to see if NumPy is imported:

https://github.com/biopython/biopython/blob/f73c7d5c54324aa6c6e8756a95e64578e2ea17fc/Tests/test_Align_codonalign.py#L8378-L8386

and then the next ~1500 lines of code are indented.

Because NumPy is imported at the top of the file, this switch statement is unused, and will always evaluate true.

> Just for code cleanup, I would remove this switch, and un-indent the ~1500 lines of code.

(I would also happily perform this little cleanup PR for you. If you like.)

### Expected behaviour

NA

### Actual behaviour

NA

### Steps to reproduce

NA

**Comment by peterjc** [comment]
That makes sense - some of our tests can be run without numpy (this was helpful during testing on Jython or early days of pypy where numpy was not available).
