### ISSUE TITLE
Efetch in Nucleotide database with variation information

### ISSUE THREAD

**Issue by Dkaaaaa** [biopython/biopython#4821]
I would like to use biopython to achieve the following result, I searched for a particular ID in the Nucleotide database and then selected the SNP as shown in red box 1 and then clicked on red box 2, thus obtaining the variation information for that gene.
May I ask if this can be achieved？ What should I do if I can, and do you have suggestions if I can't reach it with biopyhton?
<img width="759" alt="20240906151527" src="https://github.com/user-attachments/assets/4e02e230-12a1-48b1-90f0-fbced9a11eec">
<img width="294" alt="1725607011959" src="https://github.com/user-attachments/assets/807a1bd6-5dc4-418c-972d-71f8b5a0b38f">

**Comment by peterjc** [comment]
That's a view of the NM_000546.6 record in GenBank format (within a webpage), which as you say can be accessed on https://www.ncbi.nlm.nih.gov/nuccore/NM_000546.6 with some point-and-clicking.

The menu caption is quite clear to me, "Customize view", "Features added by NCBI", "SNP". i.e. The additional "variation" features in the GenBank format view are something the NCBI has computed - they are not part of the accession NM_000546.6 directly as it appears in the nucleotide database.

I don't know if this is available via the Entrez API - you will have to ask the NCBI by email.

You can click on "Send to" (also top right) and save this to a file or copy to the clipboard. That seems to give the plain text GenBank format with the variations, which Biopython can parse.

**Comment by Dkaaaaa** [comment]
Appreciate for your reply! And I will try your suggestion.
