### ISSUE TITLE
error updating Restriction enzyme definitions from current rebase release

### ISSUE THREAD

**Issue by kelsic** [biopython/biopython#484]
Parsing the most recent version of rebase (503) breaks the Restriction enzyme update script. The newenzyme function needs better error checking starting with line 166. Error output below:

    cls.suppl = tuple(target[9])
    TypeError: 'int' object is not iterable

FYI, the enzyme that breaks it is BceAI. There appear to be multiple issues with the data for this enzyme. Ignoring this enzyme, the script finishes without error.

Also the documentation for updating the rebase definitions is out of date. It has all the wrong script names for the latest version.

http://biopython.org/DIST/docs/cookbook/Restriction.html#mozTocId546339

**Comment by peterjc** [comment]
Wow, no one has touched that file for 11 years! I think I'd forgotten it even existed...
https://github.com/biopython/biopython/blob/master/Doc/cookbook/Restriction/Restriction.html

I have run the update before, most recently December 2013 I think. Problem characters in certain new enzymes has caused problems; as did changes to the URLs. The update scripts are now here if you'd like to update the HTML file as a pull request:
https://github.com/biopython/biopython/tree/master/Scripts/Restriction

Meanwhile, the entire module is currently unmaintained with some effort on replacing it, see #268. This is a chance to first of all fix the one-based counting to follow Python norms, but also deal with the grey area of shipping a transformed version of REBASE within Biopython (by instead fetching the text files on demand or during install).

**Comment by peterjc** [comment]
@MarkusPiotrowski did you have to fix this in #829 (which I just merged as 8852490cf2e31932d1a47378de82efb951c9192a), or does it look like REBASE fixed the problems with enzyme BceAI instead?

**Comment by MarkusPiotrowski** [comment]
I had no problem with BceAI, so possibly there was a problem in the REBASE file which is resolved now.
Regarding the documentation, I have updated the updating procedure in the `.md` file, but haven't touched the `.html` file.
I guess we can close this.

**Comment by peterjc** [comment]
OK, closing this - thanks all!

P.S. If the ``.html`` file is out of date compared to the ``.md`` file, that needs fixing (even with the simplistic route of removing the ``.html`` and instead auto-generating it in the ``Doc/Makefile`` using pandoc).

**Comment by MarkusPiotrowski** [comment]
OK, I'll have a look at the `.html` file. Just realized that I also forgot to delete the e-mail part in the `.md` file...

**Comment by peterjc** [comment]
Thanks Markus for updating the documentations in #834.

I'm going to close this issue as REBASE seems to have fixed the problematic enzyme.
