### ISSUE TITLE
MSA on protein seqs 

### ISSUE THREAD

**Issue by ahof1704** [biopython/biopython#4847]
Hi, 

I am trying to do a simple MSA with the following sequences
'KWCFRVCYRGICYRRCRGK', 'KWCFRVCYRGICYRRCR', 'RRWCFRVCYRGFCYRKCR'

As you can see, they aren't of the same length. I have managed to align them all by fixing the longest one, but that won't work as I would like to be able to include gaps in the longest one as well. Could you help me with that? 

Thanks
Antonio

**Comment by peterjc** [comment]
I would suggest using an external MSA tool like Muscle, or ClustalOmega - Biopython can parse their output.

**Comment by ahof1704** [comment]
Super! Muscle did the job. Thank you!
