### ISSUE TITLE
Working solution for primer detection

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#485]
Hi, apparently primer design can be done in biopython via `Bio.Emboss.Applications.Primer3Commandline`. This however has been consistently failing for a while (and does so now, and will likely to continue to do so for a while) because the `eprimer3` function which it calls (from EBOSS) is broken, and does not forward the parameters correctly to the `primer3_core` function that actually does the job. 

Of course, the problem is with EMBOSS - but since they are a lot harder to reach, and since wrapping a wrapper function is not a particularly good solution in the first place, I am wondering if bipython could maybe implement a different function for primer design? maybe one which interfaces with primer3 directly?

**Comment by peterjc** [comment]
Which version of EMBOSS are you using?

On the off chance that this is a problem in how you are using ``Bio.Emboss.Applications.Primer3Commandline`` could you post an example here please? It could for example be you need to switch between ``-otm`` and ``-opttm`` for a change made in EMBOSS 6.6.0 [changed in Biopython in December 2013, so it was working back then at least].

I can't see any emails from you on the EMBOSS mailing list raising this, nor on their bug tracker - if you are sure this is an EMBOSS problem, please try that:
http://mailman.open-bio.org/mailman/listinfo/emboss
http://sourceforge.net/p/emboss/bugs/

If you (or anyone else) wanted to write a Biopython interface directly for ``primer3`` then I'm sure that would get used.

**Comment by TheChymera** [comment]
Ok, it's possible The issue is not with upstream - I managed to get the following code to run without errors:

```
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from Bio import SeqIO
from Bio.Emboss.Applications import Primer3Commandline
from Bio.Seq import Seq
from Bio import Entrez
Entrez.email = "A.N.Other@example.com"     # Always tell NCBI who you are

entrez_id="aj627603"

handle = Entrez.efetch(db="nucleotide", id=entrez_id, rettype="gb", retmode="text")
record = SeqIO.read(handle, "genbank")
SeqIO.write(record, ".cache/"+entrez_id+".fasta", "fasta")

primer_cl = Primer3Commandline(sequence=".cache/"+entrez_id+".fasta",auto=True)
primer_cl.outfile = "out.pr3"
primer_cl.numreturn = 3
primer_cl.osize = 20
primer_cl.maxsize = 26
primer_cl.opttm = 58
primer_cl.mintm = 52
primer_cl.mingc = 35
primer_cl.maxgc = 75
primer_cl.psizeopt = 200

primer_cl()
```

For some reason this won't give me any primers. Any ideas why? I tried it with a few sequences, and I'm pretty sure there is something.

**Comment by peterjc** [comment]
Primer design is a bit of an art - it could simply be primer3 cannot find anything on these particular sequences. Have you tried other sequences?

**Comment by TheChymera** [comment]
Yes, I am pretty sure this is an issue with primer3 or how biopython interacts with it. I took my pick from a few other genbank sequences (e.g. AY751747 or DQ023272, though I am sure this is valid for most others as well) and it was never be able to provide me with as much as a single pair of primers. How can I find out what is wrong? can you reproduce my lack of output?

**Comment by TheChymera** [comment]
Searching for primers via this site (that also uses eprimer3/primer3) I get this list

```

# EPRIMER3 RESULTS FOR AJ627603.1

#                      Start  Len   Tm     GC%   Sequence

   1 PRODUCT SIZE: 201
     FORWARD PRIMER    4896   20  59.97  55.00  GGAGTACTTCCAACCGGTCA

     REVERSE PRIMER    5077   20  59.98  55.00  CTGAGGCTTTGACCCAGAAG


   2 PRODUCT SIZE: 200
     FORWARD PRIMER    5783   20  60.12  50.00  GCACTGATTTCGACCAGGTT

     REVERSE PRIMER    5963   20  59.89  50.00  GCTAACCAGCGTTTTCGTTC


   3 PRODUCT SIZE: 195
     FORWARD PRIMER    4896   20  59.97  55.00  GGAGTACTTCCAACCGGTCA

     REVERSE PRIMER    5071   20  59.98  55.00  CTTTGACCCAGAAGCCAGAG


   4 PRODUCT SIZE: 201
     FORWARD PRIMER    4855   20  59.83  60.00  GACCTGGTAGGCTCAGATGC

     REVERSE PRIMER    5036   20  60.09  55.00  TTCTCTTGGTCCCAGTCCAC


   5 PRODUCT SIZE: 203
     FORWARD PRIMER    2750   20  59.98  50.00  AGACAATCGGCTGCTCTGAT

     REVERSE PRIMER    2933   20  59.84  55.00  CAATAGCAGCCAGTCCCTTC
```

Any ideas what could be wrong?

**Comment by TheChymera** [comment]
@peterjc how can I check the (`eprimer3`, I assume) CLI call that bopython actually turns my python code into?

**Comment by peterjc** [comment]
```
print(primer_cl)
```

Or to be more explicit what this will do is:

```
print(str(primer_cl))
```

Calling ``str(...)`` on the Biopython command line wrapper objects returns the string that would be executed.

**Comment by TheChymera** [comment]
@peterjc ok, s the problem is indeed with upstream, as seen [here](https://www.biostars.org/p/102268/)

Similarly to the discussion in that thread I get the following command from `print(primer_cl)`, which gives me this from the CLI:

```
chymera@zenbookhost ~/src/CreBLseq $ eprimer3 -auto -outfile=output/last_primer_out.pr3 -sequence=/home/chymera/data/CreBLseq/Cre_aj627603/preliminary_sequencing/hit_full.fasta -numreturn=5 -osize=20 -maxsize=24 -opttm=60 -mintm=52 -mingc=35 -maxgc=75 -psizeopt=200
Error: Missing SEQUENCE tag
```

I wold like to file an issue/bug with upstream, bu sourceforge won't let me (because I need "create" access?). Why do these people have to be s difficult to reach :-/

**Comment by peterjc** [comment]
It looks like you could get on to the EMBOSS mailing list, good:
http://lists.open-bio.org/pipermail/emboss/2015-March/009018.html

Not sure what's up with the EMBOSS bug tracker - but my guess is it has been temporarily locked down due to people spamming it:
http://lists.open-bio.org/pipermail/emboss/2015-March/009017.html

Since you've determined this is an EMBOSS problem rather than in Biopython, I'm closing this issue. Thank you for your detective work.

**Comment by TheChymera** [comment]
@peterjc Are you by any chance also on the EMBOSS mailing list? Is it empty? I received my own message which I posted, but rather than that I neither got an answer nor any other EMBOSS mailing list emails. Any ideas what could be wrong?

**Comment by peterjc** [comment]
I am on the EMBOSS list. I think Peter Rice from EMBOSS should be back from a trip just after Easter - so I expect he'll be catching up on the email backlog this coming week.

**Comment by TheChymera** [comment]
@peterjc ao, any ideas what I can do about this now?

**Comment by peterjc** [comment]
I replied on the EMBOSS list: http://mailman.open-bio.org/pipermail/emboss/2015-April/009020.html
