### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by FlaviaFigueir** [biopython/biopython#4861]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

**Comment by FlaviaFigueir** [comment]
query = '("Cardiomyopathy" OR "Myocardiopathy") AND "Ultrasonography" AND "HIV"'

# Realizar a pesquisa no PubMed
handle = Entrez.esearch(db="pubmed", term=query, retmax=100)
record = Entrez.read(handle)
handle.close()

**Comment by peterjc** [comment]
What is your question?

**Comment by peterjc** [comment]
Closing for lack of any actionable question.
