### ISSUE TITLE
from Bio import Entrez  # Configurar o e-mail para se identificar no NCBI Entrez.email = "your_email@example.com"  # Definir as palavras-chave para a pesquisa query = '("Cardiomyopathy" OR "Myocardiopathy") AND "Ultrasonography" AND "HIV"'  # Realizar a pesquisa no PubMed handle = Entrez.esearch(db="pubmed", term=query, retmax=100) record = Entrez.read(handle) handle.close()  # Obter os IDs dos artigos encontrados article_ids = record["IdList"] print(f"Total de artigos encontrados: {len(article_ids)}") print("IDs dos artigos encontrados:", article_ids)  # Obter detalhes dos artigos encontrados handle = Entrez.efetch(db="pubmed", id=article_ids, rettype="medline", retmode="text") articles = handle.read() handle.close()  # Exibir detalhes dos artigos print(articles)

### ISSUE THREAD

**Issue by FlaviaFigueir** [biopython/biopython#4862]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import Bio; print(Bio.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in *)

**Comment by FlaviaFigueir** [comment]
from Bio import Entrez

# Configurar o e-mail para se identificar no NCBI
Entrez.email = "your_email@example.com"

# Definir as palavras-chave para a pesquisa
query = '("Cardiomyopathy" OR "Myocardiopathy") AND "Ultrasonography" AND "HIV"'

# Realizar a pesquisa no PubMed
handle = Entrez.esearch(db="pubmed", term=query, retmax=100)
record = Entrez.read(handle)
handle.close()

**Comment by FlaviaFigueir** [comment]
from Bio import Entrez


Entrez.email = "jandirafigueira@live.com.pt"

# Definir as palavras-chave para a pesquisa
query = '("Cardiomyopathy" OR "Myocardiopathy") AND "Ultrasonography" AND "HIV"'

# Realizar a pesquisa no PubMed
handle = Entrez.esearch(db="pubmed", term=query, retmax=100)
record = Entrez.read(handle)
handle.close()

# Obter os IDs dos artigos encontrados
article_ids = record["IdList"]
print(f"Total de artigos encontrados: {len(article_ids)}")
print("IDs dos artigos encontrados:", article_ids)

# Obter detalhes dos artigos encontrados
handle = Entrez.efetch(db="pubmed", id=article_ids, rettype="medline", retmode="text")
articles = handle.read()
handle.close()

# Exibir detalhes dos artigos
print(articles)

**Comment by FlaviaFigueir** [comment]
handle = Entrez.esearch(db="pubmed", term=query, retmax=100)
record = Entrez.read(handle)
handle.close()

**Comment by peterjc** [comment]
You've tried to share the code you are running, but what is your question? Do you get an error message?
