### ISSUE TITLE
Add multiple features to one track

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#487]
Hi guys, I want to visualize a few alignments, and the way Biopython seems most likely to let me do so is via the `Bio.Graphics.GenomeDiagram` class. Ideally I would like to add multiple overlapping features (`GenomeDiagram.Diagram.new_track().new_set().new_feature()`) to the same track.

While specifying overlapping features seems to work (in that it does not crash my script) - seeing as features all have the same height, it results in my bottom feature being obscured by the top one.

Solutions which are awful:
* use different styles (arrow, box, etc.) so that bits of the bottom feature pop up again

Solutions which would be nice:
* specify different heights for features or feature sets
* specify offset from track midline for features or feature sets

Does biopython have any functions to help me out with this use case?

**Comment by peterjc** [comment]
You can also use transparency (via the ReportLab color objects), but right now the simplest answer is to use multiple tracks (e.g. one for coding features, one for repeat regions).

We've discussed vertical positioning within a feature track before (including frame aware placement, effectively six mini-tracks in one) but this is not currently possible. Sorry.
