### ISSUE TITLE
Newick writer concatenates inner node label with support, no separator

### ISSUE THREAD

**Issue by etal** [biopython/biopython#488]
First reported here:
http://stackoverflow.com/questions/29125994/writing-bootstrapped-phylogenetic-trees-generated-with-biopython-to-a-file-using

Given a tree where (1) inner nodes have names assigned, and (2) those inner nodes also have support values (also called "confidence"), then when formatting or writing as Newick, the output string will concatenate the inner node label and the support value without any separator. The ":" separator between support value and branch length is there, though, as it should be.

To replicate (example.xml contents below):

    >>> from Bio import Phylo
    >>> t = Phylo.read("example.xml", "phyloxml")
    >>> t.format("newick")
    '(A:-0.07917,(C:0.06250,(D:-0.15000,B:0.15000)Inner140.00:0.10417)Inner210.00:0.03750,E:0.07917)Inner3100.00:0.00000;\n'

The problematic substrings are:

    Inner140.00
    Inner210.00
    Inner3100.00

Should be something like:

    Inner1:40.00
    Inner2:10.00
    Inner3:100.00

Integer bootstrap values are converted to floats (40 -> 40.00) -- that's expected and not harmful.

Test phyloXML file:

    <phyloxml xmlns="http://www.phyloxml.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.phyloxml.org http://www.phyloxml.org/1.10/phyloxml.xsd">  
    <phylogeny rooted="false">
    <clade>
      <name>Inner3</name>
      <branch_length>0</branch_length>
      <confidence type="unknown">100.0</confidence>
      <clade>
        <name>A</name>
        <branch_length>-0.0791666666667</branch_length>
      </clade>
      <clade>
        <name>Inner2</name>
        <branch_length>0.0375</branch_length>
        <confidence type="unknown">10.0</confidence>
        <clade>
          <name>C</name>
          <branch_length>0.0625</branch_length>
        </clade>
        <clade>
          <name>Inner1</name>
          <branch_length>0.104166666667</branch_length>
          <confidence type="unknown">40.0</confidence>
          <clade>
            <name>D</name>
            <branch_length>-0.15</branch_length>
          </clade>
          <clade>
            <name>B</name>
            <branch_length>0.15</branch_length>
          </clade>
        </clade>
      </clade>
      <clade>
        <name>E</name>
        <branch_length>0.0791666666667</branch_length>
      </clade>
    </clade>
    </phylogeny>
    </phyloxml>

**Comment by peterjc** [comment]
Are inner node labels with bootsraps allowed in plain Newick? If not the fix is just to drop them (label only).

**Comment by jvollme** [comment]
@peterjc: Well, at least most tree vizualisation tools (e.g. ITOL or dendroscope) can recognize support values for nodes if they are given as node labels in Newick files. So I'm not exactly sure if support values were originially considered in the syntax of the Newick format, but it does seem to be common usage to include them as node labels.

**Comment by peterjc** [comment]
Well if you're happy this is unambiguous, go for it :)

**Comment by etal** [comment]
It's true, this is probably a regression in the new Newick parser. The parser in Bio.Nexus has options for dealing with this syntax for inner node labels + support values.

**Comment by etal** [comment]
I think this is fixed now.
