### ISSUE TITLE
how can I dispay multiple diagrams on one page?

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#495]
I would like to have multiple constructs (of varying lengths) exported in one document. Currently I can add multiple tracks with different constructs/features etc. to the same `GenomeDiagram.Diagram` object, but when I export the figure they all get cropped (or extended) to the size I specify via `GenomeDiagram.Diagram.draw` - like so:

```
gdd = GenomeDiagram.Diagram("name")
gdd.draw(format='linear', pagesize="A4", fragments=1, start=1, end=len(the_length_of_one_fragment))
gdd.write("output_path", "PDF")
```

I would like to either be able to add multiple `GenomeDiagram.Diagram` objects to one outut file, or have tracks of varying lengths in a `GenomeDiagram.Diagram` object. How can I do this?

**Comment by peterjc** [comment]
If you are familiar with ReportLab you can use that combine the GenomeDiagram output (or multiple diagrams) with other graphics (e.g. adding extra captions) by working with the ReportLab drawing objects.

The simpler answer is look at the examples drawing tracks of different length, see the "Multiple tracks" example in the current Tutorial:
http://biopython.org/DIST/docs/tutorial/Tutorial.html
http://biopython.org/DIST/docs/tutorial/Tutorial.pdf

This was also covered here:
http://news.open-bio.org/news/2012/03/cross-links-in-genomediagram/

These both refer to this example script:
https://github.com/biopython/biopython/blob/master/Doc/examples/Proux_et_al_2002_Figure_6.py

**Comment by TheChymera** [comment]
Thank you very much - I was able to obtain the kind of figure I wanted.
