### ISSUE TITLE
path? issue on MacOS

### ISSUE THREAD

**Issue by indera** [biopython/biopython#496]
== Can anyone reproduce this?

$ python --version
$ Python 2.7.5

$ uname -a
Darwin MacBook-Pro.local 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin

$ git clone https://github.com/biopython/biopython.git
cd biopython

$ pip install numpy
$ python setup.py build

$ find ./ -name trie.o
./build/temp.macosx-10.9-x86_64-2.7/Bio/trie.o

$ sudo python setup.py install
Writing /usr/local/lib/python2.7/site-packages/biopython-1.65_-py2.7.egg-info

$ python 
>> from Bio import trie
raceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name trie

What am I missing?

**Comment by peterjc** [comment]
Don't run Python from the source folder, that will attempt to import the ``Bio`` files locally - and the compiled ``trie`` code would not be found.

Before running python just do ``cd ~`` or something.

**Comment by indera** [comment]
Thank you... That was simple:)

**Comment by peterjc** [comment]
P.S. You'll see a similar problem with other Python packages with C code, e.g. numpy.
