### ISSUE TITLE
SearchIO: Error if blast text contains long bitscores

### ISSUE THREAD

**Issue by hcraT** [biopython/biopython#500]
I've encountered an error while parsing a blast textual file that contains long bitscore. This is an example of text that makes the parse go wrong:
<pre>
Query= ID

Length=191482
                                                                      Score        E &lt;----
Sequences producing significant alignments:                          (Bits)     Value

  ID                                                             ...  1.683e+05  0.0  

...

Query  78     TTGATAGCGAAGAAACCGATGCGCCTCCGGCACCGTTCATCTCCTCCTCGCTCCAGATGG  137
              ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  91269  TTGATAGCGAAGAAACCGATGCGCCTCCGGCACCGTTCATCTCCTCCTCGCTCCAGATGG  91210
</pre>

The problem happens beacuse the bitscore is longer than usual and so more spaces than 5 are present between "Score" and "E" (where the little arrow in the text is pointing).

So line 214 [here](https://github.com/biopython/biopython/blob/6e001a420c2265c7f4b3547f5180eb99d96f8428/Bio/Blast/NCBIStandalone.py#L212-L218) should better be changed to use a regex.

**Comment by peterjc** [comment]
Can you supply a (short) test case? e.g. upload a complete BLAST text output file as a gist using https://gist.github.com

**Comment by hcraT** [comment]
[here](https://gist.github.com/hcraT/4f2410d6563fc4654190) you find a file that generates the error.

**Comment by peterjc** [comment]
Thank you. Do you want to try the regular expression change yourself and submit a pull request? We'd then thank you in the next release.

(See also the contributing chapter in the Tutorial, http://biopython.org/DIST/docs/tutorial/Tutorial.html )

**Comment by hcraT** [comment]
Ok. I will send the pull request.

**Comment by bow** [comment]
Closing this issue since fix is merged.
