### ISSUE TITLE
EMBOSS PrimerSearch interface.

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#505]
Hi, I would like to do some in-silico PCR, and I believe EMBOSS' primersearch (with which BioPython interfaces [via this file](https://github.com/biopython/biopython/blob/master/Bio/Emboss/PrimerSearch.py)) would be just what I need.

Sadly, I was unable to find any tutorials, or any minimal usage examples in the docstring. Is this information somewhere? Otherwise, could any of you perhaps post it here?

**Comment by peterjc** [comment]
You're right - the documentation in that parse is very very limited.  I can point you at a public example using this interface:
https://github.com/widdowquinn/find_differential_primers

If you would like to write some docstrings that would be a very useful pull request :)

See also the underlying EMBOSS tool's documentation, e.g.
http://emboss.sourceforge.net/apps/cvs/emboss/apps/primersearch.html
