### ISSUE TITLE
Import gene sequences into Biopython

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#507]
I got used to the ease with which I could import Genbank constructs into Biopython, but I am struggling to do the same with genes (e.g. Mus Musculus GADPH). NCBI seems to have a listing called "genes", but I could not find any way to actually get a sequence from [the corresponding page](http://www.ncbi.nlm.nih.gov/gene/14433), much less via biopython. I was able to follow a link to an Ensembl page, where you can zoom in until you can actually select and copy the base pair sequence, but that is just silly. Also, as it appears, there is no nice way to fetch Ensembl stuff via Biopythin.

What can I do? Surely there must be a simple way to fetch the sequence of some mouse gene!

**Comment by peterjc** [comment]
Given you want to work from the NCBI, you almost certainly want to use their Entrez Utilities (e.g. via ``Bio.Entrez``), and I would guess you should be looking at the nucleotide database (which includes sequences), and NOT the genes database (which surprisingly does not have sequences).

e.g. http://www.ncbi.nlm.nih.gov/nuccore/48237754

**Comment by TheChymera** [comment]
Now were you able to find that entry? it does not show up at all in [the search results](http://www.ncbi.nlm.nih.gov/nuccore/?term=mus+musculus+gapd).

**Comment by TheChymera** [comment]
Also, what if I want to see the entire sequence, not just part of the CDS? 

> Given you want to work from the NCBI

Seems to imply there is an easier or at least reasonable alternative? What would that be?

**Comment by peterjc** [comment]
There might be a non-NCBI option in the mouse annotation community - I wouldn't know, not my area.

The official NCBI answer is probably to use Entrez Link. How I did it was searching for the protein name restricted to the species mouse: ``"glyceraldehyde-3-phosphate-dehydrogenase"[title] mouse[organism]`` (see also http://news.open-bio.org/news/2009/06/ncbi-einfo-biopython/ which was written before a lot of the more recent official NCBI Entrez documentation)

What are you starting from? A list of mouse gene IDs?

**Comment by TheChymera** [comment]
I'm starting fro a few gene names. I want to wotrk with the sequences to create some primers and look for some restriction sites. But beyond my immediate use, it would be great if whenever I am, for instance, looking for the Cre Recombinase sequence I wouldn't have to fish it from some genbank construct, or keep it saved somewhere on my system... I am still very surprised there is no easily browsable go-to index for these things..

**Comment by peterjc** [comment]
Gene "names" in the sense of multi-word descriptions are often a pain (fuzzy matching, inconsistent spacing, hyphens etc). You really want the unique short string identifiers as used on your organism of choice. If the NCBI online resources are not ideal, check out what your peers are using. e.g. ENSEMBL? http://www.ensembl.org/Mus_musculus/Info/Index

**Comment by peterjc** [comment]
(Closing as not a Biopython issue - but rather trying to make sense of the NCBI online resources; but you can still comment here, e.g. if you find a good solution)

**Comment by TheChymera** [comment]
> Gene "names" in the sense of multi-word descriptions are often a pain (fuzzy matching, inconsistent spacing, hyphens etc). You really want the unique short string identifiers as used on your organism of choice.

@peterjc yes, that is what I want, but it seems there is no GAPDH entry on NCBI (regardless what identifier). 

I can't really see how I can get the sequence from the Ensembl page for GAPDH (it does say *Chromosome 6: 125,161,715-125,166,467 reverse strand.*, but for that I would have to first load the chromosome and then slice the string (not very elegant or economic)...

Even independently of this, I would actually prefer to use Ensembl for any and all database lookups (European patriotism and all that :D) but there seems to be no nice way to access it via Bipython :(

**Comment by peterjc** [comment]
Opening #512 for adding an ENSEMBL interface to Biopython (do you want to try this as a project?).

I don't know why the NCBI don't have GAPDH as a gene entry or alias. Sounds odd.
