### ISSUE TITLE
restriction fragment overhang length

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#509]
I have familiarized myself over the last few days with how restriction analysis is done in Biopython, chiefly via [this page](http://biopython.org/DIST/docs/cookbook/Restriction.html). Sadly, I was unable to find any built-in function hat can give me the overhang  length or sequence. enzymes have a method called `.overhang()`, but this just tells me whether it is 5' or 3'.

Of course, I can manually do this by using `.ellucidate()` and then detect the underscore and caret, and calculate the number of characters in between. But maybe Biopython has a nice way of getting this information?

**Comment by peterjc** [comment]
Is ``.fst5`` and/or ``.fst3`` (or  ``.characteristic()``) what you need?

P.S. We'd like to deprecate ``Bio.Restriction`` in favour of something like #268, in large part because the old code was overly complex, a hassle to update - plus didn't use Python counting.

**Comment by TheChymera** [comment]
Thank you very much for pointing that out! Presently I am mostly happy with what I can get from `Bio.restriction` But as soon as the new alternative will be available in the main tree and comparatively well documented, I'd happily give it a try!

Until then I can't really figure out what `.fst5` and `.fst3` do. I was able to figure out that they are the first entries in `.characteristic()` but other than that I have not a clue...

**Comment by peterjc** [comment]
This might be better on our mailing list, but I don't think the original author actively follows the discussions anymore :(

**Comment by TheChymera** [comment]
I might write a function that extracts the overhang sequences from `enzyme.elucidate()`. Would you be interested to pull that?

**Comment by peterjc** [comment]
If you can convince another user to confirm its useful, sure. Not being a user of this module myself, I'm not in a good position to judge/advise. You could also ask this on the mailing list which likely would reach many more people that a conversation here on GitHub.

**Comment by MarkusPiotrowski** [comment]
OK, this is a quite old issue...This should have been the answer:

```ovhg``` gives the length of the overhang, negative numbers are 5' overhangs, positive 3' overhangs.
```ovhgseq``` gives the sequence of the overhang (from 5' to 3')

```python
>>>from Bio import Restriction as RE
>>>RE.EcoRI.ovhg
-4
>>>RE.EcoRI.ovhgseq
'AATT'
```
These attributes are already present in Biopython 1.60 (possibly from the beginning of the ```Restriction``` module), I didn't go back further.
