### ISSUE TITLE
Entrez doesn't yet support ECitMatch

### ISSUE THREAD

**Issue by erasche** [biopython/biopython#517]
http://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.ECitMatch

**Comment by peterjc** [comment]
Interesting "*Retrieves PubMed IDs (PMIDs) that correspond to a set of input citation strings.*", so we want a new ``ecitmatch(...)`` function.

I wonder if we should off load the input string formatting entirely to the user (pipe separated fields)?

**Comment by erasche** [comment]
Yep, writing it now. I'm writing it as a list of dicts, is that acceptable?

**Comment by erasche** [comment]
The reason I'd taken on formatting (and somewhat breaking tradition with Entrez module) is that the formatting is quite unpleasant here. Pipe separated fields? Multiple citations joined on a `%0D`? I figured it made sense to handle formatting and provide end users with a nicer interface.

**Comment by peterjc** [comment]
Hmm. I think we should allow a plain string (pre-formatted as per NCBI expectations), so that people can do it themselves if they want to, as per existing ``Bio.Entrez`` design.

I'm open to something more user friendly as well, maybe a (list of) NamedTuples? What do you think @mdehoon?

**Comment by erasche** [comment]
Okay, mostly working except for the fact that `_urlencode` encodes pipes, and I need it to NOT do that. I'm not finding a simple way of implementing that, so I'm looking for suggestions.

- I considered expanding `_open(..., encode=True)` however the arguments still need to joined together and `_open` handles all of that. 
- I considered adding an `ecitmatch=False` flag which would selectively replace `%7C` with `|`, but that's...really ugly.
- Any suggestions welcome to selectively avoid URL encoding of a single parameter.

Here's my WIP: https://github.com/biopython/biopython/compare/master...erasche:ecitmatch?expand=1

**Comment by peterjc** [comment]
Beware that ``_urlencode`` is imported via our Python 3 compatibility shim, under Python 3 this is from:
```
from urllib.parse import urlencode
```
or under Python 2,
```
from urllib import urlencode
```
Which version of Python are you working on?

**Comment by erasche** [comment]
Python 2 but I expect that their behaviour is the same, pipes get encoded
no matter what.

tor. 16. apr. 2015, 11.07 skrev Peter Cock <notifications@github.com>:

**Comment by mdehoon** [comment]
@peterjc  I think the current solution by @erasche is ideal. In general I would prefer Bio.Entez.ecitmatch to do the formatting for me, as it is more Pythonic and hides the ugliness of the format requested by NCBI. That said, I could imagine that NCBI will change the format at some point (e.g. add new arguments), and that there will always be some lag before Biopython catches up with that, so we should allow users to pass the plain string also.

**Comment by erasche** [comment]
So, how would y'all feel about (lines 396 onwards of) https://github.com/biopython/biopython/commit/d87bd804e59e464209c33cfeb070fd75541af8c1 as the solution for encoded pipes. It's an unpleasant hack, but as far as I can tell it's the only reasonable way to hook something that needs to be adjusted at such a late stage in the request process.

If that's acceptable, I'll open the PR as I've added a test case and it seems to be functional.

**Comment by erasche** [comment]
Pinging for update/feedback.

**Comment by peterjc** [comment]
The pipe hack is a hack as you say, but its only within the private helper functions, and so nothing nasty is exposed in the public API. That seems OK to be as a practical solution for now.

**Comment by erasche** [comment]
@peterjc thanks, okay, I'll open the PR. I appreciate the feedback!

**Comment by mdehoon** [comment]
@erasche  , @peterjc  Thank you. I have merged the pull request.

**Comment by erasche** [comment]
@peterjc any update on a release for biopython? I'd like to release the galaxy wrappers for Entrez.

**Comment by peterjc** [comment]
http://lists.open-bio.org/pipermail/biopython-dev/2015-October/021048.html
