### ISSUE TITLE
Blast locally or remotely against a single genome

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#522]
I get it that to run BLAST remotely, I use `NCBIWWW.qblast("blastn", "nr", fasta_string)`, and to run it locally, I use `NcbiblastnCommandline(query, subject, outfmt=5, task="blastn")`.

But, what do I need to specify as a query (instead of `nr` in the first example and `query` in the latter to BLAST just against one genome.

* Where remote BLAST is concerned, I relize this is not a biopython issue, but I have no idea how NCBI handles their database ahndles, I found a few references, but the IDs they specified did not work.

* Where the local BLAST is concerned, I see that just pointing at my
`genbank/genomes/Eukaryotes/vertebrates_mammals/Mus_musculus/GRCm38.p3/`
directory will not work. Neither will pointing at
`genbank/genomes/Eukaryotes/vertebrates_mammals/Mus_musculus/GRCm38.p3/Primary_Assembly/assembled_chromosomes/FASTA/`.

 What then? I hope I do not have to iterate chromosome per chromosome....

**Comment by peterjc** [comment]
For stand alone BLAST, if you don't have a BLAST DB for the mouse (prebuilt databases may exist that you can download..), you would run ``makeblastdb`` on a FASTA file of the mouse genome. And then use the ``-db`` argument to specify searching against this database.

**Comment by TheChymera** [comment]
Where would I get a FASTA file of the mouse genome? I downloaded the genbank geome, and it contains one FASTA file per chromosome 8is that what you meant by "a BLAST DB"?). Do I use `-db` with that? how?

**Comment by peterjc** [comment]
The simplest approach is to first make a combined FASTA file with the multiple sequences in it (one for each chromosome etc), then give that to ``makeblastdb`` to turn the FASTA file into a BLAST database.

This question would be better directed at the seqanswers.com forums OR biostarts.org (but not both please).
