### ISSUE TITLE
Problem with the "penalize_end_gaps" option in pairwise2

### ISSUE THREAD

**Issue by davekr8** [biopython/biopython#529]
Hi,

i think the "penalize_end_gaps" option is not handled correctly in the pairwise2 module. Calling 

```
pairwise2.align.globalms('TCGGATAAAAGGTACTTTGGG', 'TCAACGGATAAAAGGTACTCCGGG', .00000001, -1, -1, -1, penalize_end_gaps=(False, True) )
```
gives me:
```
[('---TCGGATAAAAGGTACTTTGGG', 'TCAACGGATAAAAGGTACTCCGGG', -2.9999998199999993, 0, 24)]
```
(the cost for matching possition are choosen as "quasi-zero", but this should be valid for the given implementation). but for the given costs (substitutions equals insertion/deletion) i might also expect the following to be valid
```
TCAACGGATAAAAGGTACTCCGGG
----CGGATAAAAGGTACTTTGGG
```
which consists of 3 free initial gaps and one additional non-free instead of a mismatch. Have I missed some important detail? Or is there a reason why this should not be a true path through the alignment lattice?

*edit: typo error:*
```
----CGGATAAAAGGTACTTTGGG
```
*is the sequence below. sorry for the confusion.*

**Comment by peterjc** [comment]
This is just a local alignment since you're not using the full second sequence (the leading ``TCAA`` is missing):

```
TCAACGGATAAAAGGTACTCCGGG
----CGGATAAAAGGTACTCCGGG
```

So no, I don't think that would be a valid global alignment.

**Comment by davekr8** [comment]
its a semi-global alignment, free-gaps at the start, non-free at the end. i dont see the point, why there is a need for a match/substitution for the first non-skipped symbol of the "TCAA" string. in the implementation of pairwise2 leading gaps and matches/mismatches can not be seperated in the matrix, but from my point of view it should be valid to have x symbols skipped in string X (for free) and y symbols skipped in Y (non free) to have a valid semi-global alignment.

**Comment by peterjc** [comment]
You've asked ``pairwise2`` for a *global* alignment, which means it must include all of both the sequences. Probably you need to ask for a *local* alignment?

Also could you clarify what the desired output is? Your example looks like seq2 vs part of seq2 (rather than seq1 vs seq2).

**Comment by davekr8** [comment]
sorry for the confusion, there was a copy paste mistake.
this is what i would exspect:
```
TCAACGGATAAAAGGTACTCCGGG
---#CGGATAAAAGGTACTTTGGG
   ^               ^^
```
with the given costs # can either be a '-' gap (cost -1) or a substitution 'T' (cost -1) with the same overall sum. the pairwise method only returns the alignments with leading substitutions, when initial gaps are set to be free. i think this is to strict ! there should be both solutions.

**Comment by peterjc** [comment]
You had written the alignments with the sequence order reversed, which had confused me a bit.

You would ran something like this (giving variable names to the two inputs and making this self-contained):

```
>>> from Bio import pairwise2
>>> seq1 = 'TCGGATAAAAGGTACTTTGGG'
>>> seq2 = 'TCAACGGATAAAAGGTACTCCGGG'
>>> alignments = pairwise2.align.globalms(seq1, seq2, .00000001, -1, -1, -1, penalize_end_gaps=(False, True))
>>> for (align1, align2, _, _, _) in alignments:
...     print(align1)
...     print(align2)
... 
---TCGGATAAAAGGTACTTTGGG
TCAACGGATAAAAGGTACTCCGGG
```

This is one of the answers you expected (the fourth column is a mismatch, ``T`` vs ``A``).

The other answer you a hoping for is *not* a global alignment because it misses the first base of ``seq1``, making it only a *local* alignment:

```
----CGGATAAAAGGTACTTTGGG
TCAACGGATAAAAGGTACTCCGGG
```

Try the local alignment functions in ``pairwise2`` if you really want a local alignment instead of requiring a global alignment.

**Comment by davekr8** [comment]
regardless the semantic of free gaps for seq1, only focused on the computational aspects i still can not understand, why there is the must for a match/mismatch for the first symbol of seq1. of course it would not be the shortest path throught the lattice (from the top left to the bottom right) counting also free movements, as we would have a free horizontal move + non-free vertical move (for the mentioned case)
but the costs would be the same. i am just focused on the standard needleman-wunsch algorithm with having all zeros in the first row. 

i didn't get the point, if i missed some constraint. but there is non. or is it a matter of defining free initial gaps in the global context.

**Comment by peterjc** [comment]
Global alignments (by definition) include all the letters in the two sequences. They *must* to go from the top left to bottom right cell in the lattice. Otherwise you only have a local alignment.
