### ISSUE TITLE
Real time output using AbstractCommandline

### ISSUE THREAD

**Issue by hadim** [biopython/biopython#535]
Is there a way to get real time output into IPython notebook when calling a command with `AbstractCommandline` ?

It could be an option to `AbstractCommandline.__call__`.

Here some random Python code about it (http://stackoverflow.com/questions/17411966/printing-stdout-in-realtime-from-a-subprocess-that-requires-stdin).

```python
p = subprocess.Popen(some_cmd, stdout=subprocess.PIPE)
# Grab stdout line by line as it becomes available.  This will loop until 
# p terminates.
while p.poll() is None:
    l = p.stdout.readline() # This blocks until it receives a newline.
    print l
# When the subprocess terminates there might be unconsumed output 
# that still needs to be processed.
print p.stdout.read()
```

If you like the idea, tell me and I will work on a PR.

**Comment by peterjc** [comment]
The ``AbstractCommandline.__call__`` method is already more complex than I would like - it was intended to cover the simplest use-cases only.

What would you use as the return value in this situation? It would have to be something allowing callback to the ``.readline()`` method - so either the child process or ``.stdout`` handle?

For this and all other advanced use of ``subprocess``, the documentation recommends using ``subprocess.Popen(str(cmd_line_wrapper), ...)`` instead. If you have suggestions for making this clearer that would be great.
