### ISSUE TITLE
test_SeqIO_index fails when biopython repository sits in $TMPDIR

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#541]
The test_SeqIO_index absolute path check fails when the biopython repository is cloned into $TMPDIR (usually /tmp). The important part here is that tempfile.mkstemp() needs to create files in the same directory the repository is cloned into.

This then causes a test failure as described here: https://github.com/biopython/biopython/issues/540#issuecomment-100445053

Opening a new issue so we can continue to use issue #540 to track other Debian-build related issues.

**Comment by peterjc** [comment]
I could not reproduce this on Mac OS, tried using Python 2.7, and Python 3.4. Here ``$TMPDIR`` matched what Python's ``tempfile`` module was using. The tests passed:

```
cd $TMPDIR
git clone https://github.com/biopython/biopython.git biopython_bug541
cd biopython_bug541
python setup.py build
cd Tests
python run_tests.py test_SeqIO_index.py
```

The good news I can reproduce this on a Linux CentOS machine, where ``tempfile`` is using ``/tmp`` (curiously ``$TMP``, ``$TEMP`` and $TMPDIR`` not set), which gave:

```
$ python run_tests.py test_SeqIO_index.py
Python version: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
Operating system: posix linux2
test_SeqIO_index ... FAIL
======================================================================
FAIL: Check absolute filenames in index.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/biopython_bug541/Tests/test_SeqIO_index.py", line 269, in test_some_abs
    self.check(t, expt_sff_files, expt_sff_files)
  File "/tmp/biopython_bug541/Tests/test_SeqIO_index.py", line 204, in check
    self.assertEqual(filenames, expt_sff_files)
AssertionError: [u'biopython_bug541/Tests/Roche/E3MFGYR02_no_manifest.sff', u'biopython_bug541/Tests/Roche/greek.sff', u'biopython_bug541/Tests/Roche/paired.sff'] != ['/tmp/biopython_bug541/Tests/Roche/E3MFGYR02_no_manifest.sff', '/tmp/biopython_bug541/Tests/Roche/greek.sff', '/tmp/biopython_bug541/Tests/Roche/paired.sff']

----------------------------------------------------------------------
Ran 1 test in 14.973 seconds

FAILED (failures = 1)
```

**Comment by peterjc** [comment]
@kblin could you retest on your setup to confirm this fixes the test failure? Thanks!

**Comment by kblin** [comment]
Hi @peterjc,  can confirm that current git HEAD works on both my Ubuntu 14.04 as well as my Debian 8 test systems.

**Comment by kblin** [comment]
I'm still note sure if the index file should say "absolute paths" True in that case, but I might misunderstand what that option is for.

**Comment by peterjc** [comment]
Sorry, I missed that query on #540. The flag in the SQLite index was introduced in Biopython 1.65 and determines if any relative paths are relative to the index file (new default behaviour) or to the current directory (historical behaviour). If a path is recorded with a leading `/` then it is always simply an absolute path.
