### ISSUE TITLE
In silico PCR

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#542]
Hi, I recently started working on a function for [in silico PCR](https://github.com/TheChymera/TransGenoHit/blob/master/pcr.py). Basically this identifies potential(ly unwanted) amplicons.

I have implemented some basic paralellization for the function, and it can currently PCR against the whole mouse genome in about 20min on my laptop. I guess I could make it even faster by not BLASTing both primers against the whole genome, but just BLASTing one, and then BLASTing the second downstream of the first (the function takes a maximum amplicon length argument).

Do you think this could be a worthwhile thing to include in biopython?

**Comment by peterjc** [comment]
Quite possibly - I suggest raising this on the main Biopython mailing list to gauge interest (relatively few people will be following the GitHub issues): http://lists.open-bio.org/mailman/listinfo/biopython/

**Comment by peterjc** [comment]
http://mailman.open-bio.org/pipermail/biopython/2015-May/015628.html

**Comment by peterjc** [comment]
Closing, sadly no replied on the mailing list - but feel free to add a link to https://github.com/TheChymera/AutoTransGeno from https://biopython.org/wiki/Scriptcentral
