### ISSUE TITLE
add gap "codon" to translate table

### ISSUE THREAD

**Issue by ColinAnthony** [biopython/biopython#558]
I understand that the seq.translate does not allow for translating sequences with gaps (ie: if you have a DNA alignment with gaps and want to create a protein alignment).
This should be quite a simple and very useful addition.
Would it be possible to add {"---":"-",} to the translation table/dictionary?

Additionally, allowing incomplete codons to be translated to "X" would increase the usefulness of the function ie: {"--N":"X","-N-":"X","N--":"X"} where N = [A/G/C/T]

**Comment by peterjc** [comment]
I've wondered about this in the past. Indeed, there's a comment in the translation code ``Bio/Seq.py`` which reads:

```
# Todo? Treat "---" as a special case (gapped translation)
```

That seems useful, but I would be against translating partial codons like ``--A`` into the unknown amino acid ``X``. It would cause horrible things to happen when using nucleotide alignments naively.

**Comment by rneher** [comment]
`"---"->"-"` would be great to have. translating incomplete codons as `X` will cause problems with out-of-frame gaps even if of length `%3==0`.

**Comment by peterjc** [comment]
It sounds like adding the gap codon ``---`` mapping to the protein gap ``-` seems acceptable to all in principle.

@rneher since Biopython 1.62 the translation functions will give a warning on any partial codons (and this
will probably become an error in a future release). The idea being if you know you are dealing with partial sequences, either pad with N to extend the sequence length to a multiple of three, or explicitly trim the sequence.

**Comment by jbloom** [comment]
I concur that it would be good to have "---" translated as "-".

**Comment by peterjc** [comment]
PR to implement this here: https://github.com/biopython/biopython/pull/661

Note there would be a small change to the old behaviour in that where previously you would always get an exception for the gap codon, with the proposed change if the input sequence alphabet specifies the gap then it is translated.

**Comment by rneher** [comment]
thanks for all the work on this. I am sure many people will find this useful.

**Comment by peterjc** [comment]
Carlos' work is now on the master branch ready for the next release. This only handles translating the ```---`` "codon" into a ``-`` gap in the protein sequence.

**Comment by Pezhvuk** [comment]
Has this added functionality been deprecated now?

**Comment by peterjc** [comment]
@Pezhvuk What do you mean? Quoting the release notes from Biopython 1.67 (8 June 2016),

> When a gap character is defined, Bio.Seq will now translate gap codons
> (e.g. "---") into a single gap ("-") in the protein sequence. The gap character
> is inferred from the Seq object's alphabet, but it can also be passed as an
> argument to the translate method.

 As far as I know, it is working perfectly, e.g.

It works perfectly and there is no deprecation warning:

```python
>>> from Bio.Seq import Seq
>>> Seq("ACT---GAA").translate(gap="-")
Seq('T-E', Gapped(ExtendedIUPACProtein(), '-'))
```

Or, doing this via an explicitly declared gapped alphabet:

```python
>>> from Bio.Seq import Seq
>>> from Bio.Alphabet import generic_dna, Gapped
>>> Seq("ACT---GAA", Gapped(generic_dna, "-")).translate()
Seq('T-E', Gapped(ExtendedIUPACProtein(), '-'))
```
