### ISSUE TITLE
seqrecord comparison

### ISSUE THREAD

**Issue by dkoppstein** [biopython/biopython#559]
I just tripped over SeqRecord1 == SeqRecord2 evaluating to False despite them having all of the same attributes. I'd just like to [re-propose](http://mailman.open-bio.org/pipermail/biopython-dev/2014-February/020239.html) the idea that if all the attributes of two SeqRecords are the same, `__eq__` should be True.

**Comment by mdehoon** [comment]
Perhaps SeqRecord1 == SeqRecord2 should raise an Exception, instead of returning False.

**Comment by peterjc** [comment]
Currently they get the default Python object comparison, meaning records are not equal unless they are the exact same object in memory.

Note that comparing *all* the attributes is quite complex - if any of the attributes themselves are objects (e.g. objects representing reference information in GenBank headers), unless they too have ``__eq__`` defined you'll still get false negatives.

I would also argue against any kind of fuzzy matching as likely to cause confusion (which attributes get checked?).

Michael's suggestion of an exception seems more useful, I'm not sure it is Python like enough. Perhaps a warning on comparison might work (as we did for the ``Seq`` object prior to making it compare like a string?).

**Comment by dkoppstein** [comment]
I would agree with either a warning or exception for `__eq__`. Alternatively, I'm not familiar with all of the possible objects that a SeqRecord can have; ideally, each of them would implement `__eq__` all the way down until we hit basic python types. If indeed some of the objects referenced can't have meaningful `__eq__` methods, perhaps we could implement something along the lines of `record1.equals(record2, compare_quals=True)` which would be `return record1.seq == record2.seq and record1.letter_annotations == record2.letter_annotations`. Open to API suggestions =)

**Comment by mdehoon** [comment]
It would be difficult to know in advance which comparisons should be included in an .equals method, so I don't think we can design an .equals method that will be broadly useful and won't introduce new confusion.
Warnings are easily ignored, and if record1==record2 does not give a meaningful answer, then I think it should raise an Exception.
Something like
```python
>>> record1 = SeqIO.read(filename1, 'fasta')
>>> record2 = SeqIO.read(filename2, 'fasta')
>>> if record1==record2:
...    print record1.id
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/SeqRecord/__init__.py", line 666, in __eq__
        raise Exception("equality is not defined for SeqRecord objects")
Exception: equality is not defined for SeqRecord objects
```

looks perfectly Pythonic to me.

**Comment by peterjc** [comment]
I agree with @mdehoon that we design broadly useful ``SeqRecord`` equality without adding confusion.

However, rather than an exception, I think a warning would suffice - and won't break any existing code which may be using the object identify equality. But either a warning or an exception would be an improvement :)

**Comment by mdehoon** [comment]
If adding an exception breaks any existing code, then most likely it reveals a bug, rather than intended behavior. @dkoppstein  can you provide a patch?

**Comment by peterjc** [comment]
Raised on the mailing list as http://lists.open-bio.org/pipermail/biopython-dev/2015-October/021133.html - with Biopython 1.66 out, I'd like to merge #560 but it will need functional tests.

**Comment by lennax** [comment]
I created a unit test - unfortunately `with assertRaises` is a 2.7 innovation so it required some cartwheels. Should I submit a second PR? I don't think it's possible to add commits from another branch to an existing PR. https://github.com/lennax/biopython/commit/3bd5e2af251ea92fb7b05162c89940cd31d3e5c4

**Comment by peterjc** [comment]
Sorry if this is out of order - I commented about the context manager approach on #560.

You can add commits to a PR by adding them to the same branch (e.g. ``git cherry-pick HASH``) and pushing the updated branch to github.

**Comment by peterjc** [comment]
Changes in #560 applied, with Biopython 1.67 this should give an exception.
