### ISSUE TITLE
Alphabet equality

### ISSUE THREAD

**Issue by anntzer** [biopython/biopython#566]
`DNAAlphabet() != DNAAlphabet()` which leads to some awkward issues such as

```
s1 = Seq("ATGC", DNAAlphabet())
s2 = Seq("ATGC", DNAAlphabet())
motifs.create([s1, s2])
```

failing due to "inconsistent alphabets".

Option 1: make `DNAAlphabet` (and friends) a singleton class (using one of the many recipes available).
Option 2: make all instances of `DNAAlphabet` equal (but do you really need multiple instances?).
Option3: fix the check for alphabet consistency in `motifs.create` (this doesn't really address the issue imo).

**Comment by peterjc** [comment]
The style I would use and which the documentation general follows, would be to use the pre-instantiated DNA alphabet instance:

```
from Bio.Alpbabet import generic_dna
from Bio.Seq import Seq
from Bio import motifs
s1 = Seq("ATGC", generic_dna)
s2 = Seq("ATGC", generic_dna)
motifs.create([s1, s2])
```

I'm not quite sure how equal the alphabets need to be to make a motif (e.g. would ambiguous vs unambiguous DNA be OK), but perhaps ``Bio.Alphabet._check_type_compatible(...)`` would be enough here? @mdehoon?

In principle I would like the alphabets to be immutable singletons, which might also make alphabet equality a little simpler to think about. Note that this whole quagmire is a large part of the choice to make ``Seq`` comparison work like string comparison (effectively ignoring the alphabet).

**Comment by anntzer** [comment]
I agree that using the preinstantiated alphabets would solve the issue, but the problem is that they show up as `FooAlphabet()` in the repr, which usually suggests to the user that he can just re-create another Alphabet instance by calling the type (especially if he's not aware of these subtleties).
I see why overriding `==` can run afoul `_check_type_compatible`, so perhaps just fixing the motif constructor is a good stopgap (and we can always restrict to exactly same type for now, with the allowance for compatible alphabets added later, as they're not allowed for now anyways).

**Comment by mdehoon** [comment]
Frankly speaking I don't understand why we have all those different Alphabet classes in Bio.Alphabet. I think we can do away with them, and make all preinstantiated alphabets instances of the Alphabet class in Bio.Alphabet.

**Comment by peterjc** [comment]
I think we'd all agree the old historic alphabet system is a mess, and the current system of private methods was my attempt to work with it but fails to make the system usable.

If you can see a nice way forward with minimal code-breakage, that would be a very welcome idea.

**Comment by tbrailov** [comment]
In case of the Bio.motifs.create method, there is an issue in Instances.count method that finds the counts across all instances of the given motif. This error arises when alphabets are being compared. Because the alphabets are classes of something like 
Bio.Alphabet.ProteinAlphabet() == Bio.Alphabet.ProteinAlphabet()
returns false, which results in the error: ValueError: Alphabets are inconsistent. One easy way to fix this is to check the representations (returned by __repr__() method of Alphabet class) for equality. 
alphabet.__repr__() == a.__repr__() 
which compares the string representation of the names of alphabets. This solves the issue of instantiating motifs with sequences, as opposed to parsing motifs from text files.

**Comment by peterjc** [comment]
@tbrailov Could you file an new issue on this ``Bio.motifs.create`` problem please? I had a quick look but don't see where alphabet comparison is being triggered.

Note that the sequence objects do comparison essentially ignoring the alphabet (other than to issue warnings about things like protein vs DNA), see https://github.com/biopython/biopython/blob/biopython-170/Bio/Seq.py#L158

**Comment by peterjc** [comment]
Closing - We are removing ``Bio.Alphabet``, see #2046 

Thank you @chebizarro for issue triage.
