### ISSUE TITLE
Merge overlapping sequences

### ISSUE THREAD

**Issue by TheChymera** [biopython/biopython#574]
Hi again. Does Biopython provide any function that lets me merge two partly overlapping sequences?

Ideally I would like to get e.g. ths sequence:

AGTTCGATTAGNSWAGGA

from these two sequences:

AGTTCGATTAG
TTAGNSWAGGA

I wasn't able to find a fucntion for this. I would know how to script it myself  (I would just make an alignment, remove the matching sequence fro the sequence that has the higher sum of alignement endpoints, and then just concatenate that) - but it would be so much nicer if a binding for this already existed ^^

**Comment by peterjc** [comment]
I don't think there is anything like that already in Biopython (although there is code for gapped pairwise alignments).

**Comment by TheChymera** [comment]
> there is code for gapped pairwise alignments

What exactly do you mean by this?

**Comment by peterjc** [comment]
See the ``Bio.pairwise2`` module (and we have various wrappers for calling command line sequence alignment tools).

**Comment by TheChymera** [comment]
It turns out it's quite tricky to make sure the sequences are aligned in the way I want them. PRactically I am looking for alignments like these:

```
ATGATAGATAGCCAGATA------------------
||||||||||||||||||||||||||||||||||||
--------------GATATAACGTTANATTAWSCAT
```

I am currently trying to make sure that they always look thus by adding a very high penalty for opening gaps, no penalty for extending gaps, a medium high penalty for mismatches and a medium low score for matches:

```
alignment=pairwise2.align.globalms(sequence1, sequence2, 2, -4, -9, 0)
```

 Do you have any other/additional ideas or suggestions?

**Comment by vincentdavis** [comment]
How much overlap, what is the upper bound? Do you want to find only the longest overlap for a pair of sequences?

**Comment by TheChymera** [comment]
@vincentdavis I will do this for sequences where I know a priori that one starts roughly before the other ends. So *I want the longest overlap where the alignment of the first sequence only has a terminal gap, and the alignment of the second only has an initial gap*. 

I am currently hacking my way around this by using the settings I mentioned above, and by stripping bases from the optimal (considering my criteria) alignment in case it stars with a gap. 

E.g.

```
---ATGATAGATAGCCAGATA------------------
|||||||||||||||||||||||||||||||||||||||
UUU--------------GATATAACGTTANATTAWSCAT
```

Becomes:

```
ATGATAGATAGCCAGATA------------------
||||||||||||||||||||||||||||||||||||
--------------GATATAACGTTANATTAWSCAT
```

**Comment by peterjc** [comment]
Note that the ``Bio.pairwise2`` code will change slightly in Biopython 1.67, see #782.

**Comment by bede** [comment]
@TheChymera Can I ask wat approach you settled for in the end?
