### ISSUE TITLE
Incorrect jasper format output

### ISSUE THREAD

**Issue by bassounds** [biopython/biopython#586]
The output from write(motifs, "jasper") is incorrect.  The motif is jasper format appears correct in Python when called by print, but the output has brackets, for example:

>ATGACTCATC 	AP-1(bZIP)/ThioMac-PU.1-ChIP-Seq(GSE21512)/Homer
A [  0.42   0.28   0.28   0.03]
C [  0.00   0.00   0.00   1.00]
G [  0.01   0.00   0.96   0.02]
T [  0.98   0.00   0.00   0.01]

There should not be brackets in jasper format.

**Comment by bassounds** [comment]
A hacky fix:

motif_out = write(record, "jaspar")
chars_to_remove = ['''[''', ''']''']
subj = motif_out
motif_out_fixed = subj.translate(None, ''.join(chars_to_remove))

**Comment by mdehoon** [comment]
@bassounds 

> There should not be brackets in jasper format.

How do you know?

**Comment by bassounds** [comment]
I was incorrect earlier- in jaspar format the brackets are optional.
http://jaspar.genereg.net/html/TEMPLATES/help.html
