### ISSUE TITLE
SearchIO hmmer3-text fails when phmmer runs with '-A' option

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#588]
Maybe this has been reported before or it is in the pipeline but a quick search here in the issues list didn't show much. This bug is reproduced with the lasted git version.

If phmmer runs with the `-A` option, it adds a comment right before the last line of the output file that breaks the SearchIO HMMER3 text parser.

```
# CPU time: 1.21u 1.30s 00:00:02.51 Elapsed: 00:00:02.54
# Mc/sec: 3430.94
//
# Alignment of 168 hits satisfying inclusion thresholds saved to: psa.sto
[ok]
```

The parser complains during the `_parse_qresult` method, when trying to find the `qid` attribute. Basically, it does not expect a comment line after '//'. I guess the parser is built this way to handle jackhmmer output. Adding a simple '#'-ignore statement afterwards would fix this, but there might a more elegant solution (@peterjc @bow) :)

**Comment by bow** [comment]
Hey @JoaoRodrigues,

Yes, I can confirm this on HMMER 3.1b2. We did not have test cases for any `phmmer` output, it turns out. I'll generate some test cases and make a fix this over the weekend.

**Comment by JoaoRodrigues** [comment]
I can share mine, quite small. 


Cheers and thanks!

**Comment by bow** [comment]
Hey @JoaoRodrigues,

Another test case wouldn't hurt :) ~ but I did already generate one.

Didn't find an elegant solution, but indeed the `# Alignment ...` ignore works (pull request coming soon). Looks like the edge cases are starting to show now :/..

**Comment by bow** [comment]
Made the fix and added the test case now :).
