### ISSUE TITLE
SeqFeature.Reference comparison

### ISSUE THREAD

**Issue by kblin** [biopython/biopython#600]
Similar to the SeqRecord comparison mentioned in issue #559, comparing references is currently using Python object comparison, which makes the following code fail:

```
from Bio import SeqIO

rec1 = SeqIO.read('foo.gbk', 'genbank')
rec2 = SeqIO.read('foo.gbk', 'genbank')

assert rec1.annotations['references'] == rec2.annotations['references']
```

I'd argue that comparing references is a bit easier than comparing whole SeqRecord objects, so I'd like to make this work.

@peterjc mentioned on twitter that we'd have to decide on how we'd handle cases where the DOI was identical, but e.g. capitalisation of the title differed. Unless other people feel strongly about this, I'd go with a strict comparison for now.

Thoughts?

**Comment by peterjc** [comment]
My example was intended as a corner case, but in practice I think strict comparison of all the reference attributes should work fine.

**Comment by vincentdavis** [comment]
What is the status of this and #559? I see the pull request to Raise exceptions which makes sense to me.
Adding the ability for limited comparison looks interesting to me.

**Comment by peterjc** [comment]
Comparing the references is just one part of comparing SeqRecord objects. The later are so complex that only the default ``id(...)`` comparison makes sense, but it is not intuitive thus the suggestion of a warning or exception in #559.

Comparing references is much simpler. Equality based on testing all the attributes would probably make sense (despite corner cases like capitalisation of the title, or partial information, etc). That seems safe, PR welcome.

**Comment by peterjc** [comment]
I've flagged this for wider comment on the biopython-dev mailing lists, general on the mailing list, http://lists.open-bio.org/pipermail/biopython-dev/2015-November/021169.html

**Comment by kblin** [comment]
A thing to note with the current proposed implementation is that the current comparison ignores the location of the Reference object. That's because equality isn't defined on SeqFeature.Location objects either. And comparing two locations is probably another can of worms to open, and maybe something for another discussion.
My reasoning for ignoring the location was that if the references refer to the same publication, then they should compare to true anyway.

**Comment by peterjc** [comment]
Oh. I'd missed that. At very least the docstring should talk about that behaviour.

We can probably define equality on location objects, but as you say, there are pitfalls here. Perhaps a re-factoring of the reference object would be a better long term idea... even maybe recording the references in the list of ``SeqFeature`` objects?
