### ISSUE TITLE
Test with Python 3.5 under Windows

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#601]
See mailing list discussion: http://lists.open-bio.org/pipermail/biopython-dev/2015-August/021001.html

Specifically see: http://stevedower.id.au/blog/building-for-python-3-5/

The key point is for Python 3.5 on Windows builds now use Microsoft Visual C++ 14.0, and extension modules should use the same.

He notes that for the short term, there are likely to be compatibility problems with mingw32 which we have also used previously as an alternative to MSCV.

**Comment by benfulton** [comment]
# Testing procedure
* On Windows 8.1, install Visual Studio 15
* Install Python 3.5.0rc2
* Install Numpy from the wheel available at http://www.lfd.uci.edu/~gohlke/pythonlibs/
* Download biopython-1.65.zip
* Launch a VS15 command prompt
* python setup.py build
* cd Tests
* python run_tests.py --offline 1>testreport.txt 2>&1

Results at https://iu.box.com/biopython-win-python35-test

**Comment by peterjc** [comment]
Problem with ``test_Application.py`` failing resolved with https://github.com/biopython/biopython/commit/780c2459cd1e76cb0a1a030de8b4cdec6dcef7b4

**Comment by peterjc** [comment]
I've just tried the official Python 3.5 release compiled from source on Mac and Linux, and the problem where ``Bio.MissingPythonDependencyError`` is not being caught happens here too. So its not Windows specific.

**Comment by peterjc** [comment]
Failing to skip missing dependencies should be fixed with https://github.com/biopython/biopython/commit/929fbfbcf2d1ba65ec460a413128dd5e6f68f5bf

**Comment by peterjc** [comment]
On a related note, TravisCI is now testing under Linux Python 3.5 for us - and our buildbots cover Linux Python 3.5 and Mac OS X Python 3.5 as well.

**Comment by benfulton** [comment]
Ran another test with Python 3.5 release and the latest BioPython code - 241 tests, all passed. Updated the test report at https://iu.box.com/biopython-win-python35-test

**Comment by peterjc** [comment]
Thanks Ben. Are you able to build a working Windows installer? Something like this should work:

``C:\python35\python setup.py bdist_wininst``

See also http://biopython.org/wiki/Building_a_release

**Comment by benfulton** [comment]
Windows installer builds and installs properly on my Windows 8.1 box.

**Comment by peterjc** [comment]
Excellent. This is very encouraging and appreciated since I don't have access to a suitable Windows machine (yet).

That was all using 64 bit Python, right? Until there are official NumPy installers for 64 bit Windows, we're in an awkward place for releasing Biopython installers for 64 bit Windows - thankfully Christoph Gohlke's http://www.lfd.uci.edu/~gohlke/pythonlibs/ is a great service to the community.

Would it be easy for you to test using 32 bit Python 3.5 as well? I don't expect any problems (although there is a new NumPy release candidate we should try, that's a different issue).

**Comment by benfulton** [comment]
No problems with 32-bit Python. Tests all passed the same, and the installer built correctly. When I ran the installer, I got "Python version 3.5 required, which was not found in the registry." which is a pretty common problem when trying to work with 32-bit packages on a 64-bit machine.

**Comment by peterjc** [comment]
OK - I think we can close this issue, although if you'd be willing to help out with the (32 bit) Windows installers for the next Biopython release that would be great (specifically Python 3.5 onwards which I think will be a pain to do on my old Windows XP machine).
