### ISSUE TITLE
Bug in Bio.AlignIO 

### ISSUE THREAD

**Issue by josteij** [biopython/biopython#604]
There seems to be a bug in the MafIO.py get_spliced method() regarding strand information. 

Line 435; if strand not in ("+","-"): raise ValueError ("Strand must be +1 or -1")

This results in arguments with "+" or "-" getting passed on.

Line 561 checks if strand == ref_first_strand (which is fetched from database as "+1" or "-1"). For input "+", which wrongly is passed on from the first test in Line 435, the reversed complement is allways returned, as if the sequence was on the minus strand. 

Solution: Line 435 should be "if strand not in ("+1", "-1"): raise ValueError("Strand must be +1 or -1)

**Comment by peterjc** [comment]
Which version of the code are you looking at? URL?

**Comment by josteij** [comment]
Thanks for the hint about version. It seems like I have been using version 1.6. In the latest, the problem is solved.

**Comment by peterjc** [comment]
Biopython 1.60? Well, if its working now I'll close this. Thanks.
