### ISSUE TITLE
Bug in - print_that() as 'map' in Restriction

### ISSUE THREAD

**Issue by glinshiz** [biopython/biopython#605]
If sequence contains restriction sites only for one enzyme I receive error "KeyError:(0,) in line 338 in fine PrintFormat.py

**Comment by peterjc** [comment]
Can you turn that into a short self contained example? That would be very helpful for reproducing the problem - and perhaps even turning it into a unit test.

**Comment by glinshiz** [comment]
Here is the example 
It works in the first case, but don't work in the second case 

from Bio import Restriction
from Bio.Seq import Seq

def main():
        rb = Restriction.RestrictionBatch(["NdeI","EcoRI","BamHI","BsmBI"])

        #In the first case the sequence contains two BamHI restriction sites and one NdeI. Both BamHI and NdeI in the RestrictionBatch list.
        my_seq = Seq('CCAGTCTATAATTCG' + Restriction.BamHI.site+'GCGGCATCATACTCGA' + Restriction.BamHI.site +'ATATCGCGTGATGATA' + Restriction.NdeI.site +'CGTAGTAATTACGCATG')
        Analong = Restriction.Analysis(rb, my_seq)
        Analong.print_as('map')
        Analong.print_that()

        #In the second case the sequence contains two BamHI restriction sites and one EcoRV. Only  BamHI  in the RestrictionBatch list.
        my_seq = Seq('CCAGTCTATAATTCG' + Restriction.BamHI.site+'GCGGCATCATACTCGA' + Restriction.BamHI.site +'ATATCGCGTGATGATA' + Restriction.EcoRV.site +'CGTAGTAATTACGCATG')
        Analong = Restriction.Analysis(rb, my_seq)

        Analong.print_as('map')
        Analong.print_that()

if __name__ == "__main__":
        main()

**Comment by peterjc** [comment]
Confirmed:

```

                17 BamHI
                |                                           
                |                     39 BamHI
                |                     |                     
CCAGTCTATAATTCGGGATCCGCGGCATCATACTCGAGGATCCATATCGCGTGATGATAC
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
GGTCAGATATTAAGCCCTAGGCGCCGTAGTATGAGCTCCTAGGTATAGCGCACTACTATG
1                                                         60

 62 NdeI
 |                                                          
ATATGCGTAGTAATTACGCATG
||||||||||||||||||||||
TATACGCATCATTAATGCGTAC
61                          82


   Enzymes which do not cut the sequence.

BsmBI     EcoRI     


Traceback (most recent call last):
  File "r.py", line 21, in <module>
    main()
  File "r.py", line 18, in main
    Analong.print_that()
  File "/Library/Python/2.7/site-packages/Bio/Restriction/Restriction.py", line 2162, in print_that
    return PrintFormat.print_that(self, dct, title, s1)
  File "/Library/Python/2.7/site-packages/Bio/Restriction/PrintFormat.py", line 112, in print_that
    print(self.make_format(ls, title, nc, s1))
  File "/Library/Python/2.7/site-packages/Bio/Restriction/PrintFormat.py", line 163, in _make_map
    return self._make_map_only(ls, title) + self._make_nocut_only(nc, s1)
  File "/Library/Python/2.7/site-packages/Bio/Restriction/PrintFormat.py", line 338, in _make_map_only
    for key in cutloc[counter]:
KeyError: 0
```

See also #268

**Comment by johnbradley** [comment]
I created a change to fix this: https://github.com/biopython/biopython/pull/614

**Comment by peterjc** [comment]
Fix applied, thank you.
