### ISSUE TITLE
esearch with POST query data

### ISSUE THREAD

**Issue by jdferreira** [biopython/biopython#607]
Instructions on Entrez's esearch utility (http://www.ncbi.nlm.nih.gov/books/NBK25499/#_chapter4_ESearch_) say:

> For very long queries (more than several hundred characters long), consider using an HTTP POST call

However, I can't seem to find a way to use esearch with POST. Is there one that I'm missing?

**Comment by jotomicron** [comment]
I've submitted PR https://github.com/biopython/biopython/pull/608, which I think solves this problem. Any comments welcome.

**Comment by mdehoon** [comment]
Can this issue be closed?

**Comment by jdferreira** [comment]
Sure, I don't see why not.

**Comment by mdehoon** [comment]
thanks
