### ISSUE TITLE
problem in GenBankWriter with Definition

### ISSUE THREAD

**Issue by bneron** [biopython/biopython#615]
There is a problem in the GenBankWriter.
Some sequence write using SeqIO.write in 'genbank' 
format are not recognize by sequence format detector tool.
The problem come from the DEFINITION field, it must ends with a period 

ftp://ftp.ncbi.nih.gov/genbank/gbrel.txt

[...]
3.4.5 DEFINITION Format

  The DEFINITION record gives a brief description of the sequence,
proceeding from general to specific. It starts with the common name of
the source organism, then gives the criteria by which this sequence is
distinguished from the remainder of the source genome, such as the
gene name and what it codes for, or the protein name and mRNA, or some
description of the sequence's function (if the sequence is
non-coding). If the sequence has a coding region, the description may
be followed by a completeness qualifier, such as cds (complete coding
sequence). There is no limit on the number of lines that may be part
of the DEFINITION.  The last line must end with a period.
[...]

when I convert a fasta file in genbank format see use case
(https://gist.github.com/bneron/884b30a0a00f330c6eeb)
the definition does not ends with a period which induce trouble on some
sequence format detector. I propose to patch  GenBankWriter to ensure that 
DEFINITION field ends with a period. Thus it will follow strictly the GenBank specifications.

**Comment by peterjc** [comment]
Fixed by https://github.com/biopython/biopython/commit/3231fa0636af54012d97a555fc0012cf72fa592c from pull request #616
