### ISSUE TITLE
features.extract doesn't maintain exon order on reverse strand

### ISSUE THREAD

**Issue by alpae** [biopython/biopython#630]
I tried to extract the cDNA from a embl formated file (https://gist.github.com/alpae/5dad3252c9335bd527ff).
For sequences on the reverse strand with multiple exons, extract() does not maintain the correct order afaiks. The individual exons are correctly translated, but joined together in the wrong order.
If you can confirm that this is not an intended feature, I will provide a bug fix.

**Comment by peterjc** [comment]
Is this #570? That's been fixed and will be in the soon-to-be-released Biopython 1.66.

Are you able to install Biopython from source (from GitHub) to test this?

**Comment by alpae** [comment]
Hi, yes, I'm sorry, I haven't seen #570. with the latest version from git the problem is gone. 
Thanks for the quick reaction

**Comment by peterjc** [comment]
Oh good - I'm sorry we/I didn't catch this bug earlier. Thanks for confirming it was the same problem and the fix works for you.
