### ISSUE TITLE
biopython/Bio/Nexus/Nexus.py _unique_label() eval error

### ISSUE THREAD

**Issue by biologyguy** [biopython/biopython#633]
Hi there,
The following function in Nexus.py is throwing exceptions when non-unique taxa are present in an input file:

```python
def _unique_label(previous_labels, label):
    """Returns a unique name if label is already in previous_labels."""
    while label in previous_labels:
        if label.split('.')[-1].startswith('copy'):
            label = '.'.join(label.split('.')[:-1]) \
                  + '.copy' + str(eval('0' + label.split('.')[-1][4:]) + 1)
        else:
            label += '.copy'
    return label
```

The traceback:

```
  File "__init__.py", line 591, in parse
    for r in i:
  File "__init__.py", line 585, in <genexpr>
    i = (r for alignment in AlignIO.parse(fp, format,
  File "__init__.py", line 374, in parse
    for a in i:
  File "NexusIO.py", line 42, in NexusIterator
    n = Nexus.Nexus(handle)
  File "Nexus.py", line 593, in __init__
    self.read(input)
  File "Nexus.py", line 644, in read
    self._parse_nexus_block(title, contents)
  File "Nexus.py", line 685, in _parse_nexus_block
    getattr(self, '_' + line.command)(line.options)
  File "Nexus.py", line 909, in _matrix
    id = _unique_label(list(self.matrix.keys()), id)
  File "Nexus.py", line 286, in _unique_label
    new_label += '.copy' + str(eval('0' + label.split('.')[-1][4:]) + 1)
```

My suggested solution:

```python
def _unique_label(previous_labels, label):
    """Returns a unique name if label is already in previous_labels."""
    while label in previous_labels:
        label_split = label.split('.')
        if label_split[-1].startswith('copy'):
            copy_num = 1
            if label_split[-1] != "copy":
                copy_num = int(label_split[-1][4:]) + 1
            new_label = "%s.copy%s" % ('.'.join(label_split[:-1]), copy_num)
            label = new_label
        else:
            label += '.copy'
    return label
```

**Comment by etal** [comment]
Could you show us an example Nexus file that triggers this error? And, what was the actual error? I wasn't able to replicate it myself by duplicating lines in the MATRIX section of an existing Nexus file (and updating NTAX).

I do find your suggested `_unique_label` more readable, so I'm tempted to just use it anyway.

**Comment by biologyguy** [comment]
Hi Eric,
The actual error was `SyntaxError: invalid token (<string>, line 1)` followed by the trace above.
I should have been more clear in my description about what was causing the error, sorry about that. 
When passing in a list of SeqRecords with replicate IDs to SeqIO.write(.... "nexus"), it breaks. Reading the files with replicate ids wasn't an issue, which is probably how this bug avoided detection. Anyway, the following should illustrate the issue:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from Bio.Alphabet.IUPAC import ambiguous_dna

records = [SeqRecord(Seq("ATGCTGCTGAT", alphabet=ambiguous_dna), id="foo") for _ in range(4)]
with open("temp.del", "w") as ofile:
    SeqIO.write(records, ofile, "nexus")
```

Thanks :)
-Steve

**Comment by peterjc** [comment]
@etal would you be the best person to comment on Nexus output?

(Personally I would have opted for an error on duplicate IDs, as done in some of the ``Bio.AlignIO`` writers for example, but the precedent for auto-renaming is already set in ``Bio.Nexus``)

**Comment by etal** [comment]
@peterjc Not the best, but I did try this code to verify that the output is the same as before. It's an isolated transformation, so although it took me a little while to understand how this change fixes the bug, I think our code review here is sufficient. 

The error actually doesn't appear in Python 2.7. In Python 3, the string "01" can be converted to an integer 1 with `int` but not with `eval`, since the octal literal syntax changed to `0o01`. This patch untangles the `eval` expression and replaces the `eval` with `int` so it works in Python 3.

Since this issue only appears rarely in practice and literally anything can happen inside `eval`, it was not detected during our Python 3 porting efforts.

**Comment by peterjc** [comment]
Good - getting rid of the ``eval(...)`` is a worthwhile improvement in itself :)

**Comment by peterjc** [comment]
See #715, I have just applied the proposed fix from @biologyguy with the test from @vincentdavis.

Steve - are you happy to be thanked by name in the ``NEWS`` and ``CONTRIB`` file for the next release?

(Vincent is already listed)

**Comment by biologyguy** [comment]
Thanks Peter and Eric,
I'm cool with my name showing up in `NEWS`, yep.
Take care,
-Steve
