### ISSUE TITLE
Removing experiemental warning from QCPSuperimposer?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#670]
Biopython 1.66 was the first release to include `Bio.PDB.QCPSuperimposer` from Anuj Sharma (@xulesc) using the Quaternion Characteristic Polynomial algorithm for superimposing structures.

Assuming there is no feedback with recommended changes or problems identified, and that he agrees, we can probably remove the warning in Biopython 1.67?

**Comment by xulesc** [comment]
@peterjc, I am ok with removing the warning as I have not received any requests/recommendations for changes.
