### ISSUE TITLE
BioPythons-API documentation

### ISSUE THREAD

**Issue by buhtz** [biopython/biopython#674]
I can find the nice tutorial. But I am looking for a complete api-documentation of BioPython (especialy Entrez). Where can I get that?

**Comment by peterjc** [comment]
The Biopython API documentation is in the source code itself using Python docstrings, which we turn into HTML and post on the website at http://biopython.org/DIST/docs/api/

In the case of ``Bio.Entrez``, for much of this you should refer to the NCBI's documentation which has improved greatly over the years.

**Comment by buhtz** [comment]
I asked for a BioPython-API-doc, not for Entrez itself. Of course I know that.
But the question is how and if some Entrez features are available with BioPython. That is why I need a Bio-API-doc.

I could nowhere find the link you gave me. Not in the README, not in the Wiki.
You should add this.

**Comment by buhtz** [comment]
open

**Comment by peterjc** [comment]
Specifically the pages for the Entrez module are http://biopython.org/DIST/docs/api/Bio.Entrez-module.html and http://biopython.org/DIST/docs/api/Bio.Entrez.Parser-module.html (exact links may change once we switch away from using epydoc to generate these pages)

You should have been able to find those easily with the frame based navigation.

What are you missing/still looking for?

**Comment by buhtz** [comment]
Maybe I read something wrong but your links doesn't help.
There is this line in the example code
```Python
handle = Entrez.einfo()
```

`handle` is here my point of interesent.
I want to know the type/class and its full API. But `handle` is not clickable and doesn't appear in one of the lists in the frames.

**Comment by peterjc** [comment]
Closing, see discussion on #675 about Entrez and handles. The term "handle" is being used as a deliberate umbrella term covering a range of classes in Python which implement a standard API, see also "What the heck is a handle?" in the Biopython Tutorial and Cookbook: http://biopython.org/DIST/docs/tutorial/Tutorial.html http://biopython.org/DIST/docs/tutorial/Tutorial.pdf

Improvements to the docstring API documentation are welcome as pull requests.

**Comment by buhtz** [comment]
Thanks this helps.
