### ISSUE TITLE
ask for the create cgi-url

### ISSUE THREAD

**Issue by buhtz** [biopython/biopython#675]
Is there a way to ask Bio.Entrez which URL it creates and use including search terms parameters and things like that?

I think the opbject `cgi` at the end of  `Bio.Entrez.__Init__._open()` should be stored somewhere. Maybe `Entrez.last_url` or in the `handle`.

**Comment by peterjc** [comment]
It is in the returned handle object as the ``.url`` attribute which is normal in Python's ``urllib`` / ``urllib2`` libraries which are used internally.

Is there a good point to add this to the documentation which would have helped you find this?

**Comment by buhtz** [comment]
Please re-open.
This depends on #674.

Even in the API-doc is no `handle.url` documented. [`Bio.Entrez`](http://biopython.org/DIST/docs/api/Bio.Entrez-module.html#esearch) show `handle` in the example code but tell nothing about the class behind it. What is 'handle` and where can I see it's API.

This would have prevented basic questions like mine.

I determine that the BioPython-API is not full documented.

**Comment by peterjc** [comment]
Standard Python techniques to find our what class something is, and what methods and attributes it offers:

```
>>> from Bio import Entrez
>>> Entrez.email = "your.name.here@example.org"
>>> handle = Entrez.einfo()
>>> dir(handle)
['__doc__', '__init__', '__iter__', '__module__', '__repr__', 'close', 'code', 'fileno', 'fp', 'getcode', 'geturl', 'headers', 'info', 'msg', 'next', 'read', 'readline', 'readlines', 'url']
>>> handle.__class__
<class urllib.addinfourl at 0x10ec78390>
```

In this case (under Python 2), you get a cryptically named ``addinourl`` handle object from the standard Python library.

Your question is comparatively advanced (most people don't really care what the URL was internally). Again, is there a good point to add the ``.url`` information to the documentation which would have helped you find this?

**Comment by buhtz** [comment]
`dir()`and `type()` doesn't replace good made API documentation. You made this here to easy.
I can not string-search this. `EvilHandleHack` is here a "very helpfull" information.

btw: It looks different in Python3.
```Python
>>> dir(handle)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_handle', 'close', 'read', 'readline', 'seek', 'tell', 'url']
>>> handle.__class__
<class 'Bio._py3k._binary_to_string_handle.<locals>.EvilHandleHack'>
>>> type(handle)
<class 'Bio._py3k._binary_to_string_handle.<locals>.EvilHandleHack'>
```
My queston is _advanced_? I just ask for the API doc. API doc is for developers and contributers, not for users.

I think we use the word _documentation_ different.
You are right, the `.url` is not usefull for the Tutorial, the Wiki or any other user-documentation.

But you have to document it in the API.
I am not sure but you tell me that the type of the handle is from a third-party package (`urllib`)?
Then just put this information to the API doc (in the docstring).
Better put a external linkt to the related section in the urllib-API-doc.

**Comment by peterjc** [comment]
Hopefully this will help others: https://github.com/biopython/biopython/commit/a741f9b4a925a873a7391ef83c0be648c23f808d

Note ``urllib`` / ``urllib2`` are from the standard Python library. This is an area of Python which has changed significantly from Python 2 to 3, making it even more complicated to give clear user-friendly documentation on.

I deliberately gave Python 2 example with the ``addinourl`` class. The exact class returned is an internal detail which most people would not be interested in, and likely to change: The ``EvilHandleHack`` is (as the name should suggest) a nasty internal wrapper class to work around a bug in early versions of Python 3, which should go away at some point once we drop support for them. This class ought to act like a typical Python input handle.

If you have some specific suggestions for further improvements for the docstrings, please open a pull request.

**Comment by buhtz** [comment]
Thanks for improving.

**Comment by peterjc** [comment]
Thank you for raising this - the additional documentation added in response to your feedback should help others in future.
