### ISSUE TITLE
Ontology Support

### ISSUE THREAD

**Issue by erasche** [biopython/biopython#686]
I stumbled across this page http://www.biopython.org/w/index.php?title=Gene_Ontology&redirect=no which mentions planned support for ontologies/GO, however that page has not been touched since 2009 and the mentioned GH repo is missing.

Is Ontology support in any capacity still planned, or are there other libraries that are more feature complete and should be used instead? 

I'm finding myself wishing to test if a given feature ID is one of any children under a specific node.

**Comment by peterjc** [comment]
Probably the most recent mailing list thread on ontologies was http://lists.open-bio.org/pipermail/biopython/2014-June/015325.html with @idoerg etc.

**Comment by erasche** [comment]
I'll take that as "other libraries exist, low motivation to have integrated with biopython". Thanks @peterjc.

**Comment by idoerg** [comment]
My lab used Kamil Koziara's code. We have it here:
https://github.com/idoerg/CAFA/tree/master/obo2ancestors

On Mon, Nov 30, 2015 at 5:29 PM, Eric Rasche <notifications@github.com>
wrote:

> I'll take that as "other libraries exist, low motivation to have
> integrated with biopython". Thanks @peterjc <https://github.com/peterjc>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biopython/biopython/issues/686#issuecomment-160797313>
> .
>



-- 
Iddo Friedberg
http://iddo-friedberg.net/contact.html
++++++++++[>+++>++++++>++++++++>++++++++++>+++++++++++<<<<<-]>>>>++++.>
++++++..----.<<<<++++++++++++++++++++++++++++.-----------..>>>+.-----.
.>-.<<<<--.>>>++.>+++.<+++.----.-.<++++++++++++++++++.>+.>.<++.<<<+.>>
>>----.<--.>++++++.<<<<------------------------------------.

**Comment by erasche** [comment]
Thanks Iddo!

**Comment by idoerg** [comment]
Hey, just  to reopen this issue, if I may. I have made some substantial fixes and changes to the Ontology module, so it will serve most needs of basic obo parsing, with an emphasis on GO. Would we like it to be in BIopython?

**Comment by barwil** [comment]
I'd be for it. We initially wanted to submit this code to biopython with
Kamil Koziara, but eventually other things became more important...

I know some other people have also used variants of the code, so I think
there is a need in the community and the code seemed to be ok.

best
Bartek

On Sun, Feb 7, 2016 at 2:22 AM, Iddo Friedberg <notifications@github.com>
wrote:

> Hey, just to reopen this issue, if I may. I have made some substantial
> fixes and changes to the Ontology module, so it will serve most needs of
> basic obo parsing, with an emphasis on GO. Would we like it to be in
> BIopython?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biopython/biopython/issues/686#issuecomment-180908075>
> .
>



-- 
Bartek Wilczynski
==================
Institute of Informatics
University of Warsaw
http://www.mimuw.edu.pl/~bartek

**Comment by idoerg** [comment]
Thanks bartek.

Here's what I changed:
1) alt_ids were not used as keys for nodes in the DiGraph (fixed). That seemed to be a bug.
2) Traversing the graph  was done through all edge types. That is, you could not say 'I only want parents through "is_a" or through "part_of" or both'. I added an "accepted_edges" argument to .get_ancestors, which contains the edge types that one may want to use for traversing the graph. 

I still have to add accepted_edges argument to all other graph-traversing methods.  And, of course, test code.

Anything else?

**Comment by cmungall** [comment]
Note that we have a new proposed JSON representation of OBO, communities such as BioPython are the intended audience:

 * https://github.com/geneontology/obographs/
 * https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/

**Comment by cmungall** [comment]
For python ontology libs (primary format is obojson):

https://github.com/biolink/ontobio
https://ontobio.readthedocs.org
