### ISSUE TITLE
Get_Organism as an un resolved "return OS"

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#689]
In biopython/Doc/examples/getgene.py line 118 "return OS" looks like it OS would not exist if you get to that return statement.

**Comment by peterjc** [comment]
Yes. Do you think ``return None`` is the only sensible choice?

As an aside, is the entire script still useful? It looks like the ``swiss`` format indexing in ``Bio.SeqIO`` covers a lot of this, although not with any command line API.

**Comment by vincentdavis** [comment]
I have no idea, I was looking at something else.

**Comment by peterjc** [comment]
Change made, thanks for reporting this.

We ought to think about removing or at least deprecating the ``getgene.py`` script...
