### ISSUE TITLE
possible path issue with run_tests.py test_Tutorial

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#704]
As reported by @vincentdavis, this fails:

```
$ python Tests/run_tests.py test_Tutorial
Python version: 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
Operating system: posix darwin
test_Tutorial ... skipping. Could not find ../Doc/Tutorial.tex file
----------------------------------------------------------------------
Ran 1 test in 0.103 seconds
```

The classical way of running the tests from the ``Tests/`` folder is still fine:

```
$ cd Tests/
$ python run_tests.py test_Tutorial
Python version: 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
Operating system: posix darwin
test_Tutorial ... ok
----------------------------------------------------------------------
Ran 1 test in 5.817 seconds
```

Something is not quite right with the changes made in 3174491f42af00fa099308da6f2ac3841947e02a

**Comment by sticken88** [comment]
Hi peterjc! I'm a Computer Engineer and I want to contribute to Biopython. I think that solving this issue would give me the chance to start helping out and would let me understand how to fix bugs in Biopython. Can I join the the project?

**Comment by peterjc** [comment]
Sure - if you can work out what is wrong, and how to fix it, would you be able to make a pull request?

**Comment by sticken88** [comment]
I'll do my best!

**Comment by sticken88** [comment]
Hi peterjc. I am still strying to fix this bug but I am stuck now. If I run:
```
$ cd Tests/
$ python run_tests.py test_Tutorial
```

I get:

```
Python version: 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
Operating system: posix linux2
test_Tutorial ... FAIL
======================================================================
ERROR: test_doctests (test_Tutorial.TutorialTestCase)
Run tutorial doctests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matteo/Documents/Biology/biopython/Tests/test_Tutorial.py", line 188, in test_doctests
    (len(failures), ", ".join(failures)))
ValueError: 2 Tutorial doctests failed: test_chapter_motifs_line_00028, test_chapter_motifs_line_01449

----------------------------------------------------------------------
Ran 1 test in 0.898 seconds

FAILED (failures = 1)
```

Now, I modified a little bit the code to (at least) get the same result when running:
```
$ python Tests/run_tests.py test_Tutorial

But still I have some troubles figuring out what to do. I debugged the code and I understood (correct me if I'm wrong) that the two doctests which fail refer to the "chapter_motif.tex" file (line 28 and 1449 I guess).

I don't know what to do now. Could you give me some hints? Thanks.

**Comment by vincentdavis** [comment]
@sticken88 
Its not clear to me from your last statment "Now, I modified a little bit the code to (at least) get the same result when running:" what you mean. Are you saying the tests run but your get the same failing test?

The failing tests may be a different issue.

**Comment by sticken88** [comment]
Hi vincentdavis. Yes, exactly. I get the same failing tests now and I'd like to fix that. I was clear enough, sorry.

**Comment by vincentdavis** [comment]
You should submit a pull request for this issue #704.
The failing tests in test_chapter_motifs are a different issue. Look to see if they fail in TravisCI after you submit your pull request. If they don't fail on TravisCI then you might want to verify the failures by running the examples directly in python. If you feel it is a bug you should create a new issue.
