### ISSUE TITLE
Updating Installation Docs

### ISSUE THREAD

**Issue by souravsingh** [biopython/biopython#705]
Since Biopython is also available in PyPI, It would be good if we add this info in the installation docs.We can add this as an alternative to the normal method for installation of Biopython

**Comment by peterjc** [comment]
What did you have in mind? There is more than one way to use PyPI...

See also *[Biopython-dev] Should we recommend "pip install biopython"?*
http://lists.open-bio.org/pipermail/biopython-dev/2015-October/021105.html

And this thread on the NumPy list, *[Numpy-discussion] Proposal: stop supporting 'setup.py install'; start requiring 'pip install .' instead*
https://mail.scipy.org/pipermail/numpy-discussion/2015-October/074086.html

**Comment by souravsingh** [comment]
I believe we should support ``setup.py install`` since a few have issues with pip installation.Moreover, to upgrade to the latest package, one can do so by using the ``--upgrade`` option with ``pip install``.So mentioning that could be good

**Comment by peterjc** [comment]
Belatedly closing this issue - we added ``pip install biopython`` to the README last year in https://github.com/biopython/biopython/commit/8a16a61109f40ed353cac3970a9965e3e7505916 (with the traditional ``python setup.py build``, ``test``, and ``install`` also covered).
