### ISSUE TITLE
Return bytes or unicode from Bio.SeqIO index get_raw

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#713]
There are 2 problems with that file:

- The code does not work on Python 3

```python
for acc in ["P33487", "P19801", "P13689", "Q8JZQ5", "Q9TRC7"]:
     handle.write(uniprot.get_raw(acc))
```

This would work:

handle.write(uniprot.get_raw(acc).decode('utf-8'))

- The required download and decompression is massive 

ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz

**Comment by peterjc** [comment]
Yes, the sample data is large - but it is a real world example. The full snippet:

```
\begin{verbatim}
>>> from Bio import SeqIO
>>> uniprot = SeqIO.index("uniprot_sprot.dat", "swiss")
>>> handle = open("selected.dat", "w")
>>> for acc in ["P33487", "P19801", "P13689", "Q8JZQ5", "Q9TRC7"]:
...     handle.write(uniprot.get_raw(acc))
>>> handle.close()
\end{verbatim}
```

There is a design problem here: We index both binary and text files, so is it acceptable under Python 3 that ``.get_raw(...)`` return bytes for binary files (e.g. ``format="sff"``) and unicode for text files (e.g. ``format="swiss"``)? Or, should it always return bytes? It looks like right now it may be inconsistent - we need more test coverage here.

Likewise for the ``SeqRecord`` object ``.format(...)`` method - should ``.format("sff")`` return bytes while ``.format("swiss")`` returns unicode?

I'm going to retitle the issue to focus on this.

**Comment by peterjc** [comment]
See also #723 which touches on the bytes/unicode problem from a more general perspective: Most of our parsers are text based and so want unicode strings under Python 3. We have a few explicitly binary formats like the SFF parser. However, even on non-binary formats, there are a few cases like the ``Bio.Entrez`` expat based XML parser, and the ``SeqIO`` indexing which still use byte handles.

**Comment by peterjc** [comment]
Thanking about this I think we need two district methods here in the ``Bio.SeqIO`` and ``Bio.SearchIO`` indexers, what do you think of these options @tiagoantao and @bow:

* Deprecate ``get_raw(key)``, add ``get_raw_bytes(key)`` (available for all file formats) and ``get_raw_text(key)`` (only for plain text formats).
* Make ``get_raw(key)`` return a (unicode) string or error on binary formats, and add ``get_raw_bytes(key)`` (available for all file formats)
* Make ``get_raw(key)`` return bytes (available for all file formats), and add ``get_raw_text(key)`` (only for plain text formats).

I favour the first option - making ``get_raw(key)`` explicitly for text formats only, returning (unicode) strings under Python 3, and exception with binary file formats. Under Python 2 it could give a warning on binary file formats to use ``get_raw_bytes(key)`` instead?

I'm open to other ideas on the naming, e.g. ``get_bytes(key)`` or ``get_text(key)`` would be shorter.

**Comment by bow** [comment]
The first option with a slightly altered method names (`get_bytes` for all formats and `get_text` for text-only formats) looks more appealing to me as well, Peter. This allows us to deprecate `get_raw` gracefully, while making it clear that text and bytes should be treated differently from 3.x forward.

On `SeqRecord.format`, I think it should not return different types based on the argument. Something like `SeqRecord.format_text` (or `SeqRecord.as_text`) and `SeqRecord.format_bytes` (or `SeqRecord.as_bytes`) for the appropriate formats seems more explicit.

**Comment by peterjc** [comment]
OK, I'm happy to go with the explicit route: deprecate ``get_raw`` and replace it with ``get_bytes`` and ``get_text`` methods. I see this as consistent with how Python 2 to 3 migrations encourage people to think about this distinction. I can try to work on this for SeqIO/SearchIO over the Christmas break, but if you have time to start Bow, just email me.

As to the ``.format(...)`` method, the name was originally based on core Python functionality - so we should review how that stands now with string and bytes formatting. Probably discuss that in a separate issue?

**Comment by bow** [comment]
That sounds good then :). I'm not sure I will have time, but I will let you know if I do (+ I also would like to close other SearchIO-issues first that are still open under my name).

And yes, another issue (that also looks at all our string-related methods?) looks more suitable.

**Comment by peterjc** [comment]
OK, good news - the code base looks to be consistently returning bytes from ``get_raw(...)`` although it wasn't consistently explicitly described that way in the docstrings, nor was this being tested.

It looks like only the Tutorial examples would need tweaking for Python 3, e.g. explicitly open the output file in binary mode.

Revised plan with less disruption: Be explicit that ``get_raw(...)`` gives bytes, and test this. Consider adding ``get_text(...)`` (or similar name) giving a (unicode) string (or exception on binary file formats).

**Comment by peterjc** [comment]
I'm closing this issue as fixed - the example now explicitly opens the file in binary mode which is consistent with ``.get_raw(...)`` returning a bytes string.

Is there any call/demand for adding a (unicode) string equivalent named ``.get_text(...)'' or similar? This would essentially wrap the existing ``.get_raw(...)`` method with a bytes to unicode decode, perhaps raising a specific exception if used on binary file formats like SFF.

Tiago's second point was this "real world" uses a very large file. That's exactly the point of the indexing functionality, but I would welcome suggestions for alternative illustrative example datasets which are smaller. Sadly in the meantime, ``uniprot_sprot.dat`` will only continue to grow...
