### ISSUE TITLE
Update tutorial SeqIO.index_db GenBank example gbvlr01.seq etc

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#714]
The code will not work:

 print(gb_vrl["GQ333173.1"].description)

as the database on genbank is now a different one

**Comment by tiagoantao** [comment]
This would probably work if the complete database is downloaded (not only 16 files)

**Comment by peterjc** [comment]
i.e. This example:

```

\begin{verbatim}
>>> from Bio import SeqIO
>>> files = ["gbvrl%i.seq" % (i+1) for i in range(16)]
>>> gb_vrl = SeqIO.index_db("gbvrl.idx", files, "genbank")
>>> print("%i sequences indexed" % len(gb_vrl))
958086 sequences indexed
\end{verbatim}

...

\begin{verbatim}
>>> print(gb_vrl["GQ333173.1"].description)
HIV-1 isolate F12279A1 from Uganda gag protein (gag) gene, partial cds.
\end{verbatim}
```

There are currently 38 chunks, not 16. This ought to be a small change to the example, and the wording could be clarified to help the reader take the likely growth of the database into consideration.

(Is there a smaller more static set of GenBank files we could use instead?)
