### ISSUE TITLE
internal automatic handling of big requests and large records with Entrez

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [biopython/biopython#716]
(Sorry for my bad english.)
This is a feature request about a concept. This would be big work and is not implemented in the next month. I am aware of that of course. It is a place to discusse about the concept. And the persons being technical more involved then me (I am just a _new user_ using `Bio.Entrez` with _pubmed_) are maybe able to open seperate technical more detailed issues to implement that step by step.

There are two problems with `Entrez` using (in my cases) `efetch()` and `esearch()`.
1. The user itself have to take care about `retmax` - how much records/PMIDs will come back per request. It means doing more requests with incrementing `retstart` each iteration.
2. Sometimes there is not enough RAM to hold all recods (e.g. over 10.000 efetch-pubmed-records on a 32bit-4GB-RAM-system) in there. This is currently solved with storing seperated requests as XML files on hard drive.

When I asked on the list I get a lot of answers how to solve that. This means a lot of users solve known problems again and again with (nearly) the same solution. That is why I think this could be done by `Bio.Entrez` itself.

My inspiration about that was because `Entrez` currently handle the only-3-requests-per-second interally, too.

Maybe conceputal solutions (without answers to all detail questions comin up):
1. `Entrez` should care about the number of user-requests and seperate them in a list of requests. Question here is how large (`retmax`) should one request be? The pubmed-support itself doesn't like to tell discrete numbers here. For `esearch()` they gave me `500` because there _ebot_ use this number, too. But `15000` is working, too. Maybe this should be handled _dynamicly_: Check how long one request take and recalculate this for one record. `(timeAfter - timeBefore) / record['Count']`. This number should be observed over alle seperated requests. If it goes to high, reduce `retmax` for the next requests, ...
2. I know that currently `esearch()` and `efetch()` returning a handle-object that can be treated like a file-handle. I don't know enough about technical internals to imagnine how my wish could be implemented. I parse the XML comin back: `record = Entrez.read(handle)`. When this becomes to big for RAM there is often used seperated XML files on hard drive. I would wish a `record` object that handle that solution internaly. It means `len(record)` or `record['Count']` should return `10.000` not matter that only `500` of them currently in RAM and the rest `9.500` or in XML files on the hard drive. `for r in record:` should work the same way. There could be class encapuslating this XML-file parsing stuff.

**Comment by corleyma** [comment]
For problem number 2, you have two options that would work equally well depending on preference.

**Option 1:** Use a combination of Castra (to create an efficient, on-disk column store of your data) and Dask (for a Pandas-like dataframe that will read from a Castra store "seamlessly", i.e. as if the entire store were loaded into memory).  [See here for an example analysis using JSON-formatted data.](http://blaze.pydata.org/blog/2015/09/08/reddit-comments/) 

**Option 2:** You could read the data referred to by the file handle into an [SFrame](https://github.com/dato-code/SFrame), which is an open source branch of a proprietary data product from Dato. SFrames are also Pandas-like dataframes, just like Dask, except the column-store business/optimized disk access is all rolled in for you.  No need to read your data into a Castra store or anything of like, just load the data into the SFrame like you would a normal dataframe, and everything is taken care of for you.  As far as I know, SFrame does not support "bags" like Dask does (an abstraction for non-dataframe computations), so you'll have to decide whether your use case benefits from the simplicity of the SFrame.  Also, while I've used SFrames to good effect, I'm not sure there's as big of a community for it as there is for Dask/Castra.

In either case, I'm not sure adding this directly to BioPython is necessarily the right move--creates additional dependencies, etc.  Many people probably won't be working with Entrez queries that need out-of-memory analysis, and if they are, it probably makes more sense for them to decide how they want to do that using the tools I mentioned above.  Baking it in is unnecessarily restrictive, although tutorials combining BioPython + (Column Stores/out-of-core dataframes) could be added to the docs if there's really that much demand.

**Comment by buhtz** [comment]
Never heard of Castra or Panda.
There is no need to create dependencies when implementing my suggested solutions into BioPython.

**Comment by peterjc** [comment]
For the queries themselves, if the NCBI gives some guidelines about ``retmax`` which we can implement, that would be great. Right now they don't say anything specific, so this is left to the end user. As you realise, it is difficult to make recommendations because the size of data varies greatly between the different Entrez databases and file formats.

For parsing the XML, our documentation perhaps it needs to be clearer that the iterator based ``Entrez.parse(...)`` function is intended for large multi-record files (it returns the records one-by-one), while ``Entrez.read(...)`` is intended for small single-record files (because it loads everything into RAM as one return value).

**Comment by buhtz** [comment]
Did I understand you right that my wish number 2 is still implemented when I use `Entrez.parse()` and the `generator` object commin back? If so I will test that for my big (over 4 GB RAM using case).

Where can I find some detailed documentation about that and how the `generator` object internaly work? Can I summerize two generator objects like that?

```
h = Entrez.efetch(...) # 1000 pubmed records
r = Entrez.parse(h)
h = Entrez.efetch(...) # next 1000
r = r + Entrez.parse(h)
```

**Comment by peterjc** [comment]
I think so, yes, please try ``Entrez.parse``.

You could chain iterators together using ``itertools.chain`` https://docs.python.org/3/library/itertools.html#itertools.chain which could make sense if parsing from XML files on disk, but doesn't seem a good match for the URL handles. Instead I would use a loop:

```
for offset in ...:
    with Entrez.efetch(..., retstart=offset, retmax=...) as h:
        for record in Entrez.parse(h):
            # do stuff with record
```

Have a look at the Tutorial example using ``Entrez.efetch`` with ``retstart`` and ``retmax`` in a loop: http://biopython.org/DIST/docs/tutorial/Tutorial.html

**Comment by corleyma** [comment]
Entrez.parse works for processing the returned records line-by-line, but if you want to store the entire return in a single data structure that maps out-of-memory data to disk, you'll still have to use one of the solutions I mentioned (or at least, some alternative resembling those).

If whatever you're doing can operate on one record at a time (say, processing the records with some comparator to pull out a subset that would fit in memory, etc) then Entrez.parse will work fine.

**Comment by peterjc** [comment]
I'm going to mark this as closed.
