### ISSUE TITLE
Allow/Enable/Use github labels  

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#730]
For contributors, even those without commit rights. It would be nice for pull requests and issues to have labels. This might make it easier for a larger group to help get issues and pull requests closed. 

The minimum set I would like to see is:
Bug
Docs
Enhancement
Test

Optional:
Duplicate
Won't Fix
Invalid
Help Wanted
Needs Test

**Comment by peterjc** [comment]
Raised on the mailing lists, see http://lists.open-bio.org/pipermail/biopython/2015-December/015847.html and http://lists.open-bio.org/pipermail/biopython-dev/2015-December/021252.html

**Comment by vincentdavis** [comment]
This is now done.
