### ISSUE TITLE
Bytes or (unicode) strings from SeqRecord format method

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#733]
Spin out from discussion on #713.

The SeqRecord object has a `.format(...)` method which in theory can be used on both plain text file formats and binary file formats. Currently the method's docstring says "_Under Python 3 please note that for binary formats a bytes string is returned, otherwise a (unicode) string is returned."_

For Python 3 we ought to be consistent here - the simplest option would be to ensure it always returns (unicode) strings, and error on binary formats?

**Comment by mdehoon** [comment]
This was fixed by #2333
