### ISSUE TITLE
Entrez Tutorial, "journals", is no longer in Entrez databases.

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#735]
The Journals DB is used in this example:
https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_entrez.tex#L203
>>> handle = Entrez.esearch(db="journals", term="computational")
>>> record = Entrez.read(handle)
>>> record["Count"]
'16'

I think for the examples pubmed db will work.

"journals" is also referanced, is several other place in the section. (not a comlete list)
https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_entrez.tex#L89
https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_entrez.tex#L128
https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_entrez.tex#L212
https://github.com/biopython/biopython/blob/master/Doc/Tutorial/chapter_entrez.tex#L260

**Comment by peterjc** [comment]
Curious. Could you email the Entrez team to confirm this? Thanks!

**Comment by vincentdavis** [comment]
@peterjc I will send an email.

This page suggests to me that it has been replace or included in NLM Catalog 
https://www.nlm.nih.gov/bsd/disted/pubmedtutorial/020_550.html 

This code does not return it as an option.
from Bio import Entrez
Entrez.email = "A.N.Other@example.com"
handle = Entrez.einfo()
result = handle.read()
print(result)

**Comment by vincentdavis** [comment]
Reply from U.S. National Library of Medicine:
Yes, the journals database was merged into the NLM Catalog in 2010.  Here is an article from the NLM Technical Bulletin that will give you detailed information regarding this change: https://www.nlm.nih.gov/pubs/techbull/nd10/nd10_nlm_catalog.html

**Comment by peterjc** [comment]
Thanks for confirming that - are you interested to rework the examples to use the pubmed database or NLM catalogue?

**Comment by vincentdavis** [comment]
Yes, I will work on that this week.

Vincent Davis
720-301-3003

**Comment by peterjc** [comment]
Belatedly closing this issue after applying @vincentdavis' contribution on pull request #736 - thanks again!
