### ISSUE TITLE
Last example in Supervised learning methods missing "k"

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#737]
>>> for i in range(len(ys)):
        model = kNN.train(xs[:i]+xs[i+1:], ys[:i]+ys[i+1:])
        print("True:", ys[i], "Predicted:", kNN.classify(model, xs[i]))

should be: model = kNN.train(xs[:i]+xs[i+1:], ys[:i]+ys[i+1:], 3)

**Comment by vincentdavis** [comment]
@mdehoon
Made that change, I had to make a new pull request as the other was not in a branch that I could update.

**Comment by mdehoon** [comment]
Thanks! I merged your pull request.
