### ISSUE TITLE
BioSQL entries not properly deleted when using SQLite

### ISSUE THREAD

**Issue by ctSkennerton** [biopython/biopython#741]
The [`_delitem_`](https://github.com/ctSkennerton/biopython/blob/master/BioSQL/BioSeqDatabase.py#L633) method in `BioSeqDatabase` assumes that there are foreign keys that will cascade and delete all associated data for a given bioentry. This is not the case for SQLite where the schema for BioSQL does not include foreign key support. I see to options: first is to alter the schema to include foreign key support and the second is to create new code that does all of the deleting manually when using SQLite. I favor the first option since it requires less coding, would bring the SQLite schema in line with the other databases and improve database integrity. I'm happy to make the necessary changes to the schema and create a pull request but I'd like to get other opinions as to the pros and cons of each option.

**Comment by peterjc** [comment]
Updating the SQLite schema to be more consistent sounds best, please fill an issue at https://github.com/biosql/biosql and point back here so we can get the Biopython copy used in our tests updated to match. Thanks.

**Comment by ctSkennerton** [comment]
Great @peterjc, new pull requests for biosql/biosql#3 and biopython/biopython#743 include these changes

**Comment by ctSkennerton** [comment]
fixed with commit  8ade4cd
