### ISSUE TITLE
Tutorial problems - Cluster

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#753]
1. data is not defined
2. nodes = tree[:]

raises:

TypeError: sequence index must be integer, not 'slice'
1. mydatafile.txt missing
2. cyano.txt missing

**Comment by vincentdavis** [comment]
I looked at this a few weeks ago, I stated to make some data, sklearn has a nice tool for making fake data to test clustering.

**Comment by peterjc** [comment]
@mdehoon Also this link is dead: http://bonsai.ims.u-tokyo.ac.jp/~mdehoon/software/cluster/cluster3.pdf

**Comment by mdehoon** [comment]
What is the appropriate tex file to fix? Should I fix Tutorial.tex or Tutorial/chapter_cluster.tex ?

**Comment by peterjc** [comment]
As of late last year, ``Tutorial.tex`` has almost no content, instead it includes each chapter as a sub-file. This has also helped with things like per-chapter conversions to Python Notebooks.

So, edit ``Tutorial/chapter_cluster.tex`` then compile ``Tutorial.tex`` to get ``Tutorial.pdf`` (you can still use the make file for this).

**Comment by mdehoon** [comment]
@peterjc  OK thanks. I have fixed chapter_cluster.tex.

**Comment by peterjc** [comment]
Thanks @biomadeira, fb07f4a3bee9c110be2dd736ae050ab9b5ebaaa7 sorts out the broken URL and introduces the file format nicely.

Do you have copies of the ``mydatafile.txt`` or ``cyano.txt`` files, or were they both hypothetical? Having concrete examples would help for readers following along, and for automated testing (which is what @tiagoantao  was trying to do).

**Comment by mdehoon** [comment]
@peterjc  The ``cyano.txt`` file is real and I could upload it, or we could make some artificial data. The ``mydatafile.txt`` is hypothetical. I think it's nice to have an example of a file online at some web site, so I would like to keep this example in the documentation. But I think testing for it is fragile, so I would like to skip the test.

**Comment by vincentdavis** [comment]
sklearn has a nice utility for creating data. 
http://scikit-learn.org/stable/auto_examples/cluster/plot_mean_shift.html#example-cluster-plot-mean-shift-py
What I like about this is that it is easy to understand what the data will be like.
```python
# Generate sample data
centers = [[1, 1], [-1, -1], [1, -1]]
X, _ = make_blobs(n_samples=10000, centers=centers, cluster_std=0.6)
```

**Comment by mdehoon** [comment]
@vincentdavis But that would introduce one more dependency. Using just numpy, you could do
```python
>>> from numpy.random import standard_normal
>>> x = 0.6 * standard_normal((3*10000,2))
>>> x[:10000,:] += array([1,1])
>>> x[10000:20000,:] += array([-1,-1])
>>> x[20000:,:] += array([1,-1])
```

**Comment by peterjc** [comment]
Unless you are thinking of using sklearn (or numpy) to generate an example file to include with Biopython?

**Comment by vincentdavis** [comment]
@peterjc That is what I was thinking, using sklearn nice utility to make example files.

**Comment by peterjc** [comment]
``cyano.txt`` as added in #1216

**Comment by yogeshhk** [comment]
Is this issue still open?...seeing that cyano.txt url is already added and the original "nodes = tree[:]" is not raising any error now in Python 3.6

**Comment by peterjc** [comment]
I think you're right - ``mydatafile.txt`` is hypothetical and ``cyano.txt`` has been added. Closing, thank you.
