### ISSUE TITLE
Tutorial use of urlopen, bytes and Python 3

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#754]
As noted on #751, there are a couple of uses of `urlopen` in the tutorial to get a handle to feed to a text based parser. These need at least an updated import, e.g.

```
>>> import urllib
>>> handle = urllib.urlopen("http://www.somelocation.org/data/someswissprotfile.dat")
```

to (*fixed error python 2 example, could also use urllib2*):

```
>>> from urllib import urlopen  # Python 2
>>> from urllib.request import urlopen  # Python 3
>>> handle = urlopen("http://www.somelocation.org/data/someswissprotfile.dat")
```

However, the subtlety here is it will be a binary handle giving bytes not (unicode) strings. Would we also need to wrap the handle in `io.TextIOWrapper` (or our `EvilHandleHack` workaround for Python 3.3, see #723) as done internally by the `Bio.Entrez` and `Bio.TogoWS` interfaces?

i.e. something like this for Python 3:

```
>>> from urllib.request import urlopen
>>> from io import TextIOWrapper
>>> handle = TextIOWrapper(urlopen("http://www.somelocation.org/data/someswissprotfile.dat"))

```

**Comment by peterjc** [comment]
We've dropped Python 3.3 support, so don't need to worry about that special case.

**Comment by Gasta88** [comment]
I'll be happy to have a look at it. 

What tutorial docs are we referring to? the [biopython cookbook?](http://biopython.org/DIST/docs/tutorial/Tutorial.html)

**Comment by peterjc** [comment]
Yes, source to which is these per-chapter LaTeX files:

https://github.com/biopython/biopython/tree/master/Doc/Tutorial

You can compile it with the ``Makefile`` in the main ``Doc`` directory, i.e.

```
cd Doc
make
```

Note that would need ``pdflatex`` (for the PDF) and ``hevea`` (for the HTML) installed.

Note we have an ad hoc doctest system used for testing many of the examples, see ``Tests/test_Tutorial.py`` for details.

**Comment by Gasta88** [comment]
Thanks.
I'm on Ubuntu 17.04 and I've installed `texlive`, `pdflatex` and `hevea`.

Following your instructions I get several warnings when I run `make` but it still compile the files and I get the `.pdf` and `.html` ones. Is it normal?

**Comment by peterjc** [comment]
Probably - the LaTeX step is run three times, the first time will always warn about undefined labels but that's normal. On the second run though all the labels are known, and the third run is just in case any page layout has changed.

**Comment by Gasta88** [comment]
In order to sort out the `urlopen` error in the other chapter (`chapter_cluster.tex`) shall I open a new PR or add the commit to #1340?

Moreover, the file opened is a `.txt` for the cluster chapter. There is already a text file in `Doc/examples`; would it be OK to use it or do I need to upload a new file?

**Comment by peterjc** [comment]
See also #1216 which added ``Tests/Cluster/cyano.txt`` for the Cluster examples, although currently the tutorial doctests are disabled as something breaks under Windows - see https://github.com/biopython/biopython/commit/c2e2b388f2adc62bd0b143687091d2dc469c5b33

**Comment by Gasta88** [comment]
Thanks, I'll create another PR for `chapter_cluster.tex` and keep the doctest offline.

Feel free to merge them later on.

**Comment by souravsingh** [comment]
I believe the issue is now fixed

**Comment by peterjc** [comment]
Yes, I think you are right based on repeating that grep search. Thanks!
