### ISSUE TITLE
Missing HSP attribute in Biopython tutorial

### ISSUE THREAD

**Issue by RandallJEllis** [biopython/biopython#771]
Hello, 

In the Biopython tutorial there is a figure, Figure 7.4 (http://biopython.org/DIST/docs/tutorial/Tutorial.html#fig:blastrecord)

This figure shows all the attributes for all objects for parsing an XML output file after running a BLAST. However, in the HSP box, align_length is missing. I had to check the Biopython docs to find it, so I thought it should be placed in this figure.

**Comment by peterjc** [comment]
Could you edit the image? Or should we just remove it?

As an aside, I would expect the old ``NCBIXML`` parser to be deprecated as ``Bio.SearchIO`` matures; CC @bow

**Comment by RandallJEllis** [comment]
![blastrecord_withalignlength](https://cloud.githubusercontent.com/assets/7551835/13120442/db4fc5ea-d57b-11e5-9d70-6e458672095e.png)

Not the prettiest, but align_length is now in the bottom of the HSP box

**Comment by peterjc** [comment]
Very usable :)

@chapmanb do you recall how the ``BlastReport.dai`` file was created? It would be best to update that source diagram and generate the PNG, but it may not be worth spending much time on this.

I'm inclined to just check in @RandallJEllis' hand edited ``BlastReport.png`` file.

**Comment by chapmanb** [comment]
Thanks so much for the heads up on the old diagram. This was created with dia (http://dia-installer.de/). I updated the original dia and png objects to add in align_length. Thank you again.
