### ISSUE TITLE
SearchIO concatenated blast xml files

### ISSUE THREAD

**Issue by zclandry** [biopython/biopython#772]
Hello,
Would it be possible to add support to the SearchIO.BlastIO module for concatenated blast-xml files (multiple xml results files concatenated into a single file)? The NCBIXML Blast parser has this functionality, and it would make the transition to the new package somewhat easier.
Thank you for all the help.

**Comment by peterjc** [comment]
Why do you have concatenated XML files? The only reason our ``NCBIXML`` parser handled this was that older versions of NCBI BLAST wrongly generated such output (concatenated XML files are no longer valid XML).

CC @bow

**Comment by bow** [comment]
Hi @zclandry,

Indeed, the concatenated files are technically invalid XML. There are ways to split the incorrectly-concatenated XML files (I can point you to some tricks that could be useful). In most cases, I prefer that we parse only valid XML files.

**Comment by bow** [comment]
@peterjc , shall I close this issue? I would prefer that we do not allow invalid XML files ...

**Comment by peterjc** [comment]
Given the NCBI fixed this, I'm OK with you opting not to support it - they are clearly invalid XML.
