### ISSUE TITLE
failed to build biopython "Bio/cpairwise2module.c:12:20: fatal error: "

### ISSUE THREAD

**Issue by drelo** [biopython/biopython#777]
Hi, I installed numpy (I tested this importing numpy in the python terminal without problems)
This is a clean install Ubuntu 15.10, with python 2.7.10 in a new machine. 

I tried pip install biopython and it failed, I then downloaded following the GitHub instructions.  I then tried to build and got the following error:

`→ python setup.py build
running build
running build_py
running build_ext
building 'Bio.cpairwise2' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c Bio/cpairwise2module.c -o build/temp.linux-x86_64-2.7/Bio/cpairwise2module.o
Bio/cpairwise2module.c:12:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

How can I fix this? Thanks in advance.

**Comment by JoaoRodrigues** [comment]
You are missing the Python headers, which you can install with "apt-get
install python-dev".

More importantly, why did the pip installation fail in the first place?

**Comment by peterjc** [comment]
Unless @drelo want to continue this, I think we can close this discussion. Hopefully ``apt-get install python-dev`` solved things.
