### ISSUE TITLE
Too many values to unpack in Bio.PDB.DSSP

### ISSUE THREAD

**Issue by iCHAIT** [biopython/biopython#780]
I took [this](https://github.com/BioPython/BioPython/blob/master/Bio%2FPDB%2FDSSP.py#L223-L231) from `Bio.PDB.DSSP` and ran it but it fails:

```python
import Bio
from Bio.PDB import PDBParser, DSSP

p = PDBParser()
structure = p.get_structure("1MOT", "1MOT.pdb")
model = structure[0]
dssp = DSSP(model, "1MOT.pdb", dssp="dsspcmbi"))
# DSSP data is accessed by a tuple (chain_id, res_id)
a_key = list(dssp)[2]
# residue object, secondary structure, solvent accessibility,
# relative accessiblity, phi, psi
dssp[a_key]
```

Here is the traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "/usr/lib64/python2.7/site-packages/Bio/PDB/AbstractPropertyMap.py", line 49, in __getitem__
    translated_id = self._translate_id(key)
  File "/usr/lib64/python2.7/site-packages/Bio/PDB/AbstractPropertyMap.py", line 117, in _translate_id
    chain_id, res_id = ent_id
ValueError: too many values to unpack
too many values to unpack
```

The `1M0T.pdb` file has been downloaded from [Tests/PDB/1MOT.pdb](https://github.com/BioPython/BioPython/blob/master/Tests%2FPDB%2F1MOT.pdb)

**Comment by peterjc** [comment]
Which version of the DSSP command line are you using?

**Comment by iCHAIT** [comment]
@peterjc How do I check that?

**Comment by peterjc** [comment]
You're trying to run a binary named ``dsspcmbi``, but on my test machine,

```
$ dssp --version
mkdssp version 2.0.4
```

The good news is using this I can still recreate your error:

```
$ cat issue780.py
import Bio
print(Bio.__version__)
from Bio.PDB import PDBParser, DSSP
p = PDBParser()
structure = p.get_structure("1MOT", "1MOT.pdb")
model = structure[0]
dssp = DSSP(model, "1MOT.pdb", dssp="dssp")
a_key = list(dssp)[2]
dssp[a_key]
[buildslave@ppserver PDB]$ python2.7 issue780.py
1.66+
Traceback (most recent call last):
  File "issue780.py", line 9, in <module>
    dssp[a_key]
  File "/home.../lib/python2.7/site-packages/Bio/PDB/AbstractPropertyMap.py", line 51, in __getitem__
    translated_id = self._translate_id(key)
  File "/home.../site-packages/Bio/PDB/AbstractPropertyMap.py", line 119, in _translate_id
    chain_id, res_id = ent_id
ValueError: too many values to unpack
```

**Comment by peterjc** [comment]
I think this is simply due to the nature of the DSSP class interface, consider:

```python
>>> print(list(dssp)[2])
(3, 'A', 'H', 0.7075471698113207, -61.2, -42.4, -2, -0.7, 4, -3.0, 1, -0.2, 5, -0.2)
>>> print(list(dssp.keys())[2])
('A', (' ', 251, ' '))
```

i.e. You did not get the key you expected. Using ``a_key = list(dssp.keys())[2]`` seems to work fine.

**Comment by JoaoRodrigues** [comment]
Indeed, this is an issue with the documentation on that particular docstring. The proper way to access the residue keys is by using dssp.keys(). Iterating over the dssp object goes over the dssp data.

**Comment by mathuin** [comment]
@peterjc The version we are using is this:
```
# dsspcmbi --version
mkdssp version 2.2.1
```

The example docstring in the class shows dssp[a_key] returning six values: residue object, secondary structure, solvent accessibility, relative accessibility, phi and psi.  The output you show above has fourteen elements in the output tuple, which appear to be relative indexes and energies according to the code in _make_dssp_dict() just above the class definition for DSSP.

The docstring should probably be updated to support both the usage of dssp.keys() and the additional values being stored in the dssp variable.

**Comment by peterjc** [comment]
Yes. We aspire to have all our docstrings tested as doctests, but external dependencies like the DSSP binary make that tricky.

Could you prepare a pull request to update this documentation?

**Comment by iCHAIT** [comment]
@peterjc 

For the PR, should I change the comments to reflect the 14 values.

Or should I change [this](https://github.com/BioPython/BioPython/blob/master/Bio%2FPDB%2FDSSP.py#L228) particular line to - 
```python
a_key = list(dssp.keys())[2]
```

**Comment by peterjc** [comment]
The key fix is most important, but if you can see a good place to document the 14 values, even better :)
