### ISSUE TITLE
Question regarding pairwise alignment

### ISSUE THREAD

**Issue by d3sire** [biopython/biopython#789]
I have mad a SO question regarding. Can anyone look at it?
Here is the [link](http://stackoverflow.com/questions/36142371/nucleotides-separator-in-the-pairwise-sequence-alignment-bio-python)

Any help is appreciated.

**Comment by peterjc** [comment]
I've answered on SO with a possible trick to get this to work, but I'm not sure if this (giving the inputs as lists of elements) should be regarded as supported or not.

**Comment by d3sire** [comment]
@peterjc Yes. Your answer helped! I think if this is supported behavior, it would be good to document it.

**Comment by peterjc** [comment]
Over on #782, @MarkusPiotrowski (who also replied on SO) says he thinks this was meant to be supported behaviour, but wasn't properly documented.

**Comment by d3sire** [comment]
Yes, I see the discussion. Thank you.

**Comment by MarkusPiotrowski** [comment]
The ability of ```pairwise2``` to work with lists is (now) documented in the docstring as well as in the tutorial.

Closing.

**Comment by mdehoon** [comment]
@d3sire 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
