### ISSUE TITLE
Tutorial - Probably a typo in the example lines - 4.7  Slicing a SeqRecord

### ISSUE THREAD

**Issue by erkisala** [biopython/biopython#790]
In the "4.7  Slicing a SeqRecord" section there is a typo (in bold):

>>> print(sub_record.features**[20]**)
type: CDS
location: [42:480](+)
qualifiers:
    Key: codon_start, Value: ['1']
    .....
   
It should be the following (the position changed after slicing):
>>> print(sub_record.features**[1]**)
type: CDS
location: [42:480](+)
qualifiers:
    Key: codon_start, Value: ['1']
    .....

**Comment by peterjc** [comment]
Yes, you're quite right. I've fixed that ready for the next release - thank you :)
