### ISSUE TITLE
NexusIO tree template

### ISSUE THREAD

**Issue by sefakilic** [biopython/biopython#796]
The Bio/Phylo/NexusIO.py has the following nexus template on line 28:

`TREE_TEMPLATE = "Tree tree%(index)d=[&U]%(tree)s"`

I think `[&U]` is used to denote that the tree is unrooted ([link](http://hydrodictyon.eeb.uconn.edu/eebedia/index.php/Phylogenetics:_NEXUS_Format)). However, the template is applied to all trees, even if it is a rooted tree.

**Comment by peterjc** [comment]
CC @etal

**Comment by etal** [comment]
I'm having trouble finding a definitive source for what to do for rooted trees -- use `[&R]` instead of `[&U]`, or omit the bracketed expression altogether?

**Comment by cymon** [comment]
Hi Eric,

I'd omit the expression altogether as it's only a comment, and I'm not
aware of any software that takes any notice of it...

Regards, Cymon

On 20 April 2016 at 19:44, Eric Talevich <notifications@github.com> wrote:

> I'm having trouble finding a definitive source for what to do for rooted
> trees -- use [&R] instead of [&U], or omit the bracketed expression
> altogether?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/biopython/biopython/issues/796#issuecomment-212554295>
>
<http://orcid.org/0000-0002-4927-979X>
