### ISSUE TITLE
wrong residue ID when parsing mmCIF file

### ISSUE THREAD

**Issue by ofajardo** [biopython/biopython#806]
I am using the lastest version of biopython in the repository.

Residues IDs are not correct when reading an mmCIF file. The first field of the residue ID, which indicates if the residue is an ATOM (' ') or HETATOM ('H_something') is always empty in case of HETATOMS.

Let's say I want to iterate through all residues and get only the aminoacids that are also ATOM, discarding the HETATOM. The structure 1DAU is an extreme example where I should not get anything, because all the atoms are not aminoacids, and all aminoacids are hetatoms. If I do with the  Bio.PDB.PDBParser, then as expected residue_name is not printed in the last line, because the first element in the residue id tuple is "H_T32" or somethig like that, however, when dealing with an mmCIF, I get (' ', 7, ' '), the first element is an empty space, and therefore the residue id gets printed.

Could you please look at it? Thanks a bunch!

```
protein_ID="1dau"
pdb_file_path="1dau.cif"
MMCIF_parser =  MMCIFParser()
pdb_structure = MMCIF_parser.get_structure(protein_ID, pdb_file_path)

model = pdb_structure[0]

for chain in model:
    for residue in chain.get_list():
        #check if the residue is aminoacid
        if PDB.is_aa(residue):
            res_id = residue.get_id()
            print res_id
            #proceed only if the residue is not HETATM
            if res_id[0] == ' ':
                residue_name = residue.get_resname()
                print residue_name
```

**Comment by peterjc** [comment]
Thanks @ofajardo - this means you have the code from GitHub after I merged #800 from @JoaoRodrigues which should have fixed #778 and #779?

**Comment by ofajardo** [comment]
That should be correct. For the issue posted before, I went to the main web page (https://github.com/biopython/biopython) and clicked on "download ZIP". I did today, so I guess that should be #800? Is there a way to check what version is it? (I dont want to install git)

**Comment by peterjc** [comment]
From your description this would have been the very latest code today - probably https://github.com/biopython/biopython/commit/009d913ac2d8ed010db20aa43eab489e0031d9dd - so if you want to be 100% certain, look at line 131 of ``Bio/Align/__init__.py`` to see if it has that change. Sadly we don't update the version string between releases, so the standard version check is not very helpful:

```
$ python -c "import Bio; print(Bio.__version__)"
1.66+
```

**Comment by ofajardo** [comment]
This is my line 131:
        >>> from Bio.Align import MultipleSeqAlignment

is it good?

**Comment by peterjc** [comment]
@ofajardo that's what we'd expect if you have the latest code as of https://github.com/biopython/biopython/commit/009d913ac2d8ed010db20aa43eab489e0031d9dd - so good :)

I tweaked your example slight (imports, print functions) and tried it on Python 2.6 and 3.5,

```
$ curl -O http://files.rcsb.org/download/1DAU.cif
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  104k    0  104k    0     0   104k      0 --:--:-- --:--:-- --:--:--  104k
```

```
$ python2.6 bug806.py 
(' ', 7, ' ')
T32
(' ', 8, ' ')
T32
(' ', 19, ' ')
T32
(' ', 20, ' ')
T32
```

```
$ python3.5 bug806.py 
(' ', 7, ' ')
T32
(' ', 8, ' ')
T32
(' ', 19, ' ')
T32
(' ', 20, ' ')
T32
```

Using this as file ``bug806.py``:

```
from Bio import PDB
from Bio.PDB.MMCIFParser import MMCIFParser

protein_ID="1dau"
pdb_file_path="1dau.cif"
MMCIF_parser =  MMCIFParser()
pdb_structure = MMCIF_parser.get_structure(protein_ID, pdb_file_path)

model = pdb_structure[0]

for chain in model:
    for residue in chain.get_list():
        #check if the residue is aminoacid
        if PDB.is_aa(residue):
            res_id = residue.get_id()
            print(res_id)
            #proceed only if the residue is not HETATM
            if res_id[0] == ' ':
                residue_name = residue.get_resname()
                print(residue_name)
```

That's the same as you, right? But you expect something different based on a PDB file?

**Comment by ofajardo** [comment]
Correct, What you see is also what I get. Now, if use the pdb file by changing:
.
```
pdb_file_path="1dau.cif"
MMCIF_parser =  MMCIFParser()
pdb_structure = MMCIF_parser.get_structure(protein_ID, pdb_file_path)
```

by:

```
pdb_file_path="1dau.pdb"
pdb_parser = PDBParser()
pdb_structure = pdb_parser.get_structure(protein_ID, pdb_file_path)
```

Now the code prints:

('H_T32', 7, ' ')
('H_T32', 8, ' ')
('H_T32', 19, ' ')
('H_T32', 20, ' ')

Which is correct, the residue ID gets printed but not the resiude name, because the last if fails.

**Comment by JoaoRodrigues** [comment]
@ofajardo, thanks for the extensive testing. Perfect bug reporting etiquette :) I'll have a look at it this weekend.

**Comment by ofajardo** [comment]
Thanks Joao and Peter for the always quick reply!

Otto

**Comment by JoaoRodrigues** [comment]
The mmCIF format should note on the first field of the residue is a HETATM or not (in the field _atom_site.group_PDB ([link](http://mmcif.wwpdb.org/docs/tutorials/content/atomic-description.html)), but for this particular structure it doesn't. Have a look at `1ctf` ([link](http://files.rcsb.org/view/1CTF.cif)) for a *good* example, in which your code runs as it should. 

There are other mentions to this issue in other mailing lists, interestingly about modified nucleotides (which is this case): [example](http://x3dna.org/articles/assignment-of-hetatm-vs-atom-records-for-modified-nucleotides-in-pdb-vs-pdbx-mmcif-format), [example](https://lists.sdsc.edu/pipermail/pdb-l/2015-May/006046.html).

Unfortunately there is no much we can do. One way to solve this would be to have a set with residue names of what you consider to be a canonical amino or nucleic acid and check at every turn.

**Comment by ofajardo** [comment]
HI, 

Yes, you are absolutely right. There are a lot of structures affected by this. It seems however the problem comes from the fact that those non standard residues are modified residues part of the chain and not ligands, and therefore it is not clear whether they are really an HETATM or not. I guess the programmer has to decide what to do, in my case I was more interested in ligands, therefore I think I will trust what the mmCif says.

Thanks a lot again! I will do some more tests on my side and report if I see anything strange.

**Comment by ofajardo** [comment]
Another general question: I noticed that parsing a cif file is around 7 times slower than parsing a pdb file with biopython. Why is this?

**Comment by peterjc** [comment]
That sounds worth spending some time investigating - there are various Python profiling tools you could run, it might be just one or two places we could optimise? If you do this, I would focus on Python 3.5 as there is less benefit in speeding up things under Python 2 nowadays.

**Comment by ofajardo** [comment]
The difference is in this line:

'''
pdb_structure = pdb_parser.get_structure(protein_ID, pdb_file_path)
'''

versus this one:

'''
pdb_structure = MMCIF_parser.get_structure(protein_ID, pdb_file_path)
'''

in the case of mmCif, the function get_structure initializes the class MMCIF2DICT, in the __init__ method, there is a call to the function _tokenize, in the the same class, this function does in line 76 (of MMCIF2DICT.py) this call over 1000 times:

'''
tokens = shlex.split(line)
'''

This seems to be the expensive thing. Maybe using re module would improve it?

**Comment by ofajardo** [comment]
Yet another question: when is expected (aprox) a new version of biopython to be released incorporating the latest changes in the mmCif parsing?

**Comment by peterjc** [comment]
I was hoping to do the Biopython 1.67 release last week, but we've had website issues which have taken priority - see http://lists.open-bio.org/pipermail/biopython-dev/2016-April/021308.html and http://lists.open-bio.org/pipermail/biopython-dev/2016-April/021309.html - but soon.

**Comment by JoaoRodrigues** [comment]
I've actually worked on this mmCIF parser optimization part, see #580. The pull request is still pending though and by now is outdated and conflicts with these recent changes. I'd have to re-work it. But indeed, shlex is the issue here.. If we look only at coordinate information (which is a shame given the rich annotations of mmCIF) we can speed up the parsing quite a bit.

**Comment by ofajardo** [comment]
Thanks for all the comments, I am satisfied with the current status. 

I am looking into mmCif, as PDB.org is saying that they will phase out the pdb format this year, and wanted my code to work with the new format. However, I am still wondering what this phasing out really means (does it mean for example that in the future we will be able to download only mmCif files from pdb.org and not pdb anymore? or maybe that they will accept only mmCif for submission, but then internally convert them to pdb anyway?) I have seen that large structures are available in mmCif only.
