### ISSUE TITLE
Suggest deprecating MySQLDB

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython#821]
Currently we support MySQLDb and sql.connector for MySQL access in BioSQL. I suggest deprecating MySQLDB which is a C dependency.

This would require some changes to DocSQL.

**Comment by peterjc** [comment]
Sure - or just prepare to deprecate DocSQL if no one seems to be using it (ask on the mailing list)?

**Comment by peterjc** [comment]
We removed Bio.DocSQL in Biopython 1.71, so the only thing in Biopython still using MySQLDB is BioSQL.

**Comment by peterjc** [comment]
In light of #1931 and the existence of an active Python 3 compatible fork, I don't think we need to deprecate support for MySQLDB.

**Comment by peterjc** [comment]
For future reference,

https://pypi.org/project/mysqlclient/
https://github.com/PyMySQL/mysqlclient-python
