### ISSUE TITLE
Rename Bio.Seq.back_transcribe to Bio.Seq.reverse_transcribe

### ISSUE THREAD

**Issue by StephDC** [biopython/biopython#864]
I think using Reverse-transcribe would better describe what this program do. It is a more popular term describing the reverse-transcription from RNA to DNA, usually related to the reverse transcriptase and the retrovirus.

**Comment by peterjc** [comment]
Neither of the ``Bio.Seq`` functions and methods ``transcribe`` and ``back_transcribe`` change the sequence order, which is something which happens at a biological level from the template strand. The suggested name ``reverse_transcribe`` can also be interpreted as reverse(transcribe(...))`` which is quite different.

Moreover this would be changing a naming convention in Biopython going back 16 years to the start of Biopython.

You would need to have a very compelling argument to persuade me this is worth changing, but by all means raise this on the mailing list (with a link back to this issue).
