### ISSUE TITLE
Check handle mode in Bio.SeqIO etc?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#874]
In regards to #872 some sanity testing for the mode of handles passed to `Bio.SeqIO.parse()` etc might be sensible to give meaningful error messages when (accidentally) passing a binary handle to a parser expected a text handle.

Right now we get a range of errors, e.g.
- `ValueError: Is this handle in binary mode not text mode?` for `fastq`
- `TypeError: a bytes-like object is required, not 'str'` for `tab`
- `TypeError: startswith first arg must be bytes or a tuple of bytes, not str` for `phd`, `ig` and `ace`
- `IndexError: index out of range` for `qual` and `pir` and `fasta`
- Zero records but no error for `embl`, `genbank`

Likewise the reverse can happen when giving a text handle to a parser expecting binary, e.g.
- `ValueError: ABI files has to be opened in 'rb' mode.` for `abi`
- `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 15: invalid start byte` for `sff` when given a text handle

Something like this ought to have the desired effect (although I think the error messages need better wording:

```
--- a/Bio/File.py
+++ b/Bio/File.py
@@ -57,7 +57,8 @@ def as_handle(handleish, mode='r', **kwargs):
     All other inputs are returned, and are *not* closed

         - handleish  - Either a string or file handle
-        - mode       - Mode to open handleish (used only if handleish is a string)
+        - mode       - Mode to open handleish (used if handleish is a string,
+                       if handleish is a handle checks compatible)
         - kwargs     - Further arguments to pass to open(...)

     Example:
@@ -87,7 +88,22 @@ def as_handle(handleish, mode='r', **kwargs):
         else:
             with open(handleish, mode, **kwargs) as fp:
                 yield fp
+    elif hasattr(handleish, "mode"):
+        if "b" in mode and "b" not in handleish.mode:
+            raise ValueError("Binary mode requested (%r), "
+                             "but given handle mode %r" %
+                             (mode, handleish.mode))
+        if "b" not in mode and "b" in handleish.mode:
+            raise ValueError("Text mode requested (%r), "
+                             "but given handle binary mode %r" %
+                             (mode, handleish.mode))
+        yield handleish
     else:
+        # It is already handle like, but is the mode OK?
+        try:
+            existing_mode = handleish.mode
+        except AttributeError:
+            existing_mode = mode
         yield handleish

```

TODO: Test this doesn't break anything, and add some test to verify this works as intended.

**Comment by twrightsman** [comment]
Can confirm it breaks a few things:

```
======================================================================
ERROR: test_AlignIO
----------------------------------------------------------------------
...
ValueError: Text mode requested ('rU'), but given handle binary mode 'r'
```

**Comment by mdehoon** [comment]
I believe this is now being taken care of by `SequenceIterator` in `Bio.SeqIO.Interfaces`. Can this be closed?

**Comment by peterjc** [comment]
Yes, that refactoring makes the proposal here obsolete, and ought to have left the error types and messages more consistent.
