### ISSUE TITLE
Fix RST docstrings for Bio.PDB.DSSP

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#878]
See http://biopython.org/DIST/docs/api/Bio.PDB.DSSP%27-module.html and http://biopython.org/DIST/docs/api/Bio.PDB.DSSP%27.DSSP-class.html

Problems include the bullet point list for the main docstring (suggest escaping each letter as a literal, especially the gap), and the DSSP class ``__init__`` method docstring.

Noticed while reviewing #876

**Comment by twrightsman** [comment]
Can we use a definition list instead? It doesn't seem like a bulleted list looks nice to convey the DSSP codes.

```
The DSSP codes for secondary structure used here are:

    H
        Alpha helix (4-12)

    B
        Isolated beta-bridge residue

    E
        Strand

    G
        3-10 helix

    I
        pi helix

    T
        Turn

    S
        Bend

    \-
        None
```

**Comment by twrightsman** [comment]
Also, didn't we want to try to establish some docstring conventions like numpy? I edited DSSP's class docstring to follow numpy's [guidelines](https://github.com/numpy/numpy/blob/master/doc/EXAMPLE_DOCSTRING.rst.txt):
```
Parameters
----------
model : L{Model}
    the first model of the structure
pdb_file : string
    a PDB file
dssp : string
    the dssp executable (ie. the argument to os.system)
```

**Comment by peterjc** [comment]
I'd have to dig out the old thread, but yes, as I recall a sub-set of the NumPy RST docstring guidelines seemed sensible (avoiding heavy markup which makes reading the plain text hard, e.g. via the Python prompt ``help(...)`` function).

#882 applied, thank you.
