### ISSUE TITLE
Oracle BioSQL

### ISSUE THREAD

**Issue by twrightsman** [biopython/biopython#890]
Migrated from https://redmine.open-bio.org/issues/3398

@yong27 said:

> I just tested Oracle BioSQL for Biopython using cx_Oracle. It includes some Biopython modification due to my genbank file test. I attached this patch and describe how it was generated.
> 
> ```
> [yong27@dev biopython]$ git ls-remote --heads origin
> 902947a7df49d8529faeb7e1bfb55b2d06252272        refs/heads/master
> [yong27@dev biopython]$ git diff origin/master master > oracle_biosql.diff
> [yong27@dev biopython]$
> ```
> 
> This is a example how to use Oracle BioSQL. Oracle, Oracle BioSQL schema, cx_Oracle has to be installed.
> 
> ```
> from context lib import contextmanager
> from BioSQL import BioSeqDatabase
> 
> @contextmanager
> def biosqlconn(dbname):
>     server = BioSeqDatabase.open_database(driver='cx_Oracle, user='USER', passwd='PASS')
>     conn = server[dbname]
>     try:
>         yield conn
>     except:
>         conn.adaptor.rollback()
>         raise
>     else:
>         conn.adaptor.commit()
>     finally:
>         conn.adaptor.close()
> 
> with biosqlconn('mydb') as biosqldb:
>     record = biosqldb.lookup(accession='1234')
> ```
> 
> [oracle_biosql.diff.txt](https://github.com/biopython/biopython/files/379073/oracle_biosql.diff.txt)

**Comment by twrightsman** [comment]
@peterjc said:

> Hi, and thank you for looking at this.
> 
> Can you make a new test file test_BioSQL_cxOracle.py based on test_BioSQL_MySQLdb.py or test_BioSQL_psycopg2.py and check that works please? Note the BioSQL tests have been reorganised slightly since the Biopython 1.60 release, these files are in git. This will require putting a copy of the Oracle BioSQL schema in the Tests/BioSQL folder.
> 
> One thing that worries me is the execute command, where you remove the semi-colon. What happens with multi-line SQL commands?
> 
> Regards,
> 
> Peter
> 
> P.S. Are the changes in Bio/SeqIO/InsdcIO.py relevant to this patch?

**Comment by twrightsman** [comment]
@yong27 replied:

> Thanks Peter,
> 
> I'm writing the test test_BioSQL_cs_Oracle.py, but automatic database creation of Oracle is a little bit different with other RDBMS. It takes some time. I'll attach it in this post.
> 
> In cx_Oracle, ";" is not permitted and there are no problem in multi-line SQL commands.
> 
> Bio/SeqIO/InsdcIO.py is associated with this patch. It is because of Oracle LOB object.
> 
> Regards,
> Hyungyong

**Comment by peterjc** [comment]
We did not have access to an Oracle license, and in the absence of any interest since I'm going to close this issue now.
