### ISSUE TITLE
Legacy blast XML parser returns prematurely StopIteration

### ISSUE THREAD

**Issue by twrightsman** [biopython/biopython#911]
Migrated from https://redmine.open-bio.org/issues/3354 originally filed 16 May 2012

@mmokrejs said:

> Hi,
> I am parsing some blast 2.2.24 XML output and the last record I get is the one from
> iteration 124. I see that entry is followed by a new <Iteration_iter-num> section which
> is probably the culprit. I will try newer legacy blast but still, biopython could maybe
> overcome this bug in XML input?
> 
> ```
> blastall -p blastn -A 4 -i SRR068315.fasta -d my_targets.fasta -F 0 -S 1 -r 2 -e 10e-30 -m 7
> ```
> 
> ```
> <?xml version="1.0"?>
> <!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
> <BlastOutput>
>   <BlastOutput_program>blastn</BlastOutput_program>
>   <BlastOutput_version>blastn 2.2.24 [Aug-08-2010]</BlastOutput_version>
>   <BlastOutput_reference>~Reference: Altschul, Stephen F., Thomas L. Madden, Alejandro A. Schaffer, ~Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), ~&quot;Gapped BLAST and PSI-BLAST: a new generation of protein database search~programs&quot;,  Nucleic Acids Res. 25:3389-3402.</BlastOutput_reference>
>   <BlastOutput_db>my_targets.fasta</BlastOutput_db>
>   <BlastOutput_query-ID>lcl|1_0</BlastOutput_query-ID>
>   <BlastOutput_query-def>FYUQ5C204IQCOE length=283 xy=3463_2076 region=4 run=R_2009_07_08_19_30_38_</BlastOutput_query-def>
>   <BlastOutput_query-len>318</BlastOutput_query-len>
>   <BlastOutput_param>
>     <Parameters>
>       <Parameters_expect>1e-29</Parameters_expect>
>       <Parameters_sc-match>2</Parameters_sc-match>
>       <Parameters_sc-mismatch>-3</Parameters_sc-mismatch>
>       <Parameters_gap-open>5</Parameters_gap-open>
>       <Parameters_gap-extend>2</Parameters_gap-extend>
>       <Parameters_filter>F</Parameters_filter>
>     </Parameters>
>   </BlastOutput_param>
>   <BlastOutput_iterations>
> [cut]
>     <Iteration>
>       <Iteration_iter-num>124</Iteration_iter-num>
>       <Iteration_query-ID>lcl|124_0</Iteration_query-ID>
>       <Iteration_query-def>FYUQ5C204JXGMI length=44 xy=3954_2264 region=4 run=R_2009_07_08_19_30_38_</Iteration_query-def>
>       <Iteration_query-len>350</Iteration_query-len>
>       <Iteration_stat>
>         <Statistics>
>           <Statistics_db-num>22</Statistics_db-num>
>           <Statistics_db-len>9262</Statistics_db-len>
>           <Statistics_hsp-len>0</Statistics_hsp-len>
>           <Statistics_eff-space>0</Statistics_eff-space>
>           <Statistics_kappa>0.41</Statistics_kappa>
>           <Statistics_lambda>0.625</Statistics_lambda>
>           <Statistics_entropy>0.78</Statistics_entropy>
>         </Statistics>
>       </Iteration_stat>
>       <Iteration_message>No hits found</Iteration_message>
>     </Iteration>
>     <Iteration>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_stat>
>         <Statistics>
>           <Statistics_db-num>22</Statistics_db-num>
>           <Statistics_db-len>9262</Statistics_db-len>
>           <Statistics_hsp-len>0</Statistics_hsp-len>
>           <Statistics_eff-space>0</Statistics_eff-space>
>           <Statistics_kappa>0.41</Statistics_kappa>
>           <Statistics_lambda>0.625</Statistics_lambda>
>           <Statistics_entropy>0.78</Statistics_entropy>
>         </Statistics>
>       </Iteration_stat>
>     </Iteration>
>     <Iteration>
>       <Iteration_iter-num>125</Iteration_iter-num>
>       <Iteration_query-ID>lcl|125_0</Iteration_query-ID>
>       <Iteration_query-def>FYUQ5C204JFG82 length=173 xy=3749_2948 region=4 run=R_2009_07_08_19_30_38_</Iteration_query-def>
>       <Iteration_query-len>208</Iteration_query-len>
>       <Iteration_stat>
>         <Statistics>
>           <Statistics_db-num>22</Statistics_db-num>
>           <Statistics_db-len>9262</Statistics_db-len>
>           <Statistics_hsp-len>0</Statistics_hsp-len>
>           <Statistics_eff-space>0</Statistics_eff-space>
>           <Statistics_kappa>0.41</Statistics_kappa>
>           <Statistics_lambda>0.625</Statistics_lambda>
>           <Statistics_entropy>0.78</Statistics_entropy>
>         </Statistics>
>       </Iteration_stat>
>       <Iteration_message>No hits found</Iteration_message>
>     </Iteration>
>     <Iteration>
>       <Iteration_iter-num>126</Iteration_iter-num>
>       <Iteration_query-ID>lcl|126_0</Iteration_query-ID>
>       <Iteration_query-def>FYUQ5C204I2D3A length=146 xy=3600_2628 region=4 run=R_2009_07_08_19_30_38_</Iteration_query-def>
>       <Iteration_query-len>205</Iteration_query-len>
>       <Iteration_stat>
>         <Statistics>
>           <Statistics_db-num>22</Statistics_db-num>
>           <Statistics_db-len>9262</Statistics_db-len>
>           <Statistics_hsp-len>0</Statistics_hsp-len>
>           <Statistics_eff-space>0</Statistics_eff-space>
>           <Statistics_kappa>0.41</Statistics_kappa>
>           <Statistics_lambda>0.625</Statistics_lambda>
>           <Statistics_entropy>0.78</Statistics_entropy>
>         </Statistics>
>       </Iteration_stat>
>       <Iteration_message>No hits found</Iteration_message>
>     </Iteration>
> ```
> 
> Grep-ping for the iteration numbers I foresee few more cases like that ahead in the XML file:
> 
> ```
> <Iteration_iter-num>234</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>235</Iteration_iter-num>
>       <Iteration_iter-num>236</Iteration_iter-num>
> 
>       <Iteration_iter-num>345</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>346</Iteration_iter-num>
>       <Iteration_iter-num>347</Iteration_iter-num>
> 
>       <Iteration_iter-num>450</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>451</Iteration_iter-num>
>       <Iteration_iter-num>452</Iteration_iter-num>
> 
>       <Iteration_iter-num>555</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>556</Iteration_iter-num>
>       <Iteration_iter-num>557</Iteration_iter-num>
> 
>       <Iteration_iter-num>655</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>656</Iteration_iter-num>
>       <Iteration_iter-num>657</Iteration_iter-num>
> 
>       <Iteration_iter-num>759</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>760</Iteration_iter-num>
>       <Iteration_iter-num>761</Iteration_iter-num>
> 
>       <Iteration_iter-num>859</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>860</Iteration_iter-num>
>       <Iteration_iter-num>861</Iteration_iter-num>
> 
>       <Iteration_iter-num>956</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>957</Iteration_iter-num>
>       <Iteration_iter-num>958</Iteration_iter-num>
> 
>       <Iteration_iter-num>1050</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1051</Iteration_iter-num>
>       <Iteration_iter-num>1052</Iteration_iter-num>
> 
>       <Iteration_iter-num>1145</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1146</Iteration_iter-num>
>       <Iteration_iter-num>1147</Iteration_iter-num>
> 
>       <Iteration_iter-num>1239</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1240</Iteration_iter-num>
>       <Iteration_iter-num>1241</Iteration_iter-num>
> 
>       <Iteration_iter-num>1333</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1334</Iteration_iter-num>
>       <Iteration_iter-num>1335</Iteration_iter-num>
> 
>       <Iteration_iter-num>1430</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1431</Iteration_iter-num>
>       <Iteration_iter-num>1432</Iteration_iter-num>
> 
>       <Iteration_iter-num>1523</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1524</Iteration_iter-num>
>       <Iteration_iter-num>1525</Iteration_iter-num>
> 
>       <Iteration_iter-num>1610</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1611</Iteration_iter-num>
>       <Iteration_iter-num>1612</Iteration_iter-num>
> 
>       <Iteration_iter-num>1703</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1704</Iteration_iter-num>
>       <Iteration_iter-num>1705</Iteration_iter-num>
> 
>       <Iteration_iter-num>1792</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1793</Iteration_iter-num>
>       <Iteration_iter-num>1794</Iteration_iter-num>
> 
>       <Iteration_iter-num>1881</Iteration_iter-num>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_iter-num>1882</Iteration_iter-num>
>       <Iteration_iter-num>1883</Iteration_iter-num>
> ```
> 
> Then, no this problem anymore until end of the XML file at:
> 
> ```
> <Iteration_iter-num>25698</Iteration_iter-num>
> ```
> 
> I am attaching the XML file with entries removed since about the last problematic place, with the two "closing" XML lines added so the file should be valid XML again.

**Comment by twrightsman** [comment]
@mmokrejs replied:

> So, I reproduced this with queries using "-e 10e-98" against some completely different target database. The re-iterations since 1 occurs after same queries (124, 234, 345, etc.). It happens just because there are "No hits" all the time. If I lower down the e-value threshold it does not happen.

**Comment by twrightsman** [comment]
@mmokrejs replied:

> Happens with blastn 2.2.25 and 2.2.26. Will contact NCBI now.

**Comment by twrightsman** [comment]
@peterjc replied:

> Does that mean you have a smaller **unmodified** BLAST XML file we can use for a test case?

**Comment by twrightsman** [comment]
@mmokrejs replied:

> The first 125 entries from the FASTA query file are enough.

**Comment by twrightsman** [comment]
@peterjc replied:

> Clearly there is a problem with this XML output,
> 
> ```
> $ grep -c "<Iteration>" SRR068315_blastn.xml 
> 1902
> $ grep -c "<Iteration_query-ID>" SRR068315_blastn.xml 
> 1883
> ```
> 
> There are lots of these strange dummy blocks:
> 
> ```
>     <Iteration>
>       <Iteration_iter-num>1</Iteration_iter-num>
>       <Iteration_stat>
>         <Statistics>
>           <Statistics_db-num>22</Statistics_db-num>
>           <Statistics_db-len>9262</Statistics_db-len>
>           <Statistics_hsp-len>0</Statistics_hsp-len>
>           <Statistics_eff-space>0</Statistics_eff-space>
>           <Statistics_kappa>0.41</Statistics_kappa>
>           <Statistics_lambda>0.625</Statistics_lambda>
>           <Statistics_entropy>0.78</Statistics_entropy>
>         </Statistics>
>       </Iteration_stat>
>     </Iteration>
> ```
> 
> Biopython is (reasonably) giving one result per <Iteration> block, which therefore includes minimal results for the dummy blocks in this case:
> 
> ```
> >>> from Bio.Blast import NCBIXML
> >>> count = 0
> >>> for r in NCBIXML.parse(open("SRR068315_blastn.xml")): count += 1
> ... 
> >>> count
> 1902
> ```
> 
> Likewise on the smaller example you kindly prepared:
> 
> ```
> $ grep "<Iteration>" SRR068315_125_entries.blastn.xml -c
> 127
> $ grep -c "<Iteration_query-ID>" SRR068315_125_entries.blastn.xml
> 125
> ```
> 
> Looking at it there are 125 real results, but two dummy <Iteration> blocks, before and after lcl|125_0
> 
> ```
> >>> from Bio.Blast import NCBIXML
> >>> for r in NCBIXML.parse(open("SRR068315_125_entries.blastn.xml")): count += 1
> ... 
> >>> count
> 127
> ```
> 
> Again, Biopython is (reasonably) giving one result per <Iteration> block, which therefore includes minimal results for the two dummy blocks in this case.
> 
> It appears you have found a BLAST bug, but I do not understand what you would like changed with how Biopython is parsing this (broken) XML file.

**Comment by twrightsman** [comment]
@mmokrejs replied:

> I do not know either how to get around but one is sure. Shouldn't biopython return from the top-most iteration level only (I mean parsing the childs but returning only from the upper-most level)?
> In that case it wouldn't bother to return an empty result at all.
> 
> I contacted NCBI, I got one immediate answer but this issue wasn't answered.

**Comment by twrightsman** [comment]
@mmokrejs replied:

**Comment by twrightsman** [comment]
@mmokrejs replied:

> For the sake of archives, I note this issue is not worked around by biopython-1.62. User has to work around these in his/her own code. This is not strictly a bug in NCBIXML nor SearchIO, they don't help here around the issue. I think this issue will remain open. Same with http://biopython.org/pipermail/biopython/2011-August/007478.html .
> 
> ```
> From: "Madden, Tom \(NIH/NLM/NCBI\) \[E\]" <madden@ncbi.nlm.nih.gov>
> To: NLM/NCBI List cpp <cpp@ncbi.nlm.nih.gov>
> Date: Tue, 12 Mar 2013 17:06:23 +0000
> Subject: Re: [C++] blastall-2.2.2[4-6] XML bugs
> 
> Hello,
> 
> Thank you for your email.
> 
> Unfortunately, the NCBI does not have resources to support both the older
> (C toolkit) version of BLAST as well as the BLAST+ suite.  The BLAST
> releases since the 2.2.23 version (March, 2010) have encouraged users to
> transition to the BLAST+ applications.  The BLAST 2.2.26 announcement
> (March, 2012) stated that C toolkit binaries (e.g., blastall) would no
> longer be provided and that the source code for the C toolkit binaries
> would no longer be updated.  Help on transitioning to the BLAST+
> applications can be found in Appendix A of the BLAST User Manual at
> http://www.ncbi.nlm.nih.gov/books/NBK1763/
> 
> The BLAST+ package includes many new features that are not supported by
> the older BLAST applications (e.g., blastall, blastpgp).  These include:
> 
> 1.) blast_formatter.  The BLAST+ applications can save results as a BLAST
> archive, and the blast_formatter can then format a BLAST report from the
> archive in any supported report format.  See section 5.8 of the BLAST user
> manual at http://www.ncbi.nlm.nih.gov/books/NBK1763/ for details.
> 
> 2.) DELTA-BLAST.  DELTA-BLAST uses RPSBLAST to produce a PSSM for a
> protein query, then searches this PSSM using PSI-BLAST.  Compared to a
> standard BLASTP search, DELTA-BLAST has improved alignment quality and
> better sensitivity.  Details on the the DELTA-BLAST implementation and
> performance are available from http://www.ncbi.nlm.nih.gov/pubmed/22510480
> 
> 3.) Improved statistics.  Recent improvements in the effective length
> calculation improve the ordering of results.  Details are available at
> http://www.ncbi.nlm.nih.gov/pubmed/22691307
> 
> 4.) Faster searches for long subject and query sequences.  An article
> about BLAST+ describes the architecture and performance of the BLAST+
> applications.  The article is available from
> http://www.ncbi.nlm.nih.gov/pubmed/20003500
> 
> The upcoming release (April, 2013) will permit users to include additional
> fields in the tabular output, such as subject titles and taxonomy
> information.  It will also include improvements to the RPSBLAST
> statistics.  
> 
> Information on BLAST releases and changes are available from:
> 
> 1.) The BLAST News feed at
> http://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastNews
> 
> 2.) The blast-announce email list
> (http://www.ncbi.nlm.nih.gov/blast/blastannounce.shtml)
> 
> 3.) The NCBI Facebook and Twitter feeds.
> 
> Questions may be sent to blast-help@ncbi.nlm.nih.gov
> 
> Regards,
> 
> Tom Madden
> 
> Thomas L. Madden, Ph.D.
> Staff Scientist
> NCBI/NLM/NIH
> ```

**Comment by twrightsman** [comment]
@mmokrejs replied:

> Actually, this issue was already reported by Sebastian Bassi in 2007. ;)
> 
> http://lists.open-bio.org/pipermail/biopython/2007-October/003773.html

**Comment by twrightsman** [comment]
@peterjc replied:

**Comment by peterjc** [comment]
Can we close this? It seems to be a bug in (legacy) ``blastall``, and there had been no comments about this in the last two years.

CC @mmokrejs (original reporter) and @sbassi (raised reported something similar on the mailing list)

**Comment by mdehoon** [comment]
I think it's OK to close this issue.

**Comment by bow** [comment]
(doing some issue clean up now after a while) ~ yes, let's close this issue as there has been no further replies ...
