### ISSUE TITLE
'Bio.trie.trie' is not picklable

### ISSUE THREAD

**Issue by twrightsman** [biopython/biopython#912]
Originally filed as https://redmine.open-bio.org/issues/3337 in 2012

@superbobry said:

> Is there any reason for this, or nobody just had the need (or time) to implement pickle interface?

**Comment by twrightsman** [comment]
@etal replied:

**Comment by twrightsman** [comment]
@superbobry replied:

> A pure-Python replacement would probably be much less efficient in terms of memory consumption.

**Comment by twrightsman** [comment]
Can confirm trie object is still not pickleable:

```
$ python3
Python 3.5.2 (default, Jul 28 2016, 21:28:00) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import trie
>>> import pickle
>>> myTrie = trie.trie()
>>> myTrie['test'] = 123
>>> pickle.dump(myTrie, open('trie.pkl', 'wb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't pickle trie objects
```

**Comment by peterjc** [comment]
(On the bright side, ``Bio.Trie`` has been updated to support Python 3)

**Comment by mdehoon** [comment]
You can pickle the trie as a dictionary:
```python
>>> from Bio import trie
>>> import pickle
>>> myTrie = trie.trie()
>>> myTrie['test'] = 123
>>> pickle.dump(dict(myTrie), open('trie.pkl', 'wb'))
```
To get the same trie back, you would do
```python
>>> from Bio import trie
>>> import pickle
>>> myTrie = trie.trie()
>>> d = pickle.load(open('trie.pkl', 'rb'))
>>> for key in d:
...     myTrie[key] = d[key]
```

**Comment by mdehoon** [comment]
Adding pickle support to the trie object directly is also possible, and actually quite easy in Python. It is also possible in C, but will be quite painful and ugly code. To add pickle support in Python, we'd have to create a Bio/trie.py module or Bio/trie/__init__.py module (or some other place where the Python code can live).

**Comment by mdehoon** [comment]
@twrightsman  Would you be able to use the pygtrie package instead of the Trie code in Biopython?

**Comment by twrightsman** [comment]
I don't need Trie objects in Biopython at the moment but would it be a good idea to outsource the Trie objects to pygtrie in Biopython or is that overkill (and just adds another dependency)?

**Comment by peterjc** [comment]
We could just deprecate ``Bio.trie`` and recommend people use ``pygtrie`` instead.

**Comment by mdehoon** [comment]
@twrightsman  I am not sure if I understand. As far as I can tell, the trie modules on Biopython do not depend on anything else in Biopython, and vice versa, so they are completely independent.

**Comment by twrightsman** [comment]
@mdehoon I was suggesting that Biopython drop the Trie module (but agree with @peterjc that it should be depreciated first) and instead suggest to user to use `pygtrie` instead. Since you mention that nothing else in Biopython is dependent on Trie, it seems to be safe to depreciate?

**Comment by peterjc** [comment]
It had crossed my mind to move ``Bio.trie`` to a separate repository and entry on PyPI, but ideally someone would step up to maintain it - otherwise there is little point.

**Comment by mdehoon** [comment]
@twrightsman  OK. I think it is safe to deprecate and then remove the Trie module.

@peterjc  I had also thought about moving Bio.trie to a separate repository, but since pygtrie already exists and looks like it is actively maintained, I guess there is no point to have a separate Bio.trie as well.

**Comment by peterjc** [comment]
I have asked on #636 if they'd like to take over maintenance of Bio.trie as a standalone package.

**Comment by gmjonker** [comment]
I compared several trie implementations, and found that Bio.trie is by far the best in terms of speed and memory usage.

**Comment by peterjc** [comment]
Closing - We removed ``Bio.trie`` in #2501 

Thank you @chebizarro for issue triage.
