### ISSUE TITLE
Memory leak when working with Bio.PDB Entities

### ISSUE THREAD

**Issue by ldmoray** [biopython/biopython#913]
```python
parser = PDBParser()
structure = parser.get_structure('PHA-L', '1FAT.pdb')
structure = "some string"  # Bio.PDB entity is unreachable with a refcount > 0
```

When working with a small number of structures per session, this leak isn't an issue, but it can cause crashes when working with larger sets. One solution is to invoke the more intelligent python gc which can resolve cyclic references, but an explicit call would be useful. To prevent memory leaks, each child has to call `detatch_parent()` on itself. The function I wrote for my work is:
```python
def del_bio_entity(entity):
    """
    Delete a bio pdb entity.

    :exception TypeError: An atom is not an Entity and has no __getitem__()
    """
    try:
        for child in entity:
            del_bio_entity(child)
    except TypeError:
        # entity is an atom
        pass
    entity.detach_parent()
```

I'm not sure what name would be ideal for this function or where it should live.

**Comment by peterjc** [comment]
I can't reproduce this - what OS, version of Python, version of Biopython, and version of NumPy do you have?

```
$ python3.5 
Python 3.5.1 (default, Jun 23 2016, 12:06:32) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio.PDB import PDBParser
>>> parser = PDBParser()
>>> structure = parser.get_structure("some-id", "Tests/PDB/1A8O.pdb")
>>> structure = "some string"
>>> quit()
```

```
$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio.PDB import PDBParser
>>> parser = PDBParser()
>>> structure = parser.get_structure("some-id", "Tests/PDB/1A8O.pdb")
>>> structure = "some string"
>>> quit()
```

Can you reproduce this using any of the PDB files in the Biopython ``Tests/PDB/`` folder?

**Comment by ldmoray** [comment]
It looks like I was not understanding the default GC behaviour in CPython. I have poor notes from when I first ran into this issue a year ago. I was crashing due to memory usage when working with 1000s of PDBs one after the other, and adding the recursive `detach_parent()` fixed the issue. I was just doing some internal cleaning today and saw a comment to send it upstream. Unless someone intentionally turns off the GC, it's able to identify the structs as unreachable.

Sorry about the report, I was so focused on the proposed solution that I forgot to reproduce the bug a year later.

**Comment by peterjc** [comment]
Thanks. There may still be a problem here - if you can add any more details I'd be happy to reopen this.
