### ISSUE TITLE
New tagged release with support for HTTPS Entrez API?

### ISSUE THREAD

**Issue by tomkinsc** [biopython/biopython#916]
NCBI will be transitioning to allowing only HTTPS protocols for Entrez requests on September 30, 2016 (unless the date is pushed back). It appears changes to support HTTPS are already in the biopython [master](https://github.com/biopython/biopython/commit/d41d3f141286e0ebba9a1c4f3ae4d0c446dca080) branch, but have not yet been included in a tagged release. We'd like to update biopython in some of our projects in advance of the NCBI switchover so our users are not impacted. Will a new (>v1.67) tagged release (and PyPI package) be available soon with the HTTPS changes?

**Comment by peterjc** [comment]
Yes, that is planned http://mailman.open-bio.org/pipermail/biopython-dev/2016-August/021526.html
