### ISSUE TITLE
genbank dbsource record not exported with SeqIO.write

### ISSUE THREAD

**Issue by amvdsloot** [biopython/biopython#920]
Hello,

When I import a genbank file using Biopython Entrez.efetch and writing it as a genbank file with SeqIO write the "DBSOURCE" record / field is not exported. When fetching the same file with the standalone Entrez Edirect tool the DBSOURCE record is present (also online; see link). The dbsource record is also present in the biopython fetched version (i.e. accessible via annotations["db_source"] or when reading the raw output). So it appears to be at the level of SeqIO write. Is this a bug?

cheers,

Almer

Link to genbank test record:

http://www.ncbi.nlm.nih.gov/protein/667652385

SeqIO.write formatted genbank file:

[test_biopython_esearch.txt](https://github.com/biopython/biopython/files/439948/test_biopython_esearch.txt)

 Test script:  

[search_ncbi_test.py.txt](https://github.com/biopython/biopython/files/439970/search_ncbi_test.py.txt)

**Comment by peterjc** [comment]
I would strongly recommend you record the GenBank text from Entrez directly to disk. Biopython's SeqIO does not perfectly round-trip a GenBank/EMBL files (although this has improved slightly in the new Biopython 1.68 release).

In this case yes, the parser does capture the ``DBSOURCE`` line as ``record.annotations['db_source']`` (as a string which could be split on the semi-colons), but currently ``Bio.SeqIO.write(...)`` does not use this. The file which needs changing is ``Bio/SeqIO/InsdcIO.py`` in the ``GenBankWriter `` class ``write_record`` method.

https://github.com/biopython/biopython/blob/master/Bio/SeqIO/InsdcIO.py

This looks like an oversight - are you interested in fixing this?

**Comment by amvdsloot** [comment]
Hi Peter, thanks for the fast reply and info. I think I managed to fix it. Will do some tests on some more cases.

A
