### ISSUE TITLE
Docs: GFF Reading is Broken

### ISSUE THREAD

**Issue by erasche** [biopython/biopython#928]
The [official docs](http://biopython.org/wiki/GFF_Parsing) suggest using BCBio-GFF in order to parse GFF3 data, however as of [1.68 `sub_features` was removed](https://github.com/biopython/biopython/blob/master/DEPRECATED#L101) which bcbio-gff uses to store sub-features in the GFF3 model, [causing bcbio to break whilst reading files](https://github.com/chapmanb/bcbb/issues/110).

bcbio-gff's maintainer is [pushing people to use a different library](https://github.com/chapmanb/bcbb/issues/95#issuecomment-113196433). Biopython's docs should probably update to use [daler/gffutils](https://github.com/daler/gffutils) as well (or, as I secretly hope, re-add .sub_features on the feature model so I don't have to port thousands of lines of code to use a different library if I ever want to update biopython (and I really do since writing out topology was finally fixed in 1.68))

**Comment by peterjc** [comment]
@erasche was it obvious you could find the webpage source on GitHub now? A pull request on https://github.com/biopython/biopython.github.io/blob/master/wiki/GFF_Parsing.md would be great, assuming @chapmanb agrees?

We'd planned removing the ``.sub_features`` a long time ago as it was being used in the original object model for joins etc (now handled via ``CompoundLocation`` objects). We'd discussed adding something else for the explicit parent/child relationship needed for GFF, prior to merging Brad's GFF code (having freed up the ``Bio.GFF`` namespace), but right now ``BCBio-GFF`` can probably add ``.sub_features`` at run time if using a recent Biopython?

**Comment by erasche** [comment]
@peterjc I didn't look for the github link at all (and given that I disable CSS by default it is much less prominent). You are right, this issue is incorrectly filed. Would you prefer that I close this and re-open it on the biopython.github.io repo?

Just wanted to file this since I had a student who hit it, I'm afraid I don't have time to PR documentation updates right now.

**Comment by chapmanb** [comment]
Eric;
Sorry about the issue and thanks for reporting this. I pushed a new version of bcbio-gff (0.6.4) which should resolve this. I still do encourage folks to use gffutils but want to at least keep things compatible and working with this code for anyone depending on it. Thanks again.

**Comment by erasche** [comment]
@chapmanb thank you for the compat fixes, they're really appreciated given how much code we have that depends on bcbio-gff.

**Comment by peterjc** [comment]
@erasche don't worry about re-filing the issue. Its interesting to know some viewers will miss the website's edit button if they have CSS turned off.

@chapmanb thanks for the quick fix with v0.6.4 of bcbio-gff. Would you like to tweak the wording on https://github.com/biopython/biopython.github.io/blob/master/wiki/GFF_Parsing.md to mention https://github.com/daler/gffutils as well, or is it fine as it is?
