### ISSUE TITLE
Deprecate SeqRecord hash comparison (eg in dicts and sets)

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#929]
As discussed in #873 with @kblin, we should also do something to the `SeqRecord` default `__hash__` method which currently means you can do `my_record in set_of_records` but not `my_record in list_of_records`

e.g.

```
>>> from Bio import SeqIO
>>> list_of_records = list(SeqIO.parse("cor6_6.gb", "gb"))
>>> set_of_records = set(list_of_records)
>>> my_record = list_of_records[3]
```

This used to work, but as of Biopython 1.67 triggers the new exception:

```
>>> my_record in list_of_records
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/Bio/SeqRecord.py", line 727, in __eq__
    raise NotImplementedError(_NO_SEQRECORD_COMPARISON)
NotImplementedError: SeqRecord comparison is deliberately not implemented. Explicitly compare the attributes of interest.
```

This currently works because internally like a dict it uses `hash(my_record)`:

```
>>> my_record in set_of_records
True
```

Should we make our `SeqRecord` unhashable, i.e. match:

```
>>> hash([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```

with:

```
>>> hash(my_record)
Traceback (most recent call last):
  ...
TypeError: unhashable type: 'SeqRecord'
```

This would mean we'd get this:

```
>>> my_record in set_of_records
Traceback (most recent call last):
  ...
TypeError: unhashable type: 'SeqRecord'
```

It would be more consistent, but again could break some existing code which is deliberately using the object-comparison via the implicit hashing.

This change should be gradual with a couple of releases where using the `SeqRecord` object's `__hash__` method triggers a warning.

**Comment by chris-rands** [comment]
I just ran into this accidentally, it looks like `SeqRecord` is now unhashable:

```
>>> import Bio; print(Bio.__version__)
1.69
>>> 
>>> hash(list_of_records[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'SeqRecord'
>>> 
>>> set(list_of_records)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'SeqRecord'
```

**Comment by kblin** [comment]
You're running Python 3, I guess? This still works in Python 2.

**Comment by kblin** [comment]
Yup, apparently the logic here changed in Python 3:

>  A class that overrides `__eq__()` and does not define `__hash__()` will have its `__hash__()` implicitly set to `None`. When the `__hash__()` method of a class is None, instances of the class will raise an appropriate `TypeError` when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking `isinstance(obj, collections.Hashable)`

No such paragraph is present in the Python 2 docs.

**Comment by kblin** [comment]
I'd suggest just explicitly setting  `__hash__` to `None` so SeqRecords are unhashable on Python 2 as well to keep the behaviour consistent.

**Comment by chris-rands** [comment]
Thanks yes, sorry I should have said Python 3.6, I had not identified that was the cause but you're right of course. I agree with your suggestion too. Where would it be added? here perhaps? https://github.com/biopython/biopython/blob/master/Bio/SeqRecord.py#L752

**Comment by peterjc** [comment]
@kblin's idea should work (rather temporarily defining a hash with a warning message which I think is what I had in mind when filing this issue back in 2016).

It would need a couple of unit tests, probably in ``Tests/test_SeqRecord.py``, to confirm that hashing explicitly.
