### ISSUE TITLE
About SeqIO.parse speed 

### ISSUE THREAD

**Issue by matrs** [biopython/biopython#931]
Hi, 
I'm working with a set of fasta files, each one contains about 8-10 millions short sequences (100 bases, about 1.2GB each).
One line of my code reads (python 2.7 - ipython 5.1): 

`%time seq_list_bio = [s.seq for s in SeqIO.parse(file_name, "fasta", IUPAC.unambiguous_dna)]`
which takes about 2.5 - 3 min average 

also, I was testing a package which is only available for python 2, HTSeq
`%time seq_list = [s.seq for s in HTSeq.FastaReader(file_name)]`

which takes between 45s - 50s average

Most of the code for HTSeq is written in Cython, but as far as i know this function is pure python, you can see that here, under "class FastaReader" :
https://github.com/detrout/htseq/blob/dc208b6ad2b9c14814ca7a5dae3ff7599c165e35/HTSeq/__init__.py

I don't know much  about these 2 libraries, but the difference in time is really big and that made me wonder what could be happening. I know that sequence objects created using this two libraries are different, but they don't really appear to be that different:
HTSeq creates sequence objects with methods seq, name, description, length and a couple of others, not that different from Biopython. Maybe my code in Biopython is the problem.

**Comment by peterjc** [comment]
If you don't want the Biopython ``SeqRecord`` objects, try the underlying ``SimpleFastaParser`` defined in ``Bio.SeqIO.FastaIO``. See also https://news.open-bio.org/2009/09/25/biopython-fast-fastq/ which is a similar situation.

**Comment by mdehoon** [comment]
Since Bio.SeqIO is one of the most heavily used modules in Biopython, it would be good if we could speed it up. @matrs  Would you be willing to do run some timings on the SeqIO.parse to see which part is taking most of the time?

**Comment by matrs** [comment]
@peterjc I will try that, thank you.
 
@mdehoon  Yes, I can do that this week, but I will need some directions on how to do it (properly)

**Comment by mdehoon** [comment]
@matrs  You can you the cProfile module, for example as follows:

```python
import cProfile

cProfile.run("""\
path = "myfastafile.fa"
from Bio import SeqIO
records = SeqIO.parse(path, 'fasta')
for record in records:
    pass
""")
```

**Comment by matrs** [comment]
So I tried SimpleFastaParser and as expected is much faster (Itried everithing in python 2.7 and 3.5)
```
%%timeit 
    ...: with open(file1) as handle:
    ...:     list1 = [seq for (name,seq) in SimpleFastaParser(handle)]
    ...:     
    ...:    
1 loop, best of 3: 32.2 s per loop
```
VS

```
%timeit seq_list_bio = [s.seq for s in SeqIO.parse(file1, "fasta")]
1 loop, best of 3: 2min 10s per loop
```

About the profiling:
```
cProfile.run("""\
    ...:     ...: from Bio import SeqIO
    ...:     ...: records = SeqIO.parse(file1, 'fasta')
    ...:     ...: for record in records:
    ...:     ...:     pass
    ...:     ...: """)
    ...: 
         224886416 function calls (215890960 primitive calls) in 173.265 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    8.179    8.179  173.265  173.265 <string>:1(<module>)
  8995457   37.346    0.000   64.911    0.000 FastaIO.py:22(SimpleFastaParser)
  8995457   25.159    0.000  161.619    0.000 FastaIO.py:75(FastaIterator)
        2    0.001    0.000    0.005    0.003 File.py:47(as_handle)
  8995456    3.766    0.000    5.156    0.000 Seq.py:221(__len__)
  8995456    7.280    0.000   10.866    0.000 Seq.py:82(__init__)
  8995456   29.389    0.000   57.175    0.000 SeqRecord.py:153(__init__)
  8995456   10.127    0.000   10.127    0.000 SeqRecord.py:72(__init__)
  8995457    3.462    0.000  165.086    0.000 __init__.py:502(parse)
        1    0.000    0.000    0.000    0.000 contextlib.py:12(__init__)
        1    0.000    0.000    0.005    0.005 contextlib.py:15(__enter__)
        1    0.000    0.000    0.001    0.001 contextlib.py:21(__exit__)
        1    0.000    0.000    0.000    0.000 contextlib.py:82(helper)
 35981826    9.008    0.000    9.008    0.000 {isinstance}
17990912/8995456    8.470    0.000   12.236    0.000 {len}
 17990912    2.760    0.000    2.760    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
  8995456    2.452    0.000    2.452    0.000 {method 'join' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'lower' of 'str' objects}
 26986369   12.912    0.000   12.912    0.000 {method 'readline' of 'file' objects}
 17990912    4.841    0.000    4.841    0.000 {method 'replace' of 'str' objects}
 26986368    4.600    0.000    4.600    0.000 {method 'rstrip' of 'str' objects}
  8995456    3.507    0.000    3.507    0.000 {method 'split' of 'str' objects}
        1    0.005    0.005    0.005    0.005 {open}

```

**Comment by peterjc** [comment]
This is consistent with my expectations from past profiling - for FASTA parsing the underlying parser ``SimpleFastaParser`` is pretty good, but the object building added by ``Bio.SeqIO`` is comparatively slow (needs to create at least ``Seq``,  ``Alphabet``, and ``SeqRecord`` objects for each record, plus empty lists and dictionaries for annotations).

There might be some optimisations for building a light-weight ``SeqRecord`` (e.g. delay creating the empty objects needed for the annotations until first accessed?).

(This would likely also help with FASTQ parsing via ``Bio.SeqIO``)

**Comment by mebbert** [comment]
@peterjc, I'm curious why this issue was closed. SeqIO.parse is still pretty slow. Are there plans to improve?

**Comment by peterjc** [comment]
There is very little low hanging fruit for the FASTA parser - the underlying string bassed parser ``SimpleFastaParser`` is pretty competitive (but adding C code may help), but on top of that we have the object creation overheads and splitting off the id as the first word of the title.

If you can find something we've missed, that would be great.

With more complex file formats there is scope for speeding up common usage with lazy parsing, which would only really help with FASTA in the rare case where you don't actually want the sequence. See e.g. http://blog.evanaparker.com/2014/08/fasta-performance-comparison.html from Evan Parker's GSoC project looking at this.

**Comment by mebbert** [comment]
Ah, gotcha. I misunderstood the previous statements in this thread. When you stated "...try the underlying SimpleFastaParser...", I mistakenly interpreted that as an internal-use function ("_function") that shouldn't be called directly. Instead, there are two parsers: the light-weight and the heavy-weight parsers. Is that accurate?

**Comment by peterjc** [comment]
Yes, the heavy-weight ``Bio.SeqIO.parse(..., "fasta")`` internally calls the light-weight ``Bio.SeqIO.FastaIO.SimpleFastaParser``, which can also be used directly.
