### ISSUE TITLE
QuantifiedCode is going to be shutted down

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython#934]
https://github.com/quantifiedcode/issues/issues/62

**Comment by peterjc** [comment]
That's a shame - we might want to disable the GitHub hooks/permissions, but I don't think we need to do anything else.

We might look at alternatives like running flake8 as part of TravisCI (easier now we're using Tox) and/or our recommended git pre-commit hook?

**Comment by peterjc** [comment]
Good news, QuantifiedCode will continue for now: https://github.com/quantifiedcode/issues/issues/62#issuecomment-275705145
