### ISSUE TITLE
Entrez.esearch returns GI_ids instead of Accession_ids

### ISSUE THREAD

**Issue by Elina1994** [biopython/biopython#940]
Are you planning to update the Entrez.esearch function to return Accession_ids instead of GI_ids?

Since the NCBI website reports:
NCBI is phasing out sequence GI numbers in September 2016. Please use accession.version!

**Comment by mdehoon** [comment]
Entrez.esearch returns whatever NCBI's esearch returns (as long as it is in the DTD, which it should be). The Accession_id may be stored under a different key though than the GI_id.

**Comment by peterjc** [comment]
It will be up to the NCBI to change what ``esearch`` returns, at which point any scripts using it via Biopython's ``Bio.Entrez`` will likely need changing. As @mdehoon notes, the XML field names will probably change.

The NCBI recently gave a webinar https://www.ncbi.nlm.nih.gov/mailman/pipermail/utilities-announce/2016-September/000106.html on the changes, so I am hopeful they will update the Entrez documentation as needed before long.

See also discussion on #926.

**Comment by mdehoon** [comment]
@peterjc 
>It will be up to the NCBI to change what esearch returns, at which point any scripts using it via Biopython's Bio.Entrez will likely need changing. As @mdehoon notes, the XML field names will probably change.

If NCBI updates the DTD files to be consistent with any changes in the XML, then no updates to Bio.Entrez are needed.
