### ISSUE TITLE
Missing files for KGML_parser.py self-test

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#952]
These two files seem to be missing. I am in the process of converting the part of the self-test, "Check large metabolism", into a doc-test. Looking for input on how to proceed.

Check relations
[ko_metabolic/ko00010.xml](https://github.com/biopython/biopython/blob/master/Bio/KEGG/KGML/KGML_parser.py#L175)

Check components
[ko00253.xml', 'rU](https://github.com/biopython/biopython/blob/master/Bio/KEGG/KGML/KGML_parser.py#L186)

**Comment by peterjc** [comment]
Almost certainly you can just download those via the KEGG REST API. If not, we can ask Leighton, but I believe he's away some of this week.

**Comment by vincentdavis** [comment]
Got them, thanks

**Comment by vincentdavis** [comment]
added in pull request #950
