### ISSUE TITLE
pairwise2 still doesn't align the first nucleotide in 1.68 

### ISSUE THREAD

**Issue by darachm** [biopython/biopython#955]
I'm trying to do local alignments to find fixed regions in amplicon sequencing. 

I think I have the same problem [as documented in SO here](http://stackoverflow.com/questions/35874826/biopython-local-alignment-between-dna-sequences-doesnt-find-optimal-alignment), but I think I've got 1.68 and it's not working nicely. I'd put this in SO, but it ain't a new question and it won't let me comment.

Example pasted from terminal:

```
>>> from Bio import pairwise2                                              
>>> tmpaln = pairwise2.align.localmd(                                      
...     "CACGGGTCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA", 
...     "GTCCACGAGGTCTCT",                                                 
...     2,-5,-6,-3,-100,0,                                                 
...     penalize_end_gaps=True,one_alignment_only=True                     
...   )                                                                    
>>> print(pairwise2.format_alignment(*tmpaln[0]))                          
CACGGGTCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA
      ||||||||||||||
-----GTCCACGAGGTCTCT--------------------------------------------------------
  Score=28
>>> import Bio                                                             
>>> print(Bio.__version__) 
1.68
```

python3.5.2 btw

So that should be aligning 15 bases for a score of 30, but it's ignoring the first one and giving me 28 back. Also, it isn't treating this as a gap, or mismatch. Setting penalize_end_gaps ought doesn't fix it.

Is this the same issue as was mentioned in the SO question above?

**Comment by peterjc** [comment]
What do you think @MarkusPiotrowski?

**Comment by MarkusPiotrowski** [comment]
The problem can be solved by not setting `penalize_end_gaps` (which is default for **local** alignments) . 
```python
from Bio import pairwise2 as pw2

seq1 = 'CACGGGTCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA'
seq2 = 'GTCCACGAGGTCTCT'
aln = pw2.align.localmd(seq1, seq2, 2, -5, -6, -3, -100, 0)
print(pw2.format_alignment(*aln[0])
```
Output:
```bash
CACGGGTCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA
     |||||||||||||||
-----GTCCACGAGGTCTCT--------------------------------------------------------
  Score=30
```
I have to take a deeper look in the code, but the 'problem' may be that in *local* alignments there is no gap_open penalty for end gaps. Thus the result of 28 would occur because the gap penalty for seq2 is 0.

**Comment by darachm** [comment]
Is there a way to penalize end gaps in local mode? Is this an important use-case for this mode, or would your recommend a correctly-parameterized global alignment?

For today, I've just counted the hyphens in the second line to deliniate boundaries.

**Comment by MarkusPiotrowski** [comment]
There is no need to count the number of hyphens, the start of the alignment is returned with the  alignment:

```python
>>> print(aln[0])
('CACGGGTCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA',
 '-----GTCCACGAGGTCTCT--------------------------------------------------------', 
30.0, 5, 20)
```
The last two numbers are the start and the end of the alignment.

So, what is the problem with using local alignments but not using `penalize_end_gaps`? In you example this works nicely. Are there other examples where this does not work? What is your final goal when using pairwise alignment: finding adaptor sequences or primer binding sites?

**Comment by darachm** [comment]
Oh yeah, bad example. I'm trying to delineate segments of the amplicon, so if I've got a mistake, let's say a G->A at base6:

    seq1 = 'CACGGATCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA'
    aln = pw2.align.localmd(seq1, seq2, 2, -5, -6, -3, -100, 0)
    aln[0]

That gives me an alignment that starts at 6.

**Comment by MarkusPiotrowski** [comment]
First of all, let me say that your first example shows that there is a problem in the code (which is related to the `penalize_end_gaps` option). The two 'G's align and of course this should give a mach in the score. I will investigate this.

Your last example behaves as expected, there is no chance for a **local** alignment to start with a mismatch, unless a mismatch gives a positive score (local alignments only start at scores greater than 0). So you can try the following (setting the mismatch score to a positive value): 

```
>>> aln = pw2.align.localmd(seq1, seq2, 2, 1, -6, -3, -100, 0)
>>> print(pw2.format_alignment(*aln[0]))
CACGGATCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA
     |||||||||||||||
-----GTCCACGAGGTCTCT--------------------------------------------------------
  Score=29
```

The mismatch score can be very small, eg. 0.001. I don't know how difficult it would be to find parameters that suit your needs.

Still, I don't see the need for `penalize_end_gaps`?

BTW, `penalize_end_gaps` can be supplied as a tuple for the first and second sequence, respectively:

```
>>> seq1 = 'CACGGGTCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA'
>>> seq2 = 'GTCCACGAGGTCTCT'
>>> aln = pw2.align.localmd(seq1, seq2, 2, -5, -6, -3, -100, 0, penalize_end_gaps=(True, False))
>>> print(pw2.format_alignment(*aln[0]))
CACGGGTCCACGAGGTCTCTCGCAGTATCTTTAAGTTCGGTGTACGCTGCAGGTCGACCGCACGGGCGTGATGTGA
     |||||||||||||||
-----GTCCACGAGGTCTCT--------------------------------------------------------
  Score=30
```

**Comment by darachm** [comment]
Right, now I'm recalling that SW is supposed to terminate if the score drops below zero. That make perfect sense. By keeping mismatch scores in the positive and scaling expectations accordingly, that'll work just fine for my application.

Thanks for your time, now and in developing this package. I'm assuming I leave this issue open for the penalize_end_gaps first issue,

**Comment by MarkusPiotrowski** [comment]
After thinking about it:
In Smith-Waterman local alignments all negative scores where set to 0, thus penalizing end gaps doesn't make sense at all (they will/should be set to zero). So, `penalize_end_gaps` shouldn't be allowed for local alignments. 
@peterjc: Should I implement this as an error or a warning? I have no idea how many people try to use `penalize_end_gaps` when doing local alignments.

**Comment by peterjc** [comment]
You could be cautious and go for a warning saying ``penalize_end_gaps`` has been ignored, and in future trying to use it for a local alignment will give an error?

**Comment by MarkusPiotrowski** [comment]
Penalizing end gaps in local alignments violates the implemented Smith & Waterman algorithm. ```pairwise2``` now gives a warning when a user tries to do this.

Closing

**Comment by mdehoon** [comment]
@darachm 

We are adding some convenience functions to `Bio.Align`, which similar functionality as the functions provided by `Bio.pairwise2`. If you have any comments or suggestions for these convenience functions, please let us know at issue #5290.
