### ISSUE TITLE
Unresolved reference '_gpi20iterator' in UniProt.GOA

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython#958]
As far as I can tell this function is not defined. Maybe this is just a type o but I am not sure.
[_gpi20iterator](https://github.com/biopython/biopython/blob/589bc075ace24cb29bcd69c9789963df7febeb4d/Bio/UniProt/GOA.py#L179)

**Comment by peterjc** [comment]
One for @idoerg I think?

**Comment by svalqui** [comment]
@peterjc Could you please close this one?, it was removed on this commit e9cebed70bbebbcfacf573894fa2ce967c8aba4d

**Comment by peterjc** [comment]
Thanks
