### ISSUE TITLE
Regarding 18.1.6 Simple quality filtering for FASTQ files

### ISSUE THREAD

**Issue by dmenning** [biopython/biopython#963]
Does the example script in the Biopython Tutorial remove ALL reads below a certain quality score?

    from Bio import SeqIO
    good_reads = (rec for rec in \
        SeqIO.parse("SRR020192.fastq", "fastq") \
        if min(rec.letter_annotations["phred_quality"]) >= 20)
    count = SeqIO.write(good_reads, "good_quality.fastq", "fastq")
    print("Saved %i reads" % count)

If I assume the beginning and end of my sequence has low quality and I want to trim them, but there may be a random low quality read in between, then wouldn't this create a deletion at that point(s)?

Is there something written that reads the quality score, finds X number of good reads in a row at the beginning, crops everything before that, then continues to the end finding the last X number of good reads in a row, then crops everything after that leaving possibly lower quality bases in between?

**Comment by peterjc** [comment]
You seem to be mixing the terms "reads" and "bases". A single FASTQ read is a sequence of bases, e.g. 150bp. Each FASTQ read does not have a single quality score - they have one score per base.

This script does not do any trimming - it either keeps a read as is, or drops the entire read from the output file.

It keeps "good reads" defined as having a minimum PHRED quality score of 20. Any read with even a single base at quality 19 (or less) will be dropped.

Although you can write your own custom script using Biopython, it sounds like you should look at dedicated FASTQ trimming tools, e.g. sickle https://github.com/najoshi/sickle
