### ISSUE TITLE
nexus.write truncates node names

### ISSUE THREAD

**Issue by rneher** [biopython/biopython#973]
long node names get truncated when writing to a file in nexus format, which breaks the correspondence of taxa names in the header and the tree. The truncation happens here 

https://github.com/biopython/biopython/blob/master/Bio/Phylo/NexusIO.py#L70
```
    tax_labels = [str(x) for x in chain(*(t.get_terminals() for t in trees))]
```
and would be fixed by
```
    tax_labels = [str(x.name) for x in chain(*(t.get_terminals() for t in trees))]
```
The `__str__` method of clade trims names to 40 characters and appends `...`
https://github.com/biopython/biopython/blob/master/Bio/Phylo/BaseTree.py#L1064

**Comment by peterjc** [comment]
@rneher are you comfortable turning this into a pull request (and agreeing to licensing your contributions under both the Biopython Licence Agreement AND the 3-clause BSD license? See #898), and ideally adding a unit test?

@etal can you look at this?

Thanks!

**Comment by etal** [comment]
Yes, that fix looks correct.

**Comment by rneher** [comment]
I'll put in a PR.
