### ISSUE TITLE
Missing features in genbank_file

### ISSUE THREAD

**Issue by tambua81** [biopython/biopython#977]
Hi to all,
I noticed that if a try to parse with SeqIO.parse this genbank_record, it misses some features (in particulart tRNA). 
The record is X93575.1.

This is the typical output:

handle = open(gb_file, 'r')

for record in SeqIO.parse(handle,"genbank"):
    for feature in record.features:
        print feature  

OUTPUT:

type: source
location: [0:2799](+)
qualifiers:
    Key: clone, Value: ['5.1 Kb EcoRI fragment']
    Key: clone_lib, Value: ['EcoRI restricted mitochondrial DNA in Bluescript']
    Key: cultivar, Value: ['Bintje']
    Key: db_xref, Value: ['taxon:4113']
    Key: mol_type, Value: ['genomic DNA']
    Key: organelle, Value: ['mitochondrion']
    Key: organism, Value: ['Solanum tuberosum']
    Key: sub_species, Value: ['tuberosum']

type: misc_feature
location: [0:866](+)
qualifiers:
    Key: note, Value: ['identical to cob gene in X58437']

type: gene
location: [372:939](+)
qualifiers:
    Key: gene, Value: ['cob']
    Key: pseudo, Value: ['']

type: CDS
location: [372:939](+)
qualifiers:
    Key: codon_start, Value: ['1']
    Key: db_xref, Value: ['PSEUDO:CAA52822.1']
    Key: gene, Value: ['cob']
    Key: pseudo, Value: ['']

type: gene
location: [1503:2697](+)
qualifiers:
    Key: gene, Value: ['rps10']

type: CDS
location: join{[1503:1810](+), [2584:2697](+)}
qualifiers:
    Key: codon_start, Value: ['1']
    Key: db_xref, Value: ['GOA:Q36552', 'InterPro:IPR001848', 'InterPro:IPR005731', 'UniProtKB/TrEMBL:Q36552']
    Key: exception, Value: ['RNA editing']
    Key: gene, Value: ['rps10']
    Key: product, Value: ['ribosomal protein S10']
    Key: protein_id, Value: ['CAA52823.1']
    Key: translation, Value: ['MRQRRALRRVSQKERPPKVTTTKIGIVIRSFDHPFLENHFWGLPPYTRKIGLPESRVLYTVLRSPHIDKKSREQFFMKIKKEFLVIKTERHELRKKFFRLKRQRIFGAQYEILFSCKTRSDKGKLQRLLRNKILALTLS']

type: exon
location: [1503:1810](+)
qualifiers:
    Key: gene, Value: ['rps10']
    Key: number, Value: ['1']

type: misc_feature
location: [1561:1562](+)
qualifiers:
    Key: gene, Value: ['rps10']
    Key: note, Value: ['RNA editing, C to U']

type: misc_feature
location: [1797:1798](+)
qualifiers:
    Key: gene, Value: ['rps10']
    Key: note, Value: ['RNA editing, C to U']

type: intron
location: [1810:2584](+)
qualifiers:
    Key: gene, Value: ['rps10']

type: misc_feature
location: [1818:1819](+)
qualifiers:
    Key: gene, Value: ['rps10']
    Key: note, Value: ['RNA editing, C to U; improves secondary structure']

type: exon
location: [2584:2697](+)
qualifiers:
    Key: gene, Value: ['rps10']
    Key: number, Value: ['2']

type: misc_feature
location: [2635:2636](+)
qualifiers:
    Key: gene, Value: ['rps10']
    Key: note, Value: ['RNA editing, C to U']

type: misc_feature
location: [2664:2665](+)
qualifiers:
    Key: gene, Value: ['rps10']
    Key: note, Value: ['RNA editing, C to U; creates rps10 stop codon']

[X93575trna.gb.zip](https://github.com/biopython/biopython/files/555392/X93575trna.gb.zip)

**Comment by peterjc** [comment]
That is strange - it works for me. Which version of Biopython do you have installed?

```
$ python -c "import Bio; print(Bio.__version__)"
1.69.dev0
$ python -c "from Bio import SeqIO; r = SeqIO.read('X93575trna.gb', 'gb'); print([f.type for f in r.features])"
['source', 'gene', 'tRNA', 'misc_feature', 'gene', 'tRNA', 'gene', 'tRNA', 'gene', 'mRNA', 'CDS', 'exon', 'intron', 'exon', 'intron', 'exon']
```

This was using the current code from Github, what will eventually become Biopython 1.69 later.

**Comment by tambua81** [comment]
Hi Peter, my version is 1.68 on Archlinux, installed with pip installer

**Comment by peterjc** [comment]
I am puzzled. I have installed Biopython 1.68 on Mac OS X, and under both Python 2.7 and 3.5 the tRNA features are shown.

```
$ python -c "import Bio; print(Bio.__version__)"
1.68
$ python -c "from Bio import SeqIO; r = SeqIO.read('X93575trna.gb', 'gb'); print([f.type for f in r.features])"
['source', 'gene', 'tRNA', 'misc_feature', 'gene', 'tRNA', 'gene', 'tRNA', 'gene', 'mRNA', 'CDS', 'exon', 'intron', 'exon', 'intron', 'exon']
```

and:

```
$ python3.5 -c "import Bio; print(Bio.__version__)"
1.68
$ python3.5 -c "from Bio import SeqIO; r = SeqIO.read('X93575trna.gb', 'gb'); print([f.type for f in r.features])"
['source', 'gene', 'tRNA', 'misc_feature', 'gene', 'tRNA', 'gene', 'tRNA', 'gene', 'mRNA', 'CDS', 'exon', 'intron', 'exon', 'intron', 'exon']
```

Can you try this minimal example on your machine please?

**Comment by tambua81** [comment]
Dear Peter, I have tried uninstalling biopython(with pip) and reinstalling the same package with pacman (archlinux). Now it is working...
I think that something is wrong with pip package.
Version was 1.68.

**Comment by peterjc** [comment]
Very strange. Perhaps before you were using a much older Biopython from a previous installation attempt, but I still don't understand how it could have ignored the tRNA features.

At least it works now. Shall we close this issue?

**Comment by tambua81** [comment]
Yes, now it is working :)

**Comment by peterjc** [comment]
OK, closing. If this happens again please let us know - I remain puzzled about that was going wrong here. Thank you for getting in touch.
