### ISSUE TITLE
New package submission - FTPwalker

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [biopython/biopython#984]
Dear Sir or Madam:

We are pleased to present FTPwalker for consideration to Biopython: https://pypi.python.org/pypi/FTPwalker.  The Github repo is here: https://github.com/Bohdan-Khomtchouk/FTPwalker

Best wishes,
Bohdan Khomtchouk

**Comment by peterjc** [comment]
Does this have anything specifically to do with Biopython? If not, I think it is better as a separate package on PyPI as now.
