### ISSUE TITLE
DBLINK entry misformatted ( one line instead of two line )  in SeqIO genbank output

### ISSUE THREAD

**Issue by harijay** [biopython/biopython#997]
The DBLINK entry seems to be  misformatted in Genbank output. I got a test Genbank file from the NCBI gene output (NCBi-gene-send-File-Genbank format-Show GI checked). 

If I read it into Biopython and write it out the DBLINK entry goes from being a two line entry to a one line entry.

input:
```
DBLINK      BioProject: PRJNA168
            Assembly: GCF_000001405.33
```

output:

`DBLINK      BioProject:PRJNA168 Assembly:GCF_000001405.33`

I am not sure what the official spec is for DBLINK entry but I am wondering whether this is intended behavior since some parsers dont like the output format.

My code to generate the faulty DBLINK output reproduced below.

Thanks

```
>>> from Bio import SeqIO
>>> f = SeqIO.parse("sequence_io_test.gb", "genbank")
>>> records_out = []
>>> for record in f:
...     records_out.append(record)
...
>>> outhandle = open("sequence_io_test_output.gb","w")
>>> SeqIO.write(records_out,outhandle,"gb")
1
>>> outhandle.close()
>>>

```

Also adding Biopython version:

```
>>> import Bio
>>> Bio.__version__
'1.63+'



```

**Comment by peterjc** [comment]
Oh good - that saves me testing this. I'll close this now, thanks!
