### ISSUE TITLE
DBLINK record has no space after  colon  ":" in Biopython 1.68

### ISSUE THREAD

**Issue by harijay** [biopython/biopython#998]
Hi 
I am using Biopython 1.68 .
If I read in a file from NCBI that follows the Genbank format and write it out. 
The DBLINK record seems to change the entries from having a space after the colon to not having a space. Some parsers seem to not like that.

Input:
```
DBLINK      BioProject: PRJNA168
            Assembly: GCF_000001405.33
```

Output:

```
DBLINK      BioProject:PRJNA168
            Assembly:GCF_000001405.33
```

Here is the code I used to check the formatting.

```
>>> import Bio
>>> Bio.__version__
'1.68'
>>> from Bio import SeqIO
>>> f = SeqIO.parse("sequence_io_test.gb", "genbank")
>>> records_out = []
>>> for record in f:
...     records_out.append(record)
...
>>> outhandle = open("sequence_io_test_output_168.gb","w")
>>> SeqIO.write(records_out,outhandle,"gb")
1
>>> outhandle.close()
```
Attaching zip file of input and output below.
Thanks

[Archive.zip](https://github.com/biopython/biopython/files/589823/Archive.zip)

**Comment by peterjc** [comment]
Hmm. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3245039/ gives examples with no spaces, as did the release 170 annoucment https://www.ncbi.nlm.nih.gov/genbank/release/170/

I suspect the NCBI has been inconsistent here, and/or changed the format slightly since.

Can you give some specific NCBI examples you are looking at?

**Comment by harijay** [comment]
Hi Peter,
I got this file from NCBI using the Genbank page
Search for Gene : HBB HUMAN
Click on Genbank link

On the Send dropdown at https://www.ncbi.nlm.nih.gov/nuccore/NC_000011.10?report=genbank&from=5225466&to=5227071&strand=true :
Click on "Complete Record"  then "File" , Format: "genbank" , Show GI : check box.

That one has the space and is included in the Archive.zip

Hari

![image](https://cloud.githubusercontent.com/assets/11098/20282651/abf2ce36-aa83-11e6-9b6b-3a51991bb3fd.png)
![image](https://cloud.githubusercontent.com/assets/11098/20282683/c9102d1a-aa83-11e6-92fe-6addcb0fa136.png)

**Comment by peterjc** [comment]
I checked a sample of the current files from the NCBI GenBank FTP site which all seemed to use the space version:

ftp://ftp.ncbi.nlm.nih.gov/genbank/gbbct1.seq.gz

```
$ zcat gbbct1.seq.gz | grep DBLINK
DBLINK      BioProject: PRJNA226
DBLINK      BioProject: PRJNA226
DBLINK      BioProject: PRJNA15630
DBLINK      BioProject: PRJNA274
DBLINK      BioProject: PRJNA17933
DBLINK      BioProject: PRJNA17931
```

ftp://ftp.ncbi.nlm.nih.gov/genbank/gbvrt50.seq.gz

```
$ zcat gbvrt50.seq.gz | grep DBLINK | head
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
DBLINK      BioProject: PRJEB6383
```

ftp://ftp.ncbi.nlm.nih.gov/genbank/gbtsa110.seq.gz

```
$ zcat gbtsa110.seq.gz | grep DBLINK | head
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
DBLINK      BioProject: PRJNA80349
```

**Comment by peterjc** [comment]
This fix has been applied to the master branch and will be part of the next release. If you need it now, either install Biopython from github or you could apply the small code change to Bio/SeqIO/InsdcIO.py by hand?

Thanks for letting us know about this.

P.S. If anyone finds an official announcement from the NCBI about this apparently deliberate change to the DBLINK formatting, please do comment here. Thanks!

**Comment by peterjc** [comment]
I've tried (and BCC'd you), but I don't think I have any personal contacts in this part of the NCBI so have email the main information address.

**Comment by bachev** [comment]
> On 28 February 2017 at 11:33 Peter Cock <notifications@github.com> wrote:
> I've tried (and BCC'd you), but I don't think I have any personal contacts in this part of the NCBI 
> so have email the main information address.

Seen it, thank you.

There was just a small error in your mail, there was a "not" too many. It should have read:

"However, current real files from the FTP site do have spaces after"

Regarding NCBI mail address: I usually go via their "Write to the Help Desk" link at the bottom of the main NCBI landing page. You need then one more click but then land in a window which apparently sends something to a NCBI ticketing system. It's a bit of a pain, then again I can understand NCBI a bit there.

Bastien

**Comment by peterjc** [comment]
This was assigned NCBI ticket ID #28045-174281, and in their reply they pointed me at a newer article https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3531190/ which gives examples with spaces, but this is far from explicit.
